### ISSUE TITLE
 Copying compiler file python36.dll failed.Ensure the PORTAL 2 is not running.

### ISSUE THREAD

**Issue by Madenn** [BEEmod/BEE2.4#1002]
Can not find a solution to this problem for a very long time.

**Comment by HugoBDesigner** [comment]
Have you tried closing Portal 2 before exporting?

**Comment by HugoBDesigner** [comment]
Try double-checking the process isn't still running in task manager. Sometimes, the Portal2.exe process still lurks there.

**Comment by Madenn** [comment]
No i just checked  :/

**Comment by Madenn** [comment]
please help

**Comment by TeamSpen210** [comment]
Is this still an issue?
