### ISSUE TITLE
Tractor Beam doesn't resolve activation and polarity controls separately in certain styles.

### ISSUE THREAD

**Issue by fosley** [BEEmod/BEE2.4#1004]
<p><b>Observations:</b></p>
<p>I just started using BEEMOD 2.4.0pr30 for Portal 2, and I've found what appears to be a bug. As the title says, the issue is with the Tractor Beam object, and the issue only occurs when using certain thematic styles.</p>

<p>It seems that the tractor beam assets used in specific styles are incorrectly ANDing all inputs of any type to the "Change active state" input, rather than treating "Change active state" and "Change polarity" as different sets of inputs.</p>

<p>I've tried different settings, such as switching between Bendy and Chell, changing the palette back to "Portal 2", and having my cat give the game a Stare of Death®, but the only setting that seems to affect this behavior is the style.</p>

<p><b>Bugged Styles:</b></p>
<ol>
 <li>Overgrown</li>
 <li>Portal 1</li>
 <li>1950s Old Aperture</li>
 <li>1960s Old Aperture</li>
 <li>1970s Old Aperture</li>
</ol>
<p>(1950/1960 appear to use the same asset. Overgrown, Portal 1, and 1970 each uses its own asset.)</p>

<p><b>Working Styles:</b></p>
<ol>
 <li>Behind the Scenes</li>
 <li>Clean</li>
 <li>Original Clean</li>
 <li>1980s Old Aperture</li>
</ol>
<p>(These all appear to use the same asset.)<p>

<p><b>To replicate:</b></p>
<ol>
 <li>Use BEEMOD to set the style to Overgrown.</li>
 <li>Export and launch Portal 2.</li>
 <li>Create a new test chamber using the in-game editor.</li>
 <li>Add a tractor beam to the level.</li>
 <li>Add two pedestal buttons to the level. Set both of them to 5-second timers.</li>
 <li>Connect the first pedestal button to the tractor beam, selecting "Change active state".</li>
 <li>Connect the second pedestal button to the tractor beam, selecting "Change polarity".</li>
 <li>Start the level and press just the first pedestal button. Nothing happens.</li>
 <li>Press just the second pedestal button. Nothing happens.</li>
 <li>Press both buttons within the 5-second timer. The tractor beam activates blue.</li>
</ol>

<p><b>To see the correct behavior:</b></p>
<ol start="11">
 <li>Save the test chamber from above, then close the game.</li>
 <li>Use BEEMOD to change the style to Clean.</li>
 <li>Export and relaunch Portal 2.</li>
 <li>Open the test chamber saved above, then start the level.</li>
 <li>Press just the first button. The tractor beam activates blue.</li>
 <li>Press just the second button. Nothing happens.</li>
 <li>Press both buttons within the 5-second timer. The tractor beam activates blue with the first button, then reverses to orange with the second button (or just activates to orange if you press in the opposite order).</li>
</ol>

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.

For being the first time, i moved your issue to the item´s page, just for you: 
https://github.com/BEEmod/BEE2-items/issues/2837
