### ISSUE TITLE
Beemod causes "Failure To Compile"

### ISSUE THREAD

**Issue by richter24** [BEEmod/BEE2.4#1005]
This appears in the console when I compiled the map:

VBSP failed.
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 20, in <module>
zipimport.ZipImportError: not a Zip file

please help!!

**Comment by richter24** [comment]
Please someone tell me How can I fix it?

**Comment by LautaroL20** [comment]
Follow all the instructions step by step on this link and then see if it fixes your issue: https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod

If we do not get a response from the author in the upcoming days, this issue will be closed.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
