### ISSUE TITLE
Infinite time to load the map

### ISSUE THREAD

**Issue by Tekameikite** [BEEmod/BEE2.4#1011]
![20181027151049_1](https://user-images.githubusercontent.com/9355902/47604525-6340a600-d9fb-11e8-8cad-e7d5a547781c.jpg)

 Network: IP xxx.xxx.xxx, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: F:\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Failed to init 'maps/soundcache/_master_polish.cache'
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: lock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: unlock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Force
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198255083536\1538846405.p2c
Unknown command "cl_puzzlemaker_activate"
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198255083536\1538846405.p2c
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP xxx.xxx.xxx, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2476 )
Opened Steam Socket NS_CLIENT ( socket 2468 )
Network: IP xxx.xxx.xxx, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1538846405/c-2400_0_0.hdr' -- Trying non HDR 'maps\1538846405/c-2400_0_0'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1538846405/c-2000_2000_-48.hdr' -- Trying non HDR 'maps\1538846405/c-2000_2000_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1538846405/c-2032_-1968_-31.hdr' -- Trying non HDR 'maps\1538846405/c-2032_-1968_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\76561198255083536\1538846405
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd34-cube_addon_*, which point_template cd34-cube_template is specifying.
PrecacheScriptSound 'music.puzzlemaker\76561198255083536\1538846405_tbout' failed, no such sound script entry
Commentary: Could not find commentary data file 'maps/puzzlemaker\76561198255083536\1538846405_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
   VAC secure mode is activated.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198255083536\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF F:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,25,10)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 336 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 37706 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 38977 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198255083536\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 103516 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 104043 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
Host_EndGame: Map coordinate extents are too large!!
Check for errors!

Server connection timed out.
Didn't find Active Steam Controller to Load Menu Controls

**Comment by Tekameikite** [comment]
bump

**Comment by Tekameikite** [comment]
After reinstalling BEEmod it's still the same.

**Comment by Tekameikite** [comment]
After updating to release 31 it's the same

**Comment by TeamSpen210** [comment]
`Host_EndGame: Map coordinate extents are too large!!`

This implies something fairly seriously wrong has gone on with some object. I can't tell which from that.

**Comment by TeamSpen210** [comment]
I can't tell anything from this, other than something's seriously wrong with the map. Any more information about it? What's in your map....

**Comment by Tekameikite** [comment]
I was going to list all the items that I have in my map but I managed to fix the issue myself. Basically I just deleted these cutout tiles that were on the "upper part" (idk how to call it) and it was magically fixed (see the screenshot below)

![Uploading 20181122134125_1.png…]()

Sometimes it's worth thinking a little. Thanks for helping me and I'm sorry for wasting your time xdd
