### ISSUE TITLE
sendificator doesn't work in Ovegrown style

### ISSUE THREAD

**Issue by teawithlemons** [BEEmod/BEE2.4#1012]
When i press the button in order to send a cube to the end of the laser nothing happens, i think it's probably just me using it wrong.

**Comment by LautaroL20** [comment]
Thank you for reporting the issue, however you are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.
For being the first time, i moved your issue to the correct section just for you, here: https://github.com/BEEmod/BEE2-items/issues/2851

**Comment by LautaroL20** [comment]
@teawithlemons - This has been fixed in PRL31, download it when you can.
