### ISSUE TITLE
lol bee2 couldn't find an item pls help

### ISSUE THREAD

**Issue by MERNY** [BEEmod/BEE2.4#1013]
Idk if the problem is occurring because I have overwritten content, but idk.
Here's the error message: Could not open instance file instances/BEE2/logic/bee/trigger_multiple.vmf

**Comment by MERNY** [comment]
I have 2 trigger multiples in my level and idk

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
