### ISSUE TITLE
Map is Fullbright

### ISSUE THREAD

**Issue by Portal2027** [BEEmod/BEE2.4#1018]
Whenever I make a map with beemod(The vanilla PeTi editor works fine), it starts in fullbright. I've tried a lot of things. I havn't deleted the observation room, I put some light strips, but this still happens.
EDIT: This is on Pre-Release 31, and was also on Pre-Release 30, before I switched over.
From the console:

Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Users/Ryley/Desktop/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198355738780\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Users/Ryley/Desktop/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198355738780\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Users/Ryley/Desktop/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (3,6,7)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 52 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 7868 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 8085 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 16853 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 17344 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
*

**Comment by Overwatch-C-17** [comment]
Try uninstalling BEE Mod from your P2, after that verify P2 game files from Steam

**Comment by Portal2027** [comment]
> 
> 
> Try uninstalling BEE Mod from your P2, after that verify P2 game files from Steam

When I try to uninstall I get a huge error that I can't copy, so I can't post it here.

**Comment by Portal2027** [comment]
What are the BEE related files in bin?

**Comment by Portal2027** [comment]
> 
> 
> Try to manually delete BEE related files and folders then verify game files:
> 
>     * steamapps\common\Portal 2\bee2
> 
>     * steamapps\common\Portal 2\bin (There are some BEE files here)
> 
>     * steamapps\common\Portal 2\bin\bee2
> 
>     * steamapps\common\Portal 2\sdk_content\maps\instances\bee2

What are the BEE related files in bin?

**Comment by Overwatch-C-17** [comment]
vbsp.exe and vrad.exe with BEE Mod 2 icon and files with .pyd extension

**Comment by Portal2027** [comment]
> 
> 
> vbsp.exe and vrad.exe with BEE Mod 2 icon and files with .pyd extension

I don't have a vrad.exe. I have a vrad_original.exe though. Do I delete that?

**Comment by Overwatch-C-17** [comment]
no, don't delete the original. Rename back to vrad,exe. If you found more just remove the "_original" name. After done manual deletion, verify game files then re-install BEE Mod

**Comment by Portal2027** [comment]
> 
> 
> no, don't delete the original. Rename back to vrad,exe. If you found more just remove the "_original" name. After done manual deletion, verify game files then re-install BEE Mod

I don't have permission to rename vrad_original.exe. (Yes I am an administrator)

**Comment by Overwatch-C-17** [comment]
I guess there's a program accessing that file, probably antivirus. Try to turn it off and try again

**Comment by Portal2027** [comment]
That fixed it. I validated the game files and it fixed the fullbright problem. Thank you.
