### ISSUE TITLE
Suggestions/Corrections: Custom Themes & Items

### ISSUE THREAD

**Issue by FailureSnowy** [BEEmod/BEE2.4#1019]
A new suggestion/correction stream to take a gander at. List:
1. Allow for custom themes (Like there was the ability to in BeeMod 2.2.5 Alpha [Version I used])
2. Allow for custom items to be made and implemented, with an example .vmf file with a .txt file with it to help explain each part of the file.
3. Fixing the BTS Entry and Exit Halls. I have noticed world_portals not work and show what they're supposed to (Includes exit and entry test chamber doors, and probably the door items), and sometimes entire exit hallways disappear, making it impossible to fully, 100% complete the chamber and get to the chamber voting page without noclip. 
4. For overgrown testing styled tracks, add an item or two that can allow for "natural" (sun) lighting, like a ceiling item or wall item. Just an idea, but it makes the chamber so much better looking. (I have proven as such).
5. For BTS tests, if an antline goes over a pit of goo (textured with bottomless pit), allow the antline to travel on top of brushes, of which are on top of vactubes (To see what I mean, look at the puzzle "Spherical Testing: Part 2"). I think it's a nice addition to the BTS theme.
6. Add more and different halls for most every theme. (Excludes all Old Aperture themes, to a point. You can make different catwalk placement ideas and such forth.) Most of the ones we see now on the Workshop are overused, though still nice. 
7. Add a default editoritems,txt ("editoritems_original.txt"), as so that if we still want BeeMOD installed, but the default script, we can have it. Then again, this is optional. Up to you about this one.
8. Add compatibility to Portal 2 mods like Thinking With Time Machine, that overwrite original models. (Like, for example, have a system where the exit to the entry elevator fits into place with the entry test chamber door, and the entrance to the exit elevator to the exit test chamber door, so no world_portals)
9. Bring back some of the old BeeMOD 2.2.5 Alpha items to the new versions of BeeMOD. Some of them were great, but were removed for an unknown reason.
10. Thanks for managing to read that, and I'm sorry if it's similar to other posts, but I thought I'd put it out there about the BTS exit and entry halls and world_portal doors, as they are extremely broken and require fixing. Number 8 is an obviously optional item, but would do great with many people who love TWTM and BeeMOD items. For the overgrown detail items, you can combine mulitple with the cubetype property in the editoritems.txt. it gives you 5 options to choose from, unlike the button type, which only gives you three, Two more options to play with. Again, all of this, besides bug reports, are suggestions, and would make my day if implemented. I know you guys already have a system in development for overgrown chambers for adding plants and such into chambers, but the overgrown detail items would be a nice placeholder until this system is implemented. 

Cheers!
~FailureSnowy

**Comment by TeamSpen210** [comment]
For 1 and 2, that's literally the entire point of BEE2.4 and the packages. It's explicitly designed to allow you to make new ones, which add whatever themes and items you want. For the stuff about BTS, it's because I haven't designed/made those corridors. Antlines can't go across goo. For 7, you probably misunderstand. BEE2.4 is not just merely the editoritems script. It's a lot of complex interworking modifications, to get the "default script" you basically need to uninstall it. For 9, which items?

**Comment by FailureSnowy** [comment]
Response to sentence one & two: Where can I find a post that shows a basic idea of how to create new themes, like changing the white panel texture to something that is not default in BEE2.4? Cause I'm really interested. 
Response to sentence four: Sorry, I didn't elaborate on that too much. If the goo/bottomless pit is one unit down in PTI (128 units in hammer), then a vactube line would be generated. If you really want to understand what I mean by that, then I recommend taking a look at "Spherical Testing: Part 2", which is available in the Portal 2 Workshop (I loved it, so that's why I was asking). It was a neat idea. Plus, it would help clear some antline clutter (Though, a new item would have to be added, an anti-over-goo-tube item, when placed on the side of the ledge, it would go back to vanilla antline placement, around the pit.).
Response to your response about Item 7: what I mean is, BEE2.4 would make a copy of the editoritems.txt that was in your Portal 2/portal2_dlc2/scripts directory, and save it as "editoritems_original.txt (or something similar), as so that we can revert back to complete default, no styles, no custom items. While this is avoidable with the user making a copy of it before hand, noobs don't always do this, and such, get lost.This item was the most optional one.
Response to your question about Item 9: Breakable Glass, Torch (Which would be a good idea in some cases, though I can see why you would NOT add it back, as, from what I have understood, it was barely used), Skybox Items (Useful for placeholder collapsed ceilings in Overgrown Style), and some other items of which I cannot remember. Though, it was mentioned before in another list, and you, or some other BEE2.4 developer, said what items would be left out, added and changed or or re-added, so I have no idea where I was going with Item 9.
To your response about the BTS corridors: If you or someone could fix those, that would be nice. Some tests have a testing use of letting you see through the open door to patterns and what-not, but you can't get into them. With the broken world_portals, this is impossible, as you would only see a dark blue skybox instead of the other side of the door. (The tests using this idea are very low in numbers, which is fine, though I like the idea of it.)

If you would like an idea about what I mean by Item 5, and you don't want to look at that Workshop item, then I can post a picture of it being used in a PTI-similar environment (since my PIT instance-creation skills are VERY limited).

**Comment by FailureSnowy** [comment]
That's a long post, sorry about that. Have a good read, then? Sry...

**Comment by TeamSpen210** [comment]
7 is done already, it does make `editoritems_original.txt`, and restores that. Have a look at this [wiki page](https://github.com/BEEmod/BEE2-items/wiki/Package-Format) for a start, I need to do complete documentation.

**Comment by FailureSnowy** [comment]
Okay, thanks! And thanks for that wiki page. As for the editoritems_original.txt, I was asking because I didn't see it within my directories. I'll delve a bit deeper into it. Really, thanks!

**Comment by DylanKTV** [comment]
I feel as the mod should also have start zones and win zones just if you wanted to create a custom story

**Comment by DylanKTV** [comment]
> That is not something you use PeTi for.

what if you wanted to start your test chamber in a vent instead of a elevator and end it the same way

**Comment by Konclan** [comment]
You use Hammer for something like that...

**Comment by Konclan** [comment]
Most of these have been suggested somewhere else. If there is an idea here that isn't suggested please open another issue and keep it concise and to 1 suggestion at a time
