### ISSUE TITLE
Allow disabling laser bending

### ISSUE THREAD

**Issue by User-505** [BEEmod/BEE2.4#1024]
![portal211_12_201811_57_08pm 2](https://user-images.githubusercontent.com/44939801/48396166-2bb24900-e6df-11e8-99df-e4212c605337.gif)

Discovered it while playtesting, the laser emitter should hit the laser relay and not move but when the blue portal is placed it moves. and not hit the laser relay, making the connections interrupted.

**Comment by ZombiePwner1** [comment]
@User-505 If i'm not wrong that's a bug with the laser itself which we can't fix as it's hard coded into the game. Also your posting in the wrong section.

**Comment by TeamSpen210** [comment]
Not quite, we can turn this on/off. It's very much intentional, lasers bend to hit targets you might have just missed slightly.

**Comment by User-505** [comment]
Any way thanks.
