### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Shood247** [BEEmod/BEE2.4#1025]
Hello, I'll just preface this by saying I won't have an error log to give you but I will explain the symptoms. I'd reinstall bee 2.4 however, if I did from my past experiences in the past 7 days I would have to format my hard drive a 4th time if I wished to play portal 2.

My problem reads a lot like many of the other peoples problems of this nature. Load in add some bee mod items into the editor go to build, build fails, remove bee mod items and open a blank room and still fail to build. Something about my Vbsp being corrupt. So I verify the files which returns absolutely nothing wrong, yet steam gets stuck in an infinite loop cycle where it identifies that vbsp file in bin folder is corrupt but won't update it. Uninstall button is broken, it won't remove the portal 2 files and then I manually delete the folder and clean up anything I can find on portal 2, but this does nothing to remedy the situation. So I format since I've been meaning to for a long time and reinstall a fresh portal 2, follow the instructions but forget to disable avg which says this is harmful yadada, but add it to exceptions and everything looks like it is working fine. I manage to build the basic map I made but it was only possible one time. Trying to build again results in a failed build error. This time I try to uninstall beemod from portal 2 but it tells me some file is missing on drive F... I dont even have a drive F, so I go on to verifying files and you guessed it, no corrupt files found, but steam still decides to get stuck in an infinite validation loop after it returns nothing wrong. Go to run the game and same message about vbsp.exe in portal2/bin is corrupt. So I ask my friend to send me his vbsp files in the bin folder. Now I go to transfer these. Asks for admin permission, give the permission it starts sending the files over but then at 99% it tells me you do not have permissions to modify these files. So I open the folders settings, and give every option full permissions on this folder, yet nothing happens. Format again do same steps but this time add portal 2 directory to exceptions and beemod folder with the latest version and same thing happens. Build once, then build error forever. So format again...

I think this is what is happening. Something goes wrong in my steam folder where its unable to update the files that bee mod modifies sufficiently. Things work for only 1 build then everything goes to shit. Once this corruption occurs the files get locked somehow resulting in no admin privileges being enough and the files cannot be rewritten. I tried some quick fixes I found on google but none of them let me move these files into the folder. I un ticked read only and gave all users permissions but none of this worked for me. So I reformatted for the 3rd time that day. I'm hesitant to reinstall bee mod if all I'm going to do is make the same mistakes again but if anyone can help me out that'd be much appreciated as I have found myself greatly enjoying making maps for friends and wish to branch out into more complicated builds.

**Comment by titchdownunder** [comment]
I had simmiler problems but solved by checking avast internet - and it was deleting the vbsp etc. but I created a exception in firewall solved
Also make sure your user has FULL control of sub-directory's

**Comment by DylanKTV** [comment]
I'm having the same problem but don't exactly how to solve them

**Comment by titchdownunder** [comment]
I have reverted to bee2 - 29 as 31 seems to have MORE bugs ?

**Comment by TeamSpen210** [comment]
I can't solve crashes without any information. The log files are critical.

**Comment by LautaroL20** [comment]
@Shood247 - Open the Portal 2´s developer console, type developer 2 and build the chamber, once you got the building error, copy and paste it here and the issue will be re open. However, since it is more likely that i will become Spiderman rather than the author´s post will get back to this, i am just wasting my time at writting this.
