### ISSUE TITLE
Monitor aint Working

### ISSUE THREAD

**Issue by OceanWaves999** [BEEmod/BEE2.4#1027]
So i'm using glados as my voiceline and I wanted her to appear in my monitor. but the screen was just black. I used noclip to see any bugs behind the monitor. and I found her in a room out of the map. but no glados on the monitor.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.

For being the first time, ive moved your issue just for you to the correct place: https://github.com/BEEmod/BEE2-items/issues/2865

**Comment by TeamSpen210** [comment]
@LautaroL20, you might not have seen the button since you need admin permission to use it but GitHub now has an issue transfer feature, which lets us move the issue to other repos.

**Comment by LautaroL20** [comment]
@TeamSpen210 - It seems that the button you´re mentioning, is not visible for me. Where do i find the respective button which allows me to do the transferring?

**Comment by TeamSpen210** [comment]
It seems it's only available for me, so just leave the issues for me to move.

**Comment by LautaroL20** [comment]
Alright, then for issues posted in wrong repros, ill just close them with my premade message and the issue transfering its now in your hands or in the author´s post.
