### ISSUE TITLE
Compiling Error - Python36 cannot be copied

### ISSUE THREAD

**Issue by Vunter-Slaush** [BEEmod/BEE2.4#1028]
I feel like this error has been haunting me.

First of all, no I do not have Portal 2 running. I've shutdown steam and restarted but that still won't fix it. I've tried reinstalling 3 times, even messed with administrator privileges in order to get Beemod to copy this damn file.

Is this error message from hell fixable or do I have to wait for the next version of the Mod?

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
