### ISSUE TITLE
items/props

### ISSUE THREAD

**Issue by DylanKTV** [BEEmod/BEE2.4#1029]
I feel as bee2 should have a prop item for those people making bts maps. Maybe the prop item would work like the sign item, you choose a number and it will change the prop from desks,chairs,etc and you get to change the direction of the prop.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.
