### ISSUE TITLE
Relating to the Splash Screen photos.

### ISSUE THREAD

**Issue by TheLoafLord** [BEEmod/BEE2.4#1031]
Are the photos actually based on real levels? They look fun to play.

**Comment by TheLoafLord** [comment]
More specifically, the "abandoned testing track" photo.

**Comment by TeamSpen210** [comment]
Most of them are not, they're just made for the  screenshots.

**Comment by LautaroL20** [comment]
This is not a "suggestion"... it would require a question label, but invalid seems more accurate.
