### ISSUE TITLE
Previewing music crashes BEE2.4

### ISSUE THREAD

**Issue by Overwatch-C-17** [BEEmod/BEE2.4#1035]
![Crash](https://user-images.githubusercontent.com/12244376/49743689-14cd2b00-fc7a-11e8-9ea4-356146546cb5.png)

**Comment by LautaroL20** [comment]
Which music were you trying to test?

**Comment by Overwatch-C-17** [comment]
I was testing two music. First I test Bouncy Gel music, then BEE crash. Second I try it again but this one is chamber music Self Esteem Fund, BEE crash again.

**Comment by LautaroL20** [comment]
It doesn´t matter which song do you test, it will make the entire bee´s interface crash. All existing songs of beemod causes it.

**Comment by Overwatch-C-17** [comment]
Yes true

**Comment by LautaroL20** [comment]
Yes, the option seems to be available for all the Bee´s members which is good. This issue should be pinned indeed.

**Comment by QuentinMarical** [comment]
Same problem

---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\sound.py", line 200, in play_sample
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1429, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1405, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 238, in __init__
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 196, in f
OSError: exception: access violation reading 0x00000000

**Comment by mgperkow** [comment]
I got this one, too. Exactly the same error message and traceback as the others who reported it here.

**Comment by arminelec** [comment]
I have the same issue on **4.33.1**. With the same [incorrect] file path references. I chose to comment here, even though this ticket says 4.32.x (since the other duplicates are closed).

**Comment by LautaroL20** [comment]
> arminelec said: "even though this ticket says 4.32.x"

That is why i don´t like putting a number version in the title, since it can lend to confusion... Since even the latest release has this same issue.

**Comment by Endermage77** [comment]
Can also confirm I have same porblemo

**Comment by iTom33ro** [comment]
But how to solve this problem, because i have same crash

**Comment by LautaroL20** [comment]
You will have this issue fixed when the Pre-Release 34 comes out.

**Comment by LautaroL20** [comment]
You can not fix it by yourself since the file `sound.py` does not exists in the public releases, otherwise you could edit it easily with notepad++ based on this commit: https://github.com/BEEmod/BEE2.4/commit/e1ee453f18808f38a5a4c705a936aa2000b1245f. However, you will have this issue fixed when the Pre-Release 34 comes out.

**Comment by TeamSpen210** [comment]
Actually you can just copy that .py file into the bin folder, and it'll override the zipped one.

**Comment by LautaroL20** [comment]
Interesting. Go ahead everyone!

**Comment by iTom33ro** [comment]
which .py file?

**Comment by DrMeepster** [comment]
> Actually you can just copy that .py file into the bin folder, and it'll override the zipped one.

This works! Thanks for the temporary solution until 34 comes out.

**Comment by LautaroL20** [comment]
Pre-Release 34 Has now been released! Download links below:

Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.0
Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
