### ISSUE TITLE
Whenver I export a file, the entire interface crashes and bee2 deletes a crap ton of important bee2 files. Using PR32.

### ISSUE THREAD

**Issue by Entity447** [BEEmod/BEE2.4#1038]

**Comment by Entity447** [comment]
WHOOPS. Forgot all the important stuff. Whenever I export a palette to the editor, Bee2 crashes. I looked in the logs and found this:



[INFO] gameMan.export(): Copying Resources!
[INFO] gameMan.refresh_cache(): Cache copied.
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\50s\items\panel_half.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\clean\elevator_sp\elevator_arrival_logic.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\clean\elevator_sp\elevator_entrance.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\clean\items\panel_half.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\over\items\panel_half.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\p1\items\faith_plate.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\p1\items\panel_half_var1.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\instances\bee2\p1\items\panel_half_var2.vmf
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\bee2\bee2.fgd
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\bee2\bee2.ico
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\bee2\readme.txt
[INFO] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\bee2\bin\avbin.dll
[INFO] BEE2_config.save(): Saving changes in config "C:\Users\Marc\AppData\Roaming\BEEMOD2\config\config.cfg"!
[ERROR] tk_tools.tk_error(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 851, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 789, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 534, in refresh_cache
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bee2\\bin\\avbin.dll'

**Comment by Entity447** [comment]
And when you read the bottom few lines, keep in mind that I am the admin of my pc.

**Comment by LautaroL20** [comment]
> Entity447 Said: bee2 deletes a crap ton of important bee2 files. 

We are facing an authentic case of cannibalism!

**Comment by TeamSpen210** [comment]
Did you install BEE2 into your portal 2 folder or something?

**Comment by TeamSpen210** [comment]
It shouldn't go there, it expects its own installation folder. It will copy the correct files itself. In your error log, it detects files that shouldn't be there and tries to delete them, but fails since it's using them at the same time.

**Comment by Entity447** [comment]
OH, so I would put bee2 in a folder on my desktop then?

**Comment by TeamSpen210** [comment]
Yes.

**Comment by Entity447** [comment]
I fixed the problem, but now it doesn;t uild my chamber

**Comment by Entity447** [comment]
I fixed it, thanks for the help!
