### ISSUE TITLE
Suggestion for overgrown style

### ISSUE THREAD

**Issue by RGBACatlord** [BEEmod/BEE2.4#1043]
1. Pure white light surface, like in some test chambers with missing ceiling panels.
2. Props you can place. e.g. rubble, plants, etc
3. Placeable decals like dirt or whatever

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
