### ISSUE TITLE
Compiling bug

### ISSUE THREAD

**Issue by StartingByP** [BEEmod/BEE2.4#1046]
Hello again, this time I have another type of error I had a few days. I tried to make a BTS map, but when I compiled, some parts of the entrance are bugged, and the entrance room to the map is changed by the one from the Clean style. Here are some screenshots for more details
![screenshot1](https://user-images.githubusercontent.com/38363639/50493514-569df580-0a1e-11e9-950e-de57da4cc77d.PNG) 
:
1. Here, the window is glitched.
![screenshot2](https://user-images.githubusercontent.com/38363639/50493543-7fbe8600-0a1e-11e9-8d28-d25dc95d5169.PNG)
2. And here, like I said before, the map entrance is completely changed.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
