### ISSUE TITLE
Duplicated option in the "Palette" menu context: <Last Export> <Last Export>

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1048]
![bug](https://user-images.githubusercontent.com/35931028/50528947-17dd6d80-0afa-11e9-86d2-3b4f253abd65.png)

**Comment by ZombiePwner1** [comment]
https://github.com/BEEmod/BEE2-items/issues/2884 Wheels nice duplicate.

**Comment by LautaroL20** [comment]
Wheels, this is the correct place to report bugs related to the interface, the original post is posted in the wrong section.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Wheels I know that but you should've moved the original post properly lmao.

**Comment by Luke18033** [comment]
Only organization admins can use the built in option, although there are older alternatives like the [GitHub Issue Mover](https://github-issue-mover.appspot.com), or you could have just waited for TeamSpen to do it.

**Comment by LautaroL20** [comment]
THe GitHub Issue Mover is kinda uncomfortable for me at least, and since there is now a moving issue button there are more reasons for not using that application. I wish i had the moving button tho...
