### ISSUE TITLE
I cannot open the Bee2.exe file under Bin.

### ISSUE THREAD

**Issue by epicduck64** [BEEmod/BEE2.4#1050]
I was downloading the bee2 zip file, and freshly installed, I ran bee2.exe under Bin, and it gave me an error.
The error states that the application was unable to start, but gives no details.
The application was unable to start correctly (0xc000007b). Click OK to close the application.
I am running Windows 7 x64 freshly installed like 4 days ago. I don't understand whats going on. Portal 2 is also freshly installed. My specs are an i5 with an AMD Radeon 240. If my pc has any problems with running it, then please tell me.

I can stick to hammer for right now, but having this work would help me out alot.
Thanks!

Need more information? Comment below.

**Comment by epicduck64** [comment]
Also, I believe that there could be a compatibility problem with Windows 7, could someone confirm its compatible with the operating system?

**Comment by ZombiePwner1** [comment]
@epicduck64 There is no compatibility problem. @LautaroL20 Uses window 7 and bee2 runs fine. It's a issue on your end.

**Comment by epicduck64** [comment]
Thanks.

**Comment by epicduck64** [comment]
I'll try installing Windows 7 SP2 and see if it works.

**Comment by epicduck64** [comment]
@TeamSpen210 Can you check up on this for me? Or somebody else who could help me greatly?

**Comment by epicduck64** [comment]
![problembee2](https://user-images.githubusercontent.com/39019028/50689953-816ce880-0fe0-11e9-8bbe-5f4b0613b999.png)

**Comment by epicduck64** [comment]
A windows technician believes the compatibility is a problem here.

**Comment by LautaroL20** [comment]
Disabling the compatibility mode, it is not required at all.

**Comment by epicduck64** [comment]
When I check compatibility issues, it says Unsupported program, could this be why?

**Comment by LautaroL20** [comment]
I am using Windows 7 64 bit professional SP2 and all the beemod versions works like a charm, so idk why it does not work for you.

**Comment by LautaroL20** [comment]
I do not like windows 8, and 10 at all.

**Comment by epicduck64** [comment]
I am using a 64 bit system, but realized that my system is SP1. Im going to do a upgrade so that I can get SP2 working, and upgraded to my computer. I am also running professional, so I will give an update how everything goes.
![capture2](https://user-images.githubusercontent.com/39019028/50736014-29fb8380-116c-11e9-86dc-309d64c7ead2.PNG)

**Comment by epicduck64** [comment]
I upgraded to SP2 and still have the problem. Any suggestions?
Also, when I upgraded, it now shows the compatibility mode for Windows 7.

**Comment by epicduck64** [comment]
![windows7compatible](https://user-images.githubusercontent.com/39019028/50737980-b7969d80-1183-11e9-9c3f-8de800ba3601.jpg)

**Comment by epicduck64** [comment]
It was fixed, as I needed to install runtimes and C++ files for it to work.
Thanks for all the people to attempted to help me. Heres an image of some of the files I installed to fix it:
![fixedruntimes](https://user-images.githubusercontent.com/39019028/50738126-959e1a80-1185-11e9-8ae5-3b6a2448cb62.PNG)
