### ISSUE TITLE
BEE4.33.1 Will crash after loading... "Invalid index "1" when modifying editoritems for <ITEM_LIGHT_PANEL:VER_DEFAULT.BEE2_BTS>

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1055]
![BEE4.33.1](https://user-images.githubusercontent.com/12244376/51067160-3bbaac00-15ee-11e9-8a52-892da6953b11.png)

**Comment by PieCreeper12** [comment]
I have the same issue.

**Comment by LautaroL20** [comment]
The issue that causes this issue seems to be located at the latest version of the item´s packages.

**Comment by gerleig** [comment]
Having the same issue :(

**Comment by LautaroL20** [comment]
@PieCreeper12 @gerleig - The download was updated with a working version, now you can dowload it again and the issue should not happen anymore, link: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.33.1
