### ISSUE TITLE
Can't build testchamber... First time user.

### ISSUE THREAD

**Issue by ChazizYT** [BEEmod/BEE2.4#1058]
I'm currently in a roadblock. I can't even build a testchamber. It has problems with the "VBSP".

```
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (5,8,7)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 185 (ms)

VBSP failed.
```

Also... I installed Beemod with the instructions on github... So it should worked fine... But nope...

**Comment by LautaroL20** [comment]
Is this really your very first time at using any existing version of beemod?

**Comment by ChazizYT** [comment]
Yes... I've recently bought Portal 2 back during the Winter Sale.

**Comment by LautaroL20** [comment]
The console log is incomplete. Open the console and writte on it: `developer 2` and then compile the chamber and once you get the failure to compile, paste the full console message here.

**Comment by ChazizYT** [comment]
nah i think that it requires rebooting.
