### ISSUE TITLE
BEE2 does not let you select the voicelines that are played.

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1059]
So, BEE2 has a feature where you can select which voicelines are played by checking and unchecking the boxes next to the voicelines. However, this does not work. The voicelines that are played are always automatically selected instead of the ones you select. BEE2 picks the correct character to say a voiceline but not the correct voiceline from them.

**Comment by arminelec** [comment]
I encounter the same issue in 4.33.1.

**Comment by TeamSpen210** [comment]
Must have broken this with the palette settings upgrade.

**Comment by JavierNovellon** [comment]
Finally! Someone has the same problem as I do! I have v2 4.34.1 and I thought I was going crazy... Well, at least it's a bug. I hope they fix it at some point.
