### ISSUE TITLE
Separate entry doors for cooperative maps

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1060]
On cooperative maps, both Atlas and P-body enter the test chamber in the room. What if I want the two robots to be separated in two different rooms? I have an idea where if you place two entry doors in a cooperative test chamber, Atlas and P-body will come out from two different rooms.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

However, for being a really interesting suggestion, i will post it for you in the item´s page:  https://github.com/BEEmod/BEE2-items/issues/2893
