### ISSUE TITLE
start up issue

### ISSUE THREAD

**Issue by Slapsfaceonkeyboard** [BEEmod/BEE2.4#1065]
i'm going to keep this short because i'm probably being stupid so here's an error i get when i attempt to start up the game: portal2\GameInfo.txt is not a valid format
i just wanna know how to fix this in a simple way so i can try to fix bigger issues i'm currently seeing

**Comment by Slapsfaceonkeyboard** [comment]
[WARNING] BEE2_config.load(): Config "C:\Users\Megan\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Using defaults...
[WARNING] gameMan.edit_gameinfo(): Failed editing "C:/Program Files (x86)/Steam/steamapps/common/Portal 2\portal2_dlc2\gameinfo.txt" to add our special folder!
[WARNING] gameMan.edit_gameinfo(): Failed editing "C:/Program Files (x86)/Steam/steamapps/common/Portal 2\portal2_dlc1\gameinfo.txt" to add our special folder!
[WARNING] gameMan.edit_gameinfo(): Failed editing "C:/Program Files (x86)/Steam/steamapps/common/Portal 2\portal2\gameinfo.txt" to add our special folder!
[WARNING] packageLoader.parse_item_folder(): "VALVE_GEOMETRY:items/light_strip/editoritems.txt has palette set for extra item blocks. Deleting.
[WARNING] packageLoader.parse(): BEEMOD_1:PACK_UNDER_HOTSURFACE_WORLD: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BEE2_BULLSEYE_BTS_WHITE_FLOOR: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BEE2_BULLSEYE_BTS_UNDER_WHITE_TILE: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BEE2_BULLSEYE_BTS_WHITE_CEIL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BEE2_BULLSEYE_BTS_PLASTICWALL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BEE2_BULLSEYE_BTS_FACTORYFLOOR: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BEE2_BULLSEYE_BTS_BACKPANELS: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_FLOOR_001B: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_SQUAREBEAMS_BTS: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_PETI_PROJECTOR: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_SIGN_BUTTON: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_SIGN_EXIT: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_SIGN_FUNNEL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_SIGN_FUNNEL_POLARITY: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_SIGN_GEL_SPEED: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_BTS:PACK_BTS_SIGN_GEL_BOUNCE: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_CLEAN_STYLE:PACK_CLEAN_DETAIL_WALLS: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_CLEAN_STYLE:PACK_SQUAREBEAMS_SHINY: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_CLEAN_STYLE:PACK_SQUAREBEAMS_NOPAINT: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_CLEAN_STYLE:PACK_BEE2_SHAPE_SIGN_FRAME_CLEAN_1: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_CLEAN_STYLE:PACK_BEE2_SHAPE_SIGN_FRAME_CLEAN_2: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_BULLSEYE_RETRO_WOOD_WHITE: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_BULLSEYE_RETRO_50S_BLACK: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_BULLSEYE_RETRO_70S_BLACK: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_BULLSEYE_RETRO_80S_BLACK: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_BULLSEYE_RETRO_80S_DECAL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE_WOODWALL_003C: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE_RETRO_INDICATOR_LIGHT: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BRUSH_BOUNCE: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_RETRO_BLUE_ARROW: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_TURRET: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50S_GOO: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_LBRIDGE: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_SPEED_GEL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_LASER_RELAY: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_LASER_CUBE: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_FUNNEL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_FUNNEL_POLARITY: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_BOX_DROPPER: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_SIGN_50s_BALL_DROPPER: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_SHAPE_SIGN_FRAME_RETRO_1: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_SHAPE_SIGN_FRAME_RETRO_2: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_50S_SHAPE_1: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_50S_SHAPE_2: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_50S_SHAPE_3: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_50S_SHAPE_4: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_NOPAINT_METAL_CORRUGATED: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_NOPAINT_PLYWOOD: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_NOPAINT_SQUAREBEAMS_RUSTY: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_OLD_AP:PACK_BEE2_AP_LOGO: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): HMW_SENDIFICATOR:PACK_HMW_SENDTOR_ANT_CLEAN: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): HMW_SENDIFICATOR:PACK_HMW_SENDTOR_ANT_CLEAN_BROKEN: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): HMW_SENDIFICATOR:PACK_HMW_SENDTOR_ANT_RETRO: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): HMW_SENDIFICATOR:PACK_HMW_SENDTOR_ANT_P1: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_SIGNAGE:BEE2_PACK_SIGNAGE_TURRET: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_SIGNAGE:PACK_BEE2_80S_SIGN_PAINT_JUMP: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): BEE2_SIGNAGE:PACK_BEE2_80S_SIGN_PAINT_SPEED: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): VALVE_TEST_ELEM:PACK_BEE2_BULLSEYE_CLEAN_WHITE_CEIL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): VALVE_TEST_ELEM:PACK_BEE2_BULLSEYE_CLEAN_WHITE_FLOOR: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): VALVE_TEST_ELEM:PACK_BEE2_BULLSEYE_CLEAN_WHITE_WALL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): VALVE_TEST_ELEM:PACK_BEE2_BULLSEYE_CLEAN_WHITE_WALL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): VALVE_TEST_ELEM:PACK_BEE2_BULLSEYE_CLEAN_BLACK_FLOORCEIL: AddIfMat is no longer used.
[WARNING] packageLoader.parse(): PACK_WOM_CONDUCTOR:WOM_CONDUCTOR_OVERLAY: AddIfMat is no longer used.
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PEDESTAL_BASE_BTS_REV" has no config!
[WARNING] packageLoader.__init__(): Template "TSPEN_BTN_PED_CLEAN_BASE" has no config!
[WARNING] packageLoader.__init__(): Template "TSPEN_BTN_PED_P1_BASE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_APTAG_FIZZ_BASE_CLEAN" has no config!
[WARNING] gameMan.edit_gameinfo(): Failed editing "C:/Program Files (x86)/Steam/steamapps/common/Portal 2\portal2_dlc2\gameinfo.txt" to add our special folder!
[WARNING] gameMan.edit_gameinfo(): Failed editing "C:/Program Files (x86)/Steam/steamapps/common/Portal 2\portal2_dlc1\gameinfo.txt" to add our special folder!
[WARNING] gameMan.edit_gameinfo(): Failed editing "C:/Program Files (x86)/Steam/steamapps/common/Portal 2\portal2\gameinfo.txt" to add our special folder!

**Comment by LautaroL20** [comment]
Follow carefully all the steps contained in this link and that should fix your issue: https://github.com/BEEmod/BEE2-items/wiki/Updating-Beemod
