### ISSUE TITLE
VBSP error Bee2 v4.33.1

### ISSUE THREAD

**Issue by Kitsune-Ultima** [BEEmod/BEE2.4#1069]
Long time user haven't had this problem before
Style: Old Aperture 1960s
Voice: Cave Johnson (60s)
Skybox: Sphere Interior
Music: Vit Order #2

Pallet:
> ![bee2 pallet](https://user-images.githubusercontent.com/29787566/51628207-02e1d780-1f0a-11e9-8b8d-52e0f79bcf21.PNG)

Compile settings:
    Thumbnail: Auto
    Lighting: Fast

Developer 2 log:

`] developer 2`
`%USER% unpaused the game`
`[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...`
`[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,22,18)`
`[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 681 (ms)`
`[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198151965609\autosave.p2c`
` `
`VBSP failed.`
` `
`[I] vbsp.main(): BEE2v4.33.0 VBSP hook initiallised.`
`[I] cond.core.import_conditions(): Imported all conditions modules!`
`[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 
2/sdk_content\maps/preview.vmf"`
`[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"`
`[I] vbsp.main(): Clearing inject/ directory..`
`[I] vbsp.main(): PeTI map detected!`
`[I] vbsp.main(): Loading settings...`
`[W] vbsp_options.load(): Extra config options: {'music_location_sp': '-2824 2040 -768', 'voice_pack': 'BEE2_CAVE_60s'}`
`[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})`
`[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})`
`[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.`
`[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!`
`[I] fizzler.read_configs(): Loaded 14 fizzlers.`
`[I] vbsp.load_settings(): Settings Loaded!`
`[I] vbsp.load_map(): Parsing Map...`
`[I] vbsp.load_map(): Reading Map...`
`[I] vbsp.load_map(): Loading complete!`
`[I] vbsp.get_map_info(): Forcing elevator spawn!`
`[I] vbsp.mod_entryexit(): Setting SP Entry to 6`
`[I] vbsp.mod_entryexit(): Setting SP Exit to 4`
`[I] vbsp.get_map_info(): Game Mode: SP`
`[I] vbsp.get_map_info(): Is Preview: False`
`[I] brushLoc.read_from_map(): Analysed map, filling air... (1551 starting positions..)`
`[I] brushLoc.read_from_map(): Air filled!`
`[I] cond.core.check_all(): Checking Conditions...`
`[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']`
`[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})`
`[I] connections.gen_item_outputs(): Generating item IO...`
`[I] connections.add_item_inputs(): LOGIC counter: lg156`
`[I] connections.add_item_inputs(): LOGIC counter: lg165`
`[I] connections.add_item_inputs(): LOGIC counter: lg292`
`[I] connections.add_item_inputs(): LOGIC counter: lg454`
`[I] connections.add_item_inputs(): LOGIC counter: lg475`
`[I] connections.gen_item_outputs(): Item IO generated.`
`[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...`
`[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...`
`[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!`
`[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...`
`[W] packing.pack_list(): Packlist "PACK_RETRO_PIST_PLAT" does not exist!`
`[W] instanceLocs.get_subitems(): Invalid custom instance name - "single" for <item_rail_platform> (Valid: {'static': 'instances/bee2/50s/items/track/static.vmf'})`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.`
`[I] vbsp.set_elev_videos(): Elevator type: NONE`
`[I] voiceLine.add_voice(): Adding Voice Lines!`
`[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...`
`[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...`
`[I] voiceLine.add_voice(): Adding Base instance!`
`[I] voiceLine.add_voice(): Quote events: []`
`[I] voiceLine.add_voice(): No responses data..`
`[I] voiceLine.find_group_quotes(): "BEFORE ENTRY": 1/1 quotes..`
`[I] voiceLine.find_group_quotes(): "ENTRY": 3/4 quotes..`
`[I] voiceLine.add_quote(): Adding quote: "Line_SP"`
` | 	{`
` | 	"ID" "ASBESTOS_SPHERE_SP"`
` | 	"Bullseye" "cave_bomb_flings_entrance"`
` | 	"Choreo" "npc/cavejohnson/misc_tests08.vcd"`
` | 	}`
` | `
` |___`
` `
`[I] voiceLine.find_group_quotes(): "EXIT": 5/7 quotes..`
`[I] voiceLine.add_quote(): Adding quote: "Line"`
` | 	{`
` | 	"ID" "HAPPY_FACE"`
` | 	"Bullseye" "cave_bomb_flings_entrance"`
` | 	"Choreo" "npc/cavejohnson/misc_tests10.vcd"`
` | 	}`
` | `
` |___`
` `
`[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/1 quotes..`
`[I] voiceLine.add_voice(): Using microphones...`
`[I] voiceLine.add_voice(): 1 Mid quotes`
`[I] voiceLine.add_quote(): Adding quote: "Line"`
` | 	{`
` | 	"ID" "CAVE_LOITER"`
` | 	"Quote_Name" "@cave_catwalks"`
` | 	"Bullseye" "cave_crazy_box_2nd_chamber"`
` | 	"Choreo"`
` | 		{`
` | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"`
` | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"`
` | 		}`
` | 	}`
` | `
` |___`
` `
`[I] voiceLine.add_voice(): Done!`
`[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...`
`[I] vbsp.anti_fizz_bump(): Done!`
`[I] vbsp.set_player_portalgun(): Setting Portalgun:`
`[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y`
`[I] vbsp.set_player_portalgun(): Done!`
`[I] cond.core.check_all(): Map has attributes: ['goo', 'fizzler', 'fr_fdf', 'tdb_ff', 'glass', 'grating', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'cubereflect', 'cubedropperreflect', 'cubesphere', 'cubedroppersphere', 'cubesphereshaped', 'funnel', 'excursionfunnel', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'cubebutton', 'ballbutton', 'gel', 'speedgel', 'orangegel', 'bouncegel', 'bluegel', 'geldropper', 'deadly', 'crusher', 'fire', 'flamethrower', 'lasercatcher', 'pedestalbutton', 'bridge', 'hardlight', 'pistonplatform', 'piston', 'panel', 'laseremitter', 'laser', 'spawn_dual']`
`[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=176290, misses=370, maxsize=256, currsize=256)`
`[I] cond.core.check_all(): Style Vars: {'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'retro_voice_pre_line': False}`
`[I] cond.core.check_all(): Global instances: set()`
`[I] vbsp.add_extra_ents(): Adding Music...`
`[I] vbsp.add_extra_ents(): Adding global ents...`
`[I] vbsp.add_extra_ents(): Adding Global PTI Ents`
`[I] vbsp.change_ents(): Editing Other Entities...`
`[I] vbsp.fixup_goo_sides(): Changing goo sides...`
`[I] vbsp.fixup_goo_sides(): Done!`
`[I] vbsp.change_brush(): Editing Brushes...`
`[I] vbsp.change_brush(): Make Bottomless Pit: False`
`[I] vbsp.change_brush(): Goo heights: 480.0 <- Counter({480.0: 86})`
`[I] vbsp.clump_walls(): Clumping: 1900 clumps (+ 3 special)`
`[I] vbsp.change_overlays(): Editing Overlays...`
`[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...`
`[I] vbsp.collapse_goo_trig(): Done!`
`[I] vbsp.change_func_brush(): Editing Brush Entities...`
`[I] vbsp.fix_worldspawn(): Editing WorldSpawn`
`[I] vbsp.save(): Saving New Map...`
`[I] vbsp.save(): Complete!`
`[I] <Valve>.run_compiler(): Calling original VBSP...`
`[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'`
`[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Oct 26 2018)`
`[I] <Valve>.run_compiler(): 16 threads`
`[I] <Valve>.run_compiler(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials`
`[I] <Valve>.run_compiler(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf`
`[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar`

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
