### ISSUE TITLE
Apeture Tag Outside Style

### ISSUE THREAD

**Issue by costellokalani** [BEEmod/BEE2.4#1074]
is it possible to add this? the walls could be the same image every time and the stone and stuff doesnt matter. the goo would be grass with nerotoxing clouds above it like in the game. thanks and love the mod! ![aptagstage](https://user-images.githubusercontent.com/37136576/52517367-b7138a00-2c8e-11e9-808e-8092ccc4f21d.png)

**Comment by ZombiePwner1** [comment]
Already suggested: https://github.com/BEEmod/BEE2-items/issues/1328 Also your posting in the wrong section.
