### ISSUE TITLE
Aperture Tag Portal Gun

### ISSUE THREAD

**Issue by Jadeygaming** [BEEmod/BEE2.4#1079]
When you use Aperture Tag with BEE2 you spawn with a portal gun. Any way to fix this?

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

**Comment by Jadeygaming** [comment]
Sorry, wasn't sure which one this one would fit in... sorry.

**Comment by LautaroL20** [comment]
No problem.
