### ISSUE TITLE
This is a TRITE DUPLICATE!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by DrPipBob** [BEEmod/BEE2.4#1080]
![screen](https://user-images.githubusercontent.com/47915535/53284879-12ec1180-376b-11e9-9ad0-84afe5dca70a.PNG)

**Comment by MeloettaRules28** [comment]
This happens to everyone, they might be able to fix it with the next release/pre-release.

**Comment by DrPipBob** [comment]
Okay, Thanks.

**Comment by MeloettaRules28** [comment]
No problem!

**Comment by LautaroL20** [comment]
This is a TRITE DUPLICATE of: https://github.com/BEEmod/BEE2.4/issues/1035 - The issue is even pinned and no one of you even saw it? Well, i think ill start gifting a pair of glassess to everyone!

**Comment by MeloettaRules28** [comment]
MAN, CALM DOWN
