### ISSUE TITLE
Error compile

### ISSUE THREAD

**Issue by DrPipBob** [BEEmod/BEE2.4#1081]
Dr. Pip Bob unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 96 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 9380 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 9697 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198024254609\autosave.p2c

VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is D:\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.load_config(): Loading Settings...
[I] vrad.load_config(): Config Loaded!
[I] vrad.main(): Final status: is_peti=True, edit_args=False
[I] vrad.main(): Reading BSP
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[I] vrad.main(): Adding special packed files:
[I] vrad.main(): Injecting "scripts/vscripts/BEE2/mon_camera_args.nut" into packfile.
[I] vrad.main(): Run transformations...
[I] bsp_trans.run_transformations(): Running "P2 Coop Trigger"...
[I] bsp_trans.run_transformations(): Running "P2 Goo"...
[I] bsp_trans.run_transformations(): Running "Attachment Points"...
[I] bsp_trans.run_transformations(): Running "VScript Init Code"...
[I] bsp_trans.run_transformations(): Running "VScript RunScriptCode Strings"...
[I] bsp_trans.run_transformations(): Running "Optimise logic_auto"...
[I] bsp_trans.run_transformations(): Running "Fix Laser Catcher Skins"...
[I] bsp_trans.run_transformations(): Running "Force Paint in Map"...
[I] bsp_trans.run_transformations(): Running "Precache P2 Light Bridge"...
[I] bsp_trans.run_transformations(): Running "comp_choreo_sceneset"...
[I] bsp_trans.run_transformations(): Running "Proxy limits"...
[I] bsp_trans.run_transformations(): Running "comp_precache_model"...
[I] bsp_trans.run_transformations(): Running "comp_precache_sound"...
[I] bsp_trans.run_transformations(): Running "comp_pack_replace_soundscript"...
[I] bsp_trans.run_transformations(): Running "comp_pack"...
[I] bsp_trans.run_transformations(): Running "comp_pack_rename"...
[I] vrad.main(): Scanning map for files to pack:
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogMaxDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogStart" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "heightFogDensity" for ent of type "env_fog_controller"!
[W] packlist.pack_fgd(): Unknown keyvalue "startDisabled" for ent of type "prop_dynamic_override"!
[W] packlist.pack_fgd(): Unknown keyvalue "renderinfastreflections" for ent of type "linked_portal_door"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown keyvalue "portalnumber" for ent of type "func_areaportal"!
[W] packlist.pack_fgd(): Unknown class "playtest_manager"!
[W] packlist.pack_fgd(): Unknown keyvalue "parentname" for ent of type "point_teleport"!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "vrad.py", line 861, in <module>
  File "vrad.py", line 790, in main
  File "F:\Git\srctools\srctools\packlist.py", line 633, in eval_dependencies
  File "F:\Git\srctools\srctools\packlist.py", line 720, in _get_material_files
  File "F:\Git\srctools\srctools\packlist.py", line 180, in pack_file
ValueError: No tabs are allowed in filenames ('materials/models\\\\props_bts\truss.vtf')
WARNING: File "materials/maps/preview/nature/water_glados_01_cheap_-2400_0_0.vmt" does not exist!
WARNING: File "materials/maps/preview/metal/factory_metal_floor001a_-1904_2096_-48.vmt" does not exist!
WARNING: File "materials/maps/preview/metal/metaldoor_white01_-1904_2096_-48.vmt" does not exist!
WARNING: File "materials/maps/preview/metal/underground_wall_metal001c_-2400_0_0.vmt" does not exist!
WARNING: File "materials/maps/preview/metal/underground_wall_metal001c_-1904_2096_-48.vmt" does not exist!
WARNING: File "materials/maps/preview/tile/floor_tile_005a_-2400_0_0.vmt" does not exist!
WARNING: File "materials/maps/preview/glass/glasswindow007a_-1904_2096_-48.vmt" does not exist!
WARNING: File "materials/maps/preview/metal/factory_metal_floor001a_-2032_-2032_-31.vmt" does not exist!

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
