### ISSUE TITLE
Floating cubes when on a lightbridge

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2.4#1085]
![image](https://user-images.githubusercontent.com/32681975/53676292-7791f980-3ca0-11e9-993a-34092ac3b694.png)

I'm confused on how this works, Isn't the cube supposed to fall?

Here's the map it's on: https://steamcommunity.com/sharedfiles/filedetails/?id=1669831744 (It's the second cube)

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
