### ISSUE TITLE
Really like the Bee tool but the recent 4.34.1 made my antivirus pop up.

### ISSUE THREAD

**Issue by User-505** [BEEmod/BEE2.4#1088]
Just finish unpacking the exe file from the recent file 4.34.1 and windows defender alerted me of a trojan virus from the file BEE2_4.34.1_win.
And in the description said it was this one Trojan:Win32/Zpevdo.B and was quarantined and remove.

This just  appears just in the exe folder.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fZpevdo.B&threatid=2147729093

Just wondering if someone can confirm this and the image that appear:
Yes it in spanish telling about the file.

![image](https://user-images.githubusercontent.com/44939801/54180210-a8242100-4460-11e9-8e4a-9f522e1d0aae.png)

**Comment by ZombiePwner1** [comment]
The reason some anti-viruses get triggered is because BEE2 does stuff that are similar to what malware programs do but these do not harm your computer it's a false positive.

**Comment by User-505** [comment]
Ok thanks for the confirmation.

**Comment by TeamSpen210** [comment]
Searching this threat name eventually turned up a report mentioning some of the files PyInstaller generates. This is the tool I'm using to convert the Python application into a exe. Probably someone wrote a virus with it at some point, so it's being flagged regardless of the actual code content.

**Comment by LautaroL20** [comment]
If you do not add the compiler files to your antivirus exception´s list, forget about keep using Beemod.
