### ISSUE TITLE
I don't know what happened but all my chambers are local

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2.4#1091]
![image](https://user-images.githubusercontent.com/32681975/54498999-941f6a00-490d-11e9-9850-5b3213c1c86c.png)
This happens so when I upload them, They make a new version of themselves
I think it's because I didn't run it properly.
I clicked on one of these and it loaded portal 2.
![image](https://user-images.githubusercontent.com/32681975/54499014-b44f2900-490d-11e9-887a-991e7794910b.png)

**Comment by eeeee48** [comment]
I think I've solved it but I'm not sure how.

**Comment by LautaroL20** [comment]
This problem does not have anything to do with Beemod, next time make sure to not post unrelated stuff. Your problem is being caused with a failure on the sync between the Steam cloud and your files.
