### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by L89David** [BEEmod/BEE2.4#1092]
**So, I updated BEE, and this happened...
Here is the console details:**

NET_GetBindAddresses found 192.168.1.14: 'Intel(R) Dual Band Wireless-AC 7265'
Opened Steam Socket NS_SERVER ( socket 3124 )
Opened Steam Socket NS_CLIENT ( socket 3116 )
Network: IP "ipnumber", mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Failed to init 'maps/soundcache/_master_spanish.cache'
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Force
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control

**Note that I tried the uninstall option, and then reinstalling and nothing... Also I checked the option "Preserve Game Directories"**
Thanks!

**Comment by LautaroL20** [comment]
It is most likely some kind of antivirus or a weird firewall that is being blocking the compiler files of Beemod, if you do not add those files to your antivirus exception list, forget about keep using beemod. Just add the whole "bin" folder which is located in the Portal 2 folder to the exeption list.

**Comment by L89David** [comment]
Perfect, thank you!
