### ISSUE TITLE
Sendifigator dont work on Overgrow

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#1093]
Hey,
At first thanks for the new Mac Version for the BEEMod :-D

The old and the Sendifigator small don't work on Overgrown Style. :-(
In the Styles "Clean, Original Clean, Portal 1, and BTS" He Work Fine, but has no Skin.
In Old Aperture Don't Work but has Skin. :-/

Please look at it and fix it. Thank You.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

**Comment by dunkler-schatten** [comment]
oh sorry for that.
