### ISSUE TITLE
error compile in overgrown 2019.

### ISSUE THREAD

**Issue by DrPipBob** [BEEmod/BEE2.4#1098]
PORTAL2 PUZZLEMAKER]  Compilation time (after export): 93 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 4.34.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Using random SP Entry (2)
[I] vbsp.mod_entryexit(): Using random SP Exit (3)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_DESTROYED_64" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "ENTRY_GEN_FUTURE_STARTER"
 | 	"Choreo" "npc/announcer/prehub17.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_GEN_RESTART"
 | 	"Choreo" "npc/announcer/mp_hub_return06.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/4 quotes..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] vbsp.anti_fizz_bump(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['collapsedexitstairs', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3452, misses=393, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': True, 'restartonexit': False, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/Steam/steamapps/common/Portal 2/portal2/', 'D:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: D:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): material "bee2/overgrown/tile/white_floor_tile005a" not found.
[I] <valve>.vbsp(): Material not found!: BEE2/overgrown/tile/white_floor_tile005a
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/over/elevator_sp/entrance_corridor_2.vmf
[I] <valve>.vbsp(): 

![20190406171904_1](https://user-images.githubusercontent.com/47915535/55669392-2a510b00-5890-11e9-95c6-fd339b4e1750.jpg)

**Comment by ZombiePwner1** [comment]
Missing corridor instance. Change it via the beemod menu.

**Comment by DrPipBob** [comment]
> Missing corridor instance. Change it via the beemod menu.

Did not help. And for some reason I don’t have any instance..

**Comment by ZombiePwner1** [comment]
@DrPipBob Did you change the corridor in the beemod menu?

**Comment by DrPipBob** [comment]
> @DrPipBob Did you change the corridor in the beemod menu?

Yes, and it did not help.

**Comment by ZombiePwner1** [comment]
@DrPipBob Use all the corridors and see if that works.

**Comment by DrPipBob** [comment]
> Use all the corridors and see if that works.
Doesn't work either

**Comment by DrPipBob** [comment]
> @DrPipBob Use all the corridors and see if that works.

Hey dude. Maybe you can upload everything Bee 2.4 instances to Google and give a link? so I downloaded..

**Comment by LautaroL20** [comment]
This does not happens if you use PRL4.34.1.

When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. In order to solve this annoyance, you will have to do the following:

1 - Make sure your antivirus is not blocking the compiler´s files of Beemod that are located in the `bin` folder inside the Portal 2 game´s directory. Just add the whole `bin` folder in your antivirus exception´s list, because otherwise this can cause a ****"building error"**** issue when building your puzzle.

2 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

3 - Wait 1 minute while Beemod removes their resources from Portal 2.

4 - Verify the Game Cache Files. 

5 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application)  
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, or even on 32 Bit versions of Windows, issues can occur. Beemod currently works well only on 64 Bit versions of Windows 7, 8 and 10.

6 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

7 - Now choose your favorite Items & Style and export your palette to the game.

8 - Make sure to save these steps in a text file in case you get similar issues in the future.

9 - Happy mapmaking!

**Comment by LautaroL20** [comment]
Also, you are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
