### ISSUE TITLE
BEE2_4.34.1 launches then crashes

### ISSUE THREAD

**Issue by Echhhhhh** [BEEmod/BEE2.4#1101]
I recently redownloaded BEE2 after restoring my laptop but whenever I launch the game, I get this message:
![image](https://user-images.githubusercontent.com/49674242/56192790-13947c00-6027-11e9-861e-a4902fceeedb.png)
Followed by a crash.

Is there any way I can fix this? Thanks in advance!

**Comment by TeamSpen210** [comment]
Delete the file mentioned at the end there - `config.vdf`.

**Comment by Konclan** [comment]
Not sure this is a valid issue

**Comment by LautaroL20** [comment]
You've made this issue with what can now be considered are really old versions of the application and packages. Honestly, I do not think that this is an issue anymore, so please get the latest version of BEE2 and then if the issue still exists, let us know and we will re-open the issue.
