### ISSUE TITLE
NOT Strip without  INPUT connection: map compile error

### ISSUE THREAD

**Issue by dusp2k** [BEEmod/BEE2.4#1103]
BeeMOD version: 2.4.33.1
Targets: NOT Strip

Expected behaviour:
OUTPUT of the NOT strip should be HIGH/ON when the INPUT is LOW/OFF.
If there is no INPUT connection at all, the OUTPUT should also be HIGH/ON.

Current behaviour:
Connecting no INPUT will generate a map compilation error.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
