### ISSUE TITLE
Beemod 2.4 wont launch

### ISSUE THREAD

**Issue by sidneymnl** [BEEmod/BEE2.4#1104]
It won't open no matter what I do. I have tried
 reinstalling, launch whit admin and compatibility mode. Nothing works. It also won't generate a log so idk if its a problem whit my pc or what.

**Comment by LautaroL20** [comment]
Get in contact with the developer and collaborators of Beemod thru its Discord server in order to help you solving your issue, since for this specific issue will probably require a chat room for a correct feedback, do it thru the # application section:
 
https://discordapp.com/invite/hnGFJrz
