### ISSUE TITLE
Failed to download Bee2.4 - Forbidden

### ISSUE THREAD

**Issue by Kingmiami** [BEEmod/BEE2.4#1105]
![forboden](https://user-images.githubusercontent.com/49174731/56852901-dbc2e980-68ee-11e9-91b3-78b23261b082.PNG)

Newest version of Bee2.4 packages

Searched it up, and apparently this means the creator has a restriction in which you might have to log in or something. But, I am logged into github and it worked in the past, so I'm confused

Also, I have ABP enabled

**Comment by LautaroL20** [comment]
You are the only person having this kind of issue, get in contact with the developer thru the Discord server.
