### ISSUE TITLE
Crash everytime i export to Portal 2

### ISSUE THREAD

**Issue by ianfrancong** [BEEmod/BEE2.4#1106]
Everytime i export the palette to Portal 2 i get this error 
![yes](https://user-images.githubusercontent.com/50310076/57204974-9313cc00-6f91-11e9-8c70-5d1864a7c041.png)

**Comment by LautaroL20** [comment]
Which pre-release number are you currently using?

**Comment by Danimob** [comment]
@LautaroL20 I think they are using 4.34.1 (the newest one).  It says in the image

**Comment by TeamSpen210** [comment]
Try using the zipped packages, not the loose files,

**Comment by LautaroL20** [comment]
Try doing what TeamSpen210 said.

**Comment by TeamSpen210** [comment]
Even still, this shouldn't be an error.

**Comment by lukesound** [comment]
but what zipped files

**Comment by TeamSpen210** [comment]
The solution is to use the packaged zips in the release, not the source code. Figured out what happened here, that massive path is over 255 characters so it exceeds Windows's path limit.

**Comment by TeamSpen210** [comment]
The solution is to use the packaged zips in the release, not the source code. Figured out what happened here, that massive path is over 255 characters so it exceeds Windows's path limit.
