### ISSUE TITLE
Start/End Ideas

### ISSUE THREAD

**Issue by Danimob** [BEEmod/BEE2.4#1107]
It would be cool if you could choose a certain position in the map for it to start, (it would be able to replace the entrance). Also, it would be cool to have a trigger and when it receives an input it  fades the screen and ends the map.

**Comment by TeamSpen210** [comment]
No. This would make absolutely no sense. What puzzle purpose would this serve?

**Comment by UberFartz** [comment]
Maybe a section where you fall down a hole and end up in the Old Aperture?
I really don't know

**Comment by Danimob** [comment]
@TeamSpen210 It would allow you to make a custom beginning to a map, eg in a stasis pod, or going up a lift into the middle of a chamber.  Also, the end would allow you to make cool endings, like UberFartz said.  Another example would be turrets coming down and then it fades.  The entrance would just be like how some maps made in hammer start inside a certain place, and how the fade command thing fades the screen and ends the map.

**Comment by TeamSpen210** [comment]
The Puzzlemaker is for puzzles, not story.

**Comment by Danimob** [comment]
I think that puzzles are better with a story, like "Into the multiverse" on the steam workshop it was made with hammer, but has a cool story and good puzzles.  I would appreciate it very much if you could add this, and I don't think it would be as hard to code as many other things on bee (I may be wrong, I don't have much experience in coding), however if you really dislike this idea, you don't have to make it (This is the final part of my argument, and I probably won't respond to further replies, but I might read them)
