### ISSUE TITLE
Ultimate Moving Pannels

### ISSUE THREAD

**Issue by Danimob** [BEEmod/BEE2.4#1110]
This would be a hard item to make, so I understand if you can't make it.  It would be like a track platform, but you would be able to put items on it, eg a laser.  When the laser is triggered it would act like a normal laser, and when the platform is triggered it moves and the laser moves with it.  Sorry if I didn't explain this very well...

**Comment by TeamSpen210** [comment]
This makes more sense as individual items for each device combination, for those things that are useful.
