### ISSUE TITLE
Chamberlock Item Prevents Map From Being Rebuilt in BEE2.4 Ver. 4.34.1

### ISSUE THREAD

**Issue by Entity447** [BEEmod/BEE2.4#1113]
Whenever a chamberlock item is present in a map on the overgrown style, the map fails to rebuild.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
