### ISSUE TITLE
Config files get nulled out

### ISSUE THREAD

**Issue by mistaGreenie** [BEEmod/BEE2.4#1116]
I had recently reinstalled BEEMOD2 with the latest version and extracted them into my BEE2 folder when this error popped up.
https://pipe.miroware.io/5ce3470d55998906f27b8d90/what.PNG
Is there anything I can do to fix this?

**Comment by TeamSpen210** [comment]
To make it work, delete `C:/Users/Steve/AppData/Roaming/BEEMOD2/config/compile.cfg`.

**Comment by mistaGreenie** [comment]
Thank you.

**Comment by mistaGreenie** [comment]
I can't find AppData, I can find Roaming, but not BEEMOD2 either.

**Comment by TeamSpen210** [comment]
It's a hidden folder. Click on the folder names in the menu bar to convert that into a textbox, then type in `%appdata%` and press enter.

**Comment by mistaGreenie** [comment]
Thank you, TeamSpen.
