### ISSUE TITLE
Sending chamber changes to other users to simulate multiplayer map making

### ISSUE THREAD

**Issue by immakingthisaccounttoask1questionlolwhy** [BEEmod/BEE2.4#1117]
i literally created an account just to ask if it would be possible to send chamber changes to other users for multiplayer map making. probably not possible or too much to ask for but could be worth a mention.

**Comment by UberFartz** [comment]
I don't think that's possible.

**Comment by LautaroL20** [comment]
Just try it out yourself instead of asking if its possible or not. These repositories are just to suggest stuff or to report bugs only. Regards to questions, they should be relevant enough to make.

**Comment by TeamSpen210** [comment]
There's not much we'd be able to do here. There's no way to do like simultaneous editing, you'd just work on the map, save and send to the other person, then open and work on that. With cloud syncing you could eliminate the sending, but otherwise it'd be rather disjointed.
