### ISSUE TITLE
"Restart when Reaching Exit" option has no effect at all

### ISSUE THREAD

**Issue by programmer2514** [BEEmod/BEE2.4#1119]
Unchecking "Restart when Reaching Exit" doesn't have any effect at all.
The map will still display "Test Complete. Restarting..." and restart in the elevator, just like before.
I have only tested this in Overgrown mode.

**Comment by Konclan** [comment]
This is surprisingly still a problem

**Comment by Luke18033** [comment]
Does this affect any specific style(s) in particular? I do most of my testing in Clean and this has never been an issue for me.

**Comment by Konclan** [comment]
In clean I get to the elevator and it just says insert vote screen here and then nothing happens, I have restart when reaching exit enabled. It just doesn't work.

**Comment by Luke18033** [comment]
Oh, that's the opposite issue. Weird.

**Comment by Konclan** [comment]
Video from @Gamther
https://www.youtube.com/watch?v=QI3c17l17Fo

**Comment by Konclan** [comment]
Seems to be fixed by the corridor remake
