### ISSUE TITLE
Add installer via NSIS

### ISSUE THREAD

**Issue by programmer2514** [BEEmod/BEE2.4#1121]
I have been working on writing an installer for my program (also a compiled Python script) and I thought BEE2 could use one, too (based on the number of issues about it).
I wrote an installer for version 4.34.1, which is located [here](https://github.com/calclover2514/BEE2.4-Installer-Automatic/releases).
If you think this is a plausible fix for the lack of an installer for BEE2, please let me know.
Until then, I will continue to update the installer with every release of BEE2.

Thanks,
calclover2514

**Comment by TeamSpen210** [comment]
The main reason I haven't done an installer yet is dealing with the packages - I don't want to be including all of those in the same download as the installer itself. So for that I think I want to add a downloader for them into the application itself, then make an installer.

**Comment by calclover2514** [comment]
> I don't want to be including all of those in the same download as the installer itself
Why not?
I know it makes it bigger, but not including them makes installing way harder.

P.S. Have you tried uploading the packages to Github Pages? It would make downloading them from within BEE2 fairly easy, as long as they always had the same name/naming pattern. This could be done to automatically update BEE2 as well

**Comment by TeamSpen210** [comment]
The major problem with GH Pages is that they're a Git repo, so that means the file size will be getting ever more massive.

**Comment by calclover2514** [comment]
What about a regular free webhost service.
You wouldn't need a webpage or anything, just the files and maybe an xml file listing them
