### ISSUE TITLE
Death Detector

### ISSUE THREAD

**Issue by Danimob** [BEEmod/BEE2.4#1122]
This would be useful for race/fight minigames AND normal chambers.  This COOP only item would have an output with a timer the activates when a player dies.  
Weighted: Anyone
Cube: Atlas/Blue
Sphere: P-Body/Orange

Example of uses:  
        Fight: If blue dies, the room sprays itself with orange gel from droppers before opening the                 
        exit.
        Test: The amount of times I have managed to cheat levels by dying...   If a player dies, it could         
        spawn turrets and kill the other player, before completely resetting the map with SR latches 
        (Or reset everything after a certain point).

I really hope this is possible.

**Comment by TeamSpen210** [comment]
I don't think this is a good idea. It's the puzzlemaker, not fightmaker. For cheating levels by dying, you kinda have to think about that like any other gameplay mechanic. A simple way to force it would be to make a door after the entrance that requires both players to be able to open - so the other player must backtrack to allow the respawned player to proceed. Alternatively, just add more player spawners to control where they reappear.
