### ISSUE TITLE
BEE2 doesn't start

### ISSUE THREAD

**Issue by CryoBot343** [BEEmod/BEE2.4#1124]
When started, I get this message:
![image](https://user-images.githubusercontent.com/51292123/58762560-9c537280-8516-11e9-8467-7077ef01027c.png)
![image](https://user-images.githubusercontent.com/51292123/58762751-8e9eec80-8518-11e9-8950-ec6e7b890c4f.png)

What exactly do I do?

**Comment by LautaroL20** [comment]
That is weird, did you also download the item´s packages?

**Comment by CryoBot343** [comment]
> That is weird, did you also download the item´s packages?

Yes, it had worked for a few months.

**Comment by CryoBot343** [comment]
I probably did something wrong, because I replaced the packages folder with a new one and it works.
