### ISSUE TITLE
Portal 2 Crashes after building map

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2.4#1126]
I've been experimenting with BeeMod and I've found that having two monitor screens crashes portal 2 during the process of loading a level after it has been built.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
