### ISSUE TITLE
How to use skyboxes?

### ISSUE THREAD

**Issue by V0pT** [BEEmod/BEE2.4#1131]
I'm trying to figure out how to use skyboxes that come with the custom style to put in my factory/ escape sequence chamber. The best explanation I've seen is that it's visible 'outside the test chamber' but I have absolutely no idea how to make that area visible in the test. I'm using version 2_4.34.1 and I honestly don't know if I'm being an idiot or this feature got removed.

**Comment by Luke18033** [comment]
There's no just "skybox" item. It's mainly used to set the color/distance of fog, and is visible in some existing items (like Overgrown entry/exit corridors). Some skyboxes like 3D Factory will also convert goo into bottomless pits.
