### ISSUE TITLE
No EXE file

### ISSUE THREAD

**Issue by ohyesss** [BEEmod/BEE2.4#1134]
lol I can't find the exe. Is it in the packages?

**Comment by TeamSpen210** [comment]
What links did you download? You want to go here: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.35.1

**Comment by ohyesss** [comment]
Yes I downloaded that already.

**Comment by Luke18033** [comment]
Make sure it didn't get removed by an antivirus program, that's a common issue since they tend to not like small projects like this.

**Comment by ohyesss** [comment]
lol I don't have antivirus.

**Comment by ohyesss** [comment]
Is that the problem?

**Comment by LautaroL20** [comment]
The executable "BEE2.exe" in other releases was previously available inside the `bin` folder of Beemod. Now in this release, you should be able to find it directly among the files that are NOT inside the bee´s folders.

**Comment by Luke18033** [comment]
What does your BEE2 folder look like?

**Comment by ohyesss** [comment]
![Capture](https://user-images.githubusercontent.com/42584554/59536381-79986500-8eeb-11e9-9547-16798032cdb8.JPG)

**Comment by ohyesss** [comment]
By the way, I merged the packages with it.

**Comment by LautaroL20** [comment]
You are missing lot of files there, what pre-release version are you using?

**Comment by Luke18033** [comment]
Ah, that's the problem, you downloaded the master branch itself, not the release. Go to the link TeamSpen posted earlier and download that.

**Comment by Luke18033** [comment]
Going to assume that the issue has been solved.
