### ISSUE TITLE
60 and 90 degree angled panels using default texture

### ISSUE THREAD

**Issue by calclover2514** [BEEmod/BEE2.4#1136]
![20190613094041_1](https://user-images.githubusercontent.com/43104632/59437455-a2bbd700-8dbf-11e9-9d85-4f8125c3cc31.jpg)
See the difference between the 60 and 45 degree panels.
This is happening with all 60 & 90 degree angled panels.
I have only tested this in overgrown mode.

**Comment by TeamSpen210** [comment]
That's intentional, they're sufficiently horizontal to use the floor texture.

**Comment by calclover2514** [comment]
There should be a way of setting the texture (E.G. Button Type)

**Comment by TeamSpen210** [comment]
Why?
