### ISSUE TITLE
Could not open instance, file: instances/bee2/bts/elevator_sp/entrance_corridor_4.vmf

### ISSUE THREAD

**Issue by Klucy** [BEEmod/BEE2.4#1140]
Greetings. I have been using Bee Mod for a while now, and this issue has just now come up. My maps will not compile. The error log goes something like this:

<details>
<summary>Error Log</summary>
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 33 (ms)

VBSP failed.

[I] vbsp.main(): BEE2.35.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'glass_scale': '0.05', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 4
[I] vbsp.mod_entryexit(): Setting SP Exit to 2
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[I] vbsp.set_elev_videos(): Elevator type: NONE
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_NEW_COURSE_EXTENDED"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/mp_coop_tbeam_redirect01a.vcd"
 | 		"2" "scenes/npc/glados/mp_coop_startend02.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/9 quotes..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['factorycorridor', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2897, misses=351, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': False, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/logic/goo_fade.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: True
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_brush(): Creating Bottomless Pits...
[I] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf']}
[I] vbsp.change_brush(): Done!
[I] vbsp.clump_walls(): Clumping: 108 clumps (+ 0 special)
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <valve>.vbsp(): 8 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/bee2/bts/elevator_sp/entrance_corridor_4.vmf
[I] <valve>.vbsp(): 
</details>

**Comment by Konclan** [comment]
Entrance corridor 4 works now so this has been fixed
