### ISSUE TITLE
Add support for curly apostrophe character in the item´s descriptions

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1141]
![Issue](https://user-images.githubusercontent.com/12244376/60391594-4ef00400-9ac8-11e9-8ccc-6a31d0bee9c5.png)

**Comment by TeamSpen210** [comment]
Make sure you're using UTF-8 encoding, actually.

**Comment by LautaroL20** [comment]
Since my main PC died and i did not finish building a new one, i am still in a Potato PC that can not even launch Beemod so i can not check about the UTF-8 thing atm.

**Comment by Luke18033** [comment]
So can this be closed?

**Comment by LautaroL20** [comment]
So, this doesn´t happens with people who uses Beemod in Windows 10? Maybe i am having this issue because i have Win 7.

**Comment by TeamSpen210** [comment]
It depends on how you save the file and which editor.
