### ISSUE TITLE
Fizzler Door

### ISSUE THREAD

**Issue by EndlessRush** [BEEmod/BEE2.4#1142]
I'm not sure if it's just me (and i'm not sure if it's just the style), but when i try to load a puzzle with a fizzler door in it, it has an error. There isn't really anything else to say. I just don't know why. It's usually when loading the models.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
