### ISSUE TITLE
Beemod crashes: Windows Error 0x88880001 

### ISSUE THREAD

**Issue by OlekFXOfficial** [BEEmod/BEE2.4#1143]
![Zrzut ekranu (43)](https://user-images.githubusercontent.com/52384885/60401554-4573a400-9b7b-11e9-81d1-8a503fe4953b.png)
### **Help i always get this issue**

**Comment by LautaroL20** [comment]
That is a weird crash.

**Comment by OlekFXOfficial** [comment]
what do i do?

**Comment by OlekFXOfficial** [comment]
help
i want it to work
 contact the owner!!!!

**Comment by LautaroL20** [comment]
@OlekFXOfficial - Contact Spencer.

**Comment by OlekFXOfficial** [comment]
> @OlekFXOfficial - Contact Spencer.

how do i do that?

**Comment by OlekFXOfficial** [comment]
@TeamSpen210 what do i do with this? can you help me?

**Comment by TeamSpen210** [comment]
Do you have anything unusual with your audio drivers on your computer? Is this the latest version? Turn off sound effects in options to work around this.

**Comment by MRDark101** [comment]
TeamSpen210 how do you turn them of i dont know.kuz i have that same issue.

**Comment by OlekFXOfficial** [comment]
> Do you have anything unusual with your audio drivers on your computer? Is this the latest version? Turn off sound effects in options to work around this.

my audio drivers down work, yes the newest. And okay ill try!

**Comment by OlekFXOfficial** [comment]
> Do you have anything unusual with your audio drivers on your computer? Is this the latest version? Turn off sound effects in options to work around this.

well everytime i do something the editor just dossent respond,... 
@TeamSpen210

**Comment by TeamSpen210** [comment]
Which editor, and what exactly are you doing? And how does it not respond?

**Comment by Luke18033** [comment]
Closing due to lack of response.
