### ISSUE TITLE
1970s Antline indicators not working

### ISSUE THREAD

**Issue by JavierNovellon** [BEEmod/BEE2.4#1144]
Hello!

I have a problem regarding connection/antline indicators (that blue cross and that orange checkmark, correct me with the proper term if there's one)

In most styles, when I connect an item, it joins with antlines (or signage), but the indicator fails to work in the 1970s style. I don't know what it is, seems like it's missing the animation to turn orange? It also seems to happen to timers as well, I hear the ticking, but the timer doesn't spin.

Here's some screenshots in case that helps. The first two are the antlines, checkmarks and timers functioning correctly in the 1950s (as they do in every other style); the last two are the same elements not working in the 1970s.

![Problem A - 1950s](https://user-images.githubusercontent.com/47536167/60689274-9bb25100-9eb3-11e9-99af-d91aadbe37bb.png)
![Problem B - 1950s](https://user-images.githubusercontent.com/47536167/60689275-9bb25100-9eb3-11e9-9db5-8ddb11de8ac6.png)
![Problem A - 1970s](https://user-images.githubusercontent.com/47536167/60689277-9bb25100-9eb3-11e9-9987-62ad7b189d1b.png)
![Problem B - 1970s](https://user-images.githubusercontent.com/47536167/60689276-9bb25100-9eb3-11e9-8c1a-684a38ee23c7.png)

I was wondering if anyone else has this problem, or I am the only one. Is this something I can fix?  Or do I need to wait until a new release?

Thank you in advance!

Edit 1: fixed screenshot order

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
