### ISSUE TITLE
Plays editor's music in the "Original Clean" style. Bug in Bee2 4.35.1

### ISSUE THREAD

**Issue by Chertov2018** [BEEmod/BEE2.4#1149]
I created a test with a Bee 4.35.1 and when checking I heard the editor's music and thought: I Hope after the publication of this music will disappear. No. She still plays with the passage. (If you disable the music editor in the settings, it will not). Please fix it

**Comment by ZombiePwner1** [comment]
This is a bug that most likely can't be fixed due to the fact that this is a source code issue.

**Comment by Chertov2018** [comment]
I found the problem! physics repulsion field, when it is not on the map, everything is fine, and when it is, there is music from the editor...

**Comment by ZombiePwner1** [comment]
@Chertov2018 Still can't be fixed. Source code issue.
