### ISSUE TITLE
Bee2 error on start, then it freeze down.

### ISSUE THREAD

**Issue by spygineer** [BEEmod/BEE2.4#1150]
I have a fresh install of Portal2 and Bee2 and the program displays and error when started, then the loading screen start, but it is completly frozen.

Here is the error message:
![image](https://user-images.githubusercontent.com/14953871/61239926-50643200-a740-11e9-93c8-ee986e024551.png)

Note: Steam is installed on the D drive, but portal2 is installed on an other drive. At the bottom there is a message: File not found "D:/Steam/SteamApps/Common/Portal2", I'm not sure that couses the issue.

**Edit: Problem solved. I've edited the game's path from games.cfg. It seems I haven't properly uninstall the mod and it had some leftover config files.**

**Comment by Konclan** [comment]
Not sure this still happens
