### ISSUE TITLE
Other things to request

### ISSUE THREAD

**Issue by EndlessRush** [BEEmod/BEE2.4#1151]
I'm not sure if this is the place to request something, but I thought I could request a few things.

-Defective Turrets. Also know as "Crap Turrets" by Wheatley. You could add a "Change Button" GUI to the turrets and each button changes it to a different type of turret. One as the Sentry Turret, another one as a Defective Turret, and the other one as a boxed turret. You could go a step further and add a the Sentient Turret.

-A little update to the vactube. I thought there should be a way to crack the glass or have the glass already cracked in a test chamber. Or maybe make a way to set what is flowing through the tube (gel, cubes, or nothing) And if there was gel in the tube, it would leak if you set it to a state where it is cracked.

-Dialog Trigger. There should be a trigger that would trigger dialog from the voice chosen. when selected, it would bring up a custom gui with the dialog names from the game and you could choose that one to trigger when ran into that area.

-Cores and Potato GlaDOS. Cores are an important part of portal. I thought that maybe you guy could add Wheatley (the core) and maybe the other cores from the boss battle at the end of Portal 2.  And (if you want) you could add the other cores from the boss battle in Portal 1 when using that theme. And you could add a new option to the "Export Menu" for cores weather you start with them or not and which ones you start with. Maybe you could do the same with potato GlaDOS. 

-Office Props. You might know what I mean by office props. Desks, monitors, and chairs. It's pretty simple to add the models. I'm not sure about coding them.

It might seem a lot to add add but thankfully I didn't put everything. But here is everything else if you want add them

-Ratman Drawings
-Toggle Lights
-GlaDOS (p1 and 2) Wheatley Boss models
-Bomb Droppers
-Animal King
-Prima Donna Turret

If you add any of this stuff into the mod, I would appreciate it. You don't have to give me credit for the ideas if you don't want to.

**Comment by MRDark101** [comment]
i like thous ideas hophyli we see thous in the future.

**Comment by ZombiePwner1** [comment]
Cores will not be added, This is for making puzzles not for story maps if you want to make story maps use hammer for that.

Animal king will not be re-added
Bomb droppers will be added in a future release.
Prima Donna Turret what's the use of this?
What is the use for ratman drawings + office props?

**Comment by EndlessRush** [comment]
The Prima Donna Turret (the fat turret), ratman drawings, and office props
would be used for decorations
I mostly want the office prop because the fit the BTS theme

**Comment by EndlessRush** [comment]
The Prima Donna Turret (the fat turret), ratman drawings, and office props would be used for decorations
I mostly want the office prop because it would the fit the BTS theme. there is really no other purpose of them

**Comment by ZombiePwner1** [comment]
@EndlessRush But they don't serve as test elements and essentially they would just get in the way for BTS.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
