### ISSUE TITLE
Windows Permissions causes Error

### ISSUE THREAD

**Issue by MRDark101** [BEEmod/BEE2.4#1152]

**Comment by MRDark101** [comment]
how do i fix this teamspen210? can you help me

**Comment by MRDark101** [comment]
helloouuuu. how can i fix this?

**Comment by TeamSpen210** [comment]
You have the environment variable `BEE2_P2_LANG` set, unset that. (Search "environment variable" in the Start Menu.) Or if you need it, set it to just `english`.

**Comment by MRDark101** [comment]
it does not work. nothing happends when i unset it.

**Comment by MRDark101** [comment]
i dont know if i did it right or not but i unset it so dont know.

**Comment by MRDark101** [comment]
now i get this can you help me again

**Comment by TeamSpen210** [comment]
What do you get?

**Comment by LautaroL20** [comment]
This guy will probably take another week to just reply a simple question. It looks like hes not much interested on solving the issue if he is only checking the email inbox 1 day peer week...

**Comment by MRDark101** [comment]
i forgot this when i was at holyday rip but i get that new issue. i have put the new picure in and i am confused.

**Comment by TeamSpen210** [comment]
Go to that folder, and delete the BEEmod configs folder. It's saying that it doesn't have permission to update the config files.

**Comment by MRDark101** [comment]
ok thanks it works now.

**Comment by LautaroL20** [comment]
Is this issue fixeable?

**Comment by TeamSpen210** [comment]
Yeah.

**Comment by MRDark101** [comment]
umm. now there is a new issue. what is this. it never stops.

**Comment by MRDark101** [comment]
ou wait it works sometimes and sometimes it dosent.
weird

**Comment by MRDark101** [comment]
aaah. sometimes when i open it errors and sometimes it takes 2-5minutes to error. aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAH.

**Comment by LautaroL20** [comment]
wat
