### ISSUE TITLE
Packages in Wrong Folder

### ISSUE THREAD

**Issue by kaibeckers** [BEEmod/BEE2.4#1153]
When I try to start the BMOD, I get the following error message:

[![Screenshot from Gyazo](https://gyazo.com/654eb40bf9e8ef457c85a39973fea902/raw)](https://gyazo.com/654eb40bf9e8ef457c85a39973fea902)
Although, the error should not occur.
[![Screenshot from Gyazo](https://gyazo.com/10af606bf705ee80417f5b865ec24fc0/raw)](https://gyazo.com/10af606bf705ee80417f5b865ec24fc0)

**Comment by TeamSpen210** [comment]
You need to take the packages folder out of that one, and put it in the enclosing folder.
