### ISSUE TITLE
when you run Portal 2 with bee2 any version in palmature crashes improper Assembly

### ISSUE THREAD

**Issue by DayMandarin** [BEEmod/BEE2.4#1155]
... (sorry for my English)
um I think it sounds stupid that the test build error but this is so when you start the build card at least empty/not empty error crashes with bee2 any version, I was first a pirate but after buying the game I had a problem with portal 2 and bee2 although in the past this was not well... OK, if I start the map with the inventory and generally bee2 bee2 crashes with an error without it

**Comment by LautaroL20** [comment]
WAT. 

Id suggest using a better translator website, since that looks like its even worse than googie translate!
