### ISSUE TITLE
win need update

### ISSUE THREAD

**Issue by ENDERZOMBI102** [BEEmod/BEE2.4#1157]
well, the title says that, this is the error:
https://github.com/ENDERZOMBI102/some-things/raw/master/beerror
i think thats @TeamSpen210 python-related.
i have the latest BEE version (4.31.1) and the latest python version (3.7)

**Comment by ENDERZOMBI102** [comment]
i have reinstalled python 3.6.8, reinstalled bee and p2, same error!

[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3201, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 2933, in run_vbsp
  File "F:\Git\srctools\srctools\run.py", line 67, in run_compiler
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 707, in __init__
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 990, in _execute_child
OSError: [WinError 216] La versione di %1 � incompatibile con la versione di Windows in esecuzione. Verificare le informazioni di sistema e contattare il distributore del software
[1008] Failed to execute script compiler_launch

sooooooooo, help!!!!!!

**Comment by ENDERZOMBI102** [comment]
oh the log is in italian.... ehm sorry for that

**Comment by Luke18033** [comment]
Do you have a 32-bit system? That's the only thing that I can think might cause this error.

**Comment by ENDERZOMBI102** [comment]
Nope 64

**Comment by TeamSpen210** [comment]
What this error implies is Valve's VBSP is somehow incompatible with your windows.....

**Comment by ENDERZOMBI102** [comment]
How

**Comment by ENDERZOMBI102** [comment]
I use the p2 original like everyone

**Comment by TeamSpen210** [comment]
Try verifying your game cache.

**Comment by ENDERZOMBI102** [comment]
Already done but ok,tomorrow i'l try
