### ISSUE TITLE
Crashing Mac after loading UI

### ISSUE THREAD

**Issue by ToasterCorporation** [BEEmod/BEE2.4#1160]
I startup BEE2 and the loading works just fine but the moment that the UI finishes loading, my MacBook crashes and goes back to the login screen. Please is there a way to fix this?

**Comment by TeamSpen210** [comment]
In the folder you extracted BEE2, there should be a `BEE2.log` file in the `logs` folder. Attach a copy here.

**Comment by ToasterCorporation** [comment]
I see two logs, a normal log and a error log. I'll go ahead and attach both.

**Comment by ToasterCorporation** [comment]
Hey, haven't heard from you in a while. Is there a fix for this?

**Comment by TeamSpen210** [comment]
You didn’t attach any logs. I’d suggest doing it on the website, if you did it via email reply.

**Comment by ToasterCorporation** [comment]
Huh, for me it says I did. I'll re send them but if it doesn't show up this
time, how would I submit them through the other website?

**Comment by LautaroL20** [comment]
Just send your log files thru droppbox, for example.

**Comment by ToasterCorporation** [comment]
https://drive.google.com/drive/folders/1WnS9_57VtQz1rW_-h8M4eZftqT_K7mtP?usp=sharing
I have this google drive link with the files on it if that works.

**Comment by ToasterCorporation** [comment]
Hey it's been a while. Did you get the files?

**Comment by LautaroL20** [comment]
Yes, but the one who knows very well on how to interpret  the log file is Spencer. Just ask him @TeamSpen210

**Comment by ToasterCorporation** [comment]
He was part of this email, I thought it would've gotten to both of you...

**Comment by ToasterCorporation** [comment]
> You didn’t attach any logs. I’d suggest doing it on the website, if you did it via email reply.

Ok not sure if this will get your attention and I don't know how to contact you directly but here. This is the google drive link to my error files.
https://drive.google.com/drive/folders/1WnS9_57VtQz1rW_-h8M4eZftqT_K7mtP?usp=sharing

**Comment by Konclan** [comment]
This is the only error I see
<details>
<summary>Error</summary>
[WARNING] sound.<module>(): ERROR:SOUNDS NOT INITIALISED!
Traceback (most recent call last):
  File "sound.py", line 52, in <module>
ModuleNotFoundError: No module named 'pyglet.media'; 'pyglet' is not a package
[DEBUG] __init__.registerExtensions(): Successfully loaded extension "tkMarkdown.TKConverter".
[DEBUG] __init__.registerExtensions(): Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
[DEBUG] __init__.registerExtensions(): Successfully loaded extension "markdown.extensions.sane_lists.SaneListExtension".
[WARNING] BEE2_config.load(): Config "/Users/daniel/Library/Preferences/BEEMOD2/config/packages.cfg" not found! Using defaults...
</details>

**Comment by ToasterCorporation** [comment]
What's odd is why would a sound error cause an entire restart?

**Comment by Luke18033** [comment]
Closing due to lack of response, I'm not sure what the problem here would be.
