### ISSUE TITLE
Door types Independant of style

### ISSUE THREAD

**Issue by V0pT** [BEEmod/BEE2.4#1162]
https://forums.thinking.withportals.com/downloads.php?view=detail&df_id=2766

The page linked is a edit of the 'door' item that allows to swap between P1, BTS, and P2 door styles. I wonder, since you already have different styles for Chamberlocks/Exit Doors in the different style types, maybe the same functionality could be implemented there as well.

**Comment by TeamSpen210** [comment]
Chamberlocks don't let you change the styles, and we're not going to add the ability to mix and match style components. It looks wrong.
