### ISSUE TITLE
There was an error building the puzzle.

### ISSUE THREAD

**Issue by RealPurpleTobi** [BEEmod/BEE2.4#1163]
This started to happen for some reason I checked if there was a new version of bee2 there was and I downloaded it. It worked fine until I made a new puzzle and I had to build/rebuild it. It just kept saying "There was an error building the puzzle." It has not happened to me in the past. It just started doing that. Maybe one of you can tell the problem. I even tried to reinstall it.

<details>
<summary>Error Log</summary>
VBSP failed.

[I] vbsp.main(): BEE2.35.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 4
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (931 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[W] cond.core.resolve_value(): Invalid fixup ($start_deployed) in the "btr20" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "btr20"
 | 	 file = "instances/BEE2/clean/items/tspen/ret_btn/floor_black.vmf"
 | 	 origin = "320 704 576"
 | 	 angles = "0 -90 0"
 | 	 $connectioncount = "1"
 | 	 $start_enabled = "0"
 | 	<Output> and:OnChangeToAllTrue -> toggle_btr20 -> SetTextureIndex (1)
 | 	<Output> and:OnChangeToAnyFalse -> toggle_btr20 -> SetTextureIndex (0)
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'start_enabled': FixupTuple(var='start_enabled', value='0', id=2)}
 |___

[I] connections.gen_item_outputs(): Item IO generated.
[I] brushes.res_import_template(): IDS: set()
[I] cond.core.res_goo_debris(): GooDebris: 32/96 locations
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_MODERN_DROPPER_WRECKED" does not exist!
[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd46" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd46"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "1600 1600 960"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "1"
 | 	 $disable_autorespawn = "1"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='1', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='1', id=3)}
 |___

[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SUPPORT" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_ENTRANCE_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_B" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_c" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: ['entry_autoportal']
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "ENTRY": 3/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "ENTRY_GEN_FUTURE_STARTER"
 | 	"Choreo" "npc/announcer/prehub17.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "EXIT": 3/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "EXIT_GEN_TECH_DIFF"
 | 	"Choreo" "ann_apoc/exit_tech_diff.vmf"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 4/4 quotes..
[I] voiceLine.add_voice(): 4 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_BUTTON_TESTING"
 | 	"OnlyOnce" "1"
 | 	"Atomic" "1"
 | 	"Choreo_Name" "@voice_anycube_pickup"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	"Choreo_Name" "@voice_franken_pickup"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_FIZZLE"
 | 	"OnlyOnce" "1"
 | 	"Atomic" "1"
 | 	"Choreo_Name" "@voice_cube_dest"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_ccube_dest"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_cube_redrop"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	"Choreo_Name" "@voice_ccube_redrop"
 | 	"Choreo" "npc/announcer/testchamber09.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Passed Through a Grid"
 | 	"Target" "@voice_player_touch_fizzler"
 | 	"Choreo" "npc/announcer/testchamber07.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Avoid Being Shot"
 | 	"Target" "@voice_turret_activate"
 | 	"Choreo" "npc/announcer/sabotage_factory17.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] vbsp.anti_fizz_bump(): Done!
[W] packing.pack_list(): Packlist "PACK_CUST_LASERFIELD_OVER" does not exist!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: N, Orange: N
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'laserfield', 'laser', 'deadly', 'fizzler', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'cubebutton', 'floorbutton', 'buttonacceptscube', 'gel', 'water', 'watergel', 'cleargel', 'orangeportal', 'blueportal', 'orangeportalspawner', 'orangeportalgun', 'blueportalspawner', 'blueportalgun', 'dualportalgun', 'pedestalbutton', 'pistonplatform', 'piston', 'panel', 'turret', 'spawn_nogun']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=19540, misses=407, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': True, 'nomidvoices': False, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_3.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 352.0 <- Counter({352.0: 96})
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[E] <valve>.vbsp(): BEE2: Fatal error - saved as _original file.
</details>

**Comment by JavierNovellon** [comment]
Was this with Portal 2 or Aperture Tag? I have no idea how to interpret the log, but it has happened to me, and I believe other people too, that Aperture Tag refuses to rebuild puzzles.

My advice, that I myself had to follow several times already, is to uninstall BEEmod2, uninstall Portal 2, reinstall Portal 2, and reinstall BEEmod2.

**Comment by RealPurpleTobi** [comment]
Portal 2

**Comment by vithorte** [comment]
> Was this with Portal 2 or Aperture Tag? I have no idea how to interpret the log, but it has happened to me, and I believe other people too, that Aperture Tag refuses to rebuild puzzles.
> 
> My advice, that I myself had to follow several times already, is to uninstall BEEmod2, uninstall Portal 2, reinstall Portal 2, and reinstall BEEmod2.

I don't want to spend again reinstalling p2

**Comment by Luke18033** [comment]
You should never need to reinstall Portal 2. This particular error would indicate that the original compilers got overwritten with copies of the BEE2 ones. Validate the game files and re-export, that should fix the problem.
