### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CStafford-14** [BEEmod/BEE2.4#1165]
I think I've found an error in the compiling of the compiler. I'm installing this on Ubuntu 18.04.03

![Screenshot](https://user-images.githubusercontent.com/35039669/63161410-0c3da900-bfee-11e9-85fc-10d0157b6a8a.png)

Is this my own error or a BEE2 error?

**Comment by TeamSpen210** [comment]
You're using Python 2.7, not 3.6+.

**Comment by CStafford-14** [comment]
I’ve run apt-get update and apt-get upgrade a few times. 

How do I manually update python?
