### ISSUE TITLE
fgd.lzma is missing

### ISSUE THREAD

**Issue by CStafford-14** [BEEmod/BEE2.4#1166]
While running `pyinstaller --distpath ../dist/ --workpath ../build_tmp compiler.spec`, I get this error: `Unable to find "/home/christophers/.local/lib/python3.6/site-packages/srctools/fgd.lzma" when adding binary and data files.`

I can't find a .lzma file anywhere on my hard drive. What happened?
I'm running this on Ubuntu 18.04.03 with Python 3.6

**Comment by Luke18033** [comment]
That's exactly what the error is telling you, that it can't find the file. I think there's a copy pinned on the Discord server...

**Comment by CStafford-14** [comment]
Speaking of which, the link's expired. Otherwise, I'd join.

**Comment by Luke18033** [comment]
Where are you finding that link? The one in the readme should still work.

**Comment by CStafford-14** [comment]
It was the one in the readme.

**Comment by Luke18033** [comment]
Huh, works for me. Probably just looking in the wrong place, [here](https://discord.gg/hnGFJrz) is the correct link
