### ISSUE TITLE
Bee2 4.35.1 restart again to use again and co-op level loading makes my game crash  

### ISSUE THREAD

**Issue by Stonksoverlord2986** [BEEmod/BEE2.4#1168]
In the modified bee2 4.35.1 portal 2 map editor i can only build my map once for testing and then if i need to test again i have to
1. restart my computer
2. load bee2 editor and export it to portal 2 
3. load portal 2 map editor again
conclusion: please fix this it is horrible and also yeah if i load co-op testing map for testing game crashes

**Comment by TeamSpen210** [comment]
What happens if you build it a second time? Any relevant logs?
