### ISSUE TITLE
Error when trying to load Beemod.

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2.4#1171]
![image](https://user-images.githubusercontent.com/32681975/63866218-32caef00-c9b3-11e9-8189-159b70e154cb.png)

I have this error while trying to load Beemod, I've moved my P2 files and now It can't find them. However Beemod should run without any game files so I'm confused. Can someone help me out here?

**Comment by LautaroL20** [comment]
You've made this issue with what can now be considered are very old versions of the application and packages. I do not think that this is a problem anymore, so please get the latest version of BEE2 and then if the issue still exists, let us know and we will re-open the issue.
