### ISSUE TITLE
Some connections between items are broken

### ISSUE THREAD

**Issue by domicrni** [BEEmod/BEE2.4#1173]
The rocket turret's rockets arent visible and dont have sounds, sometimes the rocket turret breaks and keeps shooting in one spot, some connections are broken such as pedastal buttons not working with doors.

**Comment by LautaroL20** [comment]
The Rocket Turret will be fixed when Half-Life 3 comes out.

**Comment by Luke18033** [comment]
@LautaroL20 Please stop telling everyone that, it's not helpful and the joke got old ages ago.

**Comment by Luke18033** [comment]
@domicrni The rocket turret isn't really a high priority, and pretty much every issue with it is already known. There are multiple doors in the mod, which one are you referring to for the connection issue?

**Comment by domicrni** [comment]
The regular door (not chamberlock, exit or start, just the regular door included with the default package)  doesnt work with timed pedestal buttons

**Comment by Luke18033** [comment]
I'm still kind of confused, are you talking about the standing door from the original BEEmod?

**Comment by LautaroL20** [comment]
Luke18033 Said: "Please stop telling everyone that things will "release with HL3", it's not helpful and the joke got old ages ago."

Another thing that seems to got old ages ago is the branch of your large glass panel too.

**Comment by Luke18033** [comment]
And how does that have anything to do with this?

**Comment by Luke18033** [comment]
Closing due to lack of response, I'm not sure what could cause this.

**Comment by LautaroL20** [comment]
Well, i really recognize that Spencer did a good job at finally making a stable version of Mac to come true, so more people can enjoy of Beemod in other systems. Regards to this issue, i can say that is prett annoying when people makes issues sporadically and then never gets back to them to check the notifications... It feels that people who does this, seems to not truly care about the issue they were experiencing.
