### ISSUE TITLE
Error after exporting

### ISSUE THREAD

**Issue by Martin200HUN** [BEEmod/BEE2.4#1174]
![image](https://user-images.githubusercontent.com/54775074/64080330-24523f80-ccf3-11e9-83dc-468f31360ab1.png)

**Comment by TeamSpen210** [comment]
Did you install BEE2 into the Portal 2 folder? Don't do that.

**Comment by Martin200HUN** [comment]
> Did you install BEE2 into the Portal 2 folder? Don't do that.

reinstalled it outside the Portal 2 folder now it has this after export:
![image](https://user-images.githubusercontent.com/54775074/64081949-2246ab80-cd08-11e9-889a-cf1e5fd6ef4c.png)

**Comment by Martin200HUN** [comment]
wait nevermind I solved it, I just deleted the BEEMOD2 folder from Roaming and have the program remake it, aparently something was messed up in there.
