### ISSUE TITLE
Saved Palette Categories

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#1178]
I would like a way to organize our palettes. Now that you can save your settings I've been saving map palettes. This will easily lead to a cluttered mess. I propose a simple collapsable menu with a title you can set. All the default palettes will go into their own menu. Also as it is now there is no way to manually sort palettes at the moment. 

![Palette Concept Art](https://user-images.githubusercontent.com/16567080/64388589-2a9f2f00-d005-11e9-816c-45534779fd14.png)

**Comment by Konclan** [comment]
Also, a way to rename palettes would be nice.

**Comment by TeamSpen210** [comment]
It's a little awkward, but to rename a palette you could load it, save as the new name, then delete the original. You could also add prefixes to the names, like `M - ` or something. It should support anything you can type in the box.
