### ISSUE TITLE
Mac version only accepts EXE files when adding a game

### ISSUE THREAD

**Issue by V0pT** [BEEmod/BEE2.4#1182]
It won't install on the mod's osx files and I can't find any exe files.

**Comment by V0pT** [comment]
There is no portal2.exe in the folder for either. There aren't any .exes at all. Just an _osx file.
Here, I'll attach a screenshot of the folder;

![index](https://user-images.githubusercontent.com/51463119/65442794-dbc20980-ddfa-11e9-9fed-aea18335db21.jpg)

**Comment by Konclan** [comment]
Can you even launch the game?

**Comment by Konclan** [comment]
It wouldn't even be an exe for you I don't believe

**Comment by Konclan** [comment]
![Capture](https://user-images.githubusercontent.com/16567080/65459497-a8d93f00-de15-11e9-8ea3-4e6a1e2cf3fc.PNG)

**Comment by TeamSpen210** [comment]
If BEE's requiring you to select the exe and Tag's not got one, just create a file in there and rename it. It doesn't actually matter, the file's just used to determine the directory.

**Comment by Luke18033** [comment]
In that case wouldn't the issue here be that the correct executable is being greyed out?

**Comment by TeamSpen210** [comment]
Yeah.

**Comment by V0pT** [comment]
Ah, so I just need to make a blank file. I got it, sorry. Still a bit new to all this stuff. Although I do wonder what you mean about Bee2 not being compatible with TwTM yet?

**Comment by TeamSpen210** [comment]
It doesn't have any support for it, so none of the time machine functions will work.

**Comment by Luke18033** [comment]
Mac isn't really being supported anymore
