### ISSUE TITLE
avbin.dll Permission Error (WinError 5)

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2.4#1183]
I use BEE2_4.35.1_win and BEE2_v4.35.0_packages and when I click on "Export to Portal 2" I get an error: http://imgbox.com/QObIf8dT 

Permission Error (WinError 5)

Setting bee.exe to "Run as Administrator" did not help

**Comment by Emma-Walker** [comment]
Oh, and another thing: The message "This has been copied to the clipboard" is wrong. The clipboard remains empty.

**Comment by TeamSpen210** [comment]
Don't extract BEE2 into the Portal 2 folder.

**Comment by Luke18033** [comment]
It would probably be a good idea to add a check for that on startup, to stop these kinds of issues from being opened.

**Comment by Luke18033** [comment]
Also...that's just a custom theme, you're not actually using Windows XP, right?

**Comment by Emma-Walker** [comment]
>Don't extract BEE2 into the Portal 2 folder.
Thx, that fixed it.

>It would probably be a good idea to add a check for that on startup, to stop these kinds of issues from being opened.
It would probably be enough to change the README.txt, which currently reads "1. Unzip to any desired location."

>Also...that's just a custom theme, you're not actually using Windows XP, right?
That's correct, well noticed! I love this old theme/skin.

**Comment by Emma-Walker** [comment]
>Don't extract BEE2 into the Portal 2 folder.

Thx, that fixed it.

>It would probably be a good idea to add a check for that on startup, to stop these kinds of issues from being opened.

It would probably be enough to change the README.txt, which currently reads "1. Unzip to any desired location."

>Also...that's just a custom theme, you're not actually using Windows XP, right?

That's correct, well noticed! I love this old theme/skin.
