### ISSUE TITLE
Fizzler edge textures not packing

### ISSUE THREAD

**Issue by Emma-Walker** [BEEmod/BEE2.4#1184]
**This issue will only affect people who play Beemod maps without having it installed,** and it happens to the following fizzlers:

* Vanilla Fizzler
* Laserfield
* Force Deflection Field
* Matter Inquisition Field
* Compressed Smoke Field
* Closed Solid Field
* Pysics Rhepulsion Field

### **Screenshot (make sure to see it in full resolution to understand where the issue is):**
![Custom Fizzlers Issue](https://user-images.githubusercontent.com/12244376/70306338-65bc2480-17e5-11ea-88db-e7d4c9a7f7fd.jpg)

**Comment by ZombiePwner1** [comment]
Missing edge texture that's what the problem is.

**Comment by Konclan** [comment]
Is this a packing error or a building error

**Comment by Konclan** [comment]
![20190923153123_1](https://user-images.githubusercontent.com/16567080/65460339-42edb700-de17-11e9-9f83-d2dc4a02fe19.jpg)
Packing Error

**Comment by Konclan** [comment]
Looks fine in PeTI but doesn't show up on the workshop

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
