### ISSUE TITLE
BEE2_4.35.1_mac Crash on start

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#1188]
Ver. 4.35.1 on Mac dont start anymore.
He Crash on last step (13/14 initialize UI) 
and Logoff me from OSX System. :-(
![Bildschirmfoto 2019-09-30 um 14 03 37](https://user-images.githubusercontent.com/18405990/65877211-5c4cb100-e38b-11e9-9261-ddca59f0b86a.png)

 Macos 10.14.6. 
stdout:
`[I] utils.setup_localisations(): Language: 'en_US'
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2":`

stderr:
`[W] sound.<module>(): ERROR:SOUNDS NOT INITIALISED!
Traceback (most recent call last):
  File "sound.py", line 52, in <module>
ModuleNotFoundError: No module named 'pyglet.media'; 'pyglet' is not a package
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/packages.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/item_cust_configs.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/games.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/item_configs.cfg" not found! Using defaults...
objc[1476]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff91e2c3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x114d98f50). One of the two will be used. Which one is undefined.
2019-10-13 07:24:52.819 BEE2[1478:12882] HIToolbox: received notification of WindowServer event port death.
2019-10-13 07:24:52.819 BEE2[1478:12882] port matched the WindowServer port created in BindCGSToRunLoop
2019-10-13 07:24:52.856 BEE2[1478:12884] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted`

The WindowServer event port death sounds pretty bad. 
Hope this helps. Thanks!

**Comment by amolloy** [comment]
I'm seeing this here, too. Macos 10.14.6. 
stdout:
`[I] utils.setup_localisations(): Language: 'en_US'
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2":`

stderr:
`[W] sound.<module>(): ERROR:SOUNDS NOT INITIALISED!
Traceback (most recent call last):
  File "sound.py", line 52, in <module>
ModuleNotFoundError: No module named 'pyglet.media'; 'pyglet' is not a package
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/packages.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/item_cust_configs.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/games.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "/Users/smolloy/Library/Preferences/BEEMOD2/config/item_configs.cfg" not found! Using defaults...
objc[1476]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff91e2c3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x114d98f50). One of the two will be used. Which one is undefined.
2019-10-13 07:24:52.819 BEE2[1478:12882] HIToolbox: received notification of WindowServer event port death.
2019-10-13 07:24:52.819 BEE2[1478:12882] port matched the WindowServer port created in BindCGSToRunLoop
2019-10-13 07:24:52.856 BEE2[1478:12884] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted`

The WindowServer event port death sounds pretty bad. 
Hope this helps. Thanks!

**Comment by TeamSpen210** [comment]
Could you attach `logs/BEE2.log`?

**Comment by amolloy** [comment]
Sure, here's both bee2.log and bee2.error.log:

[bee2.log](https://github.com/BEEmod/BEE2.4/files/3723867/bee2.log)
[bee2.error.log](https://github.com/BEEmod/BEE2.4/files/3723868/bee2.error.log)

Let me know if you need anything else, I'm happy to (try to) help. I'd also be happy to try anything if you have any suggestions to help track this down.

**Comment by Luke18033** [comment]
What's the status of the Mac version currently, since Portal 2 can't run on Catalina?

**Comment by TeamSpen210** [comment]
People who want to use it will have to avoid upgrading, so no change. I can fairly easily make it 64-bit if required, that's not a problem.

**Comment by Luke18033** [comment]
Did you ever figure out what the problem is here?

**Comment by Meowcat285** [comment]
For me it instantly logs me out of my system

**Comment by toby2006** [comment]
Hi! what exactly is the status on this issue? It's been about a month without what any update on what is a pretty serious bug hang Mac users being unable to use beemod.

**Comment by Luke18033** [comment]
We don't know why this happens, and don't really plan on supporting Mac anymore anyway.

**Comment by toby2006** [comment]
ok thanks

**Comment by LautaroL20** [comment]
@Luke18033 - Apply the corresponding label after closing an issue. On this case, this would be "invalid".

**Comment by mm12** [comment]
darn
