### ISSUE TITLE
Overgrown does not load textures

### ISSUE THREAD

**Issue by OmGCHOOCHOOTRAIN** [BEEmod/BEE2.4#1189]
Anytime I try to load a custom chamber in overgrown, it constantly gets a very short VBSP failed message saying "Could not load instance 'floor button black.vtf'." It also said fizzler_danger_base could not load, as well as barrier_base.

SIDE NOTE - The fizzler bases and doors/chamberlocks do not load correctly in overgrown,

**Comment by ZombiePwner1** [comment]
It's nothing to do with the textures it's missing instances. Are you sure you've installed Beemod correctly? As this tends to happen if beemod is installed incorrectly.

**Comment by Luke18033** [comment]
This would indicate that the BEE2 compiler is missing, since that instance should be replaced. It probably got overwritten by the Portal 2 update, you'll want to re-export.

**Comment by OmGCHOOCHOOTRAIN** [comment]
Ok, problem solved, only had to recompile.
