### ISSUE TITLE
Mixing Custom Items from Other Styles Into A Map.

### ISSUE THREAD

**Issue by alex-baker** [BEEmod/BEE2.4#1190]
If You Added Mixing Custom Items It Would Be Cool. And Add Variation In Peoples' Bee2.4 Puzzles.

**Comment by Luke18033** [comment]
Why do people want this so much?! This would look completely wrong, to have an Old Aperture button in Overgrown for example.

**Comment by alex-baker** [comment]
? like for instance clean doors in bts though would be great

**Comment by Luke18033** [comment]
Why?

**Comment by alex-baker** [comment]
could be good for decorating maps. like observation rooms

**Comment by Konclan** [comment]
BEEmod is not a replacement for hammer, if you’re looking for cool theme transitions or mixed style items you’ve come to the wrong place. Check our [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ) for more info which you should have read already before posting
