### ISSUE TITLE
Various property widgets use classic button style

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1191]
Similarly to #1148, the slider and timer widgets in the Item Properties pane still use the old beveled style from Windows 95.
![image](https://user-images.githubusercontent.com/19228201/66709411-789c0680-ed18-11e9-8e1b-032cd3d558be.png)
Modern sliders look like this:
![image](https://user-images.githubusercontent.com/19228201/66709415-95d0d500-ed18-11e9-8c78-17bff313a1c5.png)
And here's a modern timer (well not used as a timer here, but the layout is the same):
![image](https://user-images.githubusercontent.com/19228201/66709430-e0eae800-ed18-11e9-9502-1a8fbbb47468.png)
For reference, both of these can be found in the mouse properties menu in Control Panel.

**Comment by Luke18033** [comment]
This also affects the piston platform height sliders (and possibly other properties) in Change Defaults:
![image](https://user-images.githubusercontent.com/19228201/66709973-ee599f80-ed23-11e9-9adf-fae344f218db.png)
Oddly, the Timer Delay option actually uses a modern slider, though not the same one I showed in my original image. This one has a taller bar, and no tick marks.
![image](https://user-images.githubusercontent.com/19228201/66709986-2b259680-ed24-11e9-9268-5dcc60240361.png)

**Comment by Luke18033** [comment]
Color pickers also use the old style. I don't know of any modern version of this, though it should be pretty easy to make a custom one (pretty much the same thing just with no bevel, and maybe a bit bigger).
![image](https://user-images.githubusercontent.com/19228201/66710017-bdc63580-ed24-11e9-960d-ba3702122e21.png)

**Comment by TeamSpen210** [comment]
Basically, Tkinter (the widget toolkit I'm using) has two sets of widgets - the original set, which always have the same appearance (from that sorta era), and a themed set, which matches the OS but can't be customised as much necessarily. In some cases I have to use the former for a feature or something. It looks like for these I'm not though so I can switch them across. The color pickers are actually just a "text label" with a custom background. I can remove the 3D effect.

**Comment by TeamSpen210** [comment]
Fixed, excluding the timer widget (which doesn't allow you to type in the number properly).

**Comment by Luke18033** [comment]
What do you mean?

**Comment by TeamSpen210** [comment]
I have a special validator set which allows you to type into the Item Properties timers, disallowing invalid characters. But if I use the themed version it doesn't work and typing into the box becomes entirely wrong.
