### ISSUE TITLE
Remove "Item:" before name of item being moused over

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1192]
When mousing over an item, a label will appear at the bottom of the palette, which reads "Item: \<name of item\>".
![image](https://user-images.githubusercontent.com/19228201/66709483-4390b380-ed1a-11e9-8713-a22d0f98d915.png)
There's no way this could show the name of anything other than an item, and item names are displayed in this same location within the puzzlemaker, so having the "Item:" prefix is mostly redundant. It should be changed to only show the item name, and nothing else.

**Comment by Luke18033** [comment]
I don't see the commits for this or #1191, have you not pushed them yet?

**Comment by TeamSpen210** [comment]
Mustn't have, no.
