### ISSUE TITLE
Music and Voicelines fixes

### ISSUE THREAD

**Issue by A-PENCIL-SHARPENER** [BEEmod/BEE2.4#1194]
Ok, this should be fixed. Please add PeTi Music for Propulsion Gel Music and no Robot Waiting Room for Repulsion Gel Music.

**Comment by Luke18033** [comment]
I don't understand what the problem with the music is?

**Comment by KaziPlays** [comment]
I think that PeTI Propulsion Gel is missing, and he requested PeTI lobby Repulsion Gel music to be removed, because It is already used as base music.

The Air Supply transcript is a duplicate.

**Comment by KaziPlays** [comment]
https://github.com/BEEmod/BEE2-items/issues/3370 the same guy made this issue on BEE2-items

**Comment by Konclan** [comment]
Closing due to lack of clarification and also I don't think this is an issue anymore
