### ISSUE TITLE
Beemod Error N°13: Permission denied...

### ISSUE THREAD

**Issue by eeeee48** [BEEmod/BEE2.4#1195]
![image](https://user-images.githubusercontent.com/32681975/66726954-83e85280-ee3c-11e9-99fa-9ca8820e52f4.png)

Every time I try to export my chosen palette, I'm given this error. I've tried updating my Beemod but it doesn't help. This error happens no matter what items I choose.

**Comment by eeeee48** [comment]
So uhh… How do I fix this?

**Comment by LautaroL20** [comment]
Ask Spencer.

**Comment by Luke18033** [comment]
I have this issue randomly sometimes, relogging into Windows/restarting my PC seems to fix it for me.

**Comment by Wasserboy08** [comment]
Try running as administrator

**Comment by Luke18033** [comment]
Not sure what caused this.
