### ISSUE TITLE
Z-Fighting Antline (Overgrown)

### ISSUE THREAD

**Issue by alex-baker** [BEEmod/BEE2.4#1196]
![20191015070900_1](https://user-images.githubusercontent.com/56199317/66804729-2bd44d80-ef1b-11e9-9b0f-d7d8e996189b.jpg)
How did this happen?

**Comment by alex-baker** [comment]
![20191015070900_1](https://user-images.githubusercontent.com/56199317/66805050-f11ee500-ef1b-11e9-9b35-93c490e1fa5e.jpg)
![20191015071727_1](https://user-images.githubusercontent.com/5619931
![20191015071732_1](https://user-images.githubusercontent.com/56199317/66805056-f3813f00-ef1b-11e9-939d-cd68af9907b8.jpg)
![20191015071751_1](https://user-images.githubusercontent.com/56199317/66805062-f67c2f80-ef1b-11e9-844e-5d8a78485b76.jpg)

![20191015071746_1](https://user-images.githubusercontent.com/56199317/66805059-f4b26c00-ef1b-11e9-8759-7ca89be0b038.jpg)

7/66805055-f2501200-ef1b-11e9-830a-5c0bb7ce919b.jpg)

**Comment by TeamSpen210** [comment]
This is unfortunately just  a thing that happens. The sign is a thin surface, positioned just in front of the wall. When you're this far away, the distance between the two becomes too small for the renderer to keep track of, causing z-fighting. To fix this I need #1181 to nodraw that tile.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
