### ISSUE TITLE
About translation problems

### ISSUE THREAD

**Issue by Antecer** [BEEmod/BEE2.4#1197]
Hello, i found this program have so much word didn't have translation.
So, i want help you translation Chinese language.

and now, i have a problem about the `count_entity`, your string says 
"Removing complex moving items will help reduce this."
what is "this" in here? the file size or rendering performance or other?

**Comment by TeamSpen210** [comment]
The entity count itself, which is unfortunately a limit which crashes the game if you exceed. Thanks for helping with this!

**Comment by Antecer** [comment]
thanks for your fast repy!
can you add my steam? i think it will help we talk faster.
here is my steam add link: https://s.team/p/kkh-hvnm/bfbjgpbh

**Comment by Antecer** [comment]
Sorry, another question:
![image](https://user-images.githubusercontent.com/8684916/66920123-47437380-f055-11e9-98b1-dbc9d0fad104.png)
What does this `PeTI` mean?
I don't know how to translation it.
If you can tell me its full name, thank you very much.

**Comment by Luke18033** [comment]
It stands for Perpetual Testing Initiative, and is used to refer to the Puzzlemaker in this case.

**Comment by Antecer** [comment]
thanks, now i can get help from discord, it will faster.

**Comment by Luke18033** [comment]
I think this can be closed now.
