### ISSUE TITLE
BEE2.4 Crashes: "FileNotFoundError No such file or directory"

### ISSUE THREAD

**Issue by SirCheezburgerss** [BEEmod/BEE2.4#1200]
![Capture 1](https://user-images.githubusercontent.com/57203103/67986498-8bac4300-fc01-11e9-9b52-f9a765a155b6.PNG)

So, I've been using BEEmod for a bit recently.
Changing the style works as usual, but anytime I try to export a custom palette to Portal 2, it brings up a FileNotFound error, and BEEmod crashes.
I've tried having Portal 2 both open and closed, having the puzzlemaker open and closed, and looking up answers. I have the packages required. I got it to change the style of custom maps.
Am I supposed to be using Hammer for this?

**Comment by LautaroL20** [comment]
Could you post a picture showing the entire crash message?

**Comment by SirCheezburgerss** [comment]
![Capture 1](https://user-images.githubusercontent.com/57203103/67986498-8bac4300-fc01-11e9-9b52-f9a765a155b6.PNG)
Is this a File Not Found error?

**Comment by LautaroL20** [comment]
Yes, it is a weird crash.

**Comment by Luke18033** [comment]
Not sure what the problem is here, why is it looking for an FGD file in DLC2?

**Comment by TeamSpen210** [comment]
That is bizarre. It should be looking in the installation folder. Where did you unzip it to?

**Comment by akogut2009** [comment]
Having the same issue.
![error](https://user-images.githubusercontent.com/58014847/69291696-3f7d6e80-0bc1-11ea-8d33-7fa4344a7350.PNG)

**Comment by akogut2009** [comment]
![error 2](https://user-images.githubusercontent.com/58014847/69291838-9e42e800-0bc1-11ea-86b7-95a8f45dd126.PNG)

**Comment by TeamSpen210** [comment]
That's unrelated, see #1207,

**Comment by LautaroL20** [comment]
Closing this due to lack of response from the author. I think that there should be added a warning in the faq that says: An issue could be closed in case that the author does not respond to moderator´s questions related to the issue itself within a period of 4 days as most.

**Comment by LautaroL20** [comment]
Added the following to the contributing guidelines: **"An issue could be closed in case that the author does not respond to the owner (TeamSpen210) or moderator´s questions made in the comment section related to the issue itself within a period of 4 days as most."**
