### ISSUE TITLE
Full Music Tracks

### ISSUE THREAD

**Issue by alex-baker** [BEEmod/BEE2.4#1201]
Nothing much. just a suggestion for full music tracks for example: 9999999 (Full) Vit Order (Full) Out Of Order (Full) The Reunion (Full).

**Comment by TeamSpen210** [comment]
What does that mean exactly? The soundtrack files are mixed between various individual tracks ingame. We don't want to use it because they don't loop correctly, and would need to be packed into the map.

**Comment by Luke18033** [comment]
Closing due to lack of response
