### ISSUE TITLE
Standing Laserfields

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1206]
BEE2 has standing fizzlers, so I thought why not also have standing laserfields? Standing laserfields would be the same as standing fizzlers but with a laserfield.

**Comment by TeamSpen210** [comment]
I’m working on a revamp for that item which lets you make it any type of fizzler.

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2-items#3013
