### ISSUE TITLE
Game naming dialog does not appear when adding first game

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1211]
The game naming dialog will not appear in pre-release 36 when trying to add first game just after you select the location of `portal2.exe` ,here is a screenshot where i described the issue:

____________________________________________________________

![PRL36](https://user-images.githubusercontent.com/12244376/69401633-55c81f00-0cd4-11ea-814f-1508730f5152.png)
______________________

 ###  **HOW TO REPLICATE THIS ISSUE:** 

This issue will NOT occur if you were recently using a previous pre-release version (like prl35), so in order to replicate this issue, open Beemod PRL35 then run the option "Uninstall from selected game" and now try to launch the latest version (PRL36), you will see that just after you select the location of `portal2.exe` it will not bring you the game naming dialog, becoming stangnant forever in that situation... 

**I am using Windows 7 64 Bit professional.**

**Comment by Luke18033** [comment]
Huh...weird. This was changed to use a properly themed dialog, maybe it's broken on Win7 for some reason?

**Comment by LautaroL20** [comment]
Then R.I.P me and all the people who uses Windows 7 for just a new themed dialog? Beemod always worked perfectly well in Windows 7, there is still a good ammount of Beemod users with this OS so we hope that there is a possible fix for this issue.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Could this issue be related to Win7 users only? If so, could we have in the future a paralel version for Windows 7 compatibility the same way as there is a version for Mac users?

**Comment by King0191** [comment]
This is an also an issue on Windows 10

**Comment by LautaroL20** [comment]
King0191  - Glad to know that i am not the only person having this frustrating issue! Thank you for letting us know about this.

**Comment by King0191** [comment]
Indeed! There was someone else in the Discord with this issue. You select the .exe. Annnndd nothing happens. The selector goes away as it should then nothing happens.

**Comment by King0191** [comment]
![image](https://user-images.githubusercontent.com/37309250/69471740-d2a8d680-0d70-11ea-9b4b-341beda09d35.png)
It is interesting to note that BEE stays open in the background processes when this fails... So it's TRYING. It just CAN'T for some reason

**Comment by LautaroL20** [comment]
It is weird though, maybe is missing a librarly file (.dll) that Spencer forgot to include in this release that would help making this process work or something, who knows...

**Comment by Luke18033** [comment]
It worked fine in the dev version, so either TeamSpen broke it in the final commit, he forgot to include a file in the release, or it's an issue with specific editions/versions of Windows. Will test on my own PC later today.

**Comment by Luke18033** [comment]
Also @LautaroL20, just so you're aware, Windows 7 is no longer going to be supported at the start of next year, so you might want to think about upgrading.

**Comment by Luke18033** [comment]
Works fine for me, on Windows 10 1903.

**Comment by Luke18033** [comment]
...but only when adding a second game. If I delete `games.cfg`, then immediately add a game when starting the app, the dialog doesn't appear.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
I am having the same issue as others here, please @TeamSpen210, could you do a comprehensive testing on this subject so you can to find a possible solution? We would like to having a working version for the next release, since the only way to make the current release version work, is by running the past release so the new one would not have to find the game executable!

**Comment by TeamSpen210** [comment]
I found the problem, it's caused by fixing  #1148. That new dialog style doesn't work before the application is fully initialised, so I'll make it use the old code in this startup case.

**Comment by supersean08-pro** [comment]
> Also @LautaroL20, just so you're aware, Windows 7 is no longer going to be supported at the start of next year, so you might want to think about upgrading.

glad i moved to windows 10
