### ISSUE TITLE
I can't find Bottomless Pits Item

### ISSUE THREAD

**Issue by Voidliest** [BEEmod/BEE2.4#1212]
I can't find Bottomless Pits Item at all. Please help!

**Comment by LautaroL20** [comment]
This feature is not inside of a specific item, to enable the bottomless pit, you will have to select the skybox: "3D Factory".

**Comment by Luke18033** [comment]
Specifically, it replaces the lowest goo pit in the map.

**Comment by Voidliest** [comment]
okay. Thanks I got it :) :+1:
