### ISSUE TITLE
Rockets from Rocket Turret isn't visible!

### ISSUE THREAD

**Issue by Voidliest** [BEEmod/BEE2.4#1213]
Rockets from Rocket Turret isn't visible!

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

**Comment by Luke18033** [comment]
We don't need an item issue label, that's what issue transfer is for.

**Comment by LautaroL20** [comment]
Well, at least this label was needed while the transfer issue option was not available for contributors.

**Comment by Luke18033** [comment]
Which it has been for months, ever since it left beta?

**Comment by LautaroL20** [comment]
Probably since 2/3 months, yes.
