### ISSUE TITLE
Default palettes can be deleted

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1216]
When a custom palette is deleted, the next palette above it will automatically be switched to. If this is a default palette, the delete button will not be greyed out, allowing the palette to be deleted. It will reappear the next time the BEE2 is launched, since nothing is actually being deleted off the disk (except with Last Export).

**Comment by TeamSpen210** [comment]
Ooh, that's an oversight. I moved the default palettes into the code, so there's nothing at all to actually delete.
