### ISSUE TITLE
Custom music tool built into the app

### ISSUE THREAD

**Issue by Flametusk** [BEEmod/BEE2.4#1219]
Would it be possible to add a "browse for music" option, allowing you to use any music on your computer? For example, if someone wanted to use, say, the day music from terraria, or the main battle theme from a final fantasy game, or a custom piece of music?

**Comment by CassieCatYT** [comment]
Is this going to be done?

**Comment by FrozenDragon0** [comment]
> Is this going to be done?

Just because an issue hasn't been attended to doesn't mean it's inactive, just gotta be patient :)
