### ISSUE TITLE
Bee2.4 Wrong Crash Description (FileExistsError)

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1220]
This crash usually happens when you are trying to export the pallete, but another program already open a file into the Portal 2 folder, but the beemod text box description isn´t very helpful:

![crash](https://cloud.githubusercontent.com/assets/12244376/19409720/adc6953e-92b0-11e6-9d34-aa1a45cc6b51.png)

**Comment by TeamSpen210** [comment]
I don't really know where that comes from, errors always have the traceback?

**Comment by LautaroL20** [comment]
Well, this was an issue i´ve got about a long time ago in 2016, so i do not think i can recover its traceback log file. By that time, i had not even idea that log files existed and that should had been posted with the report, so if this issue can not be solved as it was originally reported, i think i should close this.
