### ISSUE TITLE
Suggestion: Add turret range to the "Item Properties" window.

### ISSUE THREAD

**Issue by PSIGuy** [BEEmod/BEE2.4#1223]
I was thinking of this while I was building one of my test chambers, but a slider to adjust the maximum range that a turret has in the Item Properties would be pretty useful when you want to extend or limit their range in certain situations.  It would function very similarly to the "Pellet Speed:" or "Funnel Speed:" sliders, except that the slider would have to start in the middle in order to both increase and decrease the range.  

We would would appreciate an in-game indicator as well. Maybe a marker on the floor (like the faith plate's bullseye), that shows where the attack zone of the turrets begins.

I don't know if the range's appearance could be altered in the editor itself to reflect a custom range, but a note mentioning how long one unit of space is would be enough to figure out how far a customized range goes.

**Comment by TeamSpen210** [comment]
I can’t edit the in-editor range, but the rest is doable.

**Comment by Zerarath** [comment]
I would appreciate an in-game indicator as well. Maybe a marker on the floor (like the faith plate's bullseye), that shows where the attack zone of the turrets begins.

**Comment by TeamSpen210** [comment]
That's more difficult. I wouldn't really suggest using the range of turrets explicitly, just block their line of sight with geometry/glass. It's far more clear to the player.

**Comment by Luke18033** [comment]
Doesn't look like this is being added
