### ISSUE TITLE
PS:Mel and Aperture Tag soundtrack not playing

### ISSUE THREAD

**Issue by republiccommando1138** [BEEmod/BEE2.4#1224]
### **The corresponding log files:**

[vbsp.log](https://github.com/BEEmod/BEE2.4/files/3919626/vbsp.log)
[vrad.log](https://github.com/BEEmod/BEE2.4/files/3919629/vrad.log)

_________________________________________________

I've created a map that uses the overgrown style and I am hoping to use Troubled Water for the soundtrack. However, whenever I export to Portal 2, the soundtrack does not play at all. I have tried this with other tracks from both PS:M as well as Aperture Tag, both of which I have installed, and the same thing happens. I am using version 2.4.36.0 on OS X. Any help would be appreciated.

**Comment by Luke18033** [comment]
It might be broken on Mac, that version doesn't really get tested as much since most people here use Windows.

**Comment by republiccommando1138** [comment]
If it helps, here's the log of what went on in Terminal when I tried exporting.

[Terminal Saved Output.txt](https://github.com/BEEmod/BEE2.4/files/3919537/Terminal.Saved.Output.txt)

**Comment by TeamSpen210** [comment]
Could you attach `~/Library/Application Support/Steam/steamapps/common/Portal 2/bin/bee2/vbsp.log` and `vrad.log` in that folder?

**Comment by republiccommando1138** [comment]
Here you go

[vbsp.log](https://github.com/BEEmod/BEE2.4/files/3919626/vbsp.log)
[vrad.log](https://github.com/BEEmod/BEE2.4/files/3919629/vrad.log)

**Comment by republiccommando1138** [comment]
[Here](https://steamcommunity.com/sharedfiles/filedetails/?id=1918605550)'s a link to another map I tried the same thing with, if that helps

**Comment by supersean08-pro** [comment]
> It might be broken on Mac, that version doesn't really get tested as much since most people here use Windows.

im on Microsoft surface pro and its happening still, and before there wasn't any pellet for the music, and did you even put the audio file in

**Comment by Luke18033** [comment]
What?

**Comment by supersean08-pro** [comment]
> What?

yea i know im stupid at scripting even though i almost watched two hours of a building stream of one of your friend trying to make a clean version of the blue platform conveyor thing

**Comment by Luke18033** [comment]
Your comments make no sense, this has nothing to do with scripting, or "blue platform conveyors".

**Comment by Luke18033** [comment]
Mac isn't really being supported anymore
