### ISSUE TITLE
There's an extra row in All Items if the number of items evenly divides the column count.

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2.4#1225]
Silliest most minor bug ever, but if your "All Items" palette fills up the last row exactly, BEE adds an extra row of blank icons:

![image](https://user-images.githubusercontent.com/2068021/70207284-53b08800-16f8-11ea-9c6e-f77fede9cdd8.png)

BEE 4.36.1

**Comment by King0191** [comment]
Is it possible this is a placeholder bar left for future items? I've seen many softwares leave a empty slot (or multiple) as a placeholder for future features and the like.

**Comment by Luke18033** [comment]
There wouldn't be any need for that, the item list automatically expands to the number of items present.

**Comment by GiovanH** [comment]
Can confirm, experiencing the same issue.
