### ISSUE TITLE
Connection signage compiler crash

### ISSUE THREAD

**Issue by FierceThundr** [BEEmod/BEE2.4#1226]
I've been working on a map recently and found that using the connection signage consistently breaks the compiler. Even when it is placed in the default map with no additional objects. I can provide details as needed.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
