### ISSUE TITLE
i installed thinking with time machine and now BEE2 isnt working

### ISSUE THREAD

**Issue by cepcepfromdiscord** [BEEmod/BEE2.4#1228]
i think it has to do with TWTM's level editor and its new files

anyone know what i should do

**Comment by ZombiePwner1** [comment]
BEE2 Isn't 100% compatible with TWTM yet.

**Comment by Luke18033** [comment]
Indeed, there's no compatibility implemented. So you won't get the time machine, the proper style doesn't exist, and other things might be broken. The best thing to do would be to open BEE2 and choose `File > Uninstall from Selected Game`. If things are still broken, try validating the game files.

**Comment by Luke18033** [comment]
Closing due to lack of response
