### ISSUE TITLE
Overgrown: Map coordinate extents are too large - Cause:cutout tiles

### ISSUE THREAD

**Issue by BlueVapor1234** [BEEmod/BEE2.4#1236]
I cant build a puzzle and this seems to be the problem. 
[I] <valve>.vbsp(): Brush 67542: no visible sides on brush
[I] <valve>.vbsp(): Brush 67542: no visible sides on brush
[I] <valve>.vbsp(): Brush 67542: no visible sides on brush
[I] <valve>.vbsp(): Brush 67585: no visible sides on brush
[I] <valve>.vbsp(): Brush 67585: no visible sides on brush
[I] <valve>.vbsp(): Brush 67585: no visible sides on brush
[I] <valve>.vbsp(): Could not open instance file chamberlock_black.vmf

**Comment by BlueVapor1234** [comment]
![newchamber0000](https://user-images.githubusercontent.com/59751544/72194540-90486100-33d3-11ea-927c-989c5916539d.jpg)
Here is a screenshot

**Comment by Flash4433** [comment]
This post should be posted in https://github.com/BEEmod/BEE2-items . Don't worry, a mod should move this issue soon.

Those brush errors are pretty strange, might be a glitched item?... Could you list your items? And your map is SP right?

And this is the second (or more) time this chamberlock error happens. I just checked [here](https://github.com/BEEmod/BEE2-items/tree/0ceb98d8656788f8078ab94e02df02b757ebb528/packages/tspen/checkpoint), and the .vmfs aren't there. In the meantime, you can make some sort of DIY chamberlock, with a door and a absolute fizzler or normal fizzler.

**Comment by BlueVapor1234** [comment]
The map is SP, the items are Autoportal, retractable pedestal button, cut out tile, pellet emiter/carcher, infinite pellet, the pneumatic diversion tube 1x1, half tiles, and warm lights.

**Comment by BlueVapor1234** [comment]
Did the DIY Chamberlock and starts to load fine but then has an error downloading some file.
![newchamber0000](https://user-images.githubusercontent.com/59751544/72208473-93416100-3468-11ea-84b6-ae226d75f3fc.jpg)
![snapshot0001](https://user-images.githubusercontent.com/59751544/72208474-963c5180-3468-11ea-83bf-171f2f5124c1.jpg)
![snapshot0002](https://user-images.githubusercontent.com/59751544/72208476-98061500-3468-11ea-9d50-4b1c8091a71a.jpg)

**Comment by Flash4433** [comment]
I never have seen that error... Uhm... Have you tried checking local files through Steam (So Steam redownloads anything that's broken) and reexporting the files with BEE2?

**Comment by BlueVapor1234** [comment]
I'll try that now.

**Comment by BlueVapor1234** [comment]
It's still happening.

**Comment by Luke18033** [comment]
Compiling maps doesn't download anything or connect to the internet at all, that error just means a workshop item failed to download and is completely unrelated to this. It looks like it's working fine in your first screenshot there? (showing the compile progress window)

**Comment by BlueVapor1234** [comment]
It starts fine then once done loading lights it does 1 of 10 loaded bubbles then falls to zero and remains at zero even for upwards of 15 minutes.

**Comment by Luke18033** [comment]
Oh, it's the map coordinates error. No idea why that happens, validate your game files and re-export.

**Comment by BlueVapor1234** [comment]
ok then

**Comment by Luke18033** [comment]
If that doesn't fix it, upload a copy of `Portal 2/sdk_content/maps/styled/preview.vmf` so I can check out the map in Hammer.

**Comment by BlueVapor1234** [comment]
Ok got it.

**Comment by BlueVapor1234** [comment]
Validating now

**Comment by BlueVapor1234** [comment]
8 failed now re exporting

**Comment by BlueVapor1234** [comment]
Ok its not working I'll upload the preview.

**Comment by BlueVapor1234** [comment]
wont let me upload.

**Comment by BlueVapor1234** [comment]
![preview - Copy](https://user-images.githubusercontent.com/59751544/72210071-8c701980-347b-11ea-86ef-0ebc9f04252e.png)
convert it back to vmf when you get it

**Comment by BlueVapor1234** [comment]
I opened it in hammer and nothing seems that wrong.

**Comment by BlueVapor1234** [comment]
![image](https://user-images.githubusercontent.com/59751544/72210135-49fb0c80-347c-11ea-9f47-3a68054fb856.png)

**Comment by Luke18033** [comment]
I need the version in `styled/`, the one in `maps/` doesn't include any of the BEE2 stuff.

**Comment by BlueVapor1234** [comment]
Got it

**Comment by BlueVapor1234** [comment]
![preview - Copy](https://user-images.githubusercontent.com/59751544/72210238-f12c7380-347d-11ea-9995-cbebd4554e21.png)

**Comment by BlueVapor1234** [comment]
There are 2 invalid solids.

**Comment by BlueVapor1234** [comment]
I found something weird

**Comment by BlueVapor1234** [comment]
![image](https://user-images.githubusercontent.com/59751544/72210290-ab23df80-347e-11ea-963a-f1eff4af7bf6.png)

**Comment by BlueVapor1234** [comment]
![image](https://user-images.githubusercontent.com/59751544/72210308-e58d7c80-347e-11ea-8746-9c3daafc8e6a.png)

**Comment by Luke18033** [comment]
I'm not sure exactly what the problem is. There are two invalid brushes in the map, but Hammer annoyingly has no way to figure out where they are. To start off I'd suggest removing any cutout tiles from the map, they tend to be buggy and could be causing some sort of invalid brush geometry.

**Comment by BlueVapor1234** [comment]
Ok I'll do that and see if it works

**Comment by BlueVapor1234** [comment]
It loaded, the problem is the cutout tiles and chamberlock.

**Comment by BlueVapor1234** [comment]
I'm good to close it then?

**Comment by LautaroL20** [comment]
This is a duplicate of this though: https://github.com/BEEmod/BEE2-items/issues/3153
Also, you are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

**Comment by Luke18033** [comment]
Not a duplicate, the cutout tile was completely unrelated.

**Comment by LautaroL20** [comment]
Remember that people must not post combined issues when they are not related to each other.
