### ISSUE TITLE
ı have dll error and problem with game files

### ISSUE THREAD

**Issue by ustayussuf** [BEEmod/BEE2.4#1237]
### **Full** details of my system where i am running Beemod: [DxDiag.txt](https://github.com/BEEmod/BEE2.4/files/4059561/DxDiag.txt)

________________________________________________________________________________________________

first error
![image](https://user-images.githubusercontent.com/56765276/72264817-69389c00-362c-11ea-9b8c-b1105b1908e4.png)
after this error
![image](https://user-images.githubusercontent.com/56765276/72264874-85d4d400-362c-11ea-8802-0aaefff80b33.png)
plase help
BEE mod version=2.4.36.1
OS Version=Windows 8.1 32bit
System Language=Turkish

**Comment by LautaroL20** [comment]
Who knows what the hell is causing that weird issue... It will require more info most likely.

**Comment by ustayussuf** [comment]
more info???

**Comment by Luke18033** [comment]
This is the first time I've seen this particular system configuration here, maybe that's related? 32 bit OSes should work fine now, but I'm not sure how much the app has really been tested on Windows 8. We'll see what TeamSpen says about this.

**Comment by Flash4433** [comment]
Just wanna say BEE2 is working perfectly on my Windows 8 Beta 64bit.

**Comment by ustayussuf** [comment]
[DxDiag.txt](https://github.com/BEEmod/BEE2.4/files/4059561/DxDiag.txt)

**Comment by ustayussuf** [comment]
ı downloaded required dll files and this error appeared now
![image](https://user-images.githubusercontent.com/56765276/72450114-dc781480-37ca-11ea-9efb-98e944054147.png)

**Comment by Flash4433** [comment]
Download this file https://pt.dll-files.com/download/1b171f9a428c44acf85f89989007c328/vcruntime140.dll.html?c=RHdGL0hkNTduU0NLWjNvdmpZalNYdz09

Sorry, it's in Portuguese. Just wait 5 seconds and it should download the file. Just put it in your BEE2.4. folder. I think it's E:\ÍndirilenlerE\BEE2_4.36.1_win\VCRUNTIME140.dll .

**Comment by ustayussuf** [comment]
:( I look evary site bu ı cant found solution of python36.dll LoadLibrary error

**Comment by Flash4433** [comment]
Put this on your BEE2.4. folder too, I guess.

https://pt.dll-files.com/download/57851745c259c29563e2de42acf19cc1/python36.dll.html?c=cDlEdzJQcDVhajhTQnRRSklrWEUzQT09

**Comment by TeamSpen210** [comment]
I'd highly advise never downloading random dlls from those sorts of sites, they're likely viruses or otherwise malicious.

**Comment by TeamSpen210** [comment]
Both those DLLS should be in the download, if not, check older ones in case I forgot it?

**Comment by Flash4433** [comment]
I'm sorry, I'm used to these kinds of issues so I always use that website. Anyways, last time I checked [2.4.35.1](https://github.com/BEEmod/BEE2.4/releases/tag/2.4.35.1) had the python36.dll.

Here's the [python36.dll](https://github.com/BEEmod/BEE2.4/files/4078996/python36.zip) of that app version. Remember to extract it first. Hope it helps.

**Comment by ustayussuf** [comment]
ı tried but not working

**Comment by LautaroL20** [comment]
The first image would indicate that you are probably missing Visual C++ Redistributable or other important driver packages for your system. Try installing that and combine it with the latest BEE2 release and this should not happen to you anymore.
