### ISSUE TITLE
"Copying compiler file failed. Ensure the Portal 2 is not running" Error

### ISSUE THREAD

**Issue by SospectGuy58** [BEEmod/BEE2.4#1238]
Hello, this is my first post here on the BEE2 GitHub.

Everytime I try to export any palette to Portal 2, I get this error:
![90a06809de085d9096ceffe7dd29fd05](https://user-images.githubusercontent.com/59539549/72629807-54704700-3951-11ea-976b-eece1065a472.png)

Yes, I tried reinstalling, verifying Portal 2's cache, redownloading the packages, but nothing changes.
Help would be appreciated. Thanks!

EDIT: No there's no Portal 2 tasks running in background. Forgot to say that.

**Comment by LautaroL20** [comment]
WUT, if you already tried verifying, redownloading, etc, and nothing helped maybe your antivirus could be blocking some important files that causes Beemod to export the palette appropriately?

By the way: "Ensure the Portal 2 is not running".... lol dat typo.

**Comment by SospectGuy58** [comment]
Nope, my antivirus isn't blocking anything. Also yeah, I noticed that typo too lmao

**Comment by SospectGuy58** [comment]
I guess I'll just give up. Should I close this?

**Comment by Flash4433** [comment]
No, of course not. That error usually happens because something isn't letting BEE2 copy the files. Wild guess but try running BEE2 as administrator or/and checking if that file even exists.

**Comment by SospectGuy58** [comment]
Alright, I will try running as admin. The file exists tho

**Comment by SospectGuy58** [comment]
New problem:
The exporting thing works, no errors occur, but resources and music don't get exported, their process gets skipped. "Preserve Game Directories" is unchecked, so I don't understand why that happens.

**Comment by SospectGuy58** [comment]
Oh thank God it worked. Thanks so much for helping guys!
(Small disclaimer, is it normal that the "Backup Puzzles" process is skipped? It's not a problem anyway, I have a separate folder with my puzzle files saved)

**Comment by Flash4433** [comment]
You got it to export files? Nice.

Normally Backup Puzzles isn't skipped if there's a new puzzle that hasn't been backed up. I think the setting for Backup Puzzles is somewhere on the Settings.

**Comment by SospectGuy58** [comment]
Oh thanks. I will check it out.

**Comment by LautaroL20** [comment]
So, the problem here was that you were run Beemod without administrator permission?

**Comment by SospectGuy58** [comment]
Yes, and some files were deleted by BeeMod when launching it.
