### ISSUE TITLE
Mac version still crashes with basemodui.txt error

### ISSUE THREAD

**Issue by tellyworth** [BEEmod/BEE2.4#1239]
The `/releases/tag/2.4.36.1_` release includes only `BEE2_4.36.0_mac.zip`, rather than `BEE2_4.36.1_mac.zip` as you would expect.

**Comment by Luke18033** [comment]
Not an issue, that patch only applied to Windows.

**Comment by tellyworth** [comment]
Issue #1234 occurs in 4.36.0 on Mac. The [suggested fix](https://github.com/BEEmod/BEE2.4/issues/1234#issuecomment-572374628) in that issue is "update BEE2".

What version should I update to, if not 4.36.1?

**Comment by Luke18033** [comment]
Huh, that should have been fixed in the main release. 4.36.1 was a Windows specific update, to fix #1211.

**Comment by Luke18033** [comment]
@TeamSpen210 You might want to test/fix this?

**Comment by Luke18033** [comment]
As a workaround, open that file (`Portal 2/portal2/resource/basemodui_english.txt`, regardless of your language) and add an extra `}` on a new line at the end.

**Comment by Luke18033** [comment]
Sorry, you'll want to do that with the version in `portal2_dlc2` instead.

**Comment by Luke18033** [comment]
Bump.

Don't you think this is kind of a major issue...

**Comment by Luke18033** [comment]
Does this still happen?

**Comment by Luke18033** [comment]
This would no longer happen in 4.37. But Mac isn't really going to be supported anymore.
