### ISSUE TITLE
The default palette is "Aperture Tag"

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2.4#1243]
Minor one. In a fresh install of BEE2, the default palette is Aperture Tag, probably because it's the first one alphabetically. I would expect the default one to be "Portal 2".

**Comment by LautaroL20** [comment]
Finally a person that has experimented the same issue i had, see: https://github.com/BEEmod/BEE2.4/issues/605

I thought it was fixed but seems not.

**Comment by LautaroL20** [comment]
I think that this is no longer an issue on BEE2 Version 4.40.2
