### ISSUE TITLE
Something about energy pellets isn't precached

### ISSUE THREAD

**Issue by quat1024** [BEEmod/BEE2.4#1244]
There's a noticeable lag when spawning an energy pellet for the first time in a map. It's similar to turning on a light bridge for the first time in vanilla Puzzlemaker maps.

It would be nice if BEE could fix this, just like it did with the light bridge end particle caching issue.

(I don't know if you have a general purpose "this bee item preloads these assets" system you could hook into, in which case I should probably put this in the -items repo. feel free to transfer if you do)

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
