### ISSUE TITLE
Selector window descriptions and tooltips appear in all bold text

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1247]
The descriptions of items in selector windows, and tooltips when hovering over stylevars, always appear in bold text. TeamSpen said on Discord that this was a bug, putting it here so we can keep track of it.

Selector windows:
![BEE2_2020-01-25_14-54-22](https://user-images.githubusercontent.com/19228201/73128340-a3862f80-3f82-11ea-94a2-b45aee196992.png)
Tooltips:
![BEE2_2020-01-25_14-54-35](https://user-images.githubusercontent.com/19228201/73128342-a4b75c80-3f82-11ea-8a58-c1aece2dafa7.png)

I'm not sure if anything else is affected by this issue, but fixing this would probably also fix those, so I don't think we really need to worry about that.

**Comment by LogicDeLuxe** [comment]
Might be related: In Wine, the description text and the tooltips are unreadably tiny, not honoring the system settings. Anything else is presented with the expected font size and style.

**Comment by Luke18033** [comment]
Seems to now be fixed.
