### ISSUE TITLE
This window wont show up on beemod 

### ISSUE THREAD

**Issue by ChetIsNotGoodAtGames** [BEEmod/BEE2.4#1250]
The Export Options window never shows up I need it for the themes and music and stuff.

**Comment by LautaroL20** [comment]
Did you tried clicking on the button of the following image of below to see if the panel appears again:

![Export button](https://user-images.githubusercontent.com/12244376/73425225-bcd70500-430f-11ea-89e3-269b5b1bbf72.png)

**Comment by ChetIsNotGoodAtGames** [comment]
Thank you.

**Comment by LautaroL20** [comment]
No problem.
