### ISSUE TITLE
How to install BEE2 I have error 0xc000007b

### ISSUE THREAD

**Issue by Byllfighter** [BEEmod/BEE2.4#1251]
Who can help me? How to install BEE2. I have error 0xc000007b

**Comment by LautaroL20** [comment]
Get in contact with the developers of Beemod and their community at the Discord server, so they can help you. Link to the server: https://discordapp.com/invite/hnGFJrz

**Comment by TeamSpen210** [comment]
Can you post the rest of the error message?

**Comment by CoolStuff08** [comment]
That probably means that you are on a 32-bit system. You need a 64-bit OS for this to work

![image](https://user-images.githubusercontent.com/35200979/74736724-5dd72280-5221-11ea-8b16-8cf6c1721e6d.png)

**Comment by Luke18033** [comment]
BEE2 should work fine on 32-bit systems, at least since the switch to PyInstaller. Are you using the latest version?

**Comment by Luke18033** [comment]
Closing due to lack of response
