### ISSUE TITLE
Laser Collision Off bug

### ISSUE THREAD

**Issue by SteemStream** [BEEmod/BEE2.4#1253]
The laser collision off setting in the item properties tab has an issue of seemingly only applying once in a map, once you toggle sv_cheats off, or reload a save the laser collision turns back on.

**Comment by LautaroL20** [comment]
@SteemStream - You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
