### ISSUE TITLE
Fix the Line Count in "Error occurred on line X"

### ISSUE THREAD

**Issue by Flash4433** [BEEmod/BEE2.4#1254]
Hi there. While testing out some packages, I noticed that sometimes, when BEE2 has an error, the line in "Error occurred on line X" is wrong. It sometimes it's correct, sometimes it seems like it's the correct number + 2. Examples are shown below. 

Wrong:
![image](https://user-images.githubusercontent.com/38331230/74593606-d0c77a00-5024-11ea-9aa5-5eeb102b3929.png)
![image](https://user-images.githubusercontent.com/38331230/74593991-37e72d80-5029-11ea-89ba-dca8552e6dd8.png)

Correct:
![image](https://user-images.githubusercontent.com/38331230/74593917-6ca6b500-5028-11ea-800d-0d3c5ca02ff0.png)
![image](https://user-images.githubusercontent.com/38331230/74594002-5cdba080-5029-11ea-94bc-7a4f395b731c.png)

**Comment by TeamSpen210** [comment]
It's not actually incorrect, it's the the line where it discovered the error. For the first example, strings can be multiline, so the braces could have been part of the text. It only determined there was an error when it got to the end of the file and still hadn't seen the closing quote. For the second, all those braces are correct (indentation is entirely ignored), up until it finds the one extra brace.

**Comment by Flash4433** [comment]
Oh, I see. But why doesn't it count strings as multi-line in the other two "correct" examples? Just curious.

**Comment by TeamSpen210** [comment]
Because the string isn't multiline: 
```c
"Property"
    {
    "Multi" "line string
   With more text
Down here including
   {}}}{}{}{
"
    "Next" "property"
    }
```
