### ISSUE TITLE
Building Geometry is infinity

### ISSUE THREAD

**Issue by 102182123** [BEEmod/BEE2.4#1256]
I have not a license. When I want to rebuild the puzzle, it freeze on building geomerty PLEASE HELP
Screenshot:
![выфв](https://user-images.githubusercontent.com/61122724/74611671-a3eb9380-5106-11ea-9e63-b1fc3ed7c017.JPG)

P.S. Test chamber is just a test for screenshot, it freeze in every puzzle

**Comment by Luke18033** [comment]
You...don't have a license? What? Probably just some sort of translation error, though I will point out that we don't support using BEEmod with pirated/cracked versions of Portal 2, in case that's what you're referring to.

**Comment by Luke18033** [comment]
You should also post the console log, generic errors like this aren't helpful on their own.

**Comment by 102182123** [comment]
Okay, i buy the license now

**Comment by Luke18033** [comment]
I'm still pretty confused, I guess they did pirate the game?

**Comment by 102182123** [comment]
Yes, im pirtated the game

**Comment by Luke18033** [comment]
In that case I'm going to close this (for now anyway)

**Comment by LautaroL20** [comment]
@102182123 - I think that the fact that explains the issue you are having is the following: pirated stuff usually do not get patch updates so they ends up outdated as hell. Most part of Beemod´s compilers are builded matching up the latest Portal 2 patches that the game got in the recent time. I highly recommend you to wait for a Steam sale offer and buy Portal 2 at a cheap price so you will have zero issues when using Beemod.
