### ISSUE TITLE
"initializing" is spelled wrong while its on the loading ui

### ISSUE THREAD

**Issue by Meltinglce** [BEEmod/BEE2.4#1257]
title says all

**Comment by CoolStuff08** [comment]
![image](https://user-images.githubusercontent.com/35200979/74736611-28323980-5221-11ea-979f-d205f17d1680.png)

**Comment by Luke18033** [comment]
That's just an alternate spelling I think, not exactly wrong.

**Comment by Luke18033** [comment]
Indeed, this is just the British spelling.
