### ISSUE TITLE
Prevent BEE2 from running if installed in Portal 2 directory

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1258]
Installing BEE2.4 within Portal 2's directory (`Portal 2/bee2` in particular, since this is used for the searchpath) has caused various errors for people. The app should detect when this is the case, and display an error message on startup explaining that it needs to be in a different location.

**Comment by vithorte** [comment]
so uhhh i can't unistall because beemod wont let me

**Comment by vithorte** [comment]
oh nevermind fixed! :D
