### ISSUE TITLE
Bee2 won't load

### ISSUE THREAD

**Issue by Wheatley1723** [BEEmod/BEE2.4#1259]
I've been trying to open Bee2 so I can change my map items back to normal, but it keeps crashing at the last loading bar, and I cannot open it, so am I like, stuck with my current tools forever???

It says "File ended with at least one property that didn't have an ending '}'" and "Error occurred with file 'basemodui.txt'"

**Comment by LautaroL20** [comment]
Did you install Beemod in the same folder of Portal 2?

**Comment by Luke18033** [comment]
Update to the latest version of BEE2, Valve broke that file in a Portal 2 update.

**Comment by Wheatley1723** [comment]
How do I update it?

**Comment by LautaroL20** [comment]
Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).
