### ISSUE TITLE
Where music?

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2.4#1260]
Hello))) I have downloaded **Aperture tag** and **Portal Stories Mel** _but why from these mods does not play music in the tests_ ( I chose music from these mods but the music in the test did not play) _**please fix it**_

**Comment by supersean08-pro** [comment]
i dont really know

**Comment by Konclan** [comment]
Please don't comment on month old issues with literally nothing to add

**Comment by Konclan** [comment]
This issue is missing information and I'm pretty certain this issue has been brought up somewhere else.
