### ISSUE TITLE
Multiple Alternate Version System

### ISSUE THREAD

**Issue by Flash4433** [BEEmod/BEE2.4#1261]
Alternate Versions is a really useful system that's not used that much by BEE itself. Certain items, like the Turret, could definitely have alternate versions since, with a simple key-value change, it can become a backwards turret, a no-shell turret or a turret box. The backwards turret should be it's own item, as it has the ability to fire backwards, and could definitely have a puzzle purpose, like killing other turrets, but I'll add it first to the Retro Package to see how it works, and perhaps do the needed model changes. Anyways...

I also think the Alternate Versions system can be upgraded. Right now you can only choose one version per palette, which definitely decreases the amount of possible uses it could have. I thought of two ways this system could be improved.

My first idea and simplest is to allow the player to have two or more alternate versions on a single palette. This could be made by simply choosing a version of an item and putting it on the palette, then changing to another version and put it again on the palette. Right now as soon as you change versions it automatically changes the ones on the palette too.

My second idea and harder, but more useful is to allow the user to add a property to the item, and being able to choose what version it becomes if the chosen property has a certain value. For example, if the checkbox is unchecked it becomes a normal turret. If the checkbox is checked it becomes a broken turret. The player could choose from one or more checkboxes, `button_type`, `cube_type` or even the timer...
 BEE2.4. would also need to check if the chosen property/ies aren't being used by the item, and if the Item's Type even supports it. (Items with no type would make BEE2.4. add the needed type and changes, for example a `itemButtonFloor` with the proper instances paths)
 Again, a good example of something that could improve with these suggestions would be Saismee's turret alternate version package. The user could choose what property it would use to switch between versions, in this case, `cube_type`, and if the selected value is of something it would change into the proper version. 
 
Both of these ideas should be implemented together. Of course, they can certainly be improved.

**Comment by TeamSpen210** [comment]
Unfortunately this doesn't really make sense if you know how the versions system works. What it does is entirely swap out the item definitions exported, so the item is replaced by the alternative configs. They are the same item, with the same item ID and everything. To allow them to simultaneously be on the palette, you'd have to somehow rename one so they have different IDs, and go through all the configs to fix up the names in there. 

Even if I did that, you'd end up with items in your maps swapping versions depending on how you set the palette. For the second suggestion, there's no need to do this - `vbsp_config` already has the capability to swap instances like how you're requesting. I cannot automatically do that sort of thing - the conditions in the item has to be built to accommodate the item swapping instances. I cannot know how the original item is designed and whether swapping is safe.

**Comment by Flash4433** [comment]
After thinking about this for a while, I remembered that Alternate Versions can change their own properties, so it's part of the Alternate Version to enable access to the normal version if needed, just like Saismee's package.

Either way, the Alternate Versions is truly a great system, and I wish it was used more for, for example, different models or skins.
