### ISSUE TITLE
Some of my suggestions that I think are possible

### ISSUE THREAD

**Issue by ghuntbook** [BEEmod/BEE2.4#1262]
These are in order of necessity:

1. Combine the Angled Panel, Flip Panel, Drawbridge and Half Panel into one item. Add a Piston Panel to this list also.
2. Combine Faith Plate and Large Faith Plate into one item, and make the Faith Plate able to turn off.
3. Combine Glass/Grating and Small Hole Glass into one item.
4. Disable the player hitbox while in a vactube, or vise-versa, so they don't get stuck.
5. Give triggers a timer feature which determines their shape (full, half, quarter, vertical, horizontal etc.)
6. Give Pedestal Buttons, Left-Middle-Right Buttons and Protruding Buttons a start enabled feature which determines if they do the clock sound when timed.
7. Add an Angled Panel with an Auto-Portal on it.
8. Add Relaxation Vault. The Player would spawn there instead.
9. Combine all the fizzlers from the same person into one item.
10. Add Bombs like at the end of Portal 2, that come out of a cannon when receiving a signal. Timer determines how many come out. Can break glass.
11. Combine the Toggle Latch and the Logic Gates into one item.
12. Add Bomb Detectors that output a signal when detecting a Bomb explosion nearby.

I don't really care if 7-12 don't get added though.

**Comment by Luke18033** [comment]
Please read the contributing guidelines. You shouldn't combine issues like this, and it isn't even on the right repository.

**Comment by Luke18033** [comment]
Although, to respond to some of your suggestions:
- In order for items to be combined, they need to all share the same properties and collisions. Pretty much the only thing that can be combined but hasn't is [custom fizzlers](https://github.com/BEEmod/BEE2-items/issues/1596).
- Partial triggers were suggested in BEEmod/BEE2-items#300
- BEEmod/Puzzlemaker isn't for stories, I don't think a relaxation vault item will be added
- Bomb droppers are listed in BEEmod/BEE2-items#95

**Comment by Flash4433** [comment]
To respond to all of your suggestions:

1. Like Luke18033 said, they need to have the same properties and collisions. Also, those 5 items vary a lot from the others. Every single one of them.
2. Again, collision problems. However, a connection system to the Faith Plate would be cool.
3. Again, the Glass and Small Hole are completely different items, and wouldn't work that well together. I think the items' organisation is fine as it is, there's no need to add them all together, except the Custom Fizzlers.
4. This could cause issues and I'm not even sure if it's possible (without using cheats), but yeah, it would be cool to have a player transporting vactube.
5. There's really no need for that, but different sized triggers could be their own item. Not sure for what you would do with them tho.
6. The clock sound notifies the player that the button is on a timer, and it wouldn't be helpful at all to simply remove that.
7. Certain items, like Portal Magnets and hopefully Auto-Portals too are planned to work on Angled Panels when the Geometry branch is finished.
8. Could be a cool entrance for Portal 1 Style.
9. There's already a plan for something like that, like Luke said.
10. I'm already working on a bomb dropper in the Retro Package. They're fully functional, but don't explode glass, of course. After Breakable Glass is finished we can add that functionality. Also, saying the number of bombs it will drop isn't needed at all. We just use the normal drop speed Wheatley uses, and it works fine. The bombs work kinda like Gel: they can go through portals and bounce on faith plates, and explode upon contact with a surface. Fun item.
11. Like, they're super different.
12. Can bomb explosions or env_explosion be even detected? You're better off just placing a wall of turrets and using the bombs to explode them.

**Comment by TeamSpen210** [comment]
For 2, plates have inputs and have had them for almost 4 years now. For 12, you can detect explosions with a damagable object the same way monitors work for example.

**Comment by Flash4433** [comment]
Oh, they have inputs... How didn't I notice this?... :upside_down_face: 
Oh, cool. Will the breakable glass automatically detect explosions?
