### ISSUE TITLE
Adjustable laser relay heights

### ISSUE THREAD

**Issue by PaperPlayerX** [BEEmod/BEE2.4#1267]
Laser relays should have variants at different heights so that you can match them with lasers at heights that aren't floor-level. Could be interesting if the relay is held up by a little piston and not just a block, but that's optional. I'd imagine it'd be a button type, since that's three options.

That is all.

**Comment by Luke18033** [comment]
TeamSpen's addons had a "piston laser relay", which is already on the list at BEEmod/BEE2-items#95.
