### ISSUE TITLE
Decorative element

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2.4#1269]
I of course all understand that BEE MOD is not a replacement for HAMMER, but the eyes should be happy! Please add [SEPARATE] the elements of the DECOR! Chairs, other types of lighting, broken panels, etc

**Comment by TeamSpen210** [comment]
See #414 for my plans on this front.

**Comment by Kalail** [comment]
I meant that the player (the Creator of the test) put the decor in those places where it is necessary. For example, a broken panel. Select the animation using numbers for example 05 the panel will be put in place.

**Comment by ZombiePwner1** [comment]
@Kalail Unfortunately @TeamSpen210 doesn't want to do it like that for whatever reason. Most likely restrictions that can't be bypassed very easily.
