### ISSUE TITLE
The decor and pictures

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2.4#1278]
_Yes I understand that I repeat myself but why not add the ability to install different decor and elements_. You can also use drawings (png format, of course). So that the cameras can look more attractive. I hope you can hear me. Below you can see examples so to speak. **Tests should be more beautiful**
![20170217173612_1 jpg c2456000ca85e3ad7dc0b93b1e341bd3](https://user-images.githubusercontent.com/51409156/77223166-71b5d180-6b9d-11ea-9a7d-6c420fd4cdf3.jpg)
![20170217181843_1 thumb jpg b06e1f55c31c4cf8ea21693351079c5d](https://user-images.githubusercontent.com/51409156/77223167-737f9500-6b9d-11ea-9cc9-1cae538f1d4c.jpg)
![2ee6cb97375068c0123c4a3d1b504e79-1200-80](https://user-images.githubusercontent.com/51409156/77223168-74182b80-6b9d-11ea-8e3d-11f7b50b201c.png)
![2011-04-14_00004](https://user-images.githubusercontent.com/51409156/77223169-74b0c200-6b9d-11ea-8316-4b3a7cf3da2e.jpg)
![20170217181745_1](https://user-images.githubusercontent.com/51409156/77223170-75495880-6b9d-11ea-9065-1d7ba75fdb73.jpg)
![image](https://user-images.githubusercontent.com/51409156/77223171-75495880-6b9d-11ea-98f7-c9cee6f7139f.jpg)
![oboik ru_42503](https://user-images.githubusercontent.com/51409156/77223172-767a8580-6b9d-11ea-82c5-adc7a999a8d8.jpg)

**Comment by ZombiePwner1** [comment]
This will be part of the decorations once it's finished.
