### ISSUE TITLE
Linux compiler error -- BEEmod latest (of 3/24/2020) running on Windows guest VM

### ISSUE THREAD

**Issue by MeowcaTheoRange** [BEEmod/BEE2.4#1280]
Hi. I am a Linux user with Steam and Portal 2 running on Linux, the actual physical host computer, and BEEmod2 Palette and Level editor running on a Windows 7 VM guest w/ shared folders. Compiler refuses to even _bring up_ the compiler progress, and errors instantly. I am pretty sure it's because the filesystems are separate or something or the files are in entirely different places.

**Comment by snorepion** [comment]
I have the same setup (except Win10 VM instead of Win7) and it does not have this issue. If you're trying to use a shared folder on an ext[4/3/2] filesystem, that may be why - try putting Portal 2 on an NTFS partition and sharing that instead.

**Comment by Konclan** [comment]
Is this still an issue?
