### ISSUE TITLE
Publish error

### ISSUE THREAD

**Issue by lukesound** [BEEmod/BEE2.4#1281]

**Comment by CheezyPig** [comment]
I don't think anyone can help without any information at all. This issue is useless to anyone and everyone.

**Comment by lukesound** [comment]
i dont know why but help

**Comment by CheezyPig** [comment]
We can't without any information on what went wrong.

**Comment by lukesound** [comment]
but
why im publishing it says error

**Comment by lukesound** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/63037379/78429686-3b04ae80-76a7-11ea-8d82-c4ceb7d75e7b.png)
heres my problem

**Comment by CheezyPig** [comment]
Ah, a build error. Open the console and copy the text that is in there to here.

**Comment by lukesound** [comment]
how

**Comment by CheezyPig** [comment]
press the ` or ~ key, and then you should see a window open up.

**Comment by lukesound** [comment]
what should i type

**Comment by CheezyPig** [comment]
Nothing, just copy the text inside to here.

**Comment by lukesound** [comment]
okay thanks

**Comment by Luke18033** [comment]
If it only fails when publishing, that means there's a leak in your map. Do you have any Half Grates placed in corners of a room?

**Comment by Luke18033** [comment]
Closing due to lack of info
