### ISSUE TITLE
Error with publishing.

### ISSUE THREAD

**Issue by MrJasonRus** [BEEmod/BEE2.4#1283]
![изображение](https://user-images.githubusercontent.com/31430536/78752068-cf635f80-798c-11ea-8413-2ac5d0be953b.png) - from console.
I cant publish, but I can play inside.

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. Do you have any Half Grates placed in the corner of a room?

**Comment by Luke18033** [comment]
Closing due to lack of info
