### ISSUE TITLE
use these voice samples i found on google that you could use for characters with voice lines

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1285]
http://www.portal2sounds.com/

**Comment by Luke18033** [comment]
That's just a list of all the lines that are already in the game.

**Comment by ZombiePwner1** [comment]
@Luke18033 He means like instead of searching through the games VPK for voicelines you can search for all of them on the website to find a specific line easier.

**Comment by Luke18033** [comment]
Except that site's not helpful if you want to find out the actual names of the lines for Hammer/voice packs, since they don't keep the original filenames (replacing it with a random number).

**Comment by Luke18033** [comment]
For just listening to the lines it works fine, but that has nothing to specifically do with BEE.

**Comment by supersean08-pro** [comment]
but you can look at their voice lines and figure what voice belongs to, like "potato", might be glados or  the moron (you know who) to officaly know which one the two is, they might have the name "glados", and that is wheatley, because glados would'nt speak out her name, so there is your answer.
