### ISSUE TITLE
editor crashes almost instantaneously

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1286]
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.10, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 10836 )
Opened Steam Socket NS_CLIENT ( socket 2596 )
Network: IP 192.168.0.10, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps

**Comment by CheezyPig** [comment]
I'd say to verify game file integrity and reinstall BEEmod. See if that works.

**Comment by supersean08-pro** [comment]
mk

**Comment by supersean08-pro** [comment]
reinstalling beemod is the same as verifying the game

**Comment by supersean08-pro** [comment]
you idea seems to work, so that must mean beemod is not going ass intended

**Comment by Luke18033** [comment]
There's nothing unusual in that log, closing for lack of info

**Comment by supersean08-pro** [comment]
its fine, i just uninstalled portal 2, deleted the files, then reinstall it, then verify integrity of the game files.
