### ISSUE TITLE
please make beemod compatible with "thinking with time machine"

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1287]
i want you to make beemod compatible with this great mod because my portal 2 copy, keeps on crashing, songs are rare but there are songs.

Common elements:
- [ ] upside down cube dropper (so you dont have to use the cube annoyingly to make the dropper upside down.)

Theme:
- [ ] Overgrown

- [ ] old aperture 50s

- [ ] old aperture 60s

- [ ] old aperture 70s 

- [ ] old aperture 80s

- [ ] P1

- [ ] bts

- [ ] clean

- [ ] original clean

obvious stuff
- [ ] no lag

**Comment by Luke18033** [comment]
All of this has already been suggested in #461 and BEEmod/BEE2-items#589.
