### ISSUE TITLE
[geometry] BEE2.py attempts to locate bee2.ico in C:/Users/

### ISSUE THREAD

**Issue by koerismo** [BEEmod/BEE2.4#1288]
(geometry branch) On launch, BEE2.py crashes after failing to load C:/Users/bee2.ico which does not exist.

**Comment by TeamSpen210** [comment]
Do you have the full traceback? Sounds like it might have a space-in-path issue maybe?

**Comment by Luke18033** [comment]
Can't reproduce this, closing due to lack of info.
