### ISSUE TITLE
Geometry: Implement a system to disallow antlines from appearing on top of certain textures

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1295]
In Art Therapy style, it's possible for antlines to appear on top of backpanels:
![image](https://user-images.githubusercontent.com/19228201/80527871-e83ab180-8949-11ea-9682-a2eb4794c0a2.png)
This doesn't make much sense, so a system should be implemented that would be able to prevent this. Since it's not really possible to reroute antlines, this should be implemented in one of two ways:

- Prevent specified textures from generating where antlines are present
- If specified textures generate where antlines are present, remove that portion of the antline

Perhaps implement both modes, and allow choosing which one is used in vbsp_config?

**Comment by TeamSpen210** [comment]
Really backpanels shouldn't be generating like this, it should be inset or otherwise.

**Comment by Luke18033** [comment]
Yeah, I guess they'd be better as decorations, once those are implemented.

**Comment by Luke18033** [comment]
Not needed, backpanels are going to be implemented as decorations.
