### ISSUE TITLE
Crashing on initial startup

### ISSUE THREAD

**Issue by Combine-lab-2056** [BEEmod/BEE2.4#1297]
OS: Mac OS-X Mojave V. 10.14.6
BEE2.4 version: 4.34.1 (Have tried with newer versions, 4.35.1 gave the same and 4.36.1 did some freaky stuff.)

Logs are attached.
[BEE2.log](https://github.com/BEEmod/BEE2.4/files/4570220/BEE2.log)
[BEE2.error.log](https://github.com/BEEmod/BEE2.4/files/4570221/BEE2.error.log)

P.S. Problem is similar to #1160 but I couldn't find an answer for that issue. 
**** is also the substitute for the username.
EDIT: When it crashes, it also sends me back to the login menu.

**Comment by Luke18033** [comment]
What happens when you try to run the newer versions?

**Comment by Combine-lab-2056** [comment]
Well, the newest version makes my screen show something before taking me back to the login screen. I'm not really sure what to call it, and I can't get a screenshot of it since it happens a bit quick.

**Comment by Combine-lab-2056** [comment]
Closing issue, considering upgrading to Windows.
