### ISSUE TITLE
how to make an actual Friend fizzler

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1298]
1. First, you need to have a fizzler texture, then make different copy's of them but only the texture and the appearance altered.

2. you need the fizzler textures transition to a different texture in a smooth way like some "sine in sine out" transition.

3. Make the fizzler have a swirl texture, but if the texture looks nice without the swirling texture, that is up to you, but please don't make the swirl texture be affected by the performance settings.

I really hoped this actually worked out and helped!

**Comment by CheezyPig** [comment]
How does this at **all** relate to BEEmod items, let alone BEEmod?

**Comment by ZombiePwner1** [comment]
This is unrelated to beemod.

**Comment by supersean08-pro** [comment]
to make fizzlers fizzlers

**Comment by ZombiePwner1** [comment]
@supersean08-pro What do you mean to make fizzlers fizzlers? That makes no sense.

**Comment by supersean08-pro** [comment]
you know in hammer those green fizzlers
they transition to another, if you know what i mean

**Comment by Luke18033** [comment]
None of the posts by this person make sense, can we please ban them?
