### ISSUE TITLE
Portal 1 theme textures uses portal 2 textures

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1300]
![20200511185109_1](https://user-images.githubusercontent.com/63530071/81650729-831cab00-9475-11ea-963e-f5935c85583c.jpg)

**Comment by Luke18033** [comment]
I know for a fact that these work, so that's just a problem on your end. Make sure P2 isn't running when you export, it prevents these from being updated properly.

**Comment by CheezyPig** [comment]
Make sure Hammer is closed too, that was an issue I had.

**Comment by supersean08-pro** [comment]
both are closed
