### ISSUE TITLE
Cusтoм мusic

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2.4#1301]
Add so that you can add music to the package files, for example, you can add it to a ZIP with the name **_CUSTOM MUSIC_**.

**Comment by Flash4433** [comment]
Check if an issue about this was already open. In this case, #1219.

**Comment by Luke18033** [comment]
You can already add a new package containing custom music, I don't know why people think BEE is somehow locked to the default packages. If you want a tool for it directly within the app, then this is a duplicate of #1219.
