### ISSUE TITLE
Add relaxation vaults

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1303]
if you could add it, that would be great.

**Comment by Critfish** [comment]
1. This is the wrong repository. This should be in the BEE2-items repository, this one is for the application itself.

2. This has already been suggested several times, and is not being added. If you want to make a custom story, use Hammer.

**Comment by supersean08-pro** [comment]
> 1. This is the wrong repository. This should be in the BEE2-items repository, this one is for the application itself.
> 2. This has already been suggested several times, and is not being added. If you want to make a custom story, use Hammer.

if it has been said many times, put the tag "duplicate"

**Comment by CheezyPig** [comment]
No, that's **your** job to find out if it's a duplicate or not, to not flood the github. Critfish isn't a member of BEEmod, so he cannot put tags. I'm quite surprised you aren't banned yet because you keep making invalid/duplicate suggestions, or just writing nonsense.

**Comment by supersean08-pro** [comment]
of course i know that, he isn't included in the "Beemod" organization, which means that he cant put tags like "duplicate" or what ever.

**Comment by Critfish** [comment]
then why did you quote me, then say put it as duplicate?

**Comment by supersean08-pro** [comment]
"This has already been suggested several times, and is not being added. If you want to make a custom story, use Hammer."
you know exactly where you put the words "suggested several times" in.

**Comment by FrozenDragon0** [comment]
All 3 of you enough. We don't need arguing here.

**Comment by supersean08-pro** [comment]
mk
