### ISSUE TITLE
Item Icons don't use antialiasing on windows (v4.36.1)

### ISSUE THREAD

**Issue by koerismo** [BEEmod/BEE2.4#1304]
All item icons display without proper anti aliasing, resulting in less than optimal graphics.
In bee:
![image](https://user-images.githubusercontent.com/56563658/81966307-5dafae80-95e7-11ea-96f5-821595d245fb.png)

In chrome:
![image](https://user-images.githubusercontent.com/56563658/81966331-67391680-95e7-11ea-95a5-f33fcedcd19b.png)

**Comment by CheezyPig** [comment]
I believe you are meant to downscale them to 64x64 for BEEmod.

**Comment by TeamSpen210** [comment]
When downscaling, I intentionally use a nearest-neighbour algorithm since I've found it produces better results for a lot of icons - preventing some blurring. If you resize it yourself to 64x64 it'll be unaffected.
