### ISSUE TITLE
Error When Exporting To Portal 2

### ISSUE THREAD

**Issue by TheMaxGame** [BEEmod/BEE2.4#1305]
![image](https://user-images.githubusercontent.com/64435367/82151508-b3888e80-9853-11ea-9278-7124f3a631c4.png)
I have neaver come across this error untill recently. I have no idea how to fix this. Please can someone help?

**Comment by Luke18033** [comment]
BEE2 doesn't have access to that file for some reason. Try restarting your computer, Windows might think it's still running.

**Comment by TheMaxGame** [comment]
Thanks, will try!

**Comment by TheMaxGame** [comment]
> BEE2 doesn't have access to that file for some reason. Try restarting your computer, Windows might think it's still running.

This worked perfectly Thanks!
