### ISSUE TITLE
tspenAddons mod not working with BEE2.4

### ISSUE THREAD

**Issue by NWinXP** [BEEmod/BEE2.4#1306]
After installing tspenAddons into the portal2_dlc2 folder, the items and themes included in the addon do not work at all. Will it ever be updated? I want the refurbished theme back for my level. If not, I will just have to use Hammer.

**Comment by CheezyPig** [comment]
No, it is for BEE2.2, it was made for an entirely different program, and most of the items are being ported anyway.
Besides, that's not how BEE2.4 Packages are installed now.

**Comment by NWinXP** [comment]
OK. Are any of the assets being ported over yet? When will the next update come out?

**Comment by Luke18033** [comment]
Yes, those are being ported over. See BEEmod/BEE2-items#95
