### ISSUE TITLE
Exporting Palette Error

### ISSUE THREAD

**Issue by barny600** [BEEmod/BEE2.4#1310]
When I try to export a new palette, this message pop out and basically force the entire mod to close.
![Annotazione 2020-05-25 013115](https://user-images.githubusercontent.com/65875544/82767655-74e16e00-9e29-11ea-87f3-b2fb2b2e1f55.jpg)
Also the report debug doesn't seem to notice anything unusual in the process. How can I solve this problem?

**Comment by PietroLegal** [comment]
That happened too when i removed the game from BEE2. And i have no clue of how to fix :/ sorry.

**Comment by LautaroL20** [comment]
You've made this issue with what can now be considered are very old versions of the application and packages. I do not think that this is a problem anymore, so please get the latest version of BEE2 and then if the issue still exists, let us know and we will re-open the issue.
