### ISSUE TITLE
VRAD ignores studiomdl path set in srctools.vdf

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1312]
The title says it all. This makes it impossible to use the `comp_vactube` ents, since they rely on this to compile the vac_anim model.
```
[INFO] bsp_trans.run_transformations(): Running "Portal 2 Vactubes"...
[INFO] __init__.vactube_transform(): 6 vactube nodes found.
[ERROR] __init__.vactube_transform(): Vactubes present, but no studioMDL path provided!
```

**Comment by TeamSpen210** [comment]
Well one problem is that Mac/Linux versions don't have `studiomdl`.

**Comment by Luke18033** [comment]
Ah, hmm. In that case the only real solution would be adding the ability to directly save MDLs, but that seems like it'd be pretty difficult.

**Comment by Luke18033** [comment]
Maybe have it fallback to path_tracks in that case?

**Comment by Luke18033** [comment]
I mentioned at one point on Discord that you can use the older `func_train` entity for this, which is able to turn smoothly and doesn't require compiling a model.
