### ISSUE TITLE
Test chamber sign [SUGGESTION]

### ISSUE THREAD

**Issue by ThatOneRetro** [BEEmod/BEE2.4#1318]
Maybe you could create an item equivilent to the test chamber sign in the begining of tests to give a more customized feel. As there are always signs at every start, you would have to create a new elevator that skips the corridor and directly enters the test as seen in the wheatly tests.

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2-items#605, and the wrong repository.
