### ISSUE TITLE
Compile Error still to this day

### ISSUE THREAD

**Issue by vithorte** [BEEmod/BEE2.4#1325]
So, i've unistalled beemod 2 because its only compiling error, Validating files did nothing at all.

Probably i dont know what to do when it computes lighting.

**Comment by Luke18033** [comment]
Post the compile log from the console, that generic error message is useless on its own.

**Comment by vithorte** [comment]
i said that i unistalled
;-;

**Comment by vithorte** [comment]
i dont wanna lose puzzlemaker again with unistall problems

**Comment by Luke18033** [comment]
I didn't tell you to uninstall anything. Post the console log, we can't help you if you're just saying "there's a compile error".

**Comment by vithorte** [comment]
and now its not working anymore with bee launch

**Comment by Luke18033** [comment]
Are my comments invisible to you or something? Post. The. Console. Log.

**Comment by vithorte** [comment]
your comments aren't invisible and im saying

i cant even execute bee2

**Comment by vithorte** [comment]
what do you mean? the execute code?

**Comment by Luke18033** [comment]
Okay, so the app won't run now. Does any sort of error message appear?

**Comment by vithorte** [comment]
yes

a log and a failed to launch bee2

**Comment by Luke18033** [comment]
Can you post that log?

**Comment by vithorte** [comment]
ok

**Comment by vithorte** [comment]
I guess this time worked without errors ;-;

**Comment by vithorte** [comment]
yup it worked

**Comment by Luke18033** [comment]
Alright...

**Comment by vithorte** [comment]
what

**Comment by vithorte** [comment]
i said that the launch worked ;-;

**Comment by vithorte** [comment]
nvm
