### ISSUE TITLE
"Turret Shoot Monitor" in voiceline selector is inconsistently placed

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1326]
The text appears directly after the names of the characters, making it look as though the option is literally named "Wheatley Turret Shoot Monitor", for example. It should have a consistent position, or be moved down next to Monitor Visuals.
![image](https://user-images.githubusercontent.com/19228201/85187606-9c273180-b255-11ea-9315-886710f2a1b8.png)
![BEE2_NFr6f328sQ](https://user-images.githubusercontent.com/19228201/85187617-a77a5d00-b255-11ea-8c94-ae2ceb6ab985.png)
![BEE2_vruGxapX9N](https://user-images.githubusercontent.com/19228201/85187619-a8ab8a00-b255-11ea-8a9c-5788f55cce9e.png)

**Comment by TeamSpen210** [comment]
Yep that looks dumb.

**Comment by seagemgames** [comment]
Also, instead of "Turret Shoot Monitor", it should say "Turrets Shoot Monitor" or "Turret Shoots Monitor".
