### ISSUE TITLE
i'm  keep getting a build error

### ISSUE THREAD

**Issue by moonlord335** [BEEmod/BEE2.4#1331]

**Comment by A-PENCIL-SHARPENER** [comment]
What's the error? Check the console so we know what you're talking about.
If you can't access the console, then you need to bind the "Open Console" function to a specific key.

1. Go To Options;Keyboard/Mouse;and click "Enable Developer Console".
2. Press the Grave/Tilde "~" key. It's located under the Escape key.
3. Locate the error. it should start with VRAD Failed, VBSP Failed, or VVIS Failed.
4. Once you locate it, copy and paste it on this issue.

**Comment by moonlord335** [comment]
its too big of a error i cant copy it

**Comment by Luke18033** [comment]
You can? GitHub doesn't have a comment length limit.

**Comment by Luke18033** [comment]
Alternatively, type in `con_logfile console.log` and try to compile the map again. Then open `portal2/console.log`, and copy the error message out of there.

**Comment by moonlord335** [comment]
I meant in the console when I try to highlight everything ican't go down

**Comment by moonlord335** [comment]
I don't know how to copy things

**Comment by moonlord335** [comment]
VBSP failed.

vbsp_styles: Starting style Changer VBSP hook.
vbsp_styles: Elevators (hold ctrl): False
vbsp_styles: commandline: " -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/""
vbsp_styles: filename: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
vbsp_styles: game: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/"
vbsp_styles: limit: 1750
vbsp_styles: Saved modified C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
vbsp_styles: Changed 0 materials.
vbsp_styles: -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
vbsp_styles: Launching and waiting for "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" with commandline "-game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf""
vbsp_styles: Error starting C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe
The original Valve vbsp.exe must be reinstalled (verify cache), then renamed vbsp_original.exe
and Carl Kenner's vbsp_styles.exe must be copied with the copy named vbsp.exe
Both files must be in your "Portal 2\bin" folder.
vbsp_styles: Packing because RunBspZip is set to 1 in editoritems.txt
vbsp_styles: Making C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/\puzzles\76561199058833022\untitled.jpg writable

**Comment by TeamSpen210** [comment]
That's the old Stylechanger VBSP. Go into `C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/`, and then delete all of the following: `vbsp.exe`, `vbsp_original.exe`, `vbsp_styles.exe`, `vrad.exe`, `vrad_styles.exe` and `vrad_original.exe`. Then verify the game cache in Steam, and re-export BEE2.

**Comment by moonlord335** [comment]
I tried to but it says file isn't in that location but when I try to search
up on this PC but it doesn't show up as in it says no items match your
search

**Comment by moonlord335** [comment]
VBSP failed.

vbsp_styles: Starting style Changer VBSP hook.
vbsp_styles: Elevators (hold ctrl): False
vbsp_styles: The original vbsp.exe is missing. Verify your steam cache for Portal 2 to get it back, then run the style changer.

**Comment by moonlord335** [comment]
it's giving me this now

**Comment by moonlord335** [comment]
now bee2 won't open now

**Comment by TeamSpen210** [comment]
Windows' search function won't find these files, since they're in program file directories and aren't normal "document" files. You'll have to look in the bin/ folder yourself. If you're getting that error you haven't deleted them yet, and also haven't verified your game files - right click on Portal 2 in Steam, go to Properties → Local Files and click "verify".

**Comment by Luke18033** [comment]
Closing due to lack of response.

**Comment by moonlord335** [comment]
VPbS files in the vard files aren't there

**Comment by moonlord335** [comment]
i meant the vpbs files and the vard files arent there and bee 2 is not oping

**Comment by Luke18033** [comment]
Did you try validating the game files like TeamSpen suggested?

**Comment by moonlord335** [comment]
I meant the VPbS files and the vard files aren't there

**Comment by moonlord335** [comment]
Yes I did but when it was almost done it said it couldn't complete it
