### ISSUE TITLE
Missing textures.

### ISSUE THREAD

**Issue by Darkkyy** [BEEmod/BEE2.4#1334]
So i wanted to create a level with BEE and everything was fine but when i wanted to create a level i got missing textures. Here's screenshot: 
![Zrzut ekranu (415)](https://user-images.githubusercontent.com/67558446/85956426-23775200-b986-11ea-824a-f1d423c7e7a3.png)

**Comment by Luke18033** [comment]
Look in your Portal 2 folder, is there a `bee2/` folder in there? What are its contents?

**Comment by Darkkyy** [comment]
inside materials folder there is again bee2 folder and there only fizz_sides folder

**Comment by Luke18033** [comment]
Okay, there should be more stuff in there. Go to `Options > Development` in BEE, make sure "preserve game directories" isn't turned on. If it is, turn it off, click "Reset Package Caches" in the `General` tab, then export again.

**Comment by Darkkyy** [comment]
It works. Thanks Luke18033
