### ISSUE TITLE
Building Error when trying to publish Chamber

### ISSUE THREAD

**Issue by mjovan1882** [BEEmod/BEE2.4#1336]
Ive created a chamber and havent been able to upload it, but building it to test it works fine. Ive looked up the issue and found that this kind of thing is probably due to leaks, but when I tried to load the map in hammer and tried to load the pointmap, there wasnt one, so I dont think its a leak.
Im pretty sure this is the console error:

Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198128123450\1593649060.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/1593649060.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,25,25)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 663 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 49963 (ms)

VVIS failed.

Valve Software - vvis.exe (Nov 12 2019)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1593649060.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1593649060.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1593649060.prt

Again, building the map normally works fine, but trying to publish it gives a standard "There was an error building the puzzle" error.

**Comment by Luke18033** [comment]
That is indeed a leak, not sure why you aren't able to load the pointfile. Try recompiling the map once in Hammer first. It'll give the same error, but should properly generate a pointfile.

**Comment by mjovan1882** [comment]
I tried to run the map in hammer, it gives an error. 
[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\1593649060.vmf"
[I] vbsp.main(): New path: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\1593649060.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[W] vbsp.main(): Hammer map detected! skipping conversion..
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\portal2', 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\sdk_content\\maps\\1593649060.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\1593649060.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/trigger_once.vmf
[I] <valve>.vbsp():
Finished. Press a key to close.
Im not sure if im not understanding or if this is an actual error, but after the failed(?) compile, there is no pointfile.

**Comment by Luke18033** [comment]
Sorry, probably should have explained that better. puzzlemaker_export doesn't work with BEE maps, you need to open `maps/styled/preview.vmf`.

**Comment by mjovan1882** [comment]
Allright, I did that and I managed to load the point file, from what I can tell there's supposed to be a red line / arrow that leads to the leak, but there's nothing. Ive gone around the map a few times, no entities that seem to be outside the boarders and no red arrow / line

**Comment by Luke18033** [comment]
Huh, weird. Upload the VMF here, I'll see if I can figure it out.

**Comment by mjovan1882** [comment]
The VMF is the maps/styled/preview.vmf, right? 
Ill just send both
[VMF Files I cant send them so I made a ZIP.zip](https://github.com/BEEmod/BEE2.4/files/4867502/VMF.Files.I.cant.send.them.so.I.made.a.ZIP.zip)

**Comment by Luke18033** [comment]
Okay, it's a problem with the BTS skybox, the walls are too short for max-height maps.
![image](https://user-images.githubusercontent.com/19228201/86501158-2b027680-bd4b-11ea-9262-e70425050edf.png)
It's already been fixed for the next release; [here](https://github.com/BEEmod/BEE2.4/files/4871857/skybox.zip) is that version of the instance. Put it in `sdk_content/maps/instances/bee2/bts/sky`, replacing the copy that's there. It should work with the release build. Alternatively, just make your map a couple blocks shorter, it really doesn't need to be that big.
