### ISSUE TITLE
Display in the GUI when signages have a secondary variant.

### ISSUE THREAD

**Issue by SCIENTIST2004** [BEEmod/BEE2.4#1337]
I think you should add two more signages to configurator.
We already have their first parts.
![hi_Lautaro](https://user-images.githubusercontent.com/35931028/86499837-e5b76680-bd95-11ea-9a28-76aebe046e83.png)
But we don't have second parts.
![hi_Tspen](https://user-images.githubusercontent.com/35931028/86499845-ea7c1a80-bd95-11ea-8977-eb438663cbdd.png)

**Comment by TeamSpen210** [comment]
To fix this in the UI, it could display a popover or section below the left column with a preview of what the sign would look like. It would show the sign with the arrow next to it, and if a secondary version is available also show that pair.

**Comment by SCIENTIST2004** [comment]
@TeamSpen210 
Oh thanks. I forgot that some signage can do that
