### ISSUE TITLE
bee2 never exports vpks.

### ISSUE THREAD

**Issue by Fennecai** [BEEmod/BEE2.4#1338]
i always get the error that vpks were not exported; even though hammer and portal 2 are both completely closed.

i made sure via task manager that no instances of hammer.exe, portal2.exe, vrad, vvis, vpk, etc etc. were there. nothing was. yet it fails every time to export the vpks.

**Comment by Luke18033** [comment]
Tried restarting your computer? Windows sometimes gets stuck locking a file even when no program is actually accessing it anymore.

**Comment by Fennecai** [comment]
yes; the problem persists.

**Comment by Luke18033** [comment]
Weird.

**Comment by Fennecai** [comment]
maybe just check the code that throws that error and try to see if any refactoring/re-writing is needed within the call stack...? like; check the code of all the things that call the thing that makes the error pop up. cause I even used Sysinternals process explorer to manually close file handles in the portal 2 directories completely; and even with the handles all closed, this still happens. 
I almost wonder if it just thinks p2 is open because of windows explorer having handles open to portal 2's folders? but even so, i closed those handles by hand and it still happens.

I will try to restart my PC again and see if that fixes it. but if not; maybe its best to just take a look at the code. even if you cant find the source of _this_ problem; you might find other problems you didn't know existed, heh.

**Comment by TeamSpen210** [comment]
I display that error when I get a permission failure when overwriting the VPK, so it could be anything else that would prevent modifying the file.

**Comment by Fennecai** [comment]
fair enough....if it helps though; i discovered that, potentially, having a vpk already existing in dlc3 or even a folder named pak01_dir might be messing things up a bit. but restarting my PC a second time might have also contributed to the problem resolving itself. odd..

**Comment by Luke18033** [comment]
Not sure what would cause this
