### ISSUE TITLE
Portal 2 crashes after building of a co-op map using BEE2 1.36.1

### ISSUE THREAD

**Issue by Nyrif** [BEEmod/BEE2.4#1339]
I tried making a co-op map using the mod, but it crashed right after it finished building. I tried uninstalling BEE2 and reverting portal 2 to normal and it stopped crashing, but I wanted to create a co-op map with a different style. The problem went away after a reboot but it happens again if I try a second time

**Comment by Nyrif** [comment]
I've noticed it never happens on the overgrown style, but every other style it crashes

**Comment by Luke18033** [comment]
What items do you have in your map? There are a couple items that are known to cause crashes in co-op.

**Comment by Nyrif** [comment]
Just a monitor, entry/exit door, and a view room thing, I tried without a monitor and it still crashed.

**Comment by Nyrif** [comment]
> What items do you have in your map? There are a couple items that are known to cause crashes in co-op.

Just a monitor and the default items, I tried without a monitor and it still crashed.

**Comment by Luke18033** [comment]
The monitor is one of those items that causes crashes in Co-op, it shouldn't still happen after you remove the monitor though. What default items do you have? BEE modifies pretty much every default item in some way, it could be one of them.

**Comment by Nyrif** [comment]
> The monitor is one of those items that causes crashes in Co-op, it shouldn't still happen after you remove the monitor though. What default items do you have? BEE modifies pretty much every default item in some way, it could be one of them.

Default items being the exit and entry doors and the observation room

**Comment by Luke18033** [comment]
Ah...I'm not sure what the issue could be then.

**Comment by Luke18033** [comment]
Does this still happen? Try switching to a different set of corridors, or another style entirely.

**Comment by Luke18033** [comment]
Not sure why this would happen
