### ISSUE TITLE
Connecting multiple standing/reclined fizzlers to a custom fizzler breaks

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#1343]
In the editor, the left MIF is connected to all of the standing fizzlers and the right MIF is connected to all of the reclined fizzlers:
![image](https://user-images.githubusercontent.com/19228201/87103863-0efb4b00-c20b-11ea-9313-c7f7c0f9eff1.png)
However, in-game only one of the fizzlers will actually appear, seemingly chosen at random.
![image](https://user-images.githubusercontent.com/19228201/87103901-2f2b0a00-c20b-11ea-8d1e-05e5ff902de4.png)
The expected behavior is that all of the connected fizzlers should be converted to MIFs (or whatever fizzler type is connected). If this would be impossible/difficult, then the rest should just appear as normal fizzlers instead of being missing.

**Comment by TeamSpen210** [comment]
I never considered users trying to do that sort of thing, but yeah it should duplicate the fizzler. What it does is "move" the fizzler over to the custom positions, so what's happening is that it gets moved to every position here.

**Comment by LautaroL20** [comment]
There is another possible and important scenario where people would want to do another type of connection that I don´t see in the puzzlemaker screenshot of this issue, and it would be:
![20200904111443_1](https://user-images.githubusercontent.com/12244376/92249391-61ba5180-eea0-11ea-9cb7-dab90f00fd6d.jpg)

**Comment by Luke18033** [comment]
It's the same issue really, both items use the same fizzler repositioning logic.
