### ISSUE TITLE
BEE2 App not working/not launching

### ISSUE THREAD

**Issue by ThatBlooky** [BEEmod/BEE2.4#1345]
The BEE2 application is not working and it's not launching. 
I tried on the latest versions and the earliest versions (aka 1.5).

**Comment by FrozenDragon0** [comment]
What's the error message? We need more info.

**Comment by ThatBlooky** [comment]
> 
> 
> What's the error message? We need more info.
It just says that it's not responding or something like it. 
(My PC's polish and I do not understand half of it)

**Comment by FrozenDragon0** [comment]
What windows version are you running?

**Comment by ThatBlooky** [comment]
Windows 7.

**Comment by FrozenDragon0** [comment]
Hmmm not sure. Considering you don't get an error message doesn't really help us.

**Comment by ThatBlooky** [comment]
Odd.

**Comment by Combine-lab-2056** [comment]
I'm not an admin, but maybe look for a log folder?
