### ISSUE TITLE
After export the palette, Beemod will minimize the interface when you click on "No" when someone wants to prevent Portal 2 to be launched

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1349]
Beemod user interface should stay in the same stage as it was before you click "no", this means that if the Bee´s user interface window were maximized or whatever it was, should remain as that but currently the interface will get minimized.

**Comment by GiovanH** [comment]
Not sure this is a bug. Beemod asks you if you want to launch portal 2, but it processes the "After export" setting separately. I was surprised by this my first time too, but it consistently respects the option set in options. Perhaps changing the default to "do nothing" would be more intuitive?

**Comment by LautaroL20** [comment]
I just improved the title as it could have been a bit unclear.

**Comment by LautaroL20** [comment]
Basically, the Beemod user interface should stay in the same stage as it was before you click "no", this means that if the Bee´s user interface window were maximized or whatever it was, should remain as that but currently the interface will get minimized.
