### ISSUE TITLE
Beemod icons now has sawtooth issues

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1350]
For some reason, the Beemod icon now has sawtooth issues... The issue can be seen when the icon is at the taskbar and also on the star menu, on desktop it shows fine. Here is a screenshot with a small comparison:

![PRL36 VS PRL37 Beemod icon](https://user-images.githubusercontent.com/12244376/87882089-23420380-c9d4-11ea-91de-3e897e45f61b.png)

_______________________________________________________________________________________________

@seagemgames mentioned: The small Beemod icons that are pressent inside the Beemod interface does also have this issue too: 
![image](https://user-images.githubusercontent.com/32136200/104780447-bb992500-5778-11eb-9306-969fbc527e31.png)

**Comment by Luke18033** [comment]
Konclan made an updated version of the icon which TeamSpen implemented, he must have accidentally downscaled it with nearest neighbor mode or something.

**Comment by seagemgames** [comment]
This is still an issue in 4.38.1, though it's slightly less noticable. The main application favicon does not have this issue, however, the sub-menus still have this sawtooth issue.
![image](https://user-images.githubusercontent.com/32136200/104780447-bb992500-5778-11eb-9306-969fbc527e31.png)

**Comment by LautaroL20** [comment]
Thanks for that issue report, added to the description.

**Comment by LautaroL20** [comment]
This is now fixed in next release thanks to @seagemgames (https://github.com/BEEmod/BEE2.4/compare/e2db0de9a761...b272cfba1d1f)
