### ISSUE TITLE
BEE2.exe not appearing in the folder [SOLVED]

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2.4#1355]
So I installed BEE2 around a month ago and I have to say it's very useful. Well, I decided to install Aerond's Custom Music, and it also worked fine. The thing is, after that, I clicked on BEE2 to prepare a pallette for building, when I realized that BEE2.exe wasn't there. I then re installed the mod and realized BEE2.exe wasn't in the new folder either. Am I doing something wrong?
EDIT: Windows Defender nor any antivirus has said anything, I'll try to re install it again

**Comment by Flash4433** [comment]
It seems you didn't install it properly, check this. https://github.com/BEEmod/BEE2.4/wiki/How-to-Install-BEE2.4

**Comment by HeimlichLaboratories** [comment]
> It seems you didn't install it properly, check this. https://github.com/BEEmod/BEE2.4/wiki/How-to-Install-BEE2.4

No, I DID install it properly. In fact, the issue randomly happened when I ALREADY had it installed and somehow it happened when I reinstalled too.

**Comment by TeamSpen210** [comment]
You might want to check your antivirus software, sometimes they decide BEE is an virus and flag it...

**Comment by HeimlichLaboratories** [comment]
> You might want to check your antivirus software, sometimes they decide BEE is an virus and flag it...

Windows Defender hasn't said anything about BEE, but I'll take a look.

**Comment by HeimlichLaboratories** [comment]
> It seems you didn't install it properly, check this. https://github.com/BEEmod/BEE2.4/wiki/How-to-Install-BEE2.4

OK, turns out I was doing something wrong. Sorry. I'm gonna check if it works now.

**Comment by HeimlichLaboratories** [comment]
Ok people turns out I was doing something wrong. I solved it.
