### ISSUE TITLE
"There was an error building the puzzle." VBSP Error

### ISSUE THREAD

**Issue by signals357** [BEEmod/BEE2.4#1356]
I was in the puzzle builder and when I was about to test my test chamber, I got the error in the console:

VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN'}
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3153, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 334, in load_settings
  File "F:\Git\BEE2.4\src\connections.py", line 706, in read_configs
  File "F:\Git\BEE2.4\src\connections.py", line 388, in parse
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 291, in __call__
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 533, in __new__
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\enum.py", line 546, in _missing_
ValueError: 'Never' is not a valid FeatureMode
[14192] Failed to execute script compiler_launch

Can somebody tell me what's going on here?

**Comment by TeamSpen210** [comment]
It’s not a helpful error message, but this came from a change in v37 of the app so you’ll need to update.

**Comment by signals357** [comment]
Now im getting this:


VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'staticpan': 'instances/BEE2/over/static_panel/', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting Coop Exit to 1
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (36 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.add_item_inputs(): LOGIC counter: lg119070
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[W] packing.pack_list(): Packlist "PACK_BEE_CRUSHER" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (51 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1579 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1516 in final) is not on grid!
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): Generating responses data..
[W] BEE2_config.load(): Config "bee2\resp_voice.cfg" not found! Using defaults...
[I] voiceLine.find_group_quotes(): "ENTRY": 6/15 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "PELLET_SUGGESTION_BOX"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/mp_coop_paint_redirect07.vcd"
 | 		"2" "scenes/npc/glados/mp_coop_paint_redirect08.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_COOP"
 | 	{
 | 	"ID" "DEADLY_1"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/mp_coop_wall_block03.vcd"
 | 		"2" "scenes/npc/glados/mp_coop_wall_block04.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/9 quotes..
[I] voiceLine.add_voice(): 2 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "MULTI_CAVE"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 | 
 |___

[I] voiceLine.add_quote(): Adding quote: "Line_COOP"
 | 	{
 | 	"ID" "TURRET_DEATH"
 | 	"Choreo_Name" "@voice_turret_died"
 | 	"OnlyOnce" "1"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/glados/mp_coop_laser_201.vcd"
 | 		"2" "npc/glados/mp_coop_laser_202.vcd"
 | 		"3" "npc/glados/mp_coop_laser_203.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['laseremitter', 'laser', 'deadly', 'pellet', 'pelletlauncher', 'infinitepellet', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'pedestalbutton', 'crusher', 'pelletcatcher', 'lasercatcher', 'turret', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=9886, misses=390, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/bee/logic_or.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\Zach PC\AppData\Roaming\BEEMOD2\config\compile.cfg"!

**Comment by Luke18033** [comment]
See BEEmod/BEE2-items#3359.
