### ISSUE TITLE
Antique Reflecto Cube

### ISSUE THREAD

**Issue by Bluecat5995** [BEEmod/BEE2.4#1357]
Here is a concept for an antique reflecto cube.
![Reflecto antique cube](https://user-images.githubusercontent.com/26947025/88327923-4aa71200-cced-11ea-8a97-8f87d2e721f2.jpg)

**Comment by Flash4433** [comment]
Can you provide the model/materials or the link to the map?

**Comment by Luke18033** [comment]
I think that's literally just a screenshot of a normal antique cube, with reflection cube lenses photoshopped on...

**Comment by Bluecat5995** [comment]
> I think that's literally just a screenshot of a normal antique cube, with reflection cube lenses photoshopped on...

Correct

**Comment by Luke18033** [comment]
We'd want someone to actually make a model for this, and that doesn't look that good anyway.

**Comment by Flash4433** [comment]
oh.
