### ISSUE TITLE
Some closed doors appear as missing skyboxes in BTS style

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2.4#1360]
In Behind The Scenes style, closed doors without windows appear as missing skyboxes until being opened. It happens with the Heavy Door at the default BTS starting map and the door leading to the chamber itself.

**Comment by FrozenDragon0** [comment]
Wrong section post here: https://github.com/BEEmod/BEE2-items/issues/3414 Also these leaks with BTS have been posted numerous times so this is a duplicate.
