### ISSUE TITLE
Problems with BTS style

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2.4#1362]
OK sorry for this being my third issue in a row but I have a three problems with the BTS style.

1. Doors that lead to the chamber (not the preset map before the chamber itself) show a missing skybox before being opened.
2. Antlines are bright white.
3. Chamberlocks (items, not the end of the chamber) lead to the end of the map (even if there's space built behind them)
I have the latest version of BEE2. I can also copy paste lines in the console if that helps

**Comment by FrozenDragon0** [comment]
Your posting in the wrong section this is for BEE2's interface only. Post issues regarding items here: https://github.com/BEEmod/BEE2-items

**Comment by FrozenDragon0** [comment]
Issue 1. Duplicate of https://github.com/BEEmod/BEE2.4/issues/1360
Issue 2. Duplicate of https://github.com/BEEmod/BEE2.4/issues/1361 and https://github.com/BEEmod/BEE2-items/issues/3414
