### ISSUE TITLE
construction error, packages.cfg not found,...

### ISSUE THREAD

**Issue by Nuktos** [BEEmod/BEE2.4#1363]
Hi! Beemod has worked fine with me for a while, but I just updated it and now when I try to make a test chamber and test it, it gives me that screen

I also saw that beemod has an error log, and I don't quite understand how I can fix them:
[bee2.error.log](https://github.com/BEEmod/BEE2.4/files/5010643/bee2.error.log)
Last thing, when I try some other player's test chambers, unless there is specific voice scripts, they start with Cave Johnson's first PeTI voice file (the one where he believes he's speaking from the future) and I think there was a setting in beemod to reset these PeTI quotes and one to use them randomly, yet I don't find them anymore.

I'm on a windows 7, Beemod 4.37.0 with its 4.37 packages pack and my portal 2 is up to date.

I'm sorry I'm not good at solving my problems on my own...

**Comment by FrozenDragon0** [comment]
What does the console say?

**Comment by Nuktos** [comment]
I just tried, I don't know how I can use the console while in the edit mode, and since the error shows when trying to play the test chamber, I can't use it in play mode.

**Comment by Nuktos** [comment]
a random most recent test chamber that triggers the first CJ quote gives me information in the console but I can't figure out how to copy-paste them. sorry!

**Comment by Luke18033** [comment]
That would be completely unrelated. Grab the compile log from `Portal 2/bin/bee2/vbsp.error.log`, and upload it here.

**Comment by Nuktos** [comment]
[vbsp.error.log](https://github.com/BEEmod/BEE2.4/files/5017410/vbsp.error.log)
here!

**Comment by Luke18033** [comment]
You have a cube set to timer value 10 without a matching dropper.

**Comment by Nuktos** [comment]
Oh, okay, I thought the game would give me a red alert because of that.

But now I have another weird problem:

Let's say it's the first time I turn my computer on today and I directly turn Steam and Portal 2 on, then I go to my locally stored test chambers. I have the tools I selected on BeeMOD, and I have more or less 6 test chambers. I mess with them, I save them, I close Portal 2. Call that situation A.

 I open BeeMOD to change the tools and the style from clean to 1960. I transfer the datas to Portal 2 and launch the game: my test chambers list is empty and the tools and skin I selected are the ones I just changed.
I made one test chamber like that, I save, close and I turn my computer off for the day. Call that situation B.

The next day I turn my computer on and launch Portal 2: I'm back at situation A, same parameters, same tools, same 6 test rooms.
I launch BeeMOD and transfer the datas because I wanted these tools, and I'm back to situation B, with the only test chamber I made then.

I turn my computer off and on, while I search on the internet where the files are located.
I go to Steam\steamapps\common\Portal 2\portal2\puzzles\76561198890878291 and I find the test chamber of situation B. I launch Portal 2, it's in situation A. I check the folder, still in situation B!

So yeah, I can' back up my better, more important test chambers because of this, and I can't change the tools for them! Can you help me again, please?
