### ISSUE TITLE
Coop Exit prevents antlines from appearing in the block above

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1365]
The title says it all.
![image](https://user-images.githubusercontent.com/19228201/86519906-542b1180-bdf4-11ea-9883-6e55fc3b5759.png)
I'm not sure whether this applies to all styles or if it's specific to Art Therapy, but I'll want to check.

**Comment by TeamSpen210** [comment]
Actually it's showing up in the original preview map, so it might be a vanilla issue?

**Comment by Luke18033** [comment]
Really, can antlines not appear on embedfaces or something?

**Comment by TeamSpen210** [comment]
Weirdly it works on faith plates, but not the exit door face - perhaps because it's not at the origin. But the overlays are being generated correctly (with incorrect brush face settings), so we can just fix it ourselves in the compiler.
