### ISSUE TITLE
Add option to disable auto-packing

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1366]
When editing custom textures or models, auto-packing can be somewhat annoying because it requires you to recompile the map every time changes are made. An option should be added under the Development tab to disable auto-packing. When off, only dynamically generated files (like the music soundscript) and files specified in `comp_pack` entities would be included.

**Comment by TeamSpen210** [comment]
Good idea!

**Comment by Luke18033** [comment]
Actually, maybe just always disable auto-packing when in preview mode? It's not really needed, since you'd have all the resources. It would still be used when publishing of course.
