### ISSUE TITLE
Beemod causes "Failure To Compile" - Unknown visgroup "bevel_thin" for "tiling_template"!

### ISSUE THREAD

**Issue by SpaceCore12090** [BEEmod/BEE2.4#1368]
Whenever I have Portal 2 added to BEE2, if I try and build a puzzle, regardless of what is in it, it gives me a build error. If I uninstall BEE2 from Portal 2, I can build test chambers just fine!

**Comment by LautaroL20** [comment]
While you´re in the puzzlemaker, open the console, type clear and press enter, then try building your puzzle and once it fails to compile, open the console and copy & paste all what it says, here. This is the only way we could figure out what is causing your issue.

**Comment by SpaceCore12090** [comment]
VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Unknown texture generator type "black"!
[W] texturing.load_config(): Unknown texture generator type "white"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names black_gap, bullseye_black_ceiling, bullseye_black_floor, bullseye_black_wall, bullseye_white_ceiling, bullseye_white_floor, bullseye_white_wall, edge_special, laserfield, pedestalside, white, white_wall
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 47 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_WALL_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_WALL_HALF_CENTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_WALL_HALF_CENTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_WALL_PLUS", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_WALL_PLUS", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "TSPEN_BTN_PED_CLEAN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "TSPEN_BTN_PED_CLEAN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\template_brush.py", line 283, in visgrouped
KeyError: 'bevel_thin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\tiling.py", line 1582, in gen_tile_temp
  File "F:\Git\BEE2.4\src\template_brush.py", line 287, in visgrouped
ValueError: Unknown visgroup "bevel_thin" for "__tiling_template__"! (valid: '', 'flat', 'bevel')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2070, in main
  File "F:\Git\BEE2.4\src\tiling.py", line 1585, in gen_tile_temp
Exception: Bad Tiling Template!
[3808] Failed to execute script compiler_launch

**Comment by TeamSpen210** [comment]
It sounds like you installed v37 of the application, but v36 of the packages. You need to update both.

**Comment by SpaceCore12090** [comment]
How do I update it? I'm new to Github

**Comment by SpaceCore12090** [comment]
Thank you

**Comment by LautaroL20** [comment]
To prevent people being confused like this, i have added on the release notes: "**You will also need to download the [4.37.0 Packages](https://github.com/BEEmod/BEE2-items/releases/tag/v4.37.0).**"
