### ISSUE TITLE
Floor/wall antlines are swapped

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1369]
The textures specified as wall antlines will be used on floors/ceilings, and vice-versa. This normally doesn't matter because the textures are identical, but in P1 they're actually different.

**Comment by TeamSpen210** [comment]
It turns out when you need to pass the pair of antline configs through like 4 different modules, you might mix up the order of two of them.

**Comment by Luke18033** [comment]
This now happens again.
