### ISSUE TITLE
Error while using the BTS Theme

### ISSUE THREAD

**Issue by signals357** [BEEmod/BEE2.4#1370]
When building the map in the map editor I get:

[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/clean/items/light_strip_warm.vmf
[I] <valve>.vbsp(): 
 
I have a feeling it's an issue with the file directory.

**Comment by FrozenDragon0** [comment]
Yes it is [I] .vbsp(): Could not open instance file instances/BEE2/clean/items/light_strip_warm.vmf Also this is not the place to be posting package issues this is for the application itself only. You'll need to make a issue on the BEE2Items github.

**Comment by Flash4433** [comment]
Seems to be a duplicate of [BEE2-items#3055](https://github.com/BEEmod/BEE2-items/issues/3055). It's supposedly fixed in the latest release, but this release introduces some bugs too... Maybe refrain from using BTS for now, as it doesn't look that great, to be honest.
