### ISSUE TITLE
1950's elevator randomly gets stuck

### ISSUE THREAD

**Issue by grian32** [BEEmod/BEE2.4#1371]
been making a map in 1950's style, randomly  happened once
no idea why
https://media.discordapp.net/attachments/293435914598744064/742949107060178954/unknown.png?width=1097&height=632

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
