### ISSUE TITLE
Selector windows place label vertically

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2.4#1375]
Sometimes, the music menu will appear like this:
![BEEMOD 4 36 1 - Portal 2 23_08_2020 04_52_54](https://user-images.githubusercontent.com/68685620/90969760-b0f59f00-e4fc-11ea-943d-64e88a6dbf95.png)

**Comment by HeimlichLaboratories** [comment]
Ok, thanks.

**Comment by LautaroL20** [comment]
Unless this is a duplicate, it should stay open as it is an issue that should be fixed unless Spencer says that a solution for this is not over his control.

**Comment by HeimlichLaboratories** [comment]
Oh ok, sorry. I'm new at this

**Comment by LautaroL20** [comment]
No problem.

**Comment by Luke18033** [comment]
I figured out what causes this to happen. The first time a selector window is opened, if stacking the characters vertically like this would cause them to extend off the bottom of the window, then it'll get stuck that way.
