### ISSUE TITLE
Idea: Under construction chamber style

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2.4#1376]
An idea I just had for a style: A chamber still in construction, with some broken panels, cables, stuff like that.
Recommended Settings:
Voice: None
Skybox: 3D Factory
Elev Vid: Black
Music: None
The non-portalable surfaces would randomly switch their texture to one of these yellow bts panels seen in the campaign, along with other random texture changes. Small observation rooms would be small BTS areas similar to BTS's small observation rooms. Large obersation rooms could be a bigger BTS area with a fluorescent light and a vactube.
The top of the floor buttons and pedestal buttons would be gone, revealing a metallic pressure plate. However cube and sphere buttons would be normal.
Antlines would be cables inserted into the floor. Doors could also be unfinished, with one of their sides missing the outside cover (the one with the "EXIT" stickman on it).
I know this idea might be pretty bad, but I think it could work.

**Comment by TeamSpen210** [comment]
This just sounds like Art Therapy, which needs a lot of compiler upgrades to look any good.

**Comment by HeimlichLaboratories** [comment]
Oh.
