### ISSUE TITLE
Bee2.exe dissapear

### ISSUE THREAD

**Issue by Filval387** [BEEmod/BEE2.4#1377]
Whenever I unzip the file, the bee2.exe file dissapears completely.

**Comment by Flash4433** [comment]
If the .exe is in the .zip file, it might be your antivirus detecting BEE2 as a virus and deleting it immediately. It isn't a virus, it might be "detected" as it's made with Python. Maybe disable your antivirus for a bit, extract the .exe, add it to the whitelist so it doesn't get deleted and enable the antivirus again.

**Comment by LautaroL20** [comment]
Like Flash4433 said, it is really likely that your antivirus is fighting against bee2.exe and just decides to delete it each time you extract it. Just adding it to the antivirus whitelist will prevent the beemod executable to get deleted. If this is not the cause which i am almost sure that it is, let us know and we will re-open the issue.
