### ISSUE TITLE
White Faith Plates

### ISSUE THREAD

**Issue by SpaceCore12090** [BEEmod/BEE2.4#1380]
I made a small test chamber with some faith plates and they're appearing white for some odd reason.
![White Faith Plates 1](https://user-images.githubusercontent.com/69298795/91509859-c57fd000-e91e-11ea-9bba-347834eccfb7.jpg)
![White Faith Plates 2](https://user-images.githubusercontent.com/69298795/91509867-ca448400-e91e-11ea-849d-23c4360e9c0e.jpg)

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
