### ISSUE TITLE
Using multiple logic gates together?

### ISSUE THREAD

**Issue by sethpeace** [BEEmod/BEE2.4#1382]
Hello! I was attempting to make a door that closes when you step in front of it, then has to be reopened with a button. I attempted to do this by putting a trigger once in front of the door, which is attached to a not gate that is attached to an or gate (which of course has the other input of a button) which outputs to the door. The door should open when the level starts, but it doesn't, and I think it's because the not gate might think the or gate is outputting to it, instead of the other way around. It only does this when I click "connect to..." on the or gate then click on the not gate. If I do it the other way around it causes an error when I try to preview the level. Please help, because this would make an awesome level.

**Comment by Luke18033** [comment]
You want to connect them the other way. What error appears in the console? That generic error message is completely useless.

**Comment by Luke18033** [comment]
Actually, this seems to be a duplicate of BEEmod/BEE2-items#3359
