### ISSUE TITLE
There was an error building the puzzle

### ISSUE THREAD

**Issue by cryingandten** [BEEmod/BEE2.4#1386]
I installed Bee2mod 4.37.0, worked in it for 1 day and now it gives an error

**Comment by Luke18033** [comment]
That generic error message is completely useless. Open the console immediately after the compile fails, copy the error log (big block of red text), and paste it here.

**Comment by LautaroL20** [comment]
Closing because the author did not respond in a reasonable ammount of time and he probably never will.
