### ISSUE TITLE
BEE2 4.36.1 Already in use error

### ISSUE THREAD

**Issue by CrazyAttack371** [BEEmod/BEE2.4#1387]
This sometimes happens when I use bee mod. I am using BEE2 4.36.1 which most of the time works fine but occasionally this happens. When it does I have to delete the program data for the BEE2 mod and then remove it from the recycle bin and then select where my portal2.exe is located and then load it up and then that error doesn't happen anymore.
![2020-08-29 (2)](https://user-images.githubusercontent.com/70751755/92226552-d4c1c900-ee9c-11ea-9b99-bedfa62112de.png)

**Comment by LautaroL20** [comment]
You've made this issue with what can now be considered are very old versions of the application and packages. Honestly, I do not think that this is an issue anymore, so please get the latest version of BEE2 and then if the issue still exists, let us know and we will re-open the issue.
