### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by WorldTravel1518** [BEEmod/BEE2.4#1388]
I decided to try out Bee 2.4, and when I tested it out I got this error:

Traceback (most recent call last):
File "F:\Git\BEE2.4\src\UI.py", line 851, in export_editoritems
File "F:\Git\BEE2.4\src\gameMan.py", line 866, in export
File "F:\Git\BEE2.4\src\gameMan.py", line 568, in refresh_cache
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bee2\\bee2.exe'

After receiving the error, bee 2 stops working and will not run, even after a restart.

**Comment by Konclan** [comment]
Don't install BEEmod in the steam folder

**Comment by LautaroL20** [comment]
Try installing BEE2 in a separated folder instead of the Portal 2 folder, otherwise issues like this can happen. Also, make sure to get the latest version of BEE2 and then if the issue still exists, let us know and we will re-open the issue.
