### ISSUE TITLE
"View" menu doesn't respond when I click on options

### ISSUE THREAD

**Issue by RileyCollosi** [BEEmod/BEE2.4#1389]
When I hover over View and click on an option, it doesn't do anything.

**Comment by Luke18033** [comment]
What's even in the view menu?

**Comment by TeamSpen210** [comment]
It should have a menu option to hide/show each of the windows.

**Comment by Luke18033** [comment]
Ah.

**Comment by PBodyFan** [comment]
did someone fixed this? it happened to me too
