### ISSUE TITLE
Bruh.

### ISSUE THREAD

**Issue by EmeraldWizardX** [BEEmod/BEE2.4#1392]
I feel like I'm Bricking portal 2 by messing with the files. How do I get an installer for the most recent version of beemod2?

**Comment by LautaroL20** [comment]
Make sure to have downloaded and unzipped the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).
