### ISSUE TITLE
BEE2 4.37.0 launch error

### ISSUE THREAD

**Issue by Dreamanchik** [BEEmod/BEE2.4#1393]
I have a problem when i trying to launch BEEMod 2
![Скриншот 20-09-2020 173358](https://user-images.githubusercontent.com/71598883/93714430-322b6a80-fb6b-11ea-928c-38605ac49662.png)
![Скриншот 20-09-2020 173409](https://user-images.githubusercontent.com/71598883/93714434-3bb4d280-fb6b-11ea-8587-41e50d122cb8.png)
I tried to download BEEMod again, this is doesn't work

**Comment by LautaroL20** [comment]
Are you using the latest beemod release + the latest package release? The application and packages must always be from the same release version, otherwise weird things like that could happen.

**Comment by Nikitasoskov** [comment]
> Are you using the latest beemod release + the latest package release? The application and packages must always be from the same release version, otherwise weird things like that could happen.

still doesn't work

**Comment by LautaroL20** [comment]
You´re not the original author of the issue... why would you reply for him?

**Comment by Nikitasoskov** [comment]
Sorry, I'm downloading the same 4.37.0 bee versions, but still an error

What should I do to fix this error "Bee2 4.37.0 launch error"

**Comment by Nikitasoskov** [comment]
Sorry, I'm downloading the same 4.37.0 bee versions, but still an error

What should I do to fix this error "Bee2 4.37.0 launch error"

**Comment by LautaroL20** [comment]
Did you download the source code or the main archive?

**Comment by Nikitasoskov** [comment]
yes

**Comment by LautaroL20** [comment]
To the second or the latter?

**Comment by LautaroL20** [comment]
To the first or the latter?

**Comment by Nikitasoskov** [comment]
second

**Comment by Nikitasoskov** [comment]
/

**Comment by prostonikitas** [comment]
well, what should I do if I have the same versions and then an error

**Comment by LautaroL20** [comment]
Not sure what was happening with this issue, but you're using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

**Comment by CN1o2** [comment]
For me the same error is happening, I've tried everything. But nothing works.

**Comment by LautaroL20** [comment]
That error is fixed in the next BEEmod release.

**Comment by FrozenDragon0** [comment]
@LautaroL20 If you look at the top of the message it is the latest release.

**Comment by LautaroL20** [comment]
Yes, but there is already another issue for that specific problem and also that error does not have anything to do with the original error of the issue which was made by the user "Dreamanchik".
