### ISSUE TITLE
new image for "space phase" icon

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1394]
I used space engine to capture this image.

![Untitledearth](https://user-images.githubusercontent.com/63530071/93855571-0939df80-fcfb-11ea-86f9-fd19d7e199ba.png)

![scr00186](https://user-images.githubusercontent.com/63530071/93855655-2ec6e900-fcfb-11ea-9fce-4a45f031abe8.png)

![Untitledduke](https://user-images.githubusercontent.com/63530071/93855959-b57bc600-fcfb-11ea-82a3-f2fd461927b3.png)
(a bit wide)

**Comment by supersean08-pro** [comment]
in palettes I have bad spelling

**Comment by Luke18033** [comment]
The current icon is fine.

**Comment by supersean08-pro** [comment]
oh okay
