### ISSUE TITLE
BEE2_4.37 and Portal2 Pazzlemaker logic_relay error and missing cubemaps

### ISSUE THREAD

**Issue by antonische78** [BEEmod/BEE2.4#1395]
Hello. Why does the error appear: "logic relay [name of logic relay] has been trigger but is awaiting refire. OUTPUTS WILL NOT BE FIRED!!!"?
And some of the 3D models look white on the map in Portal 2.

**Comment by FrozenDragon0** [comment]
As for that logic relay error I've seen that in many maps just ignore it. As for white textures your most likely missing custom textures.

**Comment by antonische78** [comment]
screenshots:
[One](https://imgur.com/TKDVcvy)
[Two](https://imgur.com/acYyrvY)

**Comment by Luke18033** [comment]
You don't need to worry about that logic_relay error, it shouldn't affect anything. For the second bug, does that happen right after rebuilding the map? It's a known issue that it occurs when re-entering preview mode without rebuilding, it shouldn't happen in published maps.

**Comment by antonische78** [comment]
I published the map and the bug disappeared. Did not know this. Thanks you!

**Comment by LautaroL20** [comment]
It looks that after all, there is not a real issue here.
