### ISSUE TITLE
Beemod crashes when exporting

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1396]
![image](https://user-images.githubusercontent.com/63530071/93867315-3773eb00-fd0c-11ea-8f74-80a9f8186b1c.png)

**Comment by Luke18033** [comment]
How are you installing it? You need to extract the contents of the zip somewhere, it looks like you're running it out of the temporary folder that WinRAR would have put it in...somehow?

**Comment by LautaroL20** [comment]
Closing because the author did not respond in a reasonable ammount of time and he probably never will.

**Comment by supersean08-pro** [comment]
> Closing because the author did not respond in a reasonable ammount of time and he probably never will.

sorry a cant reply cuz im so into minecraft at the moment using fabric mods, not only that but portal 2 does crash after awhile and i cannot stop it until i do.

**Comment by LautaroL20** [comment]
> supersean08-pro said: "portal 2 does crash after awhile and i cannot stop it until i do."

You should try verify the game cache files of Portal 2 and see if that fixes your game crash.

**Comment by supersean08-pro** [comment]
validating portal 2 takes me a day but when with the files, it does it pretty quick

**Comment by supersean08-pro** [comment]
it lags, but i do have the charger on and it does have a cause on making games lag, mincraft goes from 30 or 80 to 30 or 1 fps, portal 2 just stutters

**Comment by supersean08-pro** [comment]
> What are your PC specs? That sounds like you are using a potato PC...

just look at the top right corner and you will see my gpu (its the only way to see my gpu)

![2020-10-27_20 26 32](https://user-images.githubusercontent.com/63530071/97282566-ed45d280-1892-11eb-8a4a-1a0f559faf09.png)

**Comment by LautaroL20** [comment]
To be honest, i do not have a remote idea why Beemod would crash for you when you try to export the palette, and the fact that you only respond one time per month does not help much with this...
