### ISSUE TITLE
pos1 and neurotoxin error

### ISSUE THREAD

**Issue by darkwolgon** [BEEmod/BEE2.4#1398]
so, I tried to export the pallettes and got this error:                                                                                                                                                               

Traceback (most recent call last):
  File "F:\Git\srctools\srctools\property_parser.py", line 728, in __getitem__
  File "F:\Git\srctools\srctools\property_parser.py", line 477, in _get_value
srctools.property_parser.NoKeyError: No key pos1!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\gameMan.py", line 1024, in build_instance_data
  File "F:\Git\srctools\srctools\property_parser.py", line 730, in __getitem__
IndexError: No key pos1!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 851, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 805, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 1036, in build_instance_data
ValueError: Bad EmbeddedVoxel data in item ITEM_BEE2_NEUROTOXIN_VENT!

please help me to understand and resolve this issue

**Comment by TeamSpen210** [comment]
You need to update the packages, you just updated the application.

**Comment by darkwolgon** [comment]
how would I do that?

**Comment by LautaroL20** [comment]
@darkwolgon - Get the updated packages, here: https://github.com/BEEmod/BEE2-items/releases/tag/v4.37.0

**Comment by darkwolgon** [comment]
will these be placed in the bee2\packadges folder unipped?

**Comment by LautaroL20** [comment]
You just have to unzip it in the same folder that you have installed Beemod.

**Comment by darkwolgon** [comment]
and this is for just beemod2 and I dont need to extract it to a specific
file inside of the beemod2 folder?

**Comment by LautaroL20** [comment]
You need to unzip the updated packages into the same folder where you have installed Beemod, that will make it work. I do not see what part of my comment is not understable...

**Comment by darkwolgon** [comment]
ok thanks Ill let you know if it works ;)

**Comment by darkwolgon** [comment]
sorry, im so new to this XP

**Comment by darkwolgon** [comment]
I also dragged the packages folder by itself to the bee2 folder and it
still didn't work

**Comment by darkwolgon** [comment]
oh never mind, I just deleted and reinstalled and it works just fine,
thanks for your help tho!
