### ISSUE TITLE
BEE2 4.36.1 Launch Error

### ISSUE THREAD

**Issue by Emerald3134** [BEEmod/BEE2.4#1399]
Even though I installed BEE2.4.36.1 correctly even the right packages in all packages in all and even tried puting in  the python36.dll (Portal 2 » portal2 file) and it didn't work. I have the alpha 2 one but I want a newer version, please help.

**Comment by Luke18033** [comment]
What's not working, can you give more detail?

**Comment by Emerald3134** [comment]
[The app/exe isn't working.] I tried without the python file and it said an error "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\beemod2.4\python36.dll" I added the python36.dll file and it still didn't work but it said "please select the game folder executive is located and I select the executive/app and then it says "this doesn't appear to be a valid game folder" and then a long error message then "Failed to execute BEE2"

**Comment by Emerald3134** [comment]
Please answer as soon as possible.

**Comment by Emerald3134** [comment]
Please tell me what to do

**Comment by Emerald3134** [comment]
Ohh this ** ee**

**Comment by Emerald3134** [comment]
nvm it worked
