### ISSUE TITLE
The chamber isnt restarting after reaching elevator in Clean

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2.4#1401]
It just goes up and stops, and nothing happens. I have "restart chamber" in stylevars checked.

**Comment by Thedoczek** [comment]
![2020-10-11 (1)](https://user-images.githubusercontent.com/69758777/95677934-68d42e00-0bc9-11eb-970f-6a4bd993238f.png)
![2020-10-11 (3)](https://user-images.githubusercontent.com/69758777/95677936-6a9df180-0bc9-11eb-902f-d42a3ce7ded4.png)
![2020-10-11](https://user-images.githubusercontent.com/69758777/95677937-6b368800-0bc9-11eb-966d-0cbdcbc26e74.png)

**Comment by seagemgames** [comment]
I believe this is just in the Puzzlemaker. Try publishing and it should work.

**Comment by Thedoczek** [comment]
Yes, that is only in puzzle maker. But still, please fix that

**Comment by Konclan** [comment]
Duplicate of #1119
