### ISSUE TITLE
"There Was An Error Building The Puzzle."

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2.4#1402]
I Placed Rexaura Cube Deflector And Positronic Energy Orb In Portal 1 Style, When I Try To Publish Puzzle This Happened. PS: Rebuilding Works. PPS: I Already Installed Beemod The Right Way, If I Need To Reinstall It Plz Remind Me To.

LoadPortals: couldn't read c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\1602793197.prt

**Comment by KaziPlays** [comment]
Good news, I've Fixed It By Reinstalling BEEMOD Again, You Can Close This Issue Now.

**Comment by LautaroL20** [comment]
Alright, thanks for clarifying it!
