### ISSUE TITLE
BEE2 4.37.0 problem with export

### ISSUE THREAD

**Issue by Zeo3131** [BEEmod/BEE2.4#1407]
can someone help me with problem when i trying to export all things that i choose in portal i get error im trying to redownload and nothing helps i trying to find a problem but i find nothing i trying all but nothing works

**Comment by LautaroL20** [comment]
You did not post the log or an image of the crash to help determining the origin of the crash cause. Regardless of that, you've made this issue with what can now be considered are old versions of the application and packages, so please get the latest version of BEE2 and then if the issue still exists, let us know and we will re-open the issue.
