### ISSUE TITLE
Physics repulsion fields are invisible for those without BEE2.

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1409]
I had somebody do a blind playthrough of my test chamber involving the physics repulsion field and they got confused because it appeared invisible. This is weird because nobody has had this issue before. Is this a bug with the new version of BEE2 or what?

Playthrough: https://www.youtube.com/watch?v=xnIFfIU0mTE

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
