### ISSUE TITLE
BEE2 MAC crash

### ISSUE THREAD

**Issue by DOGZ1234** [BEEmod/BEE2.4#1412]
Whenever I try to open bee2 I get a black screen and get taken back to the login screen I will paste the log here
[bee2.error.txt](https://github.com/BEEmod/BEE2.4/files/5548919/bee2.error.txt)

**Comment by LautaroL20** [comment]
Beemod no longer gives support to Mac systems. You will have to build a cheap PC with Windows to run Beemod.
