### ISSUE TITLE
Old aperture cubes used with the cube colouriser causes a leak.

### ISSUE THREAD

**Issue by tastyl** [BEEmod/BEE2.4#1414]
If you put a cube colouriser with an old aperture cube, with or without the dropper, playing the level causes a leak until you enter.

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
