### ISSUE TITLE
Can't open Mac versions, makes error. (PLEASE HELP!)

### ISSUE THREAD

**Issue by ThaFeeesh** [BEEmod/BEE2.4#1418]
Using the Mac-compatible versions.

An error occurred: 
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "BEE2.py", line 119, in <module>
  File "gameMan.py", line 1081, in init_trans
  File "gameMan.py", line 1109, in load_trans
  File "site-packages/srctools-1.2.0-py3.6-macosx-10.9-x86_64.egg/srctools/property_parser.py", line 381, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".

This has been copied to the clipboard.

Please help!

**Comment by ThaFeeesh** [comment]
This happens during opening btw.

**Comment by LautaroL20** [comment]
Beemod is no longer giving support to Mac systems anymore, you will have to get a Windows system to run Beemod.

**Comment by ThaFeeesh** [comment]
Lautaro, I was using an OLDER VERSION that SUPPORTS MAC.

**Comment by LautaroL20** [comment]
> ThaFeeesh said: "Lautaro, I was using an OLDER VERSION that SUPPORTS MAC."

If TeamSpen210 wanted to fix issues related with an old version, he would instead release a new one with their respective fixes but that´s not happen anymore. Anyways I highly doubt that your issue would be easy to solve without fixing a bunch of other things. I think that having tried to create a Mac version of Beemod was a big mistake, mostly because it always occurs severe difficulties of many kinds that end up as it was with this.

Not sure if a linux version of Beemod is planned, but if so, there is a 99% chance that would occur the same as it was with the Mac one, unfortunately.

**Comment by ThaFeeesh** [comment]
Lautaro, I'm not saying this is a problem with Bee2, I think it's a problem with my computer, which I want help understanding.

**Comment by ThaFeeesh** [comment]
>I think that having tried to create a Mac version of Beemod was a big mistake, mostly because it always occurs severe difficulties of many kinds that end up as it was with this.

So you would rather have Mac users not be able to use the software than have some more work put in?

**Comment by TeamSpen210** [comment]
The problem is with `portal 2/portal2_dlc2/resource/basemodui.txt` - Valve messed up the file. Open it up and add a second `}` to the very end.

**Comment by ThaFeeesh** [comment]
Thanks Spen, very cool!

**Comment by ThaFeeesh** [comment]
> The problem is with `portal 2/portal2_dlc2/resource/basemodui.txt` - Valve messed up the file. Open it up and add a second `}` to the very end.

Do you mean basemodui_english.txt? Because basemodui.txt doesn't exist.

**Comment by RedRavenYouTube** [comment]
I cannot even find the file to run bee2 I am using version Prerelease 23 bc it is compatible with macos

**Comment by RedRavenYouTube** [comment]
Now I only get SYNTAX ERROR

**Comment by LautaroL20** [comment]
Mac Os X no longer supports Portal 2 because Apple decided to remove 32 bit games support, this is why BEEmod stopped supporting that OS.

**Comment by RedRavenYouTube** [comment]
Even with older versions.
