### ISSUE TITLE
Monitors make the wall go out and float instead of disappearing

### ISSUE THREAD

**Issue by Entilled** [BEEmod/BEE2.4#1419]
I had seen this while testing chambers, and I always had to fix it. Certain random areas will cause the monitors to make the wall go out in front of itself. So far it's only been with glad0s in clean chambers, but it might also affect other ones
![image](https://user-images.githubusercontent.com/75185125/100526715-89683f80-3199-11eb-899d-e08004df1444.png)

**Comment by LautaroL20** [comment]
LOL, that is certainly one of the most crazy bugs i´ve seen since a long time here!

**Comment by Luke18033** [comment]
They must have their move direction set wrong.

**Comment by LautaroL20** [comment]
By the way, you have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
