### ISSUE TITLE
Bug with Shrek.

### ISSUE THREAD

**Issue by OceanWaves914** [BEEmod/BEE2.4#1420]
I was testing my map with BEE2, When I thought I saw Shrek the Ogre in the corner of my eye. I checked and all that was there was repulsion gel. I finished the map then my computer crashed, and there was an image of Phillip from ATNRPG with Megalovania playing in the background. I freaked out and went to the garage to grab something from walmart when Thomas the Tank Engine had Replaced my Car. He whispered: "Your Next" I pointed out his horrible grammar and went back home when DAME TU COSITA stabbed me with a knife. I'm in hell writing this, So can you please fix this bug? It's no biggie but it gets in the way (=

**Comment by Luke18033** [comment]
Okay come on, seriously? What did we just say about opening joke issues? At least the Herobrine thing was based on the changelog but this is just random memeing. This is an issue tracker, ***NOT*** a forum, so ***STOP*** using it like one!
