### ISSUE TITLE
Visible trigger

### ISSUE THREAD

**Issue by antonische78** [BEEmod/BEE2.4#1423]
Hello! Why is the trigger visible?
<a href="https://ibb.co/bXHzbc0"><img src="https://i.ibb.co/bXHzbc0/preview0000.jpg" alt="preview0000" border="0"></a>

**Comment by FrozenDragon0** [comment]
Did you have the show triggers option checked in the BEE2 interface?

**Comment by antonische78** [comment]
I checked. Shows triggers. Thanks!

**Comment by LautaroL20** [comment]
This is on purpose.
