### ISSUE TITLE
Errors in bee mod and hammer

### ISSUE THREAD

**Issue by antonische78** [BEEmod/BEE2.4#1424]
Why does the message appear when opening .vmf from BeeMod in hammer:
Could not open instance directory/name.vmf? 
[<a href="https://imgbb.com/"><img src="https://i.ibb.co/XDpc744/2020-11-30-205118.jpg" alt="2020-11-30-205118" border="0"></a>](url)
Is it possible to open a .vmf from a bee mod in hammer and compile it without problem? .vmf is correct.
It is also not possible to open .prt.
[<a href="https://ibb.co/Fnbmykq"><img src="https://i.ibb.co/DLDzvPg/2020-11-30-211501.jpg" alt="2020-11-30-211501" border="0"></a>](url)

**Comment by TeamSpen210** [comment]
You cannot use the maps in that folder, since they don't have the BEE compiler's modifications. You need to open the maps in styled/. However you really shouldn't, these maps are built only to be compiled, they have all sorts of tricks and confusing logic.
