### ISSUE TITLE
Cube droppers stay open after dropping a cube (Portal 1)

### ISSUE THREAD

**Issue by PixelHUN** [BEEmod/BEE2.4#1425]
As in the title: The droppers will stay open, and will not drop another cube if the cube is destroyed.
![image](https://user-images.githubusercontent.com/59181913/100766063-84ed9200-33f8-11eb-85b9-8020678fc1ce.png)

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
