### ISSUE TITLE
triggers don't work

### ISSUE THREAD

**Issue by ebartaus** [BEEmod/BEE2.4#1431]
(sorry, i'm russian, and I translate the text through yandex.translate) i can't use triggers - i put any of them, but when you enter them, nothing happens. what could be the problem? i have BEEMOD 4.37.0 from the repository on github.

**Comment by seagemgames** [comment]
I believe triggers in v4.37 are broken. Try downgrading to v4.36

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
