### ISSUE TITLE
Problem with export on BEE 4.37.0 (Linux)

### ISSUE THREAD

**Issue by ghost** [BEEmod/BEE2.4#1432]
When trying to export the BEE2 configuration to Portal 2 on Linux (running from source), it stops on 'Copying resources!' during the export process.
Here's the output that I get in console:

> [I] gameMan.export(): --------------------
> [I] gameMan.export(): Exporting Items and Style for "PORTAL 2"!
> [I] gameMan.export(): Style = BEE2_1960s
> [I] gameMan.export(): Music = {<MusicChannel.BASE: 'base'>: <Music VALVE_VIT_ORDER_2>, <MusicChannel.TBEAM: 'tbeam'>: <Music VALVE_VIT_ORDER_FUNNEL>, <MusicChannel.BOUNCE: 'BounceGel'>: <Music VALVE_CAUSE_SCIENCE>, <MusicChannel.SPEED: 'SpeedGel'>: <Music VALVE_GEL_REUNION>}
> [I] gameMan.export(): Skybox = BEE2_SPHERE_INTERIOR
> [I] gameMan.export(): QuotePack = BEE2_CAVE_60s
> [I] gameMan.export(): Elevator = None
> [I] gameMan.export(): Item = [('ITEM_BUTTON_PEDESTAL', 0), ('ITEM_BUTTON_FLOOR', 0), ('ITEM_BUTTON_FLOOR', 1), ('ITEM_BUTTON_FLOOR', 2), ('ITEM_CUBE', 0), ('ITEM_CUBE', 1), ('ITEM_CUBE', 3), ('ITEM_CUBE', 4), ('ITEM_TBEAM', 0), ('ITEM_CATAPULT', 0), ('ITEM_LIGHT_BRIDGE', 0), ('ITEM_PANEL_STAIRS', 0), ('ITEM_BARRIER_HAZARD', 0), ('ITEM_BARRIER', 0), ('ITEM_PISTON_PLATFORM', 0), ('ITEM_RAIL_PLATFORM', 0), ('ITEM_LASER_EMITTER_CENTER', 0), ('ITEM_LASER_CATCHER_CENTER', 0), ('ITEM_LASER_RELAY_CENTER', 0), ('ITEM_CUBE', 2), ('ITEM_PANEL_CLEAR', 0), ('ITEM_PANEL_ANGLED', 0), ('ITEM_PANEL_FLIP', 0), ('ITEM_SECONDARY_OBSERVATION_ROOM', 0), ('ITEM_BARRIER_HAZARD', 1), ('ITEM_TURRET', 0), ('ITEM_GOO', 0), ('ITEM_LIGHT_PANEL', 0), ('ITEM_PAINT_SPLAT', 0), ('ITEM_PAINT_SPLAT', 1), ('ITEM_PAINT_SPLAT', 2), ('ITEM_PAINT_SPLAT', 3)]
> [I] gameMan.export(): StyleVar = {'DoorCameras': True, 'RestartOnExit': True, 'MultiverseCave': True, 'FixFizzlerBump': False, 'NoMidVoices': False, 'UnlockDefault': False, 'AllowGooMist': True, 'FunnelAllowSwitchedLights': True, 'EnableShapeSignageFrame': True}
> [I] gameMan.export(): Signage = [('3', 'SIGN_NUM_1'), ('4', 'SIGN_NUM_2'), ('5', 'SIGN_NUM_3'), ('6', 'SIGN_NUM_4'), ('7', 'SIGN_EXIT'), ('8', 'SIGN_CUBE_DROPPER'), ('9', 'SIGN_BALL_DROPPER'), ('10', 'SIGN_REFLECT_CUBE'), ('11', 'SIGN_GOO_TOXIC'), ('12', 'SIGN_TBEAM'), ('13', 'SIGN_TBEAM_POLARITY'), ('14', 'SIGN_LASER_RELAY'), ('15', 'SIGN_TURRET'), ('16', 'SIGN_LIGHT_BRIDGE'), ('17', 'SIGN_PAINT_BOUNCE'), ('18', 'SIGN_PAINT_SPEED')]
> [I] gameMan.export(): Should refresh: True
> [I] gameMan.cache_invalid(): Need to extract - package counts inconsistent!
> [I] gameMan.export(): Cache invalid - copying..
> [I] gameMan.export(): Exporting "Item"
> [I] gameMan.export(): Exporting "ItemConfig"
> [I] gameMan.export(): Exporting "QuotePack"
> [I] packageLoader.export(): Voice conf path: /home/user/.config/BEEMOD2/config/voice/BEE2_CAVE_60s.cfg
> [I] packageLoader.export(): No normal voice config!
> [I] packageLoader.export(): Voice conf path: /home/user/.config/BEEMOD2/config/voice/MID_BEE2_CAVE_60s.cfg
> [I] packageLoader.export(): No MidChamber voice config!
> [I] packageLoader.export(): Voice conf path: /home/user/.config/BEEMOD2/config/voice/RESP_BEE2_CAVE_60s.cfg
> [I] packageLoader.export(): No Responses voice config!
> [I] gameMan.export(): Exporting "Skybox"
> [I] gameMan.export(): Exporting "Music"
> [I] gameMan.export(): Exporting "Signage"
> [W] packageLoader._serialise(): No valid "BEE2_1960s" style for "SIGN_REFLECTION_DROPPER" signage!
> [W] packageLoader._serialise(): No valid "BEE2_1960s" style for "SIGN_NO_DRINK" signage!
> [I] gameMan.export(): Exporting "StyleVar"
> [I] gameMan.export(): Exporting "StyleVPK"
> [I] packageLoader.export(): Sound cache: /home/user/.steam/debian-installation/steamapps/common/Portal 2/portal2_dlc3/maps/soundcache/_master.cache
> [I] packageLoader.export(): Written 70 files to VPK!
> [I] gameMan.export(): Exporting "Elevator"
> [I] gameMan.export(): Exporting "PackList"
> [I] packageLoader.export(): Writing packing list!
> [I] gameMan.export(): Exporting "EditorSound"
> [I] gameMan.export(): Exporting "BrushTemplate"
> [I] gameMan.export(): Exporting "ConfigGroup"
> [I] BEE2_config.save(): Saving changes in config "/home/user/.config/BEEMOD2/config/item_cust_configs.cfg"!
> [I] gameMan.export(): bin/vbsp.exe: normal=Valve, backup=Valve
> [I] gameMan.export(): Backing up original Windows VBSP!
> [I] gameMan.export(): bin/vrad.exe: normal=Valve, backup=Valve
> [I] gameMan.export(): Backing up original Windows VRAD!
> [I] gameMan.export(): bin/vbsp_osx: normal=Valve, backup=Valve
> [I] gameMan.export(): Backing up original OSX VBSP!
> [I] gameMan.export(): bin/vrad_osx: normal=Valve, backup=Valve
> [I] gameMan.export(): Backing up original OSX VRAD!
> [I] gameMan.export(): bin/vbsp_linux: normal=BEE2, backup=Valve
> [I] gameMan.export(): bin/vrad_linux: normal=BEE2, backup=Valve
> [I] gameMan.export(): Editing Gameinfo...
> [I] gameMan.export(): Adding ents to FGD.
> [I] gameMan.export(): Writing instance list...
> [I] gameMan.export(): Writing Editoritems...
> [I] gameMan.export(): Writing VBSP Config!
> [I] gameMan.export(): Copying Custom Compiler!
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_codecs_jp.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_codecs_jp.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/libmpdec.so.2 -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/libmpdec.so.2
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_codecs_kr.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_codecs_kr.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_hashlib.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_hashlib.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/resource.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/resource.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_codecs_hk.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_codecs_hk.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_codecs_cn.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_codecs_cn.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_opcode.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_opcode.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/libexpat.so.1 -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/libexpat.so.1
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/base_library.zip -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/base_library.zip
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_codecs_tw.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_codecs_tw.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/vrad_linux -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/vrad_linux
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_multibytecodec.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_multibytecodec.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_codecs_iso2022.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_codecs_iso2022.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/vbsp_linux -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/vbsp_linux
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/libpython3.8.so.1.0 -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/libpython3.8.so.1.0
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/libcrypto.so.1.1 -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/libcrypto.so.1.1
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_lzma.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_lzma.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/liblzma.so.5 -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/liblzma.so.5
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_decimal.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_decimal.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/_contextvars.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/_contextvars.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/libz.so.1 -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/libz.so.1
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/srctools/py.typed -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/srctools/py.typed
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/srctools/_tokenizer.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/srctools/_tokenizer.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/srctools/fgd.lzma -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/srctools/fgd.lzma
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/srctools/_vec.cpython-38-x86_64-linux-gnu.so -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/srctools/_vec.cpython-38-x86_64-linux-gnu.so
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/srctools/srctools.fgd -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/srctools/srctools.fgd
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources-3.3.0-py3.8.egg-info/METADATA -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources-3.3.0-py3.8.egg-info/METADATA
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources-3.3.0-py3.8.egg-info/LICENSE -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources-3.3.0-py3.8.egg-info/LICENSE
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources-3.3.0-py3.8.egg-info/RECORD -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources-3.3.0-py3.8.egg-info/RECORD
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources-3.3.0-py3.8.egg-info/WHEEL -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources-3.3.0-py3.8.egg-info/WHEEL
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources-3.3.0-py3.8.egg-info/top_level.txt -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources-3.3.0-py3.8.egg-info/top_level.txt
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources-3.3.0-py3.8.egg-info/INSTALLER -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources-3.3.0-py3.8.egg-info/INSTALLER
> [I] gameMan.export(): 	* /home/user/BEE2/compiler/importlib_resources/version.txt -> /home/user/.steam/debian-installation/steamapps/common/Portal 2/bin/importlib_resources/version.txt
> [I] gameMan.export(): Copying Resources!

And it just hangs there and never finishes.
When starting Portal 2, as expected, the style exported correctly, however the custom models and textures are missing and show as errors.

**Comment by CStafford-14** [comment]
Glad to see I'm not the only one running into this issue.

Are you running it natively or with WINE?

**Comment by haydenwalker980** [comment]
He said he's running from source so likely natively.
