### ISSUE TITLE
Skybox not rendering in place of Goo

### ISSUE THREAD

**Issue by zackabee** [BEEmod/BEE2.4#1434]
![image](https://user-images.githubusercontent.com/76178132/102523635-d25b3780-4065-11eb-8e75-e917cf604758.png)

![image](https://user-images.githubusercontent.com/76178132/102523533-a93aa700-4065-11eb-9c69-719266633326.png)

![image](https://user-images.githubusercontent.com/76178132/102523860-27974900-4066-11eb-9019-4b59698e9d52.png)

Have set skybox to 3D in BEE2 application, other elements work properly but goo is not replaced with a skybox.

**Comment by seagemgames** [comment]
Are you using v4.37.0? I believe 3D skybox pits are broken, and it's recommended to use v4.36.1;

**Comment by Luke18033** [comment]
They're not "broken", they were intentionally not reimplemented because the plan is to replace them with proper environments generated directly around the map.

**Comment by zackabee** [comment]
Is there a place I can follow development other than here?

**Comment by Konclan** [comment]
There is a discord linked in the FAQ
