### ISSUE TITLE
Aperture Tag: Compiler stops at Building Geometry, game crashes soon after canceling compiling.

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2.4#1435]
Additionally, when I choose Clean style, items are clean, but walls and the game are those from 70's style.

**Comment by Thedoczek** [comment]
Well, I got new device. I'll try again soon and check is this only device problem (Now I have very good computer, previous was very low-end.)

**Comment by Luke18033** [comment]
See #1531, this has been fixed in 4.40.
