### ISSUE TITLE
"There Was An Error While Building The Puzzle"

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2.4#1442]
When i tried To publish a certain map it said this:

LoadPortals: couldn't read c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\1609161038.prt

The other maps work fine.

I didn't try reinstalling BEEMOD but I will try and if I succeed I'll tell.

**Comment by seagemgames** [comment]
What elements do you have around your map? Are any of them near a wall, do you have any UCPs?
If you send the file at c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.vmf (something like this) it can help fix the issue.

**Comment by KaziPlays** [comment]
The style is Portal 1, the items i placed are the HEP Catcher, HEP Launcher, Goo, Unstationary Scaffold, Victory Lift, Turrets, Small and big observatory rooms, doors, etc...

And yeah almost all of them are near a wall or on a wall,

And what is a UCP

**Comment by KaziPlays** [comment]
I don't have the map anymore so
bye issue
