### ISSUE TITLE
There Was An Error While Building The Puzzle

### ISSUE THREAD

**Issue by cryingandten** [BEEmod/BEE2.4#1445]
The error occurred on the second day of using.

VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'voice_pack': 'BEE2_GLADOS_APOC'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 7
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (95 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.sendtor.res_sendificator(): Relay: <Entity>: 
 | {
 | 	 targetname = "@sendtor28_las_relay_1"
 | 	 origin = "2168 704 416"
 | 	 angles = "-0 180 0"
 | 	 classname = "logic_relay"
 | 	 StartDisabled = "0"
 | 	<Output> OnTrigger -> !self -> RunScriptCode (::sendtor_source <- self;)
 | 	<Output> OnTrigger -> @sendtor_fire -> Trigger
 | }
 | 
 |___

[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] brushes.res_import_template(): IDS: set()
[I] brushes.res_import_template(): IDS: {'2', '1'}
[I] brushes.res_import_template(): IDS: {'2', '1'}
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1377 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1472 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1567 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 2/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "DEADLY_NO_SAFETY"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/glados/prehub47.vcd"
 | 		"2" "npc/glados/prehub48.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/4 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_BETTER_THAN_RECORD"
 | 	"Choreo" "npc/glados/prehub14.vcd"
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[W] packing.pack_list(): Packlist "PACK_HMW_SENDTOR_LOGIC" does not exist!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: N, Orange: N
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['bottomless_pit', 'glass', 'cube', 'cubereflect', 'cubedropperlessreflect', 'cubenotcompanion', 'laseremitter', 'laser', 'deadly', 'sendificator', 'sendtor', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'orangeportal', 'blueportal', 'orangeportalspawner', 'orangeportalgun', 'blueportalspawner', 'blueportalgun', 'dualportalgun', 'lasercatcher', 'pedestalbutton', 'needsportalman', 'spawn_nogun']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=14577, misses=373, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/logic/goo_fade.vmf', 'instances/bee2/logic/reflection_cube_wake.vmf', 'instances/bee2/logic/hmw/sendtor_manager.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: True
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_brush(): Creating Bottomless Pits...
[I] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf']}
[I] bottomlessPit.make_bottomless_pit(): Pos: 1472 576 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1344 704 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1216 320 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1088 448 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1216 704 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1088 576 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1344 320 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[I] bottomlessPit.make_bottomless_pit(): Pos: 1472 448 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[I] vbsp.change_brush(): Done!
[I] vbsp.clump_walls(): Clumping: 660 clumps (+ 0 special)
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'F:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 6 threads
[I] <valve>.vbsp(): materialPath: F:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/logic/BEE/antline_signage.vmf
[I] <valve>.vbsp():

**Comment by seagemgames** [comment]
What version of BEEmod are you using? If you are using v4.37.0, try removing the Sendificator.

**Comment by cryingandten** [comment]
4.36.1 Because in 4.37 i can't listen to music

**Comment by cryingandten** [comment]
In my level, sendificator is the main object. Maybe I need to do 1 export per level?

**Comment by seagemgames** [comment]
Ah, my mistake, do you use the connection signage item? That appears to be missing.

**Comment by cryingandten** [comment]
Yes

**Comment by seagemgames** [comment]
It appears it would be bugged. You'll have to remove it until a patch comes out and v4.37 is stable.

**Comment by cryingandten** [comment]
Thanks
