### ISSUE TITLE
Suggestion : Enhanced bottomless pits and turret skins

### ISSUE THREAD

**Issue by SebTheDestroyer** [BEEmod/BEE2.4#1446]
Not sure if this is a feature yet but a cool feature I think should be added to BEEMOD would be if you could change goo pits to bottomless pits using the button property or as a different item and not just in the manufacturing style. What would also be cool is if you could have like a different turret item that is the exact same as the regular turrets except they have the timer property which could be used to change their skins, e.g: 1 is normal, 2 is defective and 3 could be that defective one but with the hazard tape.

**Comment by seagemgames** [comment]
The bottomless pits are already a thing, but haven't been added to v4.37 yet. As for turret skins, they don't exactly serve a purpose in the puzzlemaker, but if you do want them, you can download my addons [here](https://github.com/CheezyPig/saismee-addons/releases/tag/1.61).

Also, for item issues you should post in [BEE2-items](https://github.com/BEEmod/BEE2-items). It helps them keep track of things easier.

**Comment by FrozenDragon0** [comment]
The bottomless pits have been disabled in v4.37. They've been a feature for awhile now just disabled for 4.37 due to the new tiling system.
