### ISSUE TITLE
Export Options won't appear when I open Bee2

### ISSUE THREAD

**Issue by DerpyBat** [BEEmod/BEE2.4#1448]
Every time I open up Bee2, the Export Options flash for a second but then immediately go away. I can't even select it in the view options. It doesn't let me open it up; and I have no other ideas for how I could get it to open. Any possible way to fix this or do I have to reinstall Bee2? Because I don't wanna be stuck with the 1960s setting.

**Comment by MineDude9** [comment]
Is it possible its going behind the bee window?

**Comment by DerpyBat** [comment]
I tried checking by making the Bee Window Smaller, making it thinner horizontally. But it isn't there. I don't think it'd be going there anyways because when I hover over Bee2.4 in the tabs on the bottom of my screen, I can sorta see like the outline or something of the Export Options. But it doesn't pop up when I click into Bee2.4

**Comment by DerpyBat** [comment]
Okay, never mind, I found out the issue. There's a little button that says "Hide/Show The Export Options Window" and now I feel like a big idiot. Why that button is there, I have no clue at all whatsoever. Sorry for wasting time.
