### ISSUE TITLE
Problem with compile all of fizzlers in Horizontal rotation

### ISSUE THREAD

**Issue by THS2121966** [BEEmod/BEE2.4#1451]
Problem with compile all of fizzlers in Horizontal rotation.
[BEEMOD_FAILED.txt](https://github.com/BEEmod/BEE2.4/files/5813521/BEEMOD_FAILED.txt)

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
