### ISSUE TITLE
Adjust the layout of the compile option's map settings tab

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#1454]
![image](https://user-images.githubusercontent.com/16567080/104628982-83052880-565e-11eb-9075-16671f991f0c.png)
Use voiceline priorities should be moved to the Styles/Item Properties' Styles tab and the Corridor section should be redone so all 3 options are in a line. The current Corridor section layout has always been confusing to me.

Edit: Concept art by saismee
![image](https://user-images.githubusercontent.com/16567080/104629450-26563d80-565f-11eb-9aa0-e27f3d7c125c.png)

**Comment by TeamSpen210** [comment]
Voiceline priorities is here because of the message at the top - it takes effect instantly.
