### ISSUE TITLE
A truly automatic installer for BEE2 (Win32/64)

### ISSUE THREAD

**Issue by programmer2514** [BEEmod/BEE2.4#1455]
A while back, I had written a basic installer for BEE2 in NSIS, but, as @TeamSpen210 pointed out [here](https://github.com/BEEmod/BEE2.4/issues/1121), it had many drawbacks.
I think I have fixed them with my latest, completely-automated installer for BEE2.

This installer integrates directly with the BEE2 application, automatically checking for updates on launch, and will download them DIRECTLY FROM GITHUB, requiring no extra work from any developer. The second an update is released on GitHub, everyone who uses the installer will be notified and updated.

Downloads and more information can be found here: https://github.com/programmer2514/BEE2.4-Installer-Automatic

Feel free to contact me with comments or suggestions, and I will see if I can implement them.

P.S. Sorry if this is the wrong place to put this, but I couldn't really think of anywhere else

**Comment by LautaroL20** [comment]
That is a really interesting contribution! Let´s see what TeamSpen210 says to this, hope he is agreed to implement it although he may ask you for the code of it to add extra stuff if needed.

**Comment by programmer2514** [comment]
I've licensed it under the WTFPL, so anyone can feel free to take the code from the repo any time :)
