### ISSUE TITLE
Bee2 mod: Windows security thinks its a trojan

### ISSUE THREAD

**Issue by PockyXx** [BEEmod/BEE2.4#1458]
Since 4.38.0, My PC thinks its a trojan of some sort.
Note that it didn't happen with the previous version 4.37.0.
Here's a screenshot 
![Capture](https://user-images.githubusercontent.com/77648931/104974420-f80d9080-59c5-11eb-9fcf-fc8736a98678.PNG)
For the moment, I'm sticking with 4.37.0.

**Comment by DeliWasTaken** [comment]
No, its completely normal. Theres nothing wrong with it.

**Comment by ENDERZOMBI102** [comment]
its just windows beings windows, as BEEmod is _not_ signed (basically a paid process that makes sure the author is known) smartscreen/defender/[INSERT_OTHER_AV_HERE] detects it as malware, because normally, programs are signed

**Comment by LautaroL20** [comment]
Also, make sure to add the `BEE2.exe` from the Beemod user interface as well.
