### ISSUE TITLE
Suggestion: Make BEE2 it's own editor.

### ISSUE THREAD

**Issue by TR011F4C3** [BEEmod/BEE2.4#1460]
I suggest a built in editor - similar to the in game one, allowing users to have multiple pages of palletes. I would use hammer but I find it hard.

**Comment by FrozenDragon0** [comment]
Not possible without source code access.

**Comment by TR011F4C3** [comment]
I don't mean a version of the ingame editor - I mean an editor included with BEE2 somewhat similar to the in game one allowing multiple pages of palletes, I am aware it is impossible to add multiple pages of palletes to the main game.

**Comment by seagemgames** [comment]
That's not really what BEEmod is for... you may want to look into [Portal 2: Community Edition](https://www.portal2communityedition.com/). It will have a re-written in-game editor.

**Comment by Konclan** [comment]
Also pretty much describes what ExPM is gonna be

**Comment by TR011F4C3** [comment]
What’s exon?

**Comment by Luke18033** [comment]
Yeah, this isn't really a suggestion for BEEmod. This would end up being a different program entirely.
