### ISSUE TITLE
E3 portal mod

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1461]
I found mods that might make the e3 style possible

**Faster but not a lot process:**
Door:
https://www.moddb.com/addons/betadoor
https://gamebanana.com/skins/178251

Portal gun (BETA ANIMATIONS):
https://gamebanana.com/skins/178419

Portal:
https://gamebanana.com/skins/178168

Button:
https://gamebanana.com/skins/178411

Cube:
https://gamebanana.com/skins/178132

Railing:
https://gamebanana.com/skins/153793

laser:
https://gamebanana.com/skins/178261

Toxic goo:
https://gamebanana.com/textures/6013

Bridge:
https://gamebanana.com/skins/157200

Autoportal:
https://gamebanana.com/skins/143381

**Slower but cleaner process:**
Mod by: CutContentNetwork
https://www.moddb.com/mods/portal-2-beta

**Comment by Luke18033** [comment]
All of these are just recreations, we're not adding a beta style.

**Comment by supersean08-pro** [comment]
okay

**Comment by FrozenDragon0** [comment]
Even if we did do a beta style packing different hard light bridge and laser textures into a map is not possible.
