### ISSUE TITLE
add an option so you can make your own voicelines

### ISSUE THREAD

**Issue by thedeathiscoming** [BEEmod/BEE2.4#1463]

**Comment by seagemgames** [comment]
You already can with UCPs, but they must be pre-existing ones that are already in-game for them to work.

**Comment by Flash4433** [comment]
https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-custom-voicelines--voicelines-from-mod-x-to-bee24

**Comment by FrozenDragon0** [comment]
Not going to be implemented.
