### ISSUE TITLE
BEE 2.4 won't get past the lighting bar before showing a build error

### ISSUE THREAD

**Issue by BLUcat5995** [BEEmod/BEE2.4#1464]
[I made a short video to show the problem.](https://youtu.be/2WueiBn3gMM)

**Comment by supersean08-pro** [comment]
same
even the video

**Comment by BLUcat5995** [comment]
I even tried to do it in hammer and it still doesn't work, it gives the same error

**Comment by supersean08-pro** [comment]
i have the same thing meaning its not just me

**Comment by supersean08-pro** [comment]
here are mine

[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_lautaro_reclined_fizzler_x1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_lautaro_reclined_fizzler_x1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_lautaro_reclined_fizzler_x2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_lautaro_reclined_fizzler_x2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_lautaro_reclined_fizzler_x3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_lautaro_reclined_fizzler_x3.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Connection to Steam servers successful.
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,5)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 104 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198235887676\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 25349 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 25765 (ms)

VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.main(): Loading Settings...
[I] vrad.main(): Config Loaded!
[I] vrad.main(): Reading BSP
[I] vrad.main(): Final status: is_peti=True, edit_args=True
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[I] vrad.main(): Checking for music:
[I] vrad.main(): Run transformations...
[I] bsp_trans.run_transformations(): Running "P2 Antlines"...
[I] bsp_trans.run_transformations(): Running "P2 Coop Trigger"...
[I] bsp_trans.run_transformations(): Running "P2 Goo"...
[I] bsp_trans.run_transformations(): Running "comp_entity_finder"...
[I] bsp_trans.run_transformations(): Running "Attachment Points"...
[I] bsp_trans.run_transformations(): Running "VScript Init Code"...
[I] bsp_trans.run_transformations(): Running "VScript RunScript Inputs"...
[I] bsp_trans.run_transformations(): Running "Proxy limits"...
[I] bsp_trans.run_transformations(): Running "comp_kv_setter"...
[W] kv_setter.kv_setter(): No entities found named "cd6721-close_trig" for comp_kv_setter at (448 576 576)!
[W] kv_setter.kv_setter(): No entities found named "cd6495-close_trig" for comp_kv_setter at (448 448 576)!
[W] kv_setter.kv_setter(): No entities found named "cd7007-close_trig" for comp_kv_setter at (448 704 576)!
[W] kv_setter.kv_setter(): No entities found named "cd5581-close_trig" for comp_kv_setter at (448 320 576)!
[W] kv_setter.kv_setter(): No entities found named "cd12229-close_trig" for comp_kv_setter at (448 192 576)!
[I] bsp_trans.run_transformations(): Running "comp_relay"...
[I] bsp_trans.run_transformations(): Running "comp_numeric_transition"...
[I] bsp_trans.run_transformations(): Running "comp_entity_mover"...
[I] bsp_trans.run_transformations(): Running "comp_precache_model"...
[I] bsp_trans.run_transformations(): Running "comp_precache_sound"...
[I] bsp_trans.run_transformations(): Running "comp_pack_replace_soundscript"...
[I] bsp_trans.run_transformations(): Running "comp_pack"...
[I] bsp_trans.run_transformations(): Running "comp_pack_rename"...
[I] bsp_trans.run_transformations(): Running "Fix Laser Catcher Skins"...
[I] bsp_trans.run_transformations(): Running "Force Paint in Map"...
[I] bsp_trans.run_transformations(): Running "Precache P2 Light Bridge"...
[I] bsp_trans.run_transformations(): Running "comp_choreo_sceneset"...
[I] bsp_trans.run_transformations(): Running "comp_scriptvar_setter"...
[I] bsp_trans.run_transformations(): Running "trigger_brush Input Filters"...
[I] bsp_trans.run_transformations(): Running "Fix alternate classnames"...
[I] bsp_trans.run_transformations(): Running "Branch Listener UniqueState"...
[I] bsp_trans.run_transformations(): Running "Portal 2 Vactubes"...
[I] bsp_trans.run_transformations(): Running "BEE2: Coop Responses"...
[I] bsp_trans.run_transformations(): Running "BEE2: Cube VScript Filters"...
[I] filter.cube_filter(): Script buffers: []
[I] bsp_trans.run_transformations(): Running "Optimise logic_auto"...
[I] bsp_trans.run_transformations(): Running "Strip Entities"...
[I] bsp_trans.run_transformations(): Injecting VScript code...
[I] vrad.main(): Scanning map for files to pack:
[W] packlist.pack_fgd(): Unknown keyvalue "visible" for ent of type "trigger_catapult"!
[W] packlist.pack_fgd(): Unknown keyvalue "PaintPower" for ent of type "prop_monster_box"!
[W] packlist.pack_fgd(): Unknown keyvalue "defaultstyle" for ent of type "light"!
[W] packlist.pack_fgd(): Unknown keyvalue "InputFilter" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "null" for ent of type "ambient_generic"!
[W] packlist.pack_fgd(): Unknown keyvalue "fademindist" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "fadescale" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "disableX360" for ent of type "prop_dynamic"!
[W] packlist.pack_fgd(): Unknown keyvalue "fademaxdist" for ent of type "weapon_portalgun"!
[W] packlist.pack_fgd(): Unknown keyvalue "fademindist" for ent of type "weapon_portalgun"!
[W] packlist.pack_fgd(): Unknown keyvalue "fadescale" for ent of type "weapon_portalgun"!
[W] packlist.pack_fgd(): detail.vbsp file does not exist: "detail.vbsp"
[W] packlist._get_material_files(): File "materials/sprites/effects/bluelaser1.vmt" does not exist!
[W] packlist.pack_soundscript(): Unknown sound "doors.move14"!
[W] packlist.pack_soundscript(): Unknown sound "your.soundname"!
[I] vrad.main(): Done!
[I] vrad.main(): Writing to BSP...
[W] packlist.pack_into_zip(): WARNING: "materials/sprites/effects/bluelaser1.vmt" not packed!
[W] packlist.pack_into_zip(): WARNING: "media/aperture_appear.bik" not packed!
[W] packlist.pack_into_zip(): WARNING: "detail.vbsp" not packed!
[W] packlist.pack_into_zip(): WARNING: "sound/doors/doormove1.wav" not packed!
[W] packlist.pack_into_zip(): WARNING: "sound/doors/doorstop1.wav" not packed!
[W] packlist.pack_into_zip(): WARNING: "materials/models/props/box_dropper_tube_exponent.vtf" not packed!
[I] packlist.pack_into_zip(): Compressing packfile...
[I] vrad.main(): Packed files:
 | materials/bee2/models/props_p1/lab_shelf.vtf
 | models/bee2/props_p1/laser_catcher.vvd
 | materials/bee2/models/props_ingame/p1_lfield/p1_lfield.vtf
 | models/bee2/props_p1/hmw_laser_cube.mdl
 | scripts/vscripts/inject/inject_3f820abd.nut
 | materials/bee2/models/props_p1/cust_lfield.vtf
 | models/bee2/props_p1/laser_catcher.dx90.vtx
 | materials/bee2/models/props_p1/turret/turret_bounce.vmt
 | materials/bee2/fizz/fourthreaper/matter_inquisition_field.vmt
 | materials/bee2/models/p1_pgun/v_portalgun_exponent.vtf
 | scripts/colorcorrection/cc_testchamber.raw
 | materials/models/props/autoportal_frame/autoportal_frame.vmt
 | materials/bee2/ind_p1/straight_floor.vmt
 | models/bee2/props_p1/floor_button.mdl
 | models/bee2/props_ingame/sign_frame_1_wback.dx90.vtx
 | models/bee2/props_ingame/faith_plate_toggle.mdl
 | models/bee2/props_p1/obs_light.dx90.vtx
 | materials/bee2/models/props_ingame/p1_lfield/p1_lfield.vmt
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_speed.vmt
 | models/bee2/props_p1/hmw_laser_cube.phy
 | models/bee2/props_p1/floor_button.phy
 | materials/bee2/models/p1_pgun/v_portalgun.vtf
 | materials/models/props/autoportal_frame/autoportal_frame.vtf
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_bounce.vmt
 | materials/bee2/p1/metalwall_bts_006a.vtf
 | models/bee2/props_p1/turret_01.mdl
 | materials/bee2/models/p1_pgun/v_portalgun_blue.vtf
 | materials/bee2/p1/concrete_modular_wall002_height-ssbump.vtf
 | models/bee2/p1_pgun.vvd
 | models/props/autoportal_frame/autoportal_frame.mdl
 | models/bee2/props_p1/obs_light.phy
 | materials/bee2/p1/concrete_modular_floor001b.vmt
 | models/bee2/props_ingame/pgun_pedestal.vvd
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_core.vmt
 | models/bee2/props_p1/lab_shelf_small.mdl
 | models/bee2/props_ingame/p1_lfield.mdl
 | models/bee2/props_p1/lab_shelf_small.dx90.vtx
 | models/bee2/props_p1/mouse.phy
 | materials/bee2/p1/obs/observation_tilefloor001a.vmt
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_n.vtf
 | materials/bee2/models/p1_pgun/v_portalgun_normal.vtf
 | materials/bee2/fizz/fourthreaper/clean_mif_left.vmt
 | materials/bee2/fizz/fourthreaper/clean_mif_right.vmt
 | materials/bee2/models/props_p1/cust_lfield.vmt
 | sound/bee2/p1/pgun/portal_exit1.wav
 | materials/bee2/ind_p1/p1_antline_floor_double.vtf
 | materials/bee2/p1/goo/goo_normal.vtf
 | materials/bee2/p1/obs/observationwall_001b.vtf
 | materials/detail/detail_concrete_02.vtf
 | materials/bee2/no_paint/signage_catapult1_world.vmt
 | models/bee2/props_p1/cust_fizzler.phy
 | scripts/game_sounds_manifest.txt
 | materials/bee2/models/props_p1/floor_button/base.vtf
 | materials/bee2/p1/concrete_modular_floor001_height-ssbump.vtf
 | materials/bee2/models/props_p1/walllight_sheet.vmt
 | materials/bee2/models/props_p1/walllight_sheet.vtf
 | models/bee2/props_p1/obs_light.mdl
 | materials/bee2/p1/goo/p1_goo.vmt
 | models/bee2/props_ingame/p1_metal_box.dx90.vtx
 | models/bee2/props_ingame/sign_frame_1_wback.phy
 | materials/bee2/p1/overlay_light_gradient.vtf
 | materials/bee2/p1/concrete_modular_floor001b_height-ssbump.vtf
 | materials/bee2/models/props_p1/kb_mouse.vtf
 | materials/bee2/models/props_p1/kb_mouse.vmt
 | scripts/vscripts/inject/inject_50688a90.nut
 | models/bee2/props_ingame/p1_lfield.dx90.vtx
 | models/bee2/props_p1/lab_shelf_small.phy
 | materials/bee2/models/props_ingame/faith_plate_rusty_glass.vmt
 | scripts/bee2/p1_prop_sounds.txt
 | materials/bee2/models/props_p1/laser_pipe_glow.vtf
 | scripts/vscripts/bee2/portal_man.nut
 | models/bee2/props_p1/laser_emitter.vvd
 | models/bee2/props_ingame/p1_ball.phy
 | models/bee2/props_ingame/pgun_pedestal.dx90.vtx
 | materials/bee2/models/props_ingame/faith_plate_rusty.vmt
 | models/bee2/props_p1/laser_catcher.phy
 | models/bee2/props_ingame/p1_metal_box.phy
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp_speed.vmt
 | models/bee2/props_p1/mouse.vvd
 | materials/bee2/models/props_p1/laser_pipe_glow.vmt
 | materials/bee2/models/props_ingame/p1_ball/sphere.vtf
 | materials/bee2/models/props_p1/floor_button/normal.vtf
 | scripts/vscripts/bee2/death_fizz.nut
 | models/bee2/props_p1/cust_fizzler.dx90.vtx
 | materials/bee2/models/props_ingame/p1_ball/sphere_bounce.vmt
 | materials/bee2/no_paint/signage_catapult2_world.vmt
 | models/bee2/props_ingame/faith_plate_toggle.dx90.vtx
 | scripts/vscripts/inject/inject_38ca0a2e.nut
 | sound/bee2/p1/btn_up.wav
 | models/bee2/props_ingame/pgun_pedestal.phy
 | materials/bee2/p1/obs/observationwall_001a.vmt
 | materials/bee2/fizz_sides/side_color_999926.vmt
 | materials/bee2/fizz_sides/side_color_ff0000.vmt
 | sound/bee2/p1/pgun/portal_enter2.wav
 | materials/bee2/ind_p1/straight_wall.vmt
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_core_speed.vmt
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box.vtf
 | sound/bee2/p1/pgun/ambient.wav
 | materials/bee2/models/props_ingame/p1_ball/sphere_speed.vmt
 | models/props/autoportal_frame/autoportal_frame.dx90.vtx
 | models/bee2/props_ingame/p1_metal_box.mdl
 | materials/bee2/pc_gls.vtf
 | models/bee2/props_p1/obs_light.vvd
 | models/bee2/props_p1/keyboard.dx90.vtx
 | models/bee2/props_p1/laser_emitter.phy
 | scripts/vscripts/inject/inject_1bcae44a.nut
 | models/bee2/props_p1/mouse.dx90.vtx
 | materials/bee2/p1/concrete_modular_ceiling001a.vtf
 | models/bee2/props_ingame/p1_lfield.phy
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube.vtf
 | materials/bee2/p1/obs/observation_tilefloor001a.vtf
 | materials/models/props/autoportal_frame/autoportal_frame_n.vtf
 | materials/bee2/models/props_p1/cust_fizz.vmt
 | materials/bee2/models/props_ingame/p1_metal_box/box_paint_blue.vtf
 | materials/bee2/models/props_p1/turret/turret_speed.vmt
 | models/bee2/props_p1/floor_button.vvd
 | models/bee2/props_p1/mouse.mdl
 | scripts/vscripts/inject/inject_116b096c.nut
 | models/bee2/props_p1/lab_shelf_small.vvd
 | materials/bee2/models/props_ingame/p1_ball/sphere.vmt
 | materials/bee2/fizz/fourthreaper/clean_mif_center.vmt
 | models/props/autoportal_frame/autoportal_frame.dx80.vtx
 | models/bee2/props_ingame/p1_lfield.vvd
 | materials/bee2/models/props_p1/cust_fizz.vtf
 | materials/bee2/p1/laserplane.vmt
 | models/bee2/props_p1/hmw_laser_cube.vvd
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp.vmt
 | materials/bee2/ind_p1/p1_antline_wall_double.vtf
 | materials/bee2/p1/concrete_modular_floor001a.vmt
 | materials/bee2/models/p1_pgun/v_portalgun_glass.vmt
 | materials/bee2/models/props_p1/kb_mouse_exp.vtf
 | materials/bee2/p1/metalwall048b_lrg.vtf
 | materials/bee2/fizz/fizz_side.vtf
 | models/bee2/props_ingame/faith_plate_toggle.vvd
 | materials/bee2/models/p1_pgun/v_portalgun.vmt
 | materials/bee2/glass_player_clip.vmt
 | models/bee2/props_p1/keyboard.mdl
 | materials/bee2/p1/orange_noglow.vmt
 | materials/bee2/models/props_p1/cust_fizz_light.vtf
 | materials/bee2/p1/turret_off_eye.vmt
 | scripts/bee2_snd/portal_sounds.txt
 | materials/bee2/p1/concrete_modular_wall002.vmt
 | models/bee2/props_p1/cust_fizzler.mdl
 | models/bee2/props_p1/laser_emitter.mdl
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box.vmt
 | models/props/autoportal_frame/autoportal_frame.phy
 | sound/bee2/p1/pgun/portal_enter1.wav
 | models/bee2/props_p1/cust_fizzler.vvd
 | scripts/vscripts/inject/inject_5532f8e0.nut
 | materials/bee2/models/p1_pgun/v_portalgun_glass.vtf
 | materials/bee2/p1/obs/metaldoor028a.vmt
 | materials/bee2/models/props_ingame/faith_plate_rusty_error.vmt
 | materials/bee2/models/props_p1/lab_shelf.vmt
 | materials/bee2/models/props_ingame/p1_metal_box/box_paint_orange.vtf
 | models/bee2/props_p1/keyboard.phy
 | materials/bee2/models/props_p1/cust_fizz_light.vmt
 | materials/bee2/p1/concrete_modular_floor001b.vtf
 | models/bee2/props_ingame/sign_frame_1_wback.vvd
 | materials/bee2/models/props_p1/floor_button/exponent.vtf
 | materials/bee2/ind_p1/corner_floor.vmt
 | models/props/autoportal_frame/autoportal_frame.vvd
 | scripts/vscripts/inject/inject_72601b09.nut
 | scripts/bee2/p1_physics_sounds.txt
 | materials/bee2/p1/obs/observationwall_001b_height-ssbump.vtf
 | models/bee2/p1_pgun.mdl
 | materials/bee2/p1/concrete_modular_ceiling001a.vmt
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube.vmt
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_exponent.vtf
 | materials/bee2/p1/light_recessedcool_glow.vmt
 | scripts/bee2/p1_pgun_sounds.txt
 | models/bee2/props_p1/hmw_laser_cube.dx90.vtx
 | models/bee2/p1_pgun.dx90.vtx
 | models/bee2/props_ingame/sign_frame_1_wback.mdl
 | models/bee2/props_ingame/p1_ball.mdl
 | models/bee2/props_ingame/p1_ball.dx90.vtx
 | sound/bee2/p1/pgun/portal_exit2.wav
 | materials/bee2/p1/metalwall_bts_006a_normal.vtf
 | materials/bee2/glass_shatter.vtf
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_bounce.vmt
 | materials/bee2/p1/metalwall048b_med.vmt
 | materials/bee2/ind_p1/corner_wall.vmt
 | materials/bee2/p1/metalwall048b_lrg_height-ssbump.vtf
 | materials/bee2/p1/goo/toxic_rep_flowmapr.vtf
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_illum.vtf
 | materials/bee2/models/p1_pgun/v_portalgun_orange.vmt
 | materials/bee2/p1/obs/observationwall_001b.vmt
 | models/bee2/props_ingame/p1_metal_box.vvd
 | materials/bee2/p1/concrete_modular_wall002.vtf
 | models/bee2/props_ingame/pgun_pedestal.mdl
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_speed.vmt
 | sound/bee2/p1/btn_down.wav
 | materials/bee2/p1/concrete_modular_floor001a.vtf
 | materials/models/props/autoportal_frame/autoportal_frame_exp.vtf
 | models/bee2/props_p1/laser_catcher.mdl
 | materials/bee2/no_paint/signage_arrow_world.vmt
 | materials/bee2/p1/obs/observationwall_001a.vtf
 | materials/bee2/p1/modular_wall_light.vmt
 | materials/bee2/p1/obs/metaldoor028a.vtf
 | materials/bee2/p1/obs/detail_concrete_03.vtf
 | materials/bee2/p1/metalwall048b_med_height-ssbump.vtf
 | models/bee2/props_p1/keyboard.vvd
 | materials/bee2/nodraw_glass.vmt
 | materials/bee2/models/p1_pgun/v_portalgun_blue.vmt
 | sound/bee2/p1/wall_move5.wav
 | materials/bee2/models/p1_pgun/v_portalgun_orange.vtf
 | models/bee2/props_p1/floor_button.dx90.vtx
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_normal.vtf
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp.vtf
 | materials/bee2/p1/goo/beneath.vmt
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_core_bounce.vmt
 | materials/bee2/models/props_ingame/p1_metal_box/metal_box_comp_bounce.vmt
 | sound/bee2/p1/garage_stop1.wav
 | materials/bee2/p1/metalwall048b_lrg.vmt
 | scripts/bee2_generated_music.txt
 | models/bee2/props_p1/turret_01.phy
 | materials/bee2/p1/metalwall048b_med.vtf
 | materials/bee2/models/props_p1/hmw_laser_cube/laser_cube_glass.vmt
 | scripts/vscripts/inject/inject_65dab757.nut
 | models/bee2/props_ingame/p1_ball.vvd
 | materials/bee2/models/props_p1/kb_mouse_n.vtf
 | models/bee2/props_p1/laser_emitter.dx90.vtx
 | materials/bee2/p1/goo/p1_goo.vtf
 | materials/bee2/models/props_p1/floor_button/p1_button.vmt
 | materials/bee2/p1/metalwall_bts_006a.vmt
 | sound/bee2/p1/doorstop1.wav
 |___

[I] vrad.dump_files(): Dumping packed files to "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\maps"...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 16, in <module>
  File "vrad.py", line 291, in main
  File "vrad.py", line 62, in dump_files
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\portal2\\maps\\e3-fplate.bsp'
[6392] Failed to execute script compiler_launch

**Comment by supersean08-pro** [comment]
oh i cant access the e3-fplate mod, ima turn it off

**Comment by supersean08-pro** [comment]
i removed them and now it just crashes, and no console errors because I cant access it on loading

**Comment by Konclan** [comment]
Might be a problem with antivirus blocking or removing vbsp/vrad

**Comment by BLUcat5995** [comment]
I'll try to do something about that.

**Comment by BLUcat5995** [comment]
Alright so I forgot all about this, then I allowed vrad.exe through the firewall and it still doesn't work.

**Comment by Konclan** [comment]
@supersean08-pro Don't post your issues in other issues, if they're related then it would be a duplicate issue.

**Comment by Konclan** [comment]
@BLUcat5995 Sorry I misread this issue. Do you still have this problem when using BEEmod, can you post your Portal 2 console error after building the map.

**Comment by BLUcat5995** [comment]
That's what I posted

**Comment by BLUcat5995** [comment]
I posted the console after building the map

**Comment by Konclan** [comment]
Yes can you try re-exporting and see if you still have the same issue

**Comment by BLUcat5995** [comment]
==== calling mapspawn.nut
Connection to Steam servers successful.
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198210253855\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 33 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 6003 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 6147 (ms)

VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.main(): Loading Settings...
[I] vrad.main(): Config Loaded!
[I] vrad.main(): Reading BSP
[I] vrad.main(): Final status: is_peti=True, edit_args=False
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 16, in <module>
  File "vrad.py", line 208, in main
  File "srctools\filesys.py", line 107, in open_ref
  File "srctools\filesys.py", line 332, in _create_ref
  File "srctools\filesys.py", line 107, in open_ref
  File "srctools\filesys.py", line 633, in _create_ref
  File "srctools\vpk.py", line 288, in __init__
  File "srctools\vpk.py", line 392, in load_dirfile
MemoryError
[100] Failed to execute script compiler_launch

**Comment by TeamSpen210** [comment]
The code is running into an out-of-memory error trying to read in the VPKs in your game folder. Do you have any addons which override stuff? Do they have big VPK files?

**Comment by BLUcat5995** [comment]
I have two vpk files that replace the entire soundtrack. So I'm gonna remove them and see if it works.

**Comment by BLUcat5995** [comment]
And now it works.

**Comment by BLUcat5995** [comment]
I'll just split the vpk files.

**Comment by BLUcat5995** [comment]
It's not working. I'll just remove the vpk files.

**Comment by TeamSpen210** [comment]
That'd do it. You should use a multi-chunk VPK file for that amount of data, with everything in the numbered files not the `_dir` one.

**Comment by TeamSpen210** [comment]
I'm not sure this is an issue BEEmod can really solve, I'm not sure why Portal 2 isn't also failing here. Maybe it doesn't load the whole directory file into memory?

**Comment by BLUcat5995** [comment]
idk but where could I get a multi-chunk vpk file?

**Comment by supersean08-pro** [comment]
portal 2 crashes when beemod is in use, but when its not, its perfectly fine and doesn't crash

**Comment by LautaroL20** [comment]
> BLUcat5995 said: "I have two vpk files that replace the entire soundtrack. So I'm gonna remove them and see if it works."

Then the cause of your issue is that you were using other mods in P2 that might have interfering with the BEE2 functionality, so this is not really the BEE2´s fault then. If you want to enjoy BEE2 without issues, I´d recommend you to remove other mods that interferes with it.
