### ISSUE TITLE
dirty doors for overgrown

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1466]
https://gamebanana.com/skins/184574

**Comment by LautaroL20** [comment]
Absolutely nice! I would really like to see this implemented in Beemod.

However, you have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
