### ISSUE TITLE
Beemod with Aperture Tag doesn't work

### ISSUE THREAD

**Issue by zooz8882** [BEEmod/BEE2.4#1468]
I added Beemod to Aperture Tag, exported a palette and made a small test.  When I went to build the map, it got stuck at building geometry.  Help fixing this would be appreciated.  I attached a picture of the console if that's any help.
![image](https://user-images.githubusercontent.com/52897089/106054557-325be980-60ba-11eb-965d-de9b7fba8fc9.png)

**Comment by TeamSpen210** [comment]
That just says that you cancelled the compile.

**Comment by zooz8882** [comment]
I cancelled it because it gets stuck at "Building Geometry".  It doesn't progress past that.

**Comment by FrozenDragon0** [comment]
Try replacing the Aperture tag's beemod compilers with the Portal 2 beemod compilers. I've had a similar issue and replacing the compilers fixed it.

**Comment by zooz8882** [comment]
> Try replacing the Aperture tag's beemod compilers with the Portal 2 beemod compilers. I've had a similar issue and replacing the compilers fixed it.

How do you replace compilers?

**Comment by FrozenDragon0** [comment]
Go into both game's bin folders and replace Aperture tag's VRAD and VBSP with Portal 2's.

**Comment by zooz8882** [comment]
> Go into both game's bin folders and replace Aperture tag's VRAD and VBSP with Portal 2's.

Just to clarify, the .exe files?  The ones selected?
![image](https://user-images.githubusercontent.com/52897089/106070621-cafe6380-60d2-11eb-8277-c04fbc0ae83a.png)

**Comment by FrozenDragon0** [comment]
Yes. Replace those ones with portal 2's ones.

**Comment by zooz8882** [comment]
It didn't work. It still gets stuck at "Building Geometry"

**Comment by FrozenDragon0** [comment]
Hmmmm not sure then. Try verifying the game files then reinstalling beemod for tag.

**Comment by zooz8882** [comment]
It didn't work.  Also now for some reason when I close ApTag, it doesn't really close and infinitely generates new instances of VBSP that run in the background.  I give up.  Thanks for helping though!

**Comment by FrozenDragon0** [comment]
Oh that issue. I've had the same thing. Not sure why it didn't work though.

**Comment by Luke18033** [comment]
See #1531

**Comment by aaronyoungtn-lgtm** [comment]
> I cancelled it because it gets stuck at "Building Geometry". It doesn't progress past that.

it wont even load aperture tag for me
