### ISSUE TITLE
reconstructing style and style mix

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2.4#1469]
This would be a style that mixes overgrown and clean style or if the devs want to really get into things maybe make it so you can select 2 styles and mix them but anyway the overgrown clean style would be similar to this test chamber https://steamcommunity.com/sharedfiles/filedetails/?id=2007881260
I know it wouldn't make sense but I think it would be cool to style mix

**Comment by Electricianfromhell** [comment]
that is the reconstructing style

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
