### ISSUE TITLE
BP cube thing

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1471]
Map
https://www.mediafire.com/file/o0fmg0exrla4x95/BP_gdhjfshhcdtsvh.zip/file

amazing huh how its easy from someone who moderately use hammer

**Comment by seagemgames** [comment]
what..?

**Comment by supersean08-pro** [comment]
have you heard of bp blue portals portal mod

**Comment by seagemgames** [comment]
yes, but what does this have to do with the beemod application?

**Comment by supersean08-pro** [comment]
they are doing a BP style

**Comment by supersean08-pro** [comment]
https://github.com/BEEmod/BEE2-items/issues/2139

**Comment by seagemgames** [comment]
If you want to help with changes, you should fork the items repo. This is also posted in the wrong repo.

**Comment by supersean08-pro** [comment]
okay

**Comment by supersean08-pro** [comment]
i dont know how to

**Comment by LautaroL20** [comment]
Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

**Comment by supersean08-pro** [comment]
> Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

wait so do i make the same one in there or not

**Comment by LautaroL20** [comment]
> supersean08-pro said: "wait so do i make the same one in there or not"

If the item you are suggesting is already mentioned in the list from issue #2139, then no.

**Comment by supersean08-pro** [comment]
okay

**Comment by EllingtonElectrician** [comment]
IT'S A VIRUS!!!!

**Comment by supersean08-pro** [comment]
i use media fire and only put raw portal 2 files in so i think i will need to remove them

**Comment by supersean08-pro** [comment]
fixed
