### ISSUE TITLE
Generate tideline overlays

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2.4#1472]
Add a style var to add the dirt texture to the walls around the top of goo pits like what you see circled in the image which was taken right from the level code named column blocker in game where glados tells you about a surprise where confetti comes out of the pipe in the bts area at the start and she tells you that your adopted.

![20210201235449_1](https://user-images.githubusercontent.com/11165643/106554393-41430180-64e9-11eb-9d2a-9908492bf4a5.jpg)

**Comment by LautaroL20** [comment]
Good idea, that detail looks really fine and would make the goo to have more sense because having clean tiles on a pit alongsode a toxic water does not fit well.

**Comment by EllingtonElectrician** [comment]
> Seems to fit an ItemVar more, also, **I was thinking about goo heights, such as having it only take half the height of the voxel, or 1/4.**

This was also something i was thinking of adding is style options to set the goo height to 1/4, 1/2, and 3/4 of a voxel.
