### ISSUE TITLE
make atlas and p body explode on death in single player, can it be done?

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2.4#1473]
is this even possible?
 
 make atlas and p body when chosen as the player model explode in single player and respawn from a vactube in single player if they die like they do when they die in multiplayer.
 
 i would imagine this would be pretty complex to pull off.

**Comment by FrozenDragon0** [comment]
I do not think this is possible due to the way Single player deaths work.

**Comment by Luke18033** [comment]
It's not possible to change how death works in each mode, but this could still be implemented - by not actually killing the player, but instead just teleporting them back to a spawn point. I still don't really see it happening though, it'd require modifying lots of different items to add support.
