### ISSUE TITLE
Does not start BEEMOD 4.38.1(although a week ago everything was fine)

### ISSUE THREAD

**Issue by Mitia514** [BEEmod/BEE2.4#1475]
![би мод ошибка запуска2021-02-04_101433](https://user-images.githubusercontent.com/37024972/107005043-35cd3000-67a0-11eb-9052-79db4822d533.jpg)
![2021-02-05_112009](https://user-images.githubusercontent.com/37024972/107007890-2e0f8a80-67a4-11eb-9b1d-4aea75332542.jpg)

**Comment by Mitia514** [comment]
I have checked game files and reinstalled the mod, nothing helps.Then I figured out which other assemblies work and which don't
which versions work

25,3 ok

29 ok

30 ok

31 ok

32,0 no

33,1 no

34,1 no

36,1 no

38,1 no

**Comment by Mitia514** [comment]
I hope you'll give me a hand

**Comment by TeamSpen210** [comment]
It looks like you have a corrupt config file. Go to `%appdata%/BEEmod/`, and delete `compile.cfg`.

**Comment by Mitia514** [comment]
AppData\Roaming\BEEMOD2\config\compile.cfg 
I deleted this file and it worked, you are the savior)

**Comment by Mitia514** [comment]
Tell me, why can't I listen to songs in bee fashion? Will this be fixed?

**Comment by Konclan** [comment]
Music preview is not available in the latest versions, is planned to be re-added

**Comment by Mitia514** [comment]
I understand) thanks everyone for the help)
