### ISSUE TITLE
bee2 Error Help Pls

### ISSUE THREAD

**Issue by DiMpary** [BEEmod/BEE2.4#1478]
Hi, I recently ran into this problem: When I run bee2, it gives an error (as in the screenshot). I do not know what the problem is, this has never happened before. The packages are installed correctly and I play on the licensed version via Steam. Thank you in advance for your help.
![285628591_e465fe40487344f6dda475c364a35d86](https://user-images.githubusercontent.com/78292990/107151406-fca9e100-6994-11eb-9db6-6a5974fedd2d.jpg)

![285628591_bafd8764cf4b70969b0c69bffe5c3748](https://user-images.githubusercontent.com/78292990/107151407-fddb0e00-6994-11eb-8cb8-7e1b431760b9.jpg)

**Comment by supersean08-pro** [comment]
windows 7 miss that, had a virus and learned it the hard way, typical 11 year old me

**Comment by DiMpary** [comment]
What do you mean?

**Comment by Luke18033** [comment]
That person posts mostly nonsensical comments, you should probably just ignore them...

**Comment by LautaroL20** [comment]
You are a Windows 7 user as me, and by the time you open this issue, BEE2 missed the compatibility with Win 7 but was then restored in the latest BEE2 release. So, I´d recommend you to get the latest application and packages version of the mod with which this crash problem shouldn't happen to you anymore.
