### ISSUE TITLE
I Cant Uninstall

### ISSUE THREAD

**Issue by TCB333** [BEEmod/BEE2.4#1480]
Please Tell Me How To Uninstall Beemod

**Comment by LautaroL20** [comment]
Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears. Wait 1 minute while BEEmod resources are removed from Portal 2. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

After that, you just delete the folder where you have unzipped the BEEmod application & packages.
