### ISSUE TITLE
Randomly generated textures are inconsistent between builds

### ISSUE THREAD

**Issue by warmCabin** [BEEmod/BEE2.4#1482]
The random textures used to be consistent given the dimensions of the map, so you would get a consistent look that could be customized by placing hidden voxels. Now, you get a new arrangement every time you compile. This wouldn't be so bad if you could preview what you get before you publish, but you can't.

The current workarounds are:
- Intercept the upload with your preferred BSP before the final confirmation
- Publish. Subscribe. Play. Delete. Republish.

I'd like to suggest a "lock texture seed" button or something in the app.

Maybe someone as picky as me just needs to use Hammer, idk. But sometimes there's one grimy tile where it just doesn't make sense!

**Comment by TeamSpen210** [comment]
This should do that already, it not doing so is a bug.

**Comment by warmCabin** [comment]
Cool! I updated title to reflect that it's a bug.
