### ISSUE TITLE
movable glass

### ISSUE THREAD

**Issue by MarcusKubis9** [BEEmod/BEE2.4#1484]
this glass could be connected to anything that has an output and it acts like normals glass you can resize it change where is it hell even make it grating and then when your done fire up the level and if you put it on the floor I would move down into the floor same with roof and walls and also maybe it can move between 2 areas, of course, this would take up space under it depending on how big it is a and also maybe a setting that moves it between 2 areas? maybe?

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
