### ISSUE TITLE
compale issue

### ISSUE THREAD

**Issue by moonlord335** [BEEmod/BEE2.4#1485]
i'm heving a  issue with the compaleing here is my log 
[log.txt](https://github.com/BEEmod/BEE2.4/files/5983634/log.txt)

**Comment by moonlord335** [comment]
this is a fresh install

**Comment by seagemgames** [comment]
Vactubes are broken in 4.38.1. If you'd like to use them, downgrade to 4.36.1

**Comment by moonlord335** [comment]
oh
