### ISSUE TITLE
Compile Failure with Large Glass Hole

### ISSUE THREAD

**Issue by TacticalMeme** [BEEmod/BEE2.4#1486]
Greetings! For some reason, I can not build any puzzle when I use _BEE2_. I've tried everything I could think of. I don't know what else to do, I would really appreciate any help. x)
I will say, I could build the puzzles at one point, then for some reason it stopped working and I no longer could.

**Comment by LautaroL20** [comment]
Could you post the P2´s console log? Because that message of "there was an error building the puzzle" is way too generic and useless. Once you get the building error, copy & paste here what the game´s console says.

**Comment by TacticalMeme** [comment]
Lautaro, which part would you like? There's a lot of red and other things.

**Comment by TacticalMeme** [comment]
VBSP failed.

[I] vbsp.main(): BEE2 v4.38.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "F:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "F:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (1 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting Coop Exit to 1
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (323 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.FLOOR.BLACK: 44 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.WHITE: 38 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.BLACK: 38 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.WHITE: 79 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 79 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.FLOOR.BLACK: 44 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.CEILING.BLACK: 38 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.WHITE: 79 Clumps for 1136 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.BLACK: 79 Clumps for 1136 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] barriers.test_hole_spot(): No center barrier at 960 3008 448, -1 0 -0
[W] barriers.test_hole_spot(): No center barrier at 704 3008 448, 1 -0 -0
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[I] vbsp.set_elev_videos(): Elevator type: RAND
[W] cond.positioning.flag_brush_at_loc(): Using type=same in posIsSolid is deprecated, put this in mode!
[I] voice_line.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] voice_line.add_voice(): Quote events: []
[I] voice_line.add_voice(): 0 Mid quotes
[I] voice_line.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): ---------------------
[I] cond.core.check_all(): Conditions executed!
[I] cond.core.check_all(): Map has attributes: ['glass', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'pedestalbutton', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=41662, misses=349, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] music.add(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1939, in main
  File "precomp\barriers.py", line 275, in make_barriers
AttributeError: 'srctools._math.Angle' object has no attribute 'z'
[7620] Failed to execute script compiler_launch


An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!

**Comment by TacticalMeme** [comment]
Should I get rid of that item?

**Comment by TeamSpen210** [comment]
It's the cause yes.
