### ISSUE TITLE
Lifeform sensor causes compile error

### ISSUE THREAD

**Issue by 0xxi** [BEEmod/BEE2.4#1489]
The presence of the Lifeform sensor anywhere in the map, no matter if there is a fizzler output relay, makes the map unable to compile

> VBSP failed.
> 
> [I] vbsp.main(): BEE2 v4.38.1 VBSP hook initiallised.
> [I] cond.core.import_conditions(): Imported all conditions modules!
> [I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [I] vbsp.main(): PeTI map detected!
> [I] vbsp.main(): Loading settings...
> [W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
> [W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
> [W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/'}
> [I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
> [I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
> [I] fizzler.read_configs(): Loaded 14 fizzlers.
> [I] vbsp.load_settings(): Settings Loaded!
> [I] vbsp.load_map(): Parsing Map...
> [I] vbsp.load_map(): Reading Map...
> [I] vbsp.load_map(): Loading complete!
> [I] antlines.parse_antlines(): Parsing antlines...
> [I] antlines.parse_antlines(): Done! (1 antlines)
> [E] (unknown file).(unknown function)(): Uncaught Exception:
> Traceback (most recent call last):
>   File "precomp\connections.py", line 909, in calc_connections
> KeyError: 'pro_lfs5_modelStart5'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "compiler_launch.py", line 13, in <module>
>   File "vbsp.py", line 1907, in main
>   File "precomp\connections.py", line 911, in calc_connections
> ValueError: "pro_lfs5_modelStart5" is not a known instance!
> [20988] Failed to execute script compiler_launch

The error also occurs in version 4.37.0

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
