### ISSUE TITLE
Portal 2 has received a update after a full decade

### ISSUE THREAD

**Issue by EllingtonElectrician** [BEEmod/BEE2.4#1490]
Just a heads up Portal 2 has just received a major update after a full decade which changes some stuff in the puzzle maker

here is a link to the details

[update link](https://game-updates.info/portal2?52)

**Comment by Luke18033** [comment]
Yes, we're well aware of this already. This isn't a discussion forum, please don't open an issue unless you actually have a bug report or feature request.
