### ISSUE TITLE
Fields compile error

### ISSUE THREAD

**Issue by Lolbinhos** [BEEmod/BEE2.4#1491]
I can't compile chambers with any of the modded fields.

I'm making a chamber with Matter Inquisition Field and the Closed Solid Field
And I cant' compile them. I tried to compile other chambers with only these modded Fields and It just won't work.
![Screenshot_1](https://user-images.githubusercontent.com/79300011/108559864-aca71480-72da-11eb-99e0-4dd21b2f7821.png)

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.

**Comment by Lolbinhos** [comment]
> You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues
> 
> The section where you have posted is for things related to the Bee´s user interface, only.

Oh I'm sorry

**Comment by FrozenDragon0** [comment]
Duplicate of this: https://github.com/BEEmod/BEE2-items/issues/3641
