### ISSUE TITLE
BEE2_4.39.0 Launch problem

### ISSUE THREAD

**Issue by THS2121966** [BEEmod/BEE2.4#1496]
![BEE2_4 39 0_problem](https://user-images.githubusercontent.com/56027883/108616301-cb262080-743e-11eb-9f23-c64bc63d9426.PNG)

**Comment by ENDERZOMBI102** [comment]
translation please?

**Comment by TeamSpen210** [comment]
I've seen this error, I need to figure out what file causes it.

**Comment by THS2121966** [comment]
The byte stream type of the given url is not supported

**Comment by THS2121966** [comment]
I translated it from google translate.) Sorry if this for you means nothing. This problem is starting if i simple launch program.

**Comment by THS2121966** [comment]
If I trying launch program with win 8 Compatibility Mode:
![Снимок](https://user-images.githubusercontent.com/56027883/108681362-a5be1300-7521-11eb-86af-1c7dba293dbd.PNG)

**Comment by THS2121966** [comment]
In 4.39.1 Problem is still alive:
![123](https://user-images.githubusercontent.com/56027883/109409552-4ac76880-79c6-11eb-8875-a65ce4bfd803.PNG)

**Comment by LolekLiam** [comment]
Logs:
[I] sound.ticker(): Loading sound "swap" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\extrude.ogg
[D] BEE2.<module>(): Loading settings...
[I] gameMan.scan_music_locs(): Ap-Tag dir: c:\program files (x86)\steam\steamapps\common\aperture tag/aperturetag/sound/music
[I] BEE2.<module>(): Loading Packages...
[I] sound.ticker(): Loading sound "move" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\reconfig.ogg
[I] sound.ticker(): Loading sound "lower_3" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\panel_lower_03.ogg
[I] sound.ticker(): Loading sound "lower_2" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\panel_lower_02.ogg
[I] sound.ticker(): Loading sound "lower_1" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\panel_lower_01.ogg
[I] sound.ticker(): Loading sound "raise_3" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\panel_raise_03.ogg
[I] sound.ticker(): Loading sound "raise_2" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\panel_raise_02.ogg
[I] sound.ticker(): Loading sound "raise_1" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\panel_raise_01.ogg
[I] sound.ticker(): Loading sound "contract" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\carve.ogg
[I] sound.ticker(): Loading sound "error" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\error.ogg
[I] sound.ticker(): Loading sound "delete" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\collapse.ogg
[I] sound.ticker(): Loading sound "expand" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\extrude.ogg
[I] sound.ticker(): Loading sound "disconnect" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\connection_destroyed.ogg
[I] sound.ticker(): Loading sound "connect" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\connection_made.ogg
[I] sound.ticker(): Loading sound "subtract" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\decrement.ogg
[I] sound.ticker(): Loading sound "config" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\reconfig.ogg
[I] sound.ticker(): Loading sound "add" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\increment.ogg
[I] sound.ticker(): Loading sound "select" -> C:\Users\Liam\Desktop\Liam\BEE2 4P2\sounds\rollover.ogg

**Comment by THS2121966** [comment]
In newest 4.40.1 version all works.
