### ISSUE TITLE
Beemod Version 4.39.0 not working for all the Windows 7 users, it will crash on launch.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1497]
It seems that the Python 39 version is not compatible with Windows 7. The Beemod version 4.38 was using Python 36 which was Windows 7 compatible and for some reason, Beemod was switched directly from 36 to 39. 

![Beemod PRL39 launch error](https://user-images.githubusercontent.com/12244376/108623495-24ca2300-741e-11eb-8307-5b279194f50b.png)

Is there any plans on adding Windows 7 compatibility for Beemod in some way or all the Win 7 users will need to install Windows 10 to keep using it from now?

**Comment by LautaroL20** [comment]
I think that we will have to keep using version 38 for some time.

**Comment by FrozenDragon0** [comment]
Either that or upgrade to windows 10. Only two options unfortunately.

**Comment by LautaroL20** [comment]
Yep, RIP Beemod for Windows 7: 2016-2021.

**Comment by Luke18033** [comment]
Are you sure this is actually caused by Windows 7? In the past you've blamed things on that which are actually totally unrelated.

**Comment by Luke18033** [comment]
Never mind, I just checked the Python website and it says that Python 3.9+ isn't supported on Windows 7. So yeah you'll just need to stay on 4.38 or upgrade to Windows 10. Note that Windows 7 has been unsupported for just over a year now, so you probably shouldn't have been using it anyway...

**Comment by LautaroL20** [comment]
@TeamSpen210 - Did you intentionally reopened it or it was just an accident? It would be really wonderful to think that Windows 7 users still has some hope with future Beemod updates, however this may have been just a mistake.

**Comment by TeamSpen210** [comment]
Yes, I'll build it with Python 3.8 so it still works on Windows 7.

**Comment by LautaroL20** [comment]
Thank you a lot, good sir! The Windows 7 community will appreciate it a lot, i have no doubt.

**Comment by bodyakod** [comment]
I thought Its actually my РС рroblem...

**Comment by Luke18033** [comment]
This is now done

**Comment by LautaroL20** [comment]
>bodyakod said: "I thought Its actually my РС рroblem..."

The latest BEEmod version (4.40.2) works pretty well on Windows 7.

**Comment by bodyakod** [comment]
> > bodyakod said: "I thought Its actually my РС рroblem..."
> 
> The latest BEEmod version (4.40.2) works pretty well on Windows 7.

It doesnt for me...

**Comment by Luke18033** [comment]
That would be an unrelated issue.
