### ISSUE TITLE
Lines missing or outdated in BEE2.pot

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2.4#1500]
See #416 for main translations project.

Lines missing:
- ~~All stylevars except unstyled, and their descriptions~~ _untranslatable_ [(image)](https://user-images.githubusercontent.com/69758777/108631934-b791ae80-746c-11eb-83ce-7a0b5971d4c4.png)
- ~~All itemvars except "Confugure signage" button~~ _untranslatable_ [(image)](https://user-images.githubusercontent.com/69758777/108632007-06d7df00-746d-11eb-86cb-e47e1e078e11.png)
- "Search: " _(in main window)_
- Error window, f.ex. "This has been copied to clipboard"

Lines outdated (not translating):
- "Clear" *(in Logs)*

This will be updated when found new.

Also need to fix typos

**Comment by Luke18033** [comment]
The stylevars and itemvars are missing because they're defined in the packages, and I don't think are translatable.
