### ISSUE TITLE
Unable to compile at all in the latest version (pack_list.cfg not found)

### ISSUE THREAD

**Issue by 0xxi** [BEEmod/BEE2.4#1501]
I just updated BEE2 to v4.39.0 and i'm unable to compile anything even an empty test chamber

> VBSP failed.
> 
> [I] vbsp.main(): BEE2 v4.39.0 VBSP hook initiallised.
> [I] cond.core.import_conditions(): Imported all conditions modules!
> [I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [I] vbsp.main(): PeTI map detected!
> [I] vbsp.main(): Loading settings...
> [W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
> [W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
> [E] (unknown file).(unknown function)(): Uncaught Exception:
> Traceback (most recent call last):
>   File "compiler_launch.py", line 13, in <module>
>   File "vbsp.py", line 1860, in main
>   File "vbsp.py", line 158, in load_settings
> FileNotFoundError: [Errno 2] No such file or directory: 'bee2/pack_list.cfg'
> [18220] Failed to execute script compiler_launch

I'm pretty sure it's a problem with my installation but I don't know how to fix that

**Comment by SmokedSeaBass** [comment]
I have the same issue on a fresh install.  Have also tried uninstalling -> verifying integrity -> reinstalling.

**Comment by 0xxi** [comment]
I found a solution : Create an empty "pack_list.cfg" file in Portal 2/bin/bee2
