### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by pingist** [BEEmod/BEE2.4#1507]
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (2 antlines)
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: True
[I] brushLoc.read_from_map(): Analysed map, filling air... (115 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.FLOOR.BLACK: 26 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.WHITE: 30 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.BLACK: 30 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.WHITE: 56 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 56 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.FLOOR.BLACK: 26 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.CEILING.BLACK: 30 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.WHITE: 56 Clumps for 803 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.BLACK: 56 Clumps for 803 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x08623430>: <precomp.conditions.catwalks.Link object at 0x087F0808>, <srctools.vmf.Entity object at 0x08623460>: <precomp.conditions.catwalks.Link object at 0x087F0C28>, <srctools.vmf.Entity object at 0x08623490>: <precomp.conditions.catwalks.Link object at 0x087F0CE8>, <srctools.vmf.Entity object at 0x086234C0>: <precomp.conditions.catwalks.Link object at 0x087F0B88>}
[I] cond.catwalks.res_make_catwalk(): Markers: {'catw57': <srctools.vmf.Entity object at 0x08623430>, 'catw58': <srctools.vmf.Entity object at 0x08623460>, 'catw59': <srctools.vmf.Entity object at 0x08623490>, 'catw60': <srctools.vmf.Entity object at 0x086234C0>}
[I] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] instanceLocs.get_subitems(): Invalid custom instance name - "tim_start" for <item_bee2_scaffold_slot> (Valid: {'bee2_tim_start': 'instances/BEE2/clean/items/scaffold/tim_start.vmf'})
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:small" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:medium" for vactube group BEE2_VACTUBES!
[W] cond.vactubes.get_temp(): Invalid template "BEE2_VACTUBE_CORNER_CLEAN:large" for vactube group BEE2_VACTUBES!
[I] connections.gen_item_outputs(): Generating item IO...
[E] cond.core.check_all(): Error in MetaCondition "gen_item_outputs":
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 511, in check_all
  File "precomp\conditions\__init__.py", line 300, in test
  File "precomp\conditions\__init__.py", line 289, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\connections.py", line 862, in gen_item_outputs
  File "precomp\connections.py", line 1079, in add_item_inputs
AttributeError: 'tuple' object has no attribute 'input'

I don't know at all what is this mean, so guys please help.

**Comment by FrozenDragon0** [comment]
Are you using the latest version 4.39?

**Comment by pingist** [comment]
> Are you using the latest version 4.39?

yes

**Comment by FrozenDragon0** [comment]
> > Are you using the latest version 4.39?
> 
> yes

Hmmmm not sure. Then again 4.39 is giving alot of errors so I'd recommend downgrading to 4.36 temporarily.

**Comment by pingist** [comment]
> > > Are you using the latest version 4.39?
> > 
> > 
> > yes
> 
> Hmmmm not sure. Then again 4.39 is giving alot of errors so I'd recommend downgrading to 4.36 temporarily.

ok, i'll try.

**Comment by pingist** [comment]
> > > Are you using the latest version 4.39?
> > 
> > 
> > yes
> 
> Hmmmm not sure. Then again 4.39 is giving alot of errors so I'd recommend downgrading to 4.36 temporarily.

Okay, it worked, thanks.

**Comment by seagemgames** [comment]
4.36 fizzlers do not work though.
