### ISSUE TITLE
Beemod causes a "creation error".

### ISSUE THREAD

**Issue by Turrettt** [BEEmod/BEE2.4#1509]
if i create my chamber it says Creation error . what can i do? It says only creation error or german: (i am german) Erstellungsfehler

**Comment by DeliWasTaken** [comment]
This is not enough information whatsoever. Build errors can be caused my many, many things.

**Comment by LautaroL20** [comment]
@Turrettt - Please, when you are building the puzzle in Portal 2 and once you get the "creation error", then open the developer console and copy & paste the log here.

**Comment by LautaroL20** [comment]
Because open an issue about a "creation error" without having the corresponding console log, would be pretty much useless because it would be impossible to find a solution without it.

**Comment by LautaroL20** [comment]
Closing because the author does not respond and he probably never will.
