### ISSUE TITLE
BEE2_4.39.0.zip has virus

### ISSUE THREAD

**Issue by arRk-byte** [BEEmod/BEE2.4#1510]

**Comment by arRk-byte** [comment]
Wacatac B!mL

**Comment by seagemgames** [comment]
Read the [FAQ](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md). This is a false positive. If you don't trust it still, you can review the code yourself from [https://github.com/BEEmod/BEE2.4](here), and build it yourself [here](https://github.com/BEEmod/BEE2.4#building-from-source).
