### ISSUE TITLE
Can't open the application after updating.

### ISSUE THREAD

**Issue by DigitexStudios** [BEEmod/BEE2.4#1517]
I was using an older version of Bee2 (4.36.1) and it worked great.

I just downloaded the latest version (for the new items) and Google Chrome wouldn't even let me download it. It said it contained malware. So, I use Microsoft Edge to download it instead, and when I try to unzip it, Avast Antivirus immediately blocks BEE2.exe. I unblock it and add that folder to the exceptions, and when I try to run BEE2.exe, Windows Defender also thinks its a virus. So, I create an exception for Defender as well, and try to run the file...
And I get a popup box that says:

Cannot open self
C:\Users\-------\Desktop\Bee2.4New\BEE2.exe or archive
C:\Users\-------\Desktop\Bee2.4New\BEE2.pkg

If I try to run the app as an administrator, it says:

C:\Users\--------\Desktop\Bee2.4New\BEE2.exe
Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**BEE2 version:**
4.39.0

**Description of the bug:**
BEE2 is identified as a virus, and cannot be opened.

**Expected behavior:**
BEE2 opens normally

**Steps to reproduce:**
Literally just run BEE2.exe, not much else. The program is extracted to my desktop, in a folder called Bee2.4New. All packages are properly installed.

**Additional information:**

![Screenshot 2021-02-27 140143](https://user-images.githubusercontent.com/62073336/109397407-6833fe00-7904-11eb-94ba-4881dbb3fac1.png)
![Screenshot 2021-02-27 140301](https://user-images.githubusercontent.com/62073336/109397448-99143300-7904-11eb-84dd-981d225f8694.png)

**Comment by Konclan** [comment]
Read https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#my-anti-virus-program-flagged-bee24-as-malware for more info
