### ISSUE TITLE
Play sounds not working on Windows 7 and 8.1

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1520]
The crash has been solved, but now what remains to be solved is that the "play sounds" option is always disabled on Windows 7 and 8.1. The reason for the app crash that is now solved (file does not start with RIFF, and issue https://github.com/BEEmod/BEE2.4/issues/1521) was caused due that the OGG-format sound files are very problematic on Windows 7 and 8.1 systems.

**The solution for this is replacing the OGG sound files with WAVE-format sound files which still have the .ogg extension while the internal format is WAVE, this brings way better OS support for 7/8.1 and then the app not only will not gonna crash, but sounds will work fine**

![Play sounds always disabled](https://user-images.githubusercontent.com/12244376/132522385-0b3f1eef-18cf-4a43-85f1-3a4852c034d7.png)

Credit for this solution goes to @Lieutenant-L-T-Smash:
"As a workaround until this issue is fixed, replace the "sounds" folder inside the main BEE folder with the one from this archive:
https://drive.google.com/file/d/1pUYiGqulmzkM79fd63imq6tZityFDswa/view"

**Comment by LautaroL20** [comment]
Note that the 64-bit version of Beemod does not work at all in Windows 7, however the 32-bit version almost worked expect for this error that should be easy to fix?

**Comment by thefurrywolf** [comment]
im having the same error but im on windows 8.1

**Comment by Some-Username-Available** [comment]
Happens to me.

**Comment by LautaroL20** [comment]
Seeing that not only Windows 7 users but also Windows 8.1 users are experiencing this issue too, i will edit the issue´s title to make it more accurate.

**Comment by Lieutenant-L-T-Smash** [comment]
As a workaround until this issue is fixed, replace the "sounds" folder inside the main BEE folder with the one from this archive:
https://drive.google.com/file/d/1pUYiGqulmzkM79fd63imq6tZityFDswa/view

This will replace the problematic OGG-format sound files with WAVE-format sound files. (The filenames still have the extension .ogg but the internal format is WAVE, which has better OS support.)

**Comment by KaziPlays** [comment]
This issue happened on my Windows 10 64 bit computer, while using the 64-bit Beemod, Now there's more work to be done

**Comment by Unradelic** [comment]
> As a workaround until this issue is fixed, replace the "sounds" folder inside the main BEE folder with the one from this archive:
> https://drive.google.com/file/d/1pUYiGqulmzkM79fd63imq6tZityFDswa/view
> 
> This will replace the problematic OGG-format sound files with WAVE-format sound files. (The filenames still have the extension .ogg but the internal format is WAVE, which has better OS support.)

This is the only think that worked for me. Really appreciated!

**Comment by Luke18033** [comment]
Should be fixed in 4.40

**Comment by TeamSpen210** [comment]
I fixed the crash, but I don't think I fixed the underlying issue - it's still not playing properly?

**Comment by LautaroL20** [comment]
> It's still not playing properly?

It does not play at all, the checkbox option is always unclickable like this:

![Play sounds always disabled](https://user-images.githubusercontent.com/12244376/132522385-0b3f1eef-18cf-4a43-85f1-3a4852c034d7.png)

**Comment by Luke18033** [comment]
I've also had this happen randomly on Windows 10, no idea why it only breaks sometimes though...

**Comment by LautaroL20** [comment]
Probably, although it´s still a relevant bug to fix.

**Comment by TeamSpen210** [comment]
I think this is fixed, need someone on Win 7/8.1 to double-check though.

**Comment by Luke18033** [comment]
Ah right, you don't have compiling dev builds set up.

**Comment by Luke18033** [comment]
Ah, so that must be a bug with the music previews specifically then.
