### ISSUE TITLE
App Crash caused by the "standing_reclined_fizzlers" package

### ISSUE THREAD

**Issue by 0xxi** [BEEmod/BEE2.4#1523]
I got an error when i tried to run the latest version of bee2

> Traceback (most recent call last):
>   File "BEE2_launch.pyw", line 49, in <module>
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
>   File "app\BEE2.py", line 76, in <module>
>   File "packages\__init__.py", line 552, in load_packages
>   File "packages\item.py", line 493, in parse
> ValueError: Item "ITEM_LAUTARO_RECLINED_FIZZLER" has different visible subtypes in its styles: (1, 2, 3), (1, 2, 3, 4, 5)

One temporary solution i found was to remove the file "standing_reclined_fizzlers.bee_pack" from the package folder but so these fizzlers are no longer accessible

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
