### ISSUE TITLE
Compile error : Unable to open "preview.prt"

### ISSUE THREAD

**Issue by 0xxi** [BEEmod/BEE2.4#1524]
This error happened to me after uninstalling bee2 from the game, I think the uninstall must have broken something in the game files, and reinstalling BEE2 later didn't fix it.

> VVIS failed.
> 
> Valve Software - vvis.exe (Feb  9 2021)
> 8 threads
> reading d:\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
> reading d:\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
> LoadPortals: couldn't read d:\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt

I checked in the folder, and there is in fact no "preview.prt" file, it's just not created for some reason
I would like to be able to avoid uninstalling and reinstalling Portal 2 if possible

**Comment by FrozenDragon0** [comment]
You have a leak that's why it's not compiling. What items are in your map?

**Comment by seagemgames** [comment]
What style and version, too.

**Comment by 0xxi** [comment]
It's not related on items or style, because even with BEE2 uninstalled from the game, with portal 2 completely vanilla, I can't compile the default test chamber when I create a new map

That's why I think the uninstallation broke some game files

**Comment by seagemgames** [comment]
You should verify game file integrity after uninstalling.

**Comment by 0xxi** [comment]
The "verify game file integrity" solved the problem, thanks ! I didn't know this feature
