### ISSUE TITLE
Problems with permissions during compilation

### ISSUE THREAD

**Issue by Maniac0bra** [BEEmod/BEE2.4#1525]
> [I] vrad.dump_files(): Dumping packed files to "D:\Steam\steamapps\common\Portal 2\bin"...
> [E] (unknown file).(unknown function)(): Uncaught Exception:
> Traceback (most recent call last):
>   File "compiler_launch.py", line 16, in <module>
>   File "vrad.py", line 302, in main
>   File "vrad.py", line 100, in dump_files
> PermissionError: [WinError 5] Accès refusé: 'D:\\Steam\\steamapps\\common\\Portal 2\\bin\\binkw32.dll'
> [16480] Failed to execute script compiler_launch

("Accès refusé" is "Access denied" in French)

I know the error seems pretty obvious, but I have checked all the permissions of the binkw32.dll file (and the whole Portal 2 folder) and there is nothing wrong, I have even added extra permissions but it doesn't change anything. I don't have any anti-virus software and I have also disabled all windows anti-virus protection but the error is still there. Running Portal 2 as administrator doesn't change anything either.

This error is very confusing

And why this file specifically ? BEE2 has no problem accessing any other file. The error appears at the very end of the test chamber construction loading.
I'm not sure if I'll find the answer here as it seems more like a problem with my system but I've never had file permissions issues like this with other programs.

Styles and objects don't seem to change anything.

**Comment by TeamSpen210** [comment]
Do you have "dump files" enabled in the compiler pane? Seems like it's trying to just write those to bin/, making it think it has to delete everything.

**Comment by Maniac0bra** [comment]
Thank you ! That was that, i don't know why the "dump files" box was checked, I probably activated it by mistake
