### ISSUE TITLE
new beemod version has large glitches

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1528]
https://www.youtube.com/watch?v=v0jFIJuLYsg

tell me if the link doesn't show the right video so i can show pictures

Issues mentioned:
* Glitchy P1 panel editor sound
* P1 light strip variant isn't being used
* Angled panel isn't getting the correct template.

**Comment by seagemgames** [comment]
Read the [Contributing Guidelines](https://github.com/BEEmod/.github/blob/master/contributing.md). You shouldn't lump multiple issues into one as they cannot be manually labelled or tracked as easily.

**Comment by supersean08-pro** [comment]
okay

**Comment by FrozenDragon0** [comment]
Make multiple issues. Do not combine them all into one.
