### ISSUE TITLE
GLaDOS (Item Request)

### ISSUE THREAD

**Issue by lazytspo** [BEEmod/BEE2.4#1532]
**Description of the feature:**
Based on the Central AI GLaDOS.

**This should be implemented because:**
She wants you to make sure to add it to its custom chamber.

**Additional information:**

**Comment by Luke18033** [comment]
What? We're not going to add a placeable GLaDOS, that doesn't make any sense in a test chamber and BEE2 isn't for stories.

**Comment by seagemgames** [comment]
This should also be in BEE2-items
