### ISSUE TITLE
A simple test failed to build

### ISSUE THREAD

**Issue by CatGhiaccio** [BEEmod/BEE2.4#1534]
Error Code: VVIS failed.

Valve Software - vvis.exe (Feb  9 2021)
4 threads
reading e:\steamlib\steamapps\common\portal 2\sdk_content\maps\preview.bsp
reading e:\steamlib\steamapps\common\portal 2\sdk_content\maps\preview.prt
LoadPortals: couldn't read e:\steamlib\steamapps\common\portal 2\sdk_content\maps\preview.prt

Version: 4.38.0

Test chamber:
![image](https://user-images.githubusercontent.com/80010325/110212456-5ff33a00-7e93-11eb-944c-4e0a0146b1c2.png)

**Comment by LautaroL20** [comment]
When reporting a bug, first make sure you're on the latest version of the mod, as the issue may have already been fixed. You´re using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

**Comment by CatGhiaccio** [comment]
> When reporting a bug, first make sure you're on the latest version of the mod, as the issue may have already been fixed. You´re using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

I'm trying to use the Sendificator, as it does not work in 4.39.x

**Comment by LautaroL20** [comment]
Well, if you are saying that even a simple test will cause compile failures in Beemod version 4.38.0, then it would be way more reasonable for you to use the latest version where you will at least be able to compile a simple test chamber, isn´t it?
