### ISSUE TITLE
Bug with the  Weighted Storage Cube Receptacle

### ISSUE THREAD

**Issue by sasha155** [BEEmod/BEE2.4#1535]
I found Bug with the  Weighted Storage Cube Receptacle texture in style overgrown.Fix it,please
![image](https://user-images.githubusercontent.com/28487809/110255680-fd3e9300-7fa5-11eb-96a4-92da15643a3e.png)

**Comment by FrozenDragon0** [comment]
1. You've posted in the wrong section.
2. This is a duplicate of https://github.com/BEEmod/BEE2-items/issues/3645
