### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by cryingandten** [BEEmod/BEE2.4#1539]
I have Overgrown style and I make first try to compile chamber.

VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 2
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (385 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x05D62FD0>: <conditions.catwalks.Link object at 0x04BDE508>, <srctools.vmf.Entity object at 0x05D62FF0>: <conditions.catwalks.Link object at 0x04BDE788>}
[I] cond.catwalks.res_make_catwalk(): Markers: {'catw1830086': <srctools.vmf.Entity object at 0x05D62FD0>, 'catw1886747': <srctools.vmf.Entity object at 0x05D62FF0>}
[I] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 36/114 locations
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[W] cond.sendtor.res_signage(): Can't place signage at (1600 1216 192) in (0 0 -1) direction!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_MODERN_DROPPER_WRECKED" does not exist!
[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd1366473" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd1366473"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "1472 1472 576"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "1"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='1', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd3680695" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd3680695"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "704 3136 576"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "1"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='1', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: N, Orange: N
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'glass', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'cubedropper', 'cubedropperstandard', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'orangeportal', 'orangeportalspawner', 'autoportal', 'blueportal', 'blueportalspawner', 'pedestalbutton', 'spawn_nogun']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=70606, misses=389, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 114})
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'F:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Mar  2 2021)
[I] <valve>.vbsp(): 6 threads
[I] <valve>.vbsp(): Using shader api: shaderapiempty.dll
[I] <valve>.vbsp(): materialPath: F:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading F:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_white.vmf
[I] <valve>.vbsp():

**Comment by FrozenDragon0** [comment]
Remove the chamberlock that's causing your error.

**Comment by cryingandten** [comment]
Ок thanks

**Comment by LautaroL20** [comment]
If the chamberlock causes failure to compile, you should make a specific issue about that item in the item´s repro.
