### ISSUE TITLE
Portal 2 doesn't like me putting stuff that makes portals 

### ISSUE THREAD

**Issue by ZenyX64** [BEEmod/BEE2.4#1542]
Not sure how else to explain it, so sorry for the weird title. Anyway, I found an issue with the portal gun pedestal and the autoportal. While the autoportal just wouldn't activate no matter what I did, trying to build a test chamber where the portal gun pedestal started activated or was connected to something that activated it, it would just say there was an error building the chamber. Everything else seems to be working fine.

**Comment by FrozenDragon0** [comment]
1. You have posted in the wrong section.
2. The auto portal issue has already been reported
3. Do not combine multiple bugs in one issue as this makes it harder to track which bug is fixed and what bug isn't fixed.

**Comment by seagemgames** [comment]
Shouldn't this also have "Invalid" and be transferred to BEE2-items?
