### ISSUE TITLE
Arroja un error al crear una camara in portal 2

### ISSUE THREAD

**Issue by CreatorPlayer** [BEEmod/BEE2.4#1543]
После эекспортирования новой палитры в портал 2 редактор начал выдавать ошиьку при каждой компиляции камеры даже если в камере ничего нет. Вот ошибка: 
VBSP failed.

Python path configuration:
  PYTHONHOME = 'D:\SteamLibrary\steamapps\common\Portal 2\bin'
  PYTHONPATH = (not set)
  program name = 'D:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp.exe'
  isolated = 0
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = 'D:\\SteamLibrary\\steamapps\\common\\Portal 2\\bin\\vbsp.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'D:\\SteamLibrary\\steamapps\\common\\Portal 2\\bin\\vbsp.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'D:\\SteamLibrary\\steamapps\\common\\Portal 2\\bin\\base_library.zip',
    'D:\\SteamLibrary\\steamapps\\common\\Portal 2\\bin',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00004534 (most recent call first):
<no Python frame>

**Comment by CreatorPlayer** [comment]
> Después de exportar la nueva paleta al portal 2, el Editor comenzó a emitir un error en cada compilación de la cámara, incluso si no hay nada en la cámara. Aquí está el error:
> VBSP failed.
> 
> Python path configuration:
> PYTHONHOME = 'D:\SteamLibrary\steamapps\common\Portal 2\bin'
> PYTHONPATH = (not set)
> program name = 'D:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp.exe'
> isolated = 0
> environment = 0
> user site = 0
> import site = 0
> sys._base_executable = 'D:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp.exe'
> sys.base_prefix = ''
> sys.base_exec_prefix = ''
> sys.platlibdir = 'lib'
> sys.executable = 'D:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp.exe'
> sys.prefix = ''
> sys.exec_prefix = ''
> sys.path = [
> 'D:\SteamLibrary\steamapps\common\Portal 2\bin\base_library.zip',
> 'D:\SteamLibrary\steamapps\common\Portal 2\bin',
> ]
> Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
> Python runtime state: core initialized
> ModuleNotFoundError: No module named 'encodings'
> 
> Current thread 0x00004534 (most recent call first):

**Comment by LautaroL20** [comment]
WAT.

**Comment by Luke18033** [comment]
I guess we're going to need a "open issues in Engish" rule now.
