### ISSUE TITLE
When it gets to "initialising ui"

### ISSUE THREAD

**Issue by LugiNess** [BEEmod/BEE2.4#1544]
**BEE2 Version:**

<details>
<summary>Error Log</summary>

</details>

**Additional information:**
![errorreport](https://user-images.githubusercontent.com/81454232/112708202-f9e44c00-8e6d-11eb-8e1b-788fa40bf7a7.png)

**Comment by FrozenDragon0** [comment]
Ehmm there's no log?

**Comment by LautaroL20** [comment]
The following error: "End of text reached with remaining open sections.", can only mean two possible things: You may have been editing/modding an item package and you just missed adding some closing brackets to the text file configuration of the package. The other possible scenario could be that you are using outdated packages on a newer version of the Beemod interace, if so, please make sure that you are using the latest packages version + latest Beemod user interace.

**Comment by LugiNess** [comment]
I reinstalled it and it worked, thanks

**Comment by LautaroL20** [comment]
No problem.
