### ISSUE TITLE
hi im having and build error when using BTS style with nothing in the level and or something in it please help

### ISSUE THREAD

**Issue by ismellpie3** [BEEmod/BEE2.4#1545]
**BEE2 Version:**

<details>
<summary>Error Log</summary>

</details>

**Additional information:**

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
