### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by JoyOfOi** [BEEmod/BEE2.4#1549]
When i try to export a palate it gives me the following error in the compile log I am using version 4.39.2

[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\compile.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\item_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\games.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\config.cfg" not found! Using defaults...

**Comment by TeamSpen210** [comment]
Those aren't errors, they just mean you ran the app for the first time and it's generating blank configs.

**Comment by JoyOfOi** [comment]
Sorry for the late response I checked \AppData\Roaming\BEEMOD2\config\ to make sure I wasnt missing anything and I appear to be missing packages.cfg

**Comment by TeamSpen210** [comment]
That's not an issue, if you've never turned any off it won't need to save. What's the actual error you're getting when exporting?

**Comment by JoyOfOi** [comment]
[WARNING] BEE2_config.load(): Config "C:\Users\---\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Using defaults...

**Comment by TeamSpen210** [comment]
That's not an error, as I said. What's not working?

**Comment by LautaroL20** [comment]
Closing because the issue's author doesn't respond.
