### ISSUE TITLE
The anti-expropriation field in BeeMOD 4.38.1 at the end of the work in the editor puzzles in the port, an assembly error appears

### ISSUE THREAD

**Issue by ZelzaM** [BEEmod/BEE2.4#1550]
Hi, I got such a problem that _after expropriation_ after the end of the work, there was a build error. **How can I fix this error?**

**Comment by FrozenDragon0** [comment]
Tell us what the console says, that'll give an an error whenever a problem occurs.

**Comment by pingist** [comment]
> Tell us what the console says, that'll give an an error whenever a problem occurs. Also what is a anti-expropriation field??

basic fizzler

**Comment by LautaroL20** [comment]
Not sure what was the issue here due that the english level of the issue´s author is worst than mine... if this was about fizzlers, they works pretty well in the latest BEEmod release, so this issue no longer happens.
