### ISSUE TITLE
Error building chamber

### ISSUE THREAD

**Issue by Portaluser-max** [BEEmod/BEE2.4#1551]
BEEMOD 4.38.1

<details>
<summary>Error Log</summary>
VBSP failed.

Valve Software - vbsp.exe (Mar  2 2021)
2 threads
Using shader api: shaderapiempty.dll
materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/elevator_sp/door_frame_black.vmf

</details>

Was using original clean style

**Comment by LautaroL20** [comment]
> Portaluser-max said: "BEEMOD 4.38.1"

Remember that we do not support older Beemod versions. If you want your issue to stay open so it later can be fixed, the bug report must always be taken from the latest Beemod version.
