### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by mateibec** [BEEmod/BEE2.4#1554]
It doesn't launch, it says:
(https://user-images.githubusercontent.com/81866547/113481815-75647f80-94a4-11eb-8493-12efd016e9f6.png)

**Comment by AeroGas** [comment]
Hey mateibec,
I have the same problem.
I fixed it by reinstalling bee2 and going to %appdata%, BEEMOD2, and delete everything in here.
WARNING: you will loose all your configuration.
Tell me if this fixed your problem.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521
