### ISSUE TITLE
hello on the 1980s aperture with the recommended setting this is what my level looks like 

### ISSUE THREAD

**Issue by ismellpie3** [BEEmod/BEE2.4#1556]
**BEE2 Version:**

<details>
<summary>Error Log</summary>

</details>

**Additional information:**

**Comment by ismellpie3** [comment]
![20210405115221_1](https://user-images.githubusercontent.com/81493529/113613397-0868fb00-9606-11eb-80b7-b9d97750a081.jpg)

**Comment by DeliWasTaken** [comment]
That's definitley a leak. I'm unaware of any issues currently in that style, but does this happen without any items in the map?

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
