### ISSUE TITLE
BEE2 DON'T START PLS HELP

### ISSUE THREAD

**Issue by AeroGas** [BEEmod/BEE2.4#1557]
Hey,
I can't launch BEE2. Whenever i start it, my memory grows up to 5Go used ( i have 16) and the app don't start. I have bee2 version 4.39.1. I tried to reinstall BEE2 , even to re-download everything but it keeps doing, please help me!

![wtf](https://user-images.githubusercontent.com/82058507/113866782-02158300-97ae-11eb-8019-b11fcba4d1c1.png)

PS: i don't use ucps.

**Comment by AeroGas** [comment]
Fixed, nevermind

**Comment by TeamSpen210** [comment]
What caused this?
