### ISSUE TITLE
Fizzler causing a compile error

### ISSUE THREAD

**Issue by delete00** [BEEmod/BEE2.4#1558]
Everytime i add a basic fizzler into my test chamber, it gives me an error
Im using the 4.38.1 version of BEE2

Error Log:

VBSP failed.

[I] vbsp.main(): BEE2 v4.38.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "precomp\connections.py", line 909, in calc_connections
KeyError: 'fiz1833_modelStart1833'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1907, in main
  File "precomp\connections.py", line 911, in calc_connections
ValueError: "fiz1833_modelStart1833" is not a known instance!
[7352] Failed to execute script compiler_launch

Please help?

**Comment by seagemgames** [comment]
You should always update before posting a bug report. This has been fixed in 4.39

**Comment by delete00** [comment]
> You should always update before posting a bug report. This has been fixed in 4.39

I tried this version and got this error

Traceback (most recent call last):
  File "app \ sound.py", line 136, in ticker
  File "pyglet \ media \ __ init__.py", line 140, in load
  File "pyglet \ media \ __ init__.py", line 130, in load
  File "pyglet \ media \ codecs \ wmf.py", line 882, in decode
  File "pyglet \ media \ codecs \ wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] The byte stream type of this URL is not supported

Same thing with 4.39.2

**Comment by Luke18033** [comment]
That's an unrelated issue. It says in the contributing guidelines to only report bugs in the latest version.

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
