### ISSUE TITLE
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] Windows Error 0xc00d36c4

### ISSUE THREAD

**Issue by HyperTerminal95** [BEEmod/BEE2.4#1562]
**BEE2 version:** 4.39.1 and 4.39.0

**Description of the bug:** After launching the .exe, the following error occurs and doesn't launch BEE2.

**Additional information:**
Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] Windows Error 0xc00d36c4

I have tried installing media codec packs, sadly it wasn't fixed.

Yes, I have also checked my anti-virus and made an exception in the settings.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Comment by HyperTerminal95** [comment]
How is it a duplicate?

**Comment by LautaroL20** [comment]
The "WinError -numbers" part is irrelevant, the most important segment of the log is where it says that `pyglet.media.exceptions.MediaDecodeException` fails to work and that would be a duplicate of that issue.

**Comment by TeamSpen210** [comment]
Actually that's the Windows code indicating what internally happened. They're likely very similar causes, but it could be slightly different.
