### ISSUE TITLE
Can't build level

### ISSUE THREAD

**Issue by Keepup715** [BEEmod/BEE2.4#1567]
Whenever I want to test my level it says level failed to build and no matter how much I try it won't work. Please fix this

**Comment by FrozenDragon0** [comment]
How are we supposed to fix this if you don't provide a console log?

**Comment by Keepup715** [comment]
It wont build when i try to test it

**Comment by FrozenDragon0** [comment]
@Keepup715 Open up the console and see what it says.

**Comment by Keepup715** [comment]
ill do it tommorow

**Comment by Keepup715** [comment]
it late for me

**Comment by LautaroL20** [comment]
Closing because the author does not respond and he probably never will.
