### ISSUE TITLE
Build Error in 4.38.1

### ISSUE THREAD

**Issue by Nyrif** [BEEmod/BEE2.4#1568]
**BEE2 Version: 4.38.1**

<details>
<summary>Error Log</summary>

VBSP failed.

[I] vbsp.main(): BEE2 v4.38.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "H:/Games/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "H:/Games/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] options.load(): Extra config options: {'staticpan': 'instances/BEE2/over/static_panel/', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (2 antlines)
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "precomp\connections.py", line 909, in calc_connections
KeyError: 'fiz14_modelStart14'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1907, in main
  File "precomp\connections.py", line 911, in calc_connections
ValueError: "fiz14_modelStart14" is not a known instance!
[21460] Failed to execute script compiler_launch

</details>

**Additional information: 4.37.0 also did this but no matter how many items I remove from the map it still does it. 4.39.2 is not a viable fix for me because 4.39.2 just doesn't even start up.**

**Comment by LautaroL20** [comment]
When reporting a bug, first make sure you're on the latest version of the mod, as the issue may have already been fixed. You're using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

> Nyrif said: "4.39.2 is not a viable fix for me because 4.39.2 just doesn't even start up."

If that is the case, you will need to wait for a most stable release then. However, you could install BEE2 4.36.1 since many people says that it is the most stable Beemod release.

**Comment by Nyrif** [comment]
> When reporting a bug, first make sure you're on the latest version of the mod, as the issue may have already been fixed. You're using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

I literally cannot use the new version.

**Comment by Luke18033** [comment]
Then I don't know what you expect us to do?

**Comment by LautaroL20** [comment]
> Nyrif said: "I literally cannot use the new version."

You did not quote my message entirely... i literally gived you a suggestion about that.

**Comment by Nyrif** [comment]
> > Nyrif said: "I literally cannot use the new version."
> 
> You did not quote my message entirely... i literally gived you a suggestion about that.

tried it and got the same error
