### ISSUE TITLE
catwalk crash

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2.4#1572]
if you'll try to pull the surface under the catwalk, the game will close

**Comment by FrozenDragon0** [comment]
Hardcoded problem that can't be fixed. Also you have posted in the wrong section.

**Comment by TeamSpen210** [comment]
It might be resolved by my editoritems fixes, but I'll need to check.

**Comment by LautaroL20** [comment]
> TeamSpen210 said: "It might be resolved by my editoritems fixes, but I'll need to check."

In that case, i will re-open this issue for the time being.
