### ISSUE TITLE
autoportal don't open 

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2.4#1573]
they dont open even if you connect them,but it doesn't crush the game

**Comment by FrozenDragon0** [comment]
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3672 Also you have posted in the wrong section.

**Comment by anymaker3333** [comment]
ok


сб, 24 апр. 2021 г. в 08:33, >:FrozenDragon:< ***@***.***>:
