### ISSUE TITLE
I'm on a sugar crash

### ISSUE THREAD

**Issue by Swino4ka** [BEEmod/BEE2.4#1577]
**BEE2 version: 4.39.1**

**Description of the bug:
![image](https://user-images.githubusercontent.com/83330628/116352528-998e5480-a7f5-11eb-8ff5-924f375c067e.png)
**

**Steps to reproduce: Just launching the app**

**Additional information: Nothing**

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Comment by HRudyPlayZ** [comment]
Even if this issue is a duplicate, it had a good title so i had to:
https://imgur.com/HUMfXJf
