### ISSUE TITLE
Build error for no reasons

### ISSUE THREAD

**Issue by Badpoolinator** [BEEmod/BEE2.4#1578]
I am on BTS style and even with the default test chamber (empty 4x6 room) it just gives me an error. Any fixes? 

error.p2c: https://drive.google.com/file/d/1BQYcql5QZetdu3YjZCHJYLUgsdP8gdmE/view?usp=sharing

**Comment by HeimlichLaboratories** [comment]
I think this was already reported? #3739 in the items section

**Comment by HeimlichLaboratories** [comment]
https://github.com/BEEmod/BEE2-items/issues/3739

**Comment by FrozenDragon0** [comment]
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3720 Also you have posted in the wrong section.
