### ISSUE TITLE
BEEmod Export Error

### ISSUE THREAD

**Issue by JeremiahWD** [BEEmod/BEE2.4#1580]
**Description:**

I went to export the palette I made for Portal 2, but it didn't work and made an error log. Could someone help me with this? Thanks

**BEE2 Version:**
4.39.1

<details>
<summary>Error Log</summary>

Traceback (most recent call last):
  File "app\UI.py", line 815, in export_editoritems
  File "app\gameMan.py", line 691, in export
  File "packages\editor_sound.py", line 30, in export
  File "app\gameMan.py", line 393, in add_editor_sounds
  File "srctools\__init__.py", line 465, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\portal2_dlc2\\scripts\\tmp_5' -> 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\portal2_dlc2\\scripts\\game_sounds_editor.txt'

</details>

**Comment by Luke18033** [comment]
Do you have Portal 2 open, or a second copy of BEEmod? Something is accessing that file.

**Comment by Luke18033** [comment]
Try restarting your computer, see if that helps.

**Comment by JeremiahWD** [comment]
Ohhh, thanks. I had previously installed the BEEmod 1, and that was in the Portal 2 game files. I've deleted it's working now.
