### ISSUE TITLE
Failure to compile: PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by JeremiahWD** [BEEmod/BEE2.4#1581]
**Description:**
I have been exporting different palettes to Portal 2 and it's working really well so far. But whenever I change the 'style' to 1970s or below, the game gives me an error message. Could someone please help me with this? Thanks

**BEE2 Version:**
4.39.1

<details>
<summary>Error Log</summary>

Traceback (most recent call last):
  File "app\UI.py", line 815, in export_editoritems
  File "app\gameMan.py", line 691, in export
  File "packages\editor_sound.py", line 30, in export
  File "app\gameMan.py", line 393, in add_editor_sounds
  File "srctools\__init__.py", line 465, in __exit__
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\portal2_dlc2\\scripts\\tmp_6' -> 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\portal2_dlc2\\scripts\\game_sounds_editor.txt'

**Comment by JeremiahWD** [comment]
I have found the file location that it's talking about if that helps.
![image](https://user-images.githubusercontent.com/83687526/117102456-c0332900-adbb-11eb-95aa-a3be5674bb27.png)

**Comment by LautaroL20** [comment]
@JeremiahWD - Does this issue also happens to you in BEE2 4.40.2?

**Comment by Luke18033** [comment]
Not reproducible and author isn't responding.
