### ISSUE TITLE
Fatal error every time i do anything

### ISSUE THREAD

**Issue by SuperConnorGaming** [BEEmod/BEE2.4#1590]
**BEE2 version:**

**Description of the bug:**

**Expected behavior:**

**Steps to reproduce:**

**Additional information:**

**Comment by seagemgames** [comment]
How helpful. This gives absolutely no information to anyone about what's wrong. The template is there for a reason

**Comment by LautaroL20** [comment]
Yep, it is currently not possible to solve your issue without any kind of info, so I am laving this closed this until we get some info from the issue´s author.
