### ISSUE TITLE
vvis portal file isnt built/ cant be read

### ISSUE THREAD

**Issue by Fennecai** [BEEmod/BEE2.4#1595]
**BEE2 Version:**
4.39.1

<details>
<summary>Error Log</summary>

VVIS failed.

Valve Software - vvis.exe (May 19 2021)
8 threads
reading e:\antonios stuff\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
reading e:\antonios stuff\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
LoadPortals: couldn't read e:\antonios stuff\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt

</details>

**Additional information:**
running portal 2 in administrator mode currently; but this fails even with it off.
I cant think of any other information but please ask for clarity where needed.

**Comment by TheEnderek0** [comment]
You have a leak in your map most probably

**Comment by Fennecai** [comment]
> You have a leak in your map most probably

not to be rude but this is the bee2 repository. if this was hammer I wouldn't have needed to post about it, I would have just fixed it myself. the leak is being caused by some problem with bee2, that's why I'm reporting it. this happens when compiling in-game.

**Comment by TheEnderek0** [comment]
Leaks can happen in PeTI too. And also this is I belive wrong section, it should be posted in BEE2-Items repository since. You probably use an item that is broken in this version of BEE2 and causes leaks.

**Comment by Fennecai** [comment]
> Leaks can happen in PeTI too. And also this is I belive wrong section, it should be posted in BEE2-Items repository. You probably use an item that is broken in this version of BEE2 and causes leaks.

dude, please read my reply. i literally said:
> the leak is being caused by some problem with bee2, that's why I'm reporting it.

and I am not using any items besides the default ones. this also happens with a brand-new, un-modified puzzle.

your not one of the devs of bee2 to my knowledge and your not being helpful. please leave this for the actual devs to answer themselves.

**Comment by TeamSpen210** [comment]
Can you load the pointfile and take a screenshot, so I can know where the issue is, what style, etc?

**Comment by Fennecai** [comment]
the leak originates from the customized global_pti_ents instance but I cant figure it out because an antity inside the box leaks to the outside through a sealed nodraw wall.....

overgrown:
![image](https://user-images.githubusercontent.com/10889213/119730026-8392a480-be32-11eb-95e9-ba96da6b444c.png)


portal 1:
![bee2_leak_p1](https://user-images.githubusercontent.com/10889213/119730114-9907ce80-be32-11eb-8ace-dcfcbfe081ca.png)

...and of course, since it's the global ents, it happens for all the styles.

**Comment by Fennecai** [comment]
well- it seems ive found a way to fix the problem; and it turns out the problem is something that will most likely never occur for anybody besides me, because it resulted from a special mounting setup I have in my gameinfo.xtx files.

i had to adjust things to force portal2, dlc1, and dlc2 to be mounted below |gameinfo_path| and that fixed it somehow.....

I'm gonna close the issue since its something that's highly unlikely to occur for other people, and since the issue wasn't related to bee2 after all. sorry to waste time

**Comment by TeamSpen210** [comment]
Did you end up moving your FGD file perhaps? That will  break instances if VBSP can't find it.

**Comment by Fennecai** [comment]
I don't believe so. its in portal 2's bin folder as always.
