### ISSUE TITLE
"You cant play this level without the beemod or resource pack"

### ISSUE THREAD

**Issue by legomiku** [BEEmod/BEE2.4#1597]
I am using the current version of beemod, and whenever i go to a level that uses it, it says, "You cant play this level without the beemod, or beemod resource pack. Get either at portal2backstock.com/bee" the link it says is broken, and i have beemod installed, any help?

**Comment by Luke18033** [comment]
In the original BEEmod 1.5, you needed to have the mod installed to play maps made with it, and would see that message if you didn't. Maps made in newer versions of BEE no longer require that, but the files should still be included for those older maps to work, unless that broke at some point. I'll need to test it, can you send a link to one of the maps that was showing the message?

**Comment by legomiku** [comment]
Ok, finally found another level that had the error: https://steamcommunity.com/sharedfiles/filedetails/?id=2499243827 
This one was made recently.

**Comment by Luke18033** [comment]
Not sure what was wrong here, the script is there for me, and works to allow the map to load...
