### ISSUE TITLE
my version of the logo

### ISSUE THREAD

**Issue by ebartaus** [BEEmod/BEE2.4#1598]
hello. i don't really like the current logo of bee2, so i made my own version:
[beemod icon.zip](https://github.com/BEEmod/BEE2.4/files/6553530/beemod.icon.zip)
¯\_(ツ)_/¯

**Comment by ebartaus** [comment]
i also made loading screens with this logo:
![splash 2](https://user-images.githubusercontent.com/72306717/119833898-29fca980-bf08-11eb-9447-9ccd392187df.png)
![splash 3](https://user-images.githubusercontent.com/72306717/119833904-2a954000-bf08-11eb-9f42-147776ee75d7.png)
![splash 1](https://user-images.githubusercontent.com/72306717/119833908-2b2dd680-bf08-11eb-90c1-4add9fabd108.png)

**Comment by koerismo** [comment]
Might have gone a little overboard with the rounded edges imo. The BEE interface mainly takes after the puzzlemaker ui, which is composed of sharper shapes. I think having only a somewhat-rounded edge could take this up a notch... This does remind me of MacOS Catalina, though.

Also, what's BEE without a bee in the logo?

**Comment by ebartaus** [comment]
about the bee, i was thinking about it. the bee really symbolizes beemod, but it will look bad on the logo, given that it is a tool for portal 2. as for the rounded corners, just the loading screen with them looks better. but yes, in the program interface, they will only interfere. (sorry for the bad english)

**Comment by SCIENTIST2004** [comment]
How about use portal 2 art instead of screenshots? I already tried it looks cool

**Comment by ebartaus** [comment]
> How about use portal 2 art instead of screenshots? I already tried it looks cool

yes, it looks cool
![splash 4](https://user-images.githubusercontent.com/72306717/120315701-4f612d00-c2e5-11eb-80bd-246e9475b1a5.png)

**Comment by ebartaus** [comment]
> How about use portal 2 art instead of screenshots? I already tried it looks cool
опа, русский язык)

**Comment by SCIENTIST2004** [comment]
> > How about use portal 2 art instead of screenshots? I already tried it looks cool
> 
> опа, русский язык)

)

**Comment by Thedoczek** [comment]
1. There must be 2 in logo
2. There must be a bee in logo

I'd just replace that workshop tool with a bee.

**Comment by Luke18033** [comment]
Not really sure what's going on here, we're not changing the BEE2 logo. The splash screen colors should probably be adjusted though.
