### ISSUE TITLE
"Failed to execute script BEE2_launch" BEE2 version 4.39.1

### ISSUE THREAD

**Issue by SuperConnorGaming** [BEEmod/BEE2.4#1599]
also I get this bug whenever the app starts up

**Comment by SuperConnorGaming** [comment]
writing an improved (hopefully) version of the last issue I posted

**Comment by LautaroL20** [comment]
The type of error you have mentioned in the title, is a totally generic message that BEEmod will throw after a random crash. Please, copy and paste the log error from BEEmod here in order to figure out if this is a duplicated issue or if this is a new crash error that has not been posted before.

**Comment by LautaroL20** [comment]
Closing because the author doesn't respond.
