### ISSUE TITLE
3 menu's for slots

### ISSUE THREAD

**Issue by TheVogels** [BEEmod/BEE2.4#1601]
i think that bee mod 2 should have 3 menu's to select your blocks 😋.

**Comment by Critfish** [comment]
If you're suggesting extra item slots in the level editor, they can't add that. It's impossible to modify the editor interface itself.

**Comment by TheVogels** [comment]
oh

**Comment by TheVogels** [comment]
> 
> 
> If you're suggesting extra item slots in the level editor, they can't add that. It's impossible to modify the editor interface itself.

oh
