### ISSUE TITLE
The Pesdestal Button not have style when playing (Old Aperture Style)

### ISSUE THREAD

**Issue by IDy8I** [BEEmod/BEE2.4#1602]
The Pesdestal Button (Lautaro) have the style in the editor but when playing not (Old Aperture Style)

**Comment by HeimlichLaboratories** [comment]
I reported this already like, some months ago or something?

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
