### ISSUE TITLE
If no funnel music is set, keep base track playing.

### ISSUE THREAD

**Issue by HeimlichLaboratories** [BEEmod/BEE2.4#1603]
While the special themes for flinging and being in a funnel are good in some cases, there's situations when they're annoying. For example, if you're making a level with the theme Self Esteem Fund and it features momentum, the fling theme is out of place in the sad atmosphere of the theme. For the funnel music, it also breaks the atmosphere if it plays during a timed level with An Accent Beyond. There should be four stylevars; fling, funnel, propulsion gel, repulsion gel themes. I'm so sorry if this is a duplicate, I've tried to search but didn't found anything.

**Comment by SCIENTIST2004** [comment]
What about to add all music in all categories? I mean if anybody wants to play funnel as base music or gel music as funnel music. It will make possible to set music combinations as you wish.

**Comment by HeimlichLaboratories** [comment]
> What about to add all music in all categories? I mean if anybody wants to play funnel as base music or gel music as funnel music. It will make possible to set music combinations as you wish.

^
This.

**Comment by CassieCatYT** [comment]
I think that it would make sense if we could do these things too
