### ISSUE TITLE
App crashing always at it's second lauch, unless some app-changing file changed

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2.4#1609]
**BEE2 version:**
BEE 4.39.2
Windows 10

**Description of the bug:**
After installing, at first time game launches normally, but on second and further launches it crashes. I changed .mo file and it again launched properly, and on second launch it started behaving like before change.

**Steps to reproduce:**
https://youtu.be/4WjWCvLPdec

**Comment by CardsAndGamesYT** [comment]
upgrade to 4.40.2, that should fix it. also a lot of things are broken in 4.39.2 anyway
