### ISSUE TITLE
About Monitors

### ISSUE THREAD

**Issue by CanAtr** [BEEmod/BEE2.4#1611]
Hello i have question how can i make monitor image like in the vanilla portal 2?        by the way if theres no choice like this thats why i chose "Generic Feature Request" sorry if im wrong or something but i didnt find out how to do it so can anyone tell me?

**Comment by TheEnderek0** [comment]
What means "image like in the vanilla portal 2"?
If you mean wheatley on a monitor, just select wheatley voice lines and place the monitor anywhere.

**Comment by CanAtr** [comment]
> What means "image like in the vanilla portal 2"?
> If you mean wheatley on a monitor, just select wheatley voice lines and place the monitor anywhere.

i meant video or whatever else in monitor is diffirent like in portal 2 vanilla theres just wheatley in bee mod theres wheatley,pipe,moving plate i dont remember actually 

i want monitor like this:
![maxresdefault](https://user-images.githubusercontent.com/46308330/121818345-4ed67800-cc8f-11eb-8b06-e906dd191af8.jpg)

**Comment by TeamSpen210** [comment]
I did that intentionally, to make the video look a little better.
