### ISSUE TITLE
HEPs not packing resources automatically 

### ISSUE THREAD

**Issue by legomiku** [BEEmod/BEE2.4#1612]
Ive been playing around in a few workshop levels that used beemod, but whenever I come across a level with the High Energy Pellet, the texture is missing, I remember playing a beemod level a month ago (I don't think i had beemod installed), and the texture wasn't missing. There are also missing textures on the edges of grills, both errors are shown in the picture I took:
![image](https://user-images.githubusercontent.com/84869321/121820842-b669d480-cc49-11eb-9daf-8e611c8cfcca.png)

I have beemod installed, and all the packages installed too. Did i miss a package to install or is this just a bug?

link to the level this was in: https://steamcommunity.com/sharedfiles/filedetails/?id=2509730873

**Comment by HeimlichLaboratories** [comment]
Energy pellets appear as missing textures when playing the published map, not sure if it's been reported already

**Comment by Luke18033** [comment]
I guess reflection gel isn't the only thing which still needs a PackList after all...

**Comment by TeamSpen210** [comment]
The postcompiler should detect the launcher entity, and then pack the relevant resources - I wonder why it isn't?

**Comment by Luke18033** [comment]
Ah, is that supposed to be implemented for reflection gel as well?

**Comment by TeamSpen210** [comment]
Not yet.

**Comment by TeamSpen210** [comment]
This seems to be working fine.
