### ISSUE TITLE
"TypeError: 'ABCMeta' object is not subscriptable" when launched on Linux

### ISSUE THREAD

**Issue by xtechgithub** [BEEmod/BEE2.4#1613]
BEE2 version: Latest dev branch version

Description of the bug: BEE2 crashes on launch on Linux, Ubuntu MATE to be specific, with "TypeError: 'ABCMeta' object is not subscriptable"

Steps to reproduce: Compile dev branch version on Linux with all dependencies installed. Launch BEE2 with the command "./BEE2" in "/BEE2.4-dev/dist/64bit/BEE2".

Additional information: 
![Screenshot at 2021-06-14 12-36-01](https://user-images.githubusercontent.com/65952362/121887907-432a9600-cd0f-11eb-946a-bb4453cc05ed.png)

**Comment by TeamSpen210** [comment]
Whoops, I swapped some imports in a way that might not have worked on some Python versions.
