### ISSUE TITLE
Idea (or is there already a way?): Addition of custom voice lines

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1616]
**Description of the feature:**
I'd like a feature that will let anyone import a custom voice line.

**This should be implemented because:**
So i want to create a mappack with custom voice lines and OST, and i'd like to know, is it possible to import custom voice lines, at least without captions.

**Additional information:**
So, as i already said, i want to create a mappack for Portal 2 with custom voice lines and OST.

**Comment by FrozenDragon0** [comment]
Custom voicelines can be done but the localizations/subtitles for them cannot be packed.

**Comment by TPEcool** [comment]
> 
> 
> Custom voicelines can be done but the localizations/subtitles for them cannot be packed.

i know, but I don't know how...

**Comment by FrozenDragon0** [comment]
@TPEcool From what I understand from some community BEE2 maps on the workshop with custom voicelines the author either made a custom package with the voicelines or they have edited the map in hammer to incorporate the custom voices.

**Comment by TPEcool** [comment]
Ok, i don't know how to compile a custom package though...

вт, 15 июн. 2021 г., 14:19 >:FrozenDragon:< ***@***.***>:

**Comment by HeimlichLaboratories** [comment]
Adding custom music should be also in BEE2, in my opinion. BMMC is broken for me, plus the latest version cannot be installed for some reason.
