### ISSUE TITLE
BEEmod 4.40.1 Crash after reset package cache and then pressing the export button: UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-12: ordinal not in range(128)

### ISSUE THREAD

**Issue by THS2121966** [BEEmod/BEE2.4#1623]
**BEE2 version: 4.40.1 BEE2 Items Version is 4.40.0**

**Description of the bug: When i press "export to Portal 2" button and export is beginning after exporting compilers i see this error in picture below...**

**Expected behavior: Complete export scenario.**

**Steps to reproduce: Reset package cache and press export button.**

**Additional information:**
![123](https://user-images.githubusercontent.com/56027883/124345741-78365400-dbfc-11eb-8cab-f6e9fd3dd353.PNG)

**Comment by TeamSpen210** [comment]
DO you have any extra packages installed, other than the defaults?

**Comment by THS2121966** [comment]
No. Just only from bee2-items on GitHub page.

**Comment by THS2121966** [comment]
But on previous version i used myself modified packages. And later deleted that but in config beemod files maybe they are saved. Previous version is 4.36.1

**Comment by THS2121966** [comment]
I deleted BEEMOD2 folder from "roaming" folder and found second error:
![123](https://user-images.githubusercontent.com/56027883/124381082-67600e00-dce2-11eb-80d1-b90061a70264.PNG)

**Comment by THS2121966** [comment]
Maybe I miss something or this program has more unstable than previous versions...

**Comment by THS2121966** [comment]
I use BEE2_v4.40.1_win64 version.
