### ISSUE TITLE
Add a sensor or trigger for co-op...

### ISSUE THREAD

**Issue by ZeroNikcol** [BEEmod/BEE2.4#1625]
And so, after you read the title, you may not understand what is at stake, but I wanted to add a sensor for cooperative mode or a trigger that is triggered only when two partners enter this trigger, if one partner leaves the trigger, then this trigger will turn off, and here is the picture you saw in co-op:
![300px-Portal2CoopDoorFromMp_Coop_Doors](https://user-images.githubusercontent.com/57002697/124406314-b4c39600-dd49-11eb-9e01-85185a708594.jpg)

Sorry for the small resolution, I was just looking for this picture on the Internet. 
This sensor can be contacted with ** door, half glass door, camera lock ** and other devices that open, can also be built from rail platforms into an elevator, for co-op, can only be done with a sensor or trigger for cooperative.

Sorry for my English, I'm Russian))

**Comment by LautaroL20** [comment]
The item you are suggesting can already be replicated by using the "trigger multiple" as long as you check the option "Start Reversed" which will convert it into a Co-Op trigger. You can read any item description by right-click on an item in the BEEmod palette: 

![Co-op trigger](https://user-images.githubusercontent.com/12244376/124412517-17566b00-dd25-11eb-88b5-72371cf04859.png)

**Comment by LautaroL20** [comment]
Also, you have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.
