### ISSUE TITLE
BEEmod will crash if you left-click on an item icon in the properties dialog in the items palette. 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1635]
**BEE2 version:** Version 4.40.2

**Description of the bug:** BEEmod will crash when you click on an item icon in the properties dialog in the items palette.

 **Steps to reproduce:** Open the properties window from an item on the BEEmod Items Palette and then left-click the icon.

 **VIDEO showing the application crash:**

https://user-images.githubusercontent.com/12244376/132578519-afaaba70-4750-4f24-9464-11b7dbd17602.mp4

**Comment by Luke18033** [comment]
It's a little unclear what you're doing without the cursor visible, but if what caused the crash was clicking on one of the other subtypes in the properties window then this is fixed.

**Comment by LautaroL20** [comment]
> "if what caused the crash was clicking on one of the other subtypes in the properties window then this is fixed."

No, this crash can happen regardless if the item have or not subtype properties. I might make a small video with another program where the cursor is visible, but basically the seps to replicate the crash would be by deploying the properties window from any item on the BEEmod Items Palette and then left-clicking the icon.

**Comment by Luke18033** [comment]
I see, it's caused by clicking on the currently selected subtype again. In that case this is still an issue.
