### ISSUE TITLE
Custom high velocity/orange gel music imported using BMMC2 not working after exporting and compiling the chamber

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1637]
**BEE2 version: 4.40.2**

**Description of the bug: When I add high velocity/orange gel music using BMMC2 and export a palette with that music, no music plays when I'm at extreme speeds.**

**Expected behavior: The imported high velocity/orange gel music should play when needed, not _NEVER_.**

**Steps to reproduce: 1.Make a music package using BMMC2. 2.Export it to your BEE2. 3.Use that music in a palette and export. 4.Build a chamber. 5.Compile it. (F9) 6. Place a portal on the floor and on the ceiling and enter the "infini-fling"(infinite fling) or put some orange gel on the floor and run on it. 7.You will not hear the set high velocity/orange gel music.**

**Additional information: Since this isn't an in-game error, I don't have any console messages or BEE2 logs. I'm sorry.**

**Comment by TPEcool** [comment]
Also, there is never any BEE2 preview for the high velocity/orange gel music imported using BMMC2. The "Play a sample of this item." button is just grey and inactive.

**Comment by Laudanum-dev** [comment]
bmmc is not being developed by beemod's devs, for issues related to it you probably should find where you can submit an issue of bmmc (you can find all needed links in its [official site](https://beemmc.boards.net/) ). orange gel music works fine when you pack it manually, so beemod have nothing to do with this

**Comment by TPEcool** [comment]
i know that BMMC2 isn't developed by BEE2 devs, i just have an issue

**Comment by HeimlichLaboratories** [comment]
The latest BEE2 version is 4.40, not 4.36

**Comment by TPEcool** [comment]
@HeimlichLaboratories i know, at the moment i uploaded this, my BEE2.4.40.2 was always freezing at startup, but I fixed that now

**Comment by LautaroL20** [comment]
When reporting a bug, first make sure you're on the latest version of the mod, as the issue may have already been fixed. You're using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

**Comment by TPEcool** [comment]
I tried the newest BEE2.4.40.2 and i still have this issue. I even tried rebuilding the audio cache (snd_rebuildaudiocache), but it didn't fix the issue.

**Comment by LautaroL20** [comment]
> I tried the newest BEE2.4.40.2 and i still have this issue.

Alright then.

**Comment by TPEcool** [comment]
Any idea what can help? (The audio exported into P2 is in the required format, .wav 16-bit Microsoft PCM and 44100hz frequency)

**Comment by TeamSpen210** [comment]
Did you get any errors/warnings in the application or compiler log? Could you attach a copy of the `info.txt` file in the zip BMMC2 generated, I'll check if it's correct.

**Comment by TPEcool** [comment]
Okay, i'll do it.

**Comment by TPEcool** [comment]
Got something like this from the bee2.5.txt file (i guess it's the last log):
[INFO] utils.setup_localisations(): Language: 'ru_RU'
[DEBUG] utils.setup_localisations(): Language codes: ['ru_RU.UTF-8', 'ru_RU', 'ru.UTF-8', 'ru']
[INFO] BEE2_launch.<module>(): Arguments: ['C:\\Users\\SaN79\\Documents\\Trainz Simulator 12  WWW.rustorka.com\\Beemod 4.40.2\\BEE2.exe']
[INFO] BEE2_launch.<module>(): Running "bee2", version 4.40.2:
[INFO] sound.load(): Loading sound "select" -> C:\Users\SaN79\Documents\Trainz Simulator 12  WWW.rustorka.com\Beemod 4.40.2\sounds\rollover.ogg
[DEBUG] BEE2.<module>(): Starting loading screen...
[DEBUG] BEE2.<module>(): Loading settings...
[ERROR] sound.load(): Couldn't load sound select:
Traceback (most recent call last):
  File "pyglet\media\codecs\wave.py", line 58, in __init__
  File "wave.py", line 509, in open
  File "wave.py", line 163, in __init__
  File "wave.py", line 130, in initfp
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\sound.py", line 95, in load
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wave.py", line 107, in decode
  File "pyglet\media\codecs\wave.py", line 60, in __init__
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id

**Comment by TPEcool** [comment]
I'm not sure if it's about my issue.

**Comment by TPEcool** [comment]
I don't see any music-related logs in the Portal 2/bin/bee2, there are only vbsp.error.txt saying  "Hammer map detected. Skipping conversion...", even though I never use Hammer World Editor, and vrad.error.txt files saying that some keyvars are incorrect for some objects

**Comment by TPEcool** [comment]
But everything about the things with incorrect keyvars is fine.

**Comment by TPEcool** [comment]
> 
> 
> Did you get any errors/warnings in the application or compiler log (`logs/` in the application folder, `Portal 2/bin/bee2/` for compilers)? Could you attach a copy of the `info.txt` file in the zip BMMC2 generated, I'll check if it's correct.
Here's all the stuff from there:
"ID" "BMMC_CONFUSION"
"Name" "BEEMod Music Changer"
"Desc" "Package generated by BMMC2."
"Music"
{
"ID" "BMMC_CONFUSION"
"Name" "Confusion"
"ShortName" "Confusion"
"Group" "BEEMod Music Changer"
"Icon" "music_custom\bmmc2.png"
"IconLarge" "music_custom\bmmc2.png"
"Authors" "aerond"
"Description" "Added using BMMC2. BMMC2 is a third-party software for BEEMod developed by aerond. beemmc.boards.net"
"Sample"
{
"Base" "custom/confusion.wav"
}
"SoundScript"
{
"Base" "music/confusion.wav"
"SpeedGel"
{
"snd" "music/s_confusion_confusion-highvelocity1.wav"
"snd" "music/s_confusion_confusion-highvelocity2.wav"
"snd" "music/s_confusion_confusion-highvelocity3.wav"
"snd" "music/s_confusion_confusion-highvelocity4.wav"
}
}
}

**Comment by TPEcool** [comment]
I added four orange gel tracks because i thought that may fix the problem, but all the tracks are the same, just copied and named differently.

**Comment by TPEcool** [comment]
So... what's wrong?

**Comment by TPEcool** [comment]
> 
> 
> bmmc is not being developed by beemod's devs, for issues related to it you probably should find where you can submit an issue of bmmc (you can find all needed links in its [official site](https://beemmc.boards.net/) ). orange gel music works fine when you pack it manually, so beemod have nothing to do with this

oh, and, also, BMMC2's forum is dead. I wouldn't get a response

**Comment by TPEcool** [comment]
maybe there's an issue with that because BMMC2 was built for BEE2.4.pr.* versions.

**Comment by TPEcool** [comment]
i just checked that on their official site

**Comment by CardsAndGamesYT** [comment]
> maybe there's an issue with that because BMMC2 was built for BEE2.4.pr.* versions.

I don't think so because I am using the newest beemod and my bmmc is working fine, an issue I had is that my audio file being corrupted, check to see if that's the issue

**Comment by TPEcool** [comment]
> 
> 
> > maybe there's an issue with that because BMMC2 was built for BEE2.4.pr.* versions.
> 
> I don't think so because I am using the newest beemod and my bmmc is working fine, an issue I had is that my audio file being corrupted, check to see if that's the issue

nope, it doesn't seem like they are corrupted

**Comment by Luke18033** [comment]
I don't think this is BEE's fault, BMMC is outdated anyway I think.
