### ISSUE TITLE
BEEmod causes "Failure To Compile" - "Could not open instance file instances/BEE2/clean/elevator_sp/door_frame_black.vmf"

### ISSUE THREAD

**Issue by fishonlegs** [BEEmod/BEE2.4#1638]
I've built a chamber, and I wanted to build it to test it out. It goes about halfway through the "Building Geometry" bar, then I get an error: _` There was an error building the puzzle`_. In the dev menu, it mentions it can't find certain assets (`VBSP failed.
Valve Software - vbsp.exe (May 19 2021) 4 threads Using shader api: shaderapiempty.dll materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ConVarRef gpu_level doesn't point to an existing ConVar Could not open instance file instances/BEE2/clean/elevator_sp/door_frame_black.vmf
`) There are more, if you want I can add them.  I am using Version 2.40.2, and I have unblocked VBSP.exe and VRAD.exe from my Antivirus.

**Comment by Luke18033** [comment]
Re-export
