### ISSUE TITLE
Failed to publish (portal 1 style)

### ISSUE THREAD

**Issue by Scottiegithub** [BEEmod/BEE2.4#1647]
**BEE2 Version:** 4.40.2

I was making a portal 1 styled map, but during the publishing process (which i've done before with portal 1 styled maps) it fails just after building geometry with this error message
<details>
<summary>Error Log</summary>

VVIS failed.
Valve Software - vvis.exe (May 19 2021)
16 threads
reading d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1627060155.bsp
reading d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1627060155.prt
LoadPortals: couldn't read d:\steamlibrary\steamapps\common\portal 2\sdk_content\maps\1627060155.prt

</details>

**Comment by LautaroL20** [comment]
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
