### ISSUE TITLE
Cannot open BEE2.

### ISSUE THREAD

**Issue by KaziPlays** [BEEmod/BEE2.4#1649]
Put the need more information tag.

Basically, what happens is that it simply gives me a normal "Application.exe has stopped working" error and doesn't leave a log.

OS: Windows 7 64-bit

BEE2 Version: 4.40.2, 4.40.1, and 4.39.2 32-bit (Maybe all versions crash?)

![program_has_stopped_working_error](https://user-images.githubusercontent.com/72144613/126916014-b00a1918-4124-457f-8700-4c8ffb8dbe2d.png)

**Comment by KaziPlays** [comment]
Double checked, there is a log, but it shows absolutely nothing.

```
[INFO] utils.setup_localisations(): Language: 'pt_BR'
[DEBUG] utils.setup_localisations(): Language codes: ['pt_BR.ISO8859-1', 'pt_BR', 'pt.ISO8859-1', 'pt']
[WARNING] utils.setup_localisations(): Can't find translation for codes: ['pt_BR.ISO8859-1', 'pt_BR', 'pt.ISO8859-1', 'pt']!
[INFO] BEE2_launch.<module>(): Arguments: ['C:\\Users\\Kazi\\Desktop\\BEEMOD\\BEE2.exe']
[INFO] BEE2_launch.<module>(): Running "bee2", version 4.40.1:
```

**Comment by LautaroL20** [comment]
I have Windows 7 too, however I've never experienced this issue so probably this is not BEEmod's fault. You may need to get the latest Win 7-compatible updates of stuff like net framework, visual studio or other possible driver packages for Windows 7.

**Comment by KaziPlays** [comment]
I've fixed it by removing compatibility mode
