### ISSUE TITLE
BeeMod Launch Error

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2.4#1652]
For me the same error is happening, I've tried everything. But nothing works.
![ErroBeemod](https://user-images.githubusercontent.com/88097966/127341120-81373735-32db-4217-906b-d1768a045f25.png)

Even though I'm using the latest versions of executables and packages, there's still an error.

**Comment by Kitsune-Ultima** [comment]
I have encountered this issue myself, to fix it you need to go to "%appdata%\BEEMOD2" and create a folder labeled "config" this fixes the crash and allows bee2 to launch

at this time it seems that bee2 can not or is not programmed to create this folder

**Comment by LautaroL20** [comment]
A same issue like this is even pinned, you guys must check first if your issue was already reported before posting it... this is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1624

**Comment by CN1o2** [comment]
Ok, Thanks.
