### ISSUE TITLE
Export to hammer

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2.4#1656]
How can I export maps to hammer without problems?

**Comment by FrozenDragon0** [comment]
You would use the preview.vmf that is made with the map along with styled ones being in styled/preview.vmf

Also please do not ask questions like this here, this is not the forum for it. Ask these questions on the discord.

**Comment by HeimlichLaboratories** [comment]
I also do not recommend to do this, as BEE2 doesn't work too well with Hammer
