### ISSUE TITLE
No longer space for item name display below palette

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1658]
**BEE2 version:** Dev

**Description of the bug:** The space below the palette no longer leaves room for the item name display, causing it to stick off the bottom.
![image](https://user-images.githubusercontent.com/19228201/127782645-f4e85c3a-b802-4b27-bc08-3f7514aa631a.png)
This used to work correctly.

**Expected behavior:** A small space should be left down here where the name is displayed.
![image](https://user-images.githubusercontent.com/19228201/127782707-17f78d96-45e1-469a-83b3-357378ea4168.png)

**Steps to reproduce:**
Mouse over an item in the app.

**Comment by Laudanum-dev** [comment]
i always thought that this (first pic) is actually how it supposed to be.

**Comment by TeamSpen210** [comment]
Did a typo here, causing it to be resized 10 pixels too smaller every launch.
