### ISSUE TITLE
Selector windows default to extremely small

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1659]
**BEE2 version:** Dev

**Description of the bug:** Selector windows consistently default to a very small size which is not usable. In previous versions, the starting size was inconsistent, but never this small.
![image](https://user-images.githubusercontent.com/19228201/127783587-7ec27c4c-776c-4deb-b1b8-f84d859fb3ef.png)

**Expected behavior:** Selector windows should default to a reasonably large size, with enough room to display 3 columns of items plus the description and OK/Cancel buttons.

**Steps to reproduce:** Just open a selector window. Since the sizes are now saved, this may only apply the first time you open one and not after that, so just delete the saved window sizes from `config.vdf` to trigger this.

**Comment by Laudanum-dev** [comment]
for me it's just too large (notice the buttons being far underneath) + words are being
t
a
l
l
![image](https://user-images.githubusercontent.com/86309764/127784849-814bed39-3ec9-4dbb-a32c-844ec26c75df.png)

**Comment by Luke18033** [comment]
That text bug just happens randomly, nobody really knows why...it fixes itself if you resize the window at all.

**Comment by Luke18033** [comment]
Also is that PEE music at the top...?

**Comment by Laudanum-dev** [comment]
> 
> 
> Also is that PEE music at the top...?

downloading all ucp 'cause why not

**Comment by Luke18033** [comment]
The selector windows also seem to get slightly smaller with every app restart.
