### ISSUE TITLE
Old Aperture: floating chamber and stuck at the elevator

### ISSUE THREAD

**Issue by wheatbla** [BEEmod/BEE2.4#1665]
i was gonna play a chamber ı craeated then this happend
![PORTAL 2 - Direct3D 9 8 08 2021 15_47_31](https://user-images.githubusercontent.com/88620038/128633111-e29e15e1-431b-4053-ac84-e2cc3b72514b.png)
![PORTAL 2 - Direct3D 9 8 08 2021 15_47_45](https://user-images.githubusercontent.com/88620038/128633115-263ea94a-34ad-4b2e-a14e-8de07bef2299.png)

**Comment by wheatbla** [comment]
please help

**Comment by LautaroL20** [comment]
You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
