### ISSUE TITLE
Exporting resources from new/changed packages doesn't always work

### ISSUE THREAD

**Issue by TheEnderek0** [BEEmod/BEE2.4#1669]
**Description of the feature:**
There should be a button that forces full export into Portal 2 files. This button would force a full export, rewriting all of the files from the start, as it does when you e.g. add a new package.

**This should be implemented because:**
Sometimes when I swap the packages BEE2 does not recognize I changed something, so it doesn't export the changed content.
And also it would be usefull in many different situations

**Additional information:**
None

**Comment by Luke18033** [comment]
BEE2 is supposed to detect when packages have been added or modified and do this automatically, if it isn't doing that then it's a bug. Note that if you have unzipped packages it will do this on every export. Also make sure that Preserve Game Directories is off in the settings.

**Comment by Konclan** [comment]
Its not a bug, assets get exported and updated normally but any changes to compiler settings like vbsp_config do not get updated until you restart BEEmod. I already asked Spen about this and it has to do with data structuring so there needs to be a system to handle that. Its just not implemented yet.

**Comment by Luke18033** [comment]
I don't think that's what this is referring to? They're saying that when you install or update a package, start up BEE, then export, it doesn't copy over the new resources from that package. Which would be a bug.

**Comment by Konclan** [comment]
@TheEnderek0 didn't know about the "Reset package caches" button.
