### ISSUE TITLE
Alternate player spawn and end trigger

### ISSUE THREAD

**Issue by Dragunov37** [BEEmod/BEE2.4#1675]
**Description of the feature:**

I would like to suggest two new elements that are not related to puzzles. 

The first element is the Spawner player - this is an element that has the model of a green Freeman from Hammer. The name of the item speaks for itself, it will spawn the player where it was located, but only if there is no entrance in the test chamber, it can only be placed on the floor.
Possible functions:

- Choice of animation of appearance: no animation (the player simply appears at the specified point), with animation of awakening (you can make the same for all styles, "eyes open and the character gets up", or you can stylize sweat for each style, for example, in P1, awakening from a capsule)
- Laser Emitter cross for more detailed positioning on the panel and indicating the direction of the player's gaze when spawning
- Switch to invert the direction of gaze when spawning
- Or add, like turrets, the ability to direct the player's gaze when spawning at any angle

The second item is End Trigger - the usual trigger of the player, which is already in the mod, but when it is triggered, the level ends.

**This should be implemented because:**

I understand that these elements are needed more for decoration, but sometimes it is not convenient to arrange the entrance / exit, which takes up a lot of space.

**Comment by TheEnderek0** [comment]
Already in UCPs

**Comment by Critfish** [comment]
This seems like something that'd only ever really be useful for "story maps" - which you should be using Hammer for anyway.

**Comment by Critfish** [comment]
Also I just noticed this is in the wrong repository. This should be in the BEE2-items repository.

**Comment by seagemgames** [comment]
As TheEnderek0 said, these are already added by UCPs, and as Critfish said, this is in the wrong repository. Also, you should not combine multiple issues/suggestions as it makes them impossible to separately track.

**Comment by FrozenDragon0** [comment]
Already exist in the form of UCP's, also you should be using hammer if you want story related stuff like this.
