### ISSUE TITLE
portal 2 not working with beemod

### ISSUE THREAD

**Issue by thesmartim** [BEEmod/BEE2.4#1677]
portal 2 keeps having error when trying to publish a beemod level

i dont know the beemod version

when i try to publish it it gives me an error and discards my changes

this is my first issue on github i just signed up PLEASE DONT HATE ME

**Comment by thesmartim** [comment]
pls help

**Comment by FrozenDragon0** [comment]
We can't help you if you don't provide any information on the error.

What is the console log when you try to publish a map?

**Comment by LautaroL20** [comment]
> thesmartim said: "i dont know the beemod version"

Well... how did you even managed to download BEE2.4 in the first place? Because when you go to the download section page, it shows very clear which release version you are going to download...

**Comment by Konclan** [comment]
No response, closing
