### ISSUE TITLE
Traceback (most recent call last) File "BEE2_launch.pyw", line 50, in <module>

### ISSUE THREAD

**Issue by MappoKambriy** [BEEmod/BEE2.4#1680]
![pog](https://user-images.githubusercontent.com/89483748/130679185-146258be-889a-49cd-a13b-91b7f3550ce3.PNG)
So i have this and i dont know what to do.

**Comment by LautaroL20** [comment]
Well, we need more info than that in order to help you, like which Windows version are you using and if it is 32 or 64 bits, BEEmod version and it it is 32 or 64 bit as well.

**Comment by MappoKambriy** [comment]
> Well, we need more info than that in order to help you, like which Windows version are you using and if it is 32 or 64 bits, BEEmod version and if it is 32 or 64 bit as well.

Oh sorry i forget about it. So i have 64-Bit Windows and BEEmod also 64-bit but idk about my windows version

**Comment by LautaroL20** [comment]
> MappoKambriy said: "idk about my windows version"

That is also something important to know, type in Google: "how to determine my windows version" and you will find out help on how to determine your Windows version.

**Comment by TeamSpen210** [comment]
Windows version shouldn't really matter, have you run BEE beforehand successfully, or is this the first time?

**Comment by TeamSpen210** [comment]
This is fixed in 4.40.2, grab that version.
