### ISSUE TITLE
Crop corridor thumbnails instead of squishing them

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1681]
The small thumbnails for corridors are horizontally squished to be square, which looks somewhat stupid:
![BEE2_0dXGZyWa2v](https://user-images.githubusercontent.com/19228201/130712955-6de8c698-69c9-4072-a0fc-964242b97c0e.png)
The icons should have the edges cropped out instead:
![BEE2_0dXGZyWa2v_2](https://user-images.githubusercontent.com/19228201/130714292-1355f749-0e0d-4a4c-90b8-f5f45aa9aa80.png)

**Comment by TPEcool** [comment]
how do you get the right stairs one?

**Comment by Luke18033** [comment]
It's a new corridor which I just added.

**Comment by TPEcool** [comment]
Ok

пн, 30 авг. 2021 г., 21:49 Luke18033 ***@***.***>:

**Comment by Luke18033** [comment]
Now that I think about it, maybe it would be good to implement this for other selector window items as well? You'd still be able to provide a separate small icon if needed, but if you didn't it would crop down the large one. That would remove the need for most of the separate small/large icons, saving on file size.

**Comment by TeamSpen210** [comment]
I did implement it directly there, simply don't define the small icon. I do still need to expose a crop command, so you can manually crop other images though.
