### ISSUE TITLE
Error when creating a test camera. Please help me fix the error

### ISSUE THREAD

**Issue by Maxdmn** [BEEmod/BEE2.4#1682]
**BEE2 Version: 4.40.2**

<details>
<summary>Error Log</summary>

VRAD failed.

[I] vrad.main(): BEE2 VRAD hook started!
[I] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad.main(): Loading Settings...
[I] vrad.main(): Reading BSP
[I] vrad.main(): Final status: is_peti=True, edit_args=False
[I] vrad.main(): Done!
[I] vrad.main(): Reading our FGD files...
[I] vrad.main(): Checking for music:
[I] vrad.main(): Run transformations...
[I] bsp_trans.run_transformations(): Running "Attachment Points"...
[I] bsp_trans.run_transformations(): Running "VScript Init Code"...
[I] bsp_trans.run_transformations(): Running "VScript RunScript Inputs"...
[I] bsp_trans.run_transformations(): Running "Proxy limits"...
[I] bsp_trans.run_transformations(): Running "comp_precache_model"...
[I] bsp_trans.run_transformations(): Running "comp_precache_sound"...
[I] bsp_trans.run_transformations(): Running "comp_pack_replace_soundscript"...
[I] bsp_trans.run_transformations(): Running "comp_pack"...
[I] bsp_trans.run_transformations(): Running "comp_pack_rename"...
[I] bsp_trans.run_transformations(): Running "trigger_brush Input Filters"...
[I] bsp_trans.run_transformations(): Running "Fix alternate classnames"...
[I] bsp_trans.run_transformations(): Running "Branch Listener UniqueState"...
[I] bsp_trans.run_transformations(): Running "BEE2: Coop Responses"...
[I] bsp_trans.run_transformations(): Running "BEE2: Cube VScript Filters"...
[I] filter.cube_filter(): Script buffers: []
[I] bsp_trans.run_transformations(): Running "comp_scriptvar_setter"...
[I] bsp_trans.run_transformations(): Running "comp_entity_mover"...
[I] bsp_trans.run_transformations(): Running "Fix Laser Catcher Skins"...
[I] bsp_trans.run_transformations(): Running "Force Paint in Map"...
[I] bsp_trans.run_transformations(): Running "Precache P2 Light Bridge"...
[I] bsp_trans.run_transformations(): Running "comp_choreo_sceneset"...
[I] bsp_trans.run_transformations(): Running "P2 Coop Trigger"...
[I] bsp_trans.run_transformations(): Running "P2 Goo"...
[I] bsp_trans.run_transformations(): Running "Portal 2 Vactubes"...
[I] bsp_trans.run_transformations(): Running "comp_entity_finder"...
[I] bsp_trans.run_transformations(): Running "comp_numeric_transition"...
[I] bsp_trans.run_transformations(): Running "comp_relay"...
[I] bsp_trans.run_transformations(): Running "comp_kv_setter"...
[I] bsp_trans.run_transformations(): Running "Model Ropes"...
[I] bsp_trans.run_transformations(): Running "P2 Antlines"...
[I] bsp_trans.run_transformations(): Running "Optimise logic_auto"...
[I] bsp_trans.run_transformations(): Running "Strip Entities"...
[I] vrad.main(): Scanning map for files to pack:
[W] packlist.pack_fgd(): Unknown keyvalue "flags" for ent of type "logic_auto"!
[W] packlist.pack_fgd(): Unknown keyvalue "InputFilter" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "fadescale" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "inputfilter" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "disablex360" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "fademindist" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "fademaxdist" for ent of type "func_brush"!
[W] packlist.pack_fgd(): Unknown keyvalue "fadescale" for ent of type "linked_portal_door"!
[W] packlist.pack_fgd(): Unknown keyvalue "fademindist" for ent of type "linked_portal_door"!
[W] packlist.pack_fgd(): detail.vbsp file does not exist: "detail.vbsp"
[W] packlist._get_model_files(): Can't find model "models/editor/axis_helper.mdl"!
[W] packlist.pack_soundscript(): Unknown sound "your.soundname"!
[I] vrad.main(): Done!
[I] vrad.main(): Writing to BSP...
[W] packlist.pack_into_zip(): WARNING: "models/editor/axis_helper.mdl" not packed!
[W] packlist.pack_into_zip(): WARNING: "media" not packed!
[W] packlist.pack_into_zip(): WARNING: "media/aperture_appear.bik" not packed!
[W] packlist.pack_into_zip(): WARNING: "detail.vbsp" not packed!
[I] packlist.pack_into_zip(): Compressing packfile...
[I] vrad.main(): Packed files:
 | materials/bee2/clean/black_1x1.vmt
 | scripts/game_sounds_manifest.txt
 | materials/bee2/clean/black_ceil.vmt
 | materials/bee2/tile_noise.vtf
 | scripts/vscripts/bee2/video_splitter_rand.nut
 |___

[I] vrad.dump_files(): Dumping packed files to "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"...
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 16, in <module>
  File "vrad.py", line 297, in main
  File "vrad.py", line 100, in dump_files
PermissionError: [WinError 5] �������� � �������: 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Portal 2\\bin\\binkw32.dll'
[9796] Failed to execute script compiler_launch

</details>

**Additional information:**

**Comment by TeamSpen210** [comment]
It looks like you turned on "dump packed files" in the compiler options, but didn't set a folder - so it's trying to dump in the `bin` folder.

**Comment by Konclan** [comment]
Closing due to lack of info
