### ISSUE TITLE
I need help RIGHT NOW! Please! (Windows Text Error, then the app' deletes itself)

### ISSUE THREAD

**Issue by SuperFlashs** [BEEmod/BEE2.4#1684]
Calm down, calm down... Okay, so:
I have a really big problem that completely blocks me from opening the app'.
I simply Extract the Files with WinRAR into a single file, I open the app', then I get slapped with this message:

So it's in French but i'll Translate it quickly for you guys to help me:

"Windows cannot reach the device, access road or a specified file.
Maybe you do not have the appropriate permissions to have access to the element"

Then after this message, the BEEmod app' just deletes itself.

I explained everything, now what do I do??

**Comment by Konclan** [comment]
Sounds like its your firewall

**Comment by seagemgames** [comment]
It wouldn't be the firewall, that's for network related things. That'll be your anti-virus though.

**Comment by Konclan** [comment]
That's what I meant lmao, sorry. BEEmod is prone to false positives on anti-viruses. Your anti-virus is probably removing the app. 
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#my-anti-virus-program-flagged-bee24-as-malware

**Comment by SuperFlashs** [comment]
I see now! Alright, i'm going to retry WITHOUT the Anti-Virus.

**Comment by SuperFlashs** [comment]
Oh god it finally worked, so it wasn't the Firewall, but the Anti-Virus! Thanks a Lot @seagemgames !
And also @Konclan for the details!
Very nice from you guys!
