### ISSUE TITLE
bee2 wont start even though ive done everything

### ISSUE THREAD

**Issue by j12600** [BEEmod/BEE2.4#1687]
BEE2 will give me an error that I havent put in the packages, even though I have

**Comment by j12600** [comment]
also, this isnt really a bug, but I didnt know what else to tag it

**Comment by CardsAndGamesYT** [comment]
the package folder needs to be named "packages" and nothing else

**Comment by CardsAndGamesYT** [comment]
weird glitch with the newest version

**Comment by FrozenDragon0** [comment]
Please paste the error here... We cannot help you if you don't provide us an error log/screenshot of the issue.

**Comment by CardsAndGamesYT** [comment]
> Please paste the error here... We cannot help you if you don't provide us an error log/screenshot of the issue.

he said it, its saying that there is no packages folder even though there is. the newest beemod does not work unless the packages folder is names "packages". I thought you would have know this...

**Comment by CardsAndGamesYT** [comment]
also i think this is a duplicate

**Comment by FrozenDragon0** [comment]
> > Please paste the error here... We cannot help you if you don't provide us an error log/screenshot of the issue.
> 
> he said it, its saying that there is no packages folder even though there is. the newest beemod does not work unless the packages folder is names "packages". I thought you would have know this...

Ah, didn't read properly, how it feels to read posts early in the morning.

**Comment by CardsAndGamesYT** [comment]
its fine lol, we have all done the same thing
