### ISSUE TITLE
"NotImplementedError: Saving DXT1 not implemented!" Workaround.

### ISSUE THREAD

**Issue by ThaBluNate** [BEEmod/BEE2.4#1689]
OS:  _**windows 10** home_ **_amd64_**

Issue already tracked in #1660, here's a workaround
### **Recommended PKG version:** [4.39.1](https://github.com/BEEmod/BEE2-items/releases/tag/v4.39.1)

These versions do NOT have any setup bugs like not creating the config folder and also let you export

## Extra (for older versions):

BEE Version | Create Config | Export Correctly
------------- | ------------- | -
4.36.* | Yes |  Yes
4.37.* | Yes | Yes
4.38.* | Yes | No
4.39.2 | Yes | Yes
4.40.* | No | No

**Comment by Luke18033** [comment]
Please don't open an issue which literally just tells people to downgrade BEEmod, even if you had a proper workaround you should post it in the comments of the original issue.
