### ISSUE TITLE
on the grating can't put down the cube

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2.4#170]
on the grating can't put down the cube :sob:

**Comment by TeamSpen210** [comment]
Could you take a screenshot? Which gratings?

**Comment by goodDOS** [comment]
@TeamSpen210 I found that the player just jump, cube can put it down. --Use online translation

**Comment by goodDOS** [comment]
@TeamSpen210 
Like this, in a narrow space is grating on both sides.
![img](http://i8.tietuku.com/2d66df845370000f.png)

Unable to put down the cube on the inside.
![img](http://i8.tietuku.com/97d4529fc2fa6fff.png
)
My expression ability is not good, hope to forgive.

--Online translation

**Comment by Konclan** [comment]
I have a feeling this isn't a bug but just a problem with the PeTI and trying to put cubes on top of grates in the editors.

**Comment by TeamSpen210** [comment]
It's actually a different bug, where cubes sometimes collide with invisible walls between gratings.

**Comment by LautaroL20** [comment]
Doesn´t happens to me. Grating have been re-configured since PRL23 btw.
