### ISSUE TITLE
App Crash if i launch it

### ISSUE THREAD

**Issue by Bananchik204** [BEEmod/BEE2.4#1702]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
The App don`t start!

No error messages generated.
FormatMessageW: (text on Russian)
```

**Comment by LautaroL20** [comment]
When the application crashes, it throws an error message, please capture the screen with the key "Impr PetSis" then paste it in Paint and then upload that image, here. Otherwise, we cannot help solving your issue.

**Comment by LautaroL20** [comment]
> What is the Impr PetSis key?

Here is an image, not sure if this key is available in all keyboards though:

![Impr PetSis](https://user-images.githubusercontent.com/12244376/132370346-d6bb41d1-96d6-4d34-b4fd-9b56423706a2.jpg)

**Comment by Luke18033** [comment]
Ah interesting, sounds like it might just be a translated label for print screen.

**Comment by Defeatomizer** [comment]
I have quite similar problem.
The program archive currently comes without `api-ms-win-core-path-l1-1-0.dll` library, which is getting required by `python39.dll` loader:
![image](https://user-images.githubusercontent.com/71347607/132998151-f0e3d656-5941-4d00-aaf2-d8bf686fd48c.png)
>Program launch is not possible, because api-ms-win-core-path-l1-1-0.dll
is missing on this device. Try to reinstall the program.

If I download this file from any website and place it in the BEEMod directory, it does not fix the issue either:
![image](https://user-images.githubusercontent.com/71347607/132998181-73ed38f7-6551-4d99-a683-05b4c9d8542b.png)
>No error messages generated.
FormatMessageW: The argument is set incorrectly.

I also noticed that all built-in libraries are about 10-15 KB in size, meanwhile `api-ms-win-core-path-l1-1-0.dll`'s size is only 3 KB.

**Comment by LautaroL20** [comment]
Closing because the issue's author doesn't respond.
