### ISSUE TITLE
Glasses look strange

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2.4#1704]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

All glasses look strange
![image](https://user-images.githubusercontent.com/88097966/132411513-425a51e8-b3c3-400b-a666-a23dd1310f6f.png)

### Expected behavior

Glasses are still normal, as in the first gameplay

### Steps to reproduce

I start the map a second time and then this happens

**Comment by Luke18033** [comment]
This is a Valve bug, for some reason when you load the map after the first time it's missing cubemaps. Although Hammer maps don't have this issue (even ones without their proper cubemaps built), so maybe this is fixable?

**Comment by CN1o2** [comment]
But will this problem prevail when the map is public?

**Comment by Luke18033** [comment]
No, it only applies in preview mode.

**Comment by CN1o2** [comment]
Thank God

**Comment by CN1o2** [comment]
well, i'll close this here

**Comment by FrozenDragon0** [comment]
And you posted in the wrong section.
