### ISSUE TITLE
BEEmod 4.41-beta3: Occasional crash after exporting

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1709]
### BEE2 Application Version

4.41-beta3 32-bit

### BEE2 Package Version

4.41-beta3

### What operating system are you running on?

Windows 7 (64bit)

### Description of the issue:

**After exporting, the application will throw a second "launch game?" message after the first one, then once you click "yes" or "no", the app will crash. For this process, I had unchecked the option "Preserve Game Directories" ...**

```shell
[INFO] gameMan.export(): Optimizing editor models...
[INFO] gameMan.clean_editor_models(): 264/317 (83%) editor models used.
[INFO] gameMan.export(): Writing fizzler sides...
[INFO] resource_gen.make_cube_colourizer_legend(): Exporting "d:\steam\steamapps\common\portal 2\bee2\materials\BEE2\models\props_map_editor\cube_coloriser_legend.vtf"...
[INFO] gameMan.export(): Writing bee2/materials/BEE2/models/props_map_editor/signage/signage.vtf...
[INFO] paletteLoader.save(): Saving "<Ultima Exportación>"!
[INFO] BEE2_config.save(): Saving changes in config "C:\Users\Lautaro\AppData\Roaming\BEEMOD2\config\config.cfg"!
[ERROR] __init__.tk_error(): Uncaught Exception:
Traceback (most recent call last):
  File "app\UI.py", line 925, in export_editoritems
ValueError: <app.paletteLoader.Palette object at 0x02774A48> is not in list
```

### Additional information:

**Video showing the process until the crash occurs:**

https://user-images.githubusercontent.com/12244376/132905838-bca6766a-f951-4567-89f8-f1475acea82b.mp4

### Image showing the crash message:
![BEEmod Beta 3 will throw a duplicate launch game message, then once you click on yes or no, the app will crash](https://user-images.githubusercontent.com/12244376/132906449-a59a12a4-9bf9-4b96-ac2c-25505bef2a87.png)

### Complete log file:
[bee2.log](https://github.com/BEEmod/BEE2.4/files/7145925/bee2.log)

**Comment by Luke18033** [comment]
Seems like it's exporting twice for some reason?

**Comment by LautaroL20** [comment]
Not sure what would cause this to happen, but that could be a reason. I have attached a video in the description if you want to replicate this issue on your own.

**Comment by TeamSpen210** [comment]
Yeah it looks like it exported twice, you can see two loadscreens. I guess I need to lock out the button temporarily.

**Comment by LautaroL20** [comment]
Fixed in RC3.
