### ISSUE TITLE
python39.dll requires missing library

### ISSUE THREAD

**Issue by Defeatomizer** [BEEmod/BEE2.4#1710]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
(Screenshots have logs, but I guess this section doesn't render them, so pasting reports here)
The program archive currently comes without `api-ms-win-core-path-l1-1-0.dll` library, which is getting required by `python39.dll` loader (1st screenshot).
If I download this file from any website and place it in the BEEMod/ and BEEMod/compiler/ directories, it does not fix the issue either (2nd screenshot).
```

### Additional information

Without `api-ms-win-core-path-l1-1-0.dll`:
![image](https://user-images.githubusercontent.com/71347607/132998151-f0e3d656-5941-4d00-aaf2-d8bf686fd48c.png)
>Program launch is not possible, because api-ms-win-core-path-l1-1-0.dll
is missing on this device. Try to reinstall the program.

With `api-ms-win-core-path-l1-1-0.dll`:
![image](https://user-images.githubusercontent.com/71347607/132998181-73ed38f7-6551-4d99-a683-05b4c9d8542b.png)
>No error messages generated.
FormatMessageW: The argument is set incorrectly.

I noticed that all built-in libraries are about 10-20 KB in size, meanwhile `api-ms-win-core-path-l1-1-0.dll`'s size is only 3 KB.
I also tried to un-dll it using free version of a decompiler, and it said the library is corrupted.

**Comment by Luke18033** [comment]
You need to use the 32-bit version on Windows 7. Should probably rename it to `compat` or something to make that more clear.

**Comment by Defeatomizer** [comment]
Thanks, it works.
