### ISSUE TITLE
A "rulefree" mode

### ISSUE THREAD

**Issue by slambo312** [BEEmod/BEE2.4#1713]
### Description of the feature

Obviously, it'd be incredibly glitchy, but it would make it so basically you could place stuff inside of each other (ex: observation room inside of the elevator room).

### Why should this be implemented

I honestly don't know why it should be in, I just thought of it and I was like "Hey, it'd be really funny to see it actually in there".

### Additional information

Maybe also an option related to it that controls whether or not objects would still work when placed in goo.

**Comment by Luke18033** [comment]
I asked for this option many times. It's not really possible unfortunately.
