### ISSUE TITLE
GLaDOS P1 Lines

### ISSUE THREAD

**Issue by CN1o2** [BEEmod/BEE2.4#1716]
If you ever add the voice of Glados de P1, I have an idea of ​​what it would be like:

**When passing through the flizzer**

"First, however, note the incandescent particle field across the exit." "This Aperture Science Material Emancipation Grid will vaporize any unauthorized equipment that passes through it - for instance, the Aperture Science Weighted Storage Cube."

**High energy pellet present in chamber**

**Entry**

"Audible warning devices are required on all mobile equipment. However, alarms and flashing hazard lights have been found to agitate the high energy pellet and have therefore been disabled for your safety."

"While safety is one of many Enrichment Center goals, the Aperture Science High Energy Pellet, seen to the left of the chamber, can and has caused permanent disabilities such as vaporization." Followed (or not) with: "Please be careful."

"All subjects intending to handle high-energy gamma leaking portal technology must be informed that they MAY be informed of applicable regulatory compliance issues." Followed with: "No further compliance information is required or will be provided, and you are an excellent test subject!"

**Exit**

"Unbelievable ! You, [louder] Subject Name Here[/louder], must be the pride of [louder]Subject Hometown Here[/louder]."

"Did you know you can donate one or all of your vital organs to the Aperture Science self esteem fund for girls? It's true!"

**Deadly mechanics present in the chamber (such as lasers, high pellets, etc.):**

**Entry**

"The Enrichment Center regrets to inform you that this next test is impossible."
30% chance of being followed with:"Make no attempt to solve it." or 
"Frankly, this chamber was a mistake. If we were you, we would quit now." 
If she says the previous line, it will be followed with: "No one will blame you for giving up. In fact, quitting at this point is a perfectly reasonable response.

**Entry or Exit**

"Please note that we have added a consequence for failure. Any contact with the chamber floor will result in an 'unsatisfactory' mark on your official testing record followed by death. Good luck!"

**Panels, Aerial Faith Plate, Repulsion gel and Propusion Gel presents in the chamber**

**Entry**

"Hello again. To reiterate our previous warning, this test requires a mastery of the principles of portal momentum."
"Get ready to fling yourself. Fling into space."

**Exit**

"Spectacular. You appear to understand how a portal affects forward momentum, or to be more precise, how it does not."
"Yeeeeeeeeeeeeee [bzzzt]"

**Turrets present in chamber**

**Entry**

"Due to mandatory scheduled maintenance, the appropriate chamber for this testing sequence is currently unavailable." followed "It has been replaced with a live-fire course designed for military androids." 
A great chance to be followed with "The Enrichment Center apologizes for the inconvenience and wishes you the best of luck."

**Exit**

"Very impressive. Please note that any appearance of danger is merely a device to enhance your testing experience."
"Well done, android. The Enrichment Center once again reminds you that android hell is a real place where you will be sent at the first sign of defiance."

**Unstationary Scaffold When activated**

"Good. Now use the Aperture Science Unstationary Scaffold to reach the chamberlock."

**Toxic goo**

**Entry**

"Please note that we have added a consequence for failure. Any contact with the chamber floor will result in an 'unsatisfactory' mark on your official testing record followed by death. Good luck!"
"The Enrichment Center promises to always provide a safe testing environment." Followed with "In dangerous testing environments, the Enrichment Center promises to always provide useful advice." 
and ending with a "For instance, the floor here will kill you - try to avoid it."

**Get the portal gun from only one portal**

"Very good! You are now in possession of the Aperture Science Handheld Portal Device." followed with "With it, you can create your own portals."

**Get the double gun portal**

"The Device has been modified so that it can now manufacture two linked portals at once."

**Spawn Companion or Pick up**

"This Weighted Companion Cube will accompany you through the test chamber. Please take care of it."

**Companion Incinerate**

"You euthanized your faithful Companion Cube more quickly than any test subject on record. Congratulations."

**Generic**

**Entry**

"Please place the Weighted Storage Cube on the Fifteen Hundred Megawatt Aperture Science Heavy Duty Super-Colliding Super Button."
"Welcome to test chamber four."
"Now that you are in control of both portals, this next test could take a very, VERY, long time."
"The Enrichment Center is committed to the well being of all participants." followed with "Cake and grief counseling will be available at the conclusion of the test." and "Thank you for helping us help you help us all."
"The experiment is nearing its conclusion." followed with "The Enrichment Center is required to remind you that you will be baked, and then there will be cake."
"Welcome to the final test!"

**Entry or exit**

"Please proceed to the chamberlock. Mind the gap."

**Exit**

"Excellent. Please proceed into the chamberlock after completing each test."
"Well done! Remember: The Aperture Science Bring Your Daughter to Work Day is the perfect time to have her tested."
"Well done! Be advised that the next test requires exposure to uninsulated electrical parts that may be dangerous under certain conditions." followed with: "For more information, please attend an Enrichment Center Electrical Safety seminar."
"As part of a required test protocol, our previous statement suggesting that we would not monitor this chamber was an outright fabrication."followed with:"Good job! As part of a required test protocol, we will stop enhancing the truth in three... Two... One." or "As part of a required test protocol, we will not monitor the next test chamber. You will be entirely on your own. Good luck."(The player who will decide which of the two options will use)

**Comment by Luke18033** [comment]
We can't port the original voice lines, if we could then P1 GLaDOS would have been implmented a long time ago. Please read the [FAQ](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md).

**Comment by CN1o2** [comment]
The only thing I don't understand is, why?

**Comment by Luke18033** [comment]
> Please read the [FAQ](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md).
