### ISSUE TITLE
[dev] App crashes if user tries to press '...' button in "Dump packed files to"

### ISSUE THREAD

**Issue by shaperones0** [BEEmod/BEE2.4#1718]
### BEE2 Application Version

dev

### BEE2 Package Version

dev

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "tkinter\__init__.py", line 814, in callit
  File "bg_daemon.py", line 772, in check_queue
  File "multiprocessing\connection.py", line 262, in poll
  File "multiprocessing\connection.py", line 333, in _poll
BrokenPipeError: [WinError 109] The pipe has been ended
```

### Additional information

this button:
![image](https://user-images.githubusercontent.com/86309764/133963432-7b0767ac-2951-4961-aaaf-db767cff918e.png)

**Comment by TeamSpen210** [comment]
This is very bizarre, Tk just freezes when the call is made...

**Comment by Luke18033** [comment]
It's not actually fixed yet, we're just not going to worry about this for 4.41 since it's not really a major issue.

**Comment by Luke18033** [comment]
Actually it does seem to be fixed

**Comment by TeamSpen210** [comment]
I did a workaround, switched to a ‘load file’ dialog. Which does entirely the wrong thing.

**Comment by Laudanum-dev** [comment]
> Actually it does seem to be fixed, just no commit reference
and no actual commit as well.. (the issue persists on latest dev build)

**Comment by Luke18033** [comment]
I couldn't reproduce it...regardless, it's not important enough to delay the entire release. Most people won't use this feature, and the people who do can just set the path in the config file manually.
