### ISSUE TITLE
Separate config folders for each app version

### ISSUE THREAD

**Issue by Laudanum-dev** [BEEmod/BEE2.4#1719]
### Description of the feature

Separate config folders for each app version.
## How it works
Files will look something like this 
```
%APPDATA%\Roaming\BEEMOD2\
                         | BEE2.4.41.2\
                                      | config\
                                              | compile.cfg
                                              | config.cfg
                                              ...
                                      | palettes
                                      ...
                         | BEE2.4.42.0\
                                      | config\
                                              | compile.cfg
                                              | config.cfg
                                              ...
                                      | palettes
                                      ...
                          ...
```
when a new version is launched, it will look for it's config folder, and if fails, it will try to inherit configs from the highest version number, lower than the one we launching
for example if we have configs for BEE2.4.41.0, BEE2.4.41.1 and BEE2.4.43.0, if we launch BEE2.4.42.0, it will look for folder with highest version < 4.42.0, will find the one that BEE2.4.41.1, and copy (or do some smarter inheritance) it with the name BEE2.4.42.0

if the app fails to find its config and config of lower version, it will create a brand new config folder for itself

### Why should this be implemented

this may be helpful when new huge features will be added to the app (such as chamber exterior / changing gui engine in app / linking entites in vbsp_config (i believe this feature will be followed with rewriting many 'hardcoded' entries in beemod)) as well as changes / additions in configs format. the feature will allow users easily switch between newer unstable versions and older more stable ones, without worrying about changing settings in app every time user switches version. also this may be useful for beta testers and dev testers for the similar reason if they want to keep settings in beta separate from settings in stable.

### Additional information
cons: 
1) may result in clutter in files, if we decide to store bulkier information in configs

**Comment by TeamSpen210** [comment]
I'm not really sure this is necessary. The configuration formats actually has had almost no actual breaking changes, and when changes occur I keep backwards compatibility logic in the app. For instance you can still load BEE2.2 palette files, and they'll bring up the right items (except for those that have been removed). If I do need to migrate things, I can just add a version number to the specific config file.

**Comment by Laudanum-dev** [comment]
hmm, okay then
