### ISSUE TITLE
Preserve funnel music, bounce music, speed music selections when collapsed

### ISSUE THREAD

**Issue by Laudanum-dev** [BEEmod/BEE2.4#1722]
### BEE2 Application Version

dev (almost latest commit)

### BEE2 Package Version

dev (almost latest commit)

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

funnel music, bounce music, speed music can't be changed in app.
when i try to change it, then collapse their drop-down, and expand it back, the music remains the unchanged. 
it also affects the music configuration that will be exported, i can change base track, but i can't change the separate tracks so they will play what is default for the base track i set. the only way to do this is to change default configuration of this base track in the pack's files. 
**btw** the issue doesn't happen when i try to change the track that the base doesn't have defaults for.
for example if i select "Alt Sys Corruption" (this one doesn't have any default track for 'bounce') from Mel soundtrack and change the bounce music for it, it will be changed the way it should.

video showing the issue:

https://user-images.githubusercontent.com/86309764/134770836-439683d9-658d-490b-922a-7eeeb06bbd57.mp4

 

### Expected behavior

those music tracks are changed in the app if i collapse and expand the drop-down as well as it changes the configuration to be exported

### Steps to reproduce

1) launch app
2) select the base track that has it's funnel / bounce / speed music
3) try to change the music for funnel / bounce / speed music (you must change the one that appears in app in **bold**)
4) collapse and expand back the drop-down (the one that you use to access these separate tracks 
5) see the music in funnel / bounce / speed doesn't changed  .

### Logs and Reports

these i got when i was playing around while trying to record a video
```
[D] selector_win.save(): Storing window state "music_speed" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'portal stories: mel': True}, width=689, height=358)
[D] selector_win.save(): Storing window state "music_bounce" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'peti / robo room': True}, width=731, height=358)
[D] selector_win.save(): Storing window state "music_tbeam" = WindowState(open_groups={'': True, 'wheatley': True, 'reconstructing': True, 'portal stories: mel': True, 'old aperture': True}, width=689, height=378)
[D] selector_win.save(): Storing window state "music_base" = WindowState(open_groups={'': True, 'portal pro': True, 'rexaura': True, 'reconstructing': True, 'portal 1': True, 'bts': True, 'portal stories: mel': True, 'old aperture': True, 'wheatley': True, 'overgrown': True, 'peti / robo room': True}, width=719, height=616)
[D] selector_win.save(): Storing window state "music_tbeam" = WindowState(open_groups={'': True, 'wheatley': True, 'reconstructing': True, 'portal stories: mel': True, 'old aperture': True}, width=689, height=378)
[D] selector_win.save(): Storing window state "music_bounce" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'peti / robo room': True}, width=731, height=358)
[D] selector_win.save(): Storing window state "music_speed" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'portal stories: mel': True}, width=689, height=358)
[D] selector_win.save(): Storing window state "music_base" = WindowState(open_groups={'': True, 'portal pro': True, 'rexaura': True, 'reconstructing': True, 'portal 1': True, 'bts': True, 'portal stories: mel': True, 'old aperture': True, 'wheatley': True, 'overgrown': True, 'peti / robo room': True}, width=719, height=616)
[D] selector_win.save(): Storing window state "music_base" = WindowState(open_groups={'': True, 'portal pro': True, 'rexaura': True, 'reconstructing': True, 'portal 1': True, 'bts': True, 'portal stories: mel': True, 'old aperture': True, 'wheatley': True, 'overgrown': True, 'peti / robo room': True}, width=719, height=616)
[D] sound.play_sample(): Loading music directly from 'C:\\Prog\\_repo\\beemod\\BEE2.4\\dist\\64bit\\BEE2\\packages\\music\\p1_music\\resources/music_samp/p1/android_hell.ogg'
[D] selector_win.save(): Storing window state "music_base" = WindowState(open_groups={'': True, 'portal pro': True, 'rexaura': True, 'reconstructing': True, 'portal 1': True, 'bts': True, 'portal stories: mel': True, 'old aperture': True, 'wheatley': True, 'overgrown': True, 'peti / robo room': True}, width=719, height=616)
[D] selector_win.save(): Storing window state "music_speed" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'portal stories: mel': True}, width=689, height=358)
[D] selector_win.save(): Storing window state "music_base" = WindowState(open_groups={'': True, 'portal pro': True, 'rexaura': True, 'reconstructing': True, 'portal 1': True, 'bts': True, 'portal stories: mel': True, 'old aperture': True, 'wheatley': True, 'overgrown': True, 'peti / robo room': True}, width=719, height=616)
[D] selector_win.save(): Storing window state "music_bounce" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'peti / robo room': True}, width=731, height=358)
[D] selector_win.save(): Storing window state "music_speed" = WindowState(open_groups={'': True, 'reconstructing': True, 'bts': True, 'wheatley': True, 'old aperture': True, 'portal stories: mel': True}, width=689, height=358)
[D] selector_win.save(): Storing window state "music_tbeam" = WindowState(open_groups={'': True, 'wheatley': True, 'reconstructing': True, 'portal stories: mel': True, 'old aperture': True}, width=689, height=378)
```

### Additional information

i'm pretty sure that this issue has been already reported, but the last time i remember seeing this was pretty long time ago and the issue is still here even on latest dev version, so maybe im wrong about this being reported some time ago

**Comment by TeamSpen210** [comment]
Maybe I should tweak how it stores so it doesn't discard, but this is intentional. The arrow controls basically if you're in "basic" music mode (where you select the base track and the others are automatic), and "advanced" where you select all of them. So when you collapse the defaults are chosen. I should switch the code so it doesn't unselect your configured ones, but just ignores them during export.

**Comment by Laudanum-dev** [comment]
well then i think i can close this issue

**Comment by SCIENTIST2004** [comment]
Where does everyone take dev versions from?

**Comment by FrozenDragon0** [comment]
@SCIENTIST2004 From the beta testing channel on the discord, only select people have access to the beta testing channel.

**Comment by SCIENTIST2004** [comment]
@FrozenDragon0 
Can I have it?

**Comment by FrozenDragon0** [comment]
> @FrozenDragon0 Can I have it?

Not my decision to choose who gets access to the beta channel.
