### ISSUE TITLE
BEEmod 4.41-beta5: Any item that have a subtype property will appear using the combined icon instead of using the singular one in the BEEmod palette 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1731]
### BEE2 Application Version

4.41-beta5 32-bit

### BEE2 Package Version

4.41-beta5 

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

On BEEmod´s launch, any item that have a subtype property will appear using the combined icon instead of using the singular one for when there are present more than 1 item from a subtype property in the BEEmod palette:

![Image](https://user-images.githubusercontent.com/12244376/136674776-f53782fd-3c89-4c3d-9aaa-b3d05ee37fc7.png)

### Expected behavior

Vanilla items must use the singular icon for when there are present more than 1 item from a subtype in the BEEmod palette.

### Steps to reproduce

Launch BEEmod 4.41-beta5 and if more than 1 item from a subtype in the BEEmod Palette, you will notice how these appears using the combined icon instead of using the singular icon.

### Logs and Reports

```shell
None.
```

### Additional information

This happens at the application launch.

**Comment by Luke18033** [comment]
I can't reproduce this, might be specific to the Windows 7 version?

**Comment by LautaroL20** [comment]
Maybe, I can record a short video showing the issue if necessary though.

**Comment by LautaroL20** [comment]
According to Konclan, this can also happens with other vanilla items such as Cube buttons and Floor buttons. Here is his message from #admin-general:  

> "I build BEE, this is what the first export always looks like - Changing pallets fixes the issue but why is it happening:"

![Image](https://user-images.githubusercontent.com/12244376/136671212-4d67d678-ee0e-4490-add0-edb7fc214b78.png)

So, I have updated the issue´s title and desc.

**Comment by LautaroL20** [comment]
I just did more testing and this definitelly happens with any item (not only vanilla ones) that have a subtype property, they will appear using the combined icon instead of using the singular one for when there are present more than 1 item from a subtype property in the BEEmod palette, the following image says it all:

![Image](https://user-images.githubusercontent.com/12244376/136674776-f53782fd-3c89-4c3d-9aaa-b3d05ee37fc7.png)
