### ISSUE TITLE
BEEmod 4.41-beta5: Selecting a grouped palette from the Palette menu bar dropdown crashes the app

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1732]
### BEE2 Application Version

4.41-beta5 32-bit

### BEE2 Package Version

4.41-beta5 

### What operating system are you running on?

Windows 7 (64bit)

### Description of the issue

![BEEmod palettes stop working the app](https://user-images.githubusercontent.com/12244376/136463994-093b7e17-dd8f-440f-8cf4-5a0d5bd8d6f6.png)

**The following crash message will occur once you close the application via task manager or through the "has stop working" window:**

![BEEmod BrokenPipeError;  WinError 109  has finished the  canalization](https://user-images.githubusercontent.com/12244376/136464227-b717dd50-1c1a-4844-bac4-22fb6204de0d.png)

### Logs and Reports

Unfortunately, once the application throw the crash message after you close it, will not produce any related info about the crash on the logs... but I have posted a screenshot of the crash message though.

**Comment by Luke18033** [comment]
It crashes if you select a grouped palette through the menu bar, if you select it in the separate palettes window it works fine

**Comment by TeamSpen210** [comment]
That’s unfortunately a red herring error message, it’s from the loadscreen half of the app loosing communication with the main part after that failed. There should be something in the log files?

**Comment by TeamSpen210** [comment]
Confirmed this happens, weird.
