### ISSUE TITLE
Custom palette groups don't save

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1733]
### BEE2 Application Version

Dev

### BEE2 Package Version

Dev

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Custom palette groups don't save properly, and become ungrouped again after restarting the app.

### Expected behavior

Custom palette groups should save

### Steps to reproduce

1. Move some custom palettes into a group
2. Restart the app
3. The palettes are ungrouped again

**Comment by TeamSpen210** [comment]
Hmm, maybe I didn’t tell it to re-save? What happens if you save the palette again?

**Comment by TeamSpen210** [comment]
Great job me, I forgot to make the palette save code actually write the group into the file...
