### ISSUE TITLE
BEEmod 4.41-beta5 can't read music previews from zips

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1734]
### BEE2 Application Version

4.41-beta5 32-bit

### BEE2 Package Version

4.41-beta5 

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

**All the songs preview (including the ones from Funnel, Bounce and Speed gel) can not be hear when you hit the play button.**

### Expected behavior

Music preview should be able to reproduce the song.

### Steps to reproduce

Launch the Windows 7/8.1 Application version of BEEmod and then open the panel of any music preview and hit the play button there, music can not be hear...

### Logs and Reports

```shell
None.
```

### Additional information

Using the 32 bit Application (the Windows 7/8.1 version).

**Comment by LautaroL20** [comment]
After doing further testing I can also confirm that the Funnel, Bounce and Speed gel music previews cannot be heard either... so, actually there is no song that can be hear after click the preview play button.

**Comment by LautaroL20** [comment]
Sounds effect works pretty well though.

**Comment by slambo311** [comment]
Well, you're using the 32-bit version on a 64-bit computer, so that might be the problem. Probably not, though.

**Comment by LautaroL20** [comment]
No, the 64-bit BEEmod version is for Windows 10, only. And the 32-bit BEEmod version is for Windows 7/8.1, regardless if your OS is 32 or 64 bit. I think that when a new BEEmod release is out, the download section instead of say 32-bit version, it should say Windows 7/8.1 BEEmod version, and instead of 64-bit it should say Windows 10 BEEmod version so it will stop people´s confusion.

**Comment by Luke18033** [comment]
Yeah it's a little confusing, I'd label the 32-bit version as the "compatibility" version on the release pages.

**Comment by LautaroL20** [comment]
> Luke18033 said: "Yeah it's a little confusing, I'd label the 32-bit version as the "compatibility" version on the release pages."

"Windows 7/8.1 compatibility version" - would be better maybe? The more specific it is, the less people will get confused.

**Comment by Luke18033** [comment]
Well if you have 32-bit Windows 10, you'd also need it.

**Comment by Luke18033** [comment]
Seems like the issue here is actually that it can't read music from zips.

**Comment by Luke18033** [comment]
Seems to be fixed now, @LautaroL20 can you test this on Windows 7 once the next build is up? (It should be soon)

**Comment by LautaroL20** [comment]
Sure, as soon as TeamSpen posts the link on the beta-builds channel I will give it a test.
