### ISSUE TITLE
Running BEE2 Maps in Hammer does not work. I need help!

### ISSUE THREAD

**Issue by DatPerkYT** [BEEmod/BEE2.4#1741]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### Description of the bug

When i export a BEE2 map to Hammer, this message shows up: Could not open instance file instances/BEE2/clean/elevator_sp/door_frame_black.vmf. I was really angry because i worked a few days on this project, i just took the basic room, made a chamber, and put it into hammer. then i made a cool escape scene. Anyways, How do i fix this?!?!

### Expected behavior

i expected the map to run, i had no leaks, everything was fine until that message appeared.

### Steps to reproduce

Step 1. Find what is causing this to happen.
Step 2. Please tell me how to fix it.

### Logs and Reports

```shell
Could not open instance file instances/BEE2/clean/elevator_sp/door_frame_black.vmf
```

### Additional information

Using Most updated version of Hammer, i exported the map to it, and that showed up.

**Comment by Luke18033** [comment]
You can't use `puzzlemaker_export` with BEE maps, please check the FAQ for the proper way to do it.

Note that exporting Puzzlemaker maps to Hammer is also generally considered bad practice, especially if you intend to make significant changes like changing the style.
