### ISSUE TITLE
BEE2 Won't Launch

### ISSUE THREAD

**Issue by PixelPerfectGitHub** [BEEmod/BEE2.4#1744]
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Opening the BEE2 application gives me this error message before giving me the message "Failed to execute script BEE2_launch":
![2021-10-22 (2)](https://user-images.githubusercontent.com/83557146/138572318-b37b596d-374f-4ac1-a9d0-bebb032e6fc1.png)

### Expected behavior

I expect the application to ask me to find the game I want to pair it with.

### Steps to reproduce

Download the Application folder (Version 4.40.2) and extract it. Keep the extracted folder in the downloads folder. Download the items package (Version 4.40.0) and create a packages folder in the application folder. Take all the .bee_pack files from the items folder and place them in the packages folder in the application folder. Launch the executable.

**Comment by PixelPerfectGitHub** [comment]
Creating a config folder didn't work.

**Comment by Konclan** [comment]
Did you put it in "C:/Users/roryw/AppData/Roaming/BEEMOD2"
Is it named exactly "config"

**Comment by PixelPerfectGitHub** [comment]
Lautarol told me to post the issue in a different section of the Github page. There might've been some confusion, and I apologize for that.

**Comment by PixelPerfectGitHub** [comment]
Oh there we go. I accidentally went to the AppData folder on OneDrive. Whoops. Okay you can close the issue now.
