### ISSUE TITLE
Portal Reloaded music Built into BEE2

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1745]
### Description of the feature

I think it would be nice to have Portal Reloaded music be built into BEE2, so you don't have to spend time importing it through BMMC2 and then manually configuring it.

### Why should this be implemented

It would be very comfortable as a built-in feature.

**Comment by CN1o2** [comment]
Although I'm not a supporter of bee2, I think it would be a good idea to add them. Because the songs from Portal Reloaded are wonderful!

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2-music#2
