### ISSUE TITLE
BEEmod Release Candidate 2: Some icons from the app can occasionally appears missing.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1755]
### BEE2 Application Version

RC2 32bit

### BEE2 Package Version

RC1

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

This can actually happen with any icon from the application.

![Selection style missing icon](https://user-images.githubusercontent.com/12244376/140640002-a4bfc7f1-1d98-4cea-a927-09c036c7e2b4.png)

### Expected behavior

Those icons should appear fine.

### Steps to reproduce

Launch the BEEmod release candidate 2 and you´ll see the missing icons.

**Comment by LautaroL20** [comment]
This suddenly got mysteriously fixed after restarting the app or by re-installing it.

**Comment by LautaroL20** [comment]
Okay, after doing furter testing this still happens but occasionally, and can actually occur with any icon at each app´s launch. This issue was probably introduced as a consequence of fixing: https://github.com/BEEmod/BEE2.4/issues/1731 

Another screenshot: 
![Selection style missing icon](https://user-images.githubusercontent.com/12244376/140639834-ef896dca-5194-4e43-b597-420690c8a124.png)

**Comment by LautaroL20** [comment]
I think I should fix the title to BEEmod release candidate 2.

**Comment by TeamSpen210** [comment]
This is likely the same cause as #1756, I think.

**Comment by Luke18033** [comment]
Since that issue is fixed, this should be as well.

**Comment by LautaroL20** [comment]
Seems fixed in RC3.
