### ISSUE TITLE
BEEmod Release Candidate 2: Building a chamber with or without items will cause "Failure To Compile".

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1762]
### BEE2 Application Version

RC2 32bit

### BEE2 Package Version

RC1

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

Building a chamber with or without items will cause a compile error and this happens using any Style.

### Expected behavior

Chambers must compile.

### Steps to reproduce

Export anything to the game and then try building a chamber, you will see that it will cause a compile error.

### Logs and Reports

```shell
VRAD failed.

[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "vrad.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "srctools\packlist.py", line 171, in <module>
  File "srctools\packlist.py", line 182, in ManifestedFiles
TypeError: 'type' object is not subscriptable
[688892] Failed to execute script 'compiler_launch' due to unhandled exception!
```

**Comment by Laudanum-dev** [comment]
hmm my latest build compiles maps with no issues ...

**Comment by LautaroL20** [comment]
You are lucky then.

**Comment by Laudanum-dev** [comment]
are your previous installation compiled maps correctly? because it looks like there were no changes to compiler or items in dev branch, so if the rc2 is doesnt have any unpushed changes in it, there might be issues on your side

**Comment by LautaroL20** [comment]
> Laudanum-dev said: "are your previous installation compiled maps correctly? because it looks like there were no changes to compiler or items in dev branch, so if the rc2 is doesnt have any unpushed changes in it, there might be issues on your side"

No, I even make sure to do a 100% clean install of the RC2 and it still happens, it also worths to mention that this also happens with RC1 as well. Hoever, when I downgrade to a previous beta build, it compiles fine. My hypothesis is that when TeamSpen builded both RC1 and RC2 for the beta-testers, something got damaged in the process and thats why this does not happens to you too.


> Laudanum-dev also said:  "btw im not "beta tester" in server so i dont have access to beta channels"

You should, as you are an active member in the BEEmod Discord server who have experience using BEEmod and how it behaves. If I could, I would give you the Beta-Tester role but that feature can be given by Konclan I think.

**Comment by Laudanum-dev** [comment]
hmm, my guess of what is the source of issue, the error happens on vrad.exe, so most likely it happens on postcompiller, which utilizes srctools library. The dev build i have uses srctools v2.2.0 from pypi, and the builds compiled by teamspen use his most recent version of srctools (i guess for him it is easier to not explicitly install his own library from pypi when he can just use the one that he is working on) . the thing of most recent version of srctools is that it might have some bugs and errors that were introduced after spen pushed 2.2.0 to pypi. so those errors are shipped into RC2. 

well, thats my guess

**Comment by Laudanum-dev** [comment]
well this is where the error is being thrown
![image](https://user-images.githubusercontent.com/86309764/140913910-76d793ca-6fb0-49f4-8ce2-12def393c3d2.png)

i guess here `dict[str, tuple[str, ParsedT]]` python dont like that you try to subscript a builtin type (so things like `dict[...]` or `tuple[...]` are  should be changed to `typing`'s Dict and Tuple (as well as all similar occurrences below) 

although for some reason when i type similar things into python's IDLE it goes ok 
![image](https://user-images.githubusercontent.com/86309764/140914647-d1937c2e-6e31-4b60-995a-4332e709d296.png)

**Comment by TeamSpen210** [comment]
It's valid syntax in Python 3.9+, but this is only actually used by type checkers so it's okay to use in earlier versions if it's not actually executed.

**Comment by Laudanum-dev** [comment]
good to know. 
as i see, the issue is fixed now

**Comment by Luke18033** [comment]
Can reproduce this on 4.41 RC2 32-bit. Not sure about the 64-bit build since I apparently can't run it? It works fine in 64-bit dev builds I compile myself though.

**Comment by Luke18033** [comment]
Oh I just reread the above comments, if it's specific to Python 3.8 then it'd only happen in the 32-bit version

**Comment by LautaroL20** [comment]
Fixed in RC3.
