### ISSUE TITLE
Dragged items don't appear on the cursor

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1764]
### BEE2 Application Version

Dev

### BEE2 Package Version

Dev

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When dragging an item to or from the palette, it no longer appears on the cursor. The palette position indicator still appears, and the cursor changes.
![image](https://user-images.githubusercontent.com/19228201/141367005-4c929fb5-2ac5-4f17-b1ae-70882b32671e.png)

### Expected behavior

The item should appear on the cursor

### Steps to reproduce

1. Open BEE2
2. Grab an item

### Additional information

Also happens in 4.41 RC2

**Comment by LautaroL20** [comment]
Fixed in RC3.
