### ISSUE TITLE
Broken chambers

### ISSUE THREAD

**Issue by LazyPlaying** [BEEmod/BEE2.4#1768]
### BEE2 Application Version

4.39.1

### BEE2 Package Version

4.39.1

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I'm doing a test chamber, And if it clear or full when I'm trying to try it happens: Elevator don't work and props too, props and entities are broken. I tried to change versions of beemod, but nothing helped
![Скриншот_2021_11_14_14_32_17_750](https://user-images.githubusercontent.com/94288255/141675730-3c8082d1-39c6-4e6b-b809-6b291fe23cb8.jpg), i will add i'm russian

### Expected behavior

When I tried to clear packages (In BEE2 options) i thought it ended, but nothing changes.
Same happened when I tried to change version

### Steps to reproduce

I don't know what caused this bug

### Logs and Reports

```shell
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 23 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 3529 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 3661 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 17317 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 17590 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
CSoundEmitterSystemBase::GetParametersForSound:  No such sound music.BEE2
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
Updating sound cache [9428 entries]
Found 9399 sound files on disk
Updated 0 out of 9399 cached files [494.082 msec]
Redownloading all lightmaps
-------
Scaling type: 13
-------
I don't know what that means
```

### Additional information

I'm using clean style without extra packages

**Comment by TeamSpen210** [comment]
This happens if your FGD files are invalid or missing. Try verifying your game cache, and the Authoring Tools if you have those to see if that fixes it. You'll need to export again from BEEmod.

**Comment by LazyPlaying** [comment]
I reinstalled Portal and that fixed my problem.

**Comment by Luke18033** [comment]
Not sure how people end up with missing FGDs, the fact that this issue only appears after installing BEE makes me think that maybe we're accidentally deleting it in certain cases?
