### ISSUE TITLE
AppendIO result

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1771]
The `ChangeIOType` result allows re-defining an item's entire I/O config, but there are a few cases like the Overgrown funnel where it would be nice to be able to append new inputs or outputs without having to re-define everything else. A new `AppendIO` condition should be added for this.

**Comment by TeamSpen210** [comment]
Good idea.

**Comment by TPEcool** [comment]
excuse me, if this issue is marked with the done label, why is it still open?

**Comment by TeamSpen210** [comment]
I leave them open until it's actually released.

**Comment by TPEcool** [comment]
oh, alright, sorry.
