### ISSUE TITLE
Add 'OMG what has he done' as funnel music

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2.4#1777]
### Description of the feature

Add the funnel music on the way to the final battle as funnel music

### Why should this be implemented

I want to replecate the final funnel ride in my maps, but I don't have the music for it

### Additional information

P.S. you should also add There She Is

**Comment by MaxineMaxie** [comment]
Please

**Comment by TeamSpen210** [comment]
It's already present, under the name "Finale Funnel". Not sure what a better name would be, since it's used in both *The Part Where He Kills You* and *OMG What Has He Done*.
