### ISSUE TITLE
Use start enabled to turn goo into a bottemless pit

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2.4#1778]
### Description of the feature

Make it so that while in the editor you can set a goo pit to start enabled to make it generate as a bottomless pit

### Why should this be implemented

it would be nice to be able to implement pits without hammer

**Comment by Luke18033** [comment]
This is already planned, goo would automatically turn into bottomless pits in certain styles. See BEEmod/BEE2-items#3891.
