### ISSUE TITLE
Item properties window renders over everything.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1779]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

![Image](https://user-images.githubusercontent.com/12244376/142954485-0f4634c1-7ef5-4daf-ad24-985f5bf6b835.png)

### Expected behavior

The window from the item properties must not render over everything.

### Steps to reproduce

Launch BEEmod 4.41.0 and then right-click an item from the application, then open anything else like a program, folder or a game and you will see that the item properties window will render over anything you open.

**Comment by TeamSpen210** [comment]
This is intentional, to ensure it doesn't get stuck behind the main window.

**Comment by Luke18033** [comment]
Probably it should close when losing focus?
