### ISSUE TITLE
Enabled/disabled pakages dont save

### ISSUE THREAD

**Issue by allspice101** [BEEmod/BEE2.4#1782]
### BEE2 Application Version

2.4.41.0 32/64 bit

### BEE2 Package Version

2.4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When disabling pakages, the aplication would normally crash when saving the enabled/disabled pakages. This is not happening currently, as seen here:

https://user-images.githubusercontent.com/60833082/143409481-5f6a2fa7-35e5-4ffc-a7a6-bae9fa75e0ed.mp4

### Expected behavior

The application would save the enabled/disabled pakages before crashing

### Steps to reproduce

1: Disable pakages
2: Close and relach BEE2

### Logs and Reports

```shell
[INFO] BEE2_launch.<module>(): Arguments: ['C:\\Users\\DarZa\\Documents\\Bee2\\BEE2.exe']
[INFO] BEE2_launch.<module>(): Running "bee2", version 2.4.41.0 32-bit:
[INFO] localisation.setup(): Language: 'en_US'
[DEBUG] localisation.setup(): Language codes: ['en_US.ISO8859-1', 'en_US', 'en.ISO8859-1', 'en']
[WARNING] BEE2_config.load(): Config "C:\Users\DarZa\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Using defaults...
```

**Comment by allspice101** [comment]
I do understand that error im getting after pressing ok is normal, as ive had that pop up with previous versions

**Comment by TeamSpen210** [comment]
That error you get is not normal no, I must have messed up the logic at some point.

**Comment by allspice101** [comment]
I just tried manually adding packages.cfg, and it's read it.

when saving the pakages, it's still giving me the "app.packagMan.py" error, but packages.cfg isnt updated

**Comment by allspice101** [comment]
EDIT: after looking at the logs, its showing this before the clean style error:
`[I] BEE2_config.save(): Saving changes in config "C:\Users\DarZa\AppData\Roaming\BEEMOD2\config\config.cfg"!`

**Comment by allspice101** [comment]
This issue also appliues to the 64 bit version
