### ISSUE TITLE
Use cube droppers as gel droppers

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1783]
### Description of the feature

![20211121092631_1](https://user-images.githubusercontent.com/63530071/143724525-95a0bf48-f67d-4374-824e-44ca76bfb7e0.jpg)

### Why should this be implemented

improves aesthetic

### Additional information

if it confuses players if its a cube dropper or a gel dropper, leave the latch open for the dropper, if it still doesnt work, use an optional colour palette

**Comment by Luke18033** [comment]
No, you're only asking for this because it's what the beta did.

**Comment by supersean08-pro** [comment]
> No, you're only asking for this because it's what the beta did.

no portal 2 still has this, that was the only image i got
im not saying i want beta

**Comment by Critfish** [comment]
This is a bad idea. Element visibility is extremely important in Portal level design, and having two elements look nearly identical, but function differently, interferes with that. No amount of "aesthetics" is going to solve that problem.
