### ISSUE TITLE
Aperture tag: Crash

### ISSUE THREAD

**Issue by uwoneko** [BEEmod/BEE2.4#1790]
### BEE2 Application Version

4.41.0 64 bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

In aperture tag, when i clicked build the chamber, my game crashed

### Expected behavior

I expect that my game just started playtest and in the map appeared paint gun activation field

### Steps to reproduce

Step 1. Create a chamber with fizzler and paint gun activation field
Step 2. Connect them
Step 3. Start playtest

### Logs and Reports

Nothing

### Additional information

Nothing

**Comment by hedcreb** [comment]
this actually happened to me too. i think it might be caused by some BEE2 custom assets but alas, i don't know.

**Comment by uwoneko** [comment]
closing as fixed as doesnt occur anymore. if i remember correctly, just reinstalling fixed the problem.
