### ISSUE TITLE
Portal 1 pgun effects

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1793]
### Description of the feature

https://gamebanana.com/mods/310793
https://gamebanana.com/mods/333974

### Why should this be implemented

It will improve asthetic

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2-items#3646 (your own issue)

**Comment by LautaroL20** [comment]
Also, you have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
