### ISSUE TITLE
Togglable lights

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2.4#1794]
### Description of the feature

Make light able to be enabled and disabled with connections

### Why should this be implemented

this would help you make rooms lighter or darker

**Comment by TeamSpen210** [comment]
See the [FAQ](https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#can-you-add-lights-that-are-toggled-by-an-input), this isn't going to be added for several reasons.
