### ISSUE TITLE
Lower laser catchers

### ISSUE THREAD

**Issue by supersean08-pro** [BEEmod/BEE2.4#1797]
### Description of the feature

![20220113131114_1](https://user-images.githubusercontent.com/63530071/149266875-804ad46c-a726-4f39-9424-5773c1044408.jpg)
![Uploading 20220113154046_1.jpg…]()

### Why should this be implemented

It will improve design, and also the laser (if being redirected by a laser cube) would not be offset

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2-items#1499
