### ISSUE TITLE
PeTI doesn't compile maps after installing Latest Version.

### ISSUE THREAD

**Issue by unoreverse176** [BEEmod/BEE2.4#1798]
### BEE2 Application Version

Latest

### BEE2 Package Version

Latest

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

So, I've had this bug for a while and finally decided to speak about it. Whenever I install a BEEMOD version higher than Alpha 2.2.5, the PeTI doesn't compile maps (at least I tested only these versions). Whatever I try, restoring the files then reapplying, reinstalling it a bunch of times, it just didn't work as intended.

### Expected behavior

Well, I expected everything to work right. Little did I know it wasn't going to be like that.

### Steps to reproduce

I don't even know how did this happen, I just installed BEEMOD.

**Comment by LautaroL20** [comment]
Not sure in which folder you installed BEEmod, but you never must install it in the Portal 2 folder. Also, if when you compile the map it throws a building error, you did not post the console log.

**Comment by unoreverse176** [comment]
> Not sure in which folder you installed BEEmod, but you never must install it in the Portal 2 folder. Also, if when you compile the map it throws a building error, you did not post the console log.

Oh. But, then, where do I put it? I really want to get it working, and the PeTI just freezes completely and never compiles the map.

**Comment by Luke18033** [comment]
You can just put it anywhere.

**Comment by unoreverse176** [comment]
Oh, thanks! Gonna try it right now.

**Comment by unoreverse176** [comment]
Tried, and the map still doesn't get compiled.

**Comment by LautaroL20** [comment]
> unoreverse176 said: "Oh. But, then, where do I put it?" 

As long as you do not install BEEmod 2.4 in the Portal 2 folder which can cause issues, you can install it somewhere else.

**Comment by unoreverse176** [comment]
The BEEMOD 2.4 folder is not in Portal 2, but how am I supposed to install it? Like, I chose the Portal 2 executable. Did I do something wrong?

**Comment by LautaroL20** [comment]
That should work yes. But considering you are having issues when compile a puzzle, you can try doing the following and see if it helps or not:

1.  Make sure any antivirus software is not blocking the executable of BEEmod (BEE2.exe) and add it in your antivirus exception list. Also, you'll have do the same with the BEE2.4 compilers that are located in the Portal 2 `bin` folder. Add the entire `bin` folder in your antivirus exception list; if the exception list only allows individual files, add `vbsp.exe` and `vrad.exe`. Not doing this may cause a compile error when building your puzzle.

2. Open BEEmod and click on `File > Uninstall From Selected Game`. Choose Yes in the dialog that appears.

3. Wait 1 minute while BEEmod resources are removed from Portal 2.

4. Verify the Game Cache Files for Portal 2. This option can be found by right-clicking the game in Steam, and selecting `Properties > Local Files > Verify Integrity of Game Files`.

5. Make sure to have installed the latest Packages and Application version of BEE2.4. 
Never use different release versions of the Packages and Application, they always must be from the same Pre-Release Version. Here are the links: [Application](https://github.com/BEEmod/BEE2.4/releases) and [Packages](https://github.com/BEEmod/BEE2-items/releases).


6. Click on: `File > Options`. Go to the Development tab, and uncheck the option `Preserve Game Directories`.

7. Select a palette and style, and export it to the game as normal.

8. If after following these steps it solved your issue, make sure to save these steps in a text file in case you get similar issues with BEEmod in the future.

**Comment by unoreverse176** [comment]
![image](https://user-images.githubusercontent.com/98108873/150450829-498fcd50-312c-440a-93f4-51b808a7c8c9.png)
Well, I'm unsure if these are different or not

**Comment by unoreverse176** [comment]
And, I never download antiviruses, since I always know what I'm doing, and always check if a file is malicious or not on Virustotal.

**Comment by unoreverse176** [comment]
It finally works! Thanks for helping! It finally works. Thank you so much!

**Comment by LautaroL20** [comment]
That tells me that my steps are still very useful for people with this kind of issues.

**Comment by Luke18033** [comment]
I'm curious what the error actually was, they never posted a log?

**Comment by unoreverse176** [comment]
It was just frozen at the first stage of compiling, it didn't make any errors, just frozen

**Comment by Luke18033** [comment]
There's still a compile log, it would have appeared in the console if you turned on `developer 1`. But actually since you'd installed BEE2.2 previously I think I know what happened.

**Comment by LonelySauce** [comment]
> ![image](https://user-images.githubusercontent.com/98108873/150450829-498fcd50-312c-440a-93f4-51b808a7c8c9.png) Well, I'm unsure if these are different or not

Bro's using Windows 11, that explains everything if you ask me lol

**Comment by Luke18033** [comment]
We figured out what the problem was, this issue is months old...
