### ISSUE TITLE
Pr16 BUG: Mashy Spike Plate

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2.4#180]
In cooperative mode, use the Mashy Spike Plate will result in a compile error.

**Comment by goodDOS** [comment]
Single player mode, no problem.

**Comment by BenVlodgi** [comment]
Is it the position of the spike plate in the map?
there used to be a bug where if it was placed on the corner of a map it would leak, but I thought that had been fixed.

**Comment by goodDOS** [comment]
![img](http://i11.tietuku.com/e2494144637d622f.png)
Can't compile.
@BenVlodgi

**Comment by goodDOS** [comment]
Mashy Spike Plate hurt have bug.
![img](http://i13.tietuku.com/06bcee434cdc061e.png)
![img](http://i13.tietuku.com/05c6ec7d44d769bd.png)
Red: hurt
Blue: No hurt

Also, why the Mashy Spike Plate looks so dark.
![img](http://i13.tietuku.com/6ea6d9f565159ac8.png)
@BenVlodgi

**Comment by TeamSpen210** [comment]
The crusher's death triggers are directional - the blue parts will only hurt you when it's retracting. The red hurts you when extending.

**Comment by goodDOS** [comment]
@TeamSpen210 The player won't die

**Comment by Konclan** [comment]
It's really annoying that all these images disappeared

**Comment by LautaroL20** [comment]
This was fixed since a long time ago.
