### ISSUE TITLE
Beemod Exporting issues

### ISSUE THREAD

**Issue by Areng14** [BEEmod/BEE2.4#1800]
BEE2 Application Version
4.41.0

BEE2 Package Version
4.41.0

What operating system are you running on?
Windows 10 (64bit)

Description of the bug
Beemod exported items but they show up as pink and black textures and when I place them they just appear as an error block

Expected behavior
Beemod to export everything and the items to look normally

Steps to reproduce
No idea

Logs and Reports

VBSP failed.

[I] cond.core._get_cond_group(): No name for module "precomp.faithplate"!
[I] cond.core._get_cond_group(): No name for module "precomp.fizzler"!
[I] vbsp.main(): BEE2.4.41.0 64-bit VBSP hook initiallised, srctools v2.2.3.
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): Could not parse texture generator type "bullsye.white.floor"!
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[W] options.load(): Extra config options: {'glass_scale': '0.15', 'staticpan': 'instances/BEE2/clean/static_panel/', 'voice_pack': 'BEE2_GLADOS_P1'}
[I] cubes.parse_conf(): Parsed 8 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 15 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 7
[I] vbsp.mod_entryexit(): Using random SP Exit (4)
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (13 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] (MetaCondition "link_cubes") cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] (<BEE2_CATWALK>/items/clean) cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Generating item IO...
[I] (MetaCondition "gen_item_outputs") connections.gen_item_outputs(): Item IO generated.
[W] (<BSOA>/items/styleless/bsoa_worldportal) cond._scaffold_compat.res_unst_scaffold(): Running legacy scaffold generator for "BEE2_SCAFFOLD"!Items should now use the generic LinkedItem config, update your packages!
[I] (<BSOA>/items/styleless/bsoa_worldportal) cond._scaffold_compat.res_unst_scaffold(): Finished Scaffold generation!
[W] (<BSOA>/items/styleless/bsoa_worldportal_centered) cond._scaffold_compat.res_unst_scaffold(): Running legacy scaffold generator for "BEE2_SCAFFOLD"!Items should now use the generic LinkedItem config, update your packages!
[I] (<BSOA>/items/styleless/bsoa_worldportal_centered) cond._scaffold_compat.res_unst_scaffold(): Finished Scaffold generation!
[W] (<FIZZLER>/items/vent) instanceLocs._resolve(): "vents" not a valid item!
[I] (MetaCondition "set_elev_videos") vbsp.set_elev_videos(): Elevator type: FORCE
[I] (MetaCondition "add_voice") voice_line.add_voice(): Adding Voice Lines!
[W] (MetaCondition "add_voice") BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[W] (MetaCondition "add_voice") BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[I] (MetaCondition "add_voice") voice_line.add_voice(): Adding Base instance!
[I] (MetaCondition "add_voice") voice_line.add_voice(): Quote events: []
[I] (MetaCondition "add_voice") voice_line.find_group_quotes(): "ENTRY": 1/15 quotes..
[I] (MetaCondition "add_voice") voice_line.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC"
 | 	"choreo" "scenes/npc/glados/mp_coop_turret_ball01.vcd"
 | 	}
 | 
 |___

[I] (MetaCondition "add_voice") voice_line.find_group_quotes(): "EXIT": 1/2 quotes..
[I] (MetaCondition "add_voice") voice_line.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_EXIT"
 | 	"Choreo" "npc/glados/sp_laser_powered_lift_completion01.vcd"
 | 	}
 | 
 |___

[I] (MetaCondition "add_voice") voice_line.find_group_quotes(): "MIDCHAMBER": 2/6 quotes..
[I] (MetaCondition "add_voice") voice_line.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAM_ENTRY"
 | 	"Target" "@glados_cam_entry"
 | 	"Choreo" "npc/glados/taunt_small_wave01.vcd"
 | 	"PlayOnce" "1"
 | 	}
 | 
 |___

[I] (MetaCondition "add_voice") voice_line.add_voice(): 0 Mid quotes
[I] (MetaCondition "add_voice") voice_line.add_voice(): Done!
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Setting Portalgun:
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] (MetaCondition "set_player_portalgun") vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): ---------------------
[I] cond.core.check_all(): Conditions executed!
[I] cond.core.check_all(): Map has attributes: ['spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=115, misses=410, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': False, 'restartonexit': False, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] music.add(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (May 19 2021)
[I] <valve>.vbsp(): 20 threads
[I] <valve>.vbsp(): Using shader api: shaderapiempty.dll
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/bee2/clean/elevator_sp/door_entrance_7.vmf
[I] <valve>.vbsp(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\ADMIN\AppData\Roaming\BEEMOD2\config\compile.cfg"!

Additional information
It happens to all styles

**Comment by Luke18033** [comment]
Check your settings in the BEE2 app, make sure you don't have "preserve game directories" on, then re-export.

**Comment by Areng14** [comment]
Where is that

**Comment by Luke18033** [comment]
`File > Options` I think

**Comment by Luke18033** [comment]
I guess that fixed it?

**Comment by Areng14** [comment]
yup
