### ISSUE TITLE
i cant publish test whit p1 style and underground style and bts style

### ISSUE THREAD

**Issue by werdkindom** [BEEmod/BEE2.4#1802]
### BEE2 Application Version

4.39.1

### BEE2 Package Version

4.39.0

### What operating system are you running on?

Windows 10 (32bit)

### Description of the bug

i cant play my tests whit p1 style and underground style and i not play whit bts style and i cant publish my tests chamber whit p1 style and bts style and underground style i needs help

### Expected behavior

help

### Steps to reproduce

help

### Logs and Reports

```shell
none
```

### Additional information

none

**Comment by LautaroL20** [comment]
When reporting a bug, first make sure you're on the latest version of the mod, as the issue may have already been fixed. You're using an outdated BEE2 version, so please get the latest version of the application & packages and then if the issue still exists, let us know and we will re-open the issue.

**Comment by werdkindom** [comment]
ok

**Comment by LautaroL20** [comment]
You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
