### ISSUE TITLE
BEE2.4.41.1 64-bit error

### ISSUE THREAD

**Issue by werdkindom** [BEEmod/BEE2.4#1803]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (32bit)

### Logs and Reports

```shell
i cant extract BEE2.4 in portal 2 help me plz
```

### Additional information

![image](https://user-images.githubusercontent.com/98479978/151247893-1985128a-a1c1-487d-84de-4da40f2a393e.png)

**Comment by TeamSpen210** [comment]
That's not really a bug, apparently you've run out of space on your hard drive to extract the resources into Portal 2?

**Comment by werdkindom** [comment]
ok i already noticed lol i need to delete this thread
