### ISSUE TITLE
Music issue - Audio bug in Portal 2 (BEE2.4.41.0 x64,  Win10 x64, BMMC2 latest)

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1805]
### BEE2 Application Version

2.4.41.0 x64

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

So I noticed that BMMC2 made it a step further than just gel music and custom music now breaks almost the ENTIRE AUDIO ENGINE of Portal 2 for this session. This first happened to me when I imported a track with a fade-in start made in Audacity.

### Expected behavior

The music and any other sounds should play as normal.

### Steps to reproduce

1. Import music with BMMC2
2. Select it in BEE2 and Export
3. Compile/Build a PTI test
4. It will likely not work

### Additional information

This doesn't happen with music imported via UCPs, for example, the "Portal Reloaded Music" package I have. The music used as Gel music from that package is broken too, but it just doesn't play, it doesn't break anything.

**Comment by TPEcool** [comment]
How exactly does this even happen?!

**Comment by FrozenDragon0** [comment]
I don't even know if this is something that is fixable, what is BMMC2? I'm not sure what that is.

**Comment by TPEcool** [comment]
it isa program to import music into BEE2

**Comment by TPEcool** [comment]
custom music

**Comment by FrozenDragon0** [comment]
I'm guessing that BMMC2 is doing something to the audio file that Portal 2 cannot read/process properly.

**Comment by TPEcool** [comment]
But what could it do? Also, if it does, this is 100% a BEE-sided issue, not UCP-sided.

**Comment by LautaroL20** [comment]
BMMC2 is very outdated and it looks like their developers abandoned the project completely. So, do not expect that BMMC2 would work well and neither in the future. Also, BMMC2 is not part of the BEE2.4 project and the dev is another person so there is nothing we can do to fix it.

**Comment by TPEcool** [comment]
Though maybe someone could make a replacement, also with file-picker dialogs for images and textfields for desc and title?

**Comment by TPEcool** [comment]
I have no experience with Windows programming, so i'm not sure if i could.
