### ISSUE TITLE
consolodate lights into one "lights" item

### ISSUE THREAD

**Issue by patrlim** [BEEmod/BEE2.4#1806]
as title says, this would allow for more test elements in one level if the user wishes to use multiple lights, for example for theming.
it may be possible to do the same with fizzlers.

**Comment by LautaroL20** [comment]
You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
