### ISSUE TITLE
explosion item

### ISSUE THREAD

**Issue by CassieCatYT** [BEEmod/BEE2.4#1808]
### Description of the feature

add a device that makes an explosion of adjustable size when activated

### Why should this be implemented

i would like to be able to incorporate explosions into my map

**Comment by ErinRoseWebs** [comment]
While this would TECHNICALLY be easy to make, it doesn't make sense for peti. Outside of visuals, which peti isn't really designed for, explosions usually indicate destruction, which cannot be done in peti, only in Hammer. Your best bet is either coping without it, making a UCP (user created package), or learning Hammer.

**Comment by Luke18033** [comment]
Yeah we're not adding random explosions that appear out of nowhere, they don't make sense and if they damage players it'd also be annoying/unfair.

**Comment by FrozenDragon0** [comment]
This is also posted in the wrong section.
