### ISSUE TITLE
request to add portal realoaded portal mechanism 

### ISSUE THREAD

**Issue by Hazmatron7** [BEEmod/BEE2.4#1809]
### Description of the feature

Is it possible to add portal reloaded portal mechanism including the frizzlers etc, please?
I honestly don't know how this would work but maybe in the bee mod software it can maybe 
link to a .bsp file or something. Then it loads it when running the map from the puzzle maker.
i don't know but I just think it would be a cool idea to add.

### Why should this be implemented

I think this idea should be implemented because it could make more possibilities of making unique and harder/challenging custom maps and other really cool ideas too. As well as it was a really good mod.

### Additional information

I found a link on how to make custom maps for it in hammer:
[https://steamsplay.com/portal-reloaded-how-to-create-custom-maps-june-2021/](https://steamsplay.com/portal-reloaded-how-to-create-custom-maps-june-2021/)

**Comment by ErinRoseWebs** [comment]
actually i think getting it working for PuzzleMaker COULD be possible, but at that point there's just so much work involved it would actually be easier to make the map in Hammer, especially since it's simple scripting that does everything.

**Comment by FrozenDragon0** [comment]
Making this work for the puzzlemaker wouldn't be worth the time and effort tbh, your just better off making the map in hammer for this.

**Comment by Hazmatron7** [comment]
@FrozenDragon0 I understand. Thank you anyway. 😄
