### ISSUE TITLE
Beemod Elements don't show in the editor (FIXED)

### ISSUE THREAD

**Issue by MindofOcto** [BEEmod/BEE2.4#1812]
### BEE2 Application Version

BEE2_v4.41.1_win64

### BEE2 Package Version

BEE2_v2.4.41.0_packages

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Whenever I try to export a pallet in Beemod, it doesn't show up in the basic portal 2 editor. I don't know why it isn't working.
![Screenshot (1)](https://user-images.githubusercontent.com/99097022/152663230-10b1ce1a-ceb2-4e05-acc9-42a93a761d70.jpg)
 

### Expected behavior

I originally thought that exporting my pallet would actually export them to portal 2 with all of my chosen elements like in this video: [](https://www.youtube.com/watch?v=FINQiERS8AE) but apparently not.

### Steps to reproduce

Step 1: Export any pallet to Portal 2 via .exe program
Step 2: Hope that it works

**Comment by slambo311** [comment]
First of all, 4.41.1 isn't even out yet.
Second of all, did you verify files or put beemod in the portal 2 folder or something like that?

**Comment by MindofOcto** [comment]
First, that's what the file said when I looked at it
Second, I followed the directions by having the .exe application, choosing my palette, then exported it to portal 2, but it didn't show up. I verified the portal 2 files multiple times, but it didn't help. I watched multiple help videos who said the exact same thing, but again, nothing worked.

**Comment by slambo311** [comment]
I may not be a developer, but try uninstalling BEEmod and then reinstalling it. Make sure not to verify files after exporting, that resets it. But before you do that, do you use any launch options for Portal 2 or custom BEEmod packages or anything like that?

**Comment by MindofOcto** [comment]
wdym by launch options? Do you mean how you run the game? I only downloaded what was necessary to run BEEmod, that including the application and packages that went with it

**Comment by MindofOcto** [comment]
Modding is new for me, and I really want to create new portal 2 levels like all the other devs on the steam workshop.

**Comment by slambo311** [comment]
Alright, go in steam, right-click portal 2, click properties. There's a launch options thing there. Considering you don't know what launch options are, I'm sure it's empty (which is good, but I'd recommend typing "-vulkan" in there).
Here's a little explanation on launch options I came up with: If it starts with -, it usually messes with the graphics and stuff. If it starts with a +, you can also put it into the developer console (a lot of games have these, it's pretty much the first thing you outta mess with to get into modding).
Also, don't worry about being new, you'll get the hang of it eventually. I got a repository I made if you ever need help (but I'd recommend also joining the beemod discord, they're better at it than I am).

**Comment by MindofOcto** [comment]
It still didn't work.. Idk why bro. I did exactly what you said. reinstalled BEEmod and changed the launch options to -vulkan. Does it help if I mention that I changed a texture in portal2_dlc3??? (Before the update at the 1st of Feburary and 24th)

**Comment by RPink47** [comment]
The solution (That worked for me):
1. Open BEE2
2. Open Steam in the library tab
3. Find Portal 2, right-click and select Manage > Browse local files
4. In BEE2 File > Add Game
5. Follow the path that the file explorer shows on the top (You need to select the Portal2.exe executable in the Portal 2 folder )
6. Select the Portal2.exe executable
7. Give it a name ("Portal 2 real" for example)
8. File > Portal 2 real (in my case)
9. Now it should work (it worked for me and I had the same problem )

**Comment by MindofOcto** [comment]
tried that as well, didn't work. At this point, I'm just gonna record a video and show you whats happening so you can hopefully understand

**Comment by MindofOcto** [comment]
https://drive.google.com/file/d/1D1TCcOjOWFNB6IL7iCfXUKGrqC22Zugi/view?usp=sharing

**Comment by slambo311** [comment]
Well, I sure don't know where it went wrong. Do you have the Portal 2 Authoring Tools installed?

**Comment by MindofOcto** [comment]
1. I do have Portal 2 Authoring tools installed.
2. I have two separate exe files for some reason, only difference being the names (due to a an attempt like a year ago) and the dates. They are literally the same application but one works, which is the current version of the game

**Comment by MindofOcto** [comment]
This issue has being going on for a while, I almost gave up on it. However, I've decided to come back to it with a more experienced mind to see if we can get it fixed.

**Comment by slambo311** [comment]
At this point, might as well completely uninstall and reinstall Portal 2, Portal 2 Authoring Tools, and Beemod. Then again, I wouldn't be surprised if you already tried that multiple times, so how about this:

1. Uninstall Portal 2, Portal 2 Authoring Tools, and Beemod, as usual
2. Go into the "common" folder (aka where all your Steam games are), and if you find any Portal 2 folders, delete them.
3. Unsubscribe from any and all Portal 2 workshop maps (this one's probably not going to affect anything, but might as well)
4. Go into the "workshop" folder, right next to the "common" folder, search for any folders named 620 or 629, and remove them.
5. Obviously, empty your PC's recycling bin/trash
6. Reinstall Portal 2, Authoring Tools, and Beemod.

**Comment by TeamSpen210** [comment]
Be careful though, backup `Portal 2/portal2/puzzles/`, or you'll loose all your saved chambers.

**Comment by MindofOcto** [comment]
I'll try it, and I let you guys know if it works. If it doesn't, I appreciate your help

**Comment by MindofOcto** [comment]
IT WORKED, THANK YOU GUYS SO MUCH
