### ISSUE TITLE
Un-hardcode DLC folder usage

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#1813]
BEE2 is currently hardcoded to use `portal2_dlc3` as the folder for VPK texture overrides, which is a problem since this folder is also commonly used for user customizations. For this, `vpk_override` is provided, but this is a somewhat clunky solution since it requires re-exporting from BEE every time you want to modify custom content. There's no reason DLC3 needs to be used specifically, so BEE2 should sequentially scan through all DLC folders on export and use whatever the first available one is. To avoid infinitely creating new DLC folders, a `bee2_edit_flag` file would be created in whichever DLC folder was used; on future exports, this file would be detected and the same folder as before would be used.

The only problem this could potentially cause is if the user had pre-existing custom DLC folders, exported BEE2, then deleted one of the existing folders causing BEE2's to no longer be loaded. Since the DLC folder is only used for editor texture overrides though this shouldn't be a huge concern, they'd come back after the next export anyway.

**Comment by Luke18033** [comment]
I don't usually post "bump"-type comments anymore but this really needs to be implemented. The Portal 2 VR mod that released recently is also using DLC3 and this is going to cause conflicts if BEE is overwriting the VPKs without warning.

**Comment by TeamSpen210** [comment]
The big problem I see is migration - BEE can't tell the difference between a DLC3 folder that it created before this change, and a DLC3 folder that should be preserved. I suppose the best I can do is keep track of whether the game was loaded from a previous version, and if so check if the DLC3 VPK only includes stuff overwriting editor-related files?

**Comment by Luke18033** [comment]
Does BEE have any way of knowing if it was updated from a previous version vs. newly installed? If it does then you could just assume DLC3 is BEE the first time you export after upgrading from an old version, and add the `bee2_edit_flag` file in there
