### ISSUE TITLE
Changing options crashes BEE2

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1814]
### BEE2 Application Version

dev

### BEE2 Package Version

dev

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "trio\_core\_run.py", line 815, in __aexit__
  File "app\config.py", line 187, in apply_conf
KeyError: <class 'app.config.GenOptions'>
```

**Comment by TeamSpen210** [comment]
Could you post the full log? I think there might be further tracebacks earlier.

**Comment by Luke18033** [comment]
Yeah probably, it's also crashing when doing pretty much anything with selector windows...

**Comment by Luke18033** [comment]
[bee2.log](https://github.com/BEEmod/BEE2.4/files/8103248/bee2.log)

**Comment by Luke18033** [comment]
This is the error that's thrown when opening selector windows, not sure if it's related
```
Traceback (most recent call last):
  File "app\selector_win.py", line 1289, in open_win
NameError: name 'app' is not defined
```
