### ISSUE TITLE
The editor thinks that the lifeform Sensor is a signal output, not an input.

### ISSUE THREAD

**Issue by Artemvar41** [BEEmod/BEE2.4#1815]
I can't set up the lifeform detector. For example: it is not possible to connect a lifeform sensor to a door. And if you connect to input A or B, then the editor thinks that this is an output and not an input. If connected to a button, the field will simply turn on / off.

**Comment by LautaroL20** [comment]
You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
