### ISSUE TITLE
Portal2.fgd missing boolean defaults

### ISSUE THREAD

**Issue by Rooke6** [BEEmod/BEE2.4#1819]
### BEE2 Application Version

BEE2.4.41.0 64bit

### BEE2 Package Version

BEE2.4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

1. Uninstalled BEE2.4.36.0/1 from Portal 2.
2. Verified the Local Portal 2 files - successfully ( 2 files downloaded )
3. Deleted all BEE2.4.36.0/1 files from its repository folder. 
4. Ran Hammer.  It did not get any errors.  Closed Hammer.
5. Unpacked the BEE2.4.41.0 : program files, items and music packages to their repository folder.
6. Ran the BEE2.exe then exported BEE2 to Portal 2.
7. Ran Hammer and got the following errors:

File E:\Steam\steamapps\common\Portal 2\bin\portal2.fgd, line 2301: boolean type specified with nonsensical default value:
File E:\Steam\steamapps\common\Portal 2\bin\portal2.fgd, line 2474: boolean type specified with nonsensical default value:

Used Notepad++ to look at the Portal 2.fgd
The first error was in the code block for:  @SolidClass = comp_trigger_coop
And the line above  the stated line# was missing a default:
    nodamageforces(boolean) : "No damage forces?"
The 2nd error was in the code block for:  @SolidClass = comp_trigger_p2_goo
And once again the line above  the stated line# was missing a default:
    nodamageforces(boolean) : "No damage forces?"
    
Updated the fgd to include the defaults of 0 (zero) for both of those entries, and restarted Hammer, but the errors shifted down several lines in the fgd. Looking through the rest of the fgd showed lots of booleans missing defaults.

### Expected behavior

I expect Hammer to not get any errors when BEE2.4.x is installed and exported to Portal2.

### Steps to reproduce

Do everything stated in the description. 

### Logs and Reports

```shell
File E:\Steam\steamapps\common\Portal 2\bin\portal2.fgd, line 2301: boolean type specified with nonsensical default value:
File E:\Steam\steamapps\common\Portal 2\bin\portal2.fgd, line 2474: boolean type specified with nonsensical default value:
I
```

### Additional information

I'm using the Overgrown style.

**Comment by TeamSpen210** [comment]
Should be fixed by [this commit](https://github.com/TeamSpen210/srctools/commit/897d591f66c51bcb8381cf59df04488bc51407cc).
