### ISSUE TITLE
If i have ANY ucp for bee 2.4 then the compiler stucks at the very end of Building Geometry

### ISSUE THREAD

**Issue by ImagineUsingHammer** [BEEmod/BEE2.4#1822]
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I recently installed some user created packages for BEE2 v2.4 and the map editor broke
Basically it works fine even lets me place the custom items but then when i publish or preview the map its getting stuck on the end of Building Geometry (1st loading bar)

### Expected behavior

I expected it to publish and preview normally

### Steps to reproduce

Step 1. Install ANY ucp from BEEmod discord server
Step 2. Place the new items into your pallet
Step 3. Try to place them in the map editor
Step 4. Publish or preview the map and it will stuck

### Additional information

Using P1 style
Using P1 "Subject Name Here" music
Using Energy Pellets

**Comment by Areng14** [comment]
What UCP are you using

**Comment by Areng14** [comment]
Also send me the console log and send me a picture of the palate also describe how it doesn't work It says there was an error  building the puzzle etc

**Comment by LautaroL20** [comment]
The user created packages (UCP) are custom stuff made by the community, not the official BEEmod team. You use them at your own risk, make sure to send as much info as possible to the corresponding author of the UCP, like the console log that contains the errors, pictures, videos, etc.
