### ISSUE TITLE
XIO Fatal IO Error on Linux

### ISSUE THREAD

**Issue by MeowcaTheoRange** [BEEmod/BEE2.4#1823]
### BEE2 Application Version

Build - Git pull since commit 5e07112bb9fd635dcd6a4ec4ee8b5ad8285a1f33 (latest as of now)

### BEE2 Package Version

N/A - haven't installed pacakges yet

### What operating system are you running on?

Linux

### Logs and Reports

```shell
..@pop-os:../dist/64bit/BEE2$ ./BEE2
Need implementation of utils.check_shift()!
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 2.4.41.0.dev+5e07112b 64-bit:
[I] localisation.setup(): Language: 'en_US'
XIO:  fatal IO error 2 (No such file or directory) on X server ":1"
      after 28 requests (28 known processed) with 2 events remaining.
XIO:  fatal IO error 0 (Success) on X server ":1"
      after 40 requests (40 known processed) with 2 events remaining.
```

### Additional information

After building the game, it won't seem to cooperate, and the top-most error reads `Need implementation of utils.check_shift()!`. I'm not an expert on Python, so I'm not exactly sure what this means.

**Comment by True-cc** [comment]
I have same problem, except with different end error messages.
```
Need implementation of utils.check_shift()!
[I] BEE2_launch.<module>(): Arguments: ['./BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 2.4.41.0.dev+5e07112b 64-bit:
[I] localisation.setup(): Language: 'en_US'
X connection to :0.0 broken (explicit kill or server shutdown).
X connection to :0.0 broken (explicit kill or server shutdown).
```
I'm on arch linux with kernel 5.17.3-zen.

**Comment by TeamSpen210** [comment]
The message isn’t critical, it’s a reminder to find a way to implement checking if the shift key is held down. Unfortunately Linux requires root to do that, so it’s not really doable. But it’s not a critical feature, the problem is something between X and Tkinter, I don’t know what.

**Comment by MeowcaTheoRange** [comment]
> The message isn’t critical, it’s a reminder to find a way to implement checking if the shift key is held down. Unfortunately Linux requires root to do that, so it’s not really doable. But it’s not a critical feature, the problem is something between X and Tkinter, I don’t know what.

So does this mean I just do `sudo ./BEE2`..?

**Comment by TeamSpen210** [comment]
One thing I suspect it could be is the app icon, you could try commenting out this line here: <https://github.com/BEEmod/BEE2.4/blob/master/src/app/tk_tools.py#L82>
If not, try running in a Python debugger, see what it's doing before it finally crashes?

**Comment by 0x454d505459** [comment]
Can confirm, I get the exact same error even by commenting out line 82.
```
Need implementation of utils.check_shift()!
[I] BEE2_launch.<module>(): Arguments: ['./dist/64bit/BEE2/BEE2']
[I] BEE2_launch.<module>(): Running "bee2", version 2.4.41.0.dev+5e07112b 64-bit:
[I] localisation.setup(): Language: 'fr_FR'
X connection to :0 broken (explicit kill or server shutdown).
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 40 requests (40 known processed) with 2 events remaining.
```

**Comment by flarn2006** [comment]
Encountering the same issue on Arch after building commit 5e07112bb9fd635dcd6a4ec4ee8b5ad8285a1f33.

**Comment by haydenwalker980** [comment]
Yea I have the same problem.
