### ISSUE TITLE
 decoration items do not appear

### ISSUE THREAD

**Issue by werdkindom** [BEEmod/BEE2.4#1827]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### Description of the bug

well that sounds weird but the decoration items don't show up in the palette

### Expected behavior

not show

### Steps to reproduce

help

### Logs and Reports

```shell
help
```

### Additional information

help

**Comment by Luke18033** [comment]
What "decoration items" are you referring to?

**Comment by werdkindom** [comment]
wait

**Comment by werdkindom** [comment]
this itenshttps://steamuserimages-a.akamaihd.net/ugc/1807641959566407077/46F9D8C5D800B0268DB859951269194EFF4E4B0E/

**Comment by werdkindom** [comment]
link https://steamuserimages-a.akamaihd.net/ugc/1807641959566407077/46F9D8C5D800B0268DB859951269194EFF4E4B0E/

**Comment by Luke18033** [comment]
Those are from a UCP, you can download it in #ucp-releases on the discord server

**Comment by werdkindom** [comment]
ok
