### ISSUE TITLE
Style/Item Config Dropdown Option

### ISSUE THREAD

**Issue by ErinRoseWebs69** [BEEmod/BEE2.4#1829]
### Description of the feature

Add an option to use dropdowns for style/item variables for situations where there is a list of options that does not require the timer/slider/checkbox widget. 

### Why should this be implemented

Would help in situations where you have a specific list of options, and the other widgets don't fit.

**Comment by FrozenDragon0** [comment]
Do you mean a Dropdown like setting onto the item in-game?

**Comment by ErinRoseStewart** [comment]
like a dropdown box for the actual BEE2.4 app.

**Comment by FrozenDragon0** [comment]
Ah.
