### ISSUE TITLE
Map Optimization

### ISSUE THREAD

**Issue by seagull101** [BEEmod/BEE2.4#1830]
### Description of the feature

Map optimization could be improved by creating hint/skip brushes at corners in the map. Allowing maps to run faster.

### Why should this be implemented

I think doing this will improve runtime on older computers and also decrease compile time.

**Comment by Luke18033** [comment]
This isn't what optimization is. You really need Hammer's ability to manually place these brushes and the knowledge of how to use the features effectively for them to actually be useful. Adding hint brushes at every corner is just going to increase compile times for basically zero in-game performance benefit.
