### ISSUE TITLE
Use something else than python and Tkinter

### ISSUE THREAD

**Issue by 0x454d505459** [BEEmod/BEE2.4#1833]
### Description of the feature

It's not really a feature, but a general huge improvement.
Instead of using python that compile using pyinstaller and using tkinter for UI, you could use a compiled language like NIM, C, C++, crystal, RUST, etc..

### Why should this be implemented

NIM here would require to rewrite a bit less the code as it's syntax is similar to the python one. It will be a lot faster (nearly as fast as C) and would take way less space on disk. It can also compiles to CPP is needed and interface really well with C/CPP code.

If you can't rewrite everything, please at least consider using Kivy/KivyMD for UI and Nuitka to compile it to native OS. (Unlike pyinstaller that just pack the code with a python interpreter).

### Additional information

- [Nim programming language](https://nim-lang.org/)
- [Kivy](kivy.org)
- [Nuitka](github.com/Nuitka/Nuitka)

**Comment by seagull101** [comment]
Could .NET or Java work?

**Comment by 0x454d505459** [comment]
Well .NET is not what everyone wants to use under a linux or mac environnement, it could still do the job. And I don't really know for java. I don't know it.

Also, it could be great if we didn't have to use any interpreter/virtual machines and have an easy way to compile stuff. I might be asking too much though.

**Comment by TeamSpen210** [comment]
Syntax similarity isn't really important, because everything else would still be different and require careful rewrites. Speed of interpretation versus compilation isn't a silver bullet either - what's more important is the algorithms you use, which a higher level language allows handling much better. I've done profiling of app startup and compilation running, and both are mainly I/O dominated actually.

**Comment by 0x454d505459** [comment]
> Syntax similarity isn't really important, because everything else would still be different and require careful rewrites. Speed of interpretation versus compilation isn't a silver bullet either - what's more important is the algorithms you use, which a higher level language allows handling much better. I've done profiling of app startup and compilation running, and both are mainly I/O dominated actually. 

I agree, but I think that's the packageability of the project should be really considered. And using python and tkinter doesn't help all.

**Comment by ThaBluNate** [comment]
this would litterally take a rewrite of the project
using non-Tkinter would require rewriting entire UI's code
Using a different compiler would probably require repackaging and new scripts to get things where they need to go
+ tkinter is built-in python and it's going to leave many people confused then suddenly 2 new requirements are added

**Comment by Luke18033** [comment]
We do plan to switch to a different UI library actually, but we're not rewriting the entire app in a different programming language, that would be a huge amount of effort and basically BEE2.5.
