### ISSUE TITLE
Use something else than python and Tkinter

### ISSUE THREAD

**Issue by 0x454d505459** [BEEmod/BEE2.4#1834]
### Description of the feature

It's not really a feature, but a general huge improvement.
Instead of using python that compile using pyinstaller and using tkinter for UI, you could use a compiled language like NIM, C, C++, crystal, RUST, etc..

### Why should this be implemented

NIM here would require to rewrite a bit less the code as it's syntax is similar to the python one. It will be a lot faster (nearly as fast as C) and would take way less space on disk. It can also compiles to CPP is needed and interface really well with C/CPP code.

If you can't rewrite everything, please at least consider using Kivy/KivyMD for UI and Nuitka to compile it to native OS. (Unlike pyinstaller that just pack the code with a python interpreter).

#### Referenced
- [Nim programming language](https://nim-lang.org/)
- [Kivy](kivy.org)
- [Nuitka](github.com/Nuitka/Nuitka)

**Comment by FrozenDragon0** [comment]
Rather than opening a new issue that's literally the exact same, just edit the old issue: https://github.com/BEEmod/BEE2.4/issues/1833

**Comment by 0x454d505459** [comment]
That's a bug from github. I never opened two issues, or wanted to.
