### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by luckysandvich** [BEEmod/BEE2.4#1835]
### BEE2 Application Version

2.4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "app\UI.py", line 782, in export_editoritems
  File "app\gameMan.py", line 894, in export
  File "app\gameMan.py", line 596, in refresh_cache
PermissionError: [WinError 5] Отказано в доступе: 'd:\\steam\\steamapps\\common\\portal 2\\bee2\\avcodec-58.dll'
```

**Comment by LautaroL20** [comment]
Do you have installed BEE2.4 inside the Portal 2 folder?

**Comment by luckysandvich** [comment]
Yes

**Comment by Luke18033** [comment]
You need to install it anywhere other than `Portal 2/bee2`, that's used for custom content after exporting.
