### ISSUE TITLE
Text trigger

### ISSUE THREAD

**Issue by TomahawkFL** [BEEmod/BEE2.4#1837]
### Description of the feature

I have an idea for a new trigger. A trigger that displays text on the players screen when activated. But, it can only be activated by a button, or something that activates.

### Why should this be implemented

Helps with story-based chambers.

**Comment by FrozenDragon0** [comment]
Puzzlemaker is not designed for story-based chambers, use hammer if you want something like this.

**Comment by Areng14** [comment]
There is a UCP for that

**Comment by TomahawkFL** [comment]
> There is a UCP for that

Whats a UCP?

**Comment by TomahawkFL** [comment]
> Puzzlemaker is not designed for story-based chambers, use hammer if you want something like this.

Oh, also I forgot to mention it can give information, and is configured the same way as the cube coloriser, neurotoxin emitters, and signage items.

**Comment by TomahawkFL** [comment]
> Puzzlemaker is not designed for story-based chambers, use hammer if you want something like this.

Just thought about it for a minute. Nevermind. You're right. Still think it'd be fun, though, at least.
