### ISSUE TITLE
Add the ability to compile maps without lighting

### ISSUE THREAD

**Issue by SP2G50000** [BEEmod/BEE2.4#1841]
### Description of the feature

Currently, the "lighting" section provides an option for compiling a map with either fast lighting or full lighting (with full lighting always on for published maps - this should not change.) There is no option to skip the lighting step entirely and just run the map in fullbright. Here's what it would look like in the compiler pane:
![image](https://user-images.githubusercontent.com/20195894/172022082-e6f3d97c-b957-4c95-ab92-df390773f561.png)
(The corresponding tooltip:)
![image](https://user-images.githubusercontent.com/20195894/172022117-a8dc9d5e-5fe9-426f-9d66-01ef884fb602.png)

### Why should this be implemented

VRAD is known for taking an excessive amount of time on some maps, even in fast lighting. While a puzzlemaker map is still being developed it would be very useful to quickly compile maps to preview changes, and VRAD sometimes prevents this. This is only for previewing maps, publishing should be locked to full lighting as always.

Additionally, if someone were using BEEmod's `vrad.exe`, they would be able to use it without calling the original vrad should they want to.

### Additional information

I created [a fork](https://github.com/SP2G50000/BEE2.4/tree/dev) that implements everything suggested (along with a few fixes to make it compile properly.) I'd like to open a pull request for this fork, but first I want to verify that the BEEMod maintainers are willing to accept this feature.

**Comment by TeamSpen210** [comment]
This is a good idea yes, feel free to make that PR.

**Comment by Luke18033** [comment]
Just realized a different way we might actually want to do this - could we have the VRAD precompiler just fill in all the lightmaps with a single value? That would still provide near-instant lighting compiles, while still allowing gel and the like to work since it's not technically fullbright. Maybe we also have it override the tonemapper settings so HDR doesn't take effect.
