### ISSUE TITLE
No .exe in folder I downloaded

### ISSUE THREAD

**Issue by Sixteen60** [BEEmod/BEE2.4#1846]
### BEE2 Application Version

BEE2.4-master

### BEE2 Package Version

BEE2-items

### What operating system are you running on?

Other

### Description of the bug

For some odd reason I don't see an .exe when I downloaded the mod, even if the install guide does say to run the exe. And there's also the BEE2 icon but it's not an .exe
![image](https://user-images.githubusercontent.com/99849136/176345146-9ed1e507-ecab-4533-9d7e-5beb40b3fea8.png)

### Expected behavior

I obviously meant to see an .exe application that I can just click on.

### Steps to reproduce

I tried reinstalling the same folder but no .exe application. And it'll just keep happening every single time.

**Comment by Konclan** [comment]
You downloaded the source, not the app. This is what you’re looking for:
https://github.com/BEEmod/BEE2.4/releases
