### ISSUE TITLE
cant make tests

### ISSUE THREAD

**Issue by Darealxbox** [BEEmod/BEE2.4#1847]
when I try to play the map all the entities are misplaced and the test chamber for example I attached an image below
![image](https://user-images.githubusercontent.com/108944390/178022421-7f5edcfe-4e81-4a3e-b60e-fae80f7bcb94.png)
this happens in all old aperture styles and the overgrown style but I think it's safe to say that it happens in all styles

**Comment by Luke18033** [comment]
Validate game files and re-export, this happens if you're missing `bin/portal2.fgd`. Did you uninstall the Authoring Tools recently?

**Comment by Darealxbox** [comment]
Ill check

**Comment by Darealxbox** [comment]
thanks for the help
