### ISSUE TITLE
monitor visuals for Nigel

### ISSUE THREAD

**Issue by Darealxbox** [BEEmod/BEE2.4#1848]
### Description of the feature

just a generic one for Nigel would be nice but of course it isn't necessary 

### Why should this be implemented

details in maps

### Additional information

I can't code so I don't have images but look at a monitor in the campaign

**Comment by LautaroL20** [comment]
You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
