### ISSUE TITLE
No BTS Style

### ISSUE THREAD

**Issue by Sixteen60** [BEEmod/BEE2.4#1849]
### BEE2 Application Version

BEE2 Automatic Installer

### BEE2 Package Version

Pre included package with auto installer ^

### What operating system are you running on?

Other

### Description of the bug

For some unknown reason, I don't see the BTS (Behind The Scenes) in the styles option, nor is there the the 3D skyboxes. I'm pretty sure I saw those before so I don't know if it's the auto installer I used, or if it's a bug in BEE2.

### Expected behavior

Obviously, I meant to see the options mentioned above.

### Steps to reproduce

1) I tried reinstalling BEE2 using the same method I did before (The auto installer).
2) Still persisted even then.

**Comment by Critfish** [comment]
BTS style was cut a while ago. The reason is in the FAQ.
