### ISSUE TITLE
Game Crash In Community Chamber Menu

### ISSUE THREAD

**Issue by Team-Bugs** [BEEmod/BEE2.4#1850]
### BEE2 Application Version

4.41.0

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
(I don't know how to access the logs, the game just crashes after I click 'Create Chamber' on the community chambers menu)
```

### Additional information

The game just crashes after I click 'Create Chamber' on the community chambers menu. The only other information I have is that I have the 1950's Old Aperture theme activated.

**Comment by TeamSpen210** [comment]
This can happen if there's a corrupt autosave file. Go to `Portal 2/portal2/puzzles/<steam ID>`, and delete `autosave.p2c`.

**Comment by Team-Bugs** [comment]
It worked, thanks! I've been wanting to make another chamber for a while and now its fixed, thanks again!
