### ISSUE TITLE
Game crashes when loading into editor

### ISSUE THREAD

**Issue by Boxie98** [BEEmod/BEE2.4#1853]
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

**_Censored due to personal information_**

### Additional information

When crashed it shows this error message:
![2022-07-24 11_46_47-Window](https://user-images.githubusercontent.com/109649867/180628965-34194fe6-3b93-4adf-ad6b-254f7da093ba.png)

I don't know if this is a portal 2 error, or if it's caused by the BEEmod.

**Comment by Luke18033** [comment]
We don't support pirated copies of the game, this doesn't look like an error that would be caused by BEE anyway.
