### ISSUE TITLE
logic gates do not like SR latches

### ISSUE THREAD

**Issue by yeetmanthecoolman** [BEEmod/BEE2.4#1854]
### BEE2 Application Version

4.41.0 64 bit

### BEE2 Package Version

4.41,0

### What operating system are you running on?

Other

### Logs and Reports

```shell
no windows 11 in bug reports, lol. link to example map:
https://steamcommunity.com/sharedfiles/filedetails/?id=2841293600
```

**Comment by LautaroL20** [comment]
> yeetmanthecoolman` said: "no windows 11 in bug reports, lol."

Ineed, we need to update the tempalete issues for that.

**Comment by LautaroL20** [comment]
Also, can you be more specific, like which logic gate where you trying to connect, etc..?

**Comment by yeetmanthecoolman** [comment]
NAND SR latches start off in the race position, and if, for example, the map try’s to put it in the hold position, the game crashes because there is no slower gate on a PC.

**Comment by yeetmanthecoolman** [comment]
> > yeetmanthecoolman` said: "no windows 11 in bug reports, lol."
> 
> Ineed, we need to update the tempalete issues for that.

https://github.com/BEEmod/BEE2.4/pull/1855#issue-1320614709
it appears that someone beat you to that.

**Comment by TeamSpen210** [comment]
Ahh you're building an SR latch manually. Logic loops like that can be problematic, if they end up producing an infinite oscillation. Note that there's an SR latch item you can use, which is more robust.

**Comment by yeetmanthecoolman** [comment]
> Ahh you're building an SR latch manually. Logic loops like that can be problematic, if they end up producing an infinite oscillation. Note that there's an SR latch item you can use, which is more robust.

Still, a map with two items behaving exactly as intended shouldn’t instantly crash.

**Comment by yeetmanthecoolman** [comment]
A dumb idea: would a short delay work? Computers are pretty fast and there aren’t many ways for a player to trigger something a billion times a second. Not sure if it is possible, just wondering.

**Comment by yeetmanthecoolman** [comment]
And please remove the more information needed label.

**Comment by TeamSpen210** [comment]
They should have a 0.01s delay in the NOT gates, perhaps that's broken though.

**Comment by TeamSpen210** [comment]
Turns out the delays weren't there indeed.
