### ISSUE TITLE
Dev channel thing

### ISSUE THREAD

**Issue by yeetmanthecoolman** [BEEmod/BEE2.4#1857]
### Description of the feature

There should be some form of dev channel/insider program thing. 

### Why should this be implemented

Because it would allow for the community to get features several months early, and allow you to find bugs and not accidentally do a double take.
i.e https://github.com/BEEmod/BEE2.4/tree/2.4.39.1

**Comment by Konclan** [comment]
You can compile the dev branch yourself at anytime and we do private beta tests
