### ISSUE TITLE
when i load my level it just shuts down the game

### ISSUE THREAD

**Issue by Aperture43** [BEEmod/BEE2.4#1858]
### BEE2 Application Version

current

### BEE2 Package Version

current

### Logs and Reports

```shell
so I'm thinking of just deleting this mod now because its just making me mad. like it was working fine for the first few days  made some good levels and now when I make one and I press play it loads halfway through then shut downs the game and puts me on my desktop screen. I really liked this mod but I might have to delete it if its gonna do this
```

### Additional information

can anyone help me

**Comment by FrozenDragon0** [comment]
You most likely have a corrupt autosave file which would cause the crash.

**Comment by Konclan** [comment]
We can’t help you if you don’t provide any information

**Comment by Aperture43** [comment]
> We can’t help you if you don’t provide any information

i put it on logs and reports

**Comment by FrozenDragon0** [comment]
> > We can’t help you if you don’t provide any information
> 
> i put it on logs and reports

That's not logs and reports... You need to provide actual log information.

**Comment by HeimlichLaboratories** [comment]
> > We can’t help you if you don’t provide any information
> 
> i put it on logs and reports

That's not even useful information

**Comment by Konclan** [comment]
Closing due to lack of information
