### ISSUE TITLE
More Player and Portal Gun models

### ISSUE THREAD

**Issue by ZeynAlex** [BEEmod/BEE2.4#1859]
### Description of the feature

Add some new player models - Mel from PS: Mel, for example
Also 50s-60s and 70s should have custom Portal Gun models and Pedestal variations (but it is more about bee2-itemd).
50s-60s Portal Gun model - Aperture Quantum Tunelling Device, seen in posters.
70s - smth like PS: Mel Portal Gun.

### Why should this be implemented

This will add more OldAp aestetics to these styles

### Additional information

It is done in the Portal:Back to Past mappack

**Comment by FrozenDragon0** [comment]
Mel's portal gun we're not allowed to use as it's specifically stated by Mel's devs they don't want Virgil/Aegis or the Mel gun being used.

**Comment by Konclan** [comment]
Don’t combine issues

**Comment by ZeynAlex** [comment]
Ok, but what about Quantum Tunelling Device (50s Portal gun)?

**Comment by ZeynAlex** [comment]
Could you add function, so ucps can add custom gun models and player models?
