### ISSUE TITLE
High Energy Pellet Catcher not giving power to objects

### ISSUE THREAD

**Issue by lillabofinken** [BEEmod/BEE2.4#1861]
### BEE2 Application Version

4.41.0 64bit

### BEE2 Package Version

4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I hit an Energy Pellet in a Energy Pallet Catcher it reacts like it was hit with its animations but the antline stays blue and it won't power anything, I've tried to power Light bridge, tractor beam, angle panel, stairs, laser emitter and exit door.

### Expected behavior

antlines turn orange and a Lightbridge turns on 

### Steps to reproduce

Step 1: select 50s theme.
Step 2: place an Energy Pellet Catcher.
Step 3: Connect the Energy Pellet Catcher to something like a Light bridge, angled panel or exit door etc.
Step 4: place an Energy Pellet Emitter.
Step 5: Redetect Energy Pellet in to Energy Pellet Catcher  

![20220810172920_1](https://user-images.githubusercontent.com/80794755/183945149-b082614d-2509-4391-91b1-dde9e597e8ff.jpg)
![20220810172748_1](https://user-images.githubusercontent.com/80794755/183946017-c9096659-a5a5-4450-8c00-4cc22c3ea788.jpg)
 

### Additional information

I'm having the issue while using 50s style.   It works fine with the portal 1 theme.

**Comment by LautaroL20** [comment]
You have posted in the wrong section, anything related to items or styles must be posted on the items repository, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the BEEmod user interface, only.
