### ISSUE TITLE
it says portal storys mel is supported and its not

### ISSUE THREAD

**Issue by Darealxbox** [BEEmod/BEE2.4#1863]
when I try to add mel it says it has no editor then why add mel in the help tab 
![image](https://user-images.githubusercontent.com/108944390/184929048-aca92a3c-cec0-406e-ad42-7e307383f6ed.png)

**Comment by TeamSpen210** [comment]
It's not supported as an editor. Hmm, why did I add those mods, kinda silly...

**Comment by TeamSpen210** [comment]
Mel is no longer in the help menu

**Comment by Darealxbox** [comment]
K ty
