### ISSUE TITLE
BEE2 refuses to compile in certain file locations and wont open

### ISSUE THREAD

**Issue by yessir9997** [BEEmod/BEE2.4#1867]
### BEE2 Application Version

4.41.1_win64

### BEE2 Package Version

2.4.41.0_packages

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Refuses to compile in certain file locations and  if i try to open it it comes up with the error "the ordinal 380 could not be located in the dynamic link library C:/Users/Zachary/Desktop/BEE2.exe."

### Expected behavior

it would open and work

### Steps to reproduce

What?

### Logs and Reports

```shell
the ordinal 380 could not be located in the dynamic link library C:/Users/Zachary/Desktop/BEE2.exe.
```

### Additional information

i got it to work all i had to do was put it in a folder

**Comment by Konclan** [comment]
Why is the exe on your desktop? It should be in a folder along with the rest of the files

**Comment by yessir9997** [comment]
i have no idea and i also have no idea how to delete the exe
