### ISSUE TITLE
There was an error building test chamber

### ISSUE THREAD

**Issue by montewyn** [BEEmod/BEE2.4#1868]
Please help. Here is what is written in the console:

VBSP failed.

cond.core._get_cond_group(): No name for module "precomp.faithplate"!
cond.core._get_cond_group(): No name for module "precomp.fizzler"!
vbsp.main(): BEE2.4.41.0 64-bit VBSP hook initiallised, srctools v2.2.3.
cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
cond.core._get_cond_group(): No name for module "precomp.conditions.marker"!
cond.core.import_conditions(): Imported all conditions modules!
vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
vbsp.main(): PeTI map detected!
vbsp.main(): Loading settings...
[W] vbsp.load_settings(): Error: No vbsp_config file!
[E] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
File "compiler_launch.py", line 13, in <module>
File "vbsp.py", line 1857, in main
File "vbsp.py", line 121, in load_settings
File "precomp\template_brush.py", line 417, in load_templates
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/templates.lst'
[12684] Failed to execute script 'compiler_launch' due to unhandled exception!

**Comment by TeamSpen210** [comment]
Try exporting from the app again, looks like a file that it should have made is missing?

**Comment by montewyn** [comment]
> Try exporting from the app again, looks like a file that it should have made is missing?

hmm... I tried to do that, but it didn't work. after your answer everything worked out, thanks.
