### ISSUE TITLE
BEEmod 32 bit on Windows 7 could crash at launch.

### ISSUE THREAD

**Issue by Pixel17** [BEEmod/BEE2.4#1869]
### BEE2 Application Version

2.4.41.0

### BEE2 Package Version

Most Up-To-Date

### What operating system are you running on?

Windows 7 (64bit)

### Logs and Reports

```shell
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 54, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\gameMan.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "app\backup.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "loadScreen.py", line 241, in <module>
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 224, in _Popen
  File "multiprocessing\context.py", line 327, in _Popen
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 81, in __init__
  File "multiprocessing\popen_spawn_win32.py", line 73, in __init__
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
```

### Additional information

How To Replicate (I think) :

Have A Windows 7 64 Bit OS
Run BEEMOD2.4 32 Bit on the latest Version

![what1](https://user-images.githubusercontent.com/106642288/188283510-ae137c66-bab1-45d6-8f90-52102d20497c.PNG)

**Comment by LautaroL20** [comment]
Thats a weird crash, I have never experienced that when using BEEmod 32 bit on Windows 7. Are you sure you are using the same version of the app and packages as well as installing them correctly?

**Comment by LautaroL20** [comment]
Well, the user doesn´t look like he is answering anytime soon, but regardless of that, as a Windows 7 user who I am, the latest version of BEEmod 32 bit works pretty well for me and I haven´t seen any other Win 7 user reporting issues like this on Discord, so the crash issue may be in your side (not installing BEEmod correctly, firewall blocking important files of the app, not having full administrator permissions, etc.).

**Comment by Pixel17** [comment]
> Well, the user doesn´t look like he is answering anytime soon, but regardless of that, as a Windows 7 user who I am, the latest version of BEEmod 32 bit works pretty well for me and I haven´t seen any other Win 7 user reporting issues like this on Discord, so the crash issue may be in your end (not installing BEEmod correctly, firewall blocking important files of the app, not having full administrator permissions, etc.). 

Sorry for the late response it just NOW gave me the notification, I have made sure I've installed it correctly, Downloading the most recent release, extracting, Adding the packages, And running and it doesn't work. I'll try some things with a firewall or something but I don't know.

**Comment by LautaroL20** [comment]
> Pixel17 said: "I'll try some things with a firewall or something but I don't know."

You must exhaust all possible instances on your end before reporting an issue, because I did not see any other Win 7 user reporting this specific crash. Are you sure you have the latest drivers for Win 7 such as visual c++, Microsoft .NET, etc? Which version of Windows 7 are you using? Professional, Bussiness, enterpise?

**Comment by Pixel17** [comment]
> > Pixel17 said: "I'll try some things with a firewall or something but I don't know."
> 
> 
> 
> You must exhaust all possible instances on your end before reporting an issue, because I did not see any other Win 7 user reporting this specific crash. Are you sure you have the latest drivers for Win 7 such as visual c++, Microsoft .NET, etc? Which version of Windows 7 are you using? Professional, Bussiness, Home, Enterpise?

I am using Windows 7 Professional And I Have the latest update of Visual C++

**Comment by LautaroL20** [comment]
Where did you have installed BEEmod, in the Portal 2 folder or just the desktop?

**Comment by Pixel17** [comment]
> Where did you have installed BEEmod, in the Portal 2 folder or just the desktop?

My Desktop

**Comment by LautaroL20** [comment]
Alright, the few things that are related to this problem that I have been able to see, is that when you try to run a program and this error appears, it could be because the directory / folder name where you installed it or the file name may be written in an unsupported language or the name of that directory or filename may contain symbols or any characters. So, to fix it you just need to change the folder name or filename and write (name it) in English and writte it as simple as possible. Watch the following video to see an expamle of this: https://www.youtube.com/watch?v=GjL2OGSL9yI

**Comment by Pixel17** [comment]
> Alright, the few things that are related to this problem that I have been able to see, is that when you try to run a program and this error appears, it could be because the directory / folder name where you installed it or the file name may be written in an unsupported language or the name of that directory or filename may contain symbols or any characters. So, to fix it you just need to change the folder name or filename and write (name it) in English and writte it as simple as possible. Watch the following video for more information: https://www.youtube.com/watch?v=GjL2OGSL9yI

That didn't work, all my directory is is: C:\Users\Pixel\Desktop\bee

**Comment by Pixel17** [comment]
Hello?

**Comment by LautaroL20** [comment]
Try googling your error as deep as you can: `OSError: [Error 123] The filename, directory name, or volume label syntax is incorrect`, then ensure to choose what you may consider are the most appropriate solutions for it, and if that does not work at all, then ping TeamSpen210 who is the lead developer of BEE2.4 and ask him what can be causing your issue.

**Comment by TeamSpen210** [comment]
The error here is suggesting it can't find the BEE executable, which doesn't make much sense since it's what's running...

**Comment by vrad-exe** [comment]
I don't think we're going to keep supporting the 32 bit/windows 7 version anymore since Steam dropped support
