### ISSUE TITLE
Trojaner

### ISSUE THREAD

**Issue by fluffeliger** [BEEmod/BEE2.4#1873]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

win 64

### What operating system are you running on?

Windows 11

### Description of the bug

I just made a virus check and the result is... there is one?
https://www.virustotal.com/gui/file/0cac94f6c81878329ada278eb4dcfc2fbfd2f3f892d521ce16234be46ba8f5f2/detection

### Expected behavior

I expected no virus xdd

### Steps to reproduce

Go to https://www.virustotal.com/gui/home/upload and upload BEE2_v4.41.1_win_64.zip

**Comment by HeimlichLaboratories** [comment]
BEE2 tends to give false alarms (antivirus software does this a lot of times), you're fine

**Comment by fluffeliger** [comment]
okay thanks :D
