### ISSUE TITLE
Cameras on the floor

### ISSUE THREAD

**Issue by Bautler** [BEEmod/BEE2.4#1875]
### BEE2 Application Version

4.42.0

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

Hello!

I have no idea from Github and im apologize when im do something wrong here...

So, when i start map there is 2 a Security Cameras on the floor. Entry and Exit door. I have remove the Monitor pack but it´s not working. Cameras still there.

![20221018205653_1](https://user-images.githubusercontent.com/116113672/196533410-b1b182e6-90b9-4347-8579-9cd6dc339118.jpg)

### Expected behavior

Ehm.. that it working?

### Steps to reproduce

See Problem...

**Comment by LautaroL20** [comment]
Lol, that issue looks really weird, the cameras gone nuts...

**Comment by Marcel505526** [comment]
Hello, i have the same problem. How did you solve it?

**Comment by Nesteroid** [comment]
> Hello, i have the same problem. How did you solve it?

This has been addressed in the next release. Use the older version of beemod for now.

**Comment by Marcel505526** [comment]
> > Hello, i have the same problem. How did you solve it?
> 
> This has been addressed in the next release. Use the older version of beemod for now.

oh, ok thanks

**Comment by BigSmartBear** [comment]
Yeah, I have the same issue
