### ISSUE TITLE
Steam Deck support.

### ISSUE THREAD

**Issue by Lolbot101lol** [BEEmod/BEE2.4#1876]
### Description of the feature

Please make a version of the mod that works on Proton so we can use it on the Steam Deck made by the company known as Vavle that also made Portal 2.

### Why should this be implemented

It would let us use it on the Steam Deck way easier.

**Comment by Luke18033** [comment]
What happens if you try to run it in Proton currently? We also theoretically could build a native Linux version, but TeamSpen's not sure of the best way to package/distribute that.

**Comment by Lolbot101lol** [comment]
I put all the files into the right places at leat I think I did but I couldn't run the program used to add the new testing elements into the game meaning all I did was just add more files to some folders try it yourself if you don't believe me as I could have done something wrong. But I'm really sure that the issue is the program you have to use the edit the menu in the map editor to add the testing elements doesn't run on Linux due to there being only a windows version of it.

**Comment by Luke18033** [comment]
I meant are there any specific error messages that appear, I don't have a Steam Deck to try it myself (and I don't think TeamSpen does either)

**Comment by Lolbot101lol** [comment]
No not that. I can remember this was like a few months ago. If I remember right I would try to open it and, nothing would happen. I'm sure if there was an error code you could get it by trying it on Linux

**Comment by Lolbot101lol** [comment]
I believe you can use the same os on the steam deck on pc for free.

**Comment by haydenwalker980** [comment]
bump

you can compile from source to get it working natively on Linux but as it's been a while since ive last been here I'm not sure how compatibility has improved or worsened

**Comment by vrad-exe** [comment]
Closing in favor of other issues which go into more specific problems the Linux version has
