### ISSUE TITLE
Found the bug with BTS textures!

### ISSUE THREAD

**Issue by Funrollercoaster606** [BEEmod/BEE2.4#1879]
### Description of the feature

So, i have discovered that one of the rooms actually turns sideways, causing the entryway to be broken and disappear. Hopefully, this can help.

### Why should this be implemented

I think this should be done as the only way to add the feature back is to program it yourself.

**Comment by Luke18033** [comment]
Not sure what this is about, the BTS style was removed and isn't supported anymore

**Comment by Funrollercoaster606** [comment]
I was fooling around with the files and accidentally fixed BTS style..  Sort of. Still has a few issues. One of the issues was sometimes that window at the entrance would not appear. I created a whole video about this. https://www.youtube.com/watch?v=y3VFN3M4riI&t=4s
No point continuing here, i've submitted this and now i will go do other things- Like go outside, or work on C# projects of mine.
Bye!

**Comment by LautaroL20** [comment]
BTS Style has lot of leaks and inconsistencies and that is why it was removed from BEEmod, I highly doubt you will be able to fix the whole style.
