### ISSUE TITLE
not loading... something i dont know

### ISSUE THREAD

**Issue by skullin** [BEEmod/BEE2.4#1881]
### BEE2 Application Version

4.42.0 64 bit

### BEE2 Package Version

4.42.0

### What operating system are you running on?

windows 

### Description of the bug

for some reason when i try to publish it sais this as an error in console

VVIS failed.

Valve Software - vvis.exe (Nov 14 2021)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1668561071.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1668561071.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1668561071.prt

i have no idea what this is help

### Expected behavior

i expected to have it load normaly

### Steps to reproduce

i dont know help

### Logs and Reports

```shell
VVIS failed.

Valve Software - vvis.exe (Nov 14 2021)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1668561071.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1668561071.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1668561071.prt
```

### Additional information

im using overgrown style but it seems to happen everywhere

**Comment by HeimlichLaboratories** [comment]
Seems like a leak. Overgrown style had tons of leaks problems, seems like it still does.

**Comment by Luke18033** [comment]
There's a [leak](https://developer.valvesoftware.com/wiki/Leak) in your map. If you're using any items from user created packages, try removing them from the map to see if they're the cause of the leak. Otherwise, if the issue persists, go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by Luke18033** [comment]
Closing due to lack of response
