### ISSUE TITLE
a special panel

### ISSUE THREAD

**Issue by mikehowler** [BEEmod/BEE2.4#1883]
### Description of the feature

there should be a special panel item that is the logo for aperture [changes for old aperture]

### Why should this be implemented

it would allow for better looking areas in chambers, like a behind the scenes area,

**Comment by Critfish** [comment]
Puzzlemaker is horribly ill-equipped for designing any kind of BTS area, so I highly doubt BEE's developers are too keen on adding new items specifically for making BTS areas.

See the FAQ's statement regarding BTS style for further details.

**Comment by mikehowler** [comment]
> Puzzlemaker is horribly ill-equipped for designing any kind of BTS area, so I highly doubt BEE's developers are too keen on adding new items specifically for making BTS areas.
> 
> See the FAQ's statement regarding BTS style for further details.

no i mean that i want a panel that has a logo not bts areas

**Comment by HeimlichLaboratories** [comment]
Why would you want an Aperture logo in a test chamber? Adding logos and signs to test chamber is generally a no-no, you really need the flexibility of Hammer and make a full on custom style for it to be acceptable. It's not specifically about BTS areas, the puzzlemaker is just not equipped to add detailing, and shouldn't.
