### ISSUE TITLE
Invisible Killzone

### ISSUE THREAD

**Issue by mikehowler** [BEEmod/BEE2.4#1884]
### Description of the feature

Working Like A Lazer Field, it would be completley invisible during normal play.

### Why should this be implemented

This  Would Allow For Making Zones That Are Reachable, But Not Meant To Be Entered.

### Additional information

think of a invisible lazerfield

**Comment by Critfish** [comment]
This is pointless, just don't include the out of bounds area to begin with, or use a normal laserfield.

**Comment by FrozenDragon0** [comment]
There's literally no use for this, getting killed by going into an area of a test chamber your not supposed to reach would just be annoying.

Also this is posted in the wrong section.
