### ISSUE TITLE
Default to PTI thumbnails

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1887]
Unless you know how to use auto thumbnails properly (pressing F5 to retake it from a specific location), they usually end up just showing a random section of the chamber near the entrance, wherever you happened to look when the screenshot was taken. This usually makes them less useful than the editor views used in vanilla, so I propose making PeTI mode the default and only using auto thumbnails if the user specifically selects them in the app (in which case they'll probably see the tooltip explaining F5)

I'd also suggest changing the label from "PeTI" to "editor view" to more immediately specify what it does.

**Comment by TeamSpen210** [comment]
That probably is a good idea, though any existing users will keep the existing setting.

**Comment by Luke18033** [comment]
Could rename the option internally so it resets (I did that with voiceline priorities) or just leave it since this would mainly be for new users anyway.
