### ISSUE TITLE
Adhesion Gel

### ISSUE THREAD

**Issue by Akkorokami** [BEEmod/BEE2.4#1889]
### Description of the feature

The adhesion gel is a purple like gel that was originally implemented into the vanilla game but was scrapped. The unique characteristics about the gel is the ability to stick to surfaces that were otherwise unreachable.  This was valve's way of allowing the change of gravity without needing to do so. In addition, covering cubes with said gel could allow them to stick to walls just as the player would. 

### Why should this be implemented

By implementing the adhesion gel into the beemod editor, it could allow for more advanced puzzles to built that need "outside of the box" thinking. For example, using the gel to reach a wall linked pedestal button or flinging a adhesion covered cube so it stick to a button on the ceiling.

**Comment by LautaroL20** [comment]
Wow, no one had ever suggested that item before, thank you very much for enlightening us with the idea of implementing the "Adhesion Gel". Well, not really...  I am sorry to have to inform you that you are user number 1.000.0000.000 in suggesting an item impossible to implement like this, due that this item would require source code access. If you have ever bothered at reading the [FAQ](https://github.com/BEEmod/.github/blob/master/FAQ.md), you would have not wasted your time at posting this.
