### ISSUE TITLE
Half walls placed out of bounds cause tiling system to break down

### ISSUE THREAD

**Issue by Akkorokami** [BEEmod/BEE2.4#1891]
### BEE2 Application Version

4.42.0

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

While I was creating a test chamber to post onto the steam workshop, I tried to play the preview and noticed that certain flat walls were placed in weird areas that stopped progression. In addition, the goo covered floor was removed and replaced with a singular texture that was made up of said walls. This has never happened before and has just started. Here is the original chamber in the editor compared to the preview.
**Editor:** 
![20221213133025_1](https://user-images.githubusercontent.com/99097022/207417489-c15ca6f1-ceb1-41ea-8ca0-b3965a2e2b6e.jpg)
**In game:**
![20221213133033_1](https://user-images.githubusercontent.com/99097022/207417481-6a535701-0ff6-421b-b3a2-00d0aea22fb1.jpg)

### Expected behavior

After rebuilding the chamber and playing it, I expected it to be exactly what the editor showed. Instead, it would replace elements with flat walls and overall, make the puzzle impossible to complete. 

### Steps to reproduce

As much as it doesn't help, I'm unsure on what is causing this bug to take effect. Like mentioned before, it just started taking place and hasn't happened before hand when using Beemod. 

### Additional information

The chamber uses clean style and uses these elements:
![20221213134057_1](https://user-images.githubusercontent.com/99097022/207417947-3918d8b9-6781-4cb3-be7a-104bd389da7b.jpg)

On some instances,  as some elements are put into the chamber, everything seems normal; however, other times it ends up like the image shown in the description of the bug. In a way, it comes and goes when it feels like it.

**Comment by LautaroL20** [comment]
This is probably caused by an item which is breaking the compiler. Try deleting one item at a time then compile the map until the issue no longer happens, this way you will identify the item that is causing this issue.

**Comment by Akkorokami** [comment]
Nope, didn't work. I deleted each item as you said, but couldn't find the one that stood out. I even tried it with new elements but it didn't work

**Comment by LautaroL20** [comment]
So, this issue will happen to you even in an empty map, or it no longer happens?

**Comment by Luke18033** [comment]
Epic tiling fail. Could you go to `Portal 2/portal2/puzzles/<your steam ID>/`, find the `.p2c` file for this map (it'll have an accompanying thumbnail). and upload it here so we can try and figure out what went wrong?

**Comment by Akkorokami** [comment]
It seems to happen in that chamber only; however, I tried doing empty maps and they work just fine, except sometimes they force me to revalidate my p2 files. Here is the link to the .p2c file for the chamber: 

https://drive.google.com/file/d/1HBH1md8QbSXjkG1eMipNh8BSDWLX2bdM/view?usp=share_link

If it isn't the right file, then I have one other .p2c in the steam id folder so there's that lol

**Comment by LautaroL20** [comment]
We'll see what Luke18033 finds on your file, so the compiler can be improved to prevent things like this issue.

**Comment by Akkorokami** [comment]
Hopefully something useful 😅

**Comment by Luke18033** [comment]
This is P1 style, but the bug still happens. It seems to be caused by these half walls floating out of bounds near the exit:
![image](https://user-images.githubusercontent.com/19228201/208269367-224825c7-ec0d-46c3-a5ee-b89121a396a9.png)
Removing them and recompiling fixes the bugged surfaces:
![image](https://user-images.githubusercontent.com/19228201/208269344-3fb9495e-bcab-423a-b32d-064982fa5145.png)

**Comment by Akkorokami** [comment]
Interesting, I've never seen this happen before in my week of experience with Beemod. How is this bug causing the walls out of bounds? I'm especially curious since you can't see them in the normal editor.

**Comment by Luke18033** [comment]
The Half Wall items are placed out of bounds in the editor, and they're not visible from the back. Look at the exit platform from the same angle as in my screenshot, you should see them there and you can just select them and delete them.

**Comment by Luke18033** [comment]
They ended up there because half wall items don't automatically move when you change the chamber geometry like other items do. I'd assume you originally had a part of the map there, but later moved that wall forward to create the exit platform and the items got left behind.

We can't really fix half walls not automatically moving (it's an editor limitation), but out-of-bounds half walls should just be ignored, instead of breaking the whole tiling system like this.

**Comment by Akkorokami** [comment]
Found them, thank you for noticing this. Good to know that they don't move when you mess with the layout of the chamber.

**Comment by TeamSpen210** [comment]
That's very interesting. Those shouldn't really break anything, just generate tiles in the void which VBSP would then ignore.

**Comment by Akkorokami** [comment]
The only thing that it technically breaks is the goo covered floor. Other than that, it just generates walls that make it impossible to complete the chamber

**Comment by Luke18033** [comment]
Yeah that shouldn't be happening.

**Comment by TeamSpen210** [comment]
Okay this is basically causing a "leak" in my compiler code, breaking all sorts of logic since there's no longer an inside/outside of the map.
