### ISSUE TITLE
Ensure error server shuts down when game is closed

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#1894]
If a compile error occurs and Portal 2 is then closed without resolving the error, the server can remain running in the background, causing Steam to think the game is still open. It should probably periodically check for the `portal2` process running, and shut down if it can't find it.

**Comment by TeamSpen210** [comment]
It currently will shut down automatically after 5 minutes, but looking for Portal 2 would be a good idea as well.
