### ISSUE TITLE
BEE2 entities no longer get written into FGD

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1896]
BEE2/HammerAddons entities appear to no longer get written into Portal 2's FGD, causing leaks.

**Comment by TeamSpen210** [comment]
Do you have the `// BEE2 EDIT FLAG` set to zero in your FGD, or Preserve Resources enabled? Both of those will stop it from editing the FGD.

**Comment by Luke18033** [comment]
The BEE2 flag wouldn't have been there since it was a default FGD (Steam randomly decided to validate game files), but I did have preserve resources enabled probably, didn't realize that affected the FGD modification.

**Comment by TeamSpen210** [comment]
I changed it recently, but it probably should be a separate config option.
