### ISSUE TITLE
Crashes after booting with Windows 7

### ISSUE THREAD

**Issue by Yexiaowei11** [BEEmod/BEE2.4#1903]
### BEE2 Application Version

4.4  x64

### BEE2 Package Version

4.4

### What operating system are you running on?

Windows 7 (64bit), Windows 7 (32bit), Other

### Logs and Reports

```shell
Issue signature:
  PROBLEM EVENT NAME: APPCRASH
  Application name: BEE2.exe
  Application version: 0.0.0.0
  Application timestamp: 634e0b76
  Faulty module name: python39.dll
  Fault module version: 3.9.12150.1013
  Fault module timestamp: 623BB36C
  Exception code: c0000005
  Exception offset: 00000000000253d3
  OS version: 6.1.7601.2.1.0.256.1
  Locale ID: 2052
  Additional Information 1: A18B
  Additional information 2: A18B0157B03FCA286868331740AA5E46
  Additional Information 3: B0A1
  Additional information 4: b0a1558bd112c2058b317dc46d01bbe0

Read the privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

If you can't get the online privacy statement, please read our privacy statement offline:
  C：Windowssystem32zh-CNerofflps.txt
```

### Additional information

Python 3.5.1 x32 is available on your computer

Copy the file to VMware's Windows 10 (official image) but run normally

**Comment by Yexiaowei11** [comment]
Could it be a Python 3.5.1 x32 issue ？

**Comment by Yexiaowei11** [comment]
Microsoft Visual C++ 2005~2019 version is all installed
Microsoft .NET Framework versions: 4.8 and 4.7.2

**Comment by LautaroL20** [comment]
Well, your issue is very confused, you mentioned you are using the 32 bit version of Win 7 but at the same time you have a 64 bit version of Win 7, if you can clarify your info, I may help you.

**Comment by Yexiaowei11** [comment]
> 吧，您的问题非常混乱，您提到您使用的是 32 位版本的 Win 7，但同时您使用的是 64 位版本的 Win 7，如果您能澄清您的信息，我可能会为您提供帮助。
是 WIN 7 64

**Comment by LautaroL20** [comment]
There are two BEE2.4 versions, one of 32 bits and another of 64, which one did you install?

**Comment by Luke18033** [comment]
You have to use the 32-bit version of BEE2 on Windows 7 even if you have a 64-bit system, they're compiled with different Python versions.

**Comment by LautaroL20** [comment]
Yep, the most likely reason is that he´s probably trying to execute the 64 bit BEEmod version on Win 7, and the fact that the author only speaks Chinese doesn't help much to try to think of other causes...
