### ISSUE TITLE
Cameras appear on ground in front of door

### ISSUE THREAD

**Issue by BigSmartBear** [BEEmod/BEE2.4#1905]
### BEE2 Application Version

4.42.0

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Whenever creating a map, the camera is on the ground one voxel away rather than next to the door on the wall. This did not occur in the old version.
![20221223175734_1](https://user-images.githubusercontent.com/101303364/209411842-87359739-baaf-43ff-ba59-1592db6daf9f.jpg)
![20221223175739_1](https://user-images.githubusercontent.com/101303364/209411844-aeed7cb2-b0a5-4ea5-aff7-d5d2bfe5cb99.jpg)

### Expected behavior

the camera to be on the wall next to the entry and exit doors

### Steps to reproduce

1. create a map with an entry and exit door
2. play the map

### Logs and Reports

```shell
N/A
```

### Additional information

I am using clean style.

**Comment by HeimlichLaboratories** [comment]
#1875, it was reported already

**Comment by BigSmartBear** [comment]
You're right- no need for duplicate.
