### ISSUE TITLE
Latest (or most popular) community puzzle previews

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1907]
### Description of the feature

So, the current splashscreen just uses preset replaceable images. However, i suppose it is possible to download a few images of the most popular or latest community puzzles from the workshop. However, i don't think usage of this should be forced, so maybe make this an option in the settings that's off by default.

### Why should this be implemented

This might give users inspiration to build awesome puzzles!

### Additional information

One potential way to implement this is to:
1. On app startup, download any number (for example 8) of the images or thumbnails of the latest or/and most popular community puzzles.
2. If doesn't already exist, create a folder in the BEE2 directory, maybe called 'images_steam'?
3. Delete all contents of folder
4. Move downloaded images into folder
5. Pick random one as the splashscreen image, clearly doable as it's used for the predefined splashscreens already
(hope this isnt too hard to implement)

**Comment by Critfish** [comment]
Several issues with this:

- There's no way for the system to know which puzzles are actually made with BEEMod. It could be grabbing Hammer maps, or even just bog-standard PeTI maps.
- Images would be grabbed without consent of the map authors. The problem with this should be obvious.
- The workshop front page is complete trash most of the time, so this probably wouldn't be very good at achieving its intended goal of inspiring people.

**Comment by TPEcool** [comment]
> Several issues with this:
> 
> * There's no way for the system to know which puzzles are actually made with BEEMod. It could be grabbing Hammer maps, or even just bog-standard PeTI maps.
> * Images would be grabbed without consent of the map authors. The problem with this should be obvious.
> * The workshop front page is complete trash most of the time, so this probably wouldn't be very good at achieving its intended goal of inspiring people.
oh okay

**Comment by TPEcool** [comment]
> * The workshop front page is complete trash most of the time, so this probably wouldn't be very good at achieving its intended goal of inspiring people.

Well, then most popular puzzles, then? I mean, if they're popular they're probably not garbage

**Comment by TPEcool** [comment]
As for consent, though, perhaps only grab images from the chambers of a few specific mapmakers who have agreed with grabbing images?
Hammer maps would likely be okay, and so will be PTI maps, i suppose.

**Comment by Critfish** [comment]
> > * The workshop front page is complete trash most of the time, so this probably wouldn't be very good at achieving its intended goal of inspiring people.
> 
> Well, then most popular puzzles, then? I mean, if they're popular they're probably not garbage

The problem with Portal 2's workshop is that most people just rate up anything that happen to complete. This means dumb, easy puzzles get more popular than well-made, challenging ones. Then consider the fact that a lot of these maps bank on the novelty of custom BEEMod elements and styles to get more ratings, and you end up with a lot of trash cropping up on the list of most popular maps within the last week. You can't grab the most popular maps of all time either because they almost never change, so you'd get shown the same maps over and over again.

> As for consent, though, perhaps only grab images from the chambers of a few specific mapmakers who have agreed with grabbing images? Hammer maps would likely be okay, and so will be PTI maps, i suppose. I mean, from screenshots, you can usually make out at least a piece of the captured area's gameplay, so it should still be possible to get inspired by any screenshot.

You could probably have a list of consenting map creators, but at that point, why not just have them provide screenshots of their maps and have those included permanently?

I also think you're misunderstanding what the splash screens are for. They're mainly to show off BEEMod's features, which is why they prominently feature new items and visual features. Showing off regular PeTI maps isn't going to wow anyone, and showing off Hammer maps is effectively false advertising.

Also consider the fact that not all workshop maps feature plain screenshots of the map. Most don't even have more than one image. This means if the thumbnail has text or graphics on it, that'll show up on the splash screen, potentially being cut off or overlapping with BEE's own text.

I just don't think this is worth it.

**Comment by TPEcool** [comment]
> > > * The workshop front page is complete trash most of the time, so this probably wouldn't be very good at achieving its intended goal of inspiring people.
> > 
> > 
> > Well, then most popular puzzles, then? I mean, if they're popular they're probably not garbage
> 
> The problem with Portal 2's workshop is that most people just rate up anything that happen to complete. This means dumb, easy puzzles get more popular than well-made, challenging ones. Then consider the fact that a lot of these maps bank on the novelty of custom BEEMod elements and styles to get more ratings, and you end up with a lot of trash cropping up on the list of most popular maps within the last week. You can't grab the most popular maps of all time either because they almost never change, so you'd get shown the same maps over and over again.
> 
> > As for consent, though, perhaps only grab images from the chambers of a few specific mapmakers who have agreed with grabbing images? Hammer maps would likely be okay, and so will be PTI maps, i suppose. I mean, from screenshots, you can usually make out at least a piece of the captured area's gameplay, so it should still be possible to get inspired by any screenshot.
> 
> You could probably have a list of consenting map creators, but at that point, why not just have them provide screenshots of their maps and have those included permanently?
> 
> I also think you're misunderstanding what the splash screens are for. They're mainly to show off BEEMod's features, which is why they prominently feature new items and visual features. Showing off regular PeTI maps isn't going to wow anyone, and showing off Hammer maps is effectively false advertising.
> 
> Also consider the fact that not all workshop maps feature plain screenshots of the map. Most don't even have more than one image. This means if the thumbnail has text or graphics on it, that'll show up on the splash screen, potentially being cut off or overlapping with BEE's own text.
> 
> I just don't think this is worth it.

so does that mean that i have to close the issue as not planned?

**Comment by TeamSpen210** [comment]
Probably yeah. You can of course add whatever images you like to the folder.
