### ISSUE TITLE
Starting up a test chamber then proceeding to the second door of the test chamber has a black wall blocking it

### ISSUE THREAD

**Issue by IncinerationCube** [BEEmod/BEE2.4#1916]
### BEE2 Application Version

4.43.0 64-bit

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

![preview0002](https://user-images.githubusercontent.com/122524314/212031950-38beeb81-4f72-42d1-87c6-11df5b7a9064.jpg)
Every time I start up a test chamber or build one, this always happens. When I exit, the second door (no photo due to the console blocking the photo) has this empty skybox repeating image type thing on the borders, and when it opens, there's a black tile blocking the door. Am I using the wrong version?

### Expected behavior

I expect nothing, I don't really know what happened.

### Steps to reproduce

I don't know how to replicate the bug.

**Comment by FrozenDragon0** [comment]
Use the 4.43 package version. Using 4.42 Packages on version 4.43 is most likely causing this.

**Comment by IncinerationCube** [comment]
I can't find the 4.43 packages on the download page.

**Comment by TeamSpen210** [comment]
They're here: https://github.com/BEEmod/BEE2-items/releases/tag/v4.43.0

**Comment by IncinerationCube** [comment]
> They're here: https://github.com/BEEmod/BEE2-items/releases/tag/v4.43.0

![preview0005](https://user-images.githubusercontent.com/122524314/212336271-bc59192d-0fb5-4486-b52c-34c62921847e.jpg)
I tried the packages but they failed and ultimately did this again

**Comment by Luke18033** [comment]
Go in your BEE2 settings, hit "reset package caches", and then re-export, see if that fixes it.

**Comment by Konclan** [comment]
Closing due to lack of response
