### ISSUE TITLE
Visual Spoilage

### ISSUE THREAD

**Issue by atomupgrader** [BEEmod/BEE2.4#1918]
### BEE2 Application Version

2.4.43.0 64bit

### BEE2 Package Version

2.4.43.0

### What operating system are you running on?

Win10-64bit
### Description of the bug

White panel have visual artifacts (transparent yellow square and number 8)
![1](https://user-images.githubusercontent.com/13979618/213438503-a65bc5b0-412d-41ba-a5b0-99161a7f3031.png)

### Expected behavior

clean white appearance

### Steps to reproduce

1. Create standart new chamber
2. Compile and look (on right wall)

**Comment by Critfish** [comment]
This is literally just a regular Portal 2 texture.

**Comment by LautaroL20** [comment]
If you don´t like these kind of walls that have "artifacts", you should choose "Original Clean" on the style options.

**Comment by atomupgrader** [comment]
i think that style must be defaulf, ARTIFACTS is looks really unacceptable

**Comment by FrozenDragon0** [comment]
> i think that style must be default, ARTIFACTS is looks really unacceptable

It's literally just a regular Portal 2 texture, use original clean if you don't like it.
