### ISSUE TITLE
Upgrading machine for the portal gun

### ISSUE THREAD

**Issue by BlinkWOW** [BEEmod/BEE2.4#1920]
### Description of the feature

Improvement for the portal gun. It will be placed in front of the portal weapon rack (on the wall), if you put the portal weapon on the stand, the machine will start. This machine upgrades the portal gun with an orange (or blue) portal, adding a portal. Can also destroy one portal. You can also make it so that before passing the camera, a person must lose the portal or add it, after that the machine opens the door (if it is connected), if the door is not connected (or some other object), then the machine simply destroys the player’s portal or adds portal.

### Why should this be implemented

I think this machine will help to make more maps and more interesting gameplay.

### Additional information

Video with this idea: https://youtu.be/duAeq1lDRsE

**Comment by Konclan** [comment]
Useless, obsolete, overcomplicated
