### ISSUE TITLE
question/request 

### ISSUE THREAD

**Issue by tkiepuszew** [BEEmod/BEE2.4#1922]
is it possible to not have the elements tab and just a whole fricking beemod list of things? or if you  can then please add some more tabs

**Comment by CardsAndGamesYT** [comment]
There unable to change the way the pallet in game worked due to it being hard coded. The only thing changeable are the actual item in it.

**Comment by HeimlichLaboratories** [comment]
No, it's hardcoded. And this has been posted several times.

**Comment by FrozenDragon0** [comment]
And for clarification, if this was possible it would've already been done a long time ago.
