### ISSUE TITLE
Packages folder missing from built application install

### ISSUE THREAD

**Issue by EnrichmentConstruct2099** [BEEmod/BEE2.4#1924]
### BEE2 Application Version

BEE 2 4.43.0 win64 bit

### BEE2 Package Version

BEE 2 4.43.0 (both music and normal packages)

### Description of the bug

When Attempting to install program and merge files, program cannot locate packages due to a directory error. Investigation and experimentation revealed that the program does not have a dedicated package file that the previous versions would have files unzip to. 

### Expected behavior

When extracting and merging music and item files to BEE 2 4.43.0, I expected the files to be in a dedicated folder named "packages" like previous versions. 

### Steps to reproduce

1. Install BEE2 like normal with most recent version.
2. Unzip BEE2_v4.43.0_win64
3. Extract BEE2_v4.43.0_packages to BEE2_v4.43.0_win64
4. Extract BEE2_v4.43.0_music_packages to BEE2_v4.43.0_win64 

### Additional information

Simply renaming the unzipped normal package folder to "packages" (yes its caps sensitive), then moving the music packages to the renamed file seems to be a temporary workaround. However, I can't guarantee that will make the program run and inject the packages correctly without further testing.

**Comment by TeamSpen210** [comment]
This will work perfectly fine, it's just how I happened to zip them up into the archive. I should fix that.
