### ISSUE TITLE
Chamberlock locks itself completely before going trough it

### ISSUE THREAD

**Issue by psyklon-project** [BEEmod/BEE2.4#1926]
### BEE2 Application Version

4.41.1

### BEE2 Package Version

4.41.1

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

If you place a chamberlock in a way that it's possible to reach its backside, it will never open after you did that.

### Expected behavior

I think it should still open upon activation as long as you not activated AND not walked trough it before. It seems like there's a trigger attached where, but it does not check if the chamberlock was ever activated.

### Steps to reproduce

Step 1: Place a chamberlock so that it's possible to see and reach its backside.
Step 2: Walk to the chamberlock.
Step 3: Try to open it from the front side. You can't!

Here's a simple configuration on the attached screenshots (the trigger area is marked with a portalable surface).
![20230210093250_1](https://user-images.githubusercontent.com/35834994/218043408-06bd730f-4670-4c0e-982d-b211689cb7db.jpg)
![20230210091051_1](https://user-images.githubusercontent.com/35834994/218043411-9e9e7b8c-880f-4fe5-98f5-b731d59f8ed5.jpg)

**Comment by FrozenDragon0** [comment]
Update your BEE2 and packages version to the latest one 4.43 as using an old outdated version is likely the cause for this. If this still happens on 4.43 then please re-open this issue.

Also you have posted in the wrong section.
