### ISSUE TITLE
Unable to modify VPK's correctly

### ISSUE THREAD

**Issue by DerpBoxsrandomaccount** [BEEmod/BEE2.4#1929]
### BEE2 Application Version

4.41.1 64-bit

### BEE2 Package Version

4.39.1, but I also have some UCP's installed.

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I'm trying to make a few minor changes and add stuff to the VPK files.
But whenever I put files into vpk_override, they appear in the files as blank models. Materials and sounds come up empty as well.
Yes, I am following the correct layout.

### Expected behavior

I expected the files to show up normally.

### Steps to reproduce

1. Put files in steamapps/common/Portal 2/vpk_override.
2. Restart Bee2Mod.
3. Export.
4. Attempt to load the modified resource in game or in HLMV.

### Logs and Reports

```shell
No logs. :(
```

### Additional information

[brokenrtxgun.zip](https://github.com/BEEmod/BEE2.4/files/10760288/brokenrtxgun.zip)
[rtxgun.zip](https://github.com/BEEmod/BEE2.4/files/10760297/rtxgun.zip)
Yes, i know it's missing the DX80, but it doesn't seem to matter.

**Comment by Luke18033** [comment]
I'd recommend not using the `vpk_override` folder and just putting custom VPKs in `portal2_dlc4` instead. I'm not sure why it seems to be modifying the file contents.

**Comment by DerpBoxsrandomaccount** [comment]
I re-validated the files and cleared the vpk_override. It's fixed now. I'll use the dlc folders in the future.
