### ISSUE TITLE
Incorrect Entrance Corridor

### ISSUE THREAD

**Issue by Gmv-2000** [BEEmod/BEE2.4#1932]
### BEE2 Application Version

4.43.0 (64bit)

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I select an entrance corridor, it is shown selected, but the game shows the wrong one.
![Screenshot 2023-03-04 133036](https://user-images.githubusercontent.com/126981240/222922909-a935a1d8-115c-49ee-b4c6-31aaece1143b.png)
![Screenshot 2023-03-04 133655](https://user-images.githubusercontent.com/126981240/222923099-4904bce3-f8c0-4779-9f43-172a9a1ae51e.png)
These pictures seem very different, do they not?

### Expected behavior

I expect the entrance corridor to be the one I selected.

### Steps to reproduce

I don't really know, but here it is:
1. Select an entry corridor.
2. It may come out different from what you expected.

### Additional information

I believe it is in any style, but I first noticed it when playing the Overgrown style. One of my theories is that there is some sort of randomizer. Is this true?

**Comment by TeamSpen210** [comment]
It's randomised yeah. It's a little tricky to design this UI. Maybe I need to add a description. You drag corridors between the top and bottom sections to pick which are used - it'll pick a random one from the "selected" section.

**Comment by Gmv-2000** [comment]
> It's randomised yeah. It's a little tricky to design this UI. Maybe I need to add a description. You drag corridors between the top and bottom sections to pick which are used - it'll pick a random one from the "selected" section.

Thank You!
