### ISSUE TITLE
"leak" being shown in a brand new test chamber.

### ISSUE THREAD

**Issue by Killergamerboi16** [BEEmod/BEE2.4#1934]
### BEE2 Application Version

4.430.0

### BEE2 Package Version

4.430.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

![Screenshot 2023-03-07 181423](https://user-images.githubusercontent.com/127270430/223602047-52d0d37b-77a4-41db-994e-f850f1e8ac5a.png)
Hello, I just made this account (lol) but there's a bug, whenever I load into a new chamber, it says that the test chamber has a leak, but I don't know why it happens, like even brand new, it still happens.

### Expected behavior

I expected for no leaks to happen.

### Steps to reproduce

Step 1: I just made a new test chamber.
Step 2: I try to load it but then it says that there's a leak in the map that haven't even changed. 

### Additional information

for style, I am using Og clean.

**Comment by Luke18033** [comment]
Do you have any UCPs? (If you don't know what those are, the answer is no)

**Comment by Killergamerboi16** [comment]
yeah I do.

**Comment by HappyGIOGIO** [comment]
This has been happening to me, what is a UCP?

**Comment by FrozenDragon0** [comment]
> This has been happening to me, what is a UCP?

User created packages.

**Comment by Darealxbox** [comment]
I have been using the same ucps for a while but this is happening now? i have portal reloaded installed if that could make issues

**Comment by lAlexRich** [comment]
I literally have no ucps, no other portal 2 mods, and this is happening to me in a literal BRAND NEW test chamber. "Your map has been leaked, it's somewhere in the void and we do not care."

**Comment by lAlexRich** [comment]
I literally have no ucps, no other portal 2 mods, and this is happening to me in a literal BRAND NEW test chamber. "Your map has been leaked, it's somewhere in the void and we do not care.".

**Comment by User55555555555** [comment]
The elevator room? Mine also leaked in the void

**Comment by lAlexRich** [comment]
After I commented my last comment I redownloaded the BEE2 mod, and now it doesn't happen, but sometimes still happens with panels, if you put them somewhere in the corner.
