### ISSUE TITLE
Wrong Behavior of Catwalks (nothing to do with items)

### ISSUE THREAD

**Issue by ZeynAlex** [BEEmod/BEE2.4#1955]
### BEE2 Application Version

4.43.0 64bit

### BEE2 Package Version

4.43.0 64bit + UCPs

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Wall and ceiling supports for catwalks do not generate.
![Снимок экрана 2023-05-31 180256](https://github.com/BEEmod/BEE2.4/assets/100288527/2e355c77-afe3-4681-9e6d-1d69a0060120)
![Снимок экрана 2023-05-31 182127](https://github.com/BEEmod/BEE2.4/assets/100288527/29da1544-25b3-4a1f-b56d-416cc0d8f022)

### Expected behavior

I expect to see my catwalks supported by something, like in photo (this chamber with normal catwalks was made with bee 4.41 and some UCPs)
![Inkedexit_hammer_free](https://github.com/BEEmod/BEE2.4/assets/100288527/5405b540-5710-4196-b83d-089679057e48)

### Steps to reproduce

Place catwalks on wall or ceiling
Connect them
They are levitating

### Additional information

I tried to use older versions of catwalk.beepack but nothing changed

**Comment by TeamSpen210** [comment]
Hmm, this is because the door is there, so it assumes there's just empty space there. I need to take embed space into account.

**Comment by ZeynAlex** [comment]
Same behavior without door when catwalks attached to ceiling.
