### ISSUE TITLE
Discord server bug (Not app srry)

### ISSUE THREAD

**Issue by TheProtoToaster** [BEEmod/BEE2.4#1959]
### BEE2 Application Version

(Latest)

### BEE2 Package Version

(Latest)

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

well my discord invites to it say banned from guild. i never been in the server before so uh what happened?

### Expected behavior

.

### Steps to reproduce

.

### Logs and Reports

```shell
.
```

### Additional information

Discord

**Comment by Konclan** [comment]
We have a discussion forum on the items github for questions. https://github.com/BEEmod/BEE2-items/discussions

If you use a vpn that could be why. Otherwise we'd need your discord tag to check.

**Comment by TheProtoToaster** [comment]
No vpn but discord tag is #9744

**Comment by TheProtoToaster** [comment]
Please reply if you can fix this thanks

**Comment by Konclan** [comment]
You were banned due to having a compromised account. If your account secured I'll unban you
![image](https://github.com/BEEmod/BEE2.4/assets/16567080/952a5426-940c-4fce-bebd-85d0314210ec)

**Comment by TheProtoToaster** [comment]
when did it happen?

**Comment by TheProtoToaster** [comment]
Im sorry for that it will never happen again

**Comment by TheProtoToaster** [comment]
@Konclan im sorry for that, it wont happen again
