### ISSUE TITLE
(NOT BUG/ISSUE) Question for discord server

### ISSUE THREAD

**Issue by TheProtoToaster** [BEEmod/BEE2.4#1961]
### BEE2 Application Version

(Latest)

### BEE2 Package Version

(Latest)

### What operating system are you running on?

_Windows 10 x64_

### Description of the bug

I hope a mod responds but i will do anything to get unbanned from the BEEmod discord server.

**Comment by TheProtoToaster** [comment]
anything?

**Comment by MarcusKubis9** [comment]
What the fuck did you do

**Comment by TheProtoToaster** [comment]
well i got banned 2 years ago
and im just now talking about it

**Comment by FrozenDragon0** [comment]
> well i got banned 2 years ago and im just now talking about it

What is your Discord name?

**Comment by TheProtoToaster** [comment]
> > well i got banned 2 years ago and im just now talking about it
> 
> What is your Discord name?

Purple Protogen#9744

**Comment by TheProtoToaster** [comment]
another mod said i got banned for nitro scamming

**Comment by FrozenDragon0** [comment]
> another mod said i got banned for nitro scamming

Seems you've been unbanned already, in regards to Nitro scamming, you might've fallen for one of those scams and gotten your account compromised back then which would explain the ban.

**Comment by TheProtoToaster** [comment]
ohhh alright
thank you
