### ISSUE TITLE
BEEmod is installed yet nothing in Portal 2 is actually changing.

### ISSUE THREAD

**Issue by DefNotDylan** [BEEmod/BEE2.4#1963]
I've been trying to install BEEmod for 2 days now and I can't seem to get it to work. The actual application works just fine but when I open Portal 2 nothing is actually changed. I think it might be important to note that I have Portal 2 and BEEmod installed on a separate drive from C:. That's really the only thing I can think of that would mess it up other than maybe I installed the packages wrong. If anyone could help, it'd be much appreciated!

**Comment by TheProtoToaster** [comment]
did you install the beemod packages, unzipped it, renamed it to packages, and then put in in beemod folder?

If you did open the beemod.exe and then drag stuff u want to the bar and open Export and Export to portal 2

**Comment by TheProtoToaster** [comment]
did you export the pallet to portal 2?

**Comment by DefNotDylan** [comment]
Is exporting the pallete to Portal 2 separate from just pressing the Export to "PORTAL 2" button?

**Comment by DefNotDylan** [comment]
And yes I have the packages and everything installed.

**Comment by TheProtoToaster** [comment]
well press the P button above the pallet

and press export to portal 2

**Comment by TheProtoToaster** [comment]
on the window pop up thing

**Comment by DefNotDylan** [comment]
I just tried to export it and this time it threw an error.
"Compiler file bin/vrad.exe missing. Exit Steam applications, then press OK to verify your game cache. You can then export again."
Although I just checked Portal 2's bin and there does appear to be vrad.exe there.

**Comment by DefNotDylan** [comment]
Nevermind, I figured it out. For some reason, I had 2 different Portal 2 install locations on my drive and I was simply installing BEEmod to the wrong one. Thanks!
