### ISSUE TITLE
Option to turn off propulsion/repulsion/funnel music for the existing music

### ISSUE THREAD

**Issue by asd417** [BEEmod/BEE2.4#1964]
### Description of the feature

Please let me choose whether I want to use propulsion/repulsion/funnel music for the existing songs.

### Why should this be implemented

A lot of the musics don't fit with the sound effects so it's really irritating when it plays. For example like how portal 1 music is paired with propulsion gel music so it basically plays two different songs on top of another. I think most of the songs work best when it has no sound effects put on top of it.

**Comment by TeamSpen210** [comment]
You should be able to do this already, if you expand the music selection with the arrow, then set the other tracks to "none". Unless I made it use the suggested tracks there? (Which is definitely wrong.)

**Comment by asd417** [comment]
Oh I never realised that there is an arrow next to that
