### ISSUE TITLE
Leak located outside of the map

### ISSUE THREAD

**Issue by DigitalFoxGH** [BEEmod/BEE2.4#1966]
### BEE2 Application Version

4.43.0 (64 bit)

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 11

### Description of the bug

Whenever I make a puzzle and playtest it, an error message pops up, (after everything loads) describing a leak in my map. The leak is located outside of the puzzle no matter what size the map/puzzle is. I've tried removing all but necessary items to run the map, but the error still persists.
![Screenshot 2023-07-01 150804](https://github.com/BEEmod/BEE2.4/assets/138333575/98d7eb7e-2bc0-49ad-87cd-7982d6993315)

### Expected behavior

I expected to be able to playtest the map when it finishes loading, but instead an error message pops up. (see screenshot)

### Steps to reproduce

Export bee 2 items into Portal 2.

Build a puzzle.

Press playtest/build button in the editor.

Wait for it to build and load.

Error message comes up (screenshot).

### Logs and Reports

```shell
There is no relevant log output relating to this issue, although there are multiple warnings in the logs describing multiple items/instances having no UI callback, which I'm not sure relates to the issue.
```

### Additional information

I am using the P1 style.

**Comment by Luke18033** [comment]
In the BEE2 app, try clicking "reset package caches" in the settings, the export again and see if this works.

**Comment by DigitalFoxGH** [comment]
I've tried this multiple times already, and it doesn't work.

**Comment by Luke18033** [comment]
If you're using any items from user created packages, try removing them from the map to see if they're the cause of the leak. If the issue persists or you were only using default items, try rebuilding the map again and then go to `Portal 2/sdk_content/maps/styled`, put `preview.vmf` and `preview.lin` in a ZIP, then upload that here.

**Comment by DigitalFoxGH** [comment]
Here it is. I also do not have any user created packages, and I tried using only default items.
[portalmap.zip](https://github.com/BEEmod/BEE2.4/files/12135635/portalmap.zip)

**Comment by Luke18033** [comment]
Do you have "preserve FGD" enabled in your BEE2 settings? Make sure that (along with "preserve game directories") are turned off.

**Comment by DigitalFoxGH** [comment]
That worked! thank you very much!

**Comment by Luke18033** [comment]
Why did you turn those on in the first place?

**Comment by DigitalFoxGH** [comment]
I didn't know I had turned them on. I thought they were default setting or something. I'm not very tech savvy so I'm not really sure what those settings do anyway. Sorry
