### ISSUE TITLE
Hide developer options tab

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#1970]
The developer options tab should be hidden by default since there seem to be people who just turn stuff on in there without realizing what they actually do (mainly preserve game directories/preserve FGD). You could re-enable it with some specific action, for example by scrolling to the bottom of the credits screen and clicking a button there.

**Comment by TeamSpen210** [comment]
Perhaps the first time you open it there's a disclaimer you have to click past.

**Comment by Luke18033** [comment]
Yeah that might work too

**Comment by Luke18033** [comment]
Maybe it would be better to show the dialog the first time one of the options is changed instead of when the tab is opened, if you clicked no then it would revert the change and show the dialog again next time
