### ISSUE TITLE
How to use BeeMod on Linux?

### ISSUE THREAD

**Issue by SimplyFeed** [BEEmod/BEE2.4#198]
Like in title. I'm newbie at Linux and I don't have idea which .py file open. Thanks in advance.

**Comment by Enterpise** [comment]
There isnt any linux version of Bee2.4, as far as i know, windows and mac are the only ones.

**Comment by BenVlodgi** [comment]
I would try the mac release found on the [release page](https://github.com/BenVlodgi/BEE2.4/releases)
I don't know if that's been tested, if it doesn't work, we might have to start building linux specific releases
