### ISSUE TITLE
GLaDOS P1 announcer lines not working

### ISSUE THREAD

**Issue by Frostice2013** [BEEmod/BEE2.4#1994]
### BEE2 Application Version

BEE2.4 4.43.0 64bit

### BEE2 Package Version

BEE2.4 4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When exporting as the GlaDOS voice is changed to it's Portal 1 version, the voice is not changed and is still the regular Portal 2 voice. Sidenote: Voice options change to <None> on startup.

### Expected behavior

GLaDOS voice is supposed to be the Portal 1 voicelines

### Steps to reproduce

- Use GLaDOS Portal 1 voice.

**Comment by unfunny1** [comment]
![image](https://github.com/BEEmod/BEE2.4/assets/144345484/083c134f-1c65-4d85-9f6a-13915e5b8524)
I wonder why..

**Comment by vrad-exe** [comment]
The original voice lines can't be ported properly, so it just uses Portal 2 lines which are similar. Maybe the voice line pack should be renamed so that's more clear but otherwise this isn't a bug
