### ISSUE TITLE
BEE2.4 ARTIFACT AND PUBLIC RELEASE - Background Music Selector: The music preview button is no longer available.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#2003]
### BEE2 Application Version

beemod2_9f73df920a54ca83601059be1be88357ddbba638_win32

### BEE2 Package Version

beemod2_a15f14901c413a13e624b750e33947724b9b04c9_packages

### What operating system are you running on?

Windows 7 (64bit)

### Description of the bug

![Background Music Selector; The music preview button is no longer there](https://github.com/BEEmod/BEE2.4/assets/12244376/99464813-4ab6-4c59-8673-a6291a02af4a)

### Expected behavior

The music preview button should be there.

### Steps to reproduce

Launch BEE2.4 ARTIFACT BUILD, click music -> base, and youll see that in the background music selector window the prev button is not there anymore.

**Comment by TeamSpen210** [comment]
Seems like the win32 binaries aren't being detected properly.

**Comment by LautaroL20** [comment]
Testing this issue in more deep, it seems that this issue also happens in the BEEmod public releases from the version 4.41.0 to the version 4.43.0  (32bit). However, this problem was NOT present in the BEEmod 4.40.2 32bit version.  

I guess that the key here would be checking how the win32 binaries were in BEEmod version 4.40.2 because in that version it worked.
