### ISSUE TITLE
Bee crashes on Corridor selection

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2.4#2006]
### BEE2 Application Version

2.4.43.0.dev+a2e7311d 64-bit

### BEE2 Package Version

BEE2_v4.43.0

### What operating system are you running on?

Linux

### Logs and Reports

```shell
Traceback (most recent call last):
  File "ui_tk/corridor_selector.py", line 48, in <lambda>
  File "app/corridor_selector.py", line 275, in evt_selected
  File "ui_tk/corridor_selector.py", line 68, in set_highlight
AttributeError: module 'app.tk_tools' has no attribute 'LABEL_HIGHLIGHT_BG'
```

### Additional information

This happens on my Linux box (Arch Linux | Garuda Linux), the app seams to crash if i select any Corridor (The style seems irrelevant).
The problem is not super urgent since the corridors are decorative but, I thought you might want to know about it.
Here a screenshot to what I'm referring to:
![Screenshot_20231208_195210](https://github.com/BEEmod/BEE2.4/assets/40715852/0206db9f-e268-4e4f-b354-a65a73a1cae3)

**Comment by TeamSpen210** [comment]
This is because I didn't add a colour definition for Linux. I just copied the Window one, probably we'd actually need different ones for different themes/window managers/etc?

**Comment by marvin1099** [comment]
Makes sense, but I'm not sure if you need different definitions for custom themes.
I thought the theme will make the decision as long as you tell the theme something like: select item. 
Window Managers should also just do what do what the theme says so, I didn't think you need that.
But I'm not into this, so I could be wrong.
