### ISSUE TITLE
Beemod Dev Build Fail

### ISSUE THREAD

**Issue by TheSuperBlock** [BEEmod/BEE2.4#2010]
### BEE2 Application Version

V4.44.0 32bit

### BEE2 Package Version

V4.44.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
I Wanted To Use The Blue Portals Stuff In Beemod. But When I Tried To Launch The Application But It Crashed, I Tried It With The BP Soundtracks And Items Packages And The Art Therapy Package Too. How Do I Bypass This And Use The Stuff. I Wanna Use Them :(
```

### Additional information

This Is The Message The Crash Said:
   + Exception Group Traceback (most recent call last):
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | trio.NonBaseMultiError: <MultiError: <MultiError: TokenSyntaxError('No configration entity for template!', 'APERTURE_TAG_ITEMS:templates/fizz_base_clean.vmf', None)>>
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "app\BEE2.py", line 173, in app_main
    |   File "app\BEE2.py", line 64, in init_app
    |   File "trio\_core\_run.py", line 963, in __aexit__
    | trio.NonBaseMultiError: <MultiError: TokenSyntaxError('No configration entity for template!', 'APERTURE_TAG_ITEMS:templates/fizz_base_clean.vmf', None)>
    +-+---------------- 1 ----------------
      | Exception Group Traceback (most recent call last):
      |   File "packages\__init__.py", line 606, in load_packages
      |   File "trio\_core\_run.py", line 963, in __aexit__
      | trio.NonBaseMultiError: TokenSyntaxError('No configration entity for template!', 'APERTURE_TAG_ITEMS:templates/fizz_base_clean.vmf', None)
      +-+---------------- 1 ----------------
        | Traceback (most recent call last):
        |   File "packages\template_brush.py", line 36, in parse_template
        | srctools.keyvalues.KeyValError: No configration entity for template!
        | Error occurred with file "APERTURE_TAG_ITEMS:templates/fizz_base_clean.vmf".
        +------------------------------------

**Comment by TeamSpen210** [comment]
Do you have the latest packages? That suggests you have an old `tagItems.bee_pack` package.

**Comment by TheSuperBlock** [comment]
Yeah I Do, At The Time I Was Using V4.44.0. And Yes, I Have The Latest packages! What Is Happening!? :(

**Comment by vrad-exe** [comment]
Those branches for art therapy, blue portals stuff, etc. haven't been touched in a long time and likely aren't compatible with the latest BEE version. If you really want to use them you will need to download an old version of BEE from around the time the packages were last updated. Note that old BEE versions are not supported on this issue tracker, and also those branches were never merged for a reason, because they're very unfinished and might not even be usable.
