### ISSUE TITLE
Banned on discord server (different desc)

### ISSUE THREAD

**Issue by TheProtoToaster** [BEEmod/BEE2.4#2013]
I got banned from the discord like a week ago or so for having a opinion of hating lgbtq like people have their own opinions
I'll do anything to be unbanned, Thanks, ;)

-purple_core

**Comment by TheProtoToaster** [comment]
For mods that got confused of why i put -purple_core its my discord user

**Comment by ENDERZOMBI102** [comment]
this is not the place for such questions or requests, nor this is a request anyone would agree to undertake.
