### ISSUE TITLE
"There was an error building the puzzle"

### ISSUE THREAD

**Issue by aBronyPlays** [BEEmod/BEE2.4#2014]
### BEE2 Application Version

2.4.41.0

### BEE2 Package Version

2.4.41.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

whenever i load a chamber, even an unedited one, Portal gives me the message "There was an error building the puzzle." going into the properties tab on Steam and verifying the integrity of the files fixes four errors. then when i reload the game i can then build the puzzle, but beemod is gone. opening beemod and readding the palette or making a new pallette then causes the "There was an error building the puzzle" once again. 

### Expected behavior

i expect to load the chamber and playtest. 

### Steps to reproduce

i have no idea how to reproduce or whats even wrong or why this happens. 

### Logs and Reports

```shell
n/a
```

**Comment by TeamSpen210** [comment]
Verifying your game cache just effectively uninstalls BEEmod. You need to provide the actual compile log, open the developer console.

**Comment by vrad-exe** [comment]
Closing, not enough information
