### ISSUE TITLE
Map leak

### ISSUE THREAD

**Issue by a-straight-white-male** [BEEmod/BEE2.4#2016]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Map does not compile, reports back a leak here.
![image](https://github.com/BEEmod/BEE2.4/assets/144429107/b6aa905f-e046-4892-99a2-9a2a34af77aa)
![image](https://github.com/BEEmod/BEE2.4/assets/144429107/b94514a2-265c-433c-b72a-6e71048545bc)

Link to puzzlemaker file: https://drive.google.com/file/d/1WD18jt7fKBNg09dA-TetMJbn_uUiHPdS/view?usp=sharing

### Expected behavior

Cannot see any evident problems with the test chamber, that could cause a leak. Leak occurs even without any testing elements.

### Steps to reproduce

Sadly, cannot describe how that happened and how to reproduce the bug. Once i opened the test file and it stopped compiling.

### Additional information

Settings used: original clean style, portal 1 glados.

**Comment by a-straight-white-male** [comment]
Modifying the area by carving in or out does not help; the leak just moves further to the left.

Decompiling my last successful launch through BSPSource and opening it in hammer showed that there are two unprotected entities at 0.0.0 (the corner in question), water_lod_control and playtest_manager of all things

i have no fucking idea how the map compiled in the first place with these entities directly touching the void this makes no sense

![image](https://github.com/BEEmod/BEE2.4/assets/144429107/447c0deb-1e9f-4968-a2c4-36fc7da4439d)

**Comment by vrad-exe** [comment]
Not really sure why this would happen but it fixed after reinstalling so I guess it's fine?
