### ISSUE TITLE
Almost everything is showing as Error in the Editor

### ISSUE THREAD

**Issue by LOLYAYDEV** [BEEmod/BEE2.4#2021]
### BEE2 Application Version

4.44.1

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 11

### Description of the bug

When i put an item in the editor it does not render but shows an blue error. I can still interact with it and in the game when im playing it works as exspected.

### Expected behavior

It should render the thing/item i put in the editor.

### Steps to reproduce

I really dont know

**Comment by LOLYAYDEV** [comment]
![image](https://github.com/BEEmod/BEE2.4/assets/118024018/96a7ed91-6355-4859-9191-63331b1c68e4)

**Comment by TeamSpen210** [comment]
Can you be more specific about what items are errors there?

**Comment by LOLYAYDEV** [comment]
Here:

- Every type of button and pedestreal button
- Cube dropper (the dropper part not the cube)
- Franken cube is not showing up
- Every gel and every gel dropper
- Funnel emitter
- Stairs
- Moving Plattforms
- Light bridge emitter
- Laser Reciver
- Any moving or rotating panel
- Arial space plate is not showing up

**Comment by LOLYAYDEV** [comment]
Strange the peoblems are only with default items

**Comment by LOLYAYDEV** [comment]
Now i get an error when trying to compile it it just says there was an error

**Comment by LOLYAYDEV** [comment]
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF d:/game/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 52 (ms)
VBSP failed.
Valve Software - vbsp.exe (Apr 18 2023)
4 threads
Using shader api: shaderapiempty.dll
materialPath: d:\game\steam\steamapps\common\portal 2\portal2\materials
Loading d:/game/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/bee2_corridor/sp/entry/corr_1.vmf

**Comment by LOLYAYDEV** [comment]
I found that in the console if that helps

**Comment by LOLYAYDEV** [comment]
This to:


Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Model models/props_map_editor/arm4_white_90deg.mdl not a .MDL format file!
Model models/props_map_editor/arm4_white_60deg.mdl not a .MDL format file!
Model models/props_map_editor/arm4_white_45deg.mdl not a .MDL format file!
Model models/props_map_editor/arm4_white_30deg.mdl not a .MDL format file!
Error Index File for 'props_map_editor/arm4_blk_45deg.mdl' version 0 should be 7
Model models/props_map_editor/arm4_blk_30deg.mdl not a .MDL format file!
Model models/props_map_editor/airlock_ghost_90deg.mdl not a .MDL format file!
Model models/props_map_editor/airlock_ghost_60deg.mdl not a .MDL format file!
Model models/props_map_editor/airlock_ghost_45deg.mdl not a .MDL format file!
Model models/props_map_editor/airlock_ghost_30deg.mdl not a .MDL format file!
Model models/props_map_editor/piston_lift_grate.mdl not a .MDL format file!
Model models/props_map_editor/piston_lift_section01.mdl not a .MDL format file!
Model models/props_map_editor/piston_lift_section02.mdl not a .MDL format file!
Model models/props_map_editor/piston_lift_section03.mdl not a .MDL format file!
Error Index File for 'props_map_editor/buttonweight.mdl' version 0 should be 7
Model models/props_map_editor/buttoncube.mdl not a .MDL format file!
Error Index File for 'props_map_editor/buttonball.mdl' version 0 should be 7
Model models/props_map_editor/switch.mdl not a .MDL format file!
Error Index File for 'props_map_editor/faithplate.mdl' version 0 should be 7
Error Index File for 'props_map_editor/laser_cube_falling.mdl' version 0 should be 7
Model models/props_map_editor/frankenturret.mdl not a .MDL format file!
Model models/props_map_editor/frankenturret_falling.mdl not a .MDL format file!
Model models/props_map_editor/dropper.mdl not a .MDL format file!
Model models/props_map_editor/laserrecc.mdl not a .MDL format file!
Error Index File for 'props_map_editor/laserrecw.mdl' version 0 should be 7
Model models/props_map_editor/bridge.mdl not a .MDL format file!
Model models/props_map_editor/paint_splatter_blue.mdl not a .MDL format file!
Model models/props_map_editor/paint_splatter_orange.mdl not a .MDL format file!
Model models/props_map_editor/paint_splatter_white.mdl not a .MDL format file!
Model models/props_map_editor/paint_splatter_water.mdl not a .MDL format file!
Model models/props_map_editor/paint_dropper_editor_blue.mdl not a .MDL format file!
Error Index File for 'props_map_editor/paint_dropper_editor_orange.mdl' version 0 should be 7
Model models/props_map_editor/paint_dropper_editor_white.mdl not a .MDL format file!
Model models/props_map_editor/paint_dropper_editor_water.mdl not a .MDL format file!
Model models/props_map_editor/arm4_ghost_90deg.mdl not a .MDL format file!
Model models/props_map_editor/arm4_ghost_60deg.mdl not a .MDL format file!
Model models/props_map_editor/arm4_ghost_45deg.mdl not a .MDL format file!
Error Index File for 'props_map_editor/arm4_gls_45deg.mdl' version 0 should be 7
Model models/props_map_editor/arm4_gls_30deg.mdl not a .MDL format file!
Model models/props_map_editor/panel_flip.mdl not a .MDL format file!
Model models/props_map_editor/stairs.mdl not a .MDL format file!
Model models/props_map_editor/arm4_ghost_stairs_up.mdl not a .MDL format file!
Error Index File for 'props_map_editor/piston_lift_top.mdl' version 0 should be 7
Model models/props_map_editor/arm_motionplatform.mdl not a .MDL format file!
Model models/props_map_editor/arm_motionplatform_rail.mdl not a .MDL format file!
Model models/props_map_editor/arm_motionplatform_rail_inwater.mdl not a .MDL format file!
Model models/props_map_editor/tbeam.mdl not a .MDL format file!
Model models/props_map_editor/error_state.mdl not a .MDL format file!
Model models/props_map_editor/heart.mdl not a .MDL format file!
[

**Comment by TeamSpen210** [comment]
Try verifying your game cache, then re-rexporting?

**Comment by LOLYAYDEV** [comment]
What do you mean by verifying game cache?

**Comment by LOLYAYDEV** [comment]
@TeamSpen210

**Comment by Sirinchocolate** [comment]
@LOLYAYDEV They meant verifying your steam files. The clean style item models are pulled directly from the p2 files, and not from bee2.

Keep in mind, you'll need to re-export your bee2 pallet after doing this.

**Comment by LOLYAYDEV** [comment]
TYSM it works now i verifyed and then reexported. Now it works
