### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by conmsutton2016** [BEEmod/BEE2.4#2022]
### BEE2 Application Version

Latest

### BEE2 Package Version

Latest

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Broken code breaks BEE2.4

### Expected behavior

I expected it to B E H A V E and work.

### Steps to reproduce

1. Do anything with the latest version
2. Broken

### Additional information

It always says the packages are missing, even when I have the packages.

**Comment by TeamSpen210** [comment]
Can you be more specific about what exactly you did, which packages you used, include the actual log messages?

**Comment by vrad-exe** [comment]
This is incredibly unhelpful so I'm just going to close it

**Comment by conmsutton2016** [comment]
The issue is from way way long ago, apparently I didn't need to extract the packages as a new folder, instead, I had to extract the packages ZIP into the packages. This is fixed by me using the most recent version of BEE2 as of June 24th 2024.
