### ISSUE TITLE
Window positions not loading correctly [dev]

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#2025]
On the latest dev, all sub windows except style properties don't restore to the correct locations and instead appear at the top left corner of the main window
![image](https://github.com/BEEmod/BEE2.4/assets/19228201/ae92113b-6408-4564-a6f8-c5ae821c8dbe)

**Comment by vrad-exe** [comment]
This only happens when reopening after a crash

**Comment by TeamSpen210** [comment]
This was seeming random to me, thanks for noticing the crash is related!
