### ISSUE TITLE
Package folder is reported as empty if it only contains symlinks

### ISSUE THREAD

**Issue by vrad-exe** [BEEmod/BEE2.4#2026]
Weird edge-case I found with the new package error dialog added on dev. If the set packages directory only contains symlinks (actually "junctions", not sure if it makes a difference), the app will complain that the package folder is empty. The symlinked packages still load anyway.
![image](https://github.com/BEEmod/BEE2.4/assets/19228201/08e6b090-fece-4268-9b73-2b3060aa7fe8)

**Comment by TeamSpen210** [comment]
Actually, it'll happen if the folder specified doesn't directly contain any packages (but does in subfolders). I failed to account for that, whoops.
