### ISSUE TITLE
Increase Max Items in Editor

### ISSUE THREAD

**Issue by UnitySe3D** [BEEmod/BEE2.4#2029]
### Description of the feature

The BEEmod2 should be improved to allow for more than 32 items in the puzzle editor.

### Why should this be implemented

This should be implemented because it would drastically speed up the level creation process and make it easier to use BEEmod.

### Additional information

It would also be cool if you created a UPC package browser for all the custom packages people have made.

**Comment by TeamSpen210** [comment]
We can't do this.
