### ISSUE TITLE
Bee 2/2.4 Editor Style Error

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2.4#203]
I recently uninstalled Bee 2.4 Pre-Release 18 manually because of the glitches it had been causing, and switched back to Bee 2. For some reason when I open the level editor it shows the tiles from the Overgrown style, when I had set it to Clean in the Bee 2 editor. When I test the level, it shows as clean. Now I'm stuck with something that makes no sense to what is actually in the level. I've provided some screenshots below to showcase the glitch.

**Comment by MrKrunk** [comment]
![2016-02-17_00001](https://cloud.githubusercontent.com/assets/17092818/13125114/e99818bc-d578-11e5-93ea-f15c13925078.jpg)

![2016-02-17_00002](https://cloud.githubusercontent.com/assets/17092818/13125119/ed1dde40-d578-11e5-8c1e-fe51cad89d0a.jpg)

**Comment by MrKrunk** [comment]
I even uninstalled Portal 2 and removed all files manually that had something to do with Bee 2.4, and I eventually re-installed Bee 2. But obviously, it didn't work.

**Comment by TeamSpen210** [comment]
Remove the `portal2_dlc3/`folder to fix that. In future, use the 'Remove game' option in the BEE2.4 file menu - that should uninstall all traces of the BEE2.4 from a game.

**Comment by LautaroL20** [comment]
Second screenshot its from "Portal 1 Style", not Clean.

**Comment by MrKrunk** [comment]
I know, I used that one as an example for the bug. But it's been resolved.

**Comment by Konclan** [comment]
Wait I can easily uninstall BEE2.4 with the remove game button, shouldn't there be a tooltip or something for this?

**Comment by LautaroL20** [comment]
This has been fixed since a time ago.
