### ISSUE TITLE
Catostrophic failure when i try selecting portal 2.

### ISSUE THREAD

**Issue by toastcool** [BEEmod/BEE2.4#2031]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
+ Exception Group Traceback (most recent call last):
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | trio.NonBaseMultiError: IndexError('list index out of range')
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\BEE2.py", line 173, in app_main
    |   File "app\BEE2.py", line 49, in init_app
    |   File "app\gameMan.py", line 1327, in load
    | IndexError: list index out of range
    +------------------------------------
```

### Additional information

i try to select Portal 2 (Portal2.url) but it just opens another thing saying Catastrophic Failure.

**Comment by vrad-exe** [comment]
Make sure you select the actual Portal 2 executable and not a shortcut to it. If you right click on the game in Steam, and choose "manage > browse local files", it will open the folder where the game is located, you can then navigate there in the BEE file picker and select `portal2.exe`.

We should probably handle this case and display a special error message if you try and select a shortcut.

**Comment by toastcool** [comment]
Thank you!

**Comment by toastcool** [comment]
@vrad-exe may i ask if you can give me a step by step? if you know what to do, because i want to get this done before tomorrow.

**Comment by toastcool** [comment]
I got it working! just need to put the packages in.
Thank you for your help!!
