### ISSUE TITLE
Got it too work, but need to download packages.

### ISSUE THREAD

**Issue by toastcool** [BEEmod/BEE2.4#2032]
### BEE2 Application Version

4.44.1 64bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 11

### Logs and Reports

```shell
[D] localisation.deco(): Add lang callback: <function _update_translations at 0x0000021D2A4B4720>, 1 total
[D] localisation.deco(): Add lang callback: <function _apply_changes at 0x0000021D2A4EC0E0>, 2 total
[W] BEE2_config.load(): Config "C:\Users\pjjac\AppData\Roaming\BEEMOD2\config\item_configs.cfg" not found! Using defaults...
[D] BEE2.start_main(): Starting Trio loop.
[D] BEE2.app_main(): Opening nursery...
[D] BEE2.init_app(): Starting loading screen...
[D] BEE2.init_app(): Loading settings...
[I] gameMan.load(): Load game: Game(name='PORTAL 2', steamID='620', root='C:/Users/pjjac/Downloads/New folder/steamapps/common/Portal 2', mod_times={}, exported_style=None, unmarked_dlc3_vpk=False)
[I] BEE2.init_app(): Loading Packages...
[I] packages.find_packages(): No packages in folder packages!
[E] packages.no_packages_err(): No packages found!
Get the packages from "https://github.com/BEEmod/BEE2-items" and place them in C:\Users\pjjac\OneDrive\Desktop\packages\BEE2_v4.44.1_win64\packages
```

### Additional information

i have the normal packages and music packages zip downloaded so i dont know what is happening.

The warning says "**No packages found! Get the packages from https://github.com/BEEmod/NBEE2-items and place them in C:\Users\pjjac\OneDrive\Desktop\packages\BEE2_v4.44.1_win64\packages**"

I tried the packages part but i dont think it worked (tried redownloading the music package and normal package

**Comment by toastcool** [comment]
I did look at the website but i didnt know how to download all that.

**Comment by CardsAndGamesYT** [comment]
go to https://github.com/BEEmod/BEE2-items/releases/tag/v4.44.0 and download both `.zips`
copy all the `.bee_packs` inside them and place them in the packages folder where your bee2.exe is located
if theres no packages folder, make one

**Comment by toastcool** [comment]
Thank you @CardsAndGamesYT
