### ISSUE TITLE
Better in-application documentation of "signage" and "connection signage"

### ISSUE THREAD

**Issue by my-other-github** [BEEmod/BEE2.4#2034]
### Description of the feature

In the descriptions for "signage" and "connection signage" it should say what symbol each timer widget time generates in the map.

### Why should this be implemented

It would be easy to implement (just some extra text needs to be added to the description) and would be very convenient. Currently I am unaware as to where to find this information so I have to keep recompiling the test chamber until I find the sign I want.

**Comment by TeamSpen210** [comment]
I can't easily add the actually specified signage to the description, because it can be freely changed in the configure signage window found in the Item/Style properties page. In-game, you can right click on the item to see a display of all the signs in order for both.

**Comment by vrad-exe** [comment]
Would probably make sense to have the "configure signage" button show up in the context menu
