### ISSUE TITLE
Lasers on the center of a wall don't activate its linked components.

### ISSUE THREAD

**Issue by KittySaya** [BEEmod/BEE2.4#2035]
### BEE2 Application Version

4.44.1 64-bit

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When you catch a laser using a laser catcher on a center tile, the laser does light up yellow but does not activate any of its attached components, not does it light up any antlines connecting those components.
![20240322172653_1](https://github.com/BEEmod/BEE2.4/assets/67054071/4df74dbc-cd88-4074-abea-aaf6d6b5dee9)
![20240322173723_1](https://github.com/BEEmod/BEE2.4/assets/67054071/e3228986-4587-4ad4-bab3-fe26c9df094c)

### Expected behavior

When the laser catcher catches a laser on a center tile, the laser will activate all of its connections, which can be seen from the yellow antlines and the change in the affected component.

### Steps to reproduce

1. Create a new test chamber.
2. Place a laser emitter on a wall and do not adjust its position so it remains on the center.
3. Place a laser catcher on the opposite wall so that it catches the laser.
4. Place an additional, toggleable component (I used a light bridge, but it also failed with fizzlers or flip panels.
5. Link the laser catcher to the toggleable component.
6. Build the puzzle.
7. Go to the catcher and notice that it catches the laser but does not activate the component.

### Additional information

I'm using the Overgrown style.
The laser emitter position does not matter.

**Comment by Sirinchocolate** [comment]
This is a known issue. Please check other bug reports before filing your own.

**Comment by TeamSpen210** [comment]
See BEEmod/BEE2-items#4406. Thanks for the comprehensive report though!
