### ISSUE TITLE
The problem of Coop Checkpoint and Separated Coop Checkpoint

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2.4#204]
## Coop Checkpoint

![img](http://i13.tietuku.com/2885984ade8fe779.gif)
fizzler.
## Separated Coop Checkpoint

![img](http://i13.tietuku.com/e1108c9443e4e289.gif)
spawn have delay.

**Comment by LautaroL20** [comment]
Well, in my case, even i wasn't able to build any map by using any of the co-op checkpoints available on Bee2.4, because all i get is a "Failure to compile". So i congratulate you to have builded a map with these items.

**Comment by goodDOS** [comment]
@LautaroL20 You need to do this.
![img](http://i13.tietuku.com/43f77dbf224d4dcf.png)

**Comment by CrashingScience** [comment]
Quick q, how are you making these gifs?☺

**Comment by goodDOS** [comment]
Use Screen To Gif. :smiley:

**Comment by Konclan** [comment]
I cannot see any of these gifs, also there are many other issues such as missing cold light instances.

**Comment by LautaroL20** [comment]
This was fixed a long time ago.
