### ISSUE TITLE
Game won't build map.

### ISSUE THREAD

**Issue by Temporary50** [BEEmod/BEE2.4#2042]
### BEE2 Application Version

Latest any bit

### BEE2 Package Version

Latest

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

When I compile and run it, first of all, the "Compile Options" doesn't say ANYTHING was compiled, but, in the game map editor palette, it said they WERE compiled and made work.

### Expected behavior

It should say stuff was compiled.

### Steps to reproduce

To re-make the bug, just edit the palette, run the export, open the game, new test, rebuild [nothing has to be placed to re-create the bug], BAM! It's not working. Sorry! Here is a picture of what the console should look like:
![PORTAL 2 - Direct3D 9 4_18_2024 6_06_47 PM](https://github.com/BEEmod/BEE2.4/assets/163790581/93ea2294-d543-4939-b0c9-35c9081d90c0). If it doesn't look like that, something MUST be wrong...

### Additional information

Any style was used, pretty much.

**Comment by Temporary50** [comment]
never mind

**Comment by Temporary50** [comment]
dude its still broken what do i do

**Comment by TeamSpen210** [comment]
One of the game's VPKs couldn't be loaded, check your DLC folders. Do you have any custom ones? Or perhaps BEE's one got messed up.

**Comment by Temporary50** [comment]
Ah. VPKs. Got it. I'll figure out which one it is, fix it, and it's sure to work! And yes, I have UCPs. Thanks!

**Comment by Temporary50** [comment]
Nope, getting rid of the extra ones just made it worse. 😞.

**Comment by Temporary50** [comment]
Huh. After I renamed the game VPK back to 03, BEEmod opened the game. Hopefully it works now! This mod is awesome!
