### ISSUE TITLE
instances bee2 is not in sdk_content maps

### ISSUE THREAD

**Issue by Temporary50** [BEEmod/BEE2.4#2043]
### BEE2 Application Version

Latest 64bit

### BEE2 Package Version

latest

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I can't get the instances version of bee2 because I have no idea what the bin in the bee2 folder is all about and how to use it. I'd really like someone to tell me how to download the instances bee2 folder. Thank you, and I really like[d] the mod [when I could use it]!

### Expected behavior

I expect that in the bee2's bin folder is the instances bee2 so I can put it into portal 2. 

### Steps to reproduce

I don't know how to recreate the bug. Sorry!

### Logs and Reports

```shell
The instance instances/BEE2/clean/elevator_sp/door_entrance_3.vmf does not exist, meaning the map cannot be compiled! Try other configurations for this item, it may be the case that only some are missing.
```

### Additional information

Any style doesn't work.

**Comment by TeamSpen210** [comment]
Try clicking "reset package caches" in options and re-exporting, seems it hasn't copied over the instances from the packages.

**Comment by Temporary50** [comment]
I'm sorry. This is not an issue. I just needed to delete the %APPDATA% for BEEmod, and it worked!
