### ISSUE TITLE
Linux support for portal game launch

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2.4#2046]
### Description of the feature

After exporting to Portal 2, BEE2 will ask if the game should be opened.
This will just open the web-browser right now,
but it should use something like `xdg-open steam://rungameid/%id-here%`.
This will start the game just fine on Linux.

### Why should this be implemented

For feature parody to windows and for convenience.

**Comment by TeamSpen210** [comment]
That makes sense.
