### ISSUE TITLE
Upside down faithplate trajectory is wrong

### ISSUE THREAD

**Issue by asd417** [BEEmod/BEE2.4#2048]
### BEE2 Application Version

4.44.1

### BEE2 Package Version

4.44.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

![캡처](https://github.com/BEEmod/BEE2.4/assets/33945246/ac086126-3d79-4f41-81d5-fdd67116ca90)
When faithplate is placed like this, the faithplate makes player fly into the wall.

### Expected behavior

The faithplate should push you hard back on floor.

### Steps to reproduce

As the screenshot suggests

### Additional information

https://steamcommunity.com/sharedfiles/filedetails/?id=94552203 Check this map for how upside down faithplates are implemented and used in a puzzle.

**Comment by TeamSpen210** [comment]
Turns out ceiling plates need  to use a target like angled plates do, not sure how they worked before.

**Comment by vrad-exe** [comment]
I've also had ceiling faith plates successfully launch you downward but then randomly crash, I wonder if that's related

**Comment by TeamSpen210** [comment]
I did find one that set the speed to zero, added a safeguard against that.
