### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by BenVlodgi** [BEEmod/BEE2.4#205]
Should a wiki be developed?
I see @Venima created a little page for details about posing issues, which I didn't actually notice until today xD
We could have pages about how to operate the BEE2.4 as a general user, how the BEE2.4 works under the hood, or we could describe the process for making new custom items.

**Comment by Stendec-UA** [comment]
++++++

**Comment by Venima** [comment]
I like this. Would like all 3 topics you mentioned: general user how to, how it works and how to make custom items. 

Oh and I made the page as a sort of reference to point to if someone's not being very helpful in the issues section :P

**Comment by TeamSpen210** [comment]
Definitely. The BEE2 really needs some documentation.

**Comment by LautaroL20** [comment]
That would be useful, especially for all the beginners on the P2 mapping who do not knows how logic items interacts on complex puzzles connections.

Also, it would be good to bring some "short illustrative videos" on the wiki, as a "Small demo" from most of the Bee items. I could cooperate on this point.

**Comment by Enterpise** [comment]
If will not be a poorly maded wiki, then it would be great. if carried out, please put power on it, i always wanted to see a good Beemod wiki.

**Comment by Luke18033** [comment]
So I guess somebody decided to report an issue on the wiki by creating a page. I just deleted it.

**Comment by LautaroL20** [comment]
This is now implemented into both sections, most part of the data is in the item´s section though.

**Comment by Venima** [comment]
I'm so proud the wiki is a thing now :D
