### ISSUE TITLE
Missing Textures and models (Blue Errors) in Portal 2 Editor

### ISSUE THREAD

**Issue by VoltageVictor66** [BEEmod/BEE2.4#2050]
### BEE2 Application Version

4.45.1

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

After choosing test elements in BEEMOD and exporting to Portal 2 here the element icons should be instead have missing textures and blue errors instead of proper models when being placed in the chamber.

### Expected behavior

When exported to Portal 2, it should show the icons of the modded test elements and have models when being placed in the test chamber editor. 

### Steps to reproduce

Step 1. Choose mod elements in BEE2 application.
Step 2. Export to Portal 2
Step 3. Open Portal 2 Chamber Editor and open existing or new chamber

### Additional information

I am currently helping a friend of mine install beemod because he wants to make his own test chambers with the modded elements it has and he really liked what I was doing with my chambers using this application. I have had issues in the past but was able to solve them from online sources however when trying to help my friend, I have been unsuccessful in getting him to properly use the application because if this bug. I have no idea how to fix it. I do not believe it is an anti-virus issue that could be preventing export because my friend does not have one (I know that's not good) and it even says the export was successful every time. We have tried uninstalling beemod from Portal 2 and reinstalling, even waiting about a minute or so it completely removes its contents. Then reinstalling and still same issue. We even tried down grading to 4.45.0 and seeing if that worked, of course it didn't. I am at a complete loss and if anyone would like to help it would mean the world to me. Thank you for going through my bug report. I hope you all have an amazing day.

**Comment by TeamSpen210** [comment]
Try pressing the "reset package cache" button in options, then re-exporting.

**Comment by VoltageVictor66** [comment]
> Try pressing the "reset package cache" button in options, then re-exporting.

Ok I'll try that but right now my friend is heading to bed so I'll have him try that tomorrow and I'll let you know what happens. Thank you so much.

**Comment by VoltageVictor66** [comment]
Ok so apparently my friend rejoined he didn't go to bed yet, and we just attempted what you suggested and it did still did the same thing.

**Comment by lolekgracz** [comment]
I have the same problem i run on windows 11 64-bit
