### ISSUE TITLE
Model errors and missing item icon texture

### ISSUE THREAD

**Issue by Banimold** [BEEmod/BEE2.4#2053]
### BEE2 Application Version

4.45.1

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 11

### Description of the bug

![Snimka zaslona (31)](https://github.com/BEEmod/BEE2.4/assets/171376938/0a6a9c36-41e4-440c-98ef-6ef16067cd6b)
![Snimka zaslona (32)](https://github.com/BEEmod/BEE2.4/assets/171376938/0763770f-634a-46cc-b8f0-09735870047c)
In editor some models are fine but in the map are blue errors
also items are missing texture

### Expected behavior

not to make models a blue error neither item missing textures

### Steps to reproduce

1. downloaded the aplication and package
2. extract them in the directory i made
3. run the BEE2.exe
4. showed the portal 2 executable
5. put packages into a folder packages
6. run it again and put some custom items onto item tab
7. chose the style, voice and music
8. exported to portal 2
9. then checked the puzzlemaker
10. then found out about blue errors and missing textures

**Comment by Banimold** [comment]
I tried looking for similar issues and tried to fix it
one of them are from voltagevictor66

**Comment by Banimold** [comment]
I found a log
![Snimka zaslona (34)](https://github.com/BEEmod/BEE2.4/assets/171376938/24f104e7-1467-4847-b58f-7e40abf6266a)
before that log, compilers seem to not export

**Comment by snachnx** [comment]
Exact same setup, exact same issue here

**Comment by TeamSpen210** [comment]
Try pressing "reset package cache" in options, then re-exporting?

**Comment by snachnx** [comment]
It did nothing to it

**Comment by vheartache** [comment]
same problem …(

**Comment by PuroTheFloofer** [comment]
i can also agree to the Problem here as well 
![Screenshot 2024-06-03 140812](https://github.com/BEEmod/BEE2.4/assets/154958177/c3918a47-fdb1-435a-8200-33923c8351b8)
![Screenshot 2024-06-03 133613](https://github.com/BEEmod/BEE2.4/assets/154958177/bb8e0044-8a2b-4a90-8712-2a55dbcf44ca)

**Comment by TeamSpen210** [comment]
When you export (after pressing reset package cache), what number appears in the progress bar for resources? Also, anyone with this issue could you go into the Portal 2 folder, then see if there’s any files in a `bee2/` subfolder.

**Comment by Banimold** [comment]
![Snimka zaslona (35)](https://github.com/BEEmod/BEE2.4/assets/171376938/cddbcf64-ba1d-459a-b925-1c62237d452a)
here is an update 
i dont know what it means but i think file texture is outdated, im not so sure.

**Comment by TeamSpen210** [comment]
Nope, you have an old version of VTFEdit, VTF 7.5 is standard for Portal 2.

**Comment by Banimold** [comment]
ok also found this
![Snimka zaslona (36)](https://github.com/BEEmod/BEE2.4/assets/171376938/27009756-6ab6-4d04-8f1a-767180c7e70b)
some parts of export are skipped
![Snimka zaslona (37)](https://github.com/BEEmod/BEE2.4/assets/171376938/e5bc6dba-8717-4d13-9af0-6db569978b0c)

**Comment by TeamSpen210** [comment]
Do you get that error every time? That means exporting totally failed, you might want to delete `D:\Portal2\portal2_dlc4\pak01_dir.vpk`, it's corrupt.

**Comment by Banimold** [comment]
I did that just a minute ago
i deleted the files

**Comment by Banimold** [comment]
ill see you soon i have to go

**Comment by PuroTheFloofer** [comment]
i checked if there were files in the Portal2/
![Screenshot 2024-06-04 221740](https://github.com/BEEmod/BEE2.4/assets/154958177/7e950c87-c3ce-4026-abd2-df066f899404)
bee2 subfolder for ya and here is what i got

if this was what you were Referring to  there are files within those as well

**Comment by TeamSpen210** [comment]
Does a `Game |gameinfo_path|../bee2` entry exist in `Portal 2/portal2/gameinfo.txt`?

**Comment by PuroTheFloofer** [comment]
at the verry bottom it only says  

SearchPaths
		{
			Game				|gameinfo_path|.
		}
	}
}

**Comment by TeamSpen210** [comment]
Oooh, there's the problem. It's supposed to add a entry there, but it hasn't.

**Comment by PuroTheFloofer** [comment]
oh dang Okay then  

would it be possible to  manualy add that line into the txt?  Just Curious

**Comment by TeamSpen210** [comment]
Yep, add it after the existing one.

**Comment by PuroTheFloofer** [comment]
good news that was it!              
![image](https://github.com/BEEmod/BEE2.4/assets/154958177/ee3980c8-07d3-4b85-a5d1-7fb8865e1495)

**Comment by danilkaME** [comment]
hey i dont understand what i need to add in gameinfo.txt

**Comment by TeamSpen210** [comment]
Grab the new release.

**Comment by Banimold** [comment]
im back and i see that you solved it, thanks
