### ISSUE TITLE
Portal 1 music not avalliable to use??

### ISSUE THREAD

**Issue by doodleshep14** [BEEmod/BEE2.4#2056]
so im trying to make a portal 1 themed map and the portal 1 music is just gone???
![image_2024-06-13_134652680](https://github.com/BEEmod/BEE2.4/assets/119131991/64567b64-8b05-44c9-85e8-c8c32f2bf5c4)

**Comment by anotsospookyskeleton** [comment]
Hate to give misinformation on Github issues, but you might need to install Portal 1 from Steam to use the music in Beemod?

**Comment by vrad-exe** [comment]
You need to download the extra music pack - that hasn't been updated since v4.44 so you just need to download [that version](https://github.com/BEEmod/BEE2-items/releases/tag/v4.44.0), it's still compatible.
