### ISSUE TITLE
How do I unhide a palete setting?

### ISSUE THREAD

**Issue by conmsutton2016** [BEEmod/BEE2.4#2057]
I cannot unhide Aperture Tag's palete in the latest version of Beemod. Please help with this.

**Comment by conmsutton2016** [comment]
I resolved this by using the little add external games thing.

**Comment by conmsutton2016** [comment]
This has been fixed via the custom games.

**Comment by conmsutton2016** [comment]
I reopened the issue so that you can respond in the comments.

**Comment by vrad-exe** [comment]
Click the "show hidden palettes" button in the settings

**Comment by conmsutton2016** [comment]
> Click the "show hidden palettes" button in the settings

Oh, okay. Although, besides, I have already added BEE2 items to the Aperture Tag palete.

**Comment by conmsutton2016** [comment]
:)
