### ISSUE TITLE
Stained glass crashes TWTM

### ISSUE THREAD

**Issue by conmsutton2016** [BEEmod/BEE2.4#2058]
### BEE2 Application Version

4.45.2

### BEE2 Package Version

2.4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I tried using the stained glass in TWTM (I set the palete) and it gave me an error.

### Expected behavior

I expected:
1. For the model to have a texture
2. For it to work

### Steps to reproduce

Step 1: Add Thinking with Time Machine and add the stained glass
Step 2: Place it down somewhere*
Step 3 (Optional whether you want the error or wrong save): If you save the map, then an error pops up. If you don't save it, it gives you the wrong save

*Results may vary depending on whether you save the map.

### Additional information

I used the stained glass and it was glowing white in the editor, no transparency.

**Comment by vrad-exe** [comment]
TWTM isn't supported

**Comment by conmsutton2016** [comment]
> TWTM isn't supported



> TWTM isn't supported

I learnt that the hard way, now TWTM's PETI editor is broken and I hid TWTM from my library on Steam.
