### ISSUE TITLE
Connected up auto-save checkpoints

### ISSUE THREAD

**Issue by Venima** [BEEmod/BEE2.4#206]
So the basic idea is that the auto-save or checkpoint object should be able to be connected up to a signal, so that it'll only auto-save if a certain 'something' is true (being always-active if there is no signal). 

Reason:
I love building large or complex portal maps, but I often struggle to place checkpoints in the right places so that they're not triggered before/after a certain risky task has been completed. Sometimes the player would even cross the same path twice. With my solution, you could have multiple checkpoints even in the same space, and just have them connected up to different events, like when a weighted button is pressed. This would allow a map-maker to make their chambers much more forgiving on the player, and fine-tune their auto-save events based on specific chamber requirements.

**Comment by BenVlodgi** [comment]
Your suggesting just some item that can be linked to, and when all inputs are met triggers an autosave, right?
I recall talks about an item like this, I don't know if it was ever created.

**Comment by Venima** [comment]
Ideally, you'd use the existing auto-save trigger box in Beemod, whose behaviour doesn't change except that it would only auto-save if its inputs were met as well. You can already connect inputs up to that item, they just don't do anything, so I mean, you could simply modify its effect to check inputs. I doubt it would break anyone's maps :P

**Comment by TeamSpen210** [comment]
I would be adding input functions to both the BEE and HMW's autosave items.

**Comment by BenVlodgi** [comment]
This sounds like a pretty good idea.

I think also a non trigger based autosave item should be created. Users would be able to do exactly what you are suggesting by using a tigger multiple. When all the conditions are met including the trigger multiple being active, the autosave would fire.
I think an item like this should be added, so autosaves can also be triggered by puzzle events and not necessarily player location.

I do also think it would be good to add the functionality you suggest with only enabling the trigger-autosave when all inputs are active. Its a suggestion that has been made before, but we never did anything about it :D

**Comment by Venima** [comment]
Well, the only issue with a just trigger multiple is timing. The auto-save might be positioned on a platform that might at some point open up into toxic water. It would then be terrible for it to save if you fall there by mistake :P .. but yeah..

**Comment by BenVlodgi** [comment]
its the same with the current trigger autosave

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1244
