### ISSUE TITLE
"No compiler files were found in \BEE2\compiler"

### ISSUE THREAD

**Issue by SlimySqueed** [BEEmod/BEE2.4#2061]
### BEE2 Application Version

4.45.0 64bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

After exporting to Portal 2, I get a pop-up with the message "No compiler files were found in '\Desktop\BEE2\compiler" and am unable to compile my level in-game without receiving the message "There was an error building the puzzle."

### Expected behavior

I expect to not receive a pop-up saying no compiler files were found and expect for a successful build of my level in-game.

### Steps to reproduce

1. Run "BEE2.exe" with the 4.45.0 application and package version
2. Use whatever palette you have (I've found for me it doesn't matter which one I'm using) and press "Export to 'PORTAL 2"
3. Run Portal 2 and create a new test chamber
4. Try to build and playtest the level

### Logs and Reports

```shell
(Pictures are in the "Additional  Information" section)
```

### Additional information

![no_compiler_fiels](https://github.com/BEEmod/BEE2.4/assets/130199943/d441157f-1fb6-4c04-bb75-e04de8e96e4f)
![error_building_puzzle](https://github.com/BEEmod/BEE2.4/assets/130199943/81bda41b-952e-45c2-8295-50d6b0f2cae1)

**Comment by TeamSpen210** [comment]
Get version 4.45.2, it fixes this bug.

**Comment by SlimySqueed** [comment]
I just tried using 4.45.2 instead, I managed to no longer get the compiling error, however I still get the same message in-game "There was an error building the puzzle"

I did check the console and this appeared after trying to build the level

`VBSP failed.

[I] compiler_launch.<module>(): Arguments: ['C:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[3380] Failed to execute script 'compiler_launch' due to unhandled exception!

`

**Comment by MGMorgan16** [comment]
I had the same problem, I found the solution in #2054 - you need to select a voiceline before you export!
