### ISSUE TITLE
BEE2.4 - Energy Pellet Catcher sound

### ISSUE THREAD

**Issue by Xorven** [BEEmod/BEE2.4#207]
Hello there,
Everytime when I activate an Energy Pellet Catcher, instead of the "normal" sound, I have the Kleiner's sentence "Oh fiddlesticks, what now ?"
Can I remove this ? Seriously this is just ugly :x

Thanks :)

**Comment by harritron2k2** [comment]
Really? I have a catcher in my map but I hear it when going up the elevator. (could be just Portal 1 style being glitchy though) I haven't got the catcher to actually catch a ball, so this could be a bug in BEE2.4

**Comment by xDadiKx** [comment]
It's because the Portal 1 Glados Voice is missing, so it plays the Kleiner voice.

**Comment by harritron2k2** [comment]
I don't think it's that because I used Wheatley for the test

**Comment by TeamSpen210** [comment]
This wouldn't be because of voicelines. The pellet catcher and elevator sounds are only in Portal 1, so they need to be packed in - I must have not copied a file or something.

**Comment by harritron2k2** [comment]
Ok, I made more about this and I included this issue
