### ISSUE TITLE
Can i get help

### ISSUE THREAD

**Issue by RayanGenet2012** [BEEmod/BEE2.4#2071]
### BEE2 Application Version

4.45.2

### BEE2 Package Version

4.45.0

### Description of the bug

When i try to export the beemod new palet to Portal 2 , that say me a error

### Expected behavior

The exporting of beemod to portal 2 don't working

### Steps to reproduce

I open Beemod
I save the beemod palet
I export to Portal 2
"And for finally , that do the error"

### Logs and Reports

```shell
+ Exception Group Traceback (most recent call last):
  |   File "ui_tk\core.py", line 256, in app_main
  |   File "trio\_core\_run.py", line 954, in __aexit__
  | exceptiongroup.ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "app\UI.py", line 732, in export_editoritems
    |   File "exporting\__init__.py", line 150, in export
    |   File "os.py", line 223, in makedirs
    | PermissionError: [WinError 5] Accès refusé: 'c:\\program files\\portal 2\\bin\\bee2\\'
    +------------------------------------
```

### Additional information

I think that he cannot export in the game folders before its saying that i dont have the access , please fix that

**Comment by RayanGenet2012** [comment]
Guys ! Its do another error...

**Comment by TeamSpen210** [comment]
Why is Portal 2 directly in program files? You might have to change the security settings for the P2 folder to allow BEE to modify it.

**Comment by vrad-exe** [comment]
Closing due to lack of information. I'd assume they were using a pirated copy of portal 2, don't know why else it would be directly in program files.
