### ISSUE TITLE
Question, what system is using .pdn files

### ISSUE THREAD

**Issue by marvin1099** [BEEmod/BEE2.4#2073]
I recently noticed that this project is using .pdn files.  
These are as you may know Paint.NET image layer files.  
I wanted to convert a bunch of them for use in somting like Krita.

Because Paint.NET only runs on windows i used a vm for this.  
But since this project was using some .pdn it seems plausible  
that there is a way to load these on linux and convert them mabye.  
So i was just curious if you use these files in the code on linux.

If some library is doing this loading it would be nice if you say what library  that is.  
Mabye you are just using these .pdn files on windows pc if so just say so.  
If none of this is coorect but since these images are in your codebase,   
just say what part acctally uses these images (idk. like: portal mod loader).

Thanks in advance.

**Comment by TeamSpen210** [comment]
They're never directly used, they're just the source files for the corresponding `.png` file.

**Comment by marvin1099** [comment]
Got it, that awnsers my question thanks
