### ISSUE TITLE
Portal 2 complains that quote-unquote "Steam isn't running" after just installing BEEMOD when I HAVE STEAM OPEN

### ISSUE THREAD

**Issue by conmsutton2016** [BEEmod/BEE2.4#2074]
### BEE2 Application Version

Version 4.45.2 64bit

### BEE2 Package Version

4.45.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

After **just** re-installing BEEMod (and opening Portal 2 from Steam after exporting), it goes to the Valve intro and crashes with an error saying I need to have Steam running, and **_I HAVE STEAM RUNNING_**.

### Expected behavior

I expected Portal 2 to just, y'know, **W O R K** .

### Steps to reproduce

1: Install BEEMod V4.45.0, select Portal 2 location, edit palette and then export.
2: Click "no" to opening Portal 2 from BEEmod, open Portal 2 and if you get the error saying you need Steam running, you've reproduced, but if not then I must have done something incorrectly.

### Additional information

- Style: Clean
- Added items: Catwalk, Vactube (not the one that deletes objects), Scaffold Slot, Scaffold Wall Emitter, Scaffold Piston Emitter.

**Comment by vrad-exe** [comment]
Try restarting steam and/or your PC, this isn't something BEE could really cause (especially if you launched the game through Steam itself and not the BEE post-export dialog)

**Comment by conmsutton2016** [comment]
> Try restarting steam and/or your PC, this isn't something BEE could really cause (especially if you launched the game through Steam itself and not the BEE post-export dialog)

I tried reloading Steam (closing then re-opening) but the issue still stayed. When I turned on my computer to see if Portal 2 was working, it still did it, since I leave my windows open when turning off my computer. (sleeping my computer)

**Comment by conmsutton2016** [comment]
> For Steam, you need to click `Steam > Exit` in the top left corner of the window to fully restart it, just closing the window isn't enough. If that still fails then try fully restarting your computer, not just using sleep/hibernate.

Thanks! I have new items in my palette, and I made a BEE2 map called "The Bee Chamber". See what I did there?
