### ISSUE TITLE
Problems building puzzles

### ISSUE THREAD

**Issue by pessoaneto** [BEEmod/BEE2.4#2075]
Greetings, 

I've used Beemod for the past two years and never had any issues. However, my Portal 2 cannot build any puzzles with Beemod. When I remove Beemod from Portal 2 it builds again. Any suggestion? 

I've already reinstalled the game (steam) and Beemod (downloading again). I am using the latest versions of both programs. 
![image](https://github.com/user-attachments/assets/27a38e79-8e42-49ac-8158-d976553fd9be)

**Comment by TeamSpen210** [comment]
Please open the developer console and post the logs, this dialog appears if the compile fails for any reason.

**Comment by pessoaneto** [comment]
> Please open the developer console and post the logs, this dialog appears if the compile fails for any reason.

`[PORTAL2 PUZZLEMAKER]  Saved puzzle: c:/program files (x86)/steam/steamapps/common/portal 2/portal2/puzzles\76561198054911010\autosave.p2c
Session Started!
Using category 'Singleplayer'
Paused for 469 non-simulated ticks.
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (21,16,5)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 38 (ms)
VBSP failed.
[I] compiler_launch.<module>(): Arguments: ['c:/program files (x86)/steam/steamapps/common/portal 2/bin/vbsp.exe', '-entity_limit', '1750', '-game', 'c:/program files (x86)/steam/steamapps/common/portal 2/portal2/', 'c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\\maps/preview.vmf']
[I] compiler_launch.<module>(): Running "vbsp", version 2.4.45.2 64-bit:
[I] vbsp.main(): BEE2.4.45.2 64-bit VBSP hook initiallised, srctools v2.3.17.dev5+823ca80.dirty.2024.04.17.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "c:/program files (x86)/steam/steamapps/common/portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] vbsp.load_map(): Parsing Map...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] barriers.parse_conf(): Parsed 3 barrier types, 2 frame types, and 5 hole types.
[I] vbsp.load_settings(): Settings Loaded!
[E] logger.except_handler(): Uncaught Exception:
  + Exception Group Traceback (most recent call last):
  |   File "compiler_launch.py", line 56, in <module>
  |   File "trio\_core\_run.py", line 2303, in run
  |   File "vbsp.py", line 1623, in main
  |   File "trio\_core\_run.py", line 963, in __aexit__
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "utils.py", line 662, in _task
    |   File "precomp\voice_line.py", line 61, in load
    |   File "trio\_path.py", line 38, in wrapper
    |   File "trio\_threads.py", line 471, in to_thread_run_sync
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 397, in do_release_then_return_result
    |   File "outcome\_impl.py", line 213, in unwrap
    |   File "trio\_threads.py", line 416, in worker_fn
    |   File "trio\_path.py", line 57, in wrapper
    |   File "pathlib.py", line 1019, in read_bytes
    |   File "pathlib.py", line 1013, in open
    | FileNotFoundError: [Errno 2] No such file or directory: 'bee2\\voice.bin'
    +------------------------------------
[31752] Failed to execute script 'compiler_launch' due to unhandled exception!
Session: 6 (0.100)
Unknown command "cl_puzzlemaker_deactivate"
Session started! (menu)
`

**Comment by TeamSpen210** [comment]
See #2054.
