### ISSUE TITLE
Prl18 - Portal 1 Style errors

### ISSUE THREAD

**Issue by harritron2k2** [BEEmod/BEE2.4#208]
- Item and Style errors in the Portal 1 style
- [x] 1. Kleiner's voice plays in the main elevator shaft at the beginning of the level, some sound is missing (not voice because I used Wheatley instead of GLaDOS)
- [x] 2. Floor Button top (the part that gets pressed down) is just an error in game.
- [ ] 3. Scaffold Piston Emitters give combile error
- [x] 4. Angled Panels in editor show error as model on all angles except 90 degrees
- [x] 5. Angled Panels give combile error
- [x] 6. Energy Pellet Catcher doesn't emit a sound (#207)

That's all for now, hope these can be fixed easily.

**Comment by LautaroL20** [comment]
These were fixed since a time ago already.
