### ISSUE TITLE
Portal 1 music doesn't appear

### ISSUE THREAD

**Issue by CompyCube** [BEEmod/BEE2.4#2090]
### BEE2 Application Version

2.45.2

### BEE2 Package Version

2.4.45.0

### What operating system are you running on?

Windows 11

### Description of the bug

Portal 1 music just does not appear, its category doesn't even show up.

### Expected behavior

I expect Portal 1 music to appear, as others have it and are confused as to why I don't have it.

### Steps to reproduce

I don't know, its been like that ever since i first installed Beemod and I don't know why.

### Logs and Reports

```shell
[DEBUG] packages.find_packages(): Reading package "packages\music.bee_pack"
[DEBUG] packages.find_packages(): Reading package "packages\p1_style.bee_pack"
[DEBUG] packages.post_parse(): Inheritance path for <Style: BEE2_PORTAL_1> = [<Style: BEE2_PORTAL_1>]
```

### Additional information

I recently got a few UCP for Beemod but this hasn't affected the bug in any way.

**Comment by TeamSpen210** [comment]
Did you install the [BEE2-music](https://github.com/BEEmod/BEE2-music) packages?

**Comment by CompyCube** [comment]
I was gonna close this issue. Turns out the portal 1 music was separated
. 

> Did you install the [music](https://github.com/BEEmod/BEE2-items/releases/tag/v4.43.0) packages?

**Comment by TeamSpen210** [comment]
So you found it then?

**Comment by CompyCube** [comment]
> So you found it then?

ye
