### ISSUE TITLE
Make new variants for Entry and Exit Corridors for Old Aperture 

### ISSUE THREAD

**Issue by Kalethars** [BEEmod/BEE2.4#215]
While the current 50s to 80s style's elevator is outside the chamber and inside the sphere, it is weird that the location of entry and exit is fixed and not correct. I hope to see a new entry and exit style like bts inside the building and that will let me feel better. :)

**Comment by Konclan** [comment]
There would be no purpose to having an old aperture BTS area before and/or after a normal old aperture enrichment sphere. It would increase the compile time + there is an open sphere option that shows the outside.

**Comment by TheReviewers** [comment]
@Konclan Compile doesnt matter

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1243
