### ISSUE TITLE
Show preview images for Entry / Exit Corridors when mousing over

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#216]
It sounds a lot like there are 5 copies of the exact same corridor. even then, "Right Straight" sounds quite vague.
There should really be some actual images of the entries/exits. It doesn't even have to be in the program, some screenshots on Steam would be fine as long as they're linked to somewhere.

![art](https://cloud.githubusercontent.com/assets/12244376/20692004/d94975ac-b5b3-11e6-922b-acb167ce97de.png)

**Comment by LautaroL20** [comment]
Nice suggestion.

**Comment by TeamSpen210** [comment]
Good idea! Actually, a lot of the corridors are quite similar (with just minor texture changes). The named ones are laid out differently - 'Right' or 'Left' ones have a turn in them.

**Comment by Konclan** [comment]
The corridor selection needs a menu similar to the music selection menu

**Comment by HugoBDesigner** [comment]
If you guys want, I can provide the screenshots. For now I have the SP entry and exit for Clean and Portal 1.

**Comment by TeamSpen210** [comment]
Ironically I'll probably be remaking several of those in the future, they're all very similar to each other.

**Comment by HugoBDesigner** [comment]
You can say that again :P 
![image](https://cloud.githubusercontent.com/assets/6296061/23919645/566aaf68-08d6-11e7-882a-98455195752d.png)

**Comment by Luke18033** [comment]
P1 corridors 1-6 are all identical currently. I had an idea for one which I can make after I finish the Large Glass Panel. You know the worldportal holes in the Overgrown corridors? This would have a Ratman den that worked just like that.

**Comment by LautaroL20** [comment]
@TeamSpen210 @Luke18033 - Thats because that does requires an higer resolution size so a way that people could see them better and recognize them easily. Please, don´t make them small.

**Comment by LautaroL20** [comment]
Ill leave my concept art, here:

![art](https://cloud.githubusercontent.com/assets/12244376/20692004/d94975ac-b5b3-11e6-922b-acb167ce97de.png)

**Comment by LautaroL20** [comment]
This will be finally implemented in next Pre-Release 30.  Source (not the engine tho): https://github.com/BEEmod/BEE2-items/commit/c888a36fcd2daaf14560a08e6bdbe09862f1e3ed
