### ISSUE TITLE
Escaped from the chamber in Old Aperture

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#220]
![Legends say that if you go into the elevator, you get trapped in the pit that Wheatley described with the 3-portal portal gun...](http://i.imgur.com/F5xeWB7.png)
That door seriously needs a portal bumper...

**Comment by TeamSpen210** [comment]
Is this supposed to be an animation? I can't see anything, other than the pause menu.

**Comment by Enterpise** [comment]
@TeamSpen210 hahah me too. This guy should post clear pictures before report a bug.

**Comment by ncrecc** [comment]
I was posting a picture of the (now blacked off) exit door.

**Comment by Enterpise** [comment]
If it was that case, then you should also prove you were using Bee 2.4, and so on. You don't need to prove anything, just report a bug with a clear picture, thats all.

**Comment by Kalethars** [comment]
I also meet this problem, because the floor is portable.

**Comment by Konclan** [comment]
I saw this issue addressed in a similar issue but that issue has been deemed fixed, so shouldn't this as well?

**Comment by LautaroL20** [comment]
This bug related to the Old Aperture exit doors becoming black after the player walk trhouh it were fixed since pre-release 22.
