### ISSUE TITLE
Jazz Song not playing after the Voice of Announcer

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2.4#225]
I don't know if this is bug but when I am playing my or other's map where is announcer saying that hes gonna play Smooth Jazz then sound doesn't appear.

**Comment by TeamSpen210** [comment]
He's supposed to then play 'spark' sound FX, like the audio system is damaged.

**Comment by BenVlodgi** [comment]
perhaps we could get a selection of multiple jazz pieces, that the puzzler designer (human) could chose from.

**Comment by SpyyZ158** [comment]
Sounds great :)

**Comment by towergame** [comment]
Maybe a bit of classical music too?

**Comment by Konclan** [comment]
oh btw https://www.youtube.com/watch?v=nDifsWZ_s5s&list=LLJ3LVjZCCyxu4ulMWcJ0TfA&index=7 is the actual song for the smooth jazz chamber, Perhaps you can have this as a normal music option. Though I don't know if people would ever be able to hear it unless they have BEE2.4 installed :/

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1496
