### ISSUE TITLE
Use Compiler for Input A/B

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2.4#226]
I think Ill say it in other way, I was making this issue already but.Death Fizzler should be able to turn off like when I use button or something then it goes into normal laser or normal fizzler.Inputs A/B just changes them but not actually disabling them,When I connect button to Death Fizzler for timer it turns into laser just for like 5 seconds as usually is on button and then it goes off but if it could be able like for normal cube button to fizzler be disabled immiedently even as on normal button for timer not just change on other type.
If picture is needed just ask me :) .

**Comment by jccreszMinecraft** [comment]
I would like to suggest a death fizzler variant that only has an I/O system. Basically what you're saying, no?

TeamSpen this idea isn't half bad considering sometimes entities are fickle in the editor and these items can add up.

**Comment by SpyyZ158** [comment]
If it could be like in Portal Stories Mel, that would be cool.

**Comment by TeamSpen210** [comment]
I'll switch  the A/B items to use the compiler, which will let me make them use less entities and allow normal inputs to function reasonably.

**Comment by Luke18033** [comment]
This has been done already, right?

**Comment by TeamSpen210** [comment]
No
