### ISSUE TITLE
Executable Crashes

### ISSUE THREAD

**Issue by corrupt21** [BEEmod/BEE2.4#227]
I have downloaded pre-release 18 and have put the package folder into the bee2 folder, but whenever I open the installer, when it gets to loading object, it crashes.

Is this normal or is this just me?

**Comment by LautaroL20** [comment]
Search for a file called "BEE2-error.log", contained on your pre-release extracted folder, and copy paste the text on your post to see whats going on.

**Comment by SpyyZ158** [comment]
It does for me on 19 Prl version

**Comment by Konclan** [comment]
If this is still happening can we get a crash report? This information is very vague and this problem doesn't happen (doesn't mean it's not a bug)

**Comment by LautaroL20** [comment]
This should´t happen anymore, try downloading the latest pre-release wich is the N°23
