### ISSUE TITLE
[PRL21.5 Bug] Black Wall, and Partial Block uses the same icon

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#236]
This could lead to confusion:

---

![same icons for cutout black wall and partial block](https://cloud.githubusercontent.com/assets/12244376/13729940/971b7506-e91f-11e5-82b7-64bc85898c48.png)

**Comment by ncrecc** [comment]
It's clearly a placeholder icon for the other 2 items. You didn't actually expect TSpen would actually keep the same three icons the entire way through, and never change them, did you?

**Comment by LautaroL20** [comment]
If we apply the same logic, then why we´re reporting bugs then? If TeamSpen210 knows already them. Your logic does not work. We are reporting bugs as a "Reminder" to help the developers to not forget any of these issues.

**Comment by ncrecc** [comment]
We report bugs if it's likely the devs would have no idea of their existence anyways. If an asset for a feature was broken or turned to another one for no reason, that is a bug. If you apply the most basic logic to the icons ("they're all tile-related", and "this icon looks like the partial block"), you would know that they're both hand-downs from the partial block and the icon is being used as a placeholder for the cutout tile and the black wall. We should all be able to automatically recognize whether it's an actual bug or the dev is just a bit lazy and will immediately add the proper icons once he's actually made them.

**Comment by LautaroL20** [comment]
Cutout Tile still uses the same icons as Black Wall and Partial block on the Pre Release 20.

**Comment by LautaroL20** [comment]
Updated, this still happens with the Prl21.5

**Comment by LautaroL20** [comment]
Fixed via:  https://github.com/TeamSpen210/BEE2-items/commit/4cf3e19c61b947cc44519a9b98fb210bc7cf3bd2
