### ISSUE TITLE
[PRL19 Bug] "Unlock default items" is not providing some items

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#242]
For example, Co-op Spawns, and Large observation Rooms. GIF
![gif](https://cloud.githubusercontent.com/assets/12244376/13760387/ad9ad072-ea11-11e5-8e98-1b4086e07f38.gif)

**Comment by Konclan** [comment]
That's very strange, I don't think that occurs for me

**Comment by LautaroL20** [comment]
@Konclan - Well, in my case it happens, and even i recorded a gif file showing the bug.

**Comment by Konclan** [comment]
Yeah I see that, thats why I'm curious why its for you and not me

**Comment by LautaroL20** [comment]
This is fixed since a time ago.
