### ISSUE TITLE
BTS Massive Leaks Incorrect Entry Door placements.

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2.4#244]
![20160315185602_1](https://cloud.githubusercontent.com/assets/17092818/13766949/85320756-ea23-11e5-96ff-e3761478f2f2.jpg)

![20160315190049_1](https://cloud.githubusercontent.com/assets/17092818/13766981/b5acffbc-ea23-11e5-985f-02babb680cea.jpg)

**Comment by LautaroL20** [comment]
I remember having tested BTS style in both SP and Co-op mode and never saw that nodraw from the first screenshot from up. Did you entered that room afther last door has closed with "Noclip" or so?

**Comment by MrKrunk** [comment]
No. I walked through the entrance normally. No cheats of any sort.

**Comment by TeamSpen210** [comment]
The broken exit door is actually the cause of the Norris's in the entry area. The misplaced door causes a leak, making the areaportal in the entry not work properly.

**Comment by Konclan** [comment]
Yeah BTS is super broken atm, I suppose you could put a warning in the BTS style if its not fixed by next release

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1241
