### ISSUE TITLE
add option to bee2 to disable additional music tracks

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#247]
add an option to bee2 to disable the additional music tracks (gel, funnel, laser etc) if wanted.

it gets really annoying when jiggle bone plays in a portal 1 test chamber and you fly through a portal or use no clip and the additional music track plays really loud constantly.

**Comment by Luke18033** [comment]
Most of these bugs have been fixed, but this stylevar would still be nice.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1495
