### ISSUE TITLE
Glass with hole

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#248]
I was wondering if you could add a simple glass panel that has a cube and ball sized hole in it. this would be useful for coop maps as well as help with a small hole where people can shoot portals from. This item would also be nice with a non-glass version thats just a solid wall.

**Comment by LautaroL20** [comment]
I am also wish the re-implementation of this item. But the only problem is that this item is almost useless in Co-op since there is no pysics for cube objects :(

**Comment by Konclan** [comment]
What do you mean no physics for cube objects?

**Comment by LautaroL20** [comment]
It is a bug in the Co-op source engine version from Portal 2. This does not happens in Single-player.

**Comment by xDadiKx** [comment]
But in the Co-op campaign, it works?

**Comment by LautaroL20** [comment]
I think its the same, but Valve has managed to making puzzles without using the "Grating" puzzle concept on their co-op maps. Check this video to see what i mean with "No pysics for co-op":

https://youtu.be/3E4SBZbIzx8

**Comment by Konclan** [comment]
Oh I think I understand now, it does matter the shape of the hole in coop because the people can still get objects through them due to held items not having physics

**Comment by Konclan** [comment]
I still think this item is useful because in some of my maps I want to make a place where people can shoot portals through but I don't want it a panel sized hole, I want to restrict them to only a little area

**Comment by LautaroL20** [comment]
Yes, "Glass with hole" for co-op could be a little bit useful as long as you dont introduce "Cubes", into the puzzle area of this item.

**Comment by MrKrunk** [comment]
They don't have physics enabled so the players never get stuck in them. Their physics are then enabled once they are out of the player's grasp.

**Comment by LautaroL20** [comment]
This must be into the items section, also this will gonna be implemented.
