### ISSUE TITLE
Game freeze when pressing "Build and Play"

### ISSUE THREAD

**Issue by towergame** [BEEmod/BEE2.4#252]
I have the BTS scene, Factory skybox, Cave Johnson and PeTI music enabled. I have an empty test chamber.

**Comment by towergame** [comment]
After ending it with command line(because the freeze blocks scrolling or clicking in programs.) the BEE2.4 shows me this error while trying to export a different palette:
http://puu.sh/nK8rA/c850e09a7f.jpg

**Comment by TeamSpen210** [comment]
That means the BEE2 can't overwrite the compiler files. That probably indicates that the compiler is still running for some reason. Check task manager for processes named `vbsp` or `vrad`.

**Comment by towergame** [comment]
vbsp.exe process won't show in task manager and it won't show when typing tasklist in command line. But it succesfully copied the files after i renamed vbsp to vbsp2.

**Comment by LautaroL20** [comment]
This doesn´t happens at all for me and many other users, so this was probably fixed since a time ago.
