### ISSUE TITLE
Aperture Tag Coop have the same portal gun

### ISSUE THREAD

**Issue by Gimzie** [BEEmod/BEE2.4#253]
When making and testing coop maps, the other player's gel gun does not work. No fizzlers activate it either. I'm pretty sure it's a bug.

**Comment by Konclan** [comment]
If you're talking about how one person has a gel gun and the other has a portal gun, this is how it is in the mod so I believe it is intentional

**Comment by Gimzie** [comment]
Konclan, nonono, I see I wasn't very detailed in my description. Basically, both players have a portal gun, instead of one player only having the gel gun, and one with the portal gun. So it IS a bug, as there shouldn't be two portal guns like in P2...

**Comment by Konclan** [comment]
Ah ok, nvm then

**Comment by Luke18033** [comment]
This has now been fixed.
