### ISSUE TITLE
Portalable/Non-Portalable Piston Platform

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#266]
Like the extending piston plateform, The extending panel would push in and out, except you can make it portable and non-portable.

**Comment by TeamSpen210** [comment]
You mean a portalable/non-portalable piston platform, or using panel arms?

**Comment by Konclan** [comment]
Piston plateform

**Comment by LautaroL20** [comment]
This will gonna be implemented, and also this is a duplicate of the item´s list: https://github.com/BEEmod/BEE2-items/issues/95
