### ISSUE TITLE
Beemod fails to compile

### ISSUE THREAD

**Issue by jccreszMinecraft** [BEEmod/BEE2.4#268]
Beemod fails to compile chambers when loaded in any form. This makes it impossible to create chambers with it. For PeTI to go back to a functional state, Portal 2 required you to verify cache to fix the issues. Here is the console log.

> [PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
> [PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
> [PORTAL2 PUZZLEMAKER]  Compilation time (after export): 86 (ms)
> 
> VBSP failed.
> 
> [I] vbsp: BEE2.4.0pr19 VBSP hook initiallised.
> [I] cond.core: Imported all conditions modules!
> [I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [I] vbsp: Clearing inject/ directory..
> [I] vbsp: PeTI map detected!
> [I] vbsp: Loading settings...
> [W] instanceLocs: None in vals: False
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Failed parsing weight! ([])
> [W] cond.core: Failed parsing weight! ([])
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Failed parsing weight! ([])
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Invalid weight! ()
> [W] cond.core: Invalid weight! ()
> [I] vbsp: Settings Loaded!
> [I] vbsp: Parsing Map...
> [I] vbsp: Reading Map...
> [I] vbsp: Loading complete!
> [I] vbsp: Forcing elevator spawn!
> [I] vbsp: Using random SP Exit (4)
> [I] vbsp: Using random SP Entry (7)
> [I] vbsp: Game Mode: SP
> [I] vbsp: Is Preview: False
> [I] cond.core: Checking Conditions...
> [I] cond.core: Exiting empty condition!
> [I] cond.core: GooDebris: 0/0 locations
> [I] cond.catwalks: Starting catwalk generator...
> [I] cond.core: Exiting empty condition!
> [I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
> [I] cond.scaffold: Finished Scaffold generation!
> [I] cond.core: Exiting empty condition!
> [I] cond.core: Exiting empty condition!
> [I] cond.core: Exiting empty condition!
> [I] cond.core: Exiting empty condition!
> [I] cond.core: Exiting empty condition!
> [I] cond.core: Exiting empty condition!
> [I] cond.core: Exiting empty condition!
> [I] vbsp: Elevator type: RAND
> [I] voiceLine: Adding Voice Lines!
> [I] voiceLine: Quote events: []
> [I] voiceLine: []
> [I] voiceLine: No responses data..
> [I] voiceLine: Mid quotes: []
> [I] voiceLine: Done!
> [I] vbsp: Setting Portalgun:
> [I] vbsp: Blue: Y, Orange: Y
> [I] vbsp: Done!
> [I] vbsp: Added Screenshot Logic
> [I] cond.core: Map has attributes: 
> [I] cond.core: Style Vars:
> [I] cond.core: Global instances: 
> [I] vbsp: Adding Music...
> [I] vbsp: Adding Global PTI Ents
> [I] vbsp: Editing Other Entities...
> [I] vbsp: Editing Brushes...
> [I] vbsp: Make Bottomless Pit: False
> [I] vbsp: Adding Goo Mist...
> [I] vbsp: Done!
> [I] vbsp: Editing Overlays...
> [I] vbsp: Editing Triggers...
> [I] vbsp: Collapsing goo triggers...
> [I] vbsp: Done!
> [I] vbsp: Editing Brush Entities...
> [I] vbsp: Removing static indicator toggles...
> [I] vbsp: Done!
> [I] vbsp: Editing WorldSpawn
> [I] vbsp: Making Pack list...
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_center.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_left.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/clean_csf_right.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/compressed_smoke_field.vmt"
> [I] vbsp: "materials/BEE2/fizz/fourthreaper/player_clip_electric.vmt"
> [I] vbsp: "materials/BEE2/josepezdj/signage_wasted/base.vmt"
> [I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
> [I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
> [I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
> [I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/black.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vtf"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vmt"
> [I] vbsp: "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vtf"
> [I] vbsp: "models/BEE2/props_ingame/cust_fizz.dx90.vtx"
> [I] vbsp: "models/BEE2/props_ingame/cust_fizz.mdl"
> [I] vbsp: "models/BEE2/props_ingame/cust_fizz.phy"
> [I] vbsp: "models/BEE2/props_ingame/cust_fizz.vvd"
> [I] vbsp: "scripts/vscripts/BEE2/video_splitter_rand.nut"
> [I] vbsp: "materials/BEE2/overgrown/screens/elevator_video_overlay3.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
> [I] vbsp: Packlist written!
> [I] vbsp: Generating VRAD config...
> [I] vbsp: Saving New Map...
> [I] vbsp: Complete!
> Calling original VBSP...
> "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> VBSP failed! (1)

A side note is that on my PC (it may be a one-off case) I can only run Beemod by launching it with administrator privileges.

**Comment by BenVlodgi** [comment]
@TeamSpen210 is there a log for when the VBSP fails?

**Comment by TeamSpen210** [comment]
Check `sdk_content/maps/styled/preview.log`. `Stdout` from VBSP is cloned to Portal 2's console, so there probably isn't any other output. A number of people have had this error, where VBSP fails for no apparent reason.

**Comment by jccreszMinecraft** [comment]
Sometimes the compile process reaches VRAD and then quits.


```
VRAD failed.

[I] vrad: BEE2 VRAD hook started!
[I] vrad: Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[I] vrad: Loading Settings...
[I] vrad: Config Loaded!
[I] vrad: Files to pack:
[I] vrad:  # "materials/bee2/glass_player_clip.vmt"
[I] vrad:  # "materials/bee2/grate_player_clip.vmt"
[I] vrad: Injected files:
[I] vrad: Packing Files!
[I] vrad: Packing complete!
[I] vrad: Using automatic screenshot!
[I] vrad: Screenshot "..\portal2\screenshots\preview0006.jpg" too old (3:43:55.634397)
[I] vrad: Screenshot "..\portal2\screenshots\preview0005.jpg" too old (3:47:13.042118)
[I] vrad: Screenshot "..\portal2\screenshots\preview0004.jpg" too old (3:52:00.930950)
[I] vrad: Screenshot "..\portal2\screenshots\preview0003.jpg" too old (3:55:59.787968)
[I] vrad: Screenshot "..\portal2\screenshots\preview0002.jpg" too old (4:00:53.595393)
[I] vrad: Screenshot "..\portal2\screenshots\preview0001.jpg" too old (4:03:19.882863)
[I] vrad: Screenshot "..\portal2\screenshots\preview0000.jpg" too old (4:05:29.781074)
[I] vrad: No Auto Screenshot found!
[I] vrad: Cleaning up screenshots...
[I] vrad: Done!
[I] vrad: Using PeTI screenshot!
[I] vrad: Making "..\portal2\puzzles\76561198134803283\untitled.jpg" replaceable...
[I] vrad: Forcing Cheap Lighting!
[I] vrad: Calling original VRAD...
[I] vrad: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vrad_original" -bounce 2 -noextra -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp"
[W] vrad: VRAD failed! (1)
```

**Comment by jccreszMinecraft** [comment]
https://docs.google.com/document/d/1F9L9qrSuB7WnYe7fIiXoUZh0E112bBerKVlYsyJuVxk/edit?usp=sharing

**Comment by LautaroL20** [comment]
That log doesn´t say anything substantial. In order to get a log with the real cause, just turn on `Developer 2` on the console, then re-compile the puzzle and paste the new log.

**Comment by LautaroL20** [comment]
@jccreszMinecraft - Get Pre-release 27 (Packages & Application) since this is most likely fixed now. Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
