### ISSUE TITLE
Master Portalgun Item [Logic]

### ISSUE THREAD

**Issue by jccreszMinecraft** [BEEmod/BEE2.4#271]
A item that is invisible but determines what kind of portal gun the player starts out with. Button type determines team/gun type, while Start Enabled and Start Reversed properties control portals 1 and 2 respectively. Timeout portals can be integrated into this item via timer widget.

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1239
