### ISSUE TITLE
Permanent Gate [Logic]

### ISSUE THREAD

**Issue by jccreszMinecraft** [BEEmod/BEE2.4#273]
A logic item that triggers an output permanently or for a set time. Useful in situations where a floor button needs to be pressed only once, or similar situations.

**Comment by TeamSpen210** [comment]
For the set-time function, use a 'Shutdown Delayer' item. That activates immediately, but waits for a time before switching off the output. Permanent outputs would need a new logic item.

**Comment by OnlyFails** [comment]
This is easy, just have an SR Latch, attach only input A and trigger only input A and get the output from the SR Latch. This will permanently set the output of the SR Latch to on once input A gets power.

**Comment by LautaroL20** [comment]
SR Latch meets this exact same funtion. Also this should be posted into:  https://github.com/BEEmod/BEE2-items/issues
