### ISSUE TITLE
Personality core / Core Rails / Core plug

### ISSUE THREAD

**Issue by jccreszMinecraft** [BEEmod/BEE2.4#283]
A item set oriented around cores.

If the Personality core is hooked to a set of rails, it will follow the rails in the order it is hooked to other railing items. ~~If the personality core is not hooked to anything, it will spawn off a rail and fall to the ground. Core plugs will activate an output. Inputs can be made to unlock the core plug.~~

**Comment by Konclan** [comment]
Oh, and you can pick the core's saying with a timer setting (Like how signage works) so you can select from a bunch of preset sayings. I don't know about core plugs though. I just imagine the core would come by a hole in the wall, say something, then leave (also emit an output once it's done). And then it would start by being activated by a trigger or something

**Comment by Konclan** [comment]
I also think the core would be like an observation room sized thing

**Comment by TeamSpen210** [comment]
I'm not sure how well this would work in 1950s styles (since cores shouldn't be around in that time period). Which core it is would probably actually get set by the chosen voicelines. For Cave, Caroline and GLaDOS, perhaps it'll just not appear. (I might make a GLaDOS-core reskin..)

AI-wise: For each track point it should calculate the distance to the closest player. Then it should move to the track closest to a player, and turn to face that player. That'll work in SP and Coop quite nicely.

**Comment by jccreszMinecraft** [comment]
I would say make the item unavailable in certain themes unless items are unlocked.

**Comment by TeamSpen210** [comment]
I can't (and won't) really do that. I could disallow putting it on the palette, but what should happen if you load a map which already contains them? It's actually not styles I want to switch on, but the voiceline that's chosen.

**Comment by jccreszMinecraft** [comment]
Maybe for the core, the start reversed/start enabled and cube subtypes can determine the core type

**Comment by TeamSpen210** [comment]
I'll just set it via the quote set that's selected, and also add an option to turn off voice lines entirely.

**Comment by SpyyZ158** [comment]
Maybe BTS 1950 like in Portal Stories Mel where is like Virgin out of track and as Mel you put him on?

**Comment by Konclan** [comment]
I don't think having the person carry the core is a good idea

**Comment by SpyyZ158** [comment]
I meant tracks

**Comment by PandaVoxel** [comment]
@TeamSpen210 Are you going to add this in a future release as it sounds like a brilliant idea.

**Comment by TeamSpen210** [comment]
Perhaps a core on a management rail, but definitely not one that can be carried around.

**Comment by PandaVoxel** [comment]
@TeamSpen210  When will the next release be out?

**Comment by Luke18033** [comment]
Issue moved to [BEEmod/BEE2-items #1493](https://github.com/BEEmod/BEE2-items/issues/1493) via [**ZenHub**](https://www.zenhub.com/)
