### ISSUE TITLE
Custom Background Music 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#289]
I dont know if this is doable or not so, sorry for my ignorance, but i think it would be magnificent to have an option on Bee2.4 to export custom music tracks into the maps builded with bee2.

**Comment by TheReviewers** [comment]
@LautaroL20 , But What If...

Russian Player : Omg Bee2 Added Custom Music

Player : Hmm. A Nice Map, Lemme Download

10 Seconds Later

* Russian Music Intensifies *

**Comment by Konclan** [comment]
I feel like this would create a huge problem with troll maps with stupid background music. Also there would have to be a volume cap on the music so you dont walk into a map with ear rape

**Comment by LautaroL20** [comment]
@Konclan - Well, respect to "Troll maps" it would not be a problem mostly because people will rated them with many Thumbs Down, and then those troll maps will go to the cemetery very quickly.
There is already a tons of troll maps terrible maded and being published, but people will decide if they likes them or not.

Also, there is no need to have a "Monopoly" PeTi music, there also should be others alternatives like having an option to have custom Backgrown music.

**Comment by LautaroL20** [comment]
I have played many hammer maps with Custom Backgrown music and it fits very well. Thats because i am suggesting this for bee2.

**Comment by TeamSpen210** [comment]
There's one small issue with doing this - additional audio tracks. Portal 2's music tracks use multiple extra files to play additional audio when you're jumping on bounce gel, riding in funnels, flinging or when laser catchers activate. I'll need to figure out a nice way to select these. (It's a bit complicated adding custom versions of these tracks, so it'll be limited to P2 ones only.)

**Comment by MrKrunk** [comment]
There are actually quite a few ways to get around that additional audio tracks problem.
1. If possible, the track selected should be either slowed down or sped up.
2. Use the same, unaffected track.
And finally,
3. Add the option to insert a different track (In the music selection tab) for when the player is doing something.
Adding any three of these examples would make adding custom music much easier.

**Comment by LautaroL20** [comment]
Also there should be a "Stylevar Option" to disable those "Aditional audio tracks" like the In-Air Music.

**Comment by LautaroL20** [comment]
Implemented with the Beemod Music Changer application.
