### ISSUE TITLE
Secondary input for the Portal Gun Pedestal - raise/lower

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2.4#293]
If a portal gun is given an input by something it should bring the portal gun out of the holding area.

**Comment by Konclan** [comment]
So you mean a way to put the portal gun on the floor instead of on a pedestal or something?

**Comment by MrKrunk** [comment]
Well, no, I meant that if an input were triggered, the portal gun would be lifted out of the black area. Or whatever it is. That sounds like a good idea, though.

**Comment by TeamSpen210** [comment]
Currently inputs turn on an off the portal-firing feature. After I switch to using the compiler for input A/B, I could add this as a secondary input (which disables portal shots while down).

**Comment by Konclan** [comment]
Oh so it would retract into the floor, I understand now

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1242
