### ISSUE TITLE
Mashy Spike Plate Error

### ISSUE THREAD

**Issue by GLiTcH2** [BEEmod/BEE2.4#308]
New here so sorry if this is a known issue, However when I try to place down the Mashy Spike Plate no object appears only the word Error appears where the object should be.... Any help?

**Comment by Konclan** [comment]
It's fine, the Mashy Spike Plate is still there and will work when you press Build and Play.

**Comment by GLiTcH2** [comment]
Oh I see, Thank you.

**Comment by TeamSpen210** [comment]
Which style does this occur in?

**Comment by GLiTcH2** [comment]
I am using the Clean Style

**Comment by LautaroL20** [comment]
Fixed since a time ago.

**Comment by LautaroL20** [comment]
I think this issue is reffer to the missed editor model wich is fixed since a time ago.
