### ISSUE TITLE
Testchamber fails to build with BEE2.4 installed

### ISSUE THREAD

**Issue by SupernovaCo** [BEEmod/BEE2.4#341]
When I try to build any testchamber, no matter what elements were used in it (vanilla portal 2 or otherwise), it gives me a build error, and the developer console spits out the following mess:

VBSP failed.

[I] vbsp: BEE2.4.0pr20 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] BEE2_config: Config "C:\Users
 |_iels\Desktop\MiscApps\BEE2.4_pr20_win\config/compile.cfg" not found! Using defaults...

[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Using random SP Entry (4)
[I] vbsp: Using random SP Exit (1)
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: True
[I] cond.core: Checking Conditions...
[I] cond.core: GooDebris: 28/44 locations
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Adding quote: "Line_SP"
 |  {
 |  "ID" "TURR_ENTRY_SP"
 |  "Choreo" "npc/announcer/testchamber05.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Line "??" is disabled..
[I] voiceLine: Adding quote: "Line_SP"
 |  {
 |  "ID" "EXIT_TURRET"
 |  "Choreo" "npc/announcer/testchamber06.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line"
 |  {
 |  "Name" "Avoid Being Shot"
 |  "Target" "@voice_turret_activate"
 |  "Choreo" "npc/announcer/sabotage_factory17.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] cond.core: Map has attributes: ['spawn_dual', 'goo', 'turret', 'rocketturret', 'deadly']
[I] cond.core: instanceLocs cache: CacheInfo(hits=9437, misses=285, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'allowgoomist': True, 'fixfizzlerbump': False, 'bee_show_trigger': False, 'unlockdefault': False, 'multiversecave': True, 'nomidvoices': False, 'bee2_goo_debris': True}
[I] cond.core: Global instances: {'instances/bee2/clean/items/rocket_turret/logic.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_3.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Adding Goo Mist...
[I] vbsp: Done!
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "materials/BEE2/grate_player_clip.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted/base.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape1.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape1.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape4.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape4.vtf"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape5.vmt"
[I] vbsp: "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape5.vtf"
[I] vbsp: "materials/models/props_bts/rocket_sentry.vmt"
[I] vbsp: "materials/models/props_bts/rocket_sentry.vtf"
[I] vbsp: "materials/models/props_bts/rocket_sentry_b.vmt"
[I] vbsp: "materials/models/props_bts/rocket_sentry_b.vtf"
[I] vbsp: "materials/models/props_bts/rocket_sentry_c.vmt"
[I] vbsp: "materials/models/props_bts/rocket_sentry_c.vtf"
[I] vbsp: "materials/models/props_bts/rocket_sentry_exponent.vtf"
[I] vbsp: "materials/models/props_bts/rocket_sentry_inactive.vmt"
[I] vbsp: "materials/models/props_bts/rocket_sentry_inactive.vtf"
[I] vbsp: "materials/models/props_bts/rocket_sentry_normal.vtf"
[I] vbsp: "models/props_bts/rocket_sentry.dx80.vtx"
[I] vbsp: "models/props_bts/rocket_sentry.dx90.vtx"
[I] vbsp: "models/props_bts/rocket_sentry.mdl"
[I] vbsp: "models/props_bts/rocket_sentry.sw.vtx"
[I] vbsp: "models/props_bts/rocket_sentry.vvd"
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_specific.nut"
[I] vbsp: "sound/weapons/rocket/rocket_fire1.wav"
[I] vbsp: "sound/weapons/rocket/rocket_fly_loop1.wav"
[I] vbsp: "sound/weapons/rocket/rocket_locked_beep1.wav"
[I] vbsp: "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] <Valve>: Valve Software - vbsp.exe (Aug 26 2014)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 530 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (0)
 | writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
 | done (0)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (1) (625958 bytes)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Water found with no water_lod_control entity, creating a default one.
 | Compacting texture/material tables...
 | Reduced 3288 texinfos to 893
 | Reduced 65 texdatas to 61 (1942 bytes to 1800)
 | Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
 | 
 | nummapplanes:     ( 10082 / 65536 )
 | nummapbrushes:    (  1738 /  8192 )
 | nummapbrushsides: ( 14002 / 65536 )
 | num_map_overlays: (    11 /   512 )
 | nummodels:        (    52 /  1024 )
 | num_entities:     (   405 / 16384 )
 | 
 | 4 seconds elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (750E0000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 774FB8F0
 | CDynamicFunction: Closing library 'Kernel32.dll' (750E0000)
 |_

[I] vbsp: VBSP Done!
[I] vbsp: Retrieved counts: {'entity': ('405', '16384'), 'brush': ('1738', '8192'), 'overlay': ('11', '512')}
[I] BEE2_config: Saving changes in config "C:\Users
 |_iels\Desktop\MiscApps\BEE2.4_pr20_win\config/compile.cfg"!

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3860, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3620, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3681, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 53, in save
  File "F:\Git\BEE2.4\src\utils.py", line 903, in **enter**
  File "F:\Git\BEE2.4\src\utils.py", line 893, in make_tempfile
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 237, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\Users\niels'

**Comment by QuantiX999** [comment]
Try moving BEE out of your user folders, like Documents of Pictures.

**Comment by SupernovaCo** [comment]
Aha! Lemme try that. Thanks!

*--Marvin_Megavolt*

**Comment by LautaroL20** [comment]
Don´t merge the Beemod install alongside the Portal 2 folder, instead install it separately.

**Comment by seamuskills** [comment]
i cant get it to work still and i dont know what the problem is, is it portal 1 style or the sky box i dont understand...

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by seamuskills** [comment]
ill try it

**Comment by seamuskills** [comment]
i dont know where the og bee mod is if thats what i need to uninstall

**Comment by seamuskills** [comment]
how do i find its prerelese

**Comment by seamuskills** [comment]
its the packages were a diff prerel

**Comment by seamuskills** [comment]
testing now thanks for the help

**Comment by seamuskills** [comment]
IT WORKS thanks SOOOOOOOOOOOO much for the help no one else would give!!!!!

**Comment by LautaroL20** [comment]
Glad to see my steps helped you out.

**Comment by NoaxPrime** [comment]
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 538, in move
PermissionError: [WinError 5] Access is denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bin\\vbsp_original.exe' -> 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bin\\vbsp.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\gameMan.py", line 1275, in remove_game
  File "F:\Git\BEE2.4\src\gameMan.py", line 403, in edit_gameinfo
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 552, in move
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 251, in copy2
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\shutil.py", line 115, in copyfile
PermissionError: [Errno 13] Permission denied: 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\bin\\vbsp.exe'
Uh... This happened when I tried uninstalling it from Portal 2. What do I do? o_O

**Comment by LautaroL20** [comment]
@NoaxPrime - That also happens when your antivirus secretly blocks the compiler files of Beemod, so you will have to add the compiler files to the exception list of your antivirus.

**Comment by shepardgraff-png** [comment]
I got the QoL UCP, but it is not working. This is the dev console when I run the test:
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_wom_cond_plate_clean.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_wom_cond_plate_clean.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_angled_60.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_angled_60.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_angled_45.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_angled_45.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_angled_30.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_angled_30.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_autoportal_oran_p2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_autoportal_oran_p2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_block_flat_quart.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_block_flat_quart.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_glass_hole_small.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_glass_hole_small.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2/clean/mon_camera.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2/clean/mon_camera.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_logic_delayer_rising.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_logic_delayer_rising.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_pgun_pedestal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_pgun_pedestal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_BEE2/error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_BEE2/error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_door_90deg.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_door_90deg.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_large_faith_plate.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_large_faith_plate.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_pgun_pedestal_oran.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_pgun_pedestal_oran.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_trigger_once.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_trigger_once.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_trigger_multiple.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_trigger_multiple.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_paint_dropper_editor_grey.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_paint_dropper_editor_grey.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_pgun_pedestal_dual.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_pgun_pedestal_dual.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_glass_hole_large.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_glass_hole_large.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_logic_delayer_falling.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_logic_delayer_falling.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_over_pedestal_button_middle.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_over_pedestal_button_middle.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_selection_over_pedestal_button_middle.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_selection_over_pedestal_button_middle.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_vactube_grid_1x1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_vactube_grid_1x1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_door_bee_closed_50s.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_door_bee_closed_50s.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_light_strip_warm.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_light_strip_warm.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_fr_compressed_smoke_field.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_fr_compressed_smoke_field.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bts_opening.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bts_opening.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris0.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris0.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_debris3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_debris3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_rocket_sentry_clean.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_rocket_sentry_clean.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_resources/models/BEE2/splitter_straight.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_resources/models/BEE2/splitter_straight.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
Unknown command "cl_puzzlemaker_start_editing"
[PORTAL2 PUZZLEMAKER]  Saved puzzle: c:/program files (x86)/steam/steamapps/common/portal 2/portal2/puzzles\76561199756379533\autosave.p2c

**Comment by vrad-exe** [comment]
@shepardgraff-png This issue is over 10 years old, please don't leave random comments on it. We don't officially support UCPs, but if the error still happens with UCP items removed then you can open a new issue or discussion to report it.
