### ISSUE TITLE
add start music after voice lines checkbox

### ISSUE THREAD

**Issue by genestrashcan** [BEEmod/BEE2.4#344]
add a start music after voice lines checkbox so the voice line chosen will play first and then the test chamber music starts when the voice line ends.

**Comment by Luke18033** [comment]
This doesn't seem very useful. Can you give an example of where you would use it?

**Comment by TeamSpen210** [comment]
It's useful to make it easier to hear voice lines.

**Comment by Luke18033** [comment]
Maybe with some tracks, but with most you can hear it just fine.

**Comment by Luke18033** [comment]
Yeah I still don't really see a use for this, most music isn't loud enough to drown out voice lines and the volume of other sounds lowers when a voice line plays anyway.
