### ISSUE TITLE
BUGs BEE 21.5 Rocket Turret and Futbol don´t work correct

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#365]
Futbol produced in a continuous loop balls
Rocket Turret can't shoot any missiles
see video here what i mean : https://drive.google.com/open?id=0B8XrjMUJddxnbTh0RERpQnUwMFU

**Comment by LautaroL20** [comment]
Futbol item is fixed, but not the Rocket Turret. This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/287
