### ISSUE TITLE
Mac using Python 3.4.4 not working with latest BEE2 version?

### ISSUE THREAD

**Issue by Lythair** [BEEmod/BEE2.4#367]
I recently re-installed python 3.4.4 so as to use BEE2, however, I have been running into error after error.

So as I go to run the exec file in the bin, as suggested by the README, I end up with an error that looks like this.

dyld: Library not loaded: /Library/Frameworks/Python.framework/Versions/3.4/Python
  Referenced from: /Users/xxxxx/Desktop/BEE2.4.0pr21.5_mac/bin/BEE2
  Reason: no suitable image found.  Did find:
    /Library/Frameworks/Python.framework/Versions/3.4/Python: no matching architecture in universal wrapper
    /Library/Frameworks/Python.framework/Versions/3.4/Python: no matching architecture in universal wrapper
Trace/BPT trap: 5
logout

[Process completed]

Anybody know what I did wrong?

**Comment by dunkler-schatten** [comment]
The error say you don´t have Python 3.4 installed on your Mac. or not correctly installed.
I had in the past the same problem with exact the same error
You must install Python 3.4.x not Python 3.3 and not ver. 3.5 or else.
See my Video: https://www.youtube.com/watch?v=_mehygDBmRs for help
I hope this solve your problem
