### ISSUE TITLE
Bee2 doesn't load and vpk_cache folder gets empty and un-accessible.

### ISSUE THREAD

**Issue by Flairieve** [BEEmod/BEE2.4#380]
It looks like when Bee2 deletes the vpk_cache which I think that's right? The folder becomes un-accessible which for some odd reason makes Bee2 not load up completely when starting up until I restart my computer. No clue if its Windows 10 or the mod in general. Thanks for reading!

**Comment by Flairieve** [comment]
``

**Comment by Flairieve** [comment]
The only way to not make this happen is before launching Bee2.exe again is by deleting vpk_cache folder each time.

**Comment by TeamSpen210** [comment]
Does this still occur?
