### ISSUE TITLE
[Bug] Panels "screaming" and bugging in old aperture maps

### ISSUE THREAD

**Issue by cartman1337** [BEEmod/BEE2.4#392]
I recently made a map in 60s style, where the main things used were angled panels and various gels. I was unable to make the test quite how I wanted it to be, because whenever I activated an angled panel with a button, they would stay activated, even after removing myself of the cube used to push the button. Occasionally, when pressing and unpressing a button several times, they'd return to the original state, but most of the time they would just stay active after being activated the first time. In addition to that, the panels would make a horrible "screaming" noise whenever activated, the first "scream" being heard out at the elevator when the panels set to start activated would activate. This behavior seems to be present in all the old aperture styles.

I've now remade the chamber with Beemod 2.2.5, where the panels do not "scream", and return to their original state when buttons stop being pressed.

This behavior should be addressed in a later version of Beemod 2.4.

**Comment by TeamSpen210** [comment]
What do you mean by 'scream'? They do have a moving sound, which should be the same as the ramp in 'sp_a3_speed_ramp' (the first propulsion gel puzzle). The input issue is definitely a bug.

**Comment by cartman1337** [comment]
What I mean is best demonstrated by this video: https://www.youtube.com/watch?v=0SEjF-luR-s&feature=youtu.be

You hear the first "scream" at the very beginning, and then again throughout, with several activation "screams" heard at the end of the video. But as I recorded this with the new version of Beemod 2.4, which was released 6 days ago, I realize that this version seems to have fixed the buggy panels, and they do go back properly. The "scream" was also a lot louder in the previous release, which made it sound REALLY out of place. Still, I cannot remember ever hearing this activation sound for the panels anywhere in the game before, for for a panel, such a sound doesn't really make much sense. It sounds more like an alarm sound, or something.

Here is the same chamber made with the last Beemod 2.2.5 release, where the panels make more normal sounds when activated. You'll also see the reason of the button in the first room, which for my "scream" demo made no sense at all. https://www.youtube.com/watch?v=IqvOl5Xvq_c

**Comment by DeGenerato** [comment]
It's not only that glitch in old aperture. There is a glitch on exit, sometimes you have to crouch to pass trought, and sometimes the door will kill you. With that, the enter door is glitched too, with a graphic source issue. https://steamcommunity.com/sharedfiles/filedetails/?id=753037004 Here is a map that show an example of that glitch, along with the panel glitch.

**Comment by LautaroL20** [comment]
This was fixed since a time ago.
