### ISSUE TITLE
Not able to compile map. Reinstalling everything won't work.

### ISSUE THREAD

**Issue by GumballWatterson** [BEEmod/BEE2.4#403]
Console log:

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF F:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 37 (ms)

VBSP failed.

[I] vbsp: BEE2.4.0pr22 VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "F:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "F:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] brushLoc: Analysed map, filling air... (11 starting positions..)
[I] brushLoc: Air filled!
[I] cond.core: Checking Conditions...
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: FORCE
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: "ENTRY": 1/15 quotes..
[I] voiceLine: Adding quote: "Line"
 |  {
 |  "ID" "GENERIC_1"
 |  "choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: "EXIT": 1/5 quotes..
[I] voiceLine: Adding quote: "Line_SP"
 |  {
 |  "ID" "GENERIC_6"
 |  "Choreo" "scenes/npc/glados/dlc1_leaderboard06.vcd"
 |  }
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: "MIDCHAMBER": 1/9 quotes..
[I] voiceLine: 1 Mid quotes
[I] voiceLine: Adding quote: "Line"
 |  {
 |  "Name" "Cave Reactions"
 |  "File" "clean/cave_reaction.vmf"
 |  }
 |_

[I] voiceLine: Done!
[I] cond.monitor: Bullseye defaultdict(<class 'int'>, {})
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual']
[I] cond.core: instanceLocs cache: CacheInfo(hits=2763, misses=286, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'doorcameras': True, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'multiversecave': True, 'fixfizzlerbump': False, 'bee_show_trigger': False, 'restartonexit': True, 'rexcubepelletfizzle': False}
[I] cond.core: Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
[I] vbsp: Removing static indicator toggles...
[I] vbsp: Done!
[I] vbsp: Editing WorldSpawn
[I] vbsp: Making Pack list...
[I] vbsp: "scripts/vscripts/BEE2/video_splitter_specific.nut"
[I] vbsp: Packlist written!
[I] vbsp: Generating VRAD config...
[I] vbsp: Saving New Map...
[I] vbsp: Complete!
[I] vbsp: Calling original VBSP...
[I] vbsp: Arguments: "F:\SteamLibrary\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "F:/SteamLibrary/steamapps/common/Portal 2/portal2/" "F:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[E] <Valve>: 
[E] vbsp: VBSP failed! (1)

**Comment by GumballWatterson** [comment]
Also, doesn't work with any style, nor combination of items.

**Comment by GumballWatterson** [comment]
Turns out, I didn't completely delete the Portal 2 files. Still, you should definetely look at the issue.

**Comment by Luke18033** [comment]
I had the same thing happen when I first used BEE2.4. I had to reinstall portal 2, and in the process I lost all of my previous maps. The frustrating part was that most of my old published maps later mysteriously disappeared from the server, and were lost permanently. That's not the point though, the point is that this isn't a problem with your computer, I had the same problem.

**Comment by BenVlodgi** [comment]
There is a folder you have to backup if you want to keep your map files

**Comment by TeamSpen210** [comment]
Namely `portal 2/portal2/puzzles/`, or you can use the backup tool. I'm not really sure why this crash occurs, it hasn't ever actually happened for me.

**Comment by Luke18033** [comment]
I know, I accidentally backed up the wrong folder: the one with the BSPs. So although I can play the maps, I can't edit them.

**Comment by PandaVoxel** [comment]
Hi, please look at my issue. I have the same problem but reinstalling hasn't helped. #457

**Comment by LautaroL20** [comment]
@GumballWatterson - Get Pre-release 27 (Packages & Application) since this is most likely fixed now. Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
