### ISSUE TITLE
Add checkbox in options for "Minimize BEE2 after running game"

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#407]
As of Pr20, BEE2 will automatically minimize after exporting and launching the game. Although some people may find it useful, I find it very inconvenient, especially when making a chamber that requires switching between multiple palettes. For this reason, a checkbox should be added to Options: "Minimize BEE2 after running game".

**Comment by TeamSpen210** [comment]
I need to switch this to a dropdown and checkbox - that way you can choose whether to minimize, leave open or quit after, as well as whether to open the game.

**Comment by Luke18033** [comment]
Well until you implement that, can you just disable the minimizing completely? It's really annoying.
