### ISSUE TITLE
Stop the overlaping exporting box

### ISSUE THREAD

**Issue by Jadeygaming** [BEEmod/BEE2.4#418]
Image 
![image](https://cloud.githubusercontent.com/assets/22718537/19916147/aa213de0-a074-11e6-94da-02629f2969bb.png)

**Comment by LautaroL20** [comment]
Heh, if you are complaining about that little rendering panel overlapping your deckstop, then you don´t want to know what is to come then.... lol! But if it's any consolation, it will include some nice screenshots.

**Comment by LautaroL20** [comment]
Unfortunately, this seems to be not possible :(
