### ISSUE TITLE
When You Die, Music Stops Playing

### ISSUE THREAD

**Issue by QuantiX999** [BEEmod/BEE2.4#421]

**Comment by Jadeygaming** [comment]
?

**Comment by Byzarru** [comment]
The music will re-start for a select few items after a while (the Rexaura tracks work in this regard).

**Comment by quat1024** [comment]
More specifically the music stops when you load the game (whether that's by dying or by F6/F7)

**Comment by Luke18033** [comment]
I don't know why this happens, music continues playing fine in Hammer maps.

**Comment by ZombiePwner1** [comment]
It's definitely a bug with puzzlemaker maps. But it's unknown what causes it.

**Comment by Luke18033** [comment]
@ZombiePwner1 - No, it's not a bug with puzzlemaker maps - it's either a bug with *workshop* maps or with the way TeamSpen210 implements music. All of his Hammer maps have this issue, but yet none of mine do.

**Comment by TeamSpen210** [comment]
It's likely to do with the hackery I do to get soundscripts working (which allows funnel music and things like that).

**Comment by Luke18033** [comment]
It turns out this is also an issue in vanilla PeTi maps, it's just not as noticeable there because there are no autosaves (meaning you must quick-save/load to see the glitch).
