### ISSUE TITLE
Text pane

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2.4#425]
![image](https://cloud.githubusercontent.com/assets/22107242/20285120/d430d3aa-aa85-11e6-9b54-cb95da576c29.png)

This is a continuation/offshoot of [BEE2-items/983](https://github.com/TeamSpen210/BEE2-items/issues/983), which suggests that an autosave message should appear after passing through a save point voxel.

I would like to suggest a "Text pane" in BEE, which would:
- Set a map's title
- Set a map's subtitle
- Set a map's title colors
- Set title and subtitle sizes
- Map credits (?)
- Set title locations (Centered/Cornered)
- Set title animations (is that a thing? like fade/type effects)
- Turn on/off autosave notifications (default to off)
- Edit autosave notification text and colors

**Comment by Byzarru** [comment]
Some mock-ups of what it might look like:
![image](https://cloud.githubusercontent.com/assets/22107242/20286228/4ffe7d02-aa8b-11e6-997c-2168f40c6362.png)
![image](https://cloud.githubusercontent.com/assets/22107242/20286458/739636d2-aa8c-11e6-989a-f0db948ce3ec.png)

**Comment by Luke18033** [comment]
@Byzarru How did you get this actually working in BEE2?

**Comment by TeamSpen210** [comment]
That'd be image editing. The only thing this would probably need is the ability to associate the settings with a map - it would be bad to have to re-type the credits and whatnot if you work on a different one.

**Comment by Byzarru** [comment]
@Luke18033 You can make dialogs in Excel (I don't know what you'd do with them or how you'd get them to work) and I just put everything together in Paint. I have the .xlsx file if you want to play around with the dialog. 

@TeamSpen210 Is there a way to pull up local map information externally already or would it require some new code? I've looked around the Portal 2 app files and all I found so far were the puzzlemaker .bsp files.

**Comment by TeamSpen210** [comment]
I could store the information anywhere - the problem is that I don't know which map file is currently the one Portal 2 has loaded, and therefore which to read from. I could do something like assume it's the most recently modified map, but I need to check to ensure that's always accurate. I also need to check to make sure Portal 2 actually saves to disk before exporting.

**Comment by Byzarru** [comment]
I think it does. Published maps seem to be saved in Steam/userdata/.../mymaps and local maps are in Steam/steamapps/.../maps/puzzlemaker.
![image](https://cloud.githubusercontent.com/assets/22107242/20679303/f69da91a-b55f-11e6-9f4d-a6bca6551bfa.png)

**Comment by Byzarru** [comment]
Alternatively, you could include options to pull text data from the latest map and overwrite text data on the next map loaded.

**Comment by PandaVoxel** [comment]
This sounds like a good idea as it would make maps more atmospheric.

**Comment by Luke18033** [comment]
It would probably be a good idea to make the autosave message non-customizable, that way it's consistent between maps and can be set to use a translated text string. It would still be toggleable on and off.

**Comment by TeamSpen210** [comment]
There are a few messages we can use in the language files - which are translated correctly:
```
"PORTAL2_MsgBx_SaveCompletedTxt" = "Game Saved."
"PORTAL2_Hud_SavingGame" = "Saving Game..."
"PORTAL2_Hud_GameSaved" = "Game Saved."
```

**Comment by Konclan** [comment]
Most of this is unnecessary, saving message idea superseded by BEEmod/BEE2-items#983
