### ISSUE TITLE
[Bug] Pre 23 dont start on Mac

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#429]
Really?
Version 22-23 don´t Work on Mac :(
Version 21.5 Work Perfect.

dyld: Library not loaded: /opt/local/lib/libintl.8.dylib
  Referenced from: /Users/XXXXXXXX/Downloads/BEE2.4_pr23_mac/bin/BEE2
  Reason: image not found
Abort trap: 6

Python is already  installed, but i can´t start BeeMod

Thanks for help

**Comment by dunkler-schatten** [comment]
Now does not even work the version pre 21.5 on the Mac :'- (
He starts BeeMod, but crashes after a few seconds.
BeeMod is very cool, but now no version run....... :-( 

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cx_Freeze/initscripts/Console.py", line 27, in <module>
  File "BEE2.pyw", line 151, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tkinter/__init__.py", line 1120, in mainloop
    """Unbind for all widgets with bindtag CLASSNAME for event SEQUENCE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
logout

**Comment by LautaroL20** [comment]
Mac support is no longer in the works. If you want to use Bee2.4 you will have to migrate to Windows 7-10.

**Comment by YELDAH** [comment]
Mac support is no longer in the works. If you want to use Bee2.4 you will have to migrate to Windows 7-10.



REALY I have spent 5 days trying to get this to work >:[

**Comment by TeamSpen210** [comment]
Not true, I'm just not building binaries for it.
