### ISSUE TITLE
Leaks Caused By Deadly Goo In 1980s Style

### ISSUE THREAD

**Issue by Jadeygaming** [BEEmod/BEE2.4#432]
![20161123170816_1](https://cloud.githubusercontent.com/assets/22718537/20581631/d9c06558-b19f-11e6-8aec-c61f0d2d91bf.jpg)
And,
![20161123170843_1](https://cloud.githubusercontent.com/assets/22718537/20581635/dfef29d2-b19f-11e6-86ed-66f216c6a89a.jpg)

**Comment by Luke18033** [comment]
This should go on BEE2-items

**Comment by LautaroL20** [comment]
Wich items do you had in the editor?

**Comment by Jadeygaming** [comment]
Gel, Gel droppers, Ariel faith plates, Laser beams, Laser catchers, Panels, Reflection gel, Repultion gel, Door (LOL) and much much more.

**Comment by LautaroL20** [comment]
Pretty strange, i tried to build a 80´s old aperture map using some items and i didnt get those leaks. There is surely an item that is causing this.

**Comment by Luke18033** [comment]
Put this on [BEE2-items](https://github.com/BEEmod/BEE2-items).
