### ISSUE TITLE
Beemod´s Selector Windows becomes "Broken", after clicking a Style it becomes "Impossible" to set to another Style / Music

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#440]
Beemod´s Selector Windows becomes"Broken" after clicking a Style.

**Comment by TeamSpen210** [comment]
This doesn't happen to me.

**Comment by LautaroL20** [comment]
Well, after syncing the github app, i launched the dev version and double-clicking woked the first time, but then when i tried to set to another style it becomed impossible. I can record a small video though.

**Comment by LautaroL20** [comment]
@TeamSpen210 - It looks like you found the cause for this.
