### ISSUE TITLE
begin reworking bottomless pit code

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#441]
begin reworking bottomless pit code in the long term as @TeamSpen210 and @BenVlodgi planned to make pits generate more like they do in valve test chambers to solve many issues with pits...

once this is done i can rework and release many of my prototype pits for the new config...

**Comment by Luke18033** [comment]
Put this on [BEE2-items](https://github.com/BEEmod/BEE2-items).
