### ISSUE TITLE
Bee2.4 windows installer

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#442]
we need to have a Bee2.4 windows installer created that will do the following, we also need to merge the packages file into the main bee2.4 before this can happen. i recommend install forge for creating the main installer...

- [x] (prerequisite) merge the packages file into the main Bee2.4 file directory at each release (this is as easy as cake and should be considered already done)
- [ ] install the main program under the program files folder
- [ ] generate a shortcut to the desktop for the main bee2 exe file...

**Comment by TheDarkBomber** [comment]
I think you should join the [BEE2.4 Gitter](https://gitter.im/BenVlodgi/BEE2.4)

**Comment by LautaroL20** [comment]
I really like the idea of having an installer for this.

**Comment by TheDarkBomber** [comment]
I prefer downloading BEE2.4 without an installer.

**Comment by LautaroL20** [comment]
Well, personally i would preffer to have the packages and the interface in one file installer, but tastes are tastes i guess.

**Comment by TheDarkBomber** [comment]
And flavours are flavours, which should be mostly a delicious variety.

**Comment by Byzarru** [comment]
It's not too hard to unzip a package and look for bin/bee2.exe, but I do like my installers... :p

**Comment by Byzarru** [comment]
This should definitely be something considered along with #78 to make the process a lot smoother.

**Comment by Luke18033** [comment]
@ellingtonvengaboysmuseum Don't put it in Program Files by default. Give the user the option to install it somewhere else.

**Comment by Byzarru** [comment]
BEE2 also needs an uninstaller as well.

**Comment by TheDarkBomber** [comment]
Duplicate of #77

**Comment by LautaroL20** [comment]
@ellingtonvengaboysmuseum - Ive merged your description inside the original suggestion (#77).
