### ISSUE TITLE
[Overgrown] elevator doesn't extend all the way up, so you can see the interior from the outside

### ISSUE THREAD

**Issue by corrupt21** [BEEmod/BEE2.4#444]
![20161207191129_1](https://cloud.githubusercontent.com/assets/17777059/20959838/2bae09da-bcb1-11e6-8f5d-523a5508aa9d.jpg)

**Comment by LautaroL20** [comment]
I don´t see where is the nodraw. Other than the roof from the overgrown elevator.

**Comment by corrupt21** [comment]
This is the elevator shaft
![20161210163348_1](https://cloud.githubusercontent.com/assets/17777059/21071510/b3937622-bef6-11e6-8cb7-24abc13c923d.jpg)


You can see the elevator shaft from here
![20161207191129_1](https://cloud.githubusercontent.com/assets/17777059/21071511/b73cd160-bef6-11e6-8fe7-06392ad7183e.jpg)

**Comment by Luke18033** [comment]
I don't see it. This should go on [BEE2-items](https://github.com/BEEmod/BEE2-items) anyway.

**Comment by TeamSpen210** [comment]
The case around the elevator doesn't extend all the way up, so you can see the interior from the outside.

**Comment by LautaroL20** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/1240
