### ISSUE TITLE
Overgrown Is Not Building.

### ISSUE THREAD

**Issue by TANER05** [BEEmod/BEE2.4#445]
When I try to build an overgrown test chamber, I get this:
![builderror](https://cloud.githubusercontent.com/assets/24416767/21022048/d964a584-bd83-11e6-92b9-15829b825be5.jpg)

Please help.

**Comment by MrKrunk** [comment]
Try to figure out what item in the test chamber may be causing the compile error. I haven't tried out this new release quite yet, but I don't see anybody else having this problem.

**Comment by TANER05** [comment]
The test chamber is empty. I didn't added something.

**Comment by LautaroL20** [comment]
This is because the SP Exit Corridors number: 1, 2 and 4 were broken with the PRL23. Try using the Exit Corridor N3: Floor BTS and youll have no problems when compiling.

**Comment by tjmcnne** [comment]
lautarol I tried that it didn't work.

**Comment by TANER05** [comment]
Thank you so much! :+1: :smile:

**Comment by LautaroL20** [comment]
No problem.
