### ISSUE TITLE
add the reconstruction of panels

### ISSUE THREAD

**Issue by ILIA-NENASHEV** [BEEmod/BEE2.4#448]
![portal2 2012-01-29 01-27-53-44](https://cloud.githubusercontent.com/assets/24510029/21082122/9fbe17ca-bfe5-11e6-9437-ebef5bb893c6.jpg)

**Comment by Luke18033** [comment]
What's this even from? Is it the beta?

**Comment by TheDarkBomber** [comment]
@Luke18033 It says: Portal 2 Episode One.

**Comment by Luke18033** [comment]
Is that a mod?

**Comment by TheDarkBomber** [comment]
No, it's an inside screenshot from the new Portal game Valve is working on.

**Comment by Luke18033** [comment]
"New portal game Valve is working on"? I think this is just a mod...

**Comment by TheDarkBomber** [comment]
[It seems like Valve has hired a team to create the continuation of Portal 2...](http://portal2episode1.blogspot.com)

**Comment by Luke18033** [comment]
If that were an official sequel than it would have been the top result on Google when I search "portal 2 episode 1". Look, it's either fake or a mod.

**Comment by TheDarkBomber** [comment]
I was joking.

**Comment by Luke18033** [comment]
Probably a mod, they wouldn't be developing all of the content for nothing.

Although Valve did design a ton of maps which were removed in the final Portal 2...

**Comment by Luke18033** [comment]
Oh, okay.

**Comment by Luke18033** [comment]
See #414.
