### ISSUE TITLE
Add option to hide Incompatible stylevars

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#449]
![beemod](https://cloud.githubusercontent.com/assets/12244376/21278753/b1eaad9e-c3bb-11e6-8cef-edc65c398a10.png)

**Comment by TeamSpen210** [comment]
The 'other styles' section shows stylevars which don't apply to the selected style.

**Comment by LautaroL20** [comment]
Indeed, and thats why i am reporting this... Why other styles selection should shows stylevars options wich don't apply to the selected style? It would be better to display the options once the apropiated style is selected.

**Comment by Luke18033** [comment]
There's one problem with this - some items are intentionally unstyled. This includes most of the non-1950s Old Aperture items, and everything on Original Clean. Turning this option on would cause lots of items to disappear on those styles. Hiding stylevars would work though.

**Comment by TeamSpen210** [comment]
Those aren't actually unstyled, but inherited from the base style. In that case the stylevar logic treats them as applicable to those styles as well.

**Comment by Luke18033** [comment]
We should add the option to hide incompatible stylevars, items probably doesn't make sense because a lot of items are intentionally unstyled

**Comment by Konclan** [comment]
We don't need an option, this is getting rewritten
