### ISSUE TITLE
Palette arranger

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2.4#450]
This would be a feature that arranges items in the palette based on name, author, package, function, or a random assortment.

**Comment by Luke18033** [comment]
BEE2.2 had an option to generate a random palette. I don't know if BEE2.4 has this though.

**Comment by TheDarkBomber** [comment]
It does.

**Comment by Byzarru** [comment]
I'm talking about the option to randomize or organize what is already on the palette.

**Comment by TheDarkBomber** [comment]
Oh, ok.

**Comment by TeamSpen210** [comment]
Yeah, pretty much. I added a button which randomises your palette, might be interesting to use as inspiration or something.
