### ISSUE TITLE
Overgrown Music

### ISSUE THREAD

**Issue by Jazz63540** [BEEmod/BEE2.4#451]
Whenever I select a song from Portal Stories: Mel that would play during the overgrown test chambers, and attempt to create a test chamber with said song, it simply says "There was an error building the puzzle".

**Comment by Luke18033** [comment]
This has been reported before, but most users don't have this problem. Is Portal Stories Mel installed?

**Comment by Jazz63540** [comment]
Yes it is.

**Comment by Luke18033** [comment]
Then I don't know why you would have this problem. Issues related to the packages, like this one, should go on the [BEE2-items repository](https://github.com/BEEmod/BEE2-items).
