### ISSUE TITLE
Add indicators on the item´s window property when an item is "Unstyled"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#452]
It would be nice to display the items once the apropiated Style is selected.

**Comment by Luke18033** [comment]
And maybe also add an option to hide unstyled items.

**Comment by LautaroL20** [comment]
I already suggested that, here: https://github.com/BEEmod/BEE2.4/issues/449

**Comment by TeamSpen210** [comment]
Not quite, those cases are already handled. You can add a `"base"` command in a style to indicate that another style is acceptable if a specific version isn't available. 1970s and 1980s specify the previous decade, and that works fine. There's a `"unstyled"` flag on items which suppresses the errors entirely for logic gates and the like.
