### ISSUE TITLE
"Style Properties" scroll bar glitchy

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#455]
The scroll bar is invisible, and it is impossible to scroll down, only up. This will still happen even when clicking the arrows. This only happens sometimes, but restarting BEE2 doesn't seem to fix the problem.
![scroll-glitch](https://cloud.githubusercontent.com/assets/19228201/21325112/7f1925b0-c5d9-11e6-8ef7-2caf0005f574.gif)

UPDATE: Clicking "Reset All Windows Positions" seems to fix the problem.
UPDATE 2: Resizing Style Properties at all will fix it.

**Comment by Byzarru** [comment]
Is this the dev version? I don't seem to have this problem.

**Comment by Luke18033** [comment]
It only happens sometimes. I have the problem on both Windows 10 and Windows 7.

**Comment by Luke18033** [comment]
And yes, this is the dev version, but I have had the problem before.

**Comment by Luke18033** [comment]
Why did you close this? Is it fixed?
