### ISSUE TITLE
Monitors

### ISSUE THREAD

**Issue by Thecoolguy03** [BEEmod/BEE2.4#456]
I was testing my chamber, but when I got to the monitor that's supposed to have GLaDOS on it, the screen was blank. Inspecting further, the picture is actually behind monitor.
![20161221094521_1](https://cloud.githubusercontent.com/assets/20453448/21384433/79b68416-c762-11e6-9d82-e38ad546ee40.jpg)

**Comment by Byzarru** [comment]
[This is a duplicate](https://github.com/BEEmod/BEE2-items/issues/1083) [that should go on BEE2-items.](https://github.com/BEEmod/BEE2-items/issues)

**Comment by Byzarru** [comment]
Also, there should probably be a "BEE2-items issue" label.

**Comment by LautaroL20** [comment]
This is fixed for next release btw.
