### ISSUE TITLE
Build Error (Plz Help!)

### ISSUE THREAD

**Issue by PandaVoxel** [BEEmod/BEE2.4#457]
Hi,
I know this issue has come up many times  (#140 #136 #178 #43) but I have no idea how to fix it. I have the latest edition (pre-release 23) and have tried everything to stop this error but whenever I try to build a test chamber it shows a build error. This happens with every style and even if I have no objects in he chamber. Please help as I really want to be able to use beemod. I have verified files and everything.

**Comment by PandaVoxel** [comment]
This is the dev console log:

Corey Quinn unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,8,7)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 250 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/Program Files/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/Program Files/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Entry (2)
[INFO] vbsp.mod_entryexit(): Using random SP Exit (2)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (87 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.core.steal_from_brush(): Steal: {'rem_brush': True, 'additional': (), 'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x04008E70>, solid=<srctools.vmf.Solid object at 0x03817370>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object atsolidGroup(face=<srctools.vmf.Side object at 0x04008E70>, solid=<srctools.vmf.Solid object at 0x03817370>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x03E429D0>, <srctools.vmf.Solid object at 0x03E429F0>, <srctools.vmf.Solid object at 0x03E42A30>, <srctools.vmf.Solid object at 0x03E42A10>, <srctools.vmf.Solid object at 0x03E42AB0>, <srctools.vmf.Solid object at 0x03E42AD0>, <srctools.vmf.Solid object at 0x03E42B10>, <srctools.vmf.Solid object at 0x03E42AF0>, <srctools.vmf.Solid object at 0x03E42B90>, <srctools.vmf.Solid object at 0x03E42BB0>, <srctools.vmf.Solid object at 0x03E42BF0>], detail=None, overlay=[], orig_ids={1259: 1259, 1260: 1260, 1261: 1261, 1241: 1241, 1391: 1391, 1382: 1382, 1319: 1319, 1320: 1320, 1321: 1321, 1322: 1322, 1323: 1323, 1324: 1324, 1201: 1201, 1202: 1202, 1203: 1203, 1204: 1204, 1205: 1205, 1206: 1206, 1207: 1207, 1208: 1208, 1209: 1209, 1210: 1210, 1211: 1211, 1212: 1212, 1213: 1213, 1214: 1214, 1215: 1215, 1216: 1216, 1217: 1217, 1218: 1218, 1219: 1219, 1220: 1220, 1383: 1383, 1251: 1251, 1238: 1238, 1239: 1239, 1240: 1240, 1380: 1380, 1242: 1242, 1243: 1243, 1381: 1381, 1250: 1250, 1379: 1379, 1252: 1252, 1253: 1253, 1254: 1254, 1255: 1255, 1384: 1384, 1385: 1385, 1386: 1386, 1387: 1387, 1388: 1388, 1389: 1389, 1390: 1390, 1393: 1393, 1392: 1392, 1256: 1256, 1394: 1394, 1395: 1395, 1396: 1396, 1257: 1257, 1258: 1258})}
[INFO] cond.core.steal_from_brush(): New IDS: {'15639': ['1319', '1384', '1390', '1205', '1210', '1215', '1220', '1255', '1261', '1396', '1243']}
[INFO] vbsp.set_elev_videos(): Elevator type: RAND
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 2/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "ENTRY_DEADLY"
 | 	"File" "ann_apoc/entry_jazz.vmf"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_LASER"
 | 	"Choreo" "npc/announcer/prehub18.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/4 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CUBE_BUTTON_TESTING"
 | 	"Target" "@cube_picked_up"
 | 	"Choreo" "npc/announcer/prehub11.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['gel', 'pedestalbutton', 'laser', 'deadly', 'greygel', 'lasercatcher', 'cube', 'reflectiongel', 'cubedropperstandard', 'buttonacceptscube', 'floorbutton', 'weightedbutton', 'buttonacceptsball', 'spawn_dual', 'laseremitter', 'geldropper', 'cubestandard', 'cubedropper']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=14472, misses=314, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'bee_show_trigger': False, 'unlockdefault': False, 'rexcubepelletfizzle': False, 'nomidvoices': True, 'fixfizzlerbump': False, 'multiversecave': False, 'bee2_goo_debris': True, 'allowgoomist': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/items/cube/cache_box.vmf', 'instances/BEE2/logic/reflection_precache.vmf', 'instances/BEE2/over/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape1.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape1.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape4.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape4.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_shape5.vmt"
[[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/clean_dropper_grey.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_on.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty_on.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/gel_dropper_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/gel_dropper_grey.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/gel_dropper_red.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/gel_dropper_water.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/gel_dropper_white.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vtf"
[INFO] vbsp.make_packlist(): "materials/paintblob.vmt"
[INFO] vbsp.make_packlist(): "materials/paintblobs/blob_surface_grey.vtf"
[INFO] vbsp.make_packlist(): "materials/paintblobs/blob_surface_purple.vtf"
[INFO] vbsp.make_packlist(): "materials/paintblobs/blob_surface_stick.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/walkway_destroyed_64a.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/metal_box_rusty.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/gel_dropper.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/wrecked_dropper_128.mdl"
[INFO] vbsp.make_packlist(): "particles/paint_bomb_fx_reflect.pcf"
[INFO] vbsp.make_packlist(): "particles/paint_splats_fx_reflect.pcf"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "D:\Program Files\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/Program Files/steamapps/common/Portal 2/portal2/" "D:/Program Files/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)


[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files/steamapps/common/Portal 2/portal2/puzzles\76561198272909099\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files/steamapps/common/Portal 2/portal2/puzzles\76561198272909099\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files/steamapps/common/Portal 2/portal2/puzzles\76561198272909099\autosave.p2c
Connection to Steam servers lost.
CClientSteamContext OnSteamServersDisconnected logged on = 0
   VAC secure mode is activated.
CClientSteamContext OnSteamServersConnected logged on = 1

**Comment by Luke18033** [comment]
I don't know what the problem is. But if you have an issue related to items or styles, put it on the [BEE2-items repository](github.com/BEEmod/BEE2-items).

**Comment by BenVlodgi** [comment]
can you upload your puzzle that you're trying to build
and what palette and style you're using

_sidenote: maybe exporting those for bug reports should be a featured button_

**Comment by TeamSpen210** [comment]
Problem is it's difficult to actually know what P2C is being compiled.

**Comment by PandaVoxel** [comment]
@BenVlodgi When you say upload, do you want an image of the chamber and the palette?

**Comment by PandaVoxel** [comment]
Hmmm... I'm going to try reinstalling Portal 2 after reading issue #403

**Comment by PandaVoxel** [comment]
Nope. didn't work. Does anyone know how to fix this?

**Comment by PandaVoxel** [comment]
Some extra info:
-This is my first time I have ever installed BEE
-Ever since I installed it, Portal 2, Rexaura, and other source games/mods have been crashing
-Every time I try to compile, it seems to be a vbsp fail
-The crashes mentioned above seem to happen whenever I enter gameplay (Community Maps, Single-player, etc.)

Hope this helps

**Comment by Luke18033** [comment]
> Portal 2, Rexaura, and other source games/mods have been crashing

BEE2.4 shouldn't even be affecting Rexaura (even though it has items from it). If you have this problem, then something is wrong with those games that has nothing to do with BEE2. Try reinstalling them. Just don't forget to back up your maps first!

**Comment by LautaroL20** [comment]
>  The crashes mentioned above seem to happen whenever I enter gameplay (Community Maps, Single-player, etc.)

Then you must be using a Potato PC, simple as that.

**Comment by Luke18033** [comment]
@LautaroL20 I don't think he's using a Potato PC...

**Comment by BenVlodgi** [comment]
@TeamSpen210 they could choose from their list of puzzles I suppose

**Comment by BenVlodgi** [comment]
@TeamSpen210 does bee2 change the vbsp on every export?
just wondering how a reinstalled portal 2 might affect this

**Comment by TeamSpen210** [comment]
On every export, the BEE2 redoes anything that involves modifying existing files (that would be affected by a cache verification). The major problem with uninstalling is that it deletes all your saved puzzles - you need to backup `portal 2/portal2/puzzles/`.

**Comment by PandaVoxel** [comment]
@TeamSpen210 I don't really have any puzzles to backup. The problem is that no matter what I do, I can't build a puzzle while using BEE. Now Portal 2 is crashing when I hit the Build button. You might be right about Rexaura, but I've always been able to use Portal 2 succesfully.

**Comment by PandaVoxel** [comment]
Reinstalling Portal 2 didn't help at all (and yes I have verified the files.)

**Comment by Luke18033** [comment]
I noticed at the end of the log "VAC secure mode is activated." Do you have a VAC Ban? Because that might be interfering with BEE2 somehow.

**Comment by LautaroL20** [comment]
"VAC secure mode is activated." Do you have a VAC Ban? > 

Lol, it looks like our buddy probably got Vac Banned and that's probably the real cause of their issues. You guys were treating this like a conflict files with the game folder, but the problem is slightly different....

**Comment by TeamSpen210** [comment]
No, that shows up normally, it's a red herring.

**Comment by TheDarkBomber** [comment]
Try posting the log again with `developer 3` enabled.

**Comment by LautaroL20** [comment]
As usual with these issues, no response from the author... I'm going to close this until we get a response.
