### ISSUE TITLE
Custom Styles

### ISSUE THREAD

**Issue by JOProsper** [BEEmod/BEE2.4#458]
# Custom Styles

I've looked if this has been posted before, and it seems it hasn't so here I go.
Basically what this means is if you're using perhaps the Overgrown style and you want certain items to come from Behind the Scenes while still keeping some Overgrown items, that way you can mix styles in any way you want. This could also mean that you can use the flamethrower from the 60's Old Aperture in any chamber now. What I'm saying is that we should be able to mix and match different eras into one chamber.

**Comment by Byzarru** [comment]
This is has been discussed in various incarnations on the items repository ([this is the latest example I can think of](https://github.com/BEEmod/BEE2-items/issues/1223), but there are indeed more if you look around).

**Comment by TeamSpen210** [comment]
This wouldn't work well, lots of items are made specifically to work with their style, and wouldn't work (for example Old Aperture Observation Grates). You'd also get lots of inconsistencies, with wall textures and whatnot.
