### ISSUE TITLE
Updating an already published map creates a new wokshop map instead of updating the original publish.

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#459]
I've had this problem multiple times and even fixed it by removing the bin folder in portal2 folder and verifying the files only for it to mess up again. Please look into this, it's a major issue

**Comment by LautaroL20** [comment]
Title is wrong, it should be: "Updating an already published map creates a new wokshop map instead of updating the original publish."

**Comment by Konclan** [comment]
Well I didn't want to confuse people because to update a map you 'publish' it, which I think is stupid valve didn't change it from publish to update.

**Comment by Luke18033** [comment]
This shouldn't be related to BEE2.4.

**Comment by Konclan** [comment]
Its related to bee2.4 because 2.4 is what created the issue

**Comment by Alfe5** [comment]
I have the same issue. As soon as you install Bee2.4 the publisher breaks, even uninstalling Bee2.4 and re-validating the Portal 2 files doesn't fix it.

**Comment by quat1024** [comment]
I'm sure this isn't related to BEE... I had this problem before I even installed BEEMOD wayyyyy back when, I'm pretty sure.

**Comment by Luke18033** [comment]
I don't have this problem, at least not with Aperture Tag. (I've never tried updating a BEE2 map in Portal 2, only Aperture Tag.)

**Comment by Luke18033** [comment]
Either way, BEE2.4 shouldn't be changing how maps get published. (Isn't that hard-coded anyway?)

**Comment by Luke18033** [comment]
Yep, this is a Valve bug. See [here](http://steamcommunity.com/sharedfiles/filedetails/?id=142353952) to fix it.
