### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by Anomaly-Detected** [BEEmod/BEE2.4#462]
Basically, i downloaded the bee2 and set it to my desktop. I created a theme and exported it via the Bee2.exe, and started the game. Whenever I try to test it, it pops up with a building error. I then verified the files, and then tried again. It turns out the editor had the same textures as the overgrown theme, but no items from it. I then tested, and it worked, but the textures were regular portal 2. Basically, the building error is with that new version, Pre 23. I will grab some console things if you need it.

**Comment by Luke18033** [comment]
Oh, I think I know what the problem is. You're using Overgrown, right? If so, select exit corridor 3. That should fix your problem.

**Comment by Luke18033** [comment]
As usual with these issues, no response from the author... I'm going to close this until we get a response.
