### ISSUE TITLE
"Restart when Reaching Exit" and "Pellets Destroy Cubes" stylevars in wrong section

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#463]
They are in "selected style" even though they are available on all styles.

**Comment by TeamSpen210** [comment]
I've fixed this in dev builds.

**Comment by Luke18033** [comment]
Actually now that I look more closely, Restart when Reaching Exit isn't available on Old Aperture or BTS styles. Is this also fixed?
