### ISSUE TITLE
BEE2.4 sometimes bugging on launch

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#464]
I have been using the items development version for quite some time now. But just after syncing the latest version, BEE2 will no longer work. After loading, only the log window will appear. The BEE2.4 window is open, but minimized, and cannot be un-minimized. Here was a screenshot I managed to get of the preview popup:
![beemod2point4](https://cloud.githubusercontent.com/assets/19228201/21618797/8e8de9a8-d1a1-11e6-9264-d53d61f69753.png)
BEEMOD Palette appears to be selected, but that was *not* the last palette I used or exported.

Btw. I have opened the issue here even though I am using the items development version since it is an issue with the program itself.

EDIT: I've been unable to figure out what causes this, although deleting the config folder temporarily fixes the problem. Additionally, the palette shown in the image isn't the BEEMOD palette - notice the Cube Coloriser and Half Panel at the end of the palette.

EDIT 2: Specifically, deleting the `config.cfg` file fixes the problem.

EDIT 3: Even more specifically, deleting the Window State section will make BEE2 work again.

**Comment by TheDarkBomber** [comment]
This isn't a Development Version issue. It's a bug with any version.

**Comment by TheDarkBomber** [comment]
And not a crash.

**Comment by TeamSpen210** [comment]
Does returning to normal packages fix the problem? Check `BEE2/logs/BEE2.log`, there might be something at the end.

**Comment by Luke18033** [comment]
I don't see anything unusual...

**Comment by Luke18033** [comment]
And I get this same issue even with the default packages. Which is strange, since I've been able to use Pr23 fine before.

**Comment by Luke18033** [comment]
I looked through the log more, and found this:
```
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "BEE2.pyw", line 132, in <module>
  File "F:\Git\BEE2.4\src\UI.py", line 582, in load_packages
  File "F:\Git\BEE2.4\src\selectorWin.py", line 444, in __init__
IndexError: list index out of range
```

**Comment by Luke18033** [comment]
After deleting my `palettes` and `config` folders, and then fixing a few errors that came up because I deleted those, BEE2 will launch again.

**Comment by Luke18033** [comment]
Can you figure out what's causing this and fix it? I'm tired of re-configuring everything every 4-5 times I use BEE2.

**Comment by Luke18033** [comment]
Updated original post.

**Comment by TeamSpen210** [comment]
This implies that a lot of package data is missing, and that one of the windows is entirely empty. That would point to an incorrect folder or something, perhaps the elevator videos being missing?

**Comment by Luke18033** [comment]
Have you figured out what's causing this yet? It's still happening, even in the release version or Pr24.

**Comment by Luke18033** [comment]
It's not an issue with my computer either - it happens on both of my computers, only one of which is using the dev version.

**Comment by TeamSpen210** [comment]
When did you do the 3rd edit? That explains it - the windows might be appearing offscreen, or something like that.

**Comment by Luke18033** [comment]
"About 1 month ago", if I haven't edited it since I added that. "Keep windows inside screen" is off, so how could that be the problem?

**Comment by TeamSpen210** [comment]
You need to check that to enable the logic which forces them inside the screen.

**Comment by LautaroL20** [comment]
Wasn´t this fixed yet?

**Comment by TeamSpen210** [comment]
I think it should be.
