### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2.4#465]
I have some suggestions.

1. cool light strip.
2. combine all light strips (like square lights).
3. Tractor beam picture half blue and half orange.
4. deadly goo and deadly pit separate items and combine them (place deadly goo and have it not turn into a pit).
5. combine reflection gel with the other gels.
6. combine compressed smoke field, force deflection field, and matter inquisition field.
7. combine death fizzler with fizzler and laser field.
8. combine all unstationary scaffold items.
9. combine laser catcher and laser relay.
10. combine turret and rocket turret.
11. make ditch picture not sphere button picture.
12. add spinney blade wall/floor.
13. make cooperative spawn room picture not a cube dropper.
14. make able to move square lights around on the surface its on like light strips.

**Comment by Luke18033** [comment]
Issues about items, like this one, should go on [BEE2-items repository](https://github.com/BEEmod/BEE2-items).
