### ISSUE TITLE
BEE2.4 Doesn't execute in MAC OSX

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#466]
Moved from BEEmod/BEE2-items#1334

From @Kenkenkon:

I put all the packages inside BEE2 Folder, but when I run the application, a console message appears, saying that there's an image missing.

**Comment by TeamSpen210** [comment]
You need to install Python 3.4 for it to work - I'm not quite sure how to correctly get OS X to just load it from the folder the app's in....

**Comment by Luke18033** [comment]
Why isn't that in the README then?

**Comment by Kenkenkon** [comment]
(From #1334) "Could you upload a screen showing the full bug message? It would be helpful to identify the cause." - LautaroL20

![screen shot 2017-01-05 at 7 32 50 pm](https://cloud.githubusercontent.com/assets/21965054/21698397/f01c591a-d37d-11e6-8759-6724c7e2d771.png)

**Comment by Kenkenkon** [comment]
I got Phython 3.4, but what now? When I execute BEE2 it appears the same thing

**Comment by TeamSpen210** [comment]
Check the bin folder, there should be a copy of that libintl file, copy it to the path referenced there.

**Comment by dunkler-schatten** [comment]
> copy of that libintl file, copy it to the path referenced there.
No. this solve not the Problem. :-/ 
The mac have no path like this /opt/local/lib
He say  "does not exist"
My Error:

Last login: Wed Jan 18 12:24:08 on ttys000
Carstens-Mac-mini:~ xxxx$ /Users/xxxx/Downloads/BEE2.4_pr23_mac/bin/BEE2 ; exit;
dyld: **Library not loaded: /opt/local/lib/libintl.8.dylib**
  Referenced from: /Users/xxxxx/Downloads/BEE2.4_pr23_mac/bin/BEE2
  Reason: **image not found**
**Abort trap: 6**
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Prozess beendet]

**Comment by MeepJJ** [comment]
I got "abort trap 6" when executing after installing Python 3.4 as well. When if at all is there going to be a patch or newer version that patches this error?

**Comment by LautaroL20** [comment]
Mac support is no longer in the works, if you want to keep using BEE2.4 you will have to migrate to Windows 7-10.
