### ISSUE TITLE
Item Configuration Pane

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#467]
I originally suggested this on BEEmod/BEE2-items#547, where it could be used to select more exact values for the neurotoxin timer.

Certain items, such as the Neurotoxin Timer (BEEmod/BEE2-items#547), Customizable Test Chamber Sign (BEEmod/BEE2-items#605), or Contraption Cube (BEEmod/BEE2-items#850) would have a timer property, which would allow selecting different "configurations" for the item. Each configuration would contain data for a set of properties, which couldn't be adjusted through the editor.

The window itself would allow adding up to 28 different configurations for each item that supported them. These configurations could be selected in-game using the timer property on items which supported it. This would allow items to have many properties, or properties not possible in PeTi, such as sliders or text boxes. This would also work like the compile pane, as changing configurations would instantly apply without having to re-export.

The only minor problem with this is that it would only be possible to have 28 configurations per item. This is only a minor problem though, as players are unlikely to need more than 28 of these same items each with different configurations.

Configurations could also possibly be saved with the selected palette.

-----

Update: The ICP is in BEE2 now. As well as having the configurations feature, item-related stylevars (or "itemvars") appear here as well. It's combined with Style Properties, as opposed to being it's own window.

**Comment by Byzarru** [comment]
Could a system like this be used to create custom textures for a theoretical "Custom Overlay" item? (Like if you wanted to add your own posters to BTS, make hints or make custom Rattman dens)

**Comment by Luke18033** [comment]
Maybe. I don't think that will be implemented though. It's been requested several times, but the issue always ends up getting closed.

**Comment by TheDarkBomber** [comment]
This may need to be `long-term`, as it is a pretty big feature.

**Comment by Luke18033** [comment]
@TheDarkBomber I was going to add that, but it seems like somebody deleted it...

**Comment by TheDarkBomber** [comment]
Still needs the `New Feature` label.

**Comment by TeamSpen210** [comment]
![image](https://cloud.githubusercontent.com/assets/8453732/23111397/1a9dbdd6-f774-11e6-8e25-39f8e9ba221d.png)

**Comment by Luke18033** [comment]
One question. Where's the timer-value option? The ICP isn't nearly as useful without it...

**Comment by Luke18033** [comment]
Especially with the Cube Coloriser.

**Comment by TeamSpen210** [comment]
That's why there's 28 of the colour swatches, those correspond to the timer values. (They have a tooltip giving the colour value). I banned Colorisers from using the infinite value, but that would appear at the start.
