### ISSUE TITLE
Help me plz

### ISSUE THREAD

**Issue by Nikita74russ607** [BEEmod/BEE2.4#468]
# Im selecting style and items. _compiling my map. and error appears please help me!_

**Comment by TheDarkBomber** [comment]
Log???

**Comment by Nikita74russ607** [comment]
No logs!

**Comment by Nikita74russ607** [comment]
dont make stupid words here!

**Comment by Nikita74russ607** [comment]
- [ ] Help me

- [ ] Stop this problem

**Comment by Nikita74russ607** [comment]
1.  Help me

2. Stop this problem

**Comment by TheDarkBomber** [comment]
Check the log in the developer console. :man_facepalming:

**Comment by LautaroL20** [comment]
@Nikita74russ607 - Wich style did you use to compile the map?

**Comment by Luke18033** [comment]
> don't make stupid words here

@Nikita74russ607 What?

**Comment by TheDarkBomber** [comment]
@Luke18033 Words like logishdusjiiy, and ahbuahyahhya.

**Comment by Luke18033** [comment]
Nobody wrote that...

**Comment by TheDarkBomber** [comment]
That was a joke.

**Comment by Luke18033** [comment]
As usual with these issues no response from the author. I'm going to close this until we get a response.

**Comment by TheDarkBomber** [comment]
See #483
