### ISSUE TITLE
Default palette configurations for mods

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2.4#470]
This is for reference.
* [x] ### Aperture Tag ###
- Both Gels activator
- Blue Gel activator
- Orange Gel activator
- Gel deactivator
- Pedestal button
- Floor buttons
- Cubes
- Gels
- Excursion Funnel
- Aerial Faith Plate
- Crusher
- Stairs
- Fizzler/Laserfield
- Hard Light Bridge
- Piston platform
- Track platform
- Thermal Discouragement Beam
- Laser Catcher
- Laser Relay
- Glass/Grating
- Angled Glass
- Angled Panel
- Flip Panel
- Small Observation Room
- Goo
- Turret
- Door
- Light
- Trigger Output
- Logic Gate
- Orange Portal
- Blue Portal

* [ ] ### Thinking With Time Machine ###
Same as BEEMOD except Gels are replaced with Cleansing Gel.

**Comment by Luke18033** [comment]
Don't forget that Autoportals are unavailable in TWTM.

**Comment by Byzarru** [comment]
What are they replaced with? (Surface markers?)

**Comment by Luke18033** [comment]
Nothing, it's just a blank spot on the palette.

**Comment by TeamSpen210** [comment]
I should add these palettes, except that the 4 gel fizzler items are combined... I'll replace one with the Paint Fizzler, but what should the other two be? (The way the editor is implemented doesn't allow having holes in the palette, even though the actual editor does.)

**Comment by Byzarru** [comment]
I suggested the curved ramp item, so that could be a possibility. For the other two, the Paint Fizzler and the  Death Fizzler. TWTM should include surface markers.

**Comment by TeamSpen210** [comment]
I actually just added the original BEE1 items that weren't included it in the list.

**Comment by Luke18033** [comment]
Adding the TWTM palette isn't really necessary, you just choose BEE1 palette and remove Autoportals.

**Comment by TheDarkBomber** [comment]
Delete palettes?
