### ISSUE TITLE
Signage above Laser Catcher Crashes Portal 2

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2.4#471]
I was using the original clean theme developing a chamber when this error happened. I have provided below a link to a gif of what happened.

 http://imgur.com/a/RSqab 

Hopefully you can pinpoint the issue and fix it in a future update.

**Comment by Konclan** [comment]
It's because you broke the minigun *doot*

**Comment by Byzarru** [comment]
Ooh, what are those triggers by the doors? They look fascinating.

Related: I have had a similar issue. The game won't crash for me, the signage just won't render.

**Comment by TeamSpen210** [comment]
That's a Valve bug. Antlines will crash the editor if it's blocked inside the same block as the item it comes from.

**Comment by Byzarru** [comment]
Aha, because I didn't have antlines.

**Comment by TeamSpen210** [comment]
Actually submit this to Valve, you can do it with a light strip too.
