### ISSUE TITLE
Puzzle Backup Feature

### ISSUE THREAD

**Issue by BenVlodgi** [BEEmod/BEE2.4#472]
- 1-click backup all puzzles
- show list of backup states
- allow users to restore a backup state

**Comment by TheDarkBomber** [comment]
Doesn't that already exist?

**Comment by BenVlodgi** [comment]
No clue :)

**Comment by TheDarkBomber** [comment]
It does.

**Comment by TeamSpen210** [comment]
File -> backup puzzles.
