### ISSUE TITLE
Overgrown Not working

### ISSUE THREAD

**Issue by PortalTurret** [BEEmod/BEE2.4#477]
Every time i set the style to Overgrouwn and test it [even if its empty] it says "there was a Error when building the puzzle"
 even tho there was no Error,
Plz help me 
![20170114163020_2](https://cloud.githubusercontent.com/assets/25120793/21956011/f313278e-da76-11e6-8383-f6242395722a.jpg)

**Comment by TheDarkBomber** [comment]
Try Corridor No. 3

**Comment by Luke18033** [comment]
Use exit corridor 3, and you won't have this problem. Note though that there is currently another bug where the exit door won't close. This has been fixed for the next release. Until then, just place the Door item in front of the actual door.

**Comment by Luke18033** [comment]
Additionally, put issues about items and styles on the [BEE2-items repository](https://github.com/BEEmod/BEE2-items).

**Comment by PortalTurret** [comment]
okay im gonna try

**Comment by PortalTurret** [comment]
Thank you it worked

**Comment by ReikaKalseki** [comment]
I am getting this error as well, and using exit number three does **not** fix it.

**Comment by Luke18033** [comment]
That's strange, since this big was fixed in Pr24...

**Comment by ReikaKalseki** [comment]
I just tested; it happens with *every* non-clean style, too.

**Comment by Luke18033** [comment]
Remove Portal 2 from the BEE2 game list. Delete the `bin` folder in Portal 2's files, and then validate the game files. That should fix the problem.

**Comment by ReikaKalseki** [comment]
I already tried that.

**Comment by Luke18033** [comment]
I don't know what your problem is then, that fixed it for everyone else. Although the fact that it doesn't affect Clean means this is probably a different bug. Paste the console log.

**Comment by ReikaKalseki** [comment]
The console log said it was missing the exit room, but at this point it is not necessary; after an (unplanned) computer reboot, it is working.

**Comment by TeamSpen210** [comment]
That error means there's a mismatch between the editor item configuration and what the compiler expects.

**Comment by ReikaKalseki** [comment]
I do not know enough about Portal 2's internals to hypothesize on why that started happening, or why despite multiple game reloads only a computer reboot (a crash, no less) fixed it.
