### ISSUE TITLE
Suggestion: add music trigger to swap out music mid chamber.

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2.4#478]
I feel like a lot of portal 2 music is situational and doesn't fit for the entire chamber. I believe a lot of map creators would love it of there were a simple music trigger to change the music. However, you should probably flesh out music bugs first before implementing it.

**Comment by TheDarkBomber** [comment]
This should go on the BEE2-items repository.

**Comment by Alfe5** [comment]
sorry. could you move it for me? I barely know how to post as is =P

**Comment by TheDarkBomber** [comment]
Just copy the issue onto the BEE2-items repository.

**Comment by Alfe5** [comment]
link?

**Comment by TheDarkBomber** [comment]
[BEE2-items repository](https://github.com/BEEmod/BEE2-items/issues)

**Comment by LautaroL20** [comment]
This is something that would fit well only on the original PeTi tracks thouhg.

 Moved to: https://github.com/BEEmod/BEE2-items/issues/1400
