### ISSUE TITLE
Cannot Compile Test Chambers

### ISSUE THREAD

**Issue by Helloburp** [BEEmod/BEE2.4#479]
I've installed BEEmod as specified for Windows 10, but I get an error after the map compiles geometry.

It's worth noting that when exporting styles from the executable file that it displays that it has "Skipped!" exporting Resources and Music.

It's also worth noting that when the game finishes loading up the display view of PETI, it says that it fails to load models associated with the items on the selection menu.

Anyways, here is the console output that was highlighted in red.

I'll try to respond ASAP to any requests for further information if necessary.

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 44 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN', 'bottomless_pit': '0'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] BEE2_config.load(): Config "C:\Users	hebo\Desktop\BEE2.4_pr23_win\config/compile.cfg" not found! Using defaults...
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Using random SP Exit (1)
[INFO] vbsp.mod_entryexit(): Using random SP Entry (7)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_1"
 | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_2"
 | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Cave Reactions"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 |_

[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2842, misses=284, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'unlockdefault': False, 'rexcubepelletfizzle': False, 'fixfizzlerbump': False, 'allowgoomist': True, 'restartonexit': True, 'bee_show_trigger': False, 'nomidvoices': False, 'doorcameras': True, 'multiversecave': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 408 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (0)
 | writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
 | done (0)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (1) (452279 bytes)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Compacting texture/material tables...
 | Reduced 2645 texinfos to 462
 | Reduced 53 texdatas to 48 (1495 bytes to 1353)
 | Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
 | 
 | nummapplanes:     (  8558 / 65536 )
 | nummapbrushes:    (  1229 /  8192 )
 | nummapbrushsides: ( 10672 / 65536 )
 | num_map_overlays: (     2 /   512 )
 | nummodels:        (    31 /  1024 )
 | num_entities:     (   281 / 16384 )
 | 
 | 2 seconds elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (75030000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 76F6C8B0
 | CDynamicFunction: Closing library 'Kernel32.dll' (75030000)
 |_

[INFO] vbsp.run_vbsp(): VBSP Done!
[INFO] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('1229', '8192'), 'entity': ('281', '16384'), 'overlay': ('2', '512')}
[INFO] BEE2_config.save(): Saving changes in config "C:\Users	hebo\Desktop\BEE2.4_pr23_win\config/compile.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3642, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3400, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3461, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 270, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 261, in make_tempfile
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 237, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\thebo'
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3642, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3400, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3461, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 270, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 261, in make_tempfile
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 227, in makedirs
  File "c:\python\32-bit\3.4\lib\os.py", line 237, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\thebo'

**Comment by TheDarkBomber** [comment]
It's a problem with your user folder. (`C:\Users\thebo`)

**Comment by Helloburp** [comment]
What should I change? The user folder is normally 10 characters long. Why would this application take only a 5 character substring?

**Comment by TheDarkBomber** [comment]
It's a problem with Python itself, so this should be labelled `python-bug`

**Comment by Helloburp** [comment]
Do you think there is any way I can fix this?

**Comment by TheDarkBomber** [comment]
Yes.

**Comment by Helloburp** [comment]
Yes to the former or latter?

**Comment by TheDarkBomber** [comment]
>Do you think there is any way I can fix this?

>Yes.

**Comment by Helloburp** [comment]
Any ideas? Can I change my current user name without disturbing any other programs?

Either way, this is strange, normally other people would have users longer than 5 characters.

**Comment by TheDarkBomber** [comment]
Do you have a user named `thebo` on your computer?

**Comment by Helloburp** [comment]
The user should be TheBossCDA, but I'm going through my files and checking it now, and it seems like thebo is what it's being referred to as.

I have the beemod folder stored on my desktop, by the way.

**Comment by TheDarkBomber** [comment]
So, your folder is `thebo` but your user is `TheBossCDA`?

**Comment by Helloburp** [comment]
How can I check? This is the only user I really use.

**Comment by TheDarkBomber** [comment]
Just go to `C:\Users`

**Comment by Helloburp** [comment]
Ok, thebo is a user.

**Comment by TheDarkBomber** [comment]
So, the user folder doesn't match the actual user, so just change the folder name `thebo` to `TheBossCDA`.

Or just use BEE2.4 outside your user folder.

**Comment by Helloburp** [comment]
Wait, but the console doesn't reference TheBossCDA, right? I was just mistaken that TheBossCDA was a user

**Comment by TheDarkBomber** [comment]
No, it's referencing the incorrectly matched folder, `thebo`.

**Comment by Helloburp** [comment]
But it's not incorrectly matched, is it?

That's the only and default user, I don't think it could be mismatched. What console excerpt states this?

I'm not distrusting you, I'm just wondering how this works

**Comment by TheDarkBomber** [comment]
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\Users\thebo'

**Comment by Helloburp** [comment]
Will I need to reinstall beemod?

And what other excerpt states that TheBossCDA is the correct user? This is all just confusing to me

**Comment by TheDarkBomber** [comment]
Try reinstalling it outside the user folder. (like in a new folder called `C:\BEEmod`)

**Comment by Helloburp** [comment]
Alright. I'll report back to you. Sorry for keeping you up so late, it's about 4 AM where I live

**Comment by TheDarkBomber** [comment]
What do you mean? It's 9:43 AM where I live.

**Comment by Helloburp** [comment]
Timezones are lots of fun

**Comment by TheDarkBomber** [comment]
What about the Global Time Zone? (UTC)

**Comment by Helloburp** [comment]
If only there was a universal timezone put in place...

Anyways, worked like a charm. Thanks for the help.

One final question though. How do I close this issue?

**Comment by TheDarkBomber** [comment]
Press the `Close Issue` button
