### ISSUE TITLE
Can't move anything from/to palette.

### ISSUE THREAD

**Issue by prrg** [BEEmod/BEE2.4#480]
If I use my cursor to move anything from/to the item palette the program crashes and it gives this error:

`  File "/home/prrg/git/BEE2.4/src/UI.py", line 1027, in drag_move
    drag_win.configure(cursor=utils.CURSORS['destroy_item'])
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1333, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1324, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad cursor spec "x_cursor" `

Using latest dev version.

**Comment by LautaroL20** [comment]
I don´t have this problem. What O.S are you using?

**Comment by Luke18033** [comment]
Linux, I think (see #476).

**Comment by LautaroL20** [comment]
Well.............Thats clearly the issue, then. Beemod isn´t compatible with Linux since Spencer doesn´t have a Linux computer to port Beemod to that O.S.

**Comment by prrg** [comment]
Found the easy way out: Shift-clicking does not crash the program, so the problem is specifically with dragging. Though, like Lautaro said, @TeamSpen210 does not have a Linux computer, so I don't expect a fix anytime soon.

Time to break my shift key.

**Comment by TheDarkBomber** [comment]
@prrg If you break your shift key, you wouldn't be able to use it.

**Comment by LautaroL20** [comment]
@TheDarkBomber - Heh, the comedian has come back again... lol

**Comment by TheDarkBomber** [comment]
I wasn't making a joke. I guess you have a really **sens**itive **sense** of humour! HA!

**Comment by LautaroL20** [comment]
When prrg said "Time to break my shift key" he wasn´t mean that literally. So, i guess you have to buy a sarcasm detector:

![Sarcasm Detector](https://cloud.githubusercontent.com/assets/12244376/21965370/49c10c74-db3d-11e6-8163-7ce3eae6b296.png)

**Comment by TheDarkBomber** [comment]
My sarcasm detector says that you are being sarcastic.

**Comment by TeamSpen210** [comment]
I'd want it to be fully compatible.

**Comment by TeamSpen210** [comment]
The problem here is specifically that the app is using an invalid name for the cursor type. These differ on different platforms, I just need to know what it's called on Linux.

**Comment by TeamSpen210** [comment]
This should now be fixed, @prrg can you confirm?

**Comment by prrg** [comment]
Same error. Same line at same file too.

**Comment by TeamSpen210** [comment]
Update your src/ folder. (You should probably git clone it, so you can update in future.)

**Comment by prrg** [comment]
I did update it, ofc.

Though testing now, moving anything to the palette works now, only moving from the palette that returns error.

**Comment by Luke18033** [comment]
@prrg - Strange, moving to the palette and from the palette should be using the same cursor, @TeamSpen210 must have only changed one of them.

**Comment by TeamSpen210** [comment]
They have a different cursor, moving from the item list gives a 'no' icon until you reach the palette, moving off the palette gives a 'X' to indicate you're deleting them.
