### ISSUE TITLE
Linux-dev: VBSP (and possibly VRAD) do not build new maps

### ISSUE THREAD

**Issue by prrg** [BEEmod/BEE2.4#482]
Might as well create a separate thread for this (instead of putting a new issue on top of #480 or the already bloated #476 ) since there is a Linux tab now.

Probably the biggest issue atm 'cause it makes the editor unusable. Items and palette all work fine but compiling always fails even with the default test chamber without adding anything. Developer terminal gives out this error:

```
VBSP failed.

ERROR: ld.so: object '/home/prrg/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Current thread 0x00007f126ccaf740 (most recent call first):
```

Seems to be a problem with the compiler not finding Python dependencies. You would think other BEE2 parts would suffer in that case though.

rip vbsp

**Comment by TeamSpen210** [comment]
To revert, go to your Portal 2 directory, and replace `vrad`/`vbsp` with their `_original` versions.

**Comment by prrg** [comment]
Replacing the vrad/vbsp causes graphical glitches btw. To revert the changes you need to validate game cache.

**Comment by prrg** [comment]
Ok, so in my attempts to fix this problem, I decided to build compile_vbsp_vrad.py again and found this:

```
Missing modules:
? _dummy_threading imported from dummy_threading
? _frozen_importlib imported from importlib, importlib.abc
? _frozen_importlib_external imported from importlib, importlib._bootstrap, importlib.abc
? _sha1 imported from hashlib
? _winapi imported from subprocess
? argparse imported from inspect, pickle, tarfile, tokenize
? bz2 imported from encodings.bz2_codec, shutil, tarfile, zipfile
? ce imported from os
? dis imported from inspect
? doctest imported from heapq, pickle
? email.message imported from logging.handlers
? email.utils imported from logging.handlers
? gettext imported from getopt, utils
? grp imported from shutil, tarfile
? http.client imported from logging.handlers
? locale imported from _pydecimal, _strptime, calendar, utils
? lzma imported from shutil, tarfile, zipfile
? msvcrt imported from subprocess
? nt imported from ntpath, os, shutil
? optparse imported from calendar
? org.python.core imported from copy, pickle
? os.path imported from BEE2_config, os, py_compile, utils, vbsp, vrad_linux__main__
? pkgutil imported from conditions
? pprint imported from pickle
? pwd imported from posixpath, shutil, tarfile
? smtplib imported from logging.handlers
? textwrap imported from zipfile
? win32evtlog imported from logging.handlers
? win32evtlogutil imported from logging.handlers
This is not necessarily a problem - the modules may not be needed on this platform.
```

This is not really new and confirmed intended but there are 2 modules here which called my attention:

`? bz2 imported from encodings.bz2_codec, shutil, tarfile, zipfile`

`? dis imported from inspect`

bz2 imported from "**encodings**.bs2_codec". "encodings" is exactly what is missing here though. dis is also pretty suspicious since running vbsp_linux on terminal gives out this error:

`ImportError: No module named 'dis'`

Interesting stuff. Any opinions?

**Comment by TeamSpen210** [comment]
I've done some investigation of my own (I've got a VM worki

**Comment by prrg** [comment]
```
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
    __import__(name + "__init__")
  File "/usr/local/lib/python3.5/dist-packages/cx_Freeze/initscripts/Console.py", line 24, in <module>
    exec(code, m.__dict__)
  File "vbsp_launch.py", line 5, in <module>
  File "/home/prrg/git/BEE2.4/src/vbsp.py", line 20, in <module>
    import voiceLine
  File "/home/prrg/git/BEE2.4/src/voiceLine.py", line 8, in <module>
    import conditions.monitor
  File "/home/prrg/git/BEE2.4/src/conditions/__init__.py", line 5, in <module>
    import inspect
  File "/usr/lib/python3.5/inspect.py", line 35, in <module>
    import dis
ImportError: No module named 'dis'
```

> (I've got a VM working now)

Nice

> it's actually a bigger issue with cx_freeze and the default Python on Ubuntu.

aw shit

**Comment by TeamSpen210** [comment]
Open up `compile_vbsp_vrad.py`, and remove `'dis'` from the exclusion list there.

**Comment by prrg** [comment]
After removing dis from the exclusion list it launches fine on terminal. Still, expectedly, not working in-game though.

**Comment by petersohn** [comment]
I have the same error. It seems to be related to #517. That one is about the BEE2 GUI itself not working, but I have this problem on Linux too.

Also, I'm working on a workaround to make the compiler work without cx_Freeze (the GUI works out of the box), but that has its own issues. See #530.
