### ISSUE TITLE
Change Puzzlemaker Music

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#485]
Puzzlemaker music gets old, maybe add different music for different styles or allow the user to choose music.

**Comment by Luke18033** [comment]
What do you mean by this? You can already choose music from the Export Options pane.

**Comment by TeamSpen210** [comment]
In the editor itself.

**Comment by Luke18033** [comment]
It's not possible to add a music changer to the editor. It could be made into an item, but then the amount of tracks you could have would be limited.

**Comment by TeamSpen210** [comment]
This would be done in the BEE2 application itself, it'd let you set music for while you're editing maps. This might be doable, I'm not sure.

**Comment by Luke18033** [comment]
Ah, I get it.

**Comment by Konclan** [comment]
I had no idea if this was do-able and may be a waste of time but it could be a nice touch.

**Comment by TeamSpen210** [comment]
@Luke18033, this is the in-editor music (the 'bloop' sounds), not the ingame music.

**Comment by Luke18033** [comment]
Oh, I get it. This would be useful, maybe somebody could even make "editor versions" of all the music tracks, like in Super Mario Maker.

**Comment by Luke18033** [comment]
Not sure if this is possible, IIRC the puzzlemaker ambient noises aren't just a single looping sound, they're a bunch of separate sounds which play at random. And some also play in response to placing items.

**Comment by Luke18033** [comment]
Okay, I just checked and it looks like there is actually a single `P2Editor.BlipLoop` sound event which plays the main loop and also controls the random blips added on top. So we could easily change that to just play a single looping music track instead. That leaves the sounds when placing and deleting items, which we'd just remove. ~Or do what Mario Maker does and have a distorted voice say the name of the item being placed.~

Of course, this still leaves the problem of us not actually having any editor versions of the music to use, so someone would need to make those.

**Comment by TPEcool** [comment]
What do you mean editor versions? Is the editor music in some obscure format or something?

**Comment by Luke18033** [comment]
Look up Mario Maker editor music, they have different more ambient versions of the background music used while editing which seamlessly swap to the full tracks when you go to test the level. So the idea is we'd make similar "editor variants" of all the music in BEE, then play those while in the editor if you selected the corresponding in-game music track. The problem stems from the fact that there are like a hundred different songs selectable in BEE currently and *every one of them* would need an editor variant made, which is a lot of work.

Mario Maker also has a distorted voice say the name of objects being placed which matches the pitch of the music. I think that would be doable in P2 (the editor does have sound events triggered when placing objects), but it's kind of annoying and not needed.

**Comment by Luke18033** [comment]
I still think this would be neat to do if someone wanted to make the music
