### ISSUE TITLE
Allow Changing Suggested Settings

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#487]
Sometimes I think it would be nice to allow changing the options selected when clicking "Use Suggested".

**Comment by TheDarkBomber** [comment]
You should change the title, it looks like you are asking for the ability to change what the recommended settings are.

**Comment by Luke18033** [comment]
What should I change it to? I could make it "Allow Changing Suggested Settings" (that's what BEE2 calls it), but what else?
