### ISSUE TITLE
Overgrown Co-op exit didn't appear after compile

### ISSUE THREAD

**Issue by SW50000** [BEEmod/BEE2.4#490]
![20170121000134_1](https://cloud.githubusercontent.com/assets/20195894/22172455/ecfba33a-df6c-11e6-9af9-1694fcc1e4b1.jpg)
It Didn't appear, but the entrance appeared fine

**Comment by TheDarkBomber** [comment]
Issue moved to [BEEmod/BEE2-items #1431](https://github.com/BEEmod/BEE2-items/issues/1431) via [**ZenHub**](https://www.zenhub.com/)

**Comment by TheDarkBomber** [comment]
Moved to BEEmod/BEE2-items#1431.

**Comment by LautaroL20** [comment]
@TheDarkBomber - Do not forget to close the original post after you moved it.

**Comment by TheDarkBomber** [comment]
@LautaroL20 I can't. ZenHub allows moving issues without being a contributor on the repository.

**Comment by LautaroL20** [comment]
Ah, i forgot that haven´t anymore those privilegies.

**Comment by TheDarkBomber** [comment]
I never had those privileges on **this** repository.

**Comment by LautaroL20** [comment]
Well, if you weren´t fiddling things you could have them now, since the creation of the beemod organization wich gave us these.

**Comment by TheDarkBomber** [comment]
I wasn't. _You_ were.

**Comment by LautaroL20** [comment]
Nope, if that were true then i would have been the one who lost them.

**Comment by TheDarkBomber** [comment]
Any questions about ZenHub?

**Comment by Luke18033** [comment]
My question is, "*Why is GitHub okay with a tool that basically lets you HACK REPOSITORIES and move stuff even when you're not a collaborator?*"

**Comment by TeamSpen210** [comment]
It doesn't move anything technically, just automatically creates a new issue and adds comments matching the original.

**Comment by Luke18033** [comment]
Oh yeah, that's why it can't close it.
