### ISSUE TITLE
Overgrown Singleplayer Compile issue

### ISSUE THREAD

**Issue by SW50000** [BEEmod/BEE2.4#491]
[INFO] vbsp.main(): BEE2.4.0pr23 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[WARNING] cond.core.weighted_random(): Invalid weight! ()
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 3
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 7
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (26 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "ITEM_BEE2_FIZZLER_OUT_RELAY" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: RAND
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_ANIMAL_KING"
 | 	"Choreo" "npc/announcer/prehub46.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "EXIT_GEN_TECH_DIFF"
 | 	"Choreo" "ann_apoc/exit_tech_diff.vmf"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/4 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['cube', 'cubestandard', 'cubedropper', 'buttonacceptscube', 'cubedropperstandard', 'cubebutton', 'spawn_dual', 'floorbutton']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3942, misses=307, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'rexcubepelletfizzle': False, 'multiversecave': True, 'nomidvoices': False, 'fixfizzlerbump': False, 'bee_show_trigger': False, 'unlockdefault': False, 'restartonexit': True, 'bee2_goo_debris': True, 'allowgoomist': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/items/cube/cache_box.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_5.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_on.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty_on.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vtf"
[INFO] vbsp.make_packlist(): "materials/bee2/blend_concrete_dirt.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/walkway_destroyed_64a.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/metal_box_rusty.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/wrecked_dropper_128.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_rand.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "D:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: D:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/over/elevator_sp/elevator_exit/exit_stairs.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "D:\Bee2.4PR23\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

And here is the screenshot of what I was compiling:
![20170121000447_1](https://cloud.githubusercontent.com/assets/20195894/22172474/56030468-df6d-11e6-950d-479afe997adc.jpg)

**Comment by TeamSpen210** [comment]
This will be fixed in a few minutes.
