### ISSUE TITLE
Pr 24's connections signs have missing textures/packages

### ISSUE THREAD

**Issue by Alfe5** [BEEmod/BEE2.4#494]
I placed the brand new items into the editor today only to find missing textures for connection signs. I am using the clean test chambers atm. Please look into this as i find this item very helpful.

**Comment by LautaroL20** [comment]
Stuff related to items must be posted into this section: https://github.com/BEEmod/BEE2-items
This issue was moved to: https://github.com/BEEmod/BEE2-items/issues/1437
