### ISSUE TITLE
Warn when VPK files can't export 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#495]
![20170123152714_1](https://cloud.githubusercontent.com/assets/12244376/22218209/a3552188-e184-11e6-83a3-1e57a036f184.jpg)

**Comment by LautaroL20** [comment]
This could happens from time to time also with other Styles as well.

**Comment by TheDarkBomber** [comment]
Are you sure this isn't a BEE2-items issue?

**Comment by TeamSpen210** [comment]
Make sure you don't have Hammer or Portal 2 open when  exporting, they prevent overwriting the VPK files.

**Comment by LautaroL20** [comment]
Well, thats another thing to keep in mind that should be into the "Readme Notes" i guess.

**Comment by LautaroL20** [comment]
I think that this was implemented.
