### ISSUE TITLE
No Mac Version more?

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#496]
Mhm Since there is now no more Mac version, is with me the new Colored cubes wrongly represented.
Well after version 21.5 BeeMod went so synonymous not to start on the Mac.
Will there ever be a Mac Verison again?
Sorry again for my Bad English.
![bildschirmfoto 2017-01-24 um 09 28 33](https://cloud.githubusercontent.com/assets/18405990/22239731/2a589b90-e218-11e6-89f0-b2f5e73af85c.png)

**Comment by TheDarkBomber** [comment]
Needs `Mac` label.

**Comment by ZombiePwner1** [comment]
That's definitely wrong.

**Comment by LautaroL20** [comment]
A new version for Mac could come out with Half-Life 3.

**Comment by alicerunsonfedora** [comment]
The Mac version of BEE2 is rather difficult to build, but it can be run from source, given that some lines are changed and what-not. Experience may vary, though.

**Comment by TeamSpen210** [comment]
Next release will have a Mac version, I've manged to build it.
