### ISSUE TITLE
Beemod is not able to export to Portal 2

### ISSUE THREAD

**Issue by laserman120** [BEEmod/BEE2.4#497]
When i try to export to Portal 2 it is working fine but when it starts copying the Resources it crashes at about 2000 and he only copies 7/8 Compiler.
![bee2 exporting](https://cloud.githubusercontent.com/assets/25353348/22307265/99f94c44-e342-11e6-8ab4-e7064b3e61da.png)
then this message appears:
`Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 844, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 607, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 389, in refresh_cache
  File "F:\Git\BEE2.4\src\utils.py", line 544, in merge_tree
shutil.Error: [('../cache/resources/instances\\50s\\items\\bee', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee'"), ('../cache/resources/instances\\50s\\items\\button', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\button', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\button'"), ('../cache/resources/instances\\50s\\items\\catwalk', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\catwalk', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\catwalk'"), ('../cache/resources/instances\\50s\\items\\cond_plate', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\cond_plate', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\cond_plate'"), ('../cache/resources/instances\\50s\\items\\conveyor', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\conveyor', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\conveyor'"), ('../cache/resources/instances\\50s\\items\\cube', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\cube', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\cube'"), ('../cache/resources/instances\\50s\\items\\death_fizz', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\death_fizz', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\death_fizz'"), ('../cache/resources/instances\\50s\\items\\fizzler', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\fizzler', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\fizzler'"), ('../cache/resources/instances\\50s\\items\\fr', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\fr', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\fr'"), ('../cache/resources/instances\\50s\\items\\futbol', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\futbol', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\futbol'"), ('../cache/resources/instances\\50s\\items\\gel_dropper', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\gel_dropper', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\gel_dropper'"), ('../cache/resources/instances\\50s\\items\\gel_plate', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\gel_plate', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\gel_plate'"), ('../cache/resources/instances\\50s\\items\\hmw', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\hmw', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\hmw'"), ('../cache/resources/instances\\50s\\items\\laser', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\laser', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\laser'"), ('../cache/resources/instances\\50s\\items\\mech_plate', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\mech_plate', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\mech_plate'"), ('../cache/resources/instances\\50s\\items\\paint_fizz', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\paint_fizz', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\paint_fizz'"), ('../cache/resources/instances\\50s\\items\\pist_plat', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\pist_plat', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\pist_plat'"), ('../cache/resources/instances\\50s\\items\\rex\\pellet_dest', 'c:\\program files (x86)\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\rex\\pellet_dest', "[WinError 5] Zugriff verweigert: 'c:\\\\program files (x86)\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\rex\\\\pellet_dest'")]
`

That is the full log
[BEEMOD Exporting log.txt](https://github.com/BEEmod/BEE2.4/files/730814/BEEMOD.Exporting.log.txt)

When i start beemod i also get much errors like these:
```
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\tint_noglow.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\tint_noglow_bounce.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\tint_noglow_speed.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\tint_noglow.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\props_underground\plasticwall001d.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\p1_ball\sphere.vtf" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\p1_ball\sphere.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\p1_ball\sphere_bounce.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\models\bee2\cube_color\p1_ball\sphere_speed.vmt" not in zip! (BEE2_CUBE_COLORISER)
[W] packageLoader: Warning: "resources\materials\bee2\bullseye\bullseye_glow.vtf" not in zip! (BEE2_OVERGROWN)
[W] packageLoader: Warning: "resources\materials\bee2\bullseye\bullseye_glow.vtf" not in zip! (BEE2_OVERGROWN)
```

Here is the full log:
[BEEmod LOGS  Starting.txt](https://github.com/BEEmod/BEE2.4/files/730817/BEEmod.LOGS.Starting.txt)

These are the Items i selected:
![beemod](https://cloud.githubusercontent.com/assets/25353348/22307388/0907a2ac-e343-11e6-8a73-ad2c845067e4.png)

Thanks for any help
If anything more is needed just ask.

**Comment by laserman120** [comment]
Ok i just tried to delete all Portal 2 files and reinstall everything. It looks like i don't have any access to delete any folders even with Administrator... i'll try to fix that

**Comment by laserman120** [comment]
OK it looks like the problem was that steam was using the files. After restarting and shutting steam down it worked.

Case is solved. 
Thanks

**Comment by Tiblets** [comment]
Thank you
