### ISSUE TITLE
Clicking game options in the About drop-down crashes BEE2.4

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#498]
This will happen the second time one of these is clicked.

EDIT: I've noticed that it will actually crash after clicking *anything* once one of these has been pressed. What are these for anyway?

**Comment by TeamSpen210** [comment]
Can you post the BEE2 log?

**Comment by Luke18033** [comment]
Right [here](https://drive.google.com/open?id=0B-EufsFomXfLV1BCbFNNSmZKa28). There doesn't seem to be anything unusual...

**Comment by TheDarkBomber** [comment]
Try enabling error message boxes after crash.

**Comment by TeamSpen210** [comment]
Does the 'More Info' button in items work?

**Comment by Luke18033** [comment]
Yep, so do the wiki and repository links. Only the game options have this issue.

**Comment by Luke18033** [comment]
Interestingly, I don't even have this issue anymore. Did you fix it?

**Comment by Luke18033** [comment]
This seems to have been fixed now, case closed.
