### ISSUE TITLE
Floor button and connections broken

### ISSUE THREAD

**Issue by JaredBrian** [BEEmod/BEE2.4#499]
When I use any bee2.4 version I get an error whenever I have a floor button(including the cube and sphere button) it crashes about 75% of the way through the building geometry phase of building the chamber inside of the PeTi editor saying there was an error building the puzzle.i can reverse its effects by using the bee2.2 alpha but there are items only in 2.4 that id like to be able to use. it should be noted that I am using this on a Linux machine through wine and I have tried it on a play on Linux version of portal but whenever I use bee2 on that version it makes it so portal 2 can't open anymore. so is there a fix for this? and is this a Linux only bug? or what.
Thanks in advance-Jared_Brian_

**Comment by JaredBrian** [comment]
I should also say that the exit door isn't rendering properly when actually in the playtest and is just missing and you can see off into space where it should be.

**Comment by Byzarru** [comment]
Which style and can you give the console log?

**Comment by JaredBrian** [comment]
I hadn't even thought about trying a different styles but after messing around with all of the other styles I've found that the older button from the old aperture will allow the test to compile but the don't work and I've also found that in all of the styles the connections between items don't seem to work at all so the problem is worse than I thought.

Log from a clean style test chamber with just a floor button connected to the door:

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF /home/jaredbrian/.local/share/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 30 (ms)
Did not detect any valid joysticks.

VBSP failed.

ERROR: ld.so: object '/home/jaredbrian/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Valve Software - vbsp.exe (May  4 2016)
1 threads
materialPath: /home/jaredbrian/.local/share/Steam/steamapps/common/Portal 2/portal2/materials
Loading /home/jaredbrian/.local/share/Steam/steamapps/common/Portal 2/sdk_content/maps/preview.vmf
ConVarRef gpu_level doesn't point to an existing ConVar
Could not open instance file instances/BEE2/clean/items/button/weighted_white.vmf

**Comment by JaredBrian** [comment]
and here is a log where I just have a stand button connected to the exit door and a cube dropper and neither do anything when the button is activated/

[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 30301 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 30378 (ms) ...launching map!
Unable to remove /home/jaredbrian/.local/share/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073009401\error.p2c! (errno 2)
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Couldn't find any entities named cd3482-box_ents_*, which point_template cd3482-cube_template is specifying.
Couldn't find any entities named cd3482-box, which point_template cd3482-cube_template is specifying.
Precache called on a point_template that has no templates: cd3482-cube_template
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Did not detect any valid joysticks.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
CreateInstance called on a point_template that has no templates: cd3482-cube_template
Redownloading all lightmaps
Did not detect any valid joysticks.
SAVEGAME:  254.5kb,  137.4kb used by 298 entities (puzzlemaker/preview)
SAVEGAME:   28.0kb,   15.1kb used by 180 entities (puzzlemaker/preview)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1506
