### ISSUE TITLE
Coop Map is not starting correctly

### ISSUE THREAD

**Issue by laserman120** [BEEmod/BEE2.4#502]
When i start my coop map it loads like normal, but instead of spawning in the tubes, both players spawn in a small black Box outside the map.

I have BTS Style selected.
more here:
![unbenannt](https://cloud.githubusercontent.com/assets/25353348/22398850/4a99cae8-e590-11e6-8cb3-4f605fbd0128.png)

This is the box:
![20170128194655_1](https://cloud.githubusercontent.com/assets/25353348/22398974/b6b73d08-e592-11e6-814c-38ad3e949748.jpg)

And here P-Body inside the Box ( left side )
![20170128194711_1](https://cloud.githubusercontent.com/assets/25353348/22398978/c7d0eefe-e592-11e6-88bc-e16ae14021d1.jpg)

If anything more is needed just ask
Thank you

**Comment by TeamSpen210** [comment]
I Haven't made the BTS style coop stuff, so it's all manner of broken.

**Comment by laserman120** [comment]
ok i'll change the style
thank you
