### ISSUE TITLE
BEE2.4 Prerelease 24

### ISSUE THREAD

**Issue by Jaxoshu** [BEEmod/BEE2.4#503]
Everytime i build a level with this lastest version it spawns me in the elevator, but the elevator room is misplaced in the level itself, seen in this screenshot
![20170128190858_1](https://cloud.githubusercontent.com/assets/25406978/22399108/ebc4d4c4-e58d-11e6-84d5-e01799b02592.jpg)

I totally love all of the versions before, and I want to continue making it with the lastest version, but it still happens even when I go to downgrade to prerelease 23 or 22, so I want to know how to fix it please

**Comment by Konclan** [comment]
What the actual?

**Comment by TeamSpen210** [comment]
Could you turn on `developer 2` in the console, then post the contents after compiling? (Cancel after the first bar is finished.)

**Comment by Luke18033** [comment]
No response from the author, as usual.
