### ISSUE TITLE
Chamberlock problem

### ISSUE THREAD

**Issue by melerpe** [BEEmod/BEE2.4#504]
I got a small issue with the chamberlock. Their hitbox shows always red (And always have error model), I am using the newest packages and items.

**Comment by TeamSpen210** [comment]
You need a room behind it for the exit.

**Comment by melerpe** [comment]
ah, thanks. and the error model? will that be fixed soon (On all styles except clean it has an error model)

**Comment by TheDarkBomber** [comment]
BEE2-items issue.

**Comment by Luke18033** [comment]
No, closed issue.
