### ISSUE TITLE
About translation problems

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2.4#509]
Can You add # encoding: utf-8 to scripts? I would like to translate into Chinese. 
THX :)

**Comment by TeamSpen210** [comment]
The source code? The app has translation support - you can make a translation file from the `BEE2.pot` master, and then it should load automatically if you place it in `i18n/lang_code`. (It's a "gettext" translation format.)

**Comment by goodDOS** [comment]
@TeamSpen210 thank you

**Comment by TeamSpen210** [comment]
Could you send me a friend request on Steam?

**Comment by JimCop** [comment]
goodDos is my friend,we going to translate BEE2mod into Chinese.So you can also send me a friend request on steam.     ID yun11344,Username:JimCop.THX (•‿•)

**Comment by goodDOS** [comment]
@TeamSpen210
Add my friend steam, he is responsible for translation work. ID: yun11344, Username: JimCop. Http://steamcommunity.com/id/JimCop/

My steam
Http://steamcommunity.com/id/Kamho/
If you do not mind my lying in your friends list. XD
