### ISSUE TITLE
Coop exit not opening when something is connected to it

### ISSUE THREAD

**Issue by bleutwo** [BEEmod/BEE2.4#512]
When compiling the level in Coop mode, the exit appears to be placed 2 times when looking at the camera, making it impossible to complete the map.

EDIT: This appears to only be the case when something is connected to the exit door. When nothing is connected, the door opens.

![20170204141448_1](https://cloud.githubusercontent.com/assets/25549100/22618731/700fb89c-eae4-11e6-98a6-f658b3f37ba0.jpg)

**Comment by TheDarkBomber** [comment]
This is a BEE2-items issue.

**Comment by bleutwo** [comment]
Ok, I'll post it there instead
