### ISSUE TITLE
There was an error building the puzzle

### ISSUE THREAD

**Issue by BlackTiger63** [BEEmod/BEE2.4#515]
I'm using Bee mod 2.4 residing in D:\BEE2.4 directory.
Installed like it should be with additional items, no problem there.

Until yesterday afternoon my map compiled fine. Then yesterday evening I finished the map and then it starts compiling and just at the end of the first line (building geonometry) it says "there was an error building the puzzle".
I already tried removing vrad and vbsp files and verify cache but problem persists. Maybe I used too many items in the puzzle? So I removed a few and made a hallway smaller but the same problem occurs.

This is what I got from the developpers console where the error occurs:

> [INFO] vbsp.run_vbsp(): Arguments: "D:\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "D:/Steam/steamapps/common/Portal 2/portal2/" "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 6 threads
 | materialPath: D:\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/logic/bee/trigger_multiple.vmf
 | 
 |_
[INFO] BEE2_config.save(): Saving changes in config "D:\BEE2.4\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

How can I fix this?

**Comment by Luke18033** [comment]
It's a missing instance for the Trigger Multiple, but triggers shouldn't use instances anymore...

**Comment by BlackTiger63** [comment]
You're surely correct, but I have no clue how to fix this.

**Comment by Luke18033** [comment]
Neither do I. Remove any Trigger Multiples in the map for now.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1550
