### ISSUE TITLE
Splash Screen "Extracting Images" Overflow

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#516]
this happens on the splash screen every time it starts. the "Extracting Images" bar overflows

![splash overflow](https://cloud.githubusercontent.com/assets/11165643/22629254/874df646-ebb0-11e6-9922-9ec3f0fbe907.jpg)

**Comment by Luke18033** [comment]
You don't need to assign people to bugs...

**Comment by TeamSpen210** [comment]
Fixed by removing the progress bar entirely.
