### ISSUE TITLE
Add Multitasking Arm

### ISSUE THREAD

**Issue by XdplayerdX** [BEEmod/BEE2.4#520]
Can You Add this,is like a panel but have more angles and can move for any direction
Examples:
http://half-life.wikia.com/wiki/Aperture_Science_Multitasking_Arm
https://www.youtube.com/watch?v=Kyc4JK24EuI
In gmod have one of then https://steamcommunity.com/sharedfiles/filedetails/?id=862644776&searchtext=
thank you this is the best addon for portal 2 !!!

**Comment by Luke18033** [comment]
Great idea, but what would it be in Old Aperture or P1?

Open issues related to items or styles on the [BEE2.4 Default Pack repository](https://github.com/BEEmod/BEE2-items).

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1583

**Comment by XdplayerdX** [comment]
It's like a panel but,can move follow one rail,can ben angled,and can support other itens(cubes,turrets,cameras(like whetley and turrets or cubes)) and can make everything like this addon:
http://images.akamai.steamusercontent.com/ugc/159152387699546569/E006DCAFA804B9FEDE0DC934FAD6CF691365D4CB/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|637:358&composite-to%3D%2A%2C%2A%7C637%3A358&background-color=black

http://images.akamai.steamusercontent.com/ugc/159152387699247680/9CC5771EFC607C69858BA78780ABC08B6259DB7F/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|268:268&composite-to%3D%2A%2C%2A%7C268%3A268&background-color=black
Well you can remove that of the Old Aperture or portal 1 or you can use the old aperture panel textures and models,with some editions.

Thanks For Everything And Sorry for my bad english !
