### ISSUE TITLE
Make uninstalling more clear

### ISSUE THREAD

**Issue by tenbenbrett** [BEEmod/BEE2.4#521]
Your mod is great and I enjoyed my time with it but I have my reasons to no longer use your mod and I realized that I would have to set everything back to normal before I got rid of the mod so I could have original Portal back but have no idea how to do that even the PORATL2 palette is a little off and I would like it to be the original files how do I do that?

**Comment by TeamSpen210** [comment]
Go to the 'game' menu option, and choose to remove the game. That will uninstall it.

**Comment by Luke18033** [comment]
I didn't even know you could do that.

**Comment by TeamSpen210** [comment]
I should probably rename it to 'uninstall' or something.
