### ISSUE TITLE
Portal Gun

### ISSUE THREAD

**Issue by GeoffreyOfficial** [BEEmod/BEE2.4#522]
Hello, I just come back to Portal 2 after years. I would like to update my maps with that new bee2, but I have an issue because I created a map where you don't have a portal fun at the beginning, and you do some puzzle without it, then you keep the gun.

That item disapear of my map and I can't find it in your software.
There is the portal gun pedestal but with fires portals and you can't pick up the gun ...

So how can i get back that item ?

**Comment by Luke18033** [comment]
Do you mean the Portal Gun Pedestal? Because that's already implemented.

**Comment by GeoffreyOfficial** [comment]
Hello Thank you for your answer, like i said on my message. There is a portal gun pedestal, yes but the description said:

_Fires portals. Can rotate automatically before being collected by the player. In Aperture Tag, Portal Guns **cannot be picked up** (only firing portals).
When picked up, autoportals of the same colour permanently deactivate, and the output activates.
• Weighted fires both (use Start Reversed to choose).
• Cube is blue-only.
• Sphere is orange-only._

So what I would like to take ie, like it was in my map
Her eis my map:
https://www.youtube.com/watch?v=d9xdOOPg8-A&index=5&list=PLk1SOEr59VRUjFJqXvuv37JrMhzHu-PMJ
Like you can see, I have nothing at the beginning and at 3:45, i take the portal gun.

**Comment by Luke18033** [comment]
Nothing is wrong with the description or the item. In Aperture Tag; The Paint Gun Testing Initiative, you can't pick up the portal gun, it will only rotate and fire portals. In Portal 2, portal guns can be picked up just fine.
