### ISSUE TITLE
[Game Crash] Gel on BTS Buttons(?)

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2.4#524]
I converted [one of my older maps](http://steamcommunity.com/sharedfiles/filedetails/?id=545151069) to a Wheatley style via BeeMod's BTS style. At one point in the map, you can get gel into an excursion funnel, where it can be carried through an emancipation grill and onto (what was in clean style) a pedestal button (now a red "elevator button"). The game immediately crashed. Perhaps the new button type does not have a "painted" skin?

**Comment by Luke18033** [comment]
Put issues about items or styles on the [BEE2-items repository](https://github.com/BEEmod/BEE2-items).

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1602
