### ISSUE TITLE
Installing the Dev version

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2.4#527]
Normally, I would try just dumping all the files into the main BEE2 directory, and that's probably how it's supposed to be done, but the normal version and the Dev branch files do have a few key differences, so it would be helpful to have a guide somewhere to smooth, safe, and not-breaky installation of the Dev version.

**Comment by Luke18033** [comment]
That's not how it's done. Check the README for instructions.

**Comment by TheDarkBomber** [comment]
The README doesn't give good enough instructions, it's impossible to install the module srctools.

**Comment by Endermage77** [comment]
Soo...

How, exactly, is it done?
So's I can have a go with the turret droppers what use Dev Version BEE2 compiler stuff?

**Comment by TeamSpen210** [comment]
You want to clone the repros to your computer, and you'll then need to install Python and the other dependencies to get it running from source.

**Comment by TheDarkBomber** [comment]
That's not what I'm saying. I'm saying to update the README with clearer instructions. ESPECIALLY WITH INSTRUCTIONS ON HOW TO INSTALL SRCTOOLS!!

**Comment by Endermage77** [comment]
I'm not particularly interested in doing some development of my own (unfortunately), mind you, I simply want to use it normally so that dev items depending on code within it will work properly.

**Comment by TeamSpen210** [comment]
Those two things are basically the same for installing the dev version.

**Comment by TheDarkBomber** [comment]
HOW TO INSTALL SRCTOOLS?!?!?!??!

**Comment by TeamSpen210** [comment]
Clone that repro, then run 'python setup.py install' in the folder. You'll need to switch to dev for it to work with the current stuff.

**Comment by TheDarkBomber** [comment]
I tried that, didn't work. There's a missing `.bat` file.

**Comment by TeamSpen210** [comment]
`vcvarsall.bat`? That means you need to install a correct C compiler to build some things (unfortunately rather complicated.)

**Comment by TheDarkBomber** [comment]
Then uncomplicate it.

**Comment by Endermage77** [comment]
... May I have a step-by-step instruction guide at least?

**Comment by Endermage77** [comment]
Hang on, never mind. I found a link to an instruction guide on #541.

**Comment by gamerscruffy** [comment]
You're welcome for the guide. ^^

**Comment by Luke18033** [comment]
@BenVlodgi wrote the BEE2.4 readme (I think), and it doesn't give very good instructions...

**Comment by TeamSpen210** [comment]
That would be my fault.
