### ISSUE TITLE
Style Error

### ISSUE THREAD

**Issue by DoubleDamned** [BEEmod/BEE2.4#528]
When Im Choosing Overgrown Style And I When I Testing Or Publishing There Is A Error And Im Sad

**Comment by Luke18033** [comment]
Do you have the latest Pr24? Pr23 had a bug where Overgrown would fail to compile when not using exit 3. That's been fixed now.

**Comment by DoubleDamned** [comment]
I have updated this version couple days ago to try and fix this problem

**Comment by TeamSpen210** [comment]
What's the error you get? If it's just a compile error, make sure to copy the error from the console.

**Comment by LautaroL20** [comment]
While youre into the puzzlemaker, compile the map then when you get the error message open up the Developer Console and copy paste the full message, here.

**Comment by DoubleDamned** [comment]
maybe I dont know so I'l give the error

**Comment by LautaroL20** [comment]
As usual with these issues, no response from the author. I'm going to close this until we get a response...
