### ISSUE TITLE
Beemod constantly crash after Sync with Github: Line 159, in <module> extract_packages.check_cache(Pack_data("zipz) KeyError: "zips"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#531]
Any solution for this? Ive already synced the "srctools", "BEE2.4" and items section, but nothing worked...

![Crash](https://cloud.githubusercontent.com/assets/12244376/23227724/a35632e8-f918-11e6-819e-4dc549c2f42e.png)

**Comment by TeamSpen210** [comment]
Go into `config/config.cfg`, and set `preserve_BEE2_resource_dir` to 1. I rewrote a lot of stuff and missed that part.

**Comment by TeamSpen210** [comment]
Fixed via 2ff23801f7c285a97f23d0a37649df7f92966739
