### ISSUE TITLE
Beemod keeps exporting full resources each time you change Style or something into the Palette

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#533]
After the first export, each time you change the style or anything in the Palette then hit the export button, beemod doesn´t skip the Resources and Music from the Progress Bar as it did before.

**Comment by LautaroL20** [comment]
Same with this :/

**Comment by ZombiePwner1** [comment]
Illuminati confirmed.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - It is pretty weird since beemod did skyp resources and music (afther the first export), but now it doesnt.

**Comment by ZombiePwner1** [comment]
Well this certainly would be very bad in PRL 25

**Comment by LautaroL20** [comment]
Indeed :(

**Comment by LautaroL20** [comment]
@TeamSpen210 - Any idea why this may happens?

**Comment by TeamSpen210** [comment]
Are you running from the folders? If so, it will always extract to ensure they're accurate.

**Comment by LautaroL20** [comment]
Ah, this seems to be intended then. This is a good way to not having to re-open Beemod each time i change something into the folders.

**Comment by LautaroL20** [comment]
Btw, where is an "intentional" label when you need it?

**Comment by Luke18033** [comment]
It's only on BEE2-items right now.
