### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Maroki06** [BEEmod/BEE2.4#535]
Where is the BEE2.exe file located in P2 files? I was searching for 10mins by now, and i could only find the old beemod files.

**Comment by LautaroL20** [comment]
You can find the BEE2.exe executable inside the "bin" folder where you extracted the aplication. The installation from this new version is not merged with the Portal 2 files since you can extract it anywere in your Hard Device.

**Comment by Maroki06** [comment]
ok thanks

2017-02-26 16:36 GMT+01:00 Lautaro <notifications@github.com>:
