### ISSUE TITLE
VBSP issue after multiple restarts, re-installs and re-compiles.

### ISSUE THREAD

**Issue by Wii2** [BEEmod/BEE2.4#538]
No idea what's going on with my computer. I've seen other people with this error, but no matter what I do I can't get rid of it. No matter what style I use, or Items, etc. and so forth.
I've tired re-installing BEEMod 2.4 and then I tired re-installing Portal 2, but that doesn't work, so I just copied the console log from the start of Map Creation, but if I forgot something I'll add it in.

Cheers,
     - Wii2

-------------------------------------------------------------------------------------------------------------------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198134598480\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 179 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'voice_pack': 'BEE2_ANNOUNCER_BTS'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['factorycorridor', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2602, misses=304, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'funnelallowswitchedlights': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'allowgoomist': True, 'rexcubepelletfizzle': False, 'multiversecave': False, 'bee_show_trigger': False, 'unlockdefault': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/logic/goo_fade.vmf', 'instances/BEE2/bts/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf']}
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.clump_walls(): Clumping: 108 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/metalwall_bts_001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/metalwall_bts_001b_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/squarebeams_bts.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

] //Well, something's gone wrong!
]

![image](https://cloud.githubusercontent.com/assets/25862505/23549069/52914188-005a-11e7-8496-c4dcf3b9c030.png)

**Comment by LautaroL20** [comment]
@Wii2 - Can you compile normal without using Beemod?

**Comment by Wii2** [comment]
If I verify and re-install the game files (via the Steam properties tab), I can compile and build Test Chambers, but If I leave the BEEMod files (VBSP.exe & VRAD.exe) it fails to compile.

- Wii2

![image](https://cloud.githubusercontent.com/assets/25862505/23585050/edebdb3e-01c2-11e7-899f-f9b160281009.png)

**Comment by LautaroL20** [comment]
Well, your issue with Beemod may happens due to two reasons:

- You may have merged the  Bee2.4 installation files into the Portal 2 folder (No need to unzip the beemod files with the Game´s folder, you can install this anywere esle and it´ll work)

- Windows may be blocking some files because you have not enough administrator permissions.

Other than that, i can´t guess whats going on....

**Comment by Wii2** [comment]
I have fixed the issue by manually deleting any leftover BEEMod folders and files in the Portal 2 directory (The BEEMod folder and the VSBP and VRAD's again). And then checked and installed the files again through Steam, then BEEMod.
May I suggest, if possible, to add a 'Clean Directory' option?

Thanks for all the help,
- Wii2

**Comment by Luke18033** [comment]
Removing Portal 2 from the BEE2.4 game list will "uninstall" it from that game, deleting all BEE2.4-related files.
