### ISSUE TITLE
Pedestal rooms

### ISSUE THREAD

**Issue by BenVlodgi** [BEEmod/BEE2.4#54]
Related to some chatter in the BEE discussion.

What: A room or area (could be a part of the elevator instance, like an extended walkway a the top of the stairs) that provides the player with the portalgun that they will be using for the test. Gun should maybe then be removed from the player before the elevator ride.

Why: To draw the players attention to the gun and its capabilities. Specificically useful in chambers where the user can only shoot blue portals.

How: (In order of how it probably should be done, first one is probably the best option)
Could be a compile option in the BEE2 which is then handled by the precompiler. 
Could be an item when present in the map creates the room. This item could also use used to indicate what version of the Portalgun is used. (I don't actually know how that works in this version)
Could be some right click property on the entry door.

**Comment by ellingtonisland** [comment]
good idea

**Comment by Konclan** [comment]
Was this made before Pedistals were added? Also I still like the idea of including a pedistal in a pre-room added before the test chamber

**Comment by BenVlodgi** [comment]
This was in the original BEEMOD
I don't think its in the BEE2

**Comment by Luke18033** [comment]
This isn't really needed, just put a portal gun pedestal right in front of the entry door.
