### ISSUE TITLE
Content file locked :S

### ISSUE THREAD

**Issue by gamerscruffy** [BEEmod/BEE2.4#540]
Here's what happened: The puzzles wouldn't compile so It said to delete the vbsp and vrad.exe, but there was only vrad.exe with a BEE2 icon on it, and vbsp-original.exe. I deleted them both and verified the cache, then I tried opening it and it said a file that never existed since I got BEE2 was content locked. I have no idea on how to fix it.

I've tried to fix it, but here's the error that popped up: http://i.imgur.com/so9AVdW.png

Please help! I really wanna play Portal 2. I really wanna use Bee2.4!

**Comment by hop193** [comment]
Upload this here:
https://github.com/BEEmod/BEE2-items
they may notice it better there.

**Comment by TeamSpen210** [comment]
It's not to do with items. VBSP is part of Portal 2, 'content file locked' means something's using it. Make sure you quit Portal 2 and BEE2, or restart your computer to ensure nothing's opened the file.

**Comment by gamerscruffy** [comment]
Thank you. I forgot to close this a day or 2 ago. Bee2 is very fun!
