### ISSUE TITLE
Development Version cause error when load "Extracting Image"

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2.4#544]
![development version error](https://cloud.githubusercontent.com/assets/25024629/23691754/290056e0-03a9-11e7-9206-1a8e9752bd63.png)

**Comment by TeamSpen210** [comment]
You might need to pull the current copy of the app and srctools.

**Comment by TeamSpen210** [comment]
Indeed, this error doesn't exist anymore.

**Comment by Konata-Chan** [comment]
@TeamSpen210 Ok Thanks.That worked
