### ISSUE TITLE
How to install srctools?

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2.4#546]
It looks like to install the Dev version, one also needs srctools.
I was wondering how one installs srctools properly and how to use it to install the dev version.

NOTE: I've already found and downloaded the file.

**Comment by TheDarkBomber** [comment]
@TeamSpen210

**Comment by TeamSpen210** [comment]
To install srctools, after cloning it, `cd` to the repro directory and run `python setup.py install`.

**Comment by TheDarkBomber** [comment]
Don't forget that you need Visual Studio 2015.

**Comment by Endermage77** [comment]
What do I use to run the setup.py?

**Comment by TeamSpen210** [comment]
The Python version you have installed.

**Comment by Luke18033** [comment]
You might actually have to use `py` instead of `python`, that's what I had to do.

**Comment by Endermage77** [comment]
Okay, I have recently installed Python, now what do I do to make it run the setup.py?
