### ISSUE TITLE
"No Packages Item Directory" Window unclosable

### ISSUE THREAD

**Issue by Endermage77** [BEEmod/BEE2.4#547]
Every time I attempt to reinstall BEE2 (Which is every now and then what with accidentally messing up my own files by accident), I run the BEE2 without the packages directory so it will create the config.config sos Ic can use the Dev version packages I've already got.

However, every time I do this, first it gives an error window saying I didn't put the packages in, then a second error window pops up saying something along the lines of "No Item Packages Directory!" This window cannot be closed normally, instead the BEE2 executable has to be shut down manually fom the task manager for it to close.

Can this be fixed, please?

**Comment by TeamSpen210** [comment]
If you make a copy of the config.cfg, or just that line and the header it will add everything else to that.

**Comment by Endermage77** [comment]
Yeah, I suppose. still, I think that a bug like this deserves a fix.

**Comment by LautaroL20** [comment]
This is fixed since a long time ago.
