### ISSUE TITLE
Lag Spikes

### ISSUE THREAD

**Issue by Jazz63540** [BEEmod/BEE2.4#548]
At the end of a test chamber when you walk through the first exit door and are walking to the next one that leads to the elevator room, a lag spike always occurs. So far the styles this has occurred on for me are Overgrown and Clean.

**Comment by gamerscruffy** [comment]
Just use original clean for now. They are very similar.

**Comment by TeamSpen210** [comment]
Those would be identical in this case. This might ne a bit inevitable, that's when the elevator room turns on and becomes visible.

**Comment by Jazz63540** [comment]
I have tried changing the style to original clean, although the spike is shorter it still persists. This did not occur in the same area in previous versions, it instead occurred a couple of seconds after entering the exit elevator room.

**Comment by Luke18033** [comment]
So, this is a Valve bug?

**Comment by Luke18033** [comment]
Considering that I don't have this issue, I'm just going to assume it is.
