### ISSUE TITLE
Please, reduce the Loading Panel to a small window to stop overlapping everything!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Enterpise** [BEEmod/BEE2.4#552]
Make it a way so it only occupies a pretty small portion of the monitor´s screen, so it can appear at the Bottom / Top left, because the way that Beemod currently displays its loading process once launched its just maddening!!

I could give MANY reasons why i am suggesting this, one of the reasons is that when i am chatting to someone on Steam, if i just decided to open the Beemod application, it becomes literally impossible to keep replying him until the bloody process finishes because of how it overlaps everything.

**Comment by TeamSpen210** [comment]
Yep, I should aboht halve it in size, and allow positioning it other than center.

**Comment by Luke18033** [comment]
What you should really do is make it a normal window that doesn't overlap everything. Maybe make it work like the Borderless Window mode in some games (including Portal 2).

**Comment by Luke18033** [comment]
That doesn't have a border and can't be alt-F4'ed but still can be overlapped by other windows.

**Comment by LautaroL20** [comment]
> One of the reasons is that when i am chatting to someone on Steam, if i just decided to open the Beemod application, it becomes literally impossible to keep replying him until the bloody process finishes because how it overlaps everything.

Yes, that happens to me too and its pretty annoying :/

**Comment by TeamSpen210** [comment]
I've managed to make it so you can now drag it around and whatnot. I could also make it not overlap, but then you get a different problem. It doesn't show up on the taskbar, so you can't bring it back if it drops behind other windows.

**Comment by LautaroL20** [comment]
> I've managed to make it so you can now drag it around and whatnot.

Well, that sounds good! But i think you should make a small re-design visual on its window edges so people can notice that the loading window is grippable.

**Comment by TheDarkBomber** [comment]
@TeamSpen210 Then make it show up on the taskbar...?

**Comment by TeamSpen210** [comment]
But I can't find a way to do that...

**Comment by LautaroL20** [comment]
I am really glad that you maked it non-modal. This is a good way to still keep Bizarru´s screenshots during loading without having to deal with the overlapping annoyance. So... now i consider this fixed for next release.

**Comment by Byzarru** [comment]
Pretty much every app I use with a splash screen hides behind windows when they are brought to the front _except_ BEE.

**Comment by Luke18033** [comment]
The export window should be draggable too.

**Comment by LautaroL20** [comment]
@Luke18033 - Indeed. I have open an issue suggesting that: https://github.com/BEEmod/BEE2.4/issues/559

**Comment by TheDarkBomber** [comment]
@TeamSpen210 It's possible. You can get the taskbar icon to show when using the main GUI, so why not the splash screen?

**Comment by TeamSpen210** [comment]
Please don't just look at the surface, and then assume how all the code works. It's not a 'real' window by Window's standards, since it doesn't have the border, title bar, etc. That's why all this happens.

**Comment by TheDarkBomber** [comment]
That's not what makes it a real window. What makes it a window, is that it shows up.

**Comment by TeamSpen210** [comment]
No, it doesn't.

**Comment by TheDarkBomber** [comment]
Yes, IT DOES. I know how windows work. You're getting confused with windows and window borders.

**Comment by TeamSpen210** [comment]
http://www.tcl.tk/man/tcl8.6/TkCmd/wm.htm#M56

>> Setting the override-redirect flag for a window causes it to be ignored by the window manager; among other things, this means that the window will not be reparented from the root window into a decorative frame and the user will not be able to manipulate the window using the normal window manager mechanisms.

**Comment by TheDarkBomber** [comment]
That's not what Microsoft says. In Visual Studio, there is a "Window Border" option, which includes "None". And Visual Studio is Microsoft, as windows are. Microsoft invented windows (and Windows). Microsoft invented GUI. Microsoft defines what a window is, and what it's attributes are.

**Comment by TeamSpen210** [comment]
I'm not using Visual Studio. It's implemented differently. TK is cross-platform, it works on Linux and OS X as well.

**Comment by TeamSpen210** [comment]
Microsoft did not invent the GUI, or windows. That was Xerox, if anyone.

**Comment by TheDarkBomber** [comment]
Linux and OS X would not exist without Microsoft.

**Comment by TeamSpen210** [comment]
Please check your history.

**Comment by TheDarkBomber** [comment]
Just make it show up on the taskbar. It's not really that hard.

**Comment by TeamSpen210** [comment]
It is. Don't say 'it's not that hard', unless you actually are familar with the code, language and libraries you're talking about.

**Comment by TheDarkBomber** [comment]
-_-

**Comment by ZombiePwner1** [comment]
@TheDarkBomber I don't think you know much at programming even though you told me once you made a OS.

**Comment by LautaroL20** [comment]
Lol, it looks like that @TheDarkBomber is no longer even a "Contributor" anymore.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Indeed.

**Comment by Luke18033** [comment]
He's never been a contributor on BEE2.4. Check the items section.

**Comment by ZombiePwner1** [comment]
@Luke18033 He was a contributor before he had a contributor tag next to his name.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I think that our logic was a bit mixed up....

**Comment by ZombiePwner1** [comment]
@LautaroL20 it's not mixed up I remember clearly he had a contributor tag next to his name.
