### ISSUE TITLE
Make Beemod to not launch Portal 2 after click the "X" button even if "Launch Game After Export" were enabled

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#553]
EDITED: It should launch after click the "Accept" button, **but not the "X" though...**

______________________________________________________________________________________

![image](https://cloud.githubusercontent.com/assets/12244376/23935837/39d81a1e-092d-11e7-9b94-a7bf9a853e59.png)

**Comment by TeamSpen210** [comment]
It's a setting in options now.

**Comment by LautaroL20** [comment]
It should launch after click the "Accept" button but not the "X" though, maybe someone wants to using the "Launch game" option but just forgot something to do into the palette.

**Comment by TheDarkBomber** [comment]
Is the option in the settings to show the message box or just launch Portal 2 after exporting? If it is to launch P2 after exporting, it should be the first one.

**Comment by LautaroL20** [comment]
Fixed title, now is more accurate.

**Comment by LautaroL20** [comment]
This was implemented.
