### ISSUE TITLE
Make the "Exporting Panel" to be also "Non-Modal"

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#559]
Useful when using the "Full Expor" mode.

![exporting panel](https://cloud.githubusercontent.com/assets/12244376/24161635/c5cb54da-0e43-11e7-8b50-1ee948a4c7ba.png)

**Comment by Luke18033** [comment]
Kind of a duplicate of #552.

**Comment by TeamSpen210** [comment]
That's the splash screen, this is the exporting one.

**Comment by Luke18033** [comment]
They're basically the same thing, right?

**Comment by LautaroL20** [comment]
Exept that @enterpise was explicitly refering to the Loading Screen which is big and overlaps the entirely Deckstop, and not the Exporting Panel which is already "Small".
