### ISSUE TITLE
Hammer Editor unable to compile and play chambers with Beemod

### ISSUE THREAD

**Issue by ryyanmapes** [BEEmod/BEE2.4#561]
The Hammer editor keeps throwing me an error about missing instances, but only on BeeMod chambers.
![capture](https://cloud.githubusercontent.com/assets/25805800/24318915/53de2474-10dc-11e7-956d-4c28214d58be.PNG) 
I tried it with just a simple chamber with no BeeMod items in it but still breaks.
![capture2](https://cloud.githubusercontent.com/assets/25805800/24318918/6eff7140-10dc-11e7-88f5-61014e7dea94.PNG)
Both worked fine in Puzzlemaker. I'm probably just doing something dumb, though.

**Comment by Luke18033** [comment]
Are you using `puzzlemaker_export`? That doesn't work in BEE maps. Set Spawn Point to Elevator and Restart When Reaching Exit off, compile, then edit `/styled/preview.vmf`.

**Comment by TeamSpen210** [comment]
Don't use the `puzzlemaker_export` command. It doesn't run the precompiler, so the maps won't get edited correctly. Compile ingame once with 'start in elevator' enabled, then edit `maps/styled/preview.vmf`.

**Comment by ryyanmapes** [comment]
Oh, my bad! I knew I was doing something stupid.
