### ISSUE TITLE
Can't export anything

### ISSUE THREAD

**Issue by Al3x2nder** [BEEmod/BEE2.4#564]
---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2.pyw", line 125, in <module>
  File "F:\Git\BEE2.4\src\packageLoader.py", line 407, in load_packages
  File "F:\Git\BEE2.4\src\packageLoader.py", line 2114, in parse
  File "C:\Python34\lib\os.py", line 237, in makedirs
PermissionError: [WinError 5] Zugriff verweigert: '../vpk_cache\\vpk_bee2_1980s\\materials\\models\\props_map_editor'

This has been copied to the clipboard.
---------------------------
OK   
---------------------------
It said already before when I tried to export Items and Styles to Portal 2 "Access Denied" or in German"Zugriff Verweigert". (I use a german PC)

Sorry for my bad English, I'm still learning.

**Comment by TeamSpen210** [comment]
Try deleting the `vpk_cache` folder.

**Comment by Al3x2nder** [comment]
---------------------------
BEE2 Error!
---------------------------
An error occurred: 
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\UI.py", line 844, in export_editoritems
  File "F:\Git\BEE2.4\src\gameMan.py", line 607, in export
  File "F:\Git\BEE2.4\src\gameMan.py", line 389, in refresh_cache
  File "F:\Git\BEE2.4\src\utils.py", line 544, in merge_tree
shutil.Error: [('../cache/resources/instances\\50s\\items\\bee', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\bee'"), ('../cache/resources/instances\\50s\\items\\button', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\button', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\button'"), ('../cache/resources/instances\\50s\\items\\catwalk', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\catwalk', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\catwalk'"), ('../cache/resources/instances\\50s\\items\\cond_plate', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\cond_plate', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\cond_plate'"), ('../cache/resources/instances\\50s\\items\\conveyor', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\conveyor', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\conveyor'"), ('../cache/resources/instances\\50s\\items\\cube', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\cube', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\cube'"), ('../cache/resources/instances\\50s\\items\\death_fizz', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\death_fizz', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\death_fizz'"), ('../cache/resources/instances\\50s\\items\\fizzler', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\fizzler', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\fizzler'"), ('../cache/resources/instances\\50s\\items\\fr', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\fr', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\fr'"), ('../cache/resources/instances\\50s\\items\\futbol', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\futbol', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\futbol'"), ('../cache/resources/instances\\50s\\items\\gel_dropper', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\gel_dropper', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\gel_dropper'"), ('../cache/resources/instances\\50s\\items\\gel_plate', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\gel_plate', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\gel_plate'"), ('../cache/resources/instances\\50s\\items\\hmw', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\hmw', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\hmw'"), ('../cache/resources/instances\\50s\\items\\laser', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\laser', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\laser'"), ('../cache/resources/instances\\50s\\items\\lautaro', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\lautaro', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\lautaro'"), ('../cache/resources/instances\\50s\\items\\mech_plate', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\mech_plate', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\mech_plate'"), ('../cache/resources/instances\\50s\\items\\paint_fizz', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\paint_fizz', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\paint_fizz'"), ('../cache/resources/instances\\50s\\items\\pist_plat', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\pist_plat', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\pist_plat'"), ('../cache/resources/instances\\50s\\items\\rex\\pellet_dest', 'd:\\steam\\steamapps\\common\\portal 2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\rex\\pellet_dest', "[WinError 5] Zugriff verweigert: 'd:\\\\steam\\\\steamapps\\\\common\\\\portal 2\\\\sdk_content\\\\maps\\\\instances\\\\bee2\\\\50s\\\\items\\\\rex\\\\pellet_dest'")]


This has been copied to the clipboard.
---------------------------
OK   
---------------------------
Now this happens when I try to export something.

**Comment by laserman120** [comment]
I will talk german for a moment:
Versuch mal im Task Manager das Programm: igfxEM.exe zu beenden. Hat bei mir öfters Probleme gemacht und die selbe Fehlermeldung hervorgerufen

sag mir dann ob es funktioniert
