### ISSUE TITLE
BeeMod Uninstall

### ISSUE THREAD

**Issue by GarrothPlays420BlazeIT** [BEEmod/BEE2.4#565]
I am Having Trouble and i need to uninstall beemod and i don't know how please help me

**Comment by TeamSpen210** [comment]
In the file menu, choose 'remove game' and that will uninstall the app completely.

**Comment by GarrothPlays420BlazeIT** [comment]
where is the file menu?

**Comment by TeamSpen210** [comment]
In the BEE2 app.

**Comment by GarrothPlays420BlazeIT** [comment]
Thanks

**Comment by GarrothPlays420BlazeIT** [comment]
Is there like a section to click or what i can't find it

**Comment by GarrothPlays420BlazeIT** [comment]
i found the file menu but all it says is save export new and exit.
