### ISSUE TITLE
Implement a "Cancel" button on the Exporting Panel 

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#566]
_From @LautaroL20 on November 10, 2016 10:53_

For people who do not use Preserve Game Directories, having a "Cancel" button on the Exporting Panel to stop the process could be really useful. For example,  if we forgot to do something (Add an item, or things like that), we are not forced to wait until the process finish.

____________________________________________________________________________________________________

![palette](https://cloud.githubusercontent.com/assets/12244376/20174038/bb044f6a-a71a-11e6-8923-5ee9095bbd14.png)

_Copied from original issue: BEEmod/BEE2-items#990_

**Comment by Luke18033** [comment]
This is a BEE2.4 issue.

**Comment by Luke18033** [comment]
You can already do this on the splash screen by pressing alt+F4. But attempting to do this with the exporting window will crash BEE2, so a cancel button would be useful there.

**Comment by LautaroL20** [comment]
Unfortunately, not sure if this could be maded, since Phyton aparently gets totally frozen when exporting.

**Comment by TeamSpen210** [comment]
This has now been implemented, for all loading screens (including the splash screen).

**Comment by LautaroL20** [comment]
Ok.
