### ISSUE TITLE
sorta dumb idea for the item selector in the peti edtior changes

### ISSUE THREAD

**Issue by NotAnAcccount** [BEEmod/BEE2.4#567]
Can you see if there is a way to enlarge the item selector like add a scroll wheel to it so you can hold more items so you dont need to close portal and make a new palette. if thats possible it would be such a time saver

**Comment by TeamSpen210** [comment]
If I could, I would have.

**Comment by Endermage77** [comment]
Working off the (entirely incorrect) assumption we could get even the remotest access to directly modding Portal 2, there'd probably be a BEE2 palette menu implemented into the editor by now.

But we can't, so there isn't.

**Comment by TeamSpen210** [comment]
Indeed. Although I'd probably have some external things anyway.
