### ISSUE TITLE
Co-op spawn room variants

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#569]
This is part of: https://github.com/BEEmod/BEE2-items/issues/1812

![Concept Art](https://cloud.githubusercontent.com/assets/12244376/24680633/0f8f473c-1968-11e7-9dfe-0eb085838352.png)

**Comment by TeamSpen210** [comment]
The only issue is that since this is additional beyond Valve's setup, I can't ensure they stay the same for a map if you set it to random mode.

**Comment by LautaroL20** [comment]
In that case, we will not include the "Random" option in the Coop Compiler Settings then.

**Comment by LautaroL20** [comment]
And we will set the 1St Spawn to be the PeTi one, and the default selected on the list. (We can recall it to "PeTi Spawn").

**Comment by TeamSpen210** [comment]
I can still make it random, it just might change semi-randomly when you recompile.

**Comment by TeamSpen210** [comment]
This is implemented codewise now, just need to make the actual corridors.
