### ISSUE TITLE
(Portal 1 Theme) Surface Marker in Pallette causing errors

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2.4#570]
Whenever I had the Surface Marker in my Pallette, if I pressed F9 (My hotkey for rebuilding a puzzle) it would display the generic error message.

**Comment by TeamSpen210** [comment]
This isn't a useful error message, as you said it's generic. I need the logs in the developer console.

**Comment by iEnderMan06** [comment]
Hold on then, Just trying to figure out my new problems >-<

**Comment by iEnderMan06** [comment]
I'll make a new chamber,

**Comment by iEnderMan06** [comment]
So it seems to only happen on a specific chamber, This is the best I can provide `[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Brush 241, Side 1: mirrored plane
 | Brush 241: FloatPlane: bad normal
 | Side 2
 | Texture: tools/toolsinvisible
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! `(1)``

**Comment by iEnderMan06** [comment]
![portal2 2017-04-06 08-45-45-796](https://cloud.githubusercontent.com/assets/26350889/24743240/72e0e118-1aa5-11e7-83af-b4c7b6f59f3d.jpg)
I made this simple test, and here's the error message I got:
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (171 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[INFO] vbsp.anti_fizz_bump(): Done!
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['weightedbutton', 'spawn_dual', 'cubedropper', 'buttonacceptsball', 'cube', 'buttonacceptscube', 'floorbutton', 'cubestandard', 'pack_p1_radio_clean', 'cubedropperstandard', 'fizzler']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=41701, misses=323, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'unlockdefault': True, 'nomidvoices': True, 'p1_ported_pgun': False, 'rexcubepelletfizzle': True, 'funnelallowswitchedlights': True, 'restartonexit': False, 'doorcameras': False, 'fixfizzlerbump': True, 'allowgoomist': True, 'multiversecave': False, 'bee_show_trigger': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/p1/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/portal_sounds.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/corner_floor.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/corner_wall.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/p1_antline_floor_double.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/p1_antline_wall_double.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/straight_floor.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/ind_p1/straight_wall.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/box_paint_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/box_paint_orange.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_comp_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/p1_metal_box/metal_box_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/door_01.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/floor_button/base.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/floor_button/exponent.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/floor_button/normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_p1/floor_button/p1_button.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/light_recessedcool_glow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/modular_wall_light.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/p1/overlay_light_gradient.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/p1_metal_box.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/sign_frame_1_wback.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_frame_thick.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_left.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/door_right.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_p1/floor_button.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/garage_stop1.wav"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/wall_move5.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Brush 24, Side 1: mirrored plane
 | Brush 24: FloatPlane: bad normal
 | Side 2
 | Texture: tools/toolsinvisible
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "C:\Users\pikachu\Desktop\Beemod 2.4\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by Luke18033** [comment]
Looks like a problem with the toolsinvisible texture. What items are in the map?

**Comment by iEnderMan06** [comment]
@Luke18033 Fizzlers, Glass, Cube Dropper & Cube and a Floor Button

**Comment by Luke18033** [comment]
In that case it wouldn't have anything to do with the surface marker. Try each item separately, see what's causing the issue.
