### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by laserman120** [BEEmod/BEE2.4#571]
After having problems to export to Portal 2 i tried many things. I have reinstalled steam, Portal 2 and several times Beemod until i found out how simple it is to solve the problem.
Now i saw that i'm not the only one with this problem and i thought i should make a post about it.
This is the overall problem: https://github.com/BEEmod/BEE2.4/issues/564
Beemod is not able to export because a programm is currently using it.

After installing a programm that should unlock the folder i saw that igfxEM.exe is using it. After a quick google search i realized that this is a preinstalled programm made by Intel. 

When i stopped it with the Task Manager everything worked fine.

I also deleted igfxEM.exe cause it is not needed. 

I don't know if this happens with other programms too, but if you can't export, even if Portal 2 is not running, download a Unlocker and check what programm is causing the problems.

I used Lockhunter to find the problem: http://lockhunter.com/?ver=3.1.1.115&vertype=pro&sm=main_window_64&mode=&keystart=&keyend=

If you are worried about Viruses here is the Virustotal search: https://www.virustotal.com/de/file/adea78761f18baaf938f9b5a18ee3b07cb6426f8adfa234f715630741130ee7d/analysis/1491463208/

I hope this helps

**Comment by TeamSpen210** [comment]
This seems to be a bug in Intel's driver, for some reason. I wouldn't be able to fix that.
