### ISSUE TITLE
Add option to change which direction the elevators go

### ISSUE THREAD

**Issue by corrupt21** [BEEmod/BEE2.4#572]
For example, the entry elevator always comes from the bottom and the exit elevators always goes up. It would be nice if we could change which way the elevators go.

**Comment by ZombiePwner1** [comment]
Good suggestion. Also i see you have been improving on your underground hammer maps @corrupt21 keep it up.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/757
