### ISSUE TITLE
THE INSECT'S ARE TAKING BEEMod OVER!!

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2.4#574]
(I understand, the title is not professional, But I needed some wit.)

[The First Bug is confirmed in Aperture Tag](https://youtu.be/EkEAC5zkAaM) OOPS, uploaded wrong video [ and Portal 2](https://cdn.discordapp.com/attachments/287851332289953792/300842256779444224/bandicam_2017-04-10_04-58-58-230.mp4)
I'll explain it now, I enter the command "sv_cheats 1; thirdperson; sv_cheats 0", which activates thirdperson mode, and while in it if I spin my mouse around, It causes the momentum music to play.

angled panels in old aperture's portals can't be walked into https://youtu.be/lmxH0ot8tQA

**Comment by ZombiePwner1** [comment]
The angled panel issue is a bug to do with the player clips on the panel.

**Comment by iEnderMan06** [comment]
@ZombiePwner1 The strangest thing is how you can actually walk through the other portal,

**Comment by iEnderMan06** [comment]
Why did you close it? @LautaroL20

**Comment by TeamSpen210** [comment]
Duplicate
