### ISSUE TITLE
Lighting and Angled Panel Bug, and a suggestion.

### ISSUE THREAD

**Issue by HibblesDayTigre** [BEEmod/BEE2.4#575]
So, I have not exactly seen anything about fixing these bugs in the next release, so I'm sorry if you already know a few of these.

The first bug is it will not let me go through portals on angled panels.  Only most of the time this happens.  
For example I can stand on top of the portal that is on the angled panel.

The second bug, (which may not even be a bug) is the lighting in the bottomless pits.  It's so dark, and it doesn't blend in with the lighter areas above it.

Then there is some very obvious bugs that I am pretty sure are going to be fixed, such as the entrance to BTS chambers and in BTS, cubes are not destroyed when they need to be respawned.

My only suggestion, more of a question, but is there ANYWAY that you could make it so we can have more items in the pallete? Or even a selected number?  So we don't have to leave portal 2, and change our pallete.  This would be so helpful, and it would save me so much time!  But I do realize this would be extremely difficulty to accomplish, but maybe you could give it a shot...?

**Comment by TeamSpen210** [comment]
I cannot change the size of the palette, if I could I would have done that.

**Comment by ZombiePwner1** [comment]
We'd need to get access to the source code to change the size of the pallet.

**Comment by sharpsightkill** [comment]
how do you even make a bottomless pit?

**Comment by ZombiePwner1** [comment]
@sharpsightkill Select the 3D BTS skybox in the beemod menu and place a goo pit and you will get a bottomless pit.

**Comment by LautaroL20** [comment]
You must split each suggestion into separated post, otherwise a good part of them, may never be implemented since its what happens to most of the piled-up suggestions here. Having a single suggestion per post will help developers treating it by separate and close it when it's finally done.
