### ISSUE TITLE
In editor trigger once stairs connection crashes.

### ISSUE THREAD

**Issue by FriskRD** [BEEmod/BEE2.4#577]
I'm using the latst version of BEE2.The problem is when i connect the trigger once to the stairs,it crashes directly.Can it be repaird manualy or in the next release?

**Comment by ZombiePwner1** [comment]
Don't think your able to fix this until next release comes out.

**Comment by LautaroL20** [comment]
Which style where you using during this? Ill gonna check out this.

**Comment by LautaroL20** [comment]
K, tested with the outdated PRL24, and obviously it doesnt happens on Clean Style.

**Comment by LautaroL20** [comment]
This doesn´t happens in any Style, even i tested with coop type of triggers and neither. It´s most likely another item in the map. Can you paste the full console log from the error?

**Comment by LautaroL20** [comment]
As usual with these issues, no response from the author.....Ill leave this closed until we get a response.
