### ISSUE TITLE
Oh Fliderstrix.....Whats now!?!?!?!?!?!?

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#579]
![image](https://cloud.githubusercontent.com/assets/12244376/25072013/715077fc-229b-11e7-87e7-df2de53dd9ce.png)

**Comment by SW50000** [comment]
Did you mean to say "Fliderstrix...Whats Now" instead of the actual voice line in the title?

**Comment by ZombiePwner1** [comment]
@SW50000 @LautaroL20 Doesn't know how to pronounce english words too well. @LautaroL20 Get on steam.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Actually, the Kleiner´s line is not even an english word....

**Comment by ZombiePwner1** [comment]
@LautaroL20 On my version it is it says oh fiddlesticks what now?

**Comment by iEnderMan06** [comment]
![bandicam 2017-04-20 18-42-12-911](https://cloud.githubusercontent.com/assets/26350889/25244555/1b52c132-25f9-11e7-9997-cb97dd3542ba.jpg)
Let's ignore that...
