### ISSUE TITLE
Bee 2.4 Compiler Messing Up My Hammer Playtesting?

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2.4#580]
I decided to remake a map I made a long time ago. But now when ever I compile with hammer the modified bee launcher messes everything up! (The compiler fails) I wish I could get some log info for you but I can't Sorry!

> This time is our time! Back and better then ever! - A defective turret line from the map I am remaking

**Comment by Luke18033** [comment]
Switch VBSP and VRAD to their `_original` versions in Hammer's settings.

**Comment by benjaminpants** [comment]
How?

**Comment by benjaminpants** [comment]
Do I switch from advance mode to simple mode? If you don't feel like explaining leave a link in the tutorial.

**Comment by Luke18033** [comment]
Uh, what? Hammer doesn't have a "simple mode". Go to Tools>Options>Build Programs, the option is there.

**Comment by benjaminpants** [comment]
Re-Open This Thread. It is still not working!
![newvradnotworking](https://cloud.githubusercontent.com/assets/27522994/25106887/e29c6174-2380-11e7-8fab-a5d44f592446.PNG)

^
|
|

Image Download to the Error Log

**Comment by Luke18033** [comment]
![change-programs](https://cloud.githubusercontent.com/assets/19228201/25110710/ee5b3048-239a-11e7-9dc6-97ca21cceb13.png)

**Comment by TeamSpen210** [comment]
You need to delete vbsp, vrad, vbsp_original and vrad_original. They're copies of the BEE2 versions.

**Comment by benjaminpants** [comment]
I think that might be a issue because I think I had bee-mod already installed but I could not find the exe so then I installed 2.2.5 then I downgraded to 2.2.4

**Comment by benjaminpants** [comment]
Do I need to delete the exes? I get it now! I delete the vbsp and the vrad then to use bee mod I will move the bee mod vbsp and the bee mod vrad to a folder so they don't get deleted then run "validate game files" then I will rename the new fresh vbsp and vrad files vbsp_original and vrad_original! Thanks for the help! 
Thanks! @TeamSpen210 @Luke18033 @ZombiePwner1 @LautaroL20 @BenVlodgi 
(Next time when I install a new bee mod a backup the original before I install)
You can now close this thread!
