### ISSUE TITLE
Idea: Force Compile

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2.4#581]
This idea is where when the "Force Compile" option is checked no matter what happens it will be FORCED to compile and load the peti map. Even with errors. This would be good for people who are having issues, and this would be good for development! So you can get them patched so you don't have to use the Force Compile Option
(Basically making it so it can't say "The map had compiling errors" And force it to load)

> Let the force compile be with you!

**Comment by Luke18033** [comment]
What are you referring to by "errors"? If you're talking about placement errors, there's unfortunately nothing we can do - the editor won't export the map. Stupid Valve. If you're talking about errors that occur during compilation, we could allow those, but things would come out broken.

**Comment by ZombiePwner1** [comment]
Lol @Luke18033 I was just about to leave a comment and add the invalid label.

**Comment by TeamSpen210** [comment]
Most of the time when the errors occur, it would result in a very broken map, which wouldn't work right at all. It would probably cause further errors and not produce a map at all.

**Comment by benjaminpants** [comment]
Ok. I know it would not produce a map. I was just thinking it would be good to see if it was really broken. Or the Valve Compiler being stupid. I will close this.

**Comment by benjaminpants** [comment]
Oh its already closed.
