### ISSUE TITLE
Extended Palette / Folders?

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#582]
I just had an idea, since the item system in pr24 is a bit more "clunky" than previous versions (i.e. certain items aren't grouped into one item like they should be): folders/alt. palette buttons. Theoretically, if you were to add a button at the bottom right of the palette, you could program it to switch to a secondary palette. I think this idea was mentioned years ago when BEEMod was still in 1.x stages, but nobody ever saw it happen.

Please take this idea into consideration; BEEMod users like myself will thank you for the time saved while making maps.

**Comment by HugoBDesigner** [comment]
Thing is, if we could dynamically change the palette in-game, we would. We'd even have it contain multiple pages, but since Portal 2's source code is closed, there's nothing we can do.

**Comment by peefTube** [comment]
If you could add it to the palette as an item...?

**Comment by HugoBDesigner** [comment]
You can't change the palette while the game is still open either, that's the issue.

**Comment by peefTube** [comment]
Ah. Okay.
