### ISSUE TITLE
BEE2.4 Causes "Failure To Compile"

### ISSUE THREAD

**Issue by yFera** [BEEmod/BEE2.4#583]
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/door_frame.vmt
patch, (*insert*), 
KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/crusher_back.vmt
patch, (*insert*), 
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_blue.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_autoportal_frame.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_futbol.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun1.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun2.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_portalgun3.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_chamberlock.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198298397107\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,13,6)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 123 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3535, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 300, in load_settings
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1395: ordinal not in range(128)
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3535, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 300, in load_settings
  File "F:\Git\srctools\srctools\property_parser.py", line 303, in parse
  File "C:\Python34\lib\encodings\ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 1395: ordinal not in range(128)

**Comment by LautaroL20** [comment]
Which Style and items were you using when you got the failure to compile?

**Comment by yFera** [comment]
i was lazy to write them down, so i just give a screenshot
![kepkivagas](https://cloud.githubusercontent.com/assets/27724206/25124224/60a1479c-242b-11e7-8ca0-e40002aeb5f5.PNG)

**Comment by LautaroL20** [comment]
Overgrown + Protruding Ped Buttons..... As i suspected. But one more thing left to figure out the cause, did you use the right or left positions of this protruding button into the map?

**Comment by ZombiePwner1** [comment]
@yFera Don't use overgrown protuding pedestal buttons on the left or right position since they're broken. @LautaroL20 Get on steam u wheely.

**Comment by yFera** [comment]
I didn't use them, i just thought they might get useful once.

**Comment by LautaroL20** [comment]
Thats strange then. 

@ZombiePwner1 - I can´t, im working on the Editor Model for my Old Aperture Protruding Buttons.

**Comment by ZombiePwner1** [comment]
@LautaroL20 lol can't i just talk to you while your working on your buttons?

**Comment by yFera** [comment]
This also happens with other styles and items, even in older pre-releases.

**Comment by LautaroL20** [comment]
> yFera: "This also happens with other styles and items, even in older pre-releases."

Uhmm, did you use the Bee2.2.5 Alpha before?

**Comment by yFera** [comment]
yes...

**Comment by LautaroL20** [comment]
Thats the cause then......  Delete the "bin" folder inside the Portal 2 Directory, then verify the game cache files, launch Bee 2.4 and make it to export again. This must work.

**Comment by yFera** [comment]
Thanks, will try it out once I get home.

**Comment by yFera** [comment]
still getting the same error

**Comment by LautaroL20** [comment]
Where did you install Bee2.4? You don´t have to merge the installation files inside the Portal 2 folder, instead install bee2.4 somewhere else since it may conflict with the game files.

If this also does not work, youll have to ask TeamSpen210.

**Comment by yFera** [comment]
it's on my D: drive...

**Comment by LautaroL20** [comment]
@yFera - Get Pre-release 27 (Packages & Application). Also, to ensure everything will work fine, you will have to do the following once installed:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
