### ISSUE TITLE
50's Style issue or just Windows 10 antics? (Sorry for the duplicate, not getting any replies on the other thread)

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#588]
Every time I export to Portal 2, I get an error message saying that **access is denied** to the 50's files. Now, this is definitely an issue with my PC (I'm running Windows 10, which is apparently notorious for this sort of thing), I can tell you that much. However, I'm more concerned about **how the heck I'm going to fix this issue.** Going full admin in BEE2 doesn't help (**WinError 5**). The error message goes as follows (cuts off as well, that really alarms me): 
![image](https://cloud.githubusercontent.com/assets/26728974/25321607/bdcddec0-2864-11e7-8feb-49f2e02c7cfd.png)

Should I re-install a package or am I just plain screwed?

EDIT: This pops up no matter what I do. Trying to do anything in the 50's style results in a "map failed to build" error message.

**Comment by TeamSpen210** [comment]
Open Task Manager, and kill `igfxem.exe` if it exists (this Intel process might be causing the issue). If that's not running, try deleting those folders it's copying to.
