### ISSUE TITLE
Can't build any puzzle I make,even without anything on them.

### ISSUE THREAD

**Issue by RataDeOrdenador** [BEEmod/BEE2.4#589]
This is the error I get (I think),and I really don't know what to do. I've been trying to install BeeMod2.4 for days,but when I can do it,I keep getting the "can't build your puzzle" problem.

I even have the default set of items BeeMod gives me.

> VBSP succeeded.
> 
> [INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
> [INFO] cond.core.import_conditions(): Imported all conditions modules!
> [INFO] vbsp.main(): Map path is "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> [INFO] vbsp.main(): New path: "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [INFO] vbsp.main(): Clearing inject/ directory..
> [INFO] vbsp.main(): PeTI map detected!
> [INFO] vbsp.main(): Loading settings...
> [WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'bottomless_pit': '0', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
> [INFO] vbsp.load_settings(): Settings Loaded!
> [INFO] vbsp.load_map(): Parsing Map...
> [INFO] vbsp.load_map(): Reading Map...
> [INFO] vbsp.load_map(): Loading complete!
> [INFO] vbsp.get_map_info(): Forcing elevator spawn!
> [INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
> [INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
> [INFO] vbsp.get_map_info(): Game Mode: SP
> [INFO] vbsp.get_map_info(): Is Preview: False
> [INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
> [INFO] brushLoc.read_from_map(): Air filled!
> [INFO] cond.core.check_all(): Checking Conditions...
> [WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
> [INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
> [INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
> [INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
> [INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
> [INFO] vbsp.set_elev_videos(): Elevator type: FORCE
> [INFO] voiceLine.add_voice(): Adding Voice Lines!
> [WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
> [WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
> [INFO] voiceLine.add_voice(): Adding Base instance!
> [INFO] voiceLine.add_voice(): Quote events: []
> [INFO] voiceLine.add_voice(): No responses data..
> [INFO] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
> [INFO] voiceLine.add_quote(): Adding quote: "Line"
>  | 	{
>  | 	"ID" "GENERIC_1"
>  | 	"choreo" "scenes/npc/glados/a2_triple_laser01.vcd"
>  | 	}
>  |_
> 
> [INFO] voiceLine.add_quote(): End-commands: 
> [INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
> [INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
>  | 	{
>  | 	"ID" "GENERIC_5"
>  | 	"Choreo" "scenes/npc/glados/dlc1_leaderboard07.vcd"
>  | 	}
>  |_
> 
> [INFO] voiceLine.add_quote(): End-commands: 
> [INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/9 quotes..
> [INFO] voiceLine.add_voice(): 1 Mid quotes
> [INFO] voiceLine.add_quote(): Adding quote: "Line"
>  | 	{
>  | 	"Name" "Cave Reactions"
>  | 	"File" "clean/cave_reaction.vmf"
>  | 	}
>  |_
> 
> [INFO] voiceLine.add_voice(): Done!
> [INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
> [INFO] vbsp.set_player_portalgun(): Setting Portalgun:
> [INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
> [INFO] vbsp.set_player_portalgun(): Done!
> [INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
> [INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
> [INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=3069, misses=306, maxsize=256, currsize=256)
> [INFO] cond.core.check_all(): Style Vars: {'bee_show_trigger': False, 'funnelallowswitchedlights': True, 'rexcubepelletfizzle': False, 'unlockdefault': False, 'nomidvoices': False, 'multiversecave': True, 'fixfizzlerbump': False, 'allowgoomist': True, 'restartonexit': True, 'doorcameras': True}
> [INFO] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
> [INFO] vbsp.add_extra_ents(): Adding Music...
> [INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
> [INFO] vbsp.change_ents(): Editing Other Entities...
> [INFO] vbsp.fixup_goo_sides(): Changing goo sides...
> [INFO] vbsp.fixup_goo_sides(): Done!
> [INFO] vbsp.change_brush(): Editing Brushes...
> [INFO] vbsp.change_brush(): Make Bottomless Pit: False
> [INFO] vbsp.change_overlays(): Editing Overlays...
> [INFO] vbsp.change_trig(): Editing Triggers...
> [INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
> [INFO] vbsp.collapse_goo_trig(): Done!
> [INFO] vbsp.change_func_brush(): Editing Brush Entities...
> [INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
> [INFO] vbsp.remove_static_ind_toggles(): Done!
> [INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
> [INFO] vbsp.make_packlist(): Making Pack list...
> [INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
> [INFO] vbsp.make_packlist(): Packlist written!
> [INFO] vbsp.save(): Saving New Map...
> [INFO] vbsp.save(): Complete!
> [INFO] vbsp.run_vbsp(): Calling original VBSP...
> [INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
> [INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
>  | 2 threads
>  | materialPath: C:\Program Files\Steam\steamapps\common\Portal 2\portal2\materials
>  | Loading C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
>  | ConVarRef gpu_level doesn't point to an existing ConVar
>  | fixing up env_cubemap materials on brush sides...
>  | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
>  | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (1)
>  | Processing areas...done (0)
>  | Building Faces...done (0)
>  | Chop Details...done (0)
>  | Find Visible Detail Sides...
>  | Merged 408 detail faces...done (0)
>  | Merging details...done (0)
>  | FixTjuncs...
>  | PruneNodes...
>  | WriteBSP...
>  | done (0)
>  | writing C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
>  | done (0)
>  | Finding displacement neighbors...
>  | Finding lightmap sample positions...
>  | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
>  | Building Physics collision data...
>  | done (1) (466685 bytes)
>  | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
>  | Compacting texture/material tables...
>  | Reduced 2506 texinfos to 446
>  | Reduced 50 texdatas to 45 (1428 bytes to 1286)
>  | Writing C:/Program Files/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
>  | 
>  | nummapplanes:     (  8412 / 65536 )
>  | nummapbrushes:    (  1259 /  8192 )
>  | nummapbrushsides: ( 10940 / 65536 )
>  | num_map_overlays: (     2 /   512 )
>  | nummodels:        (    41 /  1024 )
>  | num_entities:     (   290 / 16384 )
>  | 
>  | 9 seconds elapsed
>  | CDynamicFunction: Loading library 'Kernel32.dll' (74DE0000)
>  | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 774CD050
>  | CDynamicFunction: Closing library 'Kernel32.dll' (74DE0000)
>  |_
> 
> [INFO] vbsp.run_vbsp(): VBSP Done!
> [INFO] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('1259', '8192'), 'entity': ('290', '16384'), 'overlay': ('2', '512')}
> [INFO] BEE2_config.save(): Saving changes in config "C:\Users\Manuela\Desktop\BeeMod\config/compile.cfg"!
> [INFO] vbsp.make_vrad_config(): Generating VRAD config...
> [INFO] vbsp.main(): BEE2 VBSP hook finished!
> 
> 
> [PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 17065 (ms)
> 
> VVIS succeeded.
> 
> Valve Software - vvis.exe (Aug 26 2015)
> 2 threads
> reading c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
> reading c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.prt
>   87 portalclusters
>  122 numportals
> BasePortalVis:       0...1...2...3...4...5...6...7...8...9...10 (0)
> PortalFlow:          0...1...2...3...4...5...6...7...8...9...10 (0)
> Optimized: 0 visible clusters (0.00%)
> Total clusters visible: 1595
> Average clusters visible: 18
> Building PAS...
> Average clusters audible: 24
> visdatasize:1997  compressed from 2784
> writing c:\program files\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
> 0 seconds elapsed
> CDynamicFunction: Loading library 'Kernel32.dll' (74DE0000)
> CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 774CD050
> CDynamicFunction: Closing library 'Kernel32.dll' (74DE0000)
> 
> 
> [PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 19525 (ms)
> 
> VRAD failed.
> 
> [INFO] vrad.main(): BEE2 VRAD hook started!
> [INFO] vrad.main(): Map path is C:\Program Files\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
> [INFO] vrad.load_config(): Loading Settings...
> [INFO] vrad.load_config(): Config Loaded!
> [INFO] vrad.main(): Final status: is_peti=True, edit_args=True
> [INFO] vrad.pack_content(): Files to pack:
> [INFO] vrad.pack_content():  # "scripts/vscripts/bee2/video_splitter_specific.nut"
> [INFO] vrad.pack_content(): Injected files:
> [INFO] vrad.pack_content():  # "scripts/vscripts/BEE2/auto_run.nut"
> [INFO] vrad.pack_content(): Packing Files!
> [INFO] vrad.pack_content(): Injecting "scripts/vscripts/BEE2/auto_run.nut" into packfile.
> [INFO] vrad.pack_content(): Packing complete!
> [INFO] vrad.mod_screenshots(): Using automatic screenshot!
> [INFO] vrad.mod_screenshots(): No Auto Screenshot found!
> [INFO] vrad.mod_screenshots(): Cleaning up screenshots...
> [INFO] vrad.mod_screenshots(): Done!
> [INFO] vrad.mod_screenshots(): Using PeTI screenshot!
> [INFO] vrad.mod_screenshots(): Making "..\portal2\puzzles\76561198071291263\untitled.jpg" replaceable...
> [ERROR] (unknown file).(unknown function)(): Uncaught Exception:
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
>   File "vrad.py", line 992, in <module>
>   File "vrad.py", line 977, in main
>   File "vrad.py", line 866, in mod_screenshots
>   File "F:\Git\BEE2.4\src\utils.py", line 495, in unset_readonly
> PermissionError: [WinError 5] Acceso denegado: '..\\portal2\\puzzles\\76561198071291263\\untitled.jpg'
> Traceback (most recent call last):
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
>   File "vrad.py", line 992, in <module>
>   File "vrad.py", line 977, in main
>   File "vrad.py", line 866, in mod_screenshots
>   File "F:\Git\BEE2.4\src\utils.py", line 495, in unset_readonly
> PermissionError: [WinError 5] Acceso denegado: '..\\portal2\\puzzles\\76561198071291263\\untitled.jpg'

**Comment by TeamSpen210** [comment]
We can't do much inside the BEE to fix permission issues.

**Comment by peefTube** [comment]
I remember WinError 5. It's a freaking pain.

From what I know, there's 2 possible fixes. Both are temporary and will have to be re-activated each time (from my understanding, of course).

The first fix is to press the following combination: `Windows + X` and select `Command Prompt (Admin)`. Type in the following: `net user administrator enable:yes`. Press `Enter`. To ensure that this works, repeat the process, this time typing in `net user administrator /active:yes`.

IF that doesn't work, open Task Manager. Go to the Details tab (if you're using Windows 10, it may be processes or tasks or something for Windows 7) and look for `igfxEM.exe`. End that task (a warning will pop up, you can ignore that if you have a good anti-virus). This will disable your Intel chips from interfering with your files. **This won't work if you have AMD/ATI only.**

Thanks to @TeamSpen210 for telling me about the second one.
