### ISSUE TITLE
Beemod crashes after exporting the Aperture Tag palette

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#590]
![Image](https://cloud.githubusercontent.com/assets/12244376/25562041/b0dc467a-2d50-11e7-9f30-da4a4827648b.png)

**Comment by TeamSpen210** [comment]
Make that BEE2 folder, so it can write to it.

**Comment by TeamSpen210** [comment]
Actually, this shouldn't really be able to happen - somehow you're missing the BEE2 instances folder, and it hasn't copied to there.
