### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2.4#594]
1. world portals
2. triggers for objects (same as regular triggers but activate when something passes through it like a cube)
3. ability to put in custom music
4. static half panel able to turn on and off
5. ability to place things on flat blocks, angled blocks, etc
6. SR Latch ingame item has NOT gate textures?
7. portalable piston and track platform
8. ability to place partial blocks on each other
9. ability to place catwalks in the air
10. allow button to activate a trigger autosave
11. Make lazer and catchers have a corner position (idk if possible)
12. ability to add custom elevator videos
13. make monitor model not futbol spawner/socket
14. Sign that can tell the player things (Type stuff into it)
15. Control conveyor belt speed with timer

**Comment by ZombiePwner1** [comment]
@G3neralGrant some of these aren't possible to implement signs that can tell players things was featured in the educational version of the game but that's part of the custom code on the edu version.

**Comment by awesomedoctorx3** [comment]
There's an educational version of Portal?! I NEED TO SHOW THIS TO MY TEACHER

**Comment by ZombiePwner1** [comment]
@awesomedoctorx3 It doesn't work anymore I found a YouTube video with a download link for the files the game itself loads but crashes when ur on the P2 logo.

**Comment by TeamSpen210** [comment]
Probably because it's a download of it.

**Comment by Luke18033** [comment]
1. Already suggested (BEEmod/BEE2-items#574).
2. Already going to be implemented.
3. You can already do this, make a custom package and put the music in it.
4. Already suggested (BEEmod/BEE2-items#1456).
5. Not possible, unfortunately.
6. There isn't a proper model for it yet, so the NOT gate takes its place.
7. Already suggested (BEEmod/BEE2-items#95 and BEEmod/BEE2-items#674).
8. Also not possible.
9. Not possible either.
10. Already suggested (BEEmod/BEE2-items#1077).
11. Already suggested (BEEmod/BEE2-items#1479).
12. Apparently you can't pack videos into maps.
13. Already done in the dev version.
14. Already suggested (BEEmod/BEE2-items#531)
15. Could be done.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#1905
