### ISSUE TITLE
BEE2.4pr24 fails to export options to Portal 2

### ISSUE THREAD

**Issue by kinker31** [BEEmod/BEE2.4#595]
Error Message:
Copying compiler file vbsp.exe failed. Ensure the PORTAL 2 is not running.

Output from log:
[I] gameMan: Exporting Items and Style for "PORTAL 2"!
[I] gameMan: Style = BEE2_CLEAN
[I] gameMan: QuotePack = BEE2_WHEATLEY
[I] gameMan: Music = VALVE_FRANKENTURRETS
[I] gameMan: Elevator = VALVE_APERTURE_LOGO
[I] gameMan: Skybox = BEE2_CLEAN
[I] gameMan: Should refresh: True
[I] gameMan: Cache invalid - copying..
[I] gameMan: Exporting "QuotePack"
[I] packageLoader: C:\Users\Donovan\Downloads\Roms, Emulators, and More\BEE2.4_pr24_win\bin\..\config\voice\BEE2_WHEATLEY.cfg
[I] packageLoader: No normal voice config!
[I] packageLoader: C:\Users\Donovan\Downloads\Roms, Emulators, and More\BEE2.4_pr24_win\bin\..\config\voice\MID_BEE2_WHEATLEY.cfg
[I] packageLoader: No MidChamber voice config!
[I] packageLoader: C:\Users\Donovan\Downloads\Roms, Emulators, and More\BEE2.4_pr24_win\bin\..\config\voice\RESP_BEE2_WHEATLEY.cfg
[I] packageLoader: No Responses voice config!
[I] gameMan: Exporting "StyleVPK"
[I] packageLoader: Sound cache: j:\portal 2\portal2_dlc3\maps\soundcache\_master.cache
[I] packageLoader: Written 1 files to VPK!
[I] gameMan: Exporting "EditorSound"
[I] gameMan: Exporting "PackList"
[I] packageLoader: Writing packing list!
[I] gameMan: Exporting "StyleVar"
[I] gameMan: Exporting "Music"
[I] gameMan: Exporting "Elevator"
[I] gameMan: Exporting "Skybox"
[I] gameMan: Exporting "BrushTemplate"
[I] gameMan: Exporting "Item"
[I] gameMan: Exporting "ItemConfig"
[I] gameMan: Backing up original Editoritems!
[I] gameMan: Editing Gameinfo!
[I] gameMan: Writing instance list!
[I] gameMan: Writing Editoritems!
[I] gameMan: Writing VBSP Config!
[I] gameMan: Copying Custom Compiler!
[I] gameMan: 	* compiler/python34.dll -> bin/python34.dll
[I] gameMan: 	* compiler/python34.zip -> bin/python34.zip
[I] gameMan: 	* compiler/unicodedata.pyd -> bin/unicodedata.pyd
[I] gameMan: 	* compiler/vbsp.exe -> bin/vbsp.exe

Pallete Used: ![capture](https://cloud.githubusercontent.com/assets/16625998/25647461/a48856d2-2f87-11e7-996f-e9a7fadf876e.PNG)

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
