### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by TessilnTheMaskMaker** [BEEmod/BEE2.4#596]
Whenever I try to place Futbols or Chamberlocks it generates the error texture. Also, when Rocket Turrets fire the rockets will be invisible. Chamberlocks will also generate an invalid position error even if the volume requirements are satisfied.

**Comment by LautaroL20** [comment]
This is a Bee2-Items issue. I have splitted them in three parts.

https://github.com/BEEmod/BEE2-items/issues/1908
https://github.com/BEEmod/BEE2-items/issues/1909
https://github.com/BEEmod/BEE2-items/issues/1910
