### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by TessilnTheMaskMaker** [BEEmod/BEE2.4#597]
1. Adding adhesion gel.
2. Being able to place entities on ~~the angled~~ any side of angle blocks (lasers, gel splats, etc.)
3. Adding core receptacles and cores with customizable eyes.

**Comment by Luke18033** [comment]
1. Not possible in PTI.
2. See BEEmod/BEE2-items#1485.
3. Already been suggested many times, probably won't be added.
