### ISSUE TITLE
help with uninstalling?

### ISSUE THREAD

**Issue by helpihavebug** [BEEmod/BEE2.4#598]
i was dumb and first got bee2.4 but then bee 2.2 or something. what do i do?

**Comment by Luke18033** [comment]
Which version do you want to uninstall? For BEE2.4, remove the game from the games list. That'll automatically reset the puzzlemaker to default, and remove all BEE2.4-related files. BEE2.2 might have some uninstall program, but I'm not sure.

**Comment by helpihavebug** [comment]
bee 2.2.

**Comment by Luke18033** [comment]
You really don't need to uninstall it at all - BEE2.4 was specifically designed to replace BEE2.2 stuff without any issues. It doesn't work the other way though.

**Comment by helpihavebug** [comment]
i was dumb and first installed bee 2.4 but then bee 2.2. i then keep getting build errors no matter what. what do i do?

**Comment by Luke18033** [comment]
Try validating the files.

**Comment by helpihavebug** [comment]
i tried both validating and uninstalling and reinstalling, keep getting build errors. if i try to remove the portal 2 folder manually,(uninstalling only removes it from library)it says i need admin permission.

**Comment by helpihavebug** [comment]
...i actually need help here.

**Comment by TeamSpen210** [comment]
Backup your puzzles first (Portal 2/portal2/puzzles/). But it seems like you might be havving the weird bug where stuff gets the wrong permissions.

**Comment by peefTube** [comment]
> Backup your puzzles first (Portal 2/portal2/puzzles/). But it seems like you might be havving the weird bug where stuff gets the wrong permissions.

This is always fixed by eliminating the igfxEM.exe service in Task Manager - Steam gets locked up by this service, preventing file modifications, insertions, and deletions.

**Comment by TeamSpen210** [comment]
Intel has released a [driver update](https://downloadcenter.intel.com/download/26772) with a fix.

**Comment by TeamSpen210** [comment]
Did what exactly? Try verifying the game cache.
