### ISSUE TITLE
Splash Screen keeps showing the same two pictures everytime beemod is launched 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#600]
Implement an intelligent system to ensure it will display a different screenshot each time Beemod is launched, since it only shows the Luke18033´s Screenshot and the one i commited......

**Comment by LautaroL20** [comment]
Everytime i launch Beemod, it only shows the Luke18033´s pict and the one i commited......

**Comment by Luke18033** [comment]
You must just be missing most of the images, my version shows every image in the folder.

**Comment by ZombiePwner1** [comment]
@Luke18033 can I see your pic?

**Comment by Luke18033** [comment]
![lukesplash](https://raw.githubusercontent.com/BEEmod/BEE2.4/28e473e3b3adbb46a25d91ceb035d73a7a80ae6a/images/splash_screen/abandoned-testing-track.jpg)

**Comment by TeamSpen210** [comment]
It should choose a random image from that folder. It might be though that mathematical random isn't what humans expect for random. I might go and use a more advanced system, so it never picks an image twice until it has used up all other images.

**Comment by ZombiePwner1** [comment]
Oh never mind I've seen that image I thought you had your own custom image.

**Comment by LautaroL20** [comment]
This seems to be fixed now.

PS: I can not add labels right now since i am using a Potato PC due to my main PC died recently, while i build a new one, if you can apply the "fixed" label for me i would thank you. The Potato PC is using Windows XP with an outdated web explorer.
