### ISSUE TITLE
Change some of the Entry / Exit Names that have 'Corridor' as the Name to something More Specific  |  Add a Preview Image

### ISSUE THREAD

**Issue by hop193** [BEEmod/BEE2.4#602]
Portal 1 style has 6 of these 'Corridor' options. The seventh is the only one that doesn't.

Please, change it something more specific so we can get an idea of what it is.
Better yet, add a preview image to see it in action.

**Comment by Luke18033** [comment]
Portal 1 corridors 2-6 are identical to 1. I'm working on 2, but I don't think it will make it into the next release.

**Comment by hop193** [comment]
OK.

**Comment by TeamSpen210** [comment]
The ones named 'Corridor' are basically going to be replaced.

**Comment by hop193** [comment]
@TeamSpen210 said:

> The ones named 'Corridor' are basically going to be replaced.

Oh, OK! Cool.

**Comment by LautaroL20** [comment]
Preview images will be finally implemented in next Pre-Release 30.  Source (not the engine tho): https://github.com/BEEmod/BEE2-items/commit/c888a36fcd2daaf14560a08e6bdbe09862f1e3ed
