### ISSUE TITLE
Pre-Release 26 Is not starting with the Beemod Palette.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#605]
![Image prl25](https://cloud.githubusercontent.com/assets/12244376/25777169/a5ce46ce-32ab-11e7-8d31-819d41844442.png)

**Comment by TeamSpen210** [comment]
That's not the Tag palette. You might have some old files in the palette folder.

**Comment by LautaroL20** [comment]
> TeamSpen210 Said: "You might have some old files in the palette folder."

Nope! 

As for if its the AT Palette or not, i can´t say but since it actually had the Paint Gun Activation Field i thought it were the AT Palette. 

Anyways, the point here is that Bee PRL25 is not starting with the Beemod default palette when you launch it. Note that before reporting this issue, i make sure to delete all possible Bee´s associated files from the Portal 2 Directory, including Editoritems. Then launched the PRL25 and it always shows that incomplete and wrong palette.

**Comment by LautaroL20** [comment]
This annoyiance also happens with the PRL26.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
