### ISSUE TITLE
This is not another issue of PR25

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2.4#608]
![spencer](https://cloud.githubusercontent.com/assets/25024629/25777470/d00db998-32b4-11e7-8646-419b9ca6edee.png)

I have no idea if this is duplicated.

**Comment by ZombiePwner1** [comment]
Get the config files from prl 24 and replace the the prl 25 ones with prl 24. Also duplicate of https://github.com/BEEmod/BEE2.4/issues/603

**Comment by Konata-Chan** [comment]
Ok I re-downloaded it and now it works fine
