### ISSUE TITLE
The Export Button in File Context Menu is always unclickable

### ISSUE THREAD

**Issue by ImDaveead** [BEEmod/BEE2.4#610]
It may not be always unclickable, but I should be able to click it after creating my setup... Right?

![image](https://cloud.githubusercontent.com/assets/24465214/25777968/ec4194d2-32bd-11e7-94ed-261a6a7453e6.png)

At least the other Export Button is usable.
![image](https://cloud.githubusercontent.com/assets/24465214/25777961/cb67fabc-32bd-11e7-82a3-e1f765e866ce.png)

(this was not the case in preview 24)

**Comment by TeamSpen210** [comment]
I pretty much rewrote how exporting and file extraction works, I missed fixing that button.

**Comment by iEnderMan06** [comment]
Why not close the issue instead of adding a label?

**Comment by Luke18033** [comment]
It'll be closed once the update is released.

**Comment by iEnderMan06** [comment]
I see, sorry.
