### ISSUE TITLE
Tractor Beam Polarity Connection will not build.

### ISSUE THREAD

**Issue by sloppysteve** [BEEmod/BEE2.4#611]
In the latest release the tractor beam has an issue with the polarity connection to any activator.
When there is any connection to the tractor beam polarity I get a build error.

**Comment by TeamSpen210** [comment]
I thought I fixed that...

**Comment by sloppysteve** [comment]
Byzarru has the same issue.

**Comment by Byzarru** [comment]
[I've opened this up on Bee2-items](https://github.com/BEEmod/BEE2-items/issues/1943), I posted the log there.

**Comment by TeamSpen210** [comment]
It's an app issue.

**Comment by markd0811** [comment]
I am also experiencing this issue - build worked without BEE, but not after exporting BEE items to puzzlemaker. Specifically, I used a pedestal button on a timer of 10 seconds to control polarity. No build. :(

**Comment by markd0811** [comment]
I am also now experiencing build errors with multiple tractor beams' active state trigger connections:

If two tractor beams (both blue) have active state connections, the puzzle fails to build.

**Comment by markd0811** [comment]
... And build failure continues even when I disconnect one funnel from its input. I can no longer pin down a single source for the problem. :P

**Comment by WhoozYerBuddy** [comment]
If I want a connected funnel in a puzzle do I need to revert to PR24?  Is there any other patch that I can do to get a connected funnel working and keep PR25?

**Comment by LautaroL20** [comment]
Does the commit: https://github.com/BEEmod/BEE2.4/commit/015f239a81849c86338929b26691a5e7f647e802 fix this issue?

**Comment by TeamSpen210** [comment]
Yes.
