### ISSUE TITLE
Crash from pressing escape in the 'Configure Character's Voice Lines' menu

### ISSUE THREAD

**Issue by ImDaveead** [BEEmod/BEE2.4#613]
If you open the window to toggle certain lines of the Voice (found in Export Options, click the symbol left of the voice name), and press the `escape` key, it crashes.

```
Traceback (most recent call last):
  File "C:\Users\Spencer Brown\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1699, in __call__
TypeError: wm_withdraw() takes 1 positional argument but 2 were given
```

The menu I'm talking about
![The Configure Lines Menu](https://cloud.githubusercontent.com/assets/24465214/25874511/e6dbfde6-34e0-11e7-9a49-a0064c3af8ad.png)

**Comment by TeamSpen210** [comment]
Ok, easily fixed. Whoops.
