### ISSUE TITLE
Selecting the "Carl Kenner" author tag causes the tag menu and items to glitch out

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#614]
GIF:
![tag_menu_bug](https://cloud.githubusercontent.com/assets/19228201/25879244/6e699440-34e5-11e7-8899-bb901ec23f73.gif)

**Comment by TeamSpen210** [comment]
Poor Carl.

**Comment by Luke18033** [comment]
Probably some others too.

**Comment by ZombiePwner1** [comment]
Well this release needs alot of bug fixes.

**Comment by ZombiePwner1** [comment]
Please, someone who inserts The X Files Theme song here.....

**Comment by LautaroL20** [comment]
> ZombiePwner1 Said: "Please, someone who inserts The X Files Theme song here....."

Okay, there you go: https://www.youtube.com/watch?v=HQoRXhS7vlU

**Comment by HugoBDesigner** [comment]
Poor Carl.

**Comment by Luke18033** [comment]
Poor Carl...
