### ISSUE TITLE
Add Tips to Splash Screen

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#615]
Like this (with example tip):
![bee2_splash_tip_demo](https://cloud.githubusercontent.com/assets/19228201/25880145/84366910-34ea-11e7-9253-a7616f87bdf4.png)

**Comment by TeamSpen210** [comment]
That's doable fairly easily, but it does require we have tips to use.

**Comment by TeamSpen210** [comment]
Although... it'd make sense to put those into the packages (so you don't get tips for irrelevant items), but then it'd have to wait until those are loaded.

**Comment by Luke18033** [comment]
Maybe put them on the export window instead?

**Comment by LautaroL20** [comment]
Nice suggestion!

**Comment by TeamSpen210** [comment]
I think it'll be on the splash screen, it can just show up after thr 'Loading Packages' bar (which is pretty fast).

**Comment by Luke18033** [comment]
They could probably just be defined in `info.txt`.

**Comment by HugoBDesigner** [comment]
I thought as much, but then I realized that, since packages are independent, modular things that can be updated at different rates, it wouldn't work for all items

**Comment by LautaroL20** [comment]
Tips could probably just be defined in `info.txt`

Indeed, so we can re-edit them anytime. Also it would be good to have two blocks each one with a different Tip, inside the same .txt file.

**Comment by TeamSpen210** [comment]
That's what I meant. And I'll have tha app specially read those in first, before other objects in the packsges to ensure we show them early.

**Comment by markd0811** [comment]
Awesomesauce.

**Comment by TeamSpen210** [comment]
But we need actual tips to be shown...

**Comment by markd0811** [comment]
"Want cubes to be destroyed on contact with energy pellets (like in
Rexaura)? Check the "pellets" dropdown of the "items section of the
style/item properties window!" It's a tad long, but I don't know how to say
it more quickly.

**Comment by markd0811** [comment]
"TIP: Is something missing? Comment on our Github forums!"

**Comment by Luke18033** [comment]
I don't think this is really necessary.
