### ISSUE TITLE
Voice Lines Not Implemented

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2.4#617]
It does not have some voice lines (sometimes none) for caroline, portal 1 glados, BTS announcer, & I think that is it.

**Comment by ZombiePwner1** [comment]
Portal 1 GLaDOS's voicelines haven't been included yet

**Comment by iEnderMan06** [comment]
Then don't add it to a release if it's not even in there. 👎

**Comment by Konclan** [comment]
Duplicate of BEEmod/BEE2-items#389
