### ISSUE TITLE
Problem With The Unstationary Scaffold Items

### ISSUE THREAD

**Issue by HelloIamapersonthatisalive** [BEEmod/BEE2.4#618]
While using the 60s theme I found that whenever using the Unstationary Scaffold Piston/Wall Emitter there is an error with building the puzzle.

**Comment by TeamSpen210** [comment]
This issue was moved to BEEmod/BEE2-items#1951

**Comment by HelloIamapersonthatisalive** [comment]
Here's the log if you need it VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_60s'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Exit (4)
[INFO] vbsp.mod_entryexit(): Using random SP Entry (7)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (13 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "BEFORE ENTRY": 1/1 quotes..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 0/4 quotes..
[INFO] voiceLine.find_group_quotes(): Line "Calcium Coffee" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "It's Going To Be Coal" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "Throwing Science At The Wall" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "Peanut Water Blood" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "Control Group Kepler-Seven" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "Remember Which Skin Is Yours" is disabled..
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/7 quotes..
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/1 quotes..
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['observationgrate', 'spawn_dual', 'obsworldportal', 'pedestalbutton']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2827, misses=293, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'unlockdefault': True, 'rexcubepelletfizzle': True, 'restartonexit': True, 'allowgoomist': True, 'retro_voice_pre_line': False, 'bee_show_trigger': False, 'funnelallowswitchedlights': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/50s/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.clump_walls(): Clumping: 160 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/underground_woodwall003c.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | Could not open instance file instances/BEE2/50s/items/scaffold/piston.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

It Seems I'm Missing Some Files
