### ISSUE TITLE
Pre-Release 25 Keeps skipping the resources export no matter if "Preserve Directories" is disabled, or even restarting the App

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#620]
It will only export full resorces after installing the PRL25 for first time, and after that it will keep skipping it, no matter what.

_________________________________________________________________________

![Image](https://cloud.githubusercontent.com/assets/12244376/25979018/4da780c4-369c-11e7-9ded-7c7989f168bb.png)

**Comment by TeamSpen210** [comment]
That's intended (hopefully). It's detecting that the packages haven't changed since last export, and skipping it. Click the button in 'General' to force it to re-export. Are you using zipped packages or from the repro?

**Comment by LautaroL20** [comment]
>TeamSpen210 Said: "Are you using zipped packages or from the repro?" 

I´m using the entirely Development Version that you helped me to install a long time ago via Steam, and that doesn´t have any of these bugs at all (the ones that aparently were fixed in Dev a time ago, but still pressent in PRL25) and also the bug where the App doesn´t launch with the Bee´s Palette (https://github.com/BEEmod/BEE2.4/issues/605)

I only just wanted to help out finding bugs in the Publuc Release 25.  Respect to this issue, it can be closed since it seems to be intended as you said.

**Comment by TeamSpen210** [comment]
In the case of unzipped files, it should extract every time (this bypasses the check).
