### ISSUE TITLE
Testing Elements

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2.4#621]
I would like to see a way to make rattmann dens.
Maybe BTS wheatley
how do you make stairs in catwalks & how to do catwalks
add invisible blocks

**Comment by markd0811** [comment]
Whatever happened to the rexaura cube destroyed on contact with energy pellets? I can't find it in Prerelease 25.

**Comment by Luke18033** [comment]
It's been moved to the Items tab, for obvious reasons.

**Comment by markd0811** [comment]
OH THANK YOU! I really appreciate that you got back so fast! Found the
option.

**Comment by Endermage77** [comment]
1. I'll let someone better qualified answer that one.
2. Some additional Wheatley lines would be nice.
3. The catwalks are created by connecting two catwalk items with the connector gizmo thingy, and they automatically connect no matter where they are
4. Assuming you mean invisible blocks that can have stuff placed on them; that mechanic only works with glass. Invisible glass would be a better idea.

**Comment by Luke18033** [comment]
1. Already been suggested, probably won't be added.
2. Already been suggested
3. Place multiple catwalks and connect them together. Corners will be generated where the items were placed. See the right-click menu for additional info.
4. already been suggested.
