### ISSUE TITLE
Norton removed vbsp.exe because of SONAR.ProcHijack!g11

### ISSUE THREAD

**Issue by RainerHilmer** [BEEmod/BEE2.4#622]
I tried this new release (I still was on Bee2 alpha before), compiled a new items list, created a small test chamber with some of the new items and as I tried to render the chamber, Norton removed vbsp.exe because of SONAR.ProcHijack!g11.

**Comment by TeamSpen210** [comment]
You'll need to exclude it from antivirus then, it might be picking up on the BEE2 compiler doing stuff kinda similar to what viruses do. What it does is modify the map, then call the original compiler to do the actual compilation. That is what a program might do to substitute another, but that's what you actually want.

**Comment by RainerHilmer** [comment]
Thanks for the explanation. I just wanted to make sure I don't mess up my PC. :)
