### ISSUE TITLE
Item Randomizer will add items that require Unlock Default Items enabled, even if the stylevar is off

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#623]
The title says it all.

Edit: Tested in release version, may already be fixed in dev. Also, before anyone gets confused, this is NOT an items issue.

**Comment by TeamSpen210** [comment]
That's a fun oversight. Maybe I should make it read the items shown on the list, so it obeys filters as well.

**Comment by Luke18033** [comment]
Yes, do that. I also had an idea for a "smart randomizer" that will force a certain item to be present if another item is (for example, the Fizzler Output Relay would always be added when fizzlers that required it were present).
