### ISSUE TITLE
Puzzlemaker Pellet launcher and catcher sound FX too loud

### ISSUE THREAD

**Issue by markd0811** [BEEmod/BEE2.4#625]
Hello,
Working with rexaura elements in BEEMOD is a joy, but the sounds of pellet shooters and catchers are quite jarring, as they are much louder than other puzzlemaker sounds. Could you guys turn them down a bit? Thanks!

**Comment by snorepion** [comment]
Also, crushers are incredibly loud when you right-click them. It's pretty jarring when the ambient noise of the puzzlemaker is interrupted by a huge crash.
