### ISSUE TITLE
Radiative Flux Rectangle outputs bug

### ISSUE THREAD

**Issue by actuallydamien** [BEEmod/BEE2.4#629]
i don't know if it is the same for everyone else, but in my game for some reason the Radiative Flux Rectangle doesn't make outputs at all, as seen in the screenshot below.
![20170517170140_1](https://cloud.githubusercontent.com/assets/28715380/26165251/fabb0bba-3b37-11e7-8579-ad312be80905.jpg)
if it isn't the same for everyone, can anybody tell me how to fix this?

**Comment by Luke18033** [comment]
Place the Fizzler Output Relay item over one of the emitters, and connect that to whatever you want to activate.

**Comment by TeamSpen210** [comment]
For why this is the case, unfortunately outputs on fizzler items don't work properly.
