### ISSUE TITLE
How Do You...

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2.4#633]
I am wondering how do you trigger something & trigger it again later. I mean like you are on a excursion funnel & suddenly, it stops, however, when you were walking before it turned on. please tell  me how.

**Comment by peefTube** [comment]
I'd use several TRIGGER_MULTIPLES in combination with hidden logic gates to achieve this result, although I'd like to ask why you'd need a feature like this.

**Comment by ZFM2004** [comment]
rollercoasters in tests or death traps

**Comment by peefTube** [comment]
Ahh. Makes sense. Although a sideways funnel will need something above it that you can place trigger items on, so that way it'll actually work. Otherwise, I can't think of any way to do it.

**Comment by ZFM2004** [comment]
I would Really like it if you can make something be triggered more than once & the triggers in separate places

**Comment by peefTube** [comment]
You can trigger something more than once - use the TRIGGER_MULTIPLE item. Button type on trigger items will change the type of trigger item. You can also put triggers in separate places.

**Comment by TeamSpen210** [comment]
You really need to be more precise.

**Comment by peefTube** [comment]
@TeamSpen210 Just to clarify, were you talking to @ZFM2004?
