### ISSUE TITLE
Concrete and metal piston platforms?

### ISSUE THREAD

**Issue by markd0811** [BEEmod/BEE2.4#636]
Have portalable piston platforms been ported from BEE2 alpha? I don't see them in BEE2.4 pre-release 25. It seems like a simple fix: Make them more like angled panels so that checking "portalable" on the surface below the platform will make the platform concrete instead of glass. Thank you guys!

**Comment by peefTube** [comment]
This **was** a nice feature. I'd love to see it in action again.

**Comment by Luke18033** [comment]
This is a BEE2-items issue, and also BEEmod/BEE2-items#95.
