### ISSUE TITLE
Repulsion Gel GLaDOS Line is missing Transcript

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2.4#640]
So while I was looking through the Voice Lines for GLaDOS I found that the Exit Repulsion Gel line didn't have a transcript  
![why are you reading this 2017-05-27 13-34-01-484](https://cloud.githubusercontent.com/assets/26350889/26521492/5b90968e-42e1-11e7-8e31-c28d40838ba3.jpg)

**Comment by Luke18033** [comment]
Stop closing it, it'll auto-close when the update is released.

**Comment by iEnderMan06** [comment]
Sorry
