### ISSUE TITLE
2D BTS Skybox creates bottomless pits and a 3D skybox

### ISSUE THREAD

**Issue by AddMGH** [BEEmod/BEE2.4#642]
![why are you reading this 2017-05-29 13-19-16-952](https://cloud.githubusercontent.com/assets/26350889/26549557/8654dc40-4471-11e7-8abb-fd48c5768e28.jpg)

**Comment by ZombiePwner1** [comment]
@iEnderMan06 This is intention it will still create bottomless pits but the arms on the sides won't be present.

**Comment by iEnderMan06** [comment]
@ZombiePwner1 So a 2d skybox creates a 3d skybox?

**Comment by ZombiePwner1** [comment]
@iEnderMan06 yes minus the arm models that appear in the actual 3D skybox it will just be a plain bottomless pit.

**Comment by iEnderMan06** [comment]
Don't you see what I'm saying here, if a 2d skybox makes a 3d skybox then why is it a 2d skybox, not a 3d skybox

**Comment by ZombiePwner1** [comment]
@iEnderMan06 Well i honestly don't see a difference between the 2.

**Comment by iEnderMan06** [comment]
2d = square 3d = cube

**Comment by iEnderMan06** [comment]
The 2D skybox very much should 2D, and not create a bottomless pit. (Which is done with a 3D skybox) and  I don't see the reason why you'd need to not have the arms on the bottomless pits, maybe have a stylevar to enable and disable them...

**Comment by iEnderMan06** [comment]
and leave 2D skyboxes 2D....

**Comment by TeamSpen210** [comment]
It should give only goo.

**Comment by iEnderMan06** [comment]
@TeamSpen210 That's what I thought
