### ISSUE TITLE
GLaDOS voice line is messed up [Dev]

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2.4#643]
https://soundcloud.com/gamequotes/glados-federal-regulations-1 is playing instead of https://www.youtube.com/watch?v=evGh4grJnJ8

**Comment by Luke18033** [comment]
That's intentional - it's not supposed to be identical to the campaign. Also a BEE2-items issue.

**Comment by iEnderMan06** [comment]
Why only now though? It never used to be like that...

**Comment by iEnderMan06** [comment]
(All of these "intentional" things are gonna make me have to do more work...)
