### ISSUE TITLE
Logic Gates Input/Output

### ISSUE THREAD

**Issue by divastor** [BEEmod/BEE2.4#644]
I am a bit confused with the matter so feel free to even delete my question after it is answered, but **how do you know if a connection to a logic gate is an input or an output**? Can I control which is which somehow?

I mean, I get that when you connect 2 buttons to an _OR_ and then the _OR_ to a funnel, the buttons are the input and the funnel is the output. But, how do you know which is which if you want to connect 2 _AND_ gates and 2 _NOT_ gates to an _OR_ gate. Even with the way I said it, you can't tell for sure which is the output and which the input (I could mean either the _AND_ s as input and the _NOT_ s as output or even one _AND_ and one _NOT_ as inputs, or any other combination).

 Is there a distinction I am missing, or a way to control which is which?

**Comment by iEnderMan06** [comment]
If you connect from a logic gate that'll be an output, connecting to it will be an input.

**Comment by iEnderMan06** [comment]
But these questions really are for https://discord.gg/beemod

**Comment by Luke18033** [comment]
You mean https://discord.me/beemod.

**Comment by Luke18033** [comment]
Or an invite code works too.

**Comment by TeamSpen210** [comment]
The start item is the input, the end item is the output. You can also look at the position of checkmarks, and the 'Remove connections' dialog only shows connections in one of the directions (I think it shows the inputs only).
