### ISSUE TITLE
Implement a syntax character to allow leaving "Blank lines" inside an Item´s description.

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#645]
This is how it should be:
![Image](https://cloud.githubusercontent.com/assets/12244376/26565775/b5fde466-44c4-11e7-9c3a-559bb9dc8e35.png)

**Comment by TeamSpen210** [comment]
This is impemented, have you tried double-spaces at the end of a line?

**Comment by LautaroL20** [comment]
Yes. Also i doubt its currently possible since there is no items that are using this in the desc, all the phrases are kinda piled up...

**Comment by LautaroL20** [comment]
Here´s a screenshot that proves this is not implemented, see the spaces in the text file and item´s description:
![Image](https://cloud.githubusercontent.com/assets/12244376/26588465/cdbc702e-452b-11e7-831d-0ef8b975c80c.png)

**Comment by LautaroL20** [comment]
@TeamSpen210 - Is this implemented or something?

**Comment by TeamSpen210** [comment]
This is now implemented after switching to `mistletoe`.
