### ISSUE TITLE
Improve / replace the "recursion.jpg" picture from the Splash Screen

### ISSUE THREAD

**Issue by HelloIamaPersonThatIsAliveAndHealthily** [BEEmod/BEE2.4#646]
Let me explain my point to replace that pict, and it´s because it does look pretty much unprofessional when the Bee´s logo and fonts are over it, as you can see in the picture below:

![image](https://cloud.githubusercontent.com/assets/29079770/26610923/f6964f9c-4580-11e7-8505-6d3e01d61c19.jpg)

**Comment by Luke18033** [comment]
I think I've already told you on Discord that we're not replacing it, besides changing the camera angle. I think it looks fine besides the issue with the text.

**Comment by LautaroL20** [comment]
I am probably going to remake it, i have to be agree respect that it does not looks too good.

**Comment by TeamSpen210** [comment]
A better/alternative solution would be to add a shadow to the text, which will make them easier to read on all backgrounds.

**Comment by Luke18033** [comment]
That would probably be better, actually.

**Comment by Luke18033** [comment]
Also [here](http://steamcommunity.com/sharedfiles/filedetails/?id=545151069&searchtext=recursion) is the map the screenshot is from.

**Comment by TeamSpen210** [comment]
Said shadow was implemented.
