### ISSUE TITLE
Bottomless Pit Alternate Skyboxes/Styles?

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#647]
I want to create an overgrown chamber with bottomless pits, but don't want to change skyboxes if I do so. This type of feature would also be nice for the Enrichment Spheres as well. I don't know if this has already been suggested but it really would be a nice feature to have.

**Comment by ZombiePwner1** [comment]
We need a overgrown BTS skybox that is pretty much the same as the overgrown skybox but replaces goo pits with bottomless pits.

**Comment by Luke18033** [comment]
What would also be nice is a separate Bottomless Pit item, which would also solve this problem.

**Comment by TeamSpen210** [comment]
It's difficult to do that, there's no way to tell from the VMF what item a goo pool was spawned from.

**Comment by peefTube** [comment]
@TeamSpen210 - someone else suggested it be a stylevar option

**Comment by Fazbear189** [comment]
Yeah make it a stylevar option!

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2-items/issues/3891
