### ISSUE TITLE
Full Music Packs?

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#648]
There's partial music packs for PRL24, but I'd like to ask if future versions of BEEMod will have all music from Portal Stories: Mel, Aperture Tag, and Portal 2 instead of the meager selection we have now. It's a real pain to have to do it ourselves, which is why I'm asking dedicated developers to do it instead. Either this or work on an official BEEMod music pack creator and editor to work alongside BEEMod, which I know has been requested and is definitely possible. Either way, thank you ahead of time for any answers on this matter.

**Comment by Luke18033** [comment]
What do you mean? BEE already has most of the Portal 2, Tag and Mel music.

**Comment by Luke18033** [comment]
Also Pr25 is out, why are you still using 24?

**Comment by TeamSpen210** [comment]
What's missijg? I deliberately didn't include things such as the core transfer musics, because theose don't make much sense in chambers and are very specifically set up exactly for the length of the sequence (they sound bad when looped). Other tracks aren't included because they're laser music tracks, and I still need to implement that.

**Comment by peefTube** [comment]
I'm talking about what's in their Soundtrack folders as well as Portal 2: Songs to Test By from the official Portal 2 site

**Comment by TeamSpen210** [comment]
Which specifically? Many of those don't make sense as chamber music (`Excursion Funnel` for example), and others can't (`The Courtesy Call` has Wheatley's lines embedded in it).

**Comment by peefTube** [comment]
Alright, I see where you're coming from - but please try to add in as many as possible. As I said, there's Songs to Test By, which has music-only tracks for ones like The Courtesy Call. Also, I used a lot (and I mean _**A LOT**_) of tracks out of Aperture Tag and none of them showed up in-game like they should have - please go back and fix these.

And back to the other question of a built-in music editor: this feature should absolutely be implemented, coming from a developer standpoint. BEEMod could use a package editor to smooth things along for users unable to or uneducated in coding matters. The BEEMod community will be grateful - seeing as how many times we've asked for such a tool.

And to @Luke18033 - PR25 broke BEEMod when I installed it, so I'm waiting until I have absolute confirmation that there's a fixed version of PR25 out.

**Comment by LautaroL20** [comment]
> Luke18033 Said: "Also Pr25 is out, why are you still using 24?"

Well.... the latest release came up with some past bug that were supposedly be fixed a long time ago, and also the Tractor Beam switch polarity is also broken. 

I really hope that this doesn´t occur again in future releases.

**Comment by iEnderMan06** [comment]
@peefTube If you're asking for a way to make BEE items, get out seriously, they have guides and it's ridiculously easy, for them to include it would be annoying hard and flat out dumb, a number [of](url) times I've seen people asking this has really annoyed me. Unable to? :waitwhat: or uneducated in coding matters, the problem is, it doesn't use coding languages of any sort, it's a txt file for godsake, you could even search it up on YouTube, and most items you want can be copied and slightly modified for your own BEE and no one should get me started on people asking for how to install dev...

**Comment by peefTube** [comment]
@iEnderMan06 What?! Where'd you get the question of "BEE items?!" The process of looking through a text file is difficult for some, not including me. If you have a problem with my logic to the point of becoming hostile then please hear me out. I'm trying to ask primarily for a _built-in music pack editor_ to streamline the process of adding music to BEEMod, or modifying how music files work. This wouldn't be too horribly hard to code - it's not like coding a game or something. In fact, the con of any time or work "wasted" is far outmatched by how useful such a tool would be. Instead of having to experiment with values in a .txt file, quite literally ANYONE could use a built-in pack editor to do the hard work for them. This is what the BEEMod palette UI does, for sure - using that idea as a template shouldn't be too much work. I'm developing a game - I should know whether or not this idea can work, and I know it will. It's not that hard for any programming team to do. I'm confident @TeamSpen210 and @LautaroL20 can make it work.

**Comment by iEnderMan06** [comment]
@peefTube Sorry, I must have misunderstood your comment, I've just lately been getting really annoyed by the number of people who want a item creator.
