### ISSUE TITLE
how do i install the new release?

### ISSUE THREAD

**Issue by sharpsightkill** [BEEmod/BEE2.4#650]
yes i am asking how

please comment

and answer

**Comment by peefTube** [comment]
Unzip the .zip or .rar file to a folder of your choice. It's that easy.

**Comment by sharpsightkill** [comment]
no i mean is there more than 1 file i need?

**Comment by sharpsightkill** [comment]
i mean there isnt supposed to be a master folder or somthing like that?

**Comment by peefTube** [comment]
You will need the packages zip. Just unzip that and merge it with the normal download.

**Comment by sharpsightkill** [comment]
i uninstalled the mod a week ago becuase of a unsolved error
and i dont have any idea about the version becuase the old version had a master folder

**Comment by peefTube** [comment]
If you have an uninstalled PR24, use that as well. DO NOT USE PR25, it's broken. I'd wait until PR26 to be safe.

**Comment by sharpsightkill** [comment]
too late    


but pr24 ALWAYS fucked up on my pc

**Comment by peefTube** [comment]
Well, look up any errors PR24 gives you online and on here, both open AND closed - that might help you get PR24 up and running.

**Comment by LautaroL20** [comment]
@sharpsightkill - If you have issues, delete everything in `Portal 2\sdk_content\maps\instances\bee2`, `Portal 2\bee2` and `Portal 2\bin`

Then launch Beemod and do a "Full Export" (exporting having the Preserve Game Directories unchecked) and the issue must not be there anymore.
