### ISSUE TITLE
Add bottomless pits as a stylevar option

### ISSUE THREAD

**Issue by AddMGH** [BEEmod/BEE2.4#651]

**Comment by peefTube** [comment]
Already suggested something along these lines. I'll let @TeamSpen210 or @LautaroL20 handle this though since I don't know GitHub's system of handing tags/duplicates and I'm not a moderator here

**Comment by iEnderMan06** [comment]
@peefTube Not a duplicate, since your post wasn't asking for a stylevar option, I'm simply putting it here as 1. an idea 2. for them to close/label rather than doing it on a slightly different post (which may confuse others)

**Comment by Nikita74RU** [comment]
So, will it be implemented or not?
