### ISSUE TITLE
vactubes act weird

### ISSUE THREAD

**Issue by TrustyGun** [BEEmod/BEE2.4#653]
1. Vactubes spits out cubes, spheres, etc randomly (probably not easy to fix)

2. For some reason it is extremely hard, impossible even to enter a forward facing vactube (cubes work however)

3. It's possible to get stuck in a vactube occasionally and be forced to restart/noclip out

**Comment by iEnderMan06** [comment]
BEE2-items please.

**Comment by LautaroL20** [comment]
This issue was moved to: https://github.com/BEEmod/BEE2-items/issues/2033
