### ISSUE TITLE
Found a bug with the laser in the overgrown style

### ISSUE THREAD

**Issue by Te4mLuna** [BEEmod/BEE2.4#655]
To explain it in the easiest way: 
You can´t see the laser on the other side of broken glass
![20170603174540_1](https://cloud.githubusercontent.com/assets/19846848/26754966/a1442b34-4884-11e7-9e96-1651aa78ad6f.jpg)

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#2038
