### ISSUE TITLE
Found a bug with the exit

### ISSUE THREAD

**Issue by Te4mLuna** [BEEmod/BEE2.4#656]
This happened twice so far and also includes the weird white void you can see behind the exit.
This white void is the same as the one I mentioned the good showing up as in another issue I opened.
![20170603174522_1](https://cloud.githubusercontent.com/assets/19846848/26754988/fb6ee806-4884-11e7-913f-640a5e1a7db7.jpg)
![20170603174529_1](https://cloud.githubusercontent.com/assets/19846848/26754990/fc419eea-4884-11e7-8b55-0de657c63f29.jpg)

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#2039
