### ISSUE TITLE
Overgrown doors are bugged

### ISSUE THREAD

**Issue by sloga17** [BEEmod/BEE2.4#659]
On overgrown styles the entrance door is messed up and the exit door is blocked.

**Comment by ZombiePwner1** [comment]
Can you send a screenshot?

**Comment by sloga17** [comment]
![20170606122558_1](https://user-images.githubusercontent.com/29009551/26847923-8892ebbc-4ab3-11e7-9284-68c269925cc4.jpg)
![20170606122644_1](https://user-images.githubusercontent.com/29009551/26847927-8c1311a4-4ab3-11e7-873a-006fc94033e3.jpg)

**Comment by ZombiePwner1** [comment]
@sloga17 There is a leak somewhere in your map.

**Comment by sloga17** [comment]
@ZombiePwner1 how do you fix that with peti?

**Comment by LautaroL20** [comment]
This issue was moved to: https://github.com/BEEmod/BEE2-items/issues/2046
