### ISSUE TITLE
Hovering over drop down menu is annoying

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#661]
This:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16567080/26885197-90343fe2-4b67-11e7-9f26-dd21dd23f95b.gif)

**Comment by LautaroL20** [comment]
Solving this would imply remaking the dropdown bar, making it to be displayed only when click it. See (https://github.com/BEEmod/BEE2.4/issues/568)
