### ISSUE TITLE
A Few Suggestions

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2.4#665]
1. Maybe AEGIS Voicelines from Portal Stories: Mel
2.Diversity tubes e.g When you go in you come through the connected one at a certain velocity basically acting as a world portal
3.Cores I know it's impossible but My way might work there are cores you place around the map and you connect them to the core panels once placed in the panel the panel will activate something of your choice
4. Bottomless pit item
5. BTS Chambers style basically going around the outside of chambers on a catwalk above a bottomless pit and going through offices
6.BTS Old Aperture this would be cool going through the pumps and genorators and looking at the giant spheres
7.Portal Detector This would sense when a portal is on it activating something in your map

**Comment by Luke18033** [comment]
This is a [BEE2-items](https://github.com/BEEmod/BEE2-items) issue.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#2054
