### ISSUE TITLE
Overgrown : Glass Panel and Laser barrier ERROR (re26)

### ISSUE THREAD

**Issue by Nucle0n** [BEEmod/BEE2.4#670]
Hi,

I don't understand why it happens.
It works fine for me, but when other players try to play my map all Glass angled panels get the ERROR 
Same issue with Laser Barriers. The laser barrier works fine but the 3d model on both sides of laser don't appears and are replaced by error.

Is there a way to force use default style ("clean") only for those 2 items by keeping the overgown style for all the rest of the map ?

(Excuse my english =/ )

**Comment by LautaroL20** [comment]
What item is the laser barrier, maybe do you mean the Laser emitter?

**Comment by Nucle0n** [comment]
With "Laser Barrier" I mean that thing :
![20170623135217_1](https://user-images.githubusercontent.com/29629323/27481186-a11a025e-581b-11e7-93bc-3ab6d93bac1b.jpg)

**Comment by ZombiePwner1** [comment]
Reason why it shows up as a blue error for other players is because the model is not getting packed and the laser field has a custom dirty model in overgrown style.

**Comment by CaliMari** [comment]
Players should just install BEE2 or stay with errors.
