### ISSUE TITLE
Allow the Compiler to handle up to 5 or even more ammount of "Conditions" from a configuration file 

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#673]
Currently, the number of conditions allowed from a configuration file is really limited to one condition, and if you wish to expand it to a "possible" second condition you, then you will get a fiddle of "Missing Brackets" that in many cases after launch Beemod, errors that are not possible to fix with the trial & error method.

We really need to implement a new code to allow the compiler to handle an upper ammoun of conditions without fiddling it. Since this will be needed to make future new items.

I will split this post in an aditional part suggesting how the roles such as "PosIsSolid" will work when there are more than one of these.

**Comment by TeamSpen210** [comment]
I'm really not sure what you mean here. The compiler is perfectly able to handle heaps of conditions. In fact every single condition in all the items is merged together into a single list for the compiler to parse.

**Comment by LautaroL20** [comment]
Ah, i remember i suggest this before you implemented the "Colorpicker" entity for the brush template. I was getting a fiddle with the primitive "PosIsSolid" conditions that maded me think that the compiler were not able to handle many conditions.
