### ISSUE TITLE
[dev] No music tracks are playing in latest version of dev

### ISSUE THREAD

**Issue by iEnderMan06** [BEEmod/BEE2.4#674]

**Comment by Luke18033** [comment]
Do you have the application dev as well? I don't know if that's the problem, but it might help.

**Comment by iEnderMan06** [comment]
I don't have the application dev but I can't see why that'd cause problems suddenly now.

**Comment by LautaroL20** [comment]
> Adam Said: "I don't have the application dev"

Why you written "in latest version of dev" in the title, if you don´t have the dev version? This is so contradictory....

**Comment by Luke18033** [comment]
He has the dev items, just not the compiler or application.

**Comment by LautaroL20** [comment]
Well, in that case i doubt he will be able to keep runing through the public version for long. If you do that without having the latest version of the compiler you can get a failure to compile.

**Comment by LautaroL20** [comment]
This doesn´t really happens on the complete development version. You should try installing it entirely.
