### ISSUE TITLE
How do I have a Skybox?

### ISSUE THREAD

**Issue by BlueDuckYT** [BEEmod/BEE2.4#675]
I would like to have a skybox for my level, but I have no idea how to implement it.  How do you "remove" the ceiling?

**Comment by iEnderMan06** [comment]
You'd edit the vbsp_config.cfg file and change ceiling textures to the skybox texture.

**Comment by LautaroL20** [comment]
@BlueDuckYT - Just click the "..." button next to the Skybox name located on the Export Option´s panel, then you can choose between 6 different possible skyboxes for your map. As for the "Ceilling removement", it is not currently possible.
