### ISSUE TITLE
BEE 2.4 PRL25 CRASH!!! "PermissionError: [WinError 5] Zugriff veweigert: ´d:\\program files (x86\\steam\\steamapps\\common\\portal2\\sdk_content\\maps\\instances\\bee2\\50s\\items\\bee\\drawbridge ´

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#676]
Originally posted by @Flo2912 (https://github.com/BEEmod/BEE2-items/issues/2081)

![Image](https://user-images.githubusercontent.com/19980844/27710033-8b911398-5d1e-11e7-839f-df2237f37408.png)

"I get this Error everytime I try to export something with Bee 2.4 Pre 26 to Portal 2, had the same issue with Pre 24 as well. It seems that trying to export it breaks the folder that is named in the issu, since I can't open thix folder anymore, nor can I delet or rename it. When I restart my Computer, the folder is vanished and reapperas after the next export try, however than anoter folder takes its place of disfunction and it crashes again. And older version of Bee 2 seemed to work well, while it allways got an "Can't create File that already exists" error, so I had to unpack the packages all by myself (Only knew where to pack items and resources, as result it worked but hat some things like voice-lines missing), however since I startet pre26 this old application version doesn't want to launch at all. "

**Comment by Flo2912** [comment]
I was able to fix this issue. I (again) unpacked the resources folder of every package-zip file, put all contrent of the instances folders in sdk_content/maps/instances/bee2 and all the other stuff (like bee2, models, materials, ...) into portal2_dlc2. Now it works almost perfectly well, thr pallet gets exportet, the items can all be used and are working, testchambers can be build with no problem, stylechanges work. However, custom vvoicrlies added by the Mod ar still missing, as well as the soundeffect from these pellet-switch-field from rexaura. Also its statet that there hasn't been included VPK stuff.

Strange error...

**Comment by LautaroL20** [comment]
> Flo2912 Said: "I was able to fix this issue."

Glad to know. Also, to prevent having issues with upcoming releases, before install them make sure to relete the "bee2" folder located at "Portal 2\sdk_content\maps\instances", also the "bin" and "bee2" folders located at main Portal 2 directory, if you don´t do this you will probably experience issues when using future releases.
