### ISSUE TITLE
Change the message from "Ensure the <game> is not running." to "Ensure <game> is not compiling the chamber." - For when you are just trying to export changes in the compiler options only and NOT items/styles...

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#678]
While Portal 2´s Puzzlemaker is compiling a chamber and you try to export changes in the compiler´s tab of Beemod, you will get a message that says "Ensure Portal 2 is not running"... This message is accurate if you tried to export items or a different Style so, of course the game must be restarted so the changes can take effects properly. However, if you are trying to export changes in the compiler´s tab of Beemod to get, for example, a different corridor, restarting the game is not required and the changes will take effects regardless of restarting anything. 

So, what i am suggesting is that for this particular case, the message should be changed to reflect the real cause of the issue: "Ensure Portal 2 is not compiling a chamber". However, if the user wanted to export another Style while the game is running, the message should indeed remain as: "Ensure that P2 is not running"...

----------------------------------------------------------------------------------------

I was trying to export changes in the compiler´s tab of Beemod, only:

![Image](https://user-images.githubusercontent.com/12244376/27766684-fd2bada6-5eae-11e7-90f0-de268138488a.png)

**Comment by homelessturret** [comment]
#728

**Comment by Jaxinator03** [comment]
I had something like this before, try checking the logs, (in the options tab) and find where the python36.dll should go, and move it manually. 
Worked fine for me wheh I had the same issue with  vbsp.exe

**Comment by LautaroL20** [comment]
@Jaxinator03 - This issue is just about to rename the panel´s message with the real cause, since its the puzzlemaker´s compiler process which causes it, not the game running.

**Comment by Luke18033** [comment]
What exactly is the issue here? You shouldn't have Portal 2/Hammer running during an export.

**Comment by LautaroL20** [comment]
I´ve re-edited the title as well as the description, so now it should be fully understable to what i meant with this suggestion: "While Portal 2´s Puzzlemaker is compiling a chamber and you try to export the Beemod´s Palette, you will get a message that says "Compying Compiler Failed,  Ensure Portal 2 is not running"... This message is accurate if you tried to export a different Style and of course, the game must be restarted so the changes can take effects properly. However, if you are trying to export items or just change to a different corridor, restarting the game is not required and the changes will take effects regardless of restarting anything." 

So, what i am suggesting is that for this particular case, the message should be changed to reflect the real cause of the issue: "Ensure Portal 2 is not compiling a chamber". However, if the user wanted to export another Style while the game is running, the message should indeed remain as: "Ensure that P2 is not running"...

----------------------------------------------------------------------------------------

I was trying to export items/corridors ONLY, not styles:

![Image](https://user-images.githubusercontent.com/12244376/27766684-fd2bada6-5eae-11e7-90f0-de268138488a.png)

**Comment by LautaroL20** [comment]
Now i´ve remember very well what was the purpose of this suggestion, it is only about doing changes in the compiler´s tab of Beemod where its not required to restart the game in order the changes to take effect. I guess i had a mental lapsus where for some reason, i thought it was the same for items when it is very clear that for export Styles & Items you must restart the game, i only can think this is due that there is a long time i do not use Beemod and forgot the basic mechanisms.

**Comment by Luke18033** [comment]
Options in the compile window should take effect immediately, without needing to re-export.

**Comment by LautaroL20** [comment]
The problem here is that Beemod will still warm you saying "Ensure P2 is not running." when this clearly is not needed. I think this would be mostly a bug than a suggestion.

**Comment by Luke18033** [comment]
Also note the grammar error here ("the Portal 2") and lack of a space in the middle, both of which we'd also want to fix.
