### ISSUE TITLE
"Trapped" Voice line item

### ISSUE THREAD

**Issue by Blacksilver42** [BEEmod/BEE2.4#683]
Have an item that, once activated:

1. Plays one of GLaDOS's "Congratulations, you've trapped yourself" voice lines, probably using a pedsastal-button-timer-picker-thingy to choose which one
2. After an appropriate delay based on the voice line, activates any outputs it has.

This shouldn't be _terribly_ hard to code. Heck, I'd do it if I knew how.

**Comment by Luke18033** [comment]
BEE2-items issue.

**Comment by Luke18033** [comment]
This issue was moved to BEEmod/BEE2-items#2088
