### ISSUE TITLE
Here's an idea for a new item...

### ISSUE THREAD

**Issue by ItsRyaN27** [BEEmod/BEE2.4#688]
What if we had a piston platform item that has portalable/non-portalable surfaces that blend into the floor and walls? Something like that would be very helpful for things like secrets, momentum puzzles, etc.

**Comment by Luke18033** [comment]
This is already going to be implemented, see BEEmod/BEE2-items#95.

**Comment by Endermage77** [comment]
I think what he meant here was to suggest that the portalable panels (To be implemented; see Luke's post above) be able to blend in seamlessly with surrounding tiles, presumably when both extended and retracted, yes?

**Comment by Endermage77** [comment]
(This device has no edit mode, dangit!)

This would also mean that this would classify as an Enhancement.

Then again, the title does say its suggesting a new item. But with new mechanics.
But what do I know? Apparently, I have such good memory that I forgot what the original post said betwern reading it and starting up this coment.

**Comment by TeamSpen210** [comment]
Unfortunately due to how lighting works, tiles will only be able to match lighting for fully retracted or extended.

**Comment by Luke18033** [comment]
There's actually a cool trick Reepblue used in his Portal 2 Demo Map (for Portal 1) to get the correct lighting on panels in both positions - they start extended, but are immediately retracted on map start. When fully retracted, the panels swap to "fake" versions which started in the lower position and therefore have the correct lighting. They swap back to the real versions when they start to extend.

**Comment by TeamSpen210** [comment]
You can do that, but it also means it'll suddenly swap between the two.

**Comment by Luke18033** [comment]
It wasn't really noticeable in that map, I had no idea he did that until I decompiled it.
