### ISSUE TITLE
Game crashes, error "Map coordinate extents are too large!!"

### ISSUE THREAD

**Issue by rmboyce** [BEEmod/BEE2.4#692]
Note: I'm using BEE 2.4
This has happened in three levels that I've created so far. For two of them, they worked for a while, but then stopped working. Those levels load in the editor fine, but when I try to play them the game crashes and prints the error message to the console. The other level worked until I published and unpublished (to edit), and now it will no longer load in the level editor. In all cases I get the following message at the bottom of the console output:

(...a lot of output removed, related to loading and compiling assets...)
---- Host_Changelevel ----
Host_EndGame: Map coordinate extents are too large!!
Check for errors!

The levels aren't especially large. The two that crash when I play them are fake Wheatley style (clean, wheatley, 3D factory, frankenturrets). The one that doesn't load I probably messed up somehow - I accidentally used different music and dialogue when I published it.

**Comment by Luke18033** [comment]
BEE2-items issue.

**Comment by Luke18033** [comment]
Also a duplicate of #576 (which I should move).

**Comment by rmboyce** [comment]
I remade the levels with all the same elements and they work fine now. I think it may have something to do about loading the level with the wrong style.
