### ISSUE TITLE
Preplaced repulsion gel splats issue.

### ISSUE THREAD

**Issue by keifersisawesome** [BEEmod/BEE2.4#693]
Using the 50's aperture aesthetic, i was attempting to make a repulsion gel test. I wanted to fill in the bottom of two pits with preplaced repulsion gel, without dispensers. Every time i loaded the level on fast setting one splat or so would be missing, howeve when i tried to post it, the whole game would urn black and stop working fo r a bit and then finish posting the chamber. When I load it up after it being posted, a lot of splats would be mising from the pits, and sometimes the pink and black no texture texture would appear all over the chamber. It's one of the most annoying things i've ever delt with, but that's neither here nor there. Here's the error that appears constantly seemingly in association with this issue.

prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
SAVEGAME:  840.4kb,  294.5kb used by 723 entities (workshop\835832990482183865\1500662321)
SAVEGAME:   44.3kb,   23.8kb used by 310 entities (workshop\835832990482183865\1500662321)
SAVEGAME:    1.1kb,    0.0kb used by   0 entities (workshop\835832990482183865\1500662321)
SAVEGAME:  840.4kb,  294.5kb used by 723 entities (workshop\835832990482183865\1500662321)
SAVEGAME:   44.3kb,   23.8kb used by 310 entities (workshop\835832990482183865\1500662321)
SAVEGAME:    1.1kb,    0.0kb used by   0 entities (workshop\835832990482183865\1500662321)
!! ERROR: bad input/output link:
!! logic_choreographed_scene(@cave_enter,Trigger) doesn't match type from trigger_once()
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!
prop_paint_bomb at (3152.000, 1344.000, 576.000) has no model name!

**Comment by keifersisawesome** [comment]
The error message I've pasted here appears even in other aesthetics, but all placed gel splats are present in the clean aesthetics.

**Comment by keifersisawesome** [comment]
I also recently had a strange occurrence where I changed the aesthetic and one of the gel splats was in a different place than where I initially put it.

**Comment by keifersisawesome** [comment]
It seems the mod just has an issue with gel splats as a whole.

**Comment by Luke18033** [comment]
What a strange issue...

**Comment by keifersisawesome** [comment]
Let me tell you, it is giving me ceaseless headaches with this. I just wanted to make a repulsion gel puzzle with the 50's aesthetic man. XD

**Comment by LautaroL20** [comment]
@keifersisawesome - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however once you installed the latest version, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by keifersisawesome** [comment]
@LautaroL20 Where do I find that at?

**Comment by LautaroL20** [comment]
@keifersisawesome - You get the Pre-Release 27 from the links below, then follow my steps to ensure everything will work fine:

https://github.com/BEEmod/BEE2.4/releases/tag/2.4.0pr27 (Application)
https://github.com/BEEmod/BEE2-items/releases/tag/pr27 (Packages) 

Once downloaded, you will have to unzip both files into a same folder. Go to the bin folder and launch bee2.exe and do this:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by keifersisawesome** [comment]
When I attempt to open the app,this pops up. 

![60ca05b1-59d9-42d2-88dd-fde85db40e1d](https://user-images.githubusercontent.com/30207648/32136719-ad3b7206-bbe0-11e7-96ef-97fd4b0a82f7.jpeg)

**Comment by LautaroL20** [comment]
@keifersisawesome - Are you using Linux, Mac or Windows?

**Comment by keifersisawesome** [comment]
@LautaroL20 Windows 10

**Comment by LautaroL20** [comment]
@keifersisawesome - You might try running bee2.exe as an administrator, also make sure you have full permissions on Windows 10, you can google on this if needed. Since on your picture says "Access denied" which means you have limited permissions.

**Comment by keifersisawesome** [comment]
@LautaroL20 I’m now receiving the Build Error when trying to test the puzzle.

**Comment by LautaroL20** [comment]
@keifersisawesome - Redo the following, and then let me know if it persist:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by keifersisawesome** [comment]
@LautaroL20 it still has not worked. I went ahead and copied the error i got in the dev console just in case. Here it is.

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198074144265\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,18,11)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 209 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_CAVE_50s'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_piston_platform> (Valid: {'piston_bottom_0': 'instances/bee2/50s/items/pist_plat/plat_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/pist_plat/plat_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/pist_plat/plat_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/pist_plat/plat_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/pist_plat/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/pist_plat/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/pist_plat/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/pist_plat/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/pist_plat/static_4.vmf', 'piston_logic_0': 'instances/bee2/logic/piston/logic_0.vmf', 'piston_logic_1': 'instances/bee2/logic/piston/logic_1.vmf', 'piston_logic_2': 'instances/bee2/logic/piston/logic_2.vmf', 'piston_logic_3': 'instances/bee2/logic/piston/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 12 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Using random SP Entry (5)
[INFO] vbsp.mod_entryexit(): Using random SP Exit (4)
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (274 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x07E084B0>: [False, False, False, False], <srctools.vmf.Entity object at 0x07DFBA50>: [False, False, False, False], <srctools.vmf.Entity object at 0x07DFBB50>: [False, False, False, False], <srctools.vmf.Entity object at 0x07DFBC10>: [False, False, False, False]}
[INFO] cond.catwalks.res_make_catwalk(): Markers: {'catw58': <srctools.vmf.Entity object at 0x07E084B0>, 'catw25': <srctools.vmf.Entity object at 0x07DFBA50>, 'catw26': <srctools.vmf.Entity object at 0x07DFBB50>, 'catw27': <srctools.vmf.Entity object at 0x07DFBC10>}
[INFO] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 3/6 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Follow the Blue Line"
 | 	"Bullseye" "cave_a3_03_waiting_room"
 | 	"Choreo" "npc/cavejohnson/fifties_waiting05.vcd"
 | 	"SetStyleVar" "AddBlueLine"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 2/7 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "NO_MENTIONING_CONTROL"
 | 	"Bullseye" "cave_a3_jump_intro_interchamber"
 | 	"Choreo" "npc/cavejohnson/fifties_second_test_intro01.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/2 quotes..
[INFO] voiceLine.add_voice(): Using microphones...
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['goo', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'cubedropper', 'cubedropperstandard', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'gel', 'geldropper', 'bouncegel', 'bluegel', 'water', 'watergel', 'cleargel', 'pedestalbutton', 'glass', 'observationgrate', 'obsworldportal', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=39674, misses=343, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'addblueline': True, 'retro_voice_pre_line': False}
[INFO] cond.core.check_all(): Global instances: set()
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 224.0 <- Counter({224.0: 107})
[INFO] vbsp.clump_walls(): Clumping: 755 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[WARNING] template.retexture_template(): Realign face in template "bee2_static_pan_angled_white_50s" (118 in final) is not on grid!
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/indicator_broken_1.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/indicator_broken_2.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/indicator_norm_1.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/indicator_norm_2.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/underground_woodwall003c.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/panels/static_phys.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_underground/dropper_fix.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_underground/ramp.mdl"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun 28 2017)
 | 8 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 8 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (0)
 | writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
 | done (0)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (1) (837561 bytes)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Water found with no water_lod_control entity, creating a default one.
 | Compacting texture/material tables...
 | Reduced 4019 texinfos to 947
 | Reduced 94 texdatas to 85 (3309 bytes to 2882)
 | Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
 | 
 | nummapplanes:     (  8244 / 65536 )
 | nummapbrushes:    (  2365 /  8192 )
 | nummapbrushsides: ( 19241 / 65536 )
 | num_map_overlays: (    70 /   512 )
 | nummodels:        (    74 /  1024 )
 | num_entities:     (   781 / 16384 )
 | 
 | 8 seconds elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (75980000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77514120
 | CDynamicFunction: Closing library 'Kernel32.dll' (75980000)
 |_

[INFO] vbsp.run_vbsp(): VBSP Done!
[INFO] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('2365', '8192'), 'overlay': ('70', '512'), 'entity': ('781', '16384')}
[INFO] BEE2_config.save(): Saving changes in config "C:\Program Files (x86)\BEEmod 2\config/compile.cfg"!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3744, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3489, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3550, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 267, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 262, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\BEEmod 2\\config/compile.cfg'
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3744, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3489, in run_vbsp
  File "F:\Git\BEE2.4\src\vbsp.py", line 3550, in process_vbsp_log
  File "F:\Git\BEE2.4\src\BEE2_config.py", line 54, in save
  File "F:\Git\srctools\srctools\__init__.py", line 267, in __enter__
  File "F:\Git\srctools\srctools\__init__.py", line 262, in make_tempfile
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files (x86)\\BEEmod 2\\config/compile.cfg'

**Comment by keifersisawesome** [comment]
@LautaroL20 after posting that I noticed the permission error and tried running the game as an administrator, and it built the preview just fine, but there is one problem. The Paint splat issue that this poost was created about has not gone away in this version. Some of the splats I place are still dissapearing when I buld the chamber.

**Comment by LautaroL20** [comment]
@keifersisawesome - Problem is that nobody is experiencing your issue, and therefore it is not possible to fix something that we can not replicate on our computers. As for the build error you posted, seems you still have to get FULL PERMISIONS on your Windows 10, if i were you, i would keep looking for a more concrete solution rather than having to open the context menu run it as an administrator.
