### ISSUE TITLE
Logic gates

### ISSUE THREAD

**Issue by floriscnossen** [BEEmod/BEE2.4#697]
I still have the same issue as discribed here: https://github.com/BEEmod/BEE2.4/issues/340

Some logic gates do not function right in combination with triggers

**Comment by floriscnossen** [comment]
Here im using an or-gate.
![portal2](https://user-images.githubusercontent.com/30473154/28636238-d2116e74-723d-11e7-851a-b4d4ff928197.png)

This happens if you place two triggers next to each other. walking into one if the triggers activates the gate, but when you walk from one of the gates to the other it doesn't work.

I also noticed that and-gates give the same result. If you are standing in one of the triggers the gates still activate.

**Comment by LautaroL20** [comment]
I think that the issue you mention was about the invisible logic gates. You are using the visible ones. Items-related stuff must be posted, here: 

Your issue has moved to: https://github.com/BEEmod/BEE2-items/issues/2109
