### ISSUE TITLE
Use checkboxes for corridors/elevideos instead of a dropdown

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#698]
This would eliminate the need for the Random option, but would still let you decide which random layouts to use.
If you select one layout, it will only use that layout when the level is loaded.
When two layouts are selected, it will randomly choose between those two layouts when the level is loaded.
Same with three layouts, four, five, all of them, etc. Here's a cruddy mockup:
![Also works like this for elevideos](http://i.imgur.com/cueQNNv.png)
Only problem is, I have no idea how smoothly this would fit into the current UI.

**Comment by TeamSpen210** [comment]
We can't do this actually, it's PeTI which is doing the randomisation.
