### ISSUE TITLE
Suggestions: New Textures, Camera

### ISSUE THREAD

**Issue by floriscnossen** [BEEmod/BEE2.4#700]
These are my suggestions. The second one is probably impossible to add in the mod, but I think it would be awesome.
1.	New textures for Atlas and P-body for Old Aperture (A bit like the old turrets maybe?)
2.	An addition to the camera item that, when activated, can also display its view on the full screen (in addition to only in-game monitors). 
This could be useful for cinematic shots or to give attention to things you wouldn’t normally notice.
The timer could be used to determine when to switch back to the normal first person view. (Infinity could mean: until it is deactivated)
The button type value could be used to select the place to display:
•	Weighted: Monitors in maps (current)
•	Cube: The full screen
•	Sphere: Only 1 player in Coop maybe? Start reversed determines which player

**Comment by LautaroL20** [comment]
Items-related stuff must be posted, here: 

This issue has moved to: https://github.com/BEEmod/BEE2-items/issues/2110
