### ISSUE TITLE
Closed Solid Field not showing 

### ISSUE THREAD

**Issue by Wklaver** [BEEmod/BEE2.4#702]
I wanted to use a Closed Solid Field in a test but the texture isn't showing for me.
Screenshot: http://steamcommunity.com/sharedfiles/filedetails/?id=1095205560

**Comment by ZombiePwner1** [comment]
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1918

**Comment by Wklaver** [comment]
I didn't know that some one posted all the way back on May 7th about this
