### ISSUE TITLE
Glitches and lags after starting the map

### ISSUE THREAD

**Issue by Maturas** [BEEmod/BEE2.4#704]
I have created a map with vanilla editor. Today I downloaded BEE 2.4 and added few triggers and changed some settings (music, voice and skybox). After building the map, it starts in an elevator. There are no walls - I can see some blue elements which are further in the map. I have 5-10 FPS and there are glitching screams of turrets all the time. What's happening? How can I fix this?

**Comment by TeamSpen210** [comment]
That's very strange. Could you take some screenshots?

**Comment by Maturas** [comment]
![portal2 2017-08-05 12-06-18-78](https://user-images.githubusercontent.com/24843964/28994783-a21b370e-79d6-11e7-9fa9-a211a8c1b2d6.png)
![portal2 2017-08-05 12-06-24-52](https://user-images.githubusercontent.com/24843964/28994784-a21c6b38-79d6-11e7-936f-73f5b006fc54.png)
![portal2 2017-08-05 12-06-29-63](https://user-images.githubusercontent.com/24843964/28994786-a21d6e0c-79d6-11e7-93d9-45b7e2cdc1f5.png)
![portal2 2017-08-05 12-06-34-13](https://user-images.githubusercontent.com/24843964/28994785-a21d168c-79d6-11e7-987d-90df11ecf17d.png)

**Comment by Luke18033** [comment]
Wut? Are you trying to use BTS style? Because that's pretty broken atm and could possibly cause this.

**Comment by LautaroL20** [comment]
A clean elevator in BTS Style? Thats strange....

**Comment by Maturas** [comment]
Nope, I'm using Original Clean style. I've also tried with Clean, same thing happens.

**Comment by Maturas** [comment]
Here's some output from the console:

`
NET_GetBindAddresses found 192.168.0.2: 'Realtek PCIe GBE Family Controller'
Opened Steam Socket NS_SERVER ( socket 3148 )
Opened Steam Socket NS_CLIENT ( socket 2964 )
Network: IP 192.168.0.2, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: D:\SteamLibrary\steamapps\common\Portal 2\portal2.exe\platform\config
ILocalize::AddFile() failed to load file "Resource/platform_english.txt".
ILocalize::AddFile() failed to load file "Resource/platform_polish.txt".
ILocalize::AddFile() failed to load file "Resource/vgui_english.txt".
ILocalize::AddFile() failed to load file "Resource/vgui_polish.txt".
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Using joystick 'Xbox360 controller' configuration
Advanced joystick settings initialized for joystick 1
------------
joy1 x axis:  strafe (absolute)
joy1 y axis:  forward (absolute)
joy1 z axis:  unmapped
joy1 r axis:  pitch (absolute)
joy1 u axis:  yaw (absolute)
joy1 v axis:  unmapped
Failed to init 'maps/soundcache/_master_polish.cache'
[PORTAL2 PUZZLEMAKER]  Unrecognised property type: 
Didn't find Active Steam Controller to Load Menu Controls
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.2, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 3148 )
Opened Steam Socket NS_CLIENT ( socket 3168 )
Network: IP 192.168.0.2, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_bee2_paint_fizz.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_bee2_paint_fizz.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Connection to Steam servers successful.
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/SteamLibrary/steamapps/common/Portal 2/portal2/puzzles\76561198117915240\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 76 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 9739 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/SteamLibrary/steamapps/common/Portal 2/portal2/puzzles\76561198117915240\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 87168 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/SteamLibrary/steamapps/common/Portal 2/portal2/puzzles\76561198117915240\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 119004 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 119697 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named player_start_teleport, which point_template player_start_template is specifying.
Couldn't find any entities named player_start_portalgun, which point_template player_start_template is specifying.
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
PrecacheScriptSound 'World.UndergroundElevatorDoorClose' failed, no such sound script entry
Precache called on a point_template that has no templates: player_start_template
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_bee2_paint_fizz.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_bee2_paint_fizz.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_under_faith_targ.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_crusher.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tspen_checkpoint.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
CSoundEmitterSystemBase::GetParametersForSound:  No such sound music.BEE2
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
CSoundEmitterSystemBase::GetParametersForSound:  No such sound music.bee2
CSoundEmitterSystemBase::GetParametersForSound:  No such sound Error
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
20
-2
Updating sound cache [8741 entries]
Found 8736 sound files on disk
Updated 0 out of 8736 cached files [718.139 msec]
Redownloading all lightmaps
Maturas unpaused the game

`

**Comment by TeamSpen210** [comment]
I know how to reproduce this, but not how it'd happen on someone's machine. Specifically if the fgd files are missing, VBSP doesn't know which keyvalues to adjust to move objects. So everything appears at the origin.
