### ISSUE TITLE
Beemod has basically ruined my copy of Portal 2

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2.4#705]
@TheLoafLord commented on [Fri Aug 04 2017](https://github.com/BEEmod/BEE2-items/issues/2129)

I can't play Co-op Chambers, I can't play downloaded single player maps without getting an error, I've been 'locked' out of my own chamber list, because whenever I try to open it, Portal 2 crashes, I keep getting build errors, freezing, crashes, and so much more. And I believe Beemod is to blame. I still love Beemod, I'm just pissed off. I can't even access my chambers anymore.

---

@ZombiePwner1 commented on [Fri Aug 04 2017](https://github.com/BEEmod/BEE2-items/issues/2129#issuecomment-320235417)

@TheLoafLord I'd love to help out however i'm unsure would could be causing your issues with portal 2 since i've never experienced this issue on my own copy of portal 2.

---

@ncrecc commented on [Fri Aug 04 2017](https://github.com/BEEmod/BEE2-items/issues/2129#issuecomment-320252075)

On steam, right click the game, properties, local files, verify integrity of game files.

---

@Endermage77 commented on [Fri Aug 04 2017](https://github.com/BEEmod/BEE2-items/issues/2129#issuecomment-320282133)

Yeah, verifying game files should generally be your goto if Portal 2 starts acting up.

---

@TheLoafLord commented on [Fri Aug 04 2017](https://github.com/BEEmod/BEE2-items/issues/2129#issuecomment-320401253)

I've verified it and I STILL can't access my levels... I'm pretty frustrated.

**Comment by Byzarru** [comment]
Have you deleted BEEmod? Removing Portal 2 from the game list while in BEE achieves this.

**Comment by Luke18033** [comment]
It's usually a good idea to move issues using the [GitHub Issue Mover](https://github-issue-mover.appspot.com/), it handles comments better then ZenHub does.

**Comment by Endermage77** [comment]
Maybe you can try moving all of your levels to somewhere else and then deleting a few big folders like "bin" and "portal2" and "bee2", and THEN verifying the files and then moving all of the levels back into the folder they were in.
The levels are stored in [directory]/Portal 2/portal2/puzzles/[long string of numbers], by the way.

**Comment by TeamSpen210** [comment]
Don't do that. Just verify cache.

**Comment by TeamSpen210** [comment]
@TheLoafLord, does this still occur?

**Comment by homelessturret** [comment]
Open BEE2, go to file, and then go to uninstall from game (under files) then verify cache.

**Comment by LautaroL20** [comment]
@TheLoafLord is probably having a deafective HDD or something, since nobody is experiencing this issue. Scan your hard device for errors and youll see.
