### ISSUE TITLE
Problems with running BeeMod2.4 Chamber in Hammer

### ISSUE THREAD

**Issue by WheatlyInc** [BEEmod/BEE2.4#708]
Hello,

Issue: When running the map through hammer--> Music does not play, no wheatley dialogue plays (although there is a different one that is not wheatley, which plays and says "aw what is it"), the monitors extend but do not broadcast anything ...    As I troubleshooted I even ended up just falling in a void with no portal gun every time I run the map through hammer. 

I got a chamber created in Peti, using Beemod2.4 to include wheatley monitors/dialogue, custom entrance way/exit way, checkpoints, and custom music. They all work just fine by playing through the chamber listed under PETI. However, I wanted to include Shredders in the map because that would be neat for my chamber. I ended up spending days trying suggestions for similar beemod/hammer issues, including having "start in elevator" enabled, and Restart When Reaching Exit off, and editing the map from the preview.vmf file in the "styled" folder. Additionally I repaired both portal 2 and authoring tools. 

I'm not really sure what is going on. Plus, from what I could find, there really doesn't seem to be much accessible information on exactly how compatible beemod2.4 is with hammer, or any guides on editing beemod2.4 maps further using hammer. The mod could definitely be useful just to get complicated brushes/effects out of the way by using an interface, and further edit whatever you need to in Hammer.
 I'd appreciate any help

**Comment by TeamSpen210** [comment]
You repeated yourself. It's not really supported too much, I wouldn't recommend it. None of the items are designed for easy use. It's much better to actually make the map yourself. Your problem sounds though like you haven't packed in the files.

**Comment by ZombiePwner1** [comment]
@WheatlyInc making maps from scratch in hammer is easy once you know how to use the program which isn't too hard just look up some tutorials on YouTube.

**Comment by WheatlyInc** [comment]
@TeamSpen210  Truly, I figured. I suppose I really like to experiment with any editing tools anyway.
Also I noticed that option (packed files). Do I need to do anything special with those files/save them in a specific directory? Right now I have it dumping in a folder on my desktop, and I'm still getting the same issue I described. At this point, if the issue should be fixed just by generically dumping the files, I'm fine if I'm just completely better off with my time figuring it out entirely in hammer if there isn't any other viable way to make the issue go away.

**Comment by TeamSpen210** [comment]
You'd need to pack those into your map after compiling.

**Comment by WheatlyInc** [comment]
I successfully packed them in the preview bsp in the styled folder. However I get a [Error] vbsp.run_vbsp(): VBSP failed! (1)    when I try to run the map through hammer. 
![untitled](https://user-images.githubusercontent.com/30851945/29150335-d86d8752-7d47-11e7-989c-88e1432cc3ee.png) 
Also, I think for some reason it looks like I have more files than I should in my styled folder.
![styled](https://user-images.githubusercontent.com/30851945/29150411-6a50b1da-7d48-11e7-8e3d-cc6e3ad36ce0.png)

**Comment by TeamSpen210** [comment]
The console log states that you compiled the map outside of the `styled` folder. That's you're problem.

**Comment by WheatlyInc** [comment]
Looking at that screenshot, I must have loaded a different map that wasn't in the styled folder, I apologize. Now, I  just got rid of everything in "maps" except the "instances" folder  (i think i was confusing some names of the files that I kept creating during troubleshooting), repaired authorizing tools, and rebuilt the chamber I want to hammeredit in PETI, ( so all I wanted to see was this map's files). Now when I try to pack files into preview in the styled folder 7zip says "not implemented". Tried looking online to see what that means but don't know how it applies here...

**Comment by TeamSpen210** [comment]
7Zip can't pack into BSPs. You'll need another tool.

**Comment by WheatlyInc** [comment]
Used VIDE to pack. When I F9 I spawn falling in a void with no portal gun.     At this point I think I'm pausing on this process and will just attempt to have the same elements created through hammer. I'll update if I somehow manage to get the beemap running in hammer, but in the mean time thank you for trying to help anyway
