### ISSUE TITLE
Additional stylevars for Original Clean

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#709]
These would just control how close it is to the original PeTI style.

- Fancy Angled Panels: Toggle the "special texture" for angled panels.
- Angled Targets: Toggle faithplate targets appearing on angled panels.
- Legacy Vertical Obs. Rooms: Toggle the alternate layouts on floor/ceiling aligned observation rooms. (Originally, they were just tilted versions of the regular observation room)
- No Static Models: Pistons, stairs and panels will always use their normal models.
- Original Corridors Only: Do not use any of the new corridors implemented. (This would not be necessary if #698 is to be implemented) 

Useful if you want the new items, but still want your chamber to look normal.

**Comment by TeamSpen210** [comment]
For 2, that's really just fixing a bug, I'm not sure why you'd not want to see the target. If you really don't want it, you could put it in a room inside the floor/wall.
3 can only really be done via bugs or BEE, so there's not much point. It looks silly anyway. For 5, the corridors are actually majorly modified even if you can't see it, to add Aperture Tag support, monoportal gun support, and other stuff.

**Comment by ncrecc** [comment]
For 5, if the modifications don't actually change the appearance of the corridor, they should be kept.

**Comment by TeamSpen210** [comment]
Stairs now have a toggle for choosing if you want the panel or block version, so this is implemented.
