### ISSUE TITLE
Has Mac compatibility been dropped?

### ISSUE THREAD

**Issue by MeepJJ** [BEEmod/BEE2.4#711]
I have realized that there are no application packages since Pre - Release 23, has mac been dropped?

Also, whenever I try to use one of the supported versions of Bee2, it gives me one of these messages in terminal: (I replaced my name with "**NAME**")

> **dyld: Library not loaded: /opt/local/Library/Frameworks/Python.framework/Versions/3.4/Python
>   Referenced from: /Users/NAME/Downloads/BEE2.4_pr23_mac (1)/bin/BEE2
>   Reason: no suitable image found.  Did find:
> 	/opt/local/Library/Frameworks/Python.framework/Versions/3.4/Python: no matching architecture in universal wrapper
> 	/Library/Frameworks/Python.framework/Versions/3.4/Python: no matching architecture in universal wrapper
> 	/Library/Frameworks/Python.framework/Versions/3.4/Python: no matching architecture in universal wrapper
> 	/opt/local/Library/Frameworks/Python.framework/Versions/3.4/Python: no matching architecture in universal wrapper
> Abort trap: 6**
> 

😟  I have installed Python 3.4

**Comment by Luke18033** [comment]
That's the exact reason we dropped support for it, it was always giving people errors even when they installed Python. Windows doesn't have that issue.
