### ISSUE TITLE
Sometimes BEE randomly deletes the latest map I have worked on.

### ISSUE THREAD

**Issue by CreepiX987** [BEEmod/BEE2.4#713]
It's impossible to continue working on maps if this continues. Pretty sure it's BEE, Portal 2 works normally.

**Comment by Luke18033** [comment]
The thing is, BEE doesn't even know what map you're editing, so this is likely a Valve bug. Just backup your maps frequently.

**Comment by CreepiX987** [comment]
Yeah, that was a problem on my side. Mark as Invalid.
