### ISSUE TITLE
broken piston platform

### ISSUE THREAD

**Issue by Nessusofstyx** [BEEmod/BEE2.4#714]
I have piston platforms in a few of my chambers that aren't connected to anything so that when you step on them they raise/lower. Now that I've installed beemod they aren't working. Any known fixes?

**Comment by LautaroL20** [comment]
@Nessusofstyx - Hey Wheels, at least make a little explanation before closing the issue, so the author can have an idea why you did that.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - Hey Wheels, at least make a little explanation before closing the issue, so the author can have an idea why you did that.

**Comment by TeamSpen210** [comment]
The author figured it out and closed it himself.

**Comment by ZombiePwner1** [comment]
@LautaroL20 Don't you dare accuse me of closing a issue the author closed himself.
