### ISSUE TITLE
Please, optimize the "Copy Music" process, it is insanely slow!!!

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#716]
While exporting, the "Copy Music" process is too slow! Is there a chance that this can be optimized in order to speed up it a bit more? I noticed that when you launch beemod, now it takes much less than it was in past releases so i guess this can also be done for the "Exporting Process" aswell, specially for the "Copy Music" part.

![Image](https://user-images.githubusercontent.com/12244376/29717345-30c95ec8-8985-11e7-9505-ba2beff69c5a.png)

**Comment by TeamSpen210** [comment]
Actually, since we know those files are probably never going to be updated, we can simply check for existing ones and skip immediately if they're there. That'll significantly speed it up after the first time.
