### ISSUE TITLE
Fancy Large Obs. Room Lighting stylevar

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#717]
This would toggle whether the large obs. room has fancy shadow casting or not. Good if you want two large obs. rooms a short distance from each other.

Or perhaps just [do this thing](https://developer.valvesoftware.com/wiki/Env_projectedtexture/fixes#Enabling_multiple_shadow_maps) if it's possible, I don't know since I'm terrible at Hammer.

**Comment by TeamSpen210** [comment]
Nope, that thing requires editing the game's code, which we don't have.

**Comment by TeamSpen210** [comment]
The ideal solution would be BEEmod/BEE2-items#1165.

**Comment by Luke18033** [comment]
> Nope, that thing requires editing the game's code, which we don't have.

And even if we did, it'd only work for a mod.

**Comment by ncrecc** [comment]
What about just removing the fancy shadows?

**Comment by Endermage77** [comment]
Or even a different observation room that is identical to the original in every way except this, maybe?
