### ISSUE TITLE
Outside test chambers

### ISSUE THREAD

**Issue by TheCourierSix** [BEEmod/BEE2.4#719]
Is there any way of making the areas outside of test chambers, or at least bottomless pits?

**Comment by Luke18033** [comment]
For a bottomless pit, select the 3D Factory skybox and place goo at the bottom of the map. There's no way to make proper outside areas yet.

**Comment by Luke18033** [comment]
It'd be better to ask questions like this on [Discord](https://discord.me/beemod), that way we don't constantly open question issues just to have them immediately closed once they're answered.
