### ISSUE TITLE
Why do HMW's save points exist alongside BEE's autosave triggers?

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#72]
There isn't really any reason to have two items that do the exact same thing.

**Comment by BenVlodgi** [comment]
Do they do the exact same thing?
If they do, they can be merged

**Comment by ncrecc** [comment]
They both save your game, so yes they do.

**Comment by jccreszMinecraft** [comment]
The autosave trigger from BEE can be hooked up to inputs to be activated at any time. HMW's Save trigger is simply a save which takes up fewer entities and looks a bit nicer in the editor.

**Comment by jccreszMinecraft** [comment]
The autosave trigger from BEE can be hooked up to inputs to be activated at any time. HMW's Save trigger is simply a save which takes up fewer entities and looks a bit nicer in the editor.

**Comment by TeamSpen210** [comment]
The BEE trigger actually can't take inputs. They are pretty much identical otherwise, except for the editor model.

**Comment by BenVlodgi** [comment]
@TeamSpen210 perhaps we could make a unified one, and possibly run a tool over people's maps to switch to the unified one?

**Comment by Konclan** [comment]
Yeah perhaps there is a way to make it so that one save point will turn into another. And then remove one save point from the pallet.

**Comment by LautaroL20** [comment]
@TeamSpen210 Said he will gona re-work the HWM´s save item to make it save the proggres in the markered boxel, his comment is somewhere the item´ section.
