### ISSUE TITLE
Not working for friends

### ISSUE THREAD

**Issue by TheCourierSix** [BEEmod/BEE2.4#720]
does anyone know why my friend cant see the stuff added by the mod, or activate triggers?
is there some special way I'm supposed to upload it to the workshop?

**Comment by Luke18033** [comment]
Like, you publish a map with BEE and BEE stuff doesn't appear in the published copy?

**Comment by TheCourierSix** [comment]
No. I publish through the game. Am I supposed to do it a different way?

**Comment by Luke18033** [comment]
No, that's what most other people do and it works fine. Do things just not appear at all? Or do they display as "error" models or something?

**Comment by TheCourierSix** [comment]
I put it in the theme of 50s aperture, and it looked like modern.
The catwalks wouldn't appear, and triggers wouldn't work.

**Comment by Luke18033** [comment]
Only when publishing?

**Comment by TheCourierSix** [comment]
it works just fine for me, but if i were to delete the map and download it from the workshop, i would have all of these problems.

**Comment by Luke18033** [comment]
Strange...Maybe @TeamSpen210 would know what's causing this.

**Comment by LautaroL20** [comment]
Please people, provide some screenshots on your posts, it helps a lot.

**Comment by LautaroL20** [comment]
Try out the solution i have commented on: https://github.com/BEEmod/BEE2.4/issues/718

If it does not work, open an issue this time providing one screenshot as very least.
