### ISSUE TITLE
Find out how Alert: Bowling did custom subtitles

### ISSUE THREAD

**Issue by ncrecc** [BEEmod/BEE2.4#722]
http://steamcommunity.com/sharedfiles/filedetails/?id=196546077
http://i.imgur.com/DlFDjl9.mp4

**Comment by TeamSpen210** [comment]
The player model's easy, once you've modelled, rigged and animated it. That's the tricky bit.

**Comment by ncrecc** [comment]
Guessing this is impossible?

**Comment by TeamSpen210** [comment]
The trick they used is to create a `subtitles_bowling` file, then switch the game language to that. It's not really desirable for us, I think it might even persist across level loads. Also that means we're locked to only one language.
