### ISSUE TITLE
Full custom Voices and Music.

### ISSUE THREAD

**Issue by Tjmcnee** [BEEmod/BEE2.4#724]
I've been making a series of chambers called _**Infinity.**_ But to make it make sense I need to add a custom voice. No, I can't use hammer because I don't know how to upload hammered tests. Please add Custom Voices and Music. Thanks!

**Comment by Luke18033** [comment]
You can already do this, just create a custom package and put your voice lines in it. Note though that it's not possible to properly translate custom voice lines, or add subtitles.

**Comment by Luke18033** [comment]
And before you ask, no, we're not making a create-a-package-for-you tool.
