### ISSUE TITLE
Error In my custom package (info.txt}

### ISSUE THREAD

**Issue by Tjmcnee** [BEEmod/BEE2.4#726]
What's my error? I don't understand.
Here's my file:
[info.txt](https://github.com/BEEmod/BEE2.4/files/1265521/info.txt)

**Comment by TeamSpen210** [comment]
The keys and values need to be on the same line. Additionally the '...' isn't actually part of anything, that's just saying you can put more things in there. Compare to existing files:
https://github.com/BEEmod/BEE2-items/blob/2702a05e4652689c845e5ccafca939d190a5ed8d/packages/extra/music/info.txt

**Comment by Tjmcnee** [comment]
Ok, But to make things less complicated, Is there a guide for making custon packages?

**Comment by LautaroL20** [comment]
Yes, there are some Bee´s Wiki pages where you can take a look, see if it helps:

1. Editoritems: https://github.com/BEEmod/BEE2-items/wiki/editoritems.txt
2. Package Format: https://github.com/BEEmod/BEE2-items/wiki/Package-Format
3. vbsp_config_options: https://github.com/BEEmod/BEE2-items/wiki/vbsp_config_options
4. Info.txt: https://github.com/BEEmod/BEE2-items/wiki/info.txt
5. vbsp_config_conditions: https://github.com/BEEmod/BEE2-items/wiki/vbsp_config_conditions
