### ISSUE TITLE
Rocket Turret Problems

### ISSUE THREAD

**Issue by homelessturret** [BEEmod/BEE2.4#731]
It seems the rocket turrets lock on, but they don't fire, the firing sound effect is made but no actual eplosion.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1984

**Comment by homelessturret** [comment]
@LautaroL20 This isn't a duplicate, i can see the rocket turret and it (sort of) works, it just doesn't fire rockets.

**Comment by LautaroL20** [comment]
Its a duplicate, the original post says "And if it appears in the map, its really buggy".

**Comment by homelessturret** [comment]
Regardless, i hope this can be fixed in V26

**Comment by LautaroL20** [comment]
I doubt, this item has been ignored for a while.
