### ISSUE TITLE
Entry And Exit Glitches

### ISSUE THREAD

**Issue by lucan8tor** [BEEmod/BEE2.4#732]
Whenever I try to load/build my own map or play one of my own maps It'll load fine, but the entry and exit areas will be all screwed up and make It impossible to get into the map without using noclip. I have tried setting the entry as "entry door" instead of "elevator" and many other options but the glitch will still occur.

Screenshots:
![preview0002](https://user-images.githubusercontent.com/24628416/30197110-b361a940-9433-11e7-8c6d-89d2d548f209.jpg)
![preview0003](https://user-images.githubusercontent.com/24628416/30197113-b7f0da9e-9433-11e7-914a-8896dc79400a.jpg)
![preview0004](https://user-images.githubusercontent.com/24628416/30197114-be3f7bbc-9433-11e7-827b-09972cb500c9.jpg)
![preview0005](https://user-images.githubusercontent.com/24628416/30197118-c2c51b6a-9433-11e7-8e8f-0104dda0dcae.jpg)
![preview0006](https://user-images.githubusercontent.com/24628416/30197121-c8474f0e-9433-11e7-9a85-01277a4cfd3a.jpg)

Please tell me how to fix this, thank you.

**Comment by ZombiePwner1** [comment]
LOL That is a serious and funny bug however i'm not sure what could be causing this ask @TeamSpen210

**Comment by lucan8tor** [comment]
How should I contact him?

**Comment by lucan8tor** [comment]
Oh, nevermind. I verified the game files and that seems to have fixed It. Sorry for the inconvenience, I'm just dumb. :p
