### ISSUE TITLE
A simple suggestion

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2.4#734]
Allow custom loading screens
Examples:
- Old Aperture takes the Old Aperture loading screen, same withe rest of the styles but with their loading screens.
-Allow people to put in custom images i.e a picture of their chamber.

**Comment by ZombiePwner1** [comment]
Custom loading screens for people putting in their chambers is not possible to do as for style loading screens this is possible to do @TeamSpen210 needs to figure out a way to do so.

**Comment by TeamSpen210** [comment]
It's not possible.
