### ISSUE TITLE
Fix Reflection Gel

### ISSUE THREAD

**Issue by WhoozYerBuddy** [BEEmod/BEE2.4#735]
![20170913093551_1](https://user-images.githubusercontent.com/29020282/30389252-3808c930-9867-11e7-9368-7190c7b70562.jpg)

It would be great if it it worked correctly with gelled light bridges and the sendificator.

**Comment by WhoozYerBuddy** [comment]
Oops, this should probably go in packages issues.

**Comment by ZombiePwner1** [comment]
We can't fix reflection gel using propulsion gel's color on light bridges unfortunately it's been coded to do that.

**Comment by WhoozYerBuddy** [comment]
Lol, I wasn't commenting on the color.  I was commenting on the fact that it doesn't reflect the laser.

**Comment by ZombiePwner1** [comment]
Whoops but yeah we can't fix that either unless valve actually updates the gel.
