### ISSUE TITLE
Add unused adhesive gel and Portal Stories: Mel portal gun option

### ISSUE THREAD

**Issue by EwokPilot** [BEEmod/BEE2.4#739]
I think it's a good idea to add the option to change the gun to the Portal Stories: Mel gun like you can with the Portal 1 gun. Also adhesive gel is a really interesting test element that would be fun to use! Thanks for reading!

**Comment by Luke18033** [comment]
See [here](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-adhesion-gel-to-bee24) and [here](https://github.com/BEEmod/BEE2-items/issues/1052#issuecomment-325162580), and this is also a BEE2-items issue.
