### ISSUE TITLE
Decor for overgrown.

### ISSUE THREAD

**Issue by Tjmcnee** [BEEmod/BEE2.4#740]
Can you make a item for the overgrown style? Like plants, moss and debris so I can make my levels have more detail. Can you do that?

**Comment by ZombiePwner1** [comment]
A feature like this is already in place we just haven't released it with the mod yet. I'm unsure when @TeamSpen210 will release although i'd like him to release it for prl 26.

**Comment by LautaroL20** [comment]
I doubt that the decoration feature will be abailavle even in the PRL27.

**Comment by TeamSpen210** [comment]
I really need to rebuild it from scratch, the original way I did it wasn't that good.

**Comment by ZombiePwner1** [comment]
@TeamSpen210 Please release it ASAP
