### ISSUE TITLE
Art Therapy Style for Chambers

### ISSUE THREAD

**Issue by Spearkiller** [BEEmod/BEE2.4#741]
Could we possibly get an Art Therapy (the theme from the bonus Co-Op campaign track) as a theme for our chambers, so we can get the look of a chamber that is falling apart, but not overgrown?
I mainly speak for myself here, but I personally think that would be pretty neat.

Thanks in advance 😊

**Comment by ZombiePwner1** [comment]
Art therapy is already in development however the style will not be released for awhile as it's quite unfinished.
