### ISSUE TITLE
Is art therapy ever coming back? 

### ISSUE THREAD

**Issue by wimklaver** [BEEmod/BEE2.4#745]
this might not be the correct place to ask, but im just curious if the Art Therapy style is coming back to BEEmod.

**Comment by Luke18033** [comment]
BEEmod/BEE2-items#95

**Comment by ZombiePwner1** [comment]
@wimklaver Yes art therapy style is coming back it just hasn't been worked on in awhile.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
Now lets cross the fingers so the developer gets their hands on the almost dead art therapy branch.........

**Comment by ZombiePwner1** [comment]
Art therapy will come it's just @TeamSpen210 needs to get back to it.
