### ISSUE TITLE
Can you import custom items?

### ISSUE THREAD

**Issue by Nikodemonek** [BEEmod/BEE2.4#747]
I would really loved to see if you can import custom items

EDIT: Can you add custom items to the bee2.4 application?

Thanks
--Nikodemonek

**Comment by seagemgames** [comment]
Not at the moment.
This issue is very vague, could you give info like:

- What sort of files they need to be
- Is this a suggestion or a question

**Comment by Nikodemonek** [comment]
VMF. files and this is a question

**Comment by LautaroL20** [comment]
Yes, but you have to do it manually. This implies you will have to make their respective folders for it and the required syntax files such as editoritems.txt, properties.txt and info.txt, you can take an example of this on my Half-Grate item to see how it works.
