### ISSUE TITLE
New Template´s Entity: bee2_template_visgroup_controller

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#754]
We need to implement a new template entity to controll the visgroups to skip and the visgroups to add, this would be pretty much helpful to avoid a lot of intrincate conditions on the configuration files that always ends up being something very convoluted and messy, since sometimes it breaks the compiler generating mysterious brushes everywhere.

This is why we really need to having a new entity config to make this much easier and effective without running the risk of breaking the compiler in a "mysterious way" for having convoluted stuff.

_______________________________________________________________________________

## Suggestion: 
Make this entity based in some fundamental functions such as choosing the number´s priority being the the highest the preffered and also Snap To Grid for items that handles 8 positions, as seen in the "colorpiker" template. 

**Visgroups to avoid:** The user will writte those who shouldn´t generate when the item is on contact with an specific surface.
**Visgroups to add:** The user will writte those who should actually be generated when the item is on contact with an specific surface. 

Conept Art:
![IMAGE](https://user-images.githubusercontent.com/12244376/31420706-8c8f1bf4-ae19-11e7-87aa-61c98f1e6a5e.png)

This means we will be able to administer lot of visgroup stuff without having to make other template instances just to have the configuration file clear and ordered.

Then we will be able to handle aditional brushes using an unique template for when the item needs it, without losing our heads for making convoluted configurations on vbsp_config.cfg

**Comment by gradystudios** [comment]
this sucks!

**Comment by LautaroL20** [comment]
@gradystudios - You do not even have idea for what is this though, so arguing with you would be a waste of time.

**Comment by LautaroL20** [comment]
I most likely solved in the past the issue i was having.
