### ISSUE TITLE
If combined fizzler are set to be both laser & fizzler, it starts weird

### ISSUE THREAD

**Issue by sebastiannielsen** [BEEmod/BEE2.4#762]
The combined fizzler are supposed to be in one of 4 states:
Completely off
Red fizzler
Blue fizzler
Red lasers

However, if its configured to start in the "Red fizzler" mode (start enabled + start reversed), it will also display the red lasers incorrectly, looking super weird and once you trigger one of its input, it will behave as it should.

![20171020045802_1](https://user-images.githubusercontent.com/1034930/31803430-f41c1376-b553-11e7-9c4b-81943f211a92.jpg)

**Comment by ZombiePwner1** [comment]
Moved to: https://github.com/BEEmod/BEE2-items/issues/2293
