### ISSUE TITLE
can you make a update adding more new stuff and adding old stuff back?

### ISSUE THREAD

**Issue by gradystudios** [BEEmod/BEE2.4#763]
alright last time i got hated for this! but i need more things like glados the old king turret and maby a diffrent skin mode for the portal gun! i just need more

from a fan gradystudios.

**Comment by SW50000** [comment]
They have already planned on adding them back in.
One more thing, can you please calm down?

**Comment by ZombiePwner1** [comment]
@gradystudios The old stuff from the original beemod will be implemented and like with @SW50000 please calm down and stop getting so angry.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
@gradystudios Actually, what you really need is go back to kindergarten, or to the madhouse if you are +18.....

**Comment by TeamSpen210** [comment]
GLaDOS and Animal King will not be added. BEE2 is for making puzzles, not random maps. It is *not* an "easy Hammer"..

**Comment by ZombiePwner1** [comment]
@HelloIamaPersonThatIsAliveAndHealthily Please do not post inappropriate or rude comments.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment]
To foolish words, foolish replys. To brillant arguments, brillant replies... I can stay on both sides depending on the person.

**Comment by ZombiePwner1** [comment]
@HelloIamaPersonThatIsAliveAndHealthily Well i'm just asking you to please not post rude comments and to stay on our good side.
