### ISSUE TITLE
P1 elevator glitch

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2.4#764]
If you place a portal right next to the elevator worldportal, while being in the tiny elevator room, you can walk slowly enough by walking into the wall at an angle, then glitch the worldportal.

**Comment by Fazbear189** [comment]
Whats a worldportal?

**Comment by BETTEREXTENEDEDITORMOD** [comment]
[facepalms]

**Comment by LautaroL20** [comment]
A screenshot would help, i think that a similar issue was reported and later closed because was unfixeable. Since you didn´t attach an image, i can´t be sure if this is a duplicate.

**Comment by LautaroL20** [comment]
Anything related to items, must be posted here: https://github.com/BEEmod/BEE2-items/issues

This issue was moved to the item´s page: https://github.com/BEEmod/BEE2-items/issues/2317

**Comment by IceTudor** [comment]
Not an item issue, finish a P1 Style level. Go to the elevator, right where the light cuts since the worldportal, walk into the wall at such a sharp angle, that you can somehow get past the world portal, I have no idea what is happening at that time but I know for sure the "trippy void" glitch happens at the same time.

**Comment by Luke18033** [comment]
Styles also fall under BEE2-items. This repro is only for issues related to the application itself.

**Comment by IceTudor** [comment]
Oh... strange.
