### ISSUE TITLE
Portal 1 Portal Gun

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#765]
When I have the P1 portal gun on the thing that holds it(it may happen when you spawn with the gun too) once I grab the gun and die when I grab the gun again it uses the portal 2 model and portal 2 sounds.

**Comment by LautaroL20** [comment]
Anything related to items, must be posted here: https://github.com/BEEmod/BEE2-items/issues

This issue was moved to: https://github.com/BEEmod/BEE2-items/issues/2316
