### ISSUE TITLE
When ever I make a Portal 1 map it shows.......

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2.4#766]
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/p1/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/p1/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/p1/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/p1/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/p1/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/p1/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/p1/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/p1/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/p1/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/p1/items/rex/pellet_dest/static_4.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 12 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 4
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 7
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (16 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[ERROR] cond.core.check_all(): Error in <BEE2_SIGNAGE>/items/sign_p1:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 483, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1207, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1207, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\entities.py", line 98, in res_insert_overlay
  File "F:\Git\BEE2.4\src\template_brush.py", line 466, in import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 424, in get_template
template_brush.InvalidTemplateName: Template not found: "bee2_signage_clean_arrow"
Valid templates:
 * "__TILING_TEMPLATE__"
 * "BEE2_ANGLED_BLOCK_30"
 * "BEE2_ANGLED_BLOCK_45"
 * "BEE2_ANGLED_BLOCK_60"
 * "BEE2_ANGLED_BLOCK_CORNER_30"
 * "BEE2_ANGLED_BLOCK_CORNER_45"
 * "BEE2_ANGLED_BLOCK_CORNER_60"
 * "BEE2_BALL_BUTTON_BASE_BTS"
 * "BEE2_BALL_BUTTON_BASE_P1_WHITE"
 * "BEE2_BLOCK_128_32_32"
 * "BEE2_BLOCK_128_64_64"
 * "BEE2_BLOCK_64_64_64"
 * "BEE2_BLOCK_WINDOW_FULL"
 * "BEE2_BLOCK_WINDOW_LOW"
 * "BEE2_BLOCK_WINDOW_MID"
 * "BEE2_BTS_GRATING_TEMPLATE"
 * "BEE2_CONVEYOR_COVER_CLEAN"
 * "BEE2_CONVEYOR_COVER_OVER"
 * "BEE2_CONVEYOR_COVER_PORTAL_1"
 * "BEE2_CONVEYOR_RETRO"
 * "BEE2_CONVEYOR_TUNNEL_TILE_CLEAN"
 * "BEE2_CUBE_BUTTON_BASE_BTS"
 * "BEE2_CUBE_DROPPER_BTS_CAP"
 * "BEE2_CUBE_DROPPER_CLEAN_CAP"
 * "BEE2_CUBE_DROPPER_RETRO_CAP"
 * "BEE2_CUTOUT_TILE_FLOOR_PILLAR"
 * "BEE2_CUTOUT_TILE_FLOOR_SIDE_DETAIL"
 * "BEE2_CUTOUT_TILE_FLOOR_SIDE_WORLD"
 * "BEE2_DYNAMIC_PAN_ANGLED_P1"
 * "BEE2_EMBEDDED_VOXEL"
 * "BEE2_FLAT_HALF"
 * "BEE2_FLAT_QUARTER"
 * "BEE2_FLAT_THREE_QUARTER"
 * "BEE2_FLOOR_BUTTON_BASE_BTS"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_BALL"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_CUBE"
 * "BEE2_FLOOR_BUTTON_BASE_CLEAN_WEIGHTED"
 * "BEE2_FLOOR_BUTTON_BASE_P1_WHITE"
 * "BEE2_FUTBOL_SURF_BACK"
 * "BEE2_FUTBOL_SURF_BACK_50S"
 * "BEE2_FUTBOL_SURF_BACK_P1"
 * "BEE2_GLASS_DOOR_CLEAN"
 * "BEE2_GLASS_DOOR_RETRO"
 * "BEE2_HALF_PANEL_TOP_50S"
 * "BEE2_HALF_PANEL_TOP_80S"
 * "BEE2_HALF_PANEL_TOP_CLEAN"
 * "BEE2_HALF_PANEL_TOP_P1"
 * "BEE2_HMW_SENDTOR_BASE_SLAB"
 * "BEE2_HMW_SENDTOR_BASE_SLAB_OVER"
 * "BEE2_HMW_SENDTOR_TOP_SLAB_P1"
 * "BEE2_MONITOR_COVER_CLEAN"
 * "BEE2_MONITOR_COVER_P1"
 * "BEE2_NEUROTOXIN_TIMER_COVER_CLEAN"
 * "BEE2_NEUROTOXIN_TIMER_COVER_OVER_LEFT"
 * "BEE2_NEUROTOXIN_TIMER_COVER_OVER_RIGHT"
 * "BEE2_NEUROTOXIN_TIMER_COVER_P1"
 * "BEE2_NEUROTOXIN_VENT_50S"
 * "BEE2_NEUROTOXIN_VENT_CLEAN"
 * "BEE2_NEUROTOXIN_VENT_P1"
 * "BEE2_OVER_BALL_BUTTON_BASE"
 * "BEE2_OVER_CUBE_BUTTON_BASE"
 * "BEE2_OVER_FLOOR_BUTTON_BASE"
 * "BEE2_OVER_PED_BASE"
 * "BEE2_OVER_STAIRS_TOP_1"
 * "BEE2_OVER_STAIRS_TOP_2"
 * "BEE2_OVER_STAIRS_TOP_3"
 * "BEE2_OVER_STAIRS_TOP_4"
 * "BEE2_P1_DRAWBRIDGE_DOWN"
 * "BEE2_P1_DRAWBRIDGE_UP"
 * "BEE2_P1_GLASS_BEAM"
 * "BEE2_P1_GLASS_TEMPLATE"
 * "BEE2_P1_GRATING_TEMPLATE"
 * "BEE2_RETRO_MECH_PLATE_ANGLED"
 * "BEE2_RETRO_MECH_PLATE_STRAIGHT"
 * "BEE2_ROCKET_TURRET_CAP_CLEAN"
 * "BEE2_SIGNAGE_50S_ARROW"
 * "BEE2_SIGNAGE_50S_ARROW_REV"
 * "BEE2_SIGNAGE_50S_EXIT"
 * "BEE2_SIGNAGE_50S_EXIT_REV"
 * "BEE2_SIGNAGE_50S_EXIT_WALL"
 * "BEE2_SIGNAGE_50S_NUM"
 * "BEE2_SIGNAGE_50S_NUM_REV"
 * "BEE2_SIGNAGE_50S_NUM_WALL"
 * "BEE2_SIGNAGE_50S_SIGN"
 * "BEE2_SIGNAGE_50S_SIGN_REV"
 * "BEE2_SIGNAGE_50S_SIGN_WALL"
 * "BEE2_SIGNAGE_70S_ARROW"
 * "BEE2_SIGNAGE_70S_ARROW_REV"
 * "BEE2_SIGNAGE_70S_ARROW_WALL_REV"
 * "BEE2_SIGNAGE_70S_SIGN2_FLOOR"
 * "BEE2_SIGNAGE_70S_SIGN2_FLOOR_REV"
 * "BEE2_SIGNAGE_70S_SIGN_FLOOR"
 * "BEE2_SIGNAGE_70S_SIGN_REV"
 * "BEE2_SIGNAGE_70S_SIGN_WALL"
 * "BEE2_SIGNAGE_BTS_ARROW"
 * "BEE2_SIGNAGE_BTS_ARROW_REV"
 * "BEE2_SIGNAGE_BTS_LONG"
 * "BEE2_SIGNAGE_BTS_LONG_REV"
 * "BEE2_SIGNAGE_BTS_NUM"
 * "BEE2_SIGNAGE_BTS_NUM_REV"
 * "BEE2_SIGNAGE_BTS_RECT"
 * "BEE2_SIGNAGE_BTS_RECT_REV"
 * "BEE2_SIGNAGE_CLEAN"
 * "BEE2_STAIRS_TOP"
 * "BEE2_STATIC_PAN_ANGLED"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_50S"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_70S"
 * "BEE2_STATIC_PAN_ANGLED_BLACK_80S"
 * "BEE2_STATIC_PAN_ANGLED_BTS"
 * "BEE2_STATIC_PAN_ANGLED_P1"
 * "BEE2_STATIC_PAN_ANGLED_WHITE_50S"
 * "BEE2_STATIC_PAN_ANGLED_WHITE_80S"
 * "BEE2_STATIC_PAN_FLAT"
 * "BEE2_STATIC_PAN_FLAT_P1"
 * "BEE2_STATIC_PAN_FLAT_RETRO"
 * "BEE2_STATIC_STAIRS_CLEAN_EXTENDED"
 * "BEE2_STATIC_STAIRS_CLEAN_RETRACTED"
 * "BEE2_STATIC_STAIRS_STATIC_BEAMS_OVER"
 * "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP"
 * "BEE2_TBEAM_FRAME"
 * "BEE2_TRACK_PLAT_BOTTOM"
 * "BEE2_TRACK_PLAT_MIDDLE"
 * "BEE2_TRACK_PLAT_SINGLE"
 * "BEE2_TRACK_PLAT_TOP"
 * "BEE2_TURRET_DROPPER_50S_CAP"
 * "BEE2_TURRET_DROPPER_P1_CAP"
 * "BEE2_VACTUBE_CORNER_CLEAN"
 * "BEE2_VACTUBE_CORNER_RETRO"
 * "BEE2_WALL_HALF"
 * "BEE2_WALL_HALF_CENTER"
 * "BEE2_WALL_PLUS"
 * "BEE_DOOR_COWL_CLEAN"
 * "BEE_DRAW_BRIDGE_CLEAN"
 * "BEE_DRAW_BRIDGE_OVER"
 * "BEE_HEP_CATCHER_BASE_CLEAN"
 * "BEE_HEP_CATCHER_BASE_P1_EXTENDED"
 * "BEE_HEP_CATCHER_BASE_P1_FLAT"
 * "BEE_HEP_CATCHER_BASE_P1_PISTON"
 * "BEE_HEP_EMITTER_BASE_CLEAN"
 * "BEE_HEP_EMITTER_BASE_P1"
 * "BEE_HEP_EMITTER_BASE_P1_SIGN"
 * "BEE_PGUN_BASE"
 * "BEE_VENT_BASE_50S"
 * "BEE_VENT_BASE_CLEAN"
 * "LAUTARO_PEDESTAL_BASE_80S"
 * "LAUTARO_PEDESTAL_BASE_BTS"
 * "LAUTARO_PEDESTAL_BASE_BTS_REV"
 * "LAUTARO_PEDESTAL_BASE_CLEAN"
 * "LAUTARO_PEDESTAL_BASE_OVER"
 * "LAUTARO_PEDESTAL_BASE_P1"
 * "LAUTARO_PEDESTAL_BASE_RETRO"
 * "LAUTARO_PROTRUDING_PED_BASE_80S"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK_REV"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE"
 * "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE_REV"
 * "LAUTARO_PROTRUDING_PED_BASE_CLEAN"
 * "LAUTARO_PROTRUDING_PED_BASE_OVER"
 * "LAUTARO_PROTRUDING_PED_BASE_P1"
 * "LAUTARO_PROTRUDING_PED_BASE_RETRO"
 * "LAUTARO_RECLINED_WALL_PILLAR_BTS"
 * "LAUTARO_RECLINED_WALL_PILLAR_CLEAN_OVER"
 * "LAUTARO_RECLINED_WALL_PILLAR_P1_RETRO"
 * "LAUTARO_STANDING_FIZZLER_BTS_OVERLAY"
 * "LAUTARO_STANDING_WALL_PILLAR_BTS"
 * "LAUTARO_STANDING_WALL_PILLAR_CLEAN_OVER"
 * "LAUTARO_STANDING_WALL_PILLAR_P1_RETRO"
 * "REX_CUBE_DEFLECTOR_TEMP_CLEAN"
 * "REX_CUBE_DEFLECTOR_TEMP_P1"
 * "REX_CUBE_DEFLECTOR_TEMP_RETRO_METAL"
 * "REX_CUBE_DEFLECTOR_TEMP_RETRO_WOOD"
 * "REX_PELLET_FIELD_TEMP"
 * "REX_PELLET_FIELD_TEMP_RETRO"
 * "STANDING_WALL"
 * "TSPEN_BTN_PED_CLEAN_BASE"
 * "TSPEN_BTN_PED_P1_BASE"
 * "TSPEN_CHAMBERLOCK_CLEAN"
 * "TSPEN_CHAMBERLOCK_P1"
 * "TSPEN_CHECKPOINT_SINGLE_CAP_P1"
 * "TSPEN_LARGE_FAITH_RETRO_BORDER"
 * "TSPEN_LARGE_FAITH_RETRO_MECH_BACK"
 * "TSPEN_LARGE_FAITH_TRIG"
 * "TSPEN_LARGE_FAITH_TRIG_SQUARE"
 * "WOM_CONDUCTOR_50S_BLACK"
 * "WOM_CONDUCTOR_50S_WHITE"
 * "WOM_CONDUCTOR_CLEAN"
 * "WOM_CONDUCTOR_P1"

**Comment by LautaroL20** [comment]
This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!
