### ISSUE TITLE
[OUTDATED] Beemod Version 2.7 pre-realise launch error:''api-ms-win-crt-runtime-l1-1-0.dll not created to be executed on windows (don't try changing the text haha)

### ISSUE THREAD

**Issue by Thelucas7** [BEEmod/BEE2.4#767]
everytime i open beemod 2.7 prerealise this appears ''api-ms-win-crt-runtime-l1-1-0.dll not created to be executed on windows and saying to me contact the creator and the rest is nothing informative..

i used beemod version 2.4 prerealise and this never happend.

# Edit: i have the Universal C Runtime Update for the Windows 7,but it still dosen't work.
# EDIT2: plz don't change the text this thread is dead and i don't use it anymore

**Comment by LautaroL20** [comment]
@Thelucas7 - Are you running beemod on Linux, Mac or Windows?

**Comment by Thelucas7** [comment]
Windows 7.

**Comment by LautaroL20** [comment]
@Thelucas7 - You will have to ensure some things: 

1. Make sure to have downloaded not only the release 27 Application, but also the Packages 27 that has all the items.

2. You will need to have full permissions, you google on this since windows may be stopping some beemod features from running due to limited permissions. Also, try running beemod as an administrator.

**Comment by Thelucas7** [comment]
1.yes,i have the packages 27 downloaded. and it's on the beemod/packages. (yes,it's extracted.)

2.nothing helped.

i guess it's bad luck for me? ;=;

that sounds weird since i had Pre realise 2.4 and this never happend.

**Comment by LautaroL20** [comment]
@Thelucas7 - It seems you have to download an update for your operative system, here is the link: https://support.microsoft.com/help/2999226/update-for-universal-c-runtime-in-windows

Also, make sure you have unzipped both the application and packages zip files into a same folder.

**Comment by Thelucas7** [comment]
ok,later i will say if it will work.

**Comment by Thelucas7** [comment]
it look's like the updater is broken.
it keeps looking for updates forever. searched on google obviously,nothing helped.
i'l guess theres nothing left to do /=

**Comment by Thelucas7** [comment]
WAIT A MINUTE
The update is already installed in my pc! it was a few months ago!
but bee2 dosen't work? What the hell is going on?!?

i'm going to download the files again starting 0% to try if something helps..

**Comment by DonSalierii** [comment]
I've got the same problem. Any help?

**Comment by LautaroL20** [comment]
Pre-release 28 is out, try out that latest version. This issue seems to be about the outdated 27 version.

**Comment by DonSalierii** [comment]
Still not working, always the same error message :/

**Comment by LautaroL20** [comment]
Idk what could be causing this mysteriousness... Try googling the error and follow steps there.

**Comment by DonSalierii** [comment]
After some research, I only found problems where the dll was missing, and not "not created to be executed on windows". I will still continue to search a bit.

**Comment by LautaroL20** [comment]
Keep searching, since as for the error clearly indicates that is not Beemod´s fault.

**Comment by LautaroL20** [comment]
@DonSalierii - Did you finally solve your issue or you just gave up?

**Comment by LautaroL20** [comment]
@DonSalierii and @Thelucas7 - For some remote reason, are you running Beemod on a 32 Bit version of Windows? If this is the case, then that may be the reason of your issues then. For more proof on this, see: https://github.com/BEEmod/BEE2.4/issues/836

**Comment by Thelucas7** [comment]
well i did give up at the time,and i don't play portal 2 anymore but i have a 32 bit os..

**Comment by LautaroL20** [comment]
That was exactly the cause of your issue, Beemod seems not work so well on 32 bit operative systems then.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
