### ISSUE TITLE
Bee2 Crash after trying to implement custom fizzler

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#768]
@ellingtonvengaboysmuseum said the folowing:

"@TeamSpen210 or @Luke18033 - can someone tell me what is causing this error, i am trying to implement a new custom fizzler

![photo 800 - copy](https://user-images.githubusercontent.com/11165643/32191522-c7eea4a8-bd87-11e7-9992-aedaddf8597e.jpg)"

**Comment by ellingtonvengaboysmuseum** [comment]
Also here is the code from the info.txt file of the custom fizzler

"ID" "WARIO_LCEF_FIZZLER"
"Name" "Classified Fizzler"
"Desc" "Classified Until Release."
"Item"
{
"ID" "ITEM_WARIO_LCEF_FIZZLER"
"Authors" "Wario"
"Tags" "Fizzlers"
"Description"
{
"" "Classified.  "
"" "Until.  "
"" "Release."
}
"Version"
{
"Styles"
{
"BEE2_CLEAN" "lcef_fizz"
"BEE2_OVERGROWN"
{
"Folder" "lcef_fizz"
"Instances"
{
"1" "instances/BEE2/over/items/wario/lcef_fizz_model.vmf"
"bee2_static" "instances/BEE2/over/items/wario/lcef_fizz_model_static.vmf"
}
"Replace"
{
"PACK_WARIO_LCEF_FIZZ_MDL_CLEAN" "PACK_WARIO_LCEF_FIZZ_MDL_OVER"
}
}
"BEE2_1950s"
{
"Folder" "lcef_fizz"
"Instances"
{
"0" "instances/BEE2/50s/items/wario/lcef_fizz_base.vmf"
"1" "instances/BEE2/50s/items/wario/lcef_fizz_model.vmf"
}
"Replace"
{
"PACK_WARIO_LCEF_FIZZ_MDL_CLEAN" "PACK_CUST_FIZZLER_RETRO"
"PACK_WARIO_LCEF_FIZZ_CLEAN" "PACK_WARIO_LCEF_FIZZ_RETRO"
"BEE2/fizz/lcef_fizz/" "BEE2/fizz/lcef_fizz/retro_"
":bee2_static>" ":fizz_model>"
}
}
"BEE2_PORTAL_1"
{
"Folder" "lcef_fizz"
"Instances"
{
"0" "instances/BEE2/p1/items/wario/lcef_fizz_base.vmf"
"1" "instances/BEE2/p1/items/wario/lcef_fizz_model.vmf"
}
"Replace"
{
"PACK_WARIO_LCEF_FIZZ_MDL_CLEAN" "PACK_P1_CUST_FIZZLER"
":bee2_static>" ":fizz_model>"
}
}
}
}
}
"PackList"
{
"ID" "PACK_WARIO_LCEF_FIZZ_MDL_CLEAN"
"Config"
{
"" "materials/BEE2/models/props_clean/wario/lcef_fizz_front.vmt"
"" "materials/BEE2/models/props_clean/wario/lcef_fizz_front.vtf"
"" "models/BEE2/props_clean/wario/lcef_fizz_static.mdl"
"" "models/BEE2/props_clean/wario/lcef_fizz.mdl"
}
}
"PackList"
{
"ID" "PACK_WARIO_LCEF_FIZZ_MDL_OVER"
"Config"
{
"" "materials/BEE2/models/props_clean/wario/lcef_fizz_front_dirty.vmt"
"" "materials/BEE2/models/props_clean/wario/lcef_fizz_front_dirty.vtf"
"" "models/BEE2/props_clean/wario/lcef_fizz_static.mdl"
"" "models/BEE2/props_clean/wario/lcef_fizz.mdl"
}
}
"PackList"
{
"ID" "PACK_WARIO_LCEF_FIZZ_CLEAN"
"Config"
{
"" "materials/BEE2/fizz/lcef_fizz/lcef_fizz_bounds.vtf"
"" "materials/BEE2/fizz/lcef_fizz/lcef_fizz_bounds_l.vtf"
"" "materials/BEE2/fizz/lcef_fizz/lcef_fizz_bounds_r.vtf"
"" "materials/BEE2/fizz/lcef_fizz/lcef_field.vmt"
"" "materials/BEE2/fizz/lcef_fizz/lcef_center.vmt"
"" "materials/BEE2/fizz/lcef_fizz/lcef_left.vmt"
"" "materials/BEE2/fizz/lcef_fizz/lcef_right.vmt"
}
}
"PackList"
{
"ID" "PACK_WARIO_LCEF_FIZZ_RETRO"
"Config"
{
"" "BEE2/fizz/lcef_fizz/lcef_field.vmt"
"" "BEE2/fizz/lcef_fizz/retro_lcef_field.vmt"
"" "BEE2/fizz/lcef_fizz/retro_lcef_center.vmt"
"" "BEE2/fizz/lcef_fizz/retro_lcef_left.vmt"
"" "BEE2/fizz/lcef_fizz/retro_lcef_right.vmt"
}
}

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 or @BenVlodgi - Also here is the code from the vbsp config file of the custom fizzler that is causing the bee crash... do you see anything wrong in here...

"Fizzlers"
	{
		"Fizzler"
		{
			"ID" "WARIO_LCEF_FIZZLER"
			"Item_ID" "ITEM_WARIO_LCEF_FIZZLER"
			"Base_Inst" "<ITEM_WARIO_LCEF_FIZZLER:fizz_base>"
			"Base_Inst_static" ""
			"Model" "<ITEM_WARIO_LCEF_FIZZLER:fizz_model>"
			"Model_static" "<ITEM_WARIO_LCEF_FIZZLER:bee2_static>"
			"Has" "Fizzler"
			"Has" "wario_lcef_fizz"
			"Pack" "PACK_WARIO_LCEF_FIZZ_CLEAN"
			"Pack" "PACK_WARIO_LCEF_FIZZ_MDL_CLEAN"
			"Brush"
		{
			"Name" "fizz"
			"side_color" "0.07 0.3 0.9"
			"side_vortex" "0.6 2.2 6.8"
			"tex_center" "BEE2/fizz/lcef_fizz/lcef_center"
			"tex_left" "BEE2/fizz/lcef_fizz/lcef_left"
			"tex_right" "BEE2/fizz/lcef_fizz/lcef_right"
			"tex_short" "BEE2/fizz/lcef_fizz/lcef_field"
			"Keys"
			{
				"classname" "trigger_portal_cleanser"
				"spawnflags" "9"
				"visible" "1"
				"usescanline" "0"
				"StartDisabled" "0"
			}
		}
		"Brush"
			{
				"Name" "fizz"
				"tex_trigger" "tools/toolstrigger"
				"singular" "1"
				"Keys"
				{
					"classname" "trigger_multiple"
					"spawnflags" "1"
					"StartDisabled" "0"
					"wait" "0.1"
				}
			}
		}
	}

**Comment by ellingtonvengaboysmuseum** [comment]
@TeamSpen210 or @BenVlodgi - Also here is the code from the editor items file of the custom fizzler that is causing the bee crash... do you see anything wrong in here...

"Item"
{
"Type" "ITEM_WARIO_LCEF_FIZZLER"
"ItemClass" "ItemBarrierHazard"
"Editor"
{
"SubTypeProperty" "HazardType"
"SubType"
{
"Name" "Liquid Coloring Excision Field"
"Model"
{
"ModelName" "fr_compressed_smoke_field.mdl"
}
"Palette"
{
"Tooltip" "LIQUID COLORING EXCISION FIELD"
"Image" "palette/clean/fr/csf.png"
}
"Sounds"
{
"SOUND_CREATED" "P2Editor.PlaceOther"
"SOUND_EDITING_ACTIVATE" "P2Editor.ExpandOther"
"SOUND_EDITING_DEACTIVATE" "P2Editor.CollapseOther"
"SOUND_DELETED" "P2Editor.RemoveOther"
}
}
"SubType"
{
"Name" "UNUSED"
"Model"
{
"ModelName" "bee2_fizz_error.3ds"
}
"Sounds"
{
"SOUND_CREATED" "P2Editor.PlaceOther"
"SOUND_EDITING_ACTIVATE" "P2Editor.ExpandOther"
"SOUND_EDITING_DEACTIVATE" "P2Editor.CollapseOther"
"SOUND_DELETED" "P2Editor.RemoveOther"
}
}
"MovementHandle" "HANDLE_8_POSITIONS"
"DesiredFacing" "DESIRES_HORIZONTAL"
}
"Properties"
{
"ConnectionCount"
{
"DefaultValue" "0"
"Index" "1"
}
"StartEnabled"
{
"DefaultValue" "1"
"Index" "2"
}
"HazardType"
{
"DefaultValue" "0"
"Index" "3"
}
}
"Exporting"
{
"Instances"
{
"0"
{
"Name" "instances/BEE2/clean/items/wario/lcef_fizz_base.vmf"
"EntityCount" "5"
}
"1"
{
"Name" "instances/BEE2/clean/items/wario/lcef_fizz_model.vmf"
"EntityCount" "1"
}
"bee2_static" "instances/BEE2/clean/items/wario/lcef_fizz_model_static.vmf"
}
"TargetName" "tul_lcef_fizz"
"Inputs"
{
"CONNECTION_STANDARD"
{
"Activate" "instance:counter;Add"
"Deactivate" "instance:counter;Subtract"
}
"CONNECTION_HAZARD_MODEL"
{
"Activate" "instance:mdl;FireUser2"
"Deactivate" "instance:mdl;FireUser1"
}
"CONNECTION_HAZARD_BRUSH"
{
"Activate" "Enable"
"Deactivate" "Disable"
}
}
"Outputs"
{
"CONNECTION_HAZARD"
{
"Activate" "instance:out;OnUser2"
"Deactivate" "instance:out;OnUser1"
}
}
"ConnectionPoints"
{
"Point"
{
"Dir" "1 0 0"
"Pos" "2 0 0"
"SignageOffset" "1 1 0"
"Priority" "0"
}
"Point"
{
"Dir" "1 0 0"
"Pos" "2 2 0"
"SignageOffset" "1 3 0"
"Priority" "0"
}
"Point"
{
"Dir" "1 0 0"
"Pos" "2 4 0"
"SignageOffset" "1 5 0"
"Priority" "0"
}
"Point"
{
"Dir" "1 0 0"
"Pos" "2 6 0"
"SignageOffset" "1 7 0"
"Priority" "0"
}
"Point"
{
"Dir" "-1 0 0"
"Pos" "5 0 0"
"SignageOffset" "6 1 0"
"Priority" "0"
}
"Point"
{
"Dir" "-1 0 0"
"Pos" "5 2 0"
"SignageOffset" "6 3 0"
"Priority" "0"
}
"Point"
{
"Dir" "-1 0 0"
"Pos" "5 4 0"
"SignageOffset" "6 5 0"
"Priority" "0"
}
"Point"
{
"Dir" "-1 0 0"
"Pos" "5 6 0"
"SignageOffset" "6 7 0"
"Priority" "0"
}
}
"Offset" "64 64 64"
}
}

**Comment by ZombiePwner1** [comment]
@ellingtonvengaboysmuseum Why is it called a wario fizzler? in the name it stated something related to wario.

**Comment by Luke18033** [comment]
It also has `LCEF` in the name, which is the Liquid Coloring Excision Field...

**Comment by ellingtonvengaboysmuseum** [comment]
@Luke18033 - Liquid Coloring Excision Field, Not Exactly... It stands for Light Compacting Something something... not spoiling any surprises

**Comment by ellingtonvengaboysmuseum** [comment]
teamspen210 said this appears to be a bug with bee2 itself, hopefully it gets fixed in pre release 28 and we don't have to wait 6 months for pre release 28...

**Comment by Luke18033** [comment]
Can I close this?
