### ISSUE TITLE
Include auto-installer with releases

### ISSUE THREAD

**Issue by BenVlodgi** [BEEmod/BEE2.4#77]
Problem: 
Some users don't know what to do with the .zip
There is no readme provided with the releases to tell people to extract the files to a new folder.
On top of that people are probably skiddish about where to place the files.

Solution:
Include Auto-installer.exe for the releases

________________________________________________________________________

@ellingtonvengaboysmuseum:

We need to have a Bee2.4 windows installer created that will do the following, we also need to merge the packages file into the main bee2.4 before this can happen. i recommend install forge for creating the main installer...

- [x] (prerequisite) merge the packages file into the main Bee2.4 file directory at each release (this is as easy as cake and should be considered already done)
- [ ] install the main program under the specified folder
- [ ] generate a shortcut to the desktop for the main bee2 exe file...

**Comment by Konclan** [comment]
Oh lol, I asked for this in #279

**Comment by calclover2514** [comment]
An installer can be found [here](https://github.com/calclover2514/BEE2.4-Installer-Automatic/releases).
(Issue #1121)

**Comment by Konclan** [comment]
The hope is this would be a 1 time download and not a download for every version thing and it would just grab the latest release as well as update the current BEE version

**Comment by Konclan** [comment]
Superseded by #1988
