### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by keifersisawesome** [BEEmod/BEE2.4#770]
So i was trying to build a particularly dense puzzle. Took me a good few hours to make, and now i get this error when i try to edit it. I admit it is more likely my fault than the mods, due to how densly i tried to pack it, but just in case there is something that can be done to salvage it, here's the error code, and i appreciate any help or advice.

ers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.129, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 3156 )
Opened Steam Socket NS_CLIENT ( socket 3216 )
Network: IP 192.168.1.129, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1509669888/c-2400_0_0.hdr' -- Trying non HDR 'maps\1509669888/c-2400_0_0'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1509669888/c-2000_2000_0.hdr' -- Trying non HDR 'maps\1509669888/c-2000_2000_0'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1509669888/c-1984_-2112_59.hdr' -- Trying non HDR 'maps\1509669888/c-1984_-2112_59'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1509669888/c-1984_-2240_59.hdr' -- Trying non HDR 'maps\1509669888/c-1984_-2240_59'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\76561198074144265\1509669888
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd10-cube_addons_*, which point_template cd10-cube_template is specifying.
Couldn't find any entities named cd12-cube_addons_*, which point_template cd12-cube_template is specifying.
Couldn't find any entities named cd14-cube_addons_*, which point_template cd14-cube_template is specifying.
Couldn't find any entities named cd16-cube_addons_*, which point_template cd16-cube_template is specifying.
Couldn't find any entities named cd18-cube_addons_*, which point_template cd18-cube_template is specifying.
Couldn't find any entities named cd20-cube_addons_*, which point_template cd20-cube_template is specifying.
Couldn't find any entities named cd22-cube_addons_*, which point_template cd22-cube_template is specifying.
Couldn't find any entities named cd61-cube_addons_*, which point_template cd61-cube_template is specifying.
Couldn't find any entities named cd63-cube_addons_*, which point_template cd63-cube_template is specifying.
Couldn't find any entities named cd65-cube_addons_*, which point_template cd65-cube_template is specifying.
Couldn't find any entities named cd88-cube_addons_*, which point_template cd88-cube_template is specifying.
Couldn't find any entities named cd268-cube_addons_*, which point_template cd268-cube_template is specifying.
Couldn't find any entities named cd269-cube_addons_*, which point_template cd269-cube_template is specifying.
Couldn't find any entities named cd271-cube_addons_*, which point_template cd271-cube_template is specifying.
Couldn't find any entities named cd273-cube_addons_*, which point_template cd273-cube_template is specifying.
PrecacheScriptSound 'music.puzzlemaker\76561198074144265\1509669888_tbout' failed, no such sound script entry
Warning:  Table modelprecache is full, can't add models/npcs/turret/turret_fx_break_gib24.mdl

Host_Error: CVEngineServer::PrecacheModel: 'models/npcs/turret/turret_fx_break_gib24.mdl' overflow, too many models

**Comment by LautaroL20** [comment]
If that is a compiler error, then it may be due to an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by keifersisawesome** [comment]
@LautaroL20 I have done that several times to no effect.

**Comment by TeamSpen210** [comment]
The last few lines indicate you somehow filled a model limit or something?

**Comment by keifersisawesome** [comment]
@TeamSpen210  it mentions the turret models, which I think are definitely the cause considering I did put a lot of turret models in.  I would love to remove them and have the test load properly, but every time I try to edit the test it crashes due to said abundance of turret models.

**Comment by keifersisawesome** [comment]
Is there any possible way around this?

**Comment by TeamSpen210** [comment]
No, that's what it happened to be checking when it ran out of space. This is a concern, if we load more than 1024 models we crash.

**Comment by keifersisawesome** [comment]
Ah okay. I was not aware of that but it does make sense. The thing is for a good while it was loading the puzzle in its latest state very well before it started crashing in this manner so I had hoped it would be something fixable. Suppose not then.

**Comment by TeamSpen210** [comment]
This was slightly fixed, we now disable as many models as we can.
