### ISSUE TITLE
BEE2 keeps sending me a game pic from other test chamber i made. [SOLVED]

### ISSUE THREAD

**Issue by Thelucas7** [BEEmod/BEE2.4#772]
this happend me when i unistalled BEE2

tried reinstalling it and making to use PeTi screenshots it still dosen't works

also tried unistalling bee2 content for portal 2.

also tried to verify game cache.

**Comment by TeamSpen210** [comment]
You'll want to delete `Portal 2/portal2/puzzles/<numbers>\untitled.jpg`.

**Comment by HugoBDesigner** [comment]
![image](https://user-images.githubusercontent.com/6296061/32410556-32fd6948-c1aa-11e7-9ace-698920c36a21.png)
Or you can select this option in the compile window

**Comment by Thelucas7** [comment]
thanks teamspen210
