### ISSUE TITLE
Cannot compile any maps

### ISSUE THREAD

**Issue by IceTudor** [BEEmod/BEE2.4#773]
After I changed from PRL25 to PRL27, my PeTI just says build error when I try to rebuild even with no items and most of the models and textures are missing in the editor.

**Comment by Luke18033** [comment]
You need to remount Portal 2 onto BEE2 (remove it and re-add it), otherwise things will be broken.

**Comment by IceTudor** [comment]
I did. I uninstalled P2 from BEE2.4 and then readded it, it still gives me the same errors.

**Comment by IceTudor** [comment]
... Guess I'll just have to not use PeTI then.

**Comment by IceTudor** [comment]
Nevermind, it has been fixed. Old resources being used. I CHECKED preserve game directories instead of Unchecking. Closing this thread
