### ISSUE TITLE
Portal 1 style

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#774]
Add the portal 1 model for the vents that suck things in and the portal 1 model for the vents that carry things and players around.

**Comment by TeamSpen210** [comment]
Wrong repository, and the problem is that we don't have all the model versions we need.

**Comment by ZombiePwner1** [comment]
We have the straight models and such but we need a modeler to make the rest of the models.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the "invalid" label when closing the issue.
