### ISSUE TITLE
Suggestion: Mixed Compiler Styles

### ISSUE THREAD

**Issue by kinker31** [BEEmod/BEE2.4#777]
**Example 1:** 1950-1960s Aperture chambers with Modern Aperture elements placed in them, as if GlaDOS was finishing up an old testing sphere Cave Johnson Abandoned.

**Example 2:** Modern Chambers with Portal 1 elements, as if renovations were underway.

**Example 3:** Mixed elements/chambers from 1950-1980 Aperture, looking like it was cobbled together by someone like Nigel for new testing purposes.

**Comment by ZombiePwner1** [comment]
Example 1 is already going to be implemented as refurbished style.

**Comment by kinker31** [comment]
Additional Example: Overgrown 1950-1980s Chambers

**Comment by Luke18033** [comment]
This isn't going to be implemented, besides a few specific combinations like Refurbished. For one thing, most style combinations really wouldn't make too much sense, like Overgrown + Old Aperture. There are also far too many combinations, each requiring style variants, entry/exit corridors, etc. BEE2 isn't an "easy Hammer", you can't just suggest any possible style and expect us to implement everything for you.
