### ISSUE TITLE
Auto-update built in

### ISSUE THREAD

**Issue by BenVlodgi** [BEEmod/BEE2.4#78]
Situation:
Users are installing pre-releases, and may never know to check for updates, or don't follow the forums to know there is an update.

Solution:
On initial installation with [auto-installer](https://github.com/BenVlodgi/BEE2.4/issues/77)  present auto-update options. 
Options could include 
- Automatically download updates
- Automatically switch to updated version
- Opt me in for betas and pre-releases

On startup check for new versions here on github. If a new version exists download and extract to alternate folder on disk
Program Files/BEE2/releases/<versionname>/
then notify user a new version is available to use if they would like to use instead.

> You've been using BEE2.4 pre-release 7, would you like to switch to BEE2.4 pre-release 11?

With the option to select which version to use on startup, or have it default to the latest

~This feature can be overlooked if we are going to continue forward with getting greenlit on steam.~
Perhaps just do a quick check to notify the user that they are using an old version

_____________________________________________________________________________________________

# Concept Art by @LautaroL20:

![Image](https://cloud.githubusercontent.com/assets/12244376/25589240/3ab4fcde-2e82-11e7-8c4d-a910e7c68ae6.jpg)

**Comment by calclover2514** [comment]
An installer can be found [here](https://github.com/calclover2514/BEE2.4-Installer-Automatic/releases).
(Issue #1121)

**Comment by Konclan** [comment]
Superseded by #1988
