### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by yeswellwhatever** [BEEmod/BEE2.4#781]
BEE2 doesn't work. The loading screen comes up, but that's it. None of the bars go higher, and I have to move it to do anything.

I'm using 2.4.0pr27.

**Comment by yeswellwhatever** [comment]
Also, a log appears in  the background, then stops responding after something about "BEE2_CLEAN" comes up.

**Comment by TeamSpen210** [comment]
What exactly is the log message?

**Comment by TeamSpen210** [comment]
Check `logs/bee2.log`.

**Comment by yeswellwhatever** [comment]
[BEE2.log](https://github.com/BEEmod/BEE2.4/files/1468032/BEE2.log)

**Comment by TeamSpen210** [comment]
Can you redownload `pr27`? That looks like `pr24`.

**Comment by yeswellwhatever** [comment]
Woops, I was trying the old version with the new stuff.

Sorry for wasting your time.
