### ISSUE TITLE
Some bug and suggestion

### ISSUE THREAD

**Issue by 91Yugo** [BEEmod/BEE2.4#784]
I will start with bug:
Portal 1 style : when i want put a super button it's write "error"
Dirty style : entrance and exit doors
![20171115180227_1](https://user-images.githubusercontent.com/33499533/32851035-2c1b446e-ca34-11e7-8b9e-add3a7e89be4.jpg) and 
![20171115180402_1](https://user-images.githubusercontent.com/33499533/32851043-33bbcbc6-ca34-11e7-803c-19ecbd909236.jpg) 

And for suggestion 
A button but turret must shoot for activate the thing connected
Pneumatic diversity vents with objets : 
![20171112152855_1](https://user-images.githubusercontent.com/33499533/32851128-6d633c2e-ca34-11e7-947a-bade05b2b2b8.jpg) 
Defective turrets or defective turret style for sentry turrets
that's it and thank you for reading this :)

**Comment by Luke18033** [comment]
Please don't post all of your bugs/suggestions in one issue like this, it makes it much harder to mark what things have been completed and know when the issue has been fully resolved. Additionally most of these have already been suggested. Did you even read the issue guidelines?

**Comment by Luke18033** [comment]
Also, these aren't issues with the BEE2 app, so they should go on the [BEE2-items issues page](https://github.com/BEEmod/BEE2-items/issues).

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply labels when closing an issue.
