### ISSUE TITLE
Launcher error

### ISSUE THREAD

**Issue by 91Yugo** [BEEmod/BEE2.4#785]
When i do "export to "PORTAL 2" it's say 

Launcher Error

Failed to load the launcher DLL: 
The specified module was not found

**Comment by Luke18033** [comment]
That would be an issue with Portal 2 when it's trying to launch, and has nothing to do with BEE2.4. Verify your game files, that should fix it.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply labels when closing an issue.
