### ISSUE TITLE
Development Version will not compile maps

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#786]
VBSP failed.

Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

**Comment by LautaroL20** [comment]
I guess i'll have to re-install the development version then. However, this takes time and i don't have any guarantee that it will work, so i'll do it when i have nothing better to do since the public release matches with the minimun requirements for what i am developing.

Since i don't think that this is an issue that also occurs to others who also have the complete development version.

**Comment by Luke18033** [comment]
I'm having this issue as well, did you ever end up finding a solution? (Other than using the release version, which I'm not doing.)

**Comment by LautaroL20** [comment]
Unfortunately, no. It seems that we are now in the same boat then. However, for what i googled, the possible issue for this involves different situations to what could be causing this, and therefore i was not able to find an enlightening solutionsolution to trying out for our issue.  

Please, if in the future you are able find out a fix to this terrible annoyiance that stop us from using the Dev version, share it with us!

**Comment by ZombiePwner1** [comment]
@LautaroL20 Get on steam wheels.

**Comment by troublemaker139** [comment]
I've been having errors in Beemod, when i build a map in the editor it barley makes it past geometry before, saying the is an error building the puzzle.

**Comment by LautaroL20** [comment]
@troublemaker139 - That does not have anything to do with this issue, title clearly says it is about the development version, not the public release which you are probably using. Please open an issue and post the console log there.

**Comment by LautaroL20** [comment]
@Luke18033 - Did you find a solution for this?

**Comment by TeamSpen210** [comment]
You'd want to try reinstalling Python probably, not the code (or just `cx_freeze`). The error indicates it can't find any code basically.

**Comment by LautaroL20** [comment]
I no longer use the development version anymore since the past year.
