### ISSUE TITLE
Installing on Mac

### ISSUE THREAD

**Issue by LinuxChampagne** [BEEmod/BEE2.4#787]
I can't understand the instrux for installing this for Mac. Is it a standalone copy of _Portal 2_ but edited? Is it an add-on that links to the game? If so, how do I link it? Walk me through, please. Simple language.

**Comment by LinuxChampagne** [comment]
(I don't know how to label it, btw.)

**Comment by Luke18033** [comment]
Mac isn't supported for release versions anymore, there were a lot of issues with people needing to install Python stuff for it to work so we dropped support for it. You can try to compile the development version using the instructions in the readme, but that's kinda complicated. Only members of the @BEEmod organization are able to label issues.

**Comment by LinuxChampagne** [comment]
:(

**Comment by LinuxChampagne** [comment]
All you have to do is the stuff in https://github.com/BEEmod/BEE2.4#build-from-source-mac ? Nothing else?
