### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by CaliMari** [BEEmod/BEE2.4#788]
!THIS WAS JUST AN WRONG SCREENSHOT!

**Comment by CaliMari** [comment]
Wrong Screenshot?!?!?!?!?!

**Comment by CaliMari** [comment]
Why... oh yeah... Portal 2 is FULLSCREEN

**Comment by CaliMari** [comment]
Wait a secound!

**Comment by CaliMari** [comment]
![p2_ctc_missing_items](https://user-images.githubusercontent.com/34241667/33557368-bace7c28-d90f-11e7-9d32-a9461d9e74f5.jpg)

**Comment by CaliMari** [comment]
There we go!

**Comment by CaliMari** [comment]
![p2_ctc_levelerror](https://user-images.githubusercontent.com/34241667/33557516-22f776ec-d910-11e7-9b50-8811ced02f3e.jpg)

**Comment by CaliMari** [comment]
Doors are fine,white errors are portable.At first i liked this and did TH3 GL1TCH.Just 2 Levels.Then i wanted to do CLEAN tests.But this errors remained.And now i hate them D:
I will do a console output.

**Comment by CaliMari** [comment]
NET_GetBindAddresses found 192.168.1.101: '802.11n USB Wireless LAN Card'
NET_GetBindAddresses found 192.168.180.1: 'VMware Virtual Ethernet Adapter for VMnet1'
NET_GetBindAddresses found 192.168.91.1: 'VMware Virtual Ethernet Adapter for VMnet8'
Opened Steam Socket NS_SERVER ( socket 1200 )
Opened Steam Socket NS_CLIENT ( socket 1208 )
Network: IP 192.168.1.101, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: C:\Program Files (x86)\Steam\steamapps\common\Portal II\portal2.exe\platform\config
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
Host_WriteConfiguration: Wrote cfg/config.cfg
Changing resolutions from (1680, 1050) -> (720, 480)
Unable to remove c:\program files (x86)\steam\steamapps\common\portal ii\portal2\textwindow_temp.html! (errno 2)
Unable to remove c:\program files (x86)\steam\steamapps\common\portal ii\portal2\textwindow_temp.html! (errno 2)
Double registration of demo custom data callback.
Host_WriteConfiguration: Wrote cfg/config.cfg
Changing resolutions from (720, 480) -> (1280, 768)
Unable to remove c:\program files (x86)\steam\steamapps\common\portal ii\portal2\textwindow_temp.html! (errno 2)
Unable to remove c:\program files (x86)\steam\steamapps\common\portal ii\portal2\textwindow_temp.html! (errno 2)
Double registration of demo custom data callback.
Unable to remove c:\program files (x86)\steam\steamapps\common\portal ii\portal2\! (errno d)
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.101, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 1212 )
Opened Steam Socket NS_CLIENT ( socket 1208 )
Network: IP 192.168.1.101, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
C_GameInstructor::KeyValueBuilder failed to save GI.lesson.Swap_Split_Screen_Control
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_03.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_03.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_05.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_05.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_08.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_08.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_15.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_15.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_20.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_20.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal II/portal2/puzzles\76561197960274076\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal II/portal2/puzzles\76561197960274076\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal II/portal2/puzzles\76561197960274076\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal II/portal2/puzzles\76561197960274076\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal II/portal2/puzzles\76561197960274076\autosave.p2c
Unknown command "cl_puzzlemaker_deactivate"
Dropped AoriFire from server (Server shutting down)
[PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561197960274076\1512318634.p2c
Unknown command "cl_puzzlemaker_activate"
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.1.101, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 1064 )
Opened Steam Socket NS_CLIENT ( socket 1208 )
Network: IP 192.168.1.101, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\1512318634/c-2400_0_0.hdr' -- Trying non HDR 'maps\1512318634/c-2400_0_0'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1512318634/c-2000_2000_-48.hdr' -- Trying non HDR 'maps\1512318634/c-2000_2000_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\1512318634/c-2032_-1968_-31.hdr' -- Trying non HDR 'maps\1512318634/c-2032_-1968_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\76561197960274076\1512318634
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named cd144185-cube_addon_*, which point_template cd144185-cube_template is specifying.
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
PrecacheScriptSound 'music.puzzlemaker\76561197960274076\1512318634_tbout' failed, no such sound script entry
Commentary: Could not find commentary data file 'maps/puzzlemaker\76561197960274076\1512318634_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_03.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_03.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_05.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_05.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_08.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_08.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_15.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_15.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_tuleby_bomb_cube_clean_20.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_tuleby_bomb_cube_clean_20.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Requested non-existent write path LOCAL!
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
Error: Operator stop_entry, unknown sound operator attribute input_start
Unknown command "cl_puzzlemaker_start_previewing"
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
0
-2
Updating sound cache [8704 entries]
Found 8695 sound files on disk
 updated 'bee2\music\rex\five.mp3'
Updated 1 out of 8695 cached files [722.529 msec]
Setting arrival movie to media\laser_portal.bik
-------
Scaling type: 7
-------
SAVEGAME:  737.9kb,  214.4kb used by 506 entities (puzzlemaker\76561197960274076\1512318634)
SAVEGAME:   31.0kb,   16.3kb used by 190 entities (puzzlemaker\76561197960274076\1512318634)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker\76561197960274076\1512318634)
AoriFire unpaused the game







This is what is in the Console.Yeah i have three names: Calimari , AoriFire and FriskRD (not joking)

**Comment by CaliMari** [comment]
Yeah... i don't have steam **that's bad?**

**Comment by CaliMari** [comment]
Can you please help me?

**Comment by CaliMari** [comment]
@LautaroL20  @TeamSpen210  @BenVlodgi  or @Luke18033  or... Anymone,please help.

**Comment by Konclan** [comment]
You can't have Portal 2 without steam unless you pirate it. We can't help you if you did.

**Comment by Starchasm** [comment]
Portal 2 goes seems to sell for $2 on each Steam sale.  Wait a couple weeks for the Christmas sale, step up, and get a legit version already.  Considering how good the game is, $2 is money well spent.

**Comment by ZombiePwner1** [comment]
@CaliMari Sorry we can't help you if you got a pirated version of the game. Your gonna need to get the proper steam version.

**Comment by ncrecc** [comment]
Um, hate to say this, but Steam is shown in the background of the first screenshot.

**Comment by LautaroL20** [comment]
@CaliMari - 
This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!

**Comment by CaliMari** [comment]
Thanks.And sorry.I am in Romania and i have no money for games right now.But from 8 December i will buy the game steam code.Thanks LautaroL20 for help.BTW i have a suggestion too.Panel Bridge.A panel that has a Lightbridge on it.Adjustable.

**Comment by Starchasm** [comment]
Not having money for games is not justification for pirating them.

**Comment by CaliMari** [comment]
I have the original game from Steam now.But why can't i still add friends? it was 60RON in romania that means in America USD 15.34 dollars.Why can't i add friends?I know this is not BEE2 related but does anyone know anyway?

**Comment by LautaroL20** [comment]
@CaliMari - Thats weird, try googling your problem. Maybe where you live, steam rules are slightly  different idk.

**Comment by ZombiePwner1** [comment]
@CaliMari Have you payed the $10?

**Comment by CaliMari** [comment]
@ZombiePwner1 of course if the game costed 14$

**Comment by ZombiePwner1** [comment]
@CaliMari I mean't have you payed the $10 on steam which gives you full access to the program such as adding friends and stuff.

**Comment by OmGCHOOCHOOTRAIN** [comment]
Same problem I have.
