### ISSUE TITLE
Make more choices for elevator coming direction 

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2.4#791]
For example normal elevator goes from down to up on start of map , why not make it also from up to down direction , same for exit elevator from up to down , this would make few sense like going in underground for people making series of maps
It can be chosen by Bee 2.4 app in compile options for example.

**Comment by TeamSpen210** [comment]
I'm explicitly not supporting map series, the PeTI has no business doing that. But yes this is desirable, probably a random option.

**Comment by SpyyZ158** [comment]
and is it doable?

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/757
