### ISSUE TITLE
Reconstructing Theme

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#792]
You should add this theme. But make the elevators go from up to down. More information can be found here: https://developer.valvesoftware.com/wiki/Reconstructing_(Portal_2)

**Comment by CaliMari** [comment]
This is a pretty good idea!

**Comment by ZombiePwner1** [comment]
This style is already going to be added at some point however work on this style hasn't started so it's unknown when this style will eventually come.

**Comment by Fazbear189** [comment]
Oh, ok.
