### ISSUE TITLE
Bee2 export failed

### ISSUE THREAD

**Issue by ThatOneOwl** [BEEmod/BEE2.4#793]
every. single. time. i try to export i get the message copying compiler file python36.dll failed, ensure the PORTAL 2 is not running.

I've tried restarting my computer, I also have the latest version.

**Comment by TeamSpen210** [comment]
Go into your `Portal 2/bin/` folder, and try deleting that file yourself manually.

**Comment by ThatOneOwl** [comment]
Then i get the error "the code execution cannot proceed because python36.dll was not found. reinstalling the program may fix this problem."

**Comment by CaliMari** [comment]
Maybe if you reinstall BEE2?

**Comment by protoborg** [comment]
I get the same problem.  It sounds to me like an internal issue with the program itself rather than the external file.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
