### ISSUE TITLE
building test error 

### ISSUE THREAD

**Issue by nahoJ974** [BEEmod/BEE2.4#794]
when i build a test, there are not end and is show me this error in the console

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Valve/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,12,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 52 (ms)

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.[INFO] cond.core.import_conditions(): Imported all conditions modules![INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Valve/Portal 2/sdk_content\maps/preview.vmf"[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Valve/Portal 2/sdk_content\maps\styled\preview.vmf"[INFO] vbsp.main(): Clearing inject/ directory..[INFO] vbsp.main(): PeTI map detected![INFO] vbsp.main(): Loading settings...[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_GLADOS_CLEAN'}[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.[INFO] fizzler.read_configs(): Loaded 13 fizzlers.[INFO] vbsp.load_settings(): Settings Loaded![INFO] vbsp.load_map(): Parsing Map...[INFO] vbsp.load_map(): Reading Map...[INFO] vbsp.load_map(): Loading complete![WARNING] instance_traits.set_traits(): Unknown instance "instances/p2editor/elevator_exit.vmf"![WARNING] instance_traits.set_traits(): Unknown instance "instances/p2editor/elevator_entrance.vmf"![WARNING] instance_traits.set_traits(): Unknown instance "instances/p2editor/arrival_departure_transition_ents.vmf"![INFO] vbsp.get_map_info(): Forcing elevator spawn![INFO] vbsp.get_map_info(): Game Mode: ERR[INFO] vbsp.get_map_info(): Is Preview: False[ERROR] (unknown file).(unknown function)(): Uncaught Exception:Traceback (most recent call last):  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>  File "vbsp_launch.py", line 7, in <module>  File "F:\Git\BEE2.4\src\vbsp.py", line 3712, in main  File "F:\Git\BEE2.4\src\vbsp.py", line 1424, in get_map_infoException: Unknown game mode - Map missing exit room!Traceback (most recent call last):  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>  File "<frozen importlib._bootstrap>", line 961, in _find_and_load  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>  File "vbsp_launch.py", line 7, in <module>  File "F:\Git\BEE2.4\src\vbsp.py", line 3712, in main  File "F:\Git\BEE2.4\src\vbsp.py", line 1424, in get_map_infoException: Unknown game mode - Map missing exit room!

[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Valve/Portal 2/portal2/puzzles\76561199455873652\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Valve/Portal 2/portal2/puzzles\76561199455873652\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Valve/Portal 2/portal2/puzzles\76561199455873652\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Valve/Portal 2/portal2/puzzles\76561199455873652\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: C:/Program Files (x86)/Valve/Portal 2/portal2/puzzles\76561199455873652\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Compilation canceled
pls someone help me
(sorry for my english)

**Comment by LautaroL20** [comment]
This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
