### ISSUE TITLE
How to add custom items from hammer

### ISSUE THREAD

**Issue by SwistakPL** [BEEmod/BEE2.4#797]
Does anyone know how can I add my own items to the list in bee mod? For example I took lamp (easiest to edit) and added something. How can I add it as a new item inside bee items list?

**Comment by CaliMari** [comment]
I want to know too!

**Comment by DoMessWithProfile** [comment]
Coding in Python and textures and models... it's really hard or I think you can't.

**Comment by ZombiePwner1** [comment]
You can add your own custom made items to the pallet however it will involve coding since beemod will not recognize it as a regular item.

**Comment by SwistakPL** [comment]
Is there any template, like an empty item that I could use to add my own items?

**Comment by LautaroL20** [comment]
For questions like these, use the Discrod channel from beemod. You will probably get the desired reply, there: https://discordapp.com/invite/fBdpg2
