### ISSUE TITLE
VBSP Failed in Hammer.

### ISSUE THREAD

**Issue by CaliMari** [BEEmod/BEE2.4#802]
I am making a Overgrown map in hammer,but with BEE2 i use Original Clean.I make the layout and gameplay in PeTI and then go with preview.vmf in hammer.Doing things there but after i click Run Map,it sais this: CDynamicFunction: Loading library 'Kernel32.dll' (74430000)
CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 773A4120

-------------------------------------------------------------------------------
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.vmf"
-------------------------------------------------------------------------------

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.vmf"
[INFO] vbsp.main(): New path: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[WARNING] vbsp.main(): Hammer map detected! skipping conversion..
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.vmf"

I can't copy anymore because it closes fast.but at the end it says "VBSP Failed." I waited a few minutes but nothing happened.Is this a Valve bug or Bee2 or what is it anyway?
EDIT:BTW how to make the copied text not to change?I mean to put it in a separate window?
Another EDIT:How to add PS:M songs in-game?BEE2 shows them in Select Music,i put files in the Portal 2\bee2\sounds\music\mel but they are not playing in game.I changed them from Mp3 to Wav too but it does not work 😑

**Comment by LautaroL20** [comment]
Beemod is not a Hammer addon, so if you experience weird issues its understable. However, if you want to start using Hammer instead of beemod, go ahead but do not mix up both things since they where not  desinged to work togheter. Beemod is just a tool to mod the Portal 2´s Puzzlemaker.

**Comment by CaliMari** [comment]
@LautaroL20 but what about the PS:Mel songs? Where to put them?

**Comment by LautaroL20** [comment]
As long as you installed PS:Mel from Steam, beemod will be able to detect them to be used for your puzzles.

**Comment by CaliMari** [comment]
I have it.BeeMod detects them,but the game says that is missing.

**Comment by CaliMari** [comment]
@LautaroL20
