### ISSUE TITLE
Compile Error on Portal 2 BEEMOD 

### ISSUE THREAD

**Issue by WhatspoppinJimbo69** [BEEmod/BEE2.4#806]
I have Pre-Release 27 for both packages and the application but no matter what i do theres a compile error

Heres the dev-log:

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr27 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'voice_pack': 'BEE2_GLADOS_CLEAN'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cond.cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 4
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 4
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (85 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 3/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "SENDIFICATOR_1"
 | 	"Choreo"
 | 		{
 | 		"1" "scenes/npc/glados/coop_test_chamber_both15.vcd"
 | 		"2" "scenes/npc/glados/sp_laser_redirect_intro_entry03.vcd"
 | 		"3" "scenes/npc/glados/sp_paint_jump_trampoline_entry01.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "FAITH_1"
 | 	"Choreo" "scenes/npc/glados/sp_catapult_fling_sphere_peek_completion01.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/9 quotes..
[INFO] voiceLine.add_voice(): 2 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Cave Reactions"
 | 	"File" "clean/cave_reaction.vmf"
 | 	}
 |_

[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"Name" "Have Fun Soaring Through The Air"
 | 	"Choreo_Name" "@voice_faith_trigger"
 | 	"OnlyOnce" "1"
 | 	"Choreo" "npc/glados/sp_trust_fling_entry01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['bottomless_pit', 'has', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'faith', 'catapult', 'faithplate', 'sendificator', 'sendtor', 'pedestalbutton', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=10222, misses=365, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'doorcameras': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': False, 'funnelallowswitchedlights': False, 'enableshapesignageframe': False}
[INFO] cond.core.check_all(): Global instances: {'instances/bee2/logic/hmw/sendtor_detector_sp.vmf', 'instances/BEE2/logic/goo_fade.vmf', 'instances/bee2/logic/hmw/sendtor_manager.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf']}
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 704 704 64, NSEW: (True, False, True, False), lookup: (<CONN_TYPES.corner: 3>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 960 448 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 320 192 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 448 -64 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 320 320 64, NSEW: (False, True, False, True), lookup: (<CONN_TYPES.corner: 3>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 192 448 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 320 64 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 704 -64 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 960 64 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 832 704 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 448 832 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 960 576 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 960 192 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 832 -64 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 192 576 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 960 320 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 576 832 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 576 -64 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 320 832 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 192 704 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/black_ceiling_metal.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/black_floor_metal.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/black_floor_metal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/bullseye_glow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/fizz_side.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz_sides/side_color_06141A.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/signage_arrow_world.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/signage_catapult1_world.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/signage_catapult2_world.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/sendtor/sendificator_antlines.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/sendtor/sendificator_antlines.vtf"
[INFO] vbsp.make_packlist(): "materials/models/hmw/props/sendificator.vmt"
[INFO] vbsp.make_packlist(): "materials/models/hmw/props/sendificator.vtf"
[INFO] vbsp.make_packlist(): "materials/models/hmw/props/sendificator_beam.vmt"
[INFO] vbsp.make_packlist(): "materials/models/hmw/props/sendificator_beam.vtf"
[INFO] vbsp.make_packlist(): "materials/models/hmw/props/sendificator_n.vtf"
[INFO] vbsp.make_packlist(): "materials/models/hmw/props/sendificator_r.vmt"
[INFO] vbsp.make_packlist(): "models/hmw/props/sendificator.mdl"
[INFO] vbsp.make_packlist(): "models/hmw/props/sendificator_beam.mdl"
[INFO] vbsp.make_packlist(): "models/hmw/props/sendificator_cube0.mdl"
[INFO] vbsp.make_packlist(): "models/hmw/props/sendificator_cube1.mdl"
[INFO] vbsp.make_packlist(): "models/hmw/props/sendificator_sphere0.mdl"
[INFO] vbsp.make_packlist(): "models/hmw/props/sendificator_sphere1.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/hmw/sendificator.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun 28 2017)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/clean/elevator_sp/door_entrance_4.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by WhatspoppinJimbo69** [comment]
Someone plz help

**Comment by Luke18033** [comment]
> Could not open instance file instances/bee2/clean/elevator_sp/door_entrance_4.vmf

It looks like you're missing the instance for entrance corridor 4. Try switching to another in the compile window, see if that fixes the error.

**Comment by WhatspoppinJimbo69** [comment]
How do i do that?

**Comment by SpyyZ158** [comment]
@WhatspoppinJimbo69 change different corridor entrance on your compile options menu under SP Entry

**Comment by LautaroL20** [comment]
This is not a problem on the PRL27, your problem is different. This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Packages & Application version of Beemod, and both must have to be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
