### ISSUE TITLE
Beemod crashes while exporting palette to Portal 2

### ISSUE THREAD

**Issue by WhatspoppinJimbo69** [BEEmod/BEE2.4#808]
When i try to export my palette to portal 2, i get this error

An error occured:
Traceback (most recent call last):
 File "F:\Git\BEE2.4\src\UI.py", line 853, in export_editoritems
 File "F:\Git\BEE2.4\src\gameMan.py", line 597, in export
 File "F:\Git\BEE2.4\src\gameMan.py", line 801, in generate_fizzler_sides
 File "C:\Users\Spencer
Brown\AppData\Local\Programs\Pyton\Python36-32\lib\os.py", line
220, in makedirs
PermissionError: [WinError 5] Acess is denied: 'c\\program files
(x86)\\steam\\steamapps\\common\\portal
2\\bee2\\materials\\bee2\\fizz_sides\\'

I don't understand!
plz help

**Comment by LautaroL20** [comment]
Try re-exporting again without having Portal 2 running this time and see what happens.

**Comment by WhatspoppinJimbo69** [comment]
Same thing happens, also a log appears before beemod opens now

**Comment by LautaroL20** [comment]
I will never understand why some people opens issues for lately abandoning them entiry making the feedback impossible.
