### ISSUE TITLE
16th item in the palette persists on being track platform

### ISSUE THREAD

**Issue by HugoBDesigner** [BEEmod/BEE2.4#811]
This is an issue I've faced multiple times: independently of how I arrange my palette, sometimes the 16th item (or 4th row and 4th line) will remain as a track platform, even if the track platform itself is positioned elsewhere in the palette (leading to a duplicate).
Here's the palette that I get in-game:
![portal2_2018-01-07_21-02-41](https://user-images.githubusercontent.com/6296061/34655305-7488edda-f3ee-11e7-856b-d9b8159094cc.png)

And the palette that I exported:
![pythonw_2018-01-07_21-03-07](https://user-images.githubusercontent.com/6296061/34655308-7f2f1fd4-f3ee-11e7-8ac1-88a4f246c6f1.png)

**Comment by TeamSpen210** [comment]
I believe this might have something to do with Tuleby's item pack. I'll have to look at it.

**Comment by Konclan** [comment]
This happens with Tuleby’s item pack, the one he gave out. This doesn’t have anything to do with beemod itself I believe.

**Comment by TeamSpen210** [comment]
To fix this, remove everything after line 189 in `tuleby.zip/items/pistonwhite/editoritems.txt`. (The `"Item"` blocks.)

**Comment by TeamSpen210** [comment]
I've added a check for this in the app, so it will now no longer produce the icon there.
