### ISSUE TITLE
BEE2 Item Suggestion: Activation Field

### ISSUE THREAD

**Issue by PieCreeper13** [BEEmod/BEE2.4#815]
Activation fields will activate an item it's connected to when a player walks through it. If the player walks through the activation field again while it's activating an item, it'll deactivate the item. This can make it so an item can only be enabled when a player is on one side of a room and disabled when on the other side.

**Comment by snorepion** [comment]
Do this instead, though it works better for smaller rooms.
![img](https://i.imgur.com/Wt9vQRl.png)

**Comment by HTiago** [comment]
@snorepion, you can do this too for big areas:
![image](https://user-images.githubusercontent.com/29435727/35186315-7da00b7a-fde8-11e7-8148-dcc4017e5e4e.png)
![image](https://user-images.githubusercontent.com/29435727/35186306-64ecc2bc-fde8-11e7-8a10-7aa63a8d2e13.png)

**Comment by snorepion** [comment]
@HTiago Yes, but it takes a long time and is harder if you want to fill up a whole room.

**Comment by CaliMari** [comment]
LOL i did not know that if you connect 2 triggers it will make a big area XD

**Comment by TeamSpen210** [comment]
This is present in Portal Pro, and I do want to add it.

**Comment by HTiago** [comment]
Oh that field from Pro... Would be interesting on coop chambers.

**Comment by LautaroL20** [comment]
This repro is only for issues related to the BEE2.4 application itself; anything else goes on [BEE2-items](https://github.com/BEEmod/BEE2-items/issues).
