### ISSUE TITLE
Some weird things

### ISSUE THREAD

**Issue by HTiago** [BEEmod/BEE2.4#816]
Well, I've noticed some bugs, I don't know if some of them are already known and/or expected, but here it goes:
- 'Draw Bridge' acts strange when interacting with objects, sometimes cubes passes through or get stuck. It is easy to players get stuck too.
![image](https://user-images.githubusercontent.com/29435727/35180324-2cbe327c-fd84-11e7-9e6c-203df4300509.png)
(Cube flickering on panel)
- ~~Laser beam reflects weird when pointed to angled blocks covered with reflection gel.~~ Not a BEEMOD bug, cause it happens even with angled panels.
![image](https://user-images.githubusercontent.com/29435727/35180008-7192f552-fd7c-11e7-88ac-769266b79c7c.png)
- Placing a 'Scaffold Wall Slot' and a 'Laser Emitter' on same surface instantly crashes the game.
- Rockets fired by 'Rocket Turret' are invisible.
- 'Rocket Turret' does not appears on 1970 style. (Did not tested other styles)
- On 1970, if more than 1 'large observation room' is placed on a chamber, causes to all of them bug, showing an white glowing void.
- On Portal 1 style, 'Angled Panel' deflects pellets at non-accurately angles. That makes so hard to create chambers using it.
- On Portal 1 style, there's a fizzler on entry room, but it is possible to create a portal on the ceiling above it.
- 'Physics Repulsion Field' blocks objects, but doesn't blocks if a player pass through holding it.
- When a cube is sucked by 'Vactube', sometimes it get "stuck" near to the entrance, floating forever, trying to enter.
- Belt from 'Conveyour Belt' can be "deformed" if a cube or player stuck between its parts.
- 'Closed Solid Field' sometimes become invisible. (Tested on style 1970)
- 'Overgrown' exit elevator moves, stops and the "end chamber" trigger never activate, so player get trapped on elevator.
- Light Bridge does not activate on Overgrown syle, even with "Start Enabled" enabled. (Maybe intentional?)

However the mod is awesome, recommended it to my friends. Keep the good work, guys!

**Comment by CaliMari** [comment]
Yeah.The pellet on portal 1 is anoying D: I want to make a series called HardEasy and its Rexaura style.lets hope at pre-28 will be fixed

**Comment by ZombiePwner1** [comment]
@HTiago That' the whole point of reflection gel is to reflect lasers it's not weird at all.

**Comment by HTiago** [comment]
@ZombiePwner1 I know, but it still strange to laser do not reflect like would happen IRL.

I've tested again using angled blocks (BEEMOD) and angled panels (default) and reflection gel always applies 90 degrees to the laser beam, no matter which angle, so it is not a BEEMOD bug.

**Comment by ZombiePwner1** [comment]
@HTiago It isn't a beemod bug it's a valve bug which can't be fixed.

**Comment by TeamSpen210** [comment]
Valve coded Reflection Gel like that, no idea why.

**Comment by Fazbear189** [comment]
Why don't you guys edit the code, and not just stick to the Portal 2 stuff? It would be much easier to understand.

**Comment by TeamSpen210** [comment]
Um, we can't. The game is closed source, only Valve can.

**Comment by ZombiePwner1** [comment]
@Fazbear189 Like @TeamSpen210 You can't forget we can't edit the game code if we were able to do this we would ruin a few important things on the code.

**Comment by Fazbear189** [comment]
Oh. If I were you, then I would make it a mod available on Mod db or greenlight.

**Comment by Fazbear189** [comment]
Well, Mod db. then greenlight.

**Comment by TeamSpen210** [comment]
That doesn't do anything at all, why do you think that gives any special powers?

**Comment by Fazbear189** [comment]
Because you can add a custom workshop, more options for each item in the editor, and abilities to add water, scripts and such.

**Comment by TeamSpen210** [comment]
You need the source code for that. And we don't want to fracture the community requiring some special game version to play. That would just wreck any ability for players to find maps.

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

Also, you are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
