### ISSUE TITLE
Suggestion: Cancel Button After Exporting

### ISSUE THREAD

**Issue by HankyMueller** [BEEmod/BEE2.4#817]
I think launching Portal after an export is a fantastic addition, but I think it would be nice if there was a cancel button in the case that you don't want it to launch immediately. Just a minor suggestion.

**Comment by HugoBDesigner** [comment]
Already a feature. Go to File > Options and on "After Export", uncheck "Launch Game"
![image](https://user-images.githubusercontent.com/6296061/35188843-6f51a028-fe25-11e7-87ef-629dfc6d7d1f.png)

**Comment by Luke18033** [comment]
Kind of a duplicate of #553, which is suggesting to cancel launching the game if the dialog is closed.

**Comment by HankyMueller** [comment]
Well that setting isn't what I mean, I usually like the fact the game launches after exporting, But sometimes I'll forget an item or something and I'll have to go back for it. 

Sorry if this is a duplicate, I didn't really read through the forum before posting.

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/566

**Comment by TeamSpen210** [comment]
Actually no, it's something different - after export is finished, allow cancelling running Portal 2.

**Comment by Blacksilver42** [comment]
Dedicated "Launch portal 2" and "back" buttons would be nice, instead of generic buttons like "ok" and "cancel"
