### ISSUE TITLE
compiling maps issue

### ISSUE THREAD

**Issue by SirNightshade** [BEEmod/BEE2.4#819]
recently when i downloaded the new version of BEE2.4, ive been having problems with compiling new maps. i made a test map earlier, then after i made a new palette and compiled a new map, this happens in the console:
> NET_GetBindAddresses found 192.168.1.232: 'Atheros AR9285 Wireless Network Adapter'
> NET_GetBindAddresses found 192.168.56.1: 'VirtualBox Host-Only Ethernet Adapter'
> NET_GetBindAddresses found 25.125.166.211: 'Hamachi Network Interface'
> Opened Steam Socket NS_SERVER ( socket 1652 )
> Opened Steam Socket NS_CLIENT ( socket 1660 )
> Network: IP 192.168.1.232, mode MP, dedicated No, ports 27015 SV / 27005 CL
> Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
> Game supporting (2) split screen players
> maxplayers set to 1
> Steam config directory: D:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
> --- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
> --- Missing Vgui material vgui/hud/commands/gesture_Spinjump
> --- Missing Vgui material vgui/hud/commands/gesture_headspin
> --- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
> --- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
> --- Missing Vgui material vgui/hud/commands/gesture_Spinjump
> --- Missing Vgui material vgui/hud/commands/gesture_headspin
> --- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
> Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
> Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
> Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
> Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
> --- Missing Vgui material vgui/hud/commands/change_this
> --- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
> --- Missing Vgui material vgui/hud/commands/gesture_Spinjump
> --- Missing Vgui material vgui/hud/commands/gesture_headspin
> --- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
> --- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
> --- Missing Vgui material vgui/hud/commands/gesture_Spinjump
> --- Missing Vgui material vgui/hud/commands/gesture_headspin
> --- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
> Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
> Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
> Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
> Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
> --- Missing Vgui material vgui/hud/commands/gesture_smallwave
> resource/closecaption_sba.txt not found
> resource/closecaption_english.txt will be used
> Unknown command "cl_thirdperson"
> Unknown command "joy_no_accel_scale"
> Unknown command ":"
> Didn't find Active Steam Controller to Load Menu Controls
> resource/closecaption_sba.txt not found
> resource/closecaption_english.txt will be used
> Unknown command "cl_thirdperson"
> Unknown command ":"
> C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
> An error occurred while attempting to download a file from the UGC server!
> An error occurred while attempting to download a file from the UGC server!
> An error occurred while attempting to download a file from the UGC server!
> [PORTAL2 PUZZLEMAKER]  Loaded puzzle puzzles\76561198073982931\1516823848.p2c
> Unknown command "cl_puzzlemaker_activate"
> CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
> maxplayers set to 1
> ---- Host_NewGame ----
> Network: IP 192.168.1.232, mode SP, dedicated No, ports 0 SV / 0 CL
> Opened Steam Socket NS_SERVER ( socket 1664 )
> Opened Steam Socket NS_CLIENT ( socket 1660 )
> Network: IP 192.168.1.232, mode MP, dedicated No, ports 27015 SV / 27005 CL
> Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
> Failed, using default cubemap 'engine/defaultcubemap'
> Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
> Failed, using default cubemap 'engine/defaultcubemap'
> Host_NewGame on map puzzlemaker\newchamber
> exec: couldn't exec skill1.cfg
> ==== calling mapspawn.nut
> Unable to load sprite material materials/sprites/gunsmoke.vmt!
> Unable to load sprite material materials/sprites/bubble.vmt!
> Attempted to create unknown entity type playtest_manager!
> Can't init playtest_manager
> Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
> Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
> 1.000:  Sending UDP connect to public IP 127.0.0.1:27015
> Server using '<none>' lobbies, requiring pw no, lobby id 0
> RememberIPAddressForLobby: lobby 0 from address loopback
> Can't find factory for entity: wearable_item
> NULL Ent in UTIL_PrecacheOther
> [PORTAL2 PUZZLEMAKER]  --------START loading assets--------
> 
> KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/door_frame.vmt
> patch, (*insert*), 
> KeyValues Error: RecursiveLoadFromBuffer:  got EOF instead of keyname in file materials/models/props_map_editor/crusher_back.vmt
> patch, (*insert*), 
> [PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
> [PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
> [PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
> [PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
> [PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
> [PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
> [PORTAL2 PUZZLEMAKER]  ---------END loading assets---------
> 
> ==== calling mapspawn.nut
> Connection to Steam servers successful.
>    VAC secure mode is activated.
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> Parent cvar in client.dll not allowed (r_shadowlod)
> ***********************************
> *         NO GAME SESSION         *
> * some features might be disabled *
> * (achievements, stats, UI, etc.) *
> ***********************************
> Redownloading all lightmaps
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> ✧°:* Sir Nightshade *:°✧ unpaused the game
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> ✧°:* Sir Nightshade *:°✧ unpaused the game
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198073982931\1516823848.p2c
> [PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
> [PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (13,12,5)
> [PORTAL2 PUZZLEMAKER]  Compilation time (after export): 688 (ms)
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 149714 (ms)
> [PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 156561 (ms)
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 189800 (ms)
> [PORTAL2 PUZZLEMAKER]  Compilation time (complete): 196198 (ms) ...launching map!
> Error: Operator stop_entry, unknown sound operator attribute input_start
> ---- Host_Changelevel ----
> exec: couldn't exec skill1.cfg
> ==== calling mapspawn.nut
> Attempted to create unknown entity type playtest_manager!
> Can't init playtest_manager
> Couldn't find any entities named cd154968-cube_addon_*, which point_template cd154968-cube_template is specifying.
> Couldn't find any entities named cd157475-cube_addon_*, which point_template cd157475-cube_template is specifying.
> Couldn't find any entities named cd259405-cube_addon_*, which point_template cd259405-cube_template is specifying.
> PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
> Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
> Can't find factory for entity: wearable_item
> NULL Ent in UTIL_PrecacheOther
> [PORTAL2 PUZZLEMAKER]  --------START loading assets--------
> 
> [PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
> [PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
> [PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
> [PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
> [PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
> [PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
> [PORTAL2 PUZZLEMAKER]  ---------END loading assets---------
> 
> ==== calling mapspawn.nut
> Unknown command "cl_puzzlemaker_start_previewing"
> ***********************************
> *         NO GAME SESSION         *
> * some features might be disabled *
> * (achievements, stats, UI, etc.) *
> ***********************************
> =======================Trying to GivePlayerPortalgun
> =======================Trying to UpgradePlayerPortalgun
> Updating sound cache [8949 entries]
> Found 8788 sound files on disk
> Updated 0 out of 8788 cached files [2522.796 msec]
> Redownloading all lightmaps
> -------
> Scaling type: 10
> -------
> SAVEGAME:  935.7kb,  348.4kb used by 746 entities (puzzlemaker/preview)
> SAVEGAME:   41.5kb,   23.6kb used by 281 entities (puzzlemaker/preview)
> SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)
> Unknown command "cl_puzzlemaker_start_editing"
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> ✧°:* Sir Nightshade *:°✧ unpaused the game
> [PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
> [PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (13,12,5)
> [PORTAL2 PUZZLEMAKER]  Compilation time (after export): 528 (ms)
> Could not execute the command:
>    "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
> Windows gave the error message:
>    "�� ������� ����� ��������� ����."
> 
> VBSP failed.
> 
> Failed to start process ("D:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "D:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (D:/Program Files (x86)/Steam/steamapps/common/Portal 2/bin/)
> 
> 
> ✧°:* Sir Nightshade *:°✧ unpaused the game
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198073982931\1516823848.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c
> [PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198073982931\autosave.p2c

also when i first compile a new map, it brings me to an old one, and then when i try to compile again, the puzzlemaker gives me a usual "There was an error building the puzzle". could i have done possibly something wrong? i hope i wont get this issue again later on.
thanks for reviving a great puzzlemaker extending mod.
- sir nightshade

**Comment by LautaroL20** [comment]
When using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue clearly seems te be related to this, so in order to solving this annoyance, you will have to do the following:

1 - Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2 - Wait 1 minute while Beemod removes their resources from Portal 2.

3 - Verify the Game Cache Files. 

4 - Make sure to have downloaded and unzipped the latest Item's Packages and Application version of BEE2.4, and both must be from the same Pre-Release Version, otherwise bugs may occur. Links:

https://github.com/BEEmod/BEE2.4/releases (Application) 
https://github.com/BEEmod/BEE2-items/releases (Item's Packages)

Note that if you are running Beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5 - Click on: `File ----> Options ----> Development`, then uncheck the option: `Preserve Game Directories`.

6 - Now choose your favorite Items & Style and export your palette to the game.

7 - Make sure to save these steps in a text file in case you get similar issues in the future.

8 - Happy mapmaking!
