### ISSUE TITLE
My BEE2 doesn't work

### ISSUE THREAD

**Issue by GewoonLeonYT** [BEEmod/BEE2.4#824]
When i open my BEE2 i get an error
![test](https://user-images.githubusercontent.com/35887230/35480039-3a739a28-0406-11e8-9415-edb7c58eb7dc.PNG)

**Comment by Cellolide** [comment]
I am using the pr27 version till it's fixed...

**Comment by TeamSpen210** [comment]
Delete the `cfg/game.cfg` file. It seems the location of Portal 2 moved...

**Comment by Konclan** [comment]
I think this is considered fixed?
