### ISSUE TITLE
Suggestion: Make light strips one pallet item

### ISSUE THREAD

**Issue by Cellolide** [BEEmod/BEE2.4#829]
Like the "Square Neutral Light" all three variants of the light strip could be merged into one single pallete element. In the editor you can choose the type with the "Button type" property like using the "Square Neutral Light" or many other elements.

**Comment by Luke18033** [comment]
We can't do this, it would require switching to the floor button item class which breaks collisions. Actually, now that I think about it, couldn't we use Cube Type since that works with any item class? We'd just need to figure out what the fourth and fifth variants would be.

**Comment by Luke18033** [comment]
Regardless of whether it would work, this is a [BEE2-items](https://github.com/BEEmod/BEE2-items) issue which should be posted there instead.
