### ISSUE TITLE
Suggestion: portal prelude content and other thing

### ISSUE THREAD

**Issue by nahoJ974** [BEEmod/BEE2.4#830]
Hello, i have suggestion for bee mod and well i will send video because i have a very bad english

1.something who kill you serious he don't give the name of the object in portal prelude)
video : https://www.youtube.com/watch?v=-ZRpS7ArjvE

2. portal stories mel soundtrack because..... this is awesome ?

3. thinking with time machine style

4.Gravity thing because all new thing in portal prelude has not name is affect only cube and if you want turret
video : https://www.youtube.com/watch?v=MfUeK4dp8xc&feature=youtu.be

**Comment by peefTube** [comment]
The Portal Stories: Mel soundtrack is already packaged, I believe.

**Comment by Luke18033** [comment]
Did you even read the contribution guidelines? This is the wrong repository, you're not supposed to combine suggestions, and all of these have been suggested before.
