### ISSUE TITLE
Bee2.4 won't build anything and results in a build error

### ISSUE THREAD

**Issue by WafflesAndSyrup** [BEEmod/BEE2.4#832]
Everytime I try to run bee2.4 it gives me a build error when trying to build the chamber. 
I'm using Windows 10, which bee2.4 is optimized for, but it still seems to have an error.
If anyone has a suggestion, i'll be willing to try.

**Comment by WafflesAndSyrup** [comment]
Nevermind, i fixed it.

**Comment by kayflay** [comment]
Could you detail how you fixed it? I seem to be having a similar/the same issue as you and I'm not sure whether it's worthy of opening a whole new issue. Thanks in advance!

**Comment by WafflesAndSyrup** [comment]
It appears it keeps failing when I try to select 1950s aperture style or anything else. 
But what I did was this.
Open Beemod and click on: File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES.

Wait 1 minute while beemod removes their resources from Portal 2.

Verify the Game Cache Files.

Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

Click on: File ----> Options ----> Development, and now uncheck the option: Preserve Game Directories.

It worked for an overgrown test chamber, but nothing else...

**Comment by TeamSpen210** [comment]
Open up the developer console, the actual error is in there.

**Comment by WafflesAndSyrup** [comment]
I think the reason it didn't work is because I didn't have pr28 packages, i've downloaded them and that seems to fix it.

**Comment by Nikita74RU** [comment]
Why i can comment on closed topics?
