### ISSUE TITLE
[Off-Topic] [Question] How do you become a contribuitor that can close,reopen other one's issues,add labels and more?

### ISSUE THREAD

**Issue by xGARDYx** [BEEmod/BEE2.4#833]
The title is speaking.

**Comment by Fazbear189** [comment]
Uh, you contribute to the mod?

**Comment by Fazbear189** [comment]
I actually have the same question.

**Comment by HugoBDesigner** [comment]
You actively contribute to whatever extent you can, be it via providing your own items, textures, code, or by responding to other issues and such. This still doesn't guarantee a contributor role, though.

**Comment by LautaroL20** [comment]
As HugoDBesigner said, the only way to get the management on the Beemod Issues page and Repository, is by contributing with any kind of relevant item for beemod or another substantial contribution to the mod itself. Tryign to get it via being active on these issues is useless.
