### ISSUE TITLE
BEE 2.4 pr28: api-ms-win-crt-runtime-|1-1-0.dll isn't designed to run in windows or contains error...

### ISSUE THREAD

**Issue by Honza2268** [BEEmod/BEE2.4#836]
So i have this error.  Firs thing i will ask is this: Can it even be opened on 32 bit OS?

**Comment by LautaroL20** [comment]
Oh, a similar issue by another user was opened since a week ago and now reading at your description, it seems that the cause might be that you are running it in a 32 bit O.S!!! Now i have another reason to think what could be causing the issue then.

**Comment by Honza2268** [comment]
nice. deleting those apis worked
