### ISSUE TITLE
Map issues after publishing

### ISSUE THREAD

**Issue by MajickTek** [BEEmod/BEE2.4#837]
So I made a map using BEE2.4 on my Win10 laptop, and it works well. However, after publishing the map and testing it on my Mac, which doesn't have BEE2 (yet), I can't move the player's head.

Here is the map (so you can reproduce the problem):
http://steamcommunity.com/sharedfiles/filedetails/?id=1297250817

**Comment by ncrecc** [comment]
The map's working perfectly fine. This must be a problem on your end

**Comment by MajickTek** [comment]
odd. i'll try again and see if it works.
