### ISSUE TITLE
Aperture Tag Co-Op

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#838]
Include a fix for the portal gun and gel gun in Aperture Tags co-op mode.

**Comment by Fazbear189** [comment]
I am sure you are aware that it's broken.

**Comment by ZombiePwner1** [comment]
@Fazbear189 Um you don't seem to be aware that atlas is supposed to have a paint gun and not a portal gun in aperture tag.........

**Comment by Fazbear189** [comment]
Yeah, in aperture tag, one person has Portal gun, and one person has paint gun, but the portal gun is invisible, and the person who is supposed to have the paint gun has the portal gun model, but shoots paint.

**Comment by ZombiePwner1** [comment]
@Fazbear189 WE cannot fix that if we try to give atlas a portal gun model that can't fire portals it will crash the game. And we can't give p-body a portal gun since it's been replaced by the paint gun.

**Comment by Fazbear189** [comment]
Well, I never said give them to the people that aren't supposed to have them. If Atlas is supposed to fire paint, give him the paint gun model. If P-body is supposed to fire portals, give him the portal gun model!

**Comment by ZombiePwner1** [comment]
@Fazbear189 I just told you we can't give atlas the paint gun model otherwise it crashes the game. p-body we can't give the portal gun because aperture tag reskins the portal gun to look like a paint gun.....

**Comment by Fazbear189** [comment]
Why don't you re-do the files? Because I am pretty sure they are corrupted.

**Comment by Fazbear189** [comment]
Like my vbsp.exe

**Comment by ZombiePwner1** [comment]
@Fazbear189 They are not corrupted this is how they are supposed to be.

**Comment by TeamSpen210** [comment]
We cannot give them different models.

**Comment by Fazbear189** [comment]
So the paint gun is supposed to shoot portals? Because when others play the mod in older versions it was fine.

**Comment by ZombiePwner1** [comment]
@Fazbear189 That's the whole point mate like @TeamSpen210 said we cannot change p-bodies portal gun model.

**Comment by LautaroL20** [comment]
@TeamSpen210 - Do not forget to apply the "Invalid" label when closing the issue.
