### ISSUE TITLE
Suggestion: Art Therapy Style Chambers

### ISSUE THREAD

**Issue by WafflesAndSyrup** [BEEmod/BEE2.4#840]
![250px-art-therapy-example01](https://user-images.githubusercontent.com/36249695/36180366-09d6e476-115b-11e8-95bd-7b81073a782c.jpg)
Art Therapy is the additional co-op course combining BTS and clean and sometimes old aperture chambers.
I'd like to see them as a test chamber style in beemod, i'm not sure if it would work though

**Comment by WafflesAndSyrup** [comment]
Wheatley style chambers would be interesting to see too.

**Comment by ZombiePwner1** [comment]
@WafflesAndSyrup This is already in development.
