### ISSUE TITLE
Suggestion: PotatOS Portal Gun

### ISSUE THREAD

**Issue by WafflesAndSyrup** [BEEmod/BEE2.4#848]
![maxresdefault](https://user-images.githubusercontent.com/36249695/36705647-3ff7fc3e-1ba1-11e8-9c6a-d4c3ec99e516.jpg)
![c08_11](https://user-images.githubusercontent.com/36249695/36705652-435cb9e6-1ba1-11e8-9ca9-a881647b28e0.jpg)

**Comment by LautaroL20** [comment]
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/418
