### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#849]
Bee mod doesn't launch by it's .exe file...
(I installed Microsoft Framework, but when i installed it, bee mod did work still. And then it just starts their logs and packages extraction and... It exits and pallete editor doesnt launch.)

**Comment by Nikita74RU** [comment]
nvm solved, i just installed mod in wrong directory

**Comment by Nikita74RU** [comment]
But i still got an a error
Here it is

**Comment by Nikita74RU** [comment]
![error](https://user-images.githubusercontent.com/35829557/36934855-9f748e8e-1f11-11e8-99fd-77efacfbacd6.PNG)

**Comment by Nikita74RU** [comment]
I think i have item in packages which is listed twice

**Comment by Blacksilver42** [comment]
Reinstall everything and try again.

**Comment by xGARDYx** [comment]
@Nikita74RU is your problem fixed?

**Comment by Nikita74RU** [comment]
Yes. I use 29 Pre Release and i am happy bout that.
