### ISSUE TITLE
Problem with package (i think)

### ISSUE THREAD

**Issue by nahoJ974** [BEEmod/BEE2.4#850]
Hello, well did you renember when i suggested the music of portal stories mel? it's because on my bee 2 i don't have the portal 2 stories mel music but when i go in my package folder, i see melMusic but it's don't work in bee mod, the same for glados p1 voice, if someone can help me.And i hope you gonna understand because my english is really shitty

**Comment by nahoJ974** [comment]
and the versions of the package and the application is the same

**Comment by TeamSpen210** [comment]
You need Portal Stories:Mel installed.
