### ISSUE TITLE
Bee mod 2.4 crashes on start

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#851]
I installed BeeMod 28 Pre-Release. 2.4. Now, all packages are fine. I launch the bee mod and this happens!

![error](https://user-images.githubusercontent.com/35829557/36934905-2d219e3e-1f12-11e8-99d2-2d8f8df1083c.PNG)

**Comment by Nikita74RU** [comment]
![image](https://user-images.githubusercontent.com/35829557/36934907-3886b066-1f12-11e8-8176-998bd2afebea.png)

**Comment by LautaroL20** [comment]
Both, the application and packages must be of the same pre-release version by the way.
