### ISSUE TITLE
Exports fine, then crashes

### ISSUE THREAD

**Issue by Honest-Signal** [BEEmod/BEE2.4#856]
So, bit of an odd issue. I was having trouble exporting for a while so I reinstalled/verified according to some other steps listed in other threads, and exporting works now. However!

I now get 

> ```
> Traceback (most recent call last):
>   File "F:\Git\BEE2.4\src\UI.py", line 853, in export_editoritems
>   File "F:\Git\BEE2.4\src\gameMan.py", line 722, in export
>   File "F:\Git\BEE2.4\src\gameMan.py", line 475, in refresh_cache
> PermissionError: [WinError 5] Access is denied: 'g:\\steam\\steamapps\\common\\portal 2\\bee2\\bin\\avbin.dll'

when exporting. The palette exports into Portal 2 fine, however. It just crashes after this. Additionally, the log says

> ```
> [I] gameMan: Exporting Items and Style for "PORTAL 2"!
> [I] gameMan: Style = BEE2_CLEAN
> [I] gameMan: Music = VALVE_PETI
> [I] gameMan: Skybox = BEE2_CLEAN
> [I] gameMan: QuotePack = BEE2_GLADOS_CLEAN
> [I] gameMan: Elevator = VALVE_APERTURE_LOGO
> [I] gameMan: Should refresh: True
> [I] gameMan: Need to extract - package counts inconsistent!
> [I] gameMan: Cache invalid - copying..
> [I] gameMan: Exporting "Item"
> [I] gameMan: Exporting "ItemConfig"
> [I] gameMan: Exporting "QuotePack"
> [I] packageLoader: G:\Steam\steamapps\common\portal 2\BEE2\bin\..\config\voice\BEE2_GLADOS_CLEAN.cfg
> [I] packageLoader: No normal voice config!
> [I] packageLoader: G:\Steam\steamapps\common\portal 2\BEE2\bin\..\config\voice\MID_BEE2_GLADOS_CLEAN.cfg
> [I] packageLoader: No MidChamber voice config!
> [I] packageLoader: G:\Steam\steamapps\common\portal 2\BEE2\bin\..\config\voice\RESP_BEE2_GLADOS_CLEAN.cfg
> [I] packageLoader: No Responses voice config!
> [I] gameMan: Exporting "Skybox"
> [I] gameMan: Exporting "Music"
> [I] gameMan: Exporting "StyleVar"
> [I] gameMan: Exporting "StyleVPK"
> [I] packageLoader: Sound cache: g:\steam\steamapps\common\portal 2\portal2_dlc3\maps\soundcache\_master.cache
> [I] packageLoader: Written 0 files to VPK!
> [I] gameMan: Exporting "Elevator"
> [I] gameMan: Exporting "PackList"
> [I] packageLoader: Writing packing list!
> [I] gameMan: Exporting "EditorSound"
> [I] gameMan: Exporting "BrushTemplate"
> [I] gameMan: Exporting "ConfigGroup"
> [I] BEE2_config: Saving changes in config "../config\item_cust_configs.cfg"!
> [I] gameMan: Editing Gameinfo!
> [I] gameMan: Writing instance list!
> [I] gameMan: Writing Editoritems!
> [I] gameMan: Writing VBSP Config!
> [I] gameMan: Copying Custom Compiler!
> [I] gameMan: 	* compiler/python36.dll -> bin/python36.dll
> [I] gameMan: 	* compiler/python36.zip -> bin/python36.zip
> [I] gameMan: 	* compiler/srctools._tokenizer.pyd -> bin/srctools._tokenizer.pyd
> [I] gameMan: 	* compiler/unicodedata.pyd -> bin/unicodedata.pyd
> [I] gameMan: 	* compiler/vbsp.exe -> bin/vbsp.exe
> [I] gameMan: 	* compiler/VCRUNTIME140.dll -> bin/VCRUNTIME140.dll
> [I] gameMan: 	* compiler/vrad.exe -> bin/vrad.exe
> [I] gameMan: 	* compiler/_decimal.pyd -> bin/_decimal.pyd
> [I] gameMan: 	* compiler/_hashlib.pyd -> bin/_hashlib.pyd
> [I] gameMan: Copying Resources!
> [I] gameMan: Cache copied.
> [I] gameMan: Deleting: g:\steam\steamapps\common\portal 2\bee2\bee2.ico
> [I] gameMan: Deleting: g:\steam\steamapps\common\portal 2\bee2\readme.txt
> [I] gameMan: Deleting: g:\steam\steamapps\common\portal 2\bee2\bin\avbin.dll

which seems strange (the deleting). Bee2 deleting its own .ico also creates issues when trying to restart it, unless I replace the .ico myself.

**Comment by TeamSpen210** [comment]
Don't put it inside the Portal 2 folder. It shouldn't be in there - it does any needed copying itself.

**Comment by Honest-Signal** [comment]
Oh. Whaddya know! That works. Thanks!
