### ISSUE TITLE
A Couple Suggestions.

### ISSUE THREAD

**Issue by OceanWaves999** [BEEmod/BEE2.4#857]
1. Please Add A Incinerator Item. There Is The Diversity Vent. But It Cant Activate Something If You Put Something In.

2. Make The Rocket Turrets Break Stuff. Right Now There Just A Invincible Turret That One Shots You.
Make Them Break Glass, Cores (My Next Suggestion), etc.

3. Add GLaDOS Boss, Weatley Boss, And Weatley As A Core. Of Course Weatley and GLaDOS Wouldn't Be Anything Without The Neurotoxin, Rocket, And Incinerator But It Would Be Cool To Add Them!

4. The Custom Items To Have Custom Options. What I Mean Is For An Item Like The Portal Gun Petistal To Have The Portal Gun Type To Be Actually Labeled Instead Of Being Button Types. This Will Help So I Don't Have To Test Which One I Picked.

5. Different Turret Types. When You Get A Turret Make Options to Make Them Regular Turrets, Turrets In Boxes, Detective Turrets, And Oracle Turrets. You Can Place Oracle Turrets In Vactubes (It Will Say The Lines It Says In There Usually.) And In Conveyor Belts. (Once You Pick It Up It Will Say Its Lines)

That's All For Now. I Really Hope You Can Add These =)

**Comment by HugoBDesigner** [comment]
For the 4th item, it is not possible: if it was, it would have been done long ago. We cannot edit anything in Portal 2, be it how many items the palette has, or how things get named, or how many options each item can have. This is a technical limitation impossible to overcome because Portal 2 is source-closed, meaning we can't edit the puzzlemaker itself

**Comment by OceanWaves999** [comment]
Ok... Anything About The Other 4?

**Comment by OceanWaves999** [comment]
Ok. Anything About The Other 4?

**Comment by Luke18033** [comment]
Please don't combine suggestions like this, it makes it harder to label and close the issue, especially if you don't use checkboxes. Additionally it's on the wrong repro, half of these are duplicates, and 3 and 5 are "easy Hammer" suggestions. Did you even read the contributing guidelines?

**Comment by OceanWaves999** [comment]
Ok. Just Make The Incinerator Then
