### ISSUE TITLE
Incinerator pls?

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#861]
Can you add an a Emergercy intelligence incinerator

**Comment by Luke18033** [comment]
Duplicate of BEEmod/BEE2-items#95, and this is the wrong repository.

**Comment by TeamSpen210** [comment]
What exactly would it be useful for anyway, really?

**Comment by cartman1337** [comment]
Level design mostly, and perhaps, in closed form, climbing, if it's possible to jump on it with or without the aid of a cube. Along with a fire pit it would make for some nice Portal 1 maps, at least.

**Comment by LautaroL20** [comment]
@Luke18033 - Do not forget to apply the label after closing an issue.
