### ISSUE TITLE
HELP PLOX ! ! ! ! How do I install the BEE2.4 mod on a Mac Os X?

### ISSUE THREAD

**Issue by Ewuffel** [BEEmod/BEE2.4#864]
I accidentally uninstalled the BEE2 mod on my computer, and I decided to install the updated version, but I can't find the mac files! I went to the download the page where they are supposed to be, and I could only find the windows files. I downloaded them, but the exe file wouldn't open even though I have wine installed. I went to github to find some answers, but everyone had already found the mac file. Where do I find the file and how do I install it? Help is appreciated. I literally made this account just to ask this question.

**Comment by Luke18033** [comment]
Release versions aren't available on Mac anymore. You'll need to build the dev version by following the instructions in the README, or use an old version.

**Comment by Ewuffel** [comment]
Ok, so that's how it's installed? I actually need to program it?

**Comment by Ewuffel** [comment]
So I've installed the necessary programs, but it doesn't say what to do next, there's just a line of code.

**Comment by Ewuffel** [comment]
Help would be appreciated

**Comment by Ewuffel** [comment]
Ok, I've installed an old version, but none of the textures are working. What do I do?

**Comment by Ewuffel** [comment]
Can someone plz help?

**Comment by LautaroL20** [comment]
The latest beemod version does not work on mac os x as far as i know.

**Comment by Ewuffel** [comment]
Yeh, but im trying to get the textures to work on BEE2.2. I went to their website and requested a mac version, but I have to make due with what I have now. Unfortunately the textures aren't working and the level editor won't load a level with it installed. Can you help me with that?

PS. I like the new title of the issue :)

**Comment by Ewuffel** [comment]
Please! I need help!

**Comment by LautaroL20** [comment]
@Ewuffel - Ask Spencer.

**Comment by Ewuffel** [comment]
Ok. SPENCER? I NEED HELP!

How exactly do I do that? I'm really new to github.

**Comment by LautaroL20** [comment]
@Ewuffel - You can contact Spencer in a more direct way thru the following links: 

http://steamcommunity.com/id/TeamSpen210 (Steam profile)
https://discord.me/beemod (Discord Page, please, use the Aplication Channel there)

**Comment by Ewuffel** [comment]
Thanks!
