### ISSUE TITLE
TNT Turret

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2.4#865]
So I just updated to the most recent version. What happened to the TNT Turret?

**Comment by TeamSpen210** [comment]
I never reimplemented it. Is it actually that useful?

**Comment by King0191** [comment]
Yes it is... At least for me. I would love if you could implement it. I love the concept of it. Its so cool. I made a map dedicated to it before I upgraded

**Comment by King0191** [comment]
Of course you do not have to implement it back in. Same with the normal bombs. However they would be really neat. due to what you can do with them.

**Comment by LautaroL20** [comment]
This repro is only for issues related to the BEE2.4 application itself; anything else goes on [BEE2-items](https://github.com/BEEmod/BEE2-items/issues).
