### ISSUE TITLE
Beemod Causes "Failure To Compile"

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2.4#866]
I've tried everything. Removing ALL portal 2 files. Uninstalling. Reinstalling. Verifying. Etc. 
Is there a glitch going on rn?

**Comment by Luke18033** [comment]
Post the console log so we can see what the error is.

**Comment by King0191** [comment]
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=False
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "materials/bee2/clean/black_1x1.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/clean/black_1x2.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/clean/black_ceil.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/tile_noise.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/tile_noise_2x1.vtf"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/portal_man.nut"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/video_splitter_specific.nut"
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/bee2/auto_run.nut" into packfile.
[INFO] vrad.pack_content(): Packing complete!
[INFO] vrad.mod_screenshots(): Using automatic screenshot!
[INFO] vrad.mod_screenshots(): No Auto Screenshot found!
[INFO] vrad.mod_screenshots(): Cleaning up screenshots...
[INFO] vrad.mod_screenshots(): Done!
[INFO] vrad.mod_screenshots(): Using PeTI screenshot!
[INFO] vrad.mod_screenshots(): Making "..\portal2\puzzles\76561198209103051\untitled.jpg" replaceable...
[INFO] vrad.main(): Publishing - Full lighting enabled! (or forced to do so)
[INFO] vrad.run_vrad(): Calling original VRAD...
[INFO] vrad.run_vrad(): "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vrad_original.exe" -final -staticproppolys -staticproplighting -textureshadows -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.bsp"
Valve Software - vrad.exe SSE (Mar  1 2018)

      Valve Radiosity Simulator     
8 threads
[Reading texlights from 'lights.rad']
[59 texlights parsed from 'lights.rad']

Loading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Loaded alpha texture materials\Tools\toolsinvisible.vtf
Setting up ray-trace acceleration structure... Done (2.48 seconds)
1246 faces
1 degenerate faces
5740195 square feet [826588160.00 square inches]
0 Displacements
0 Square Feet [0.00 Square Inches]
1245 patches before subdivision
zero area child patch
12533 patches after subdivision
70 direct lights
BuildFacelights:     0...1...2...3...4...5...6...7...8...9...10 (1)
BuildVisLeafs:       0...1...2...3...4...5...6...7...8...9...10 (1)
transfers 1118705, max 349
transfer lists:   8.5 megs
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #1 added RGB(7957, 9276, 9438)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #2 added RGB(4125, 4999, 5272)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #3 added RGB(2526, 3109, 3310)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #4 added RGB(1630, 2026, 2162)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #5 added RGB(1075, 1344, 1433)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #6 added RGB(721, 907, 963)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #7 added RGB(490, 618, 653)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #8 added RGB(336, 426, 446)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #9 added RGB(232, 295, 306)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #10 added RGB(161, 205, 211)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #11 added RGB(112, 143, 146)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #12 added RGB(79, 100, 101)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #13 added RGB(55, 70, 70)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #14 added RGB(39, 49, 49)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #15 added RGB(27, 35, 34)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #16 added RGB(19, 25, 24)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #17 added RGB(13, 17, 16)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #18 added RGB(9, 12, 11)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #19 added RGB(7, 9, 8)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #20 added RGB(5, 6, 6)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #21 added RGB(3, 4, 4)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #22 added RGB(2, 3, 3)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #23 added RGB(2, 2, 2)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #24 added RGB(1, 1, 1)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #25 added RGB(1, 1, 1)
GatherLight:         0...1...2...3...4...5...6...7...8...9...10 (0)
	Bounce #26 added RGB(1, 1, 1)
Build Patch/Sample Hash Table(s).....Done<0.0022 sec>
FinalLightFace:      0...1...2...3...4...5...6...7...8...9...10 (1)
FinalLightFace Done
40 of 40 (100% of) surface lights went in leaf ambient cubes.
ThreadComputeLeafAmbient: 0...1...2...3...4...5...6...7...8...9...10 (0)
Writing leaf ambient...done
Computing static prop lighting : 0ThreadComputeStaticPropLighting: 0...1...2...3...4...5...6...7...8...9...10 (2)

Ready to Finish

Object names       Objects/Maxobjs  Memory / Maxmem  Fullness 
------------       ---------------  ---------------  -------- 
models                  45/1024         2160/49152    ( 4.4%) 
brushes               1251/8192        15012/98304    (15.3%) 
brushsides           10825/65536       86600/524288   (16.5%) 
planes                8248/65536      164960/1310720  (12.6%) 
vertexes              3247/65536       38964/786432   ( 5.0%) 
nodes                  823/65536       26336/2097152  ( 1.3%) 
texinfos               457/12288       32904/884736   ( 3.7%) 
texdata                 48/2048         1536/65536    ( 2.3%) 
dispinfos                0/0               0/0        ( 0.0%) 
disp_verts               0/0               0/0        ( 0.0%) 
disp_tris                0/0               0/0        ( 0.0%) 
disp_multiblend          0/0               0/0        ( 0.0%) 
disp_lmsamples           0/0               0/0        ( 0.0%) 
faces                 1246/65536       69776/3670016  ( 1.9%) 
hdr faces             1246/65536       69776/3670016  ( 1.9%) 
origfaces             1089/65536       60984/3670016  ( 1.7%) 
facebrushes            310/0             620/0        ( 0.0%) 
facebrushlists        1246/0            4984/0        ( 0.0%) 
leaves                 869/65536       27808/2097152  ( 1.3%) 
leaffaces             1421/65536        2842/131072   ( 2.2%) 
leafbrushes           1867/65536        3734/131072   ( 2.8%) 
areas                   11/256            88/2048     ( 4.3%) 
surfedges            10243/512000      40972/2048000  ( 2.0%) 
edges                 6668/256000      26672/1024000  ( 2.6%) 
LDR worldlights          0/8192            0/819200   ( 0.0%) 
HDR worldlights         70/8192         7000/819200   ( 0.9%) 
leafwaterdata            0/32768           0/393216   ( 0.0%) 
waterstrips            150/32768        1500/327680   ( 0.5%) 
waterverts               0/65536           0/786432   ( 0.0%) 
waterindices          2712/65536        5424/131072   ( 4.1%) 
cubemapsamples           3/1024           48/16384    ( 0.3%) 
overlays                 2/512           704/180224   ( 0.4%) 
LDR lightdata         [variable]           0/0        ( 0.0%) 
HDR lightdata         [variable]     1036500/0        ( 0.0%) 
visdata               [variable]        1994/16777216 ( 0.0%) 
entdata               [variable]       92057/393216   (23.4%) 
LDR ambient table      869/65536        3476/262144   ( 1.3%) 
HDR ambient table      869/65536        3476/262144   ( 1.3%) 
LDR leaf ambient       869/65536       24332/1835008  ( 1.3%) 
HDR leaf ambient      2484/65536       69552/1835008  ( 3.8%) 
occluders                0/0               0/0        ( 0.0%) 
occluder polygons        0/0               0/0        ( 0.0%) 
occluder vert ind        0/0               0/0        ( 0.0%) 
detail props          [variable]           1/12       ( 8.3%) 
static props          [variable]           1/13746    ( 0.0%) 
pakfile               [variable]     1139327/0        ( 0.0%) 
physics               [variable]      464249/4194304  (11.1%) 
physics terrain       [variable]           2/1048576  ( 0.0%) 

Level flags = 2

Total triangle count: 3343
Writing c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Error opening c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp!

**Comment by King0191** [comment]
That's what the Portal 2 Console gave me

**Comment by LautaroL20** [comment]
If u already tried verifying cache and etc, still u get the build error it is pretty weird then.

**Comment by benjaminpants** [comment]
Same.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
