### ISSUE TITLE
vbsp.exe a virus?

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#868]
When I try to use Beemod, Avast says the vbsp.exe is infected with IDP.Generic. Which means that a file is acting strangely, which can be signs of malware.

**Comment by TeamSpen210** [comment]
Yes, because it's pretending to be the original compilers. It's not a virus.

**Comment by ZombiePwner1** [comment]
@Fazbear189 Like @TeamSpen210 said it's not a virus it's the way it acts that give anti-viruses false alarms.

**Comment by SexyBoi101** [comment]
the only problem is that i cant delet any of the bee2 files.
