### ISSUE TITLE
Corrupted vbsp.exe

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#869]
When I try to use Portal 2, I verify the game cache, and it says unable to update Portal 2 (corrupt content files) vbsp.exe after I verify it.

**Comment by TeamSpen210** [comment]
Well, we overwrite that, so don't verify your game cache when using BEE2. You can try deleting the file manually to fix that error.

**Comment by Fazbear189** [comment]
I don't have vbsp.exe in my bin, though. I have file names that mention it, like vbsp original, but not exactly vbsp.exe

**Comment by ZombiePwner1** [comment]
@Fazbear189 Rename the vbsp_original to vbsp.exe beemod creates that original file to prevent overwriting the main file.

**Comment by TeamSpen210** [comment]
If it’s missing, you probably have your antivirus software mistakenly triggering on BEE2's compilers. Check their history.

**Comment by Fazbear189** [comment]
It's not. I checked.
