### ISSUE TITLE
Elevator suggestion [Suggestion]

### ISSUE THREAD

**Issue by The-14th-Doctor** [BEEmod/BEE2.4#871]
Hello! I so far like BEE2.4 but something that I would love to see added is an elevator item similar to the ones you see at the start and ends of levels except they allow you to go up and down, I would love if they were a stand alone item but you can make it something with the Vactubes or piston / track platforms.

Thanks
:D

**Comment by TeamSpen210** [comment]
Duplicate of BEEmod/BEE2-items#2565
