### ISSUE TITLE
Question about DEV

### ISSUE THREAD

**Issue by xGARDYx** [BEEmod/BEE2.4#872]
How do you acces the development version? Do you have to be a contribuitor or what?

**Comment by LautaroL20** [comment]
> xGARDYx Said: "Do you have to be a contribuitor or what?"

No, you only must know how to install Pyhon and how to build the compiler thru CMD commands. And also, you will need to clone both beemod repros thru Github for desktop.

**Comment by xGARDYx** [comment]
._. that sounds pretty hard :/

**Comment by xGARDYx** [comment]
now the question that i want to ask is (IT SOUND EXTREMELY STUPID but): can you do it for me? 😸
