### ISSUE TITLE
Adhesion gel

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#874]
Makes players to stick onto walls, same with cubes.
Purple colour.

**Comment by Luke18033** [comment]
See the [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-adhesion-gel-to-bee24) for why this can't be added.

**Comment by LautaroL20** [comment]
This is by far the most trite suggestion ever posted on the beemod´s github repositories.
