### ISSUE TITLE
Plain Crusher Panel

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#876]
Seen in Portal Prelude, just a panel moving down, acts like a slow crusher.
(can be used on walls too)

**Comment by LautaroL20** [comment]
This repro is only for issues related to the BEE2.4 application itself; anything else goes on [BEE2-items]

**Comment by TeamSpen210** [comment]
It’s already been suggested (and I've mostly finished reimplementing) under the name Slow Crusher.
