### ISSUE TITLE
Portal 2's in-game editor crashes when used.

### ISSUE THREAD

**Issue by ThEnderYoshi** [BEEmod/BEE2.4#877]
Portal 2's editor was working just fine until I installed BEE2 (pre28), now it freezes for about 5 seconds before it just crashes. After uninstalling bee2, the editor still crashes.

**Comment by xGARDYx** [comment]
I had that problem too but (maybe it wont be fixed like this for you[most likely not]) i just restarted my PC and then opening Portal 2 again.

**Comment by ThEnderYoshi** [comment]
Nope, didn't work :/
