### ISSUE TITLE
Beemod causes "Failure To Compile"

### ISSUE THREAD

**Issue by ConnorT05** [BEEmod/BEE2.4#878]
I rescently downloaded Bee2 and when I go to test my level it says there was an error. This is what the Dev Console says

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr28 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'APERTURE_TAG_NIGEL'}
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/over/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/over/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/over/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/over/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/over/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/over/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/over/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/over/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/over/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/over/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/over/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[INFO] fizzler.read_configs(): Loaded 12 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (152 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.monitor.mon_remove_bullseyes(): Bullseye defaultdict(<class 'int'>, {Vec_tuple(x=320.0, y=192.0, z=0.0): 1, Vec_tuple(x=832.0, y=704.0, z=0.0): 1})
[INFO] cond.monitor.mon_remove_bullseyes(): Pos: Vec_tuple(x=320.0, y=192.0, z=0.0) -> 
[INFO] cond.monitor.mon_remove_bullseyes(): Bullseye defaultdict(<class 'int'>, {Vec_tuple(x=320.0, y=192.0, z=0.0): 0, Vec_tuple(x=832.0, y=704.0, z=0.0): 1})
[INFO] cond.monitor.mon_remove_bullseyes(): Pos: Vec_tuple(x=832.0, y=704.0, z=0.0) -> 
[INFO] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[WARNING] cond.core.resolve_value(): Invalid fixup ($color) in the "cd6" instance:
| <Entity>: 
| {
| classname = "func_instance"
| targetname = "cd6"
| file = "instances/BEE2/over/items/cube/dropper.vmf"
| origin = "320 320 320"
| angles = "0 180 180"
| $connectioncount = "0"
| $item_fall_straight_down = "1"
| $disable_autodrop = "0"
| $disable_autorespawn = "0"
| }
| 
|_{'connectioncount': FixupTuple(var='connectioncount', value='0', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='0', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}

[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 2/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
| {
| "ID" "PORTAL_INOUT"
| "snd" "core/core_map11_intro.wav"
| "cc_emit" "core.m11_intro"
| }
|_

[INFO] voiceLine.find_group_quotes(): "EXIT": 1/2 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
| {
| "ID" "GENERIC_EXIT_PARENTS"
| "snd" "core/core_s4_outro.wav"
| "cc_emit" "core.s4_outro"
| }
|_

[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {Vec_tuple(x=320.0, y=192.0, z=0.0): 0, Vec_tuple(x=832.0, y=704.0, z=0.0): 0})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: N, Orange: N
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['glass', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'cubedropper', 'cubedropperstandard', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'orangeportal', 'orangeportalspawner', 'autoportal', 'blueportal', 'blueportalspawner', 'monitor', 'spawn_nogun']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=27701, misses=395, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_cube.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Adding Goo Mist...
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/base.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_arrow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/josepezdj/signage_wasted/jose_wasted_signage_exit.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_on.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_rusty_on.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/comp_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/on_speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/metal_box_rusty/speed.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/monitor_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/triple_wallpipe_nocull.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/glados_screen_dirty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/triple_wallpipe_nocull_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/triple_wallpipe_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/truss_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/broken_indicator_corner.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/glass.vmt"
[INFO] vbsp.make_packlist(): "materials/bee2/blend_concrete_dirt.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown_off.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_a_overgrown_off.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_aoff.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_aoff.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_b_overgrown.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_b_overgrown.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_b_overgrown_off.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_boff.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_c_overgrown.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_c_overgrown.vtf"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_c_overgrown_off.vmt"
[INFO] vbsp.make_packlist(): "materials/models/elevator/elevator_main_coff.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_stair_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_32b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/overgrown/hanging_walkway_end_cap.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/metal_box_rusty.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/truss_1024.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/truss_512.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_overgrown/wrecked_dropper_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/corner_c.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/straight_a.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/straight_b.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/triple_wallpipe/straight_c.mdl"
[INFO] vbsp.make_packlist(): "models/bee2/cam_parts/cam_base_clean.mdl"
[INFO] vbsp.make_packlist(): "models/bee2/cam_parts/cam_lens_clean.mdl"
[INFO] vbsp.make_packlist(): "models/bee2/cam_parts/cam_shaft_clean.mdl"
[INFO] vbsp.make_packlist(): "models/bee2/props_ingame/monitor_glass.mdl"
[INFO] vbsp.make_packlist(): "models/bee2/props_overgrown/glados_screen_curve.mdl"
[INFO] vbsp.make_packlist(): "models/elevator/elevator_b_skins.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/change_models.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/mon_camera.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/bee2/portal_man.nut"
[INFO] vbsp.make_packlist(): "materials/BEE2/overgrown/screens/elevator_video_overlay1.vmt" as "materials/BEE2/overgrown/lightboard_overlay.vmt"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER] Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198240331128\autosave.p2c
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!
[PORTAL2 PUZZLEMAKER] Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198240331128\autosave.p2c
[PORTAL2 PUZZLEMAKER] Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198240331128\autosave.p2c
[PORTAL2 PUZZLEMAKER] Saved puzzle: C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198240331128\autosave.p2c

Anyone Have a fix?

**Comment by LautaroL20** [comment]
@ConnorT05 - Is this your very first time at using Beemod, or do you used other versions in the past?

**Comment by ConnorT05** [comment]
Yes this is my First time using Beemod.

**Comment by ConnorT05** [comment]
This is my first time using it I have never downloaded any other version.

**Comment by LautaroL20** [comment]
You may be wondering why ive asked that, and it is that when using BEE2.4 after installing a new version, old resources from past releases will not be overwritten, resulting in bugs that were fixed still being present and some things not working correctly. Your issue does not seems to be related to this, so i can not guess what may be causing it.

**Comment by TeamSpen210** [comment]
@LautaroL20, that should never happen anymore. If it ever does, there's a bug in the application.

**Comment by ConnorT05** [comment]
Then what do I do about this situation?

**Comment by ConnorT05** [comment]
So how do I fix it then?

**Comment by TeamSpen210** [comment]
Check your `bin/` folder, see if there's a vbsp_original.exe` in there, and if so what the icon it uses.

**Comment by ConnorT05** [comment]
There is a vbsp.exe but there's no vbsp_original.exe.

**Comment by LautaroL20** [comment]
You can give it a try to the PRL29 of Beemod which was released yesterday and see if this version works for you:

https://github.com/BEEmod/BEE2.4/releases/tag/2.4.0pr29 (Application)
https://github.com/BEEmod/BEE2-items/releases/tag/pr29 (Packages)

**Comment by TeamSpen210** [comment]
Delete `vbsp.exe`, `vbsp_original.exe`, `vrad.exe` and `vrad_original.exe`. Verify cache, then run and export BEE again. (This is in Portal 2/bin/ right?)

**Comment by ConnorT05** [comment]
Yes

**Comment by ConnorT05** [comment]
No luck. Now What?

**Comment by LautaroL20** [comment]
Get help support from many experienced beemod users through the discord server, i am absolutely sure you will get a proper solution and if you don´t, then its your PC´s fault. Discord Server: https://discord.me/beemod

**Comment by Nalkahn** [comment]
I have the same problem since pr27 ... I was waiting for a fix, but I'll try to help.

I was thinking "maybe it's because I installed beemod2 on a drive different to the game."

The last line before the bug is very strange : look at the / and the \ .  We find the same patern on issue #866

**Comment by ConnorT05** [comment]
I tried deleting vbsp.exe, vbsp_original.exe, vrad.exe and vrad_original.exe. and verifying and now I get this error message.
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=True
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.gen_sound_manifest(): Written new soundscripts_manifest..
[INFO] vrad.gen_part_manifest(): Written new particles_manifest..
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content(): # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_grey.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_grey.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_water.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_water.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_white.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_white.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_p1/door_01.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_p1/door_01.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_p1/walllight_sheet.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/models/props_p1/walllight_sheet.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/light_recessedcool_glow.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/metalwall048b_lrg.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/metalwall048b_lrg.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/metalwall048b_med.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/metalwall048b_med.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/modular_wall_light.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/detail_concrete_03.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/metaldoor028a.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/metaldoor028a.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observationwall_001a.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observationwall_001a.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observationwall_001b.vmt"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observationwall_001b.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vrad.pack_content(): # "materials/bee2/p1/overlay_light_gradient.vtf"
[INFO] vrad.pack_content(): # "materials/paintblob.vmt"
[INFO] vrad.pack_content(): # "materials/paintblobs/blob_surface_grey.vtf"
[INFO] vrad.pack_content(): # "materials/paintblobs/blob_surface_purple.vtf"
[INFO] vrad.pack_content(): # "materials/paintblobs/blob_surface_stick.vmt"
[INFO] vrad.pack_content(): # "models/bee2/props_ingame/p1_gel_dropper.mdl"
[INFO] vrad.pack_content(): # "models/bee2/props_p1/door_frame_thick.mdl"
[INFO] vrad.pack_content(): # "models/bee2/props_p1/door_left.mdl"
[INFO] vrad.pack_content(): # "models/bee2/props_p1/door_right.mdl"
[INFO] vrad.pack_content(): # "models/bee2/props_p1/obs_light.mdl"
[INFO] vrad.pack_content(): # "models/bee2/props_p1/security_camera.mdl"
[INFO] vrad.pack_content(): # "particles/paint_bomb_fx_reflect.pcf"
[INFO] vrad.pack_content(): # "particles/paint_splats_fx_reflect.pcf"
[INFO] vrad.pack_content(): # "scripts/bee2_snd/portal_sounds.txt"
[INFO] vrad.pack_content(): # "scripts/vscripts/bee2/change_models.nut"
[INFO] vrad.pack_content(): # "sound/bee2/music/pro/beeps.mp3"
[INFO] vrad.pack_content(): # "sound/bee2/p1/doorstop1.wav"
[INFO] vrad.pack_content(): # "sound/bee2/p1/garage_stop1.wav"
[INFO] vrad.pack_content(): # "sound/bee2/p1/wall_move5.wav"
[INFO] vrad.pack_content(): Potential additional files:
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content(): # "scripts/game_sounds_manifest.txt"
[INFO] vrad.pack_content(): # "particles/particles_manifest.txt"
[INFO] vrad.pack_content(): # "scripts/BEE2_generated_music.txt"
[INFO] vrad.pack_content(): # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
[INFO] vrad.pack_content(): Injecting "scripts/game_sounds_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "particles/particles_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/BEE2_generated_music.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/bee2/auto_run.nut" into packfile.
[INFO] vrad.pack_content(): Packing complete!
[INFO] vrad.mod_screenshots(): Using automatic screenshot!
[INFO] vrad.mod_screenshots(): No Auto Screenshot found!
[INFO] vrad.mod_screenshots(): Cleaning up screenshots...
[INFO] vrad.mod_screenshots(): Done!
[INFO] vrad.mod_screenshots(): Using PeTI screenshot!
[INFO] vrad.mod_screenshots(): Making "..\portal2\puzzles\76561198240331128\untitled.jpg" replaceable...
[INFO] vrad.main(): Forcing Cheap Lighting!
[INFO] vrad.run_vrad(): Calling original VRAD...
[INFO] vrad.run_vrad(): "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vrad_original.exe" -bounce 2 -noextra -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp"
[WARNING] vrad.run_vrad(): VRAD failed! (1)

**Comment by Konclan** [comment]
Ok seriously we need to teach people to either use pastebin or the fact that it usually dumps a nice little error message at the end of the compile.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
