### ISSUE TITLE
Beemod causes "Failure To Compile"

### ISSUE THREAD

**Issue by offbrandbiscuit** [BEEmod/BEE2.4#879]
I've been creating a test chamber with the Portal 1 style, and Portal 1 skybox. It uses Positronic Energy Orbs from Rexaura, which I thought was the issue, but when I removed them, it didn't work. It also uses High Energy Pellet Launchers and Catchers, Angled Blocks, Cold Lights, Pedestal Buttons, regular Buttons, Cubes, CharmberLocks, Fizzlers, Angled Panels, and that's about it.
But, everytime I try to build it to publish it, it encounters a build error, and and when I check the console, it says this:
_______________________________________________________________________________________________________________

VVIS failed.

Valve Software - vvis.exe (Mar  1 2018)
2 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1521859450.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1521859450.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\1521859450.prt

Apparently, VVIS has to do with visibility and stuff. So, apparently its meant to check the visibility, and will encounter a build error if it doesn't check. So.... how to fix it?

![screenshot 6](https://user-images.githubusercontent.com/37862715/38015180-93e8eff2-329d-11e8-9190-42e9c4ae143d.png)

And a picture of my chamber. Anything I should be aware of?
![screenshot 5](https://user-images.githubusercontent.com/37862715/38015204-a4bb2cbe-329d-11e8-8565-3eab8f077b9d.png)

Thank you for reading, and I hope you'll be able to help.

**Comment by Blacksilver42** [comment]
Check your antivirus -- They have a thing for deleting BEE's modified test compilers.

**Comment by offbrandbiscuit** [comment]
Apologies, I fixed this quite a while ago. However, I appreciate all the help and responses I have received.
Thank you.
