### ISSUE TITLE
Hammer can't read preview.prt

### ISSUE THREAD

**Issue by BloxingGames** [BEEmod/BEE2.4#883]
I tried exporting my map to hammer and whenever I run the map I get an error. Help would be much appreciated.
I checked and there isn't even a preview.prt in the styled folder.
The error:
CDynamicFunction: Loading library 'Kernel32.dll' (73E80000)
CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77404120

-------------------------------------------------------------------------------
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
-------------------------------------------------------------------------------

[INFO] vbsp.main(): BEE2.4.0pr28 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): New path: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[WARNING] vbsp.main(): Hammer map detected! skipping conversion..
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf"
[INFO] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Mar  1 2018)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
 | Patching WVT material: maps/preview/anim_wp/framework/blend_backpanels02_pipes_wvt_patch
 | fixing up env_cubemap materials on brush sides...
 | ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
 | **** leaked ****
 | Entity prop_static (1024.00 2560.00 784.00) leaked!
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (960.0 3072.0 1122.0)
 | Leaf 0 contents: CONTENTS_SOLID
 | Leaf 1 contents:
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (448.0 3072.0 1122.0)
 | Leaf 0 contents: CONTENTS_SOLID
 | Leaf 1 contents:
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1024.0 3264.0 64.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1024.0 3776.0 64.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1024.0 3584.0 -967.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1024.0 3584.0 192.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1024.0 3264.0 320.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 |
 | FindPortalSide: Couldn't find a good match for which brush to assign to a portal near (1024.0 3776.0 320.0)
 | Leaf 0 contents:
 | Leaf 1 contents: CONTENTS_SOLID
 | viscontents (node 0 contents ^ node 1 contents): CONTENTS_SOLID
 | This means that none of the brushes in leaf 0 or 1 that touches the portal has CONTENTS_SOLID
 | Check for a huge brush enclosing the coordinates above that has contents CONTENTS_SOLID
 | Candidate brush IDs:
 |
 | *** Suppressing further FindPortalSide errors.... ***
 | Processing areas...done (0)
 | Building Faces...done (0)
 | Chop Details...done (0)
 | Find Visible Detail Sides...
 | Merged 130 detail faces...done (0)
 | Merging details...done (0)
 | FixTjuncs...
 | PruneNodes...
 | WriteBSP...
 | done (1)
 | Finding displacement neighbors...
 | Finding lightmap sample positions...
 | Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
 | Building Physics collision data...
 | done (1) (868983 bytes)
 | Static prop models/props_underground/old_speaker_big.mdl outside the map (547.94, 0.13, 223.96)
 | Static prop models/props_underground/old_speaker_big.mdl outside the map (1628.06, 2943.87, 223.96)
 | Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
 | Water found with no water_lod_control entity, creating a default one.
 | Compacting texture/material tables...
 | Reduced 4248 texinfos to 1321
 | Reduced 145 texdatas to 133 (4719 bytes to 4276)
 | Writing C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview.bsp
 |
 | nummapplanes:     (  9044 / 65536 )
 | nummapbrushes:    (  2336 /  8192 )
 | nummapbrushsides: ( 19786 / 65536 )
 | num_map_overlays: (    82 /   512 )
 | nummodels:        (   252 /  1024 )
 | num_entities:     (  1136 / 16384 )
 |
 | 34 seconds elapsed
 | CDynamicFunction: Loading library 'Kernel32.dll' (73E80000)
 | CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77404120
 | CDynamicFunction: Closing library 'Kernel32.dll' (73E80000)
 |_

[INFO] vbsp.run_vbsp(): VBSP Done!
[INFO] vbsp.make_vrad_config(): Generating VRAD config...
[INFO] vbsp.main(): BEE2 VBSP hook finished!

-------------------------------------------------------------------------------
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"
-------------------------------------------------------------------------------

-------------------------------------------------------------------------------
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vvis.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\styled\preview"
-------------------------------------------------------------------------------

CDynamicFunction: Loading library 'Kernel32.dll' (73E80000)
CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77404120
Valve Software - vvis.exe (Mar  1 2018)
4 threads
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\styled\preview.bsp
reading c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\styled\preview.prt
LoadPortals: couldn't read c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\styled\preview.prt

**Comment by offbrandbiscuit** [comment]
Chambers made in Hammer that utilise stuff from Beemod don't really work. I've tried it before, and it always fails to run.

**Comment by ZombiePwner1** [comment]
@BloxingGames There is actually a prop_static leaked in the map meaning it's somewhere outside the map. All models must be inside a map for it to compile and or export.

**Comment by offbrandbiscuit** [comment]
Right. Apologies.

**Comment by BloxingGames** [comment]
Thanks, all sorted now.
Took me a while

**Comment by FrozenDragon0** [comment]
> Thanks, all sorted now. Took me a while

It took multiple years to sort this issue out?

**Comment by csososo** [comment]
> Thanks, all sorted now. Took me a while

How?
