### ISSUE TITLE
Lighting/Chamber Construction Error

### ISSUE THREAD

**Issue by Jazz63540** [BEEmod/BEE2.4#884]
So this seems to affect the versions after Pr27. I export my chosen palette, style, music, etc. I go to create a new chamber. I build the chamber and the lighting is wrong:
![20180330184433_1](https://user-images.githubusercontent.com/22215605/38147901-25df694a-344c-11e8-9e1e-6200e9e0f3ba.jpg)

I then press tab and try to rebuild but this time the loading bars that say Building Test Chamber, etc. don't show up and it just says There was an error building the puzzle:
![20180330184449_1](https://user-images.githubusercontent.com/22215605/38147959-5ead264a-344c-11e8-9615-5bf3d8c6b090.jpg)

After this I tried Pr27 again and it works fine. Before installing the latest version of BEE2.4 (Pr29), I uninstalled Pr27 from Portal 2 and then verified the game cache but to no avail.

**Comment by Luke18033** [comment]
Post the console log, that "error building the puzzle" message is useless on its own.

**Comment by Jazz63540** [comment]
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Connection to Steam servers successful.
   VAC secure mode is activated.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198095556696\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
Error: Operator stop_entry, unknown sound operator attribute input_start
Unknown command "cl_puzzlemaker_start_previewing"
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
*************************************************************************************************
*** ERROR: logic_relay InstanceAuto1-global_ents-environment_testchamber has been triggered but is awaiting refire. OUTPUTS WILL NOT BE FIRED!!!
*************************************************************************************************

"puzzlemaker_show" = "1" ( def. "0" )                                            - 1 shows the puzzle maker,  0 hides it
Unknown command "cl_puzzlemaker_start_editing"
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 69 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 6587 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VVIS): 7533 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VRAD): 13679 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (complete): 14772 (ms) ...launching map!
Error: Operator stop_entry, unknown sound operator attribute input_start
---- Host_Changelevel ----
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
PrecacheScriptSound 'music.BEE2' failed, no such sound script entry
prop_glass_futbol at (592.000, 192.000, 81.609) has no model name!
Commentary: Could not find commentary data file 'maps/puzzlemaker/preview_commentary.txt'. 
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
Unknown command "cl_puzzlemaker_start_previewing"
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
=======================Trying to GivePlayerPortalgun
=======================Trying to UpgradePlayerPortalgun
Updating sound cache [8798 entries]
Found 8789 sound files on disk
Updated 0 out of 8789 cached files [365.747 msec]
prop_glass_futbol at (592.000, 192.000, 81.609) has no model name!
prop_glass_futbol has an no spawner set. It will not respawn.
Late precache of models/props/futbol_gib01.mdl
Late precache of models/props/futbol_gib02.mdl
Late precache of models/props/futbol_gib03.mdl
Late precache of models/props/futbol_gib04.mdl
Redownloading all lightmaps
SAVEGAME:  772.3kb,  238.5kb used by 551 entities (puzzlemaker/preview)
SAVEGAME:   28.0kb,   14.8kb used by 177 entities (puzzlemaker/preview)
SAVEGAME:    1.0kb,    0.0kb used by   0 entities (puzzlemaker/preview)
Jazz63540 unpaused the game
"puzzlemaker_show" = "1" ( def. "0" )                                            - 1 shows the puzzle maker,  0 hides it
Unknown command "cl_puzzlemaker_start_editing"
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 52 (ms)
Could not execute the command:
   "E:/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "E:/Steam/steamapps/common/Portal 2/portal2/" "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Windows gave the error message:
   "The system cannot find the file specified."

VBSP failed.

Failed to start process ("E:/Steam/steamapps/common/Portal 2/bin/vbsp.exe" -entity_limit 1750 -game "E:/Steam/steamapps/common/Portal 2/portal2/" "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (E:/Steam/steamapps/common/Portal 2/bin/)


[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198095556696\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198095556696\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198095556696\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198095556696\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198095556696\autosave.p2c

**Comment by Jazz63540** [comment]
I got this when I tried to build a blank chamber and for some reason it loaded a chamber that I had previously built but not saved.

**Comment by TeamSpen210** [comment]
Check your antivirus, it might be deleting BEE2's vrad and vbsp.

**Comment by Jazz63540** [comment]
It worked! Thanks very much :D
