### ISSUE TITLE
Custom Music

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#885]
Because why not?

**Comment by Luke18033** [comment]
You can already do this, either by using aerond's music changer (linked in the Help menu) or by creating the package yourself.

**Comment by Nikita74RU** [comment]
How bout you open this again? This will not work on 29 pre.

**Comment by Luke18033** [comment]
That would be an issue with BMMC, which you'll want to ask aerond about.

**Comment by Nikita74RU** [comment]
Blame the 29 pre and BMMC
