### ISSUE TITLE
Exporting Error

### ISSUE THREAD

**Issue by TANER05** [BEEmod/BEE2.4#889]
When I try to export the palette, It gives an error: 
![bee2](https://user-images.githubusercontent.com/24416767/38315299-dc1a404e-3830-11e8-92a9-4197ea0555d6.PNG) 
What can I do? And also my portal 2 was closed.

**Comment by TANER05** [comment]
Nevermind, I fixed it. It was tha antivirus causing it. So I deactivated it.

**Comment by maocat2000** [comment]
taner05 how??? same problem w python 36
