### ISSUE TITLE
Add A Player Start!

### ISSUE THREAD

**Issue by TANER05** [BEEmod/BEE2.4#892]
It could be cool if you added a player start. When you place it on the map, you would start the game from there instead of the door or the elevator. Could you do that? Please?

**Comment by xDadiKx** [comment]
Hmm... I'm not sure, it would look unprofessional. Maybe add an env_fade or a door behind to not make it look like the player came out of nowhere. It would be also better to add a bed waking up sequence and maybe back to sleep for an exit.
If you really want to, you could make a Hammer map to tell a story, the Puzzle Maker is simply for making puzzles, not telling stories.

**Comment by TANER05** [comment]
But in Hammer I can't make them. And when I do, It gives errors.
