### ISSUE TITLE
PRL29 Bug: Typo in Working Coop Grates

### ISSUE THREAD

**Issue by xDadiKx** [BEEmod/BEE2.4#893]
- If the Grate is NOT facing a white wall, almost mentioned items can go through exepting Funnels and Light Bridges.
- Almost Gel Flows can go through, exept Bombs.

**Comment by LautaroL20** [comment]
Seems the typo is in "exepting" and "exept", appart from that everything else seems to be correct.

**Comment by LautaroL20** [comment]
Now fixed, however this issue will have to be closed manually once PRL30 is out since its not possible to generate a closing commit thru the "Items Repro" using Github from Desktop.

**Comment by TeamSpen210** [comment]
Yes you can, by mentioning the full repro name: `closes BEEmod/BEE2.4#893`.

**Comment by LautaroL20** [comment]
Did not know. I guess ill try using that code after i fix the disproportionate selection mesh of the "Toggle Latch" item, and see if it generates the closing commit, here.

**Comment by ZombiePwner1** [comment]
@peefTube Remember the item was made from @LautaroL20 And his English still needs some improvements.

**Comment by peefTube** [comment]
I know, just trying to help out ;)
