### ISSUE TITLE
PR29 Piston Panel AI issue

### ISSUE THREAD

**Issue by markd0811** [BEEmod/BEE2.4#895]
https://youtu.be/OO4liCRn-sI
As seen in this video, a piston platform (working normally in PR28/stock) is malfunctioning in PR29.
The platform is positioned to move downward when the player steps onto it. No other elements are connected to the platform, and the theme is Overgrown.
The video demonstrates that on first standing on this platform it does nothing. On stepping off and on again, it goes down one tile, instead of the intended 3. The same occurs if the platform is set to descend two tiles; it only goes down one.

**Comment by markd0811** [comment]
UPDATE: Upon stepping on a descending lift for a third, fourth, etc. time, it appears to behave normally.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.
