### ISSUE TITLE
Loading Screens Option.

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#897]
You can choose the loading screens for your chambers, 
Coop: Original with P-Body flying in excursion funnel, joking on atlas and etc, just original coop screens.
SP: Old Aperture Loading screens, Wheatley loading screens, Overgrown loading screen, Clean screen (already included)

**Comment by BETTEREXTENEDEDITORMOD** [comment]
This is impossible to do

**Comment by Nikita74RU** [comment]
Wrong

**Comment by HugoBDesigner** [comment]
I believe it might actually be impossible to do with puzzlemaker.

**Comment by TeamSpen210** [comment]
Indeed.
