### ISSUE TITLE
can only use the build and play level button once, and then it says error

### ISSUE THREAD

**Issue by GamerX69** [BEEmod/BEE2.4#901]
so i made my first level with the bee2 mod and everything, i used the overgrown textures and stuff, when i tried it the first time, it all went fine, but after i pressed the build and play button a second time, it said Error
There was an error building the puzzle, im just worried that i cant use the mod. is this common to other people too? i use the release 29 on both packages and application, so please help me out a bit
![20180416221308_1](https://user-images.githubusercontent.com/38441254/38832896-44efa162-41c4-11e8-8a5a-3d40046ad477.jpg)

**Comment by Konclan** [comment]
Can you post the last 10 or so lines in your developer console right after the error happens?

**Comment by TeamSpen210** [comment]
Likely a problem with your antivirus.

**Comment by GamerX69** [comment]
ok i will try turning it off


2018-04-17 3:37 GMT+02:00 TeamSpen210 <notifications@github.com>:
