### ISSUE TITLE
UI Bug (Invalid)

### ISSUE THREAD

**Issue by Nolram12345** [BEEmod/BEE2.4#902]
When im trying to start Bee the Item editor opens , but not the compiler options or all these other Windows . How can i fix this ?

**Comment by LautaroL20** [comment]
On the almost upper left corner of the Bee´s window, you will see 4 buttons with different letters, you must click on the "C" letter. The "P" button is for selecting a Pallete, the "E" button is for the exporting options, the "S" button is for the styling options.
