### ISSUE TITLE
Game crashes when I open my test chamber menu.

### ISSUE THREAD

**Issue by StartingByP** [BEEmod/BEE2.4#903]
By some reason, when I open My Test Chambers menu, the game crashes.

**Comment by LautaroL20** [comment]
Verify the game cache files, that must fix your crash in Portal 2.

**Comment by TeamSpen210** [comment]
This is often also caused by a corrupt autosaved puzzle. Delete `Portal 2/portal2/puzzles/<steam ID>/autosave.p2c` (or temporarily move it).
