### ISSUE TITLE
PRE-RELEASE 31 - BEE 2.4 Unable to build puzzle 

### ISSUE THREAD

**Issue by UserBlackBox** [BEEmod/BEE2.4#905]
BEE 2.4 is unable to build the puzzle. I saw this issue many times but each solution seemed specific to that one user.
I am using **BTS/Factory** Texture and Skybox
I am using Portal 2 **default items plus Bomb Cube, Door, Chamber Lock, Angled Bricks, Angled Corners, Flat Blocks, Closed Solid Field, Portal Gun Pedestal, Windows, and Glass Hole**.

**The developer console says the following:**
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr28 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'glass_scale': '0.05'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 2
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (264 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[ERROR] cond.core.check_all(): Error in MetaCondition "link_cubes":
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 485, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 304, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 293, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\cubes.py", line 1101, in link_cubes
ValueError: Unknown cube "linkage" value (5) in cube!
A cube has a timer set which doesn't match any droppers.

**Comment by LautaroL20** [comment]
I will give this a test in BTS, however it could be related to a linked cube somewhere in your puzzle? The value Errror of your log says: "Unknown cube "linkage" value (5) in cube!"

**Comment by TeamSpen210** [comment]
```
Unknown cube "linkage" value (5) in cube!
A cube has a timer set which doesn't match any droppers.
```
You have a cube set to respawn from a dropper (set to 5), but no such dropper exists. Check your cubes for that, and set it to infinite if you don't want that.

**Comment by quentin9909** [comment]
I think it is a bomb cube that I might have accidentally set as 5.

**Comment by quentin9909** [comment]
I deleted the two Bomb Cubes that were set to 5 and readded them as their default form and it still failed to build. The console now says this:

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr28 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'glass_scale': '0.05'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[INFO] fizzler.read_configs(): Loaded 13 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 2
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (369 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] brushes.res_import_template(): IDS: set()
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[WARNING] barriers.test_hole_spot(): No center barrier at 1088 1216 448, 0 -1 -0
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'1'}
[INFO] brushes.res_import_template(): IDS: {'24'}
[INFO] brushes.res_import_template(): IDS: {'24'}
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[WARNING] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (731 in final) is not on grid!
[WARNING] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[WARNING] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (300 in final) is not on grid!
[WARNING] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: N, Orange: N
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['bottomless_pit', 'fizzler', 'tdb_ff', 'glass', 'grating', 'cube', 'cubetulebycubebomb', 'cubedropperlesstulebycubebomb', 'cubenotcompanion', 'cubestandard', 'cubedropperlessstandard', 'cubesphere', 'cubedropperlesssphere', 'cubesphereshaped', 'cubedropper', 'cubedroppersphere', 'cubedropperstandard', 'cubebutton', 'floorbutton', 'buttonacceptscube', 'ballbutton', 'buttonacceptsball', 'gel', 'water', 'watergel', 'cleargel', 'orangeportal', 'blueportal', 'orangeportalspawner', 'orangeportalgun', 'blueportalspawner', 'blueportalgun', 'dualportalgun', 'pedestalbutton', 'faith', 'catapult', 'faithplate', 'pistonplatform', 'piston', 'panel', 'deadly', 'turret', 'factorycorridor', 'spawn_nogun']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=43290, misses=374, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/logic/goo_fade.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.corner: 3>: ['instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_1.vmf', 'instances/BEE2/bts/sky/corner_2.vmf', 'instances/BEE2/bts/sky/corner_3.vmf'], <CONN_TYPES.straight: 2>: ['instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_1.vmf', 'instances/BEE2/bts/sky/side_2.vmf', 'instances/BEE2/bts/sky/side_3.vmf', 'instances/BEE2/bts/sky/side_4.vmf'], <CONN_TYPES.triple: 4>: ['instances/BEE2/bts/sky/triple_1.vmf', 'instances/BEE2/bts/sky/triple_2.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/bts/sky/pillar_1.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_2.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf', 'instances/BEE2/bts/sky/pillar_3.vmf']}
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 576 -64 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 448 -64 64, NSEW: (False, True, False, False), lookup: (<CONN_TYPES.side: 1>, '0 270 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 448 192 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 320 64 64, NSEW: (False, False, False, True), lookup: (<CONN_TYPES.side: 1>, '0 180 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 576 192 64, NSEW: (True, False, False, False), lookup: (<CONN_TYPES.side: 1>, '0 90 0')
[INFO] bottomlessPit.make_bottomless_pit(): Pos: 704 64 64, NSEW: (False, False, True, False), lookup: (<CONN_TYPES.side: 1>, '0 0 0')
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.clump_walls(): Clumping: 300 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[WARNING] vbsp.make_packlist(): Packlist "PACK_BTS_FLOOR_BUTTON_MATS" does not exist!
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/command_target.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/factory_metal_floor001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/factory_metal_floor001a.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/factory_metal_floor001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/factory_metal_floor001b.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/factory_metal_floor001c.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/factory_metal_floor001c.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/fizz_side.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/player_clip_electric.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/clean_csfi_center.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/clean_csfi_left.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/clean_csfi_right.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/closed_solid_field.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz/thedarkbomber/invis_paintable.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz_sides/side_color_06141A.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/fizz_sides/side_color_FFFFFF.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/metalwall_bts_001b.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/metalwall_bts_001b_normal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/effect.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_danger.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_ingame/cust_fizz/fizzler_dirty_danger.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/squarebeams_bts.vmt"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_glass.vmt"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_glass.vtf"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_light.vmt"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_light.vtf"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_light_cheap.vmt"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_shell.vmt"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_shell.vtf"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_shell_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/models/BEE2/props_clean/tuleby/reflecto_bomb_shell_speed.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/props_clean/tuleby/reflecto_bomb_cube.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/cust_fizz.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/pgun_pedestal.mdl"
[INFO] vbsp.make_packlist(): "models/props_bts/vactube_glass_bothsides/vactube_128_straight_glass.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/tuleby_cube_bomb.nut"
[INFO] vbsp.make_packlist(): "scripts/vscripts/bee2/portal_man.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/charge_pgun.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by LautaroL20** [comment]
#PrayForQuentin9909

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
