### ISSUE TITLE
Can't run BEE2.exe because "VCRUNTIME140.dll isn't on my computer"

### ISSUE THREAD

**Issue by Firepal** [BEEmod/BEE2.4#907]
I downloaded the latest version (2.4 29 prerelease), i merged the packages, and ran BEE2.exe.
Now, i don't have the message in english (since i'm not), but it's basically telling me i'm missing this DLL file.
I installed the redistribuable version of Visual Studio 2015 (?), and restarted my computer.
Still not functioning. Any help ?

Edit: I use 64-bit Windows 7, for the record.

**Comment by TheIceCreamMan10000000** [comment]
I have the same exact problem. but I have a 64x bit Windows 10 and didn't install Visual Studio.

**Comment by Firepal** [comment]
I don't know lol

**Comment by MeepJJ** [comment]
Installing this will fix it: [https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads]

**Comment by LautaroL20** [comment]
No responce from the author since a long time ago so i assume he solved this issue. I hate so much when authors don´t responce through the decades....
