### ISSUE TITLE
Add a stylevar to remove disintegration sounds while fizzling any object.

### ISSUE THREAD

**Issue by Nikita74Russian** [BEEmod/BEE2.4#911]
This can take a huge effect in P1 style. Because in Portal 1 cubes and almost anything didn't have a fizzle sound.

**Comment by ZombiePwner1** [comment]
@Nikita74Russian this is useless as it has no effect on the puzzle. + This is actually part of the source code which we can't change.

**Comment by LautaroL20** [comment]
@ZombiePwner1 - I do not even understand why you still bother at giving this kid explanations for what it's an absurd and meaningless suggestion...
