### ISSUE TITLE
Two new thinks that was really Cool

### ISSUE THREAD

**Issue by dunkler-schatten** [BEEmod/BEE2.4#918]
It would be awesome if you could use in a map, as an example, clean and overgown style at the same time. Eg for timetravel maps?

Very cool would be the possibility of an element that loads the next defined map when the player touched this.

Oh and i miss the BeeMod for MAC :'-(

**Comment by Luke18033** [comment]
Did you even read the contributing guidelines? Actually, you've posted here before, so maybe GitHub didn't show you the link. Regardless, you should read [them](https://github.com/BEEmod/BEE2.4/blob/master/.github/contributing.md) before posting any more issues, as this issue violates several of the rules.

As for your actual suggestions:

1. BEE2 isn't a Hammer replacement. Use that if you want multistyle.
2. BEE2 also isn't for stories, and I don't think this would be possible in a workshop map anyway.

BEE2.4 is still Mac-compatible, there just aren't release versions anymore. You'd need to install Python and build it from source manually.
