### ISSUE TITLE
failure to build puzzle

### ISSUE THREAD

**Issue by ConnorT05** [BEEmod/BEE2.4#919]
VRAD failed.

[INFO] vrad.main(): BEE2 VRAD hook started!
[INFO] vrad.main(): Map path is C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp
[INFO] vrad.load_config(): Loading Settings...
[INFO] vrad.load_config(): Config Loaded!
[INFO] vrad.main(): Final status: is_peti=True, edit_args=True
[INFO] vrad.main(): Reading BSP
[INFO] vrad.main(): Done!
[INFO] vrad.gen_sound_manifest(): Written new soundscripts_manifest..
[INFO] vrad.gen_part_manifest(): Written new particles_manifest..
[INFO] vrad.pack_content(): Files to pack:
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_grey.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_grey.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_water.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_water.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_white.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_ingame/p1_gel_drop/gel_drop_white.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/door_01.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/door_01.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/walllight_sheet.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/models/props_p1/walllight_sheet.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/light_recessedcool_glow.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_lrg.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_lrg.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_lrg_height-ssbump.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_med.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_med.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/metalwall048b_med_height-ssbump.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/modular_wall_light.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/detail_concrete_03.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/metaldoor028a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/metaldoor028a.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observation_tilefloor001a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observation_tilefloor001a.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001a.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001a.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001b.vmt"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001b.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/obs/observationwall_001b_height-ssbump.vtf"
[INFO] vrad.pack_content():  # "materials/bee2/p1/overlay_light_gradient.vtf"
[INFO] vrad.pack_content():  # "materials/paintblob.vmt"
[INFO] vrad.pack_content():  # "materials/paintblobs/blob_surface_grey.vtf"
[INFO] vrad.pack_content():  # "materials/paintblobs/blob_surface_purple.vtf"
[INFO] vrad.pack_content():  # "materials/paintblobs/blob_surface_stick.vmt"
[INFO] vrad.pack_content():  # "models/bee2/props_ingame/p1_gel_dropper.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/door_frame_thick.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/door_left.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/door_right.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/obs_light.mdl"
[INFO] vrad.pack_content():  # "models/bee2/props_p1/security_camera.mdl"
[INFO] vrad.pack_content():  # "particles/paint_bomb_fx_reflect.pcf"
[INFO] vrad.pack_content():  # "particles/paint_splats_fx_reflect.pcf"
[INFO] vrad.pack_content():  # "scripts/bee2_snd/portal_sounds.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/change_models.nut"
[INFO] vrad.pack_content():  # "sound/bee2/music/pro/beeps.mp3"
[INFO] vrad.pack_content():  # "sound/bee2/p1/doorstop1.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/garage_stop1.wav"
[INFO] vrad.pack_content():  # "sound/bee2/p1/wall_move5.wav"
[INFO] vrad.pack_content(): Potential additional files:
[INFO] vrad.pack_content(): Injected files:
[INFO] vrad.pack_content():  # "scripts/game_sounds_manifest.txt"
[INFO] vrad.pack_content():  # "particles/particles_manifest.txt"
[INFO] vrad.pack_content():  # "scripts/BEE2_generated_music.txt"
[INFO] vrad.pack_content():  # "scripts/vscripts/bee2/auto_run.nut"
[INFO] vrad.pack_content(): Packing Files!
[INFO] vrad.pack_content(): Injecting "scripts/game_sounds_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "particles/particles_manifest.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/BEE2_generated_music.txt" into packfile.
[INFO] vrad.pack_content(): Injecting "scripts/vscripts/bee2/auto_run.nut" into packfile.
[INFO] vrad.pack_content(): Packing complete!
[INFO] vrad.mod_screenshots(): Using automatic screenshot!
[INFO] vrad.mod_screenshots(): No Auto Screenshot found!
[INFO] vrad.mod_screenshots(): Cleaning up screenshots...
[INFO] vrad.mod_screenshots(): Done!
[INFO] vrad.mod_screenshots(): Using PeTI screenshot!
[INFO] vrad.mod_screenshots(): Making "..\portal2\puzzles\76561198240331128\untitled.jpg" replaceable...
[INFO] vrad.main(): Forcing Cheap Lighting!
[INFO] vrad.run_vrad(): Calling original VRAD...
[INFO] vrad.run_vrad(): "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vrad_original.exe" -bounce 2 -noextra -hdr -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2" "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\sdk_content\maps\preview.bsp"
[WARNING] vrad.run_vrad(): VRAD failed! (1)

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
