### ISSUE TITLE
Skybox Improvements

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2.4#92]
- [ ] Generate realistic supports
  - Add a SupportChance value, specifying how common supports will be
  - When placing wall edges, check supportChance and add the origin to a set
  - Corners and pillar sections always have supports
  - Triple pieces have the support on the adjacient tile.
  - Generate 1 support per block, facing random direction
- [ ] Background elements
  - Partition the map area into a 512 grid. Extend down an additional 6 spaces, sideways and up 2 (based on how large the map is.)
  - Invalidate each grid section which is occupied by a brush.
  - Also invalidate any pos occupied by an instance - ambient lights are placed every 512 units, so interior blocks aren't occupied
  - Now start placing instances (in skybox) to fill grid sections - BackgroundChance /100 if a space is filled
  - Instances might also occupy a region below - loop from top to bottom when placing, so they don't overlap - need to define for each file their height.
- [ ] Wiring
  - Choose a random pit side (WireChance /100 per each side )
  - Move in the direction of the normal (up to 2048 or so units) looking for the opposite pit brush
  - Choose z-heights for both brushes (some distance below )
  - For both brushes, check if they have a support
    - If so rope position is the center, ±32
  - Otherwise look back 1 512 grid space, to find grid instance
    - If found rope position is ±200 units from center of support, otherwise abort adding rope at these pos.
  - Place move_rope and keyframe_rope, add keyvalues to position. Width range configurable. Slack = dist between + random slack value (configurable max/min)

**Comment by ellingtonisland** [comment]
so, the bottomless pits will be procedurally generated. this is VERY good, this should make it so no two bottomless pits are the same!

**Comment by ellingtonisland** [comment]
how will this work to generate vacuum tubes in pits procedurally?

**Comment by TeamSpen210** [comment]
I'm splitting the map up into a 512-sized grid (4x4 editor blocks), and filling in space around chambers with randomised instances. That'll add the decoration. I don't think I'll generate vactubes that span the bottoms of bottomless pits, players might think they can jump down onto them.

**Comment by jccreszMinecraft** [comment]
Maybe these skyboxes can also just be items with a timer thing to select
the different instance. Also a secondary thought is that they should
generate random frames on the edges of the pit blocks before the actual pit.

On Tue, Jul 28, 2015 at 3:59 AM, TeamSpen210 <notifications@github.com>
wrote:

> I'm splitting the map up into a 512-sized grid (4x4 editor blocks), and
> filling in space around chambers with randomised instances. That'll add the
> decoration. I don't think I'll generate vactubes that span the bottoms of
> bottomless pits, players might think they can jump down onto them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BenVlodgi/BEE2.4/issues/92#issuecomment-125490831>.
>



-- 
[image: Ice Network 2014]

**Comment by harritron2k2** [comment]
With instances around the map you should be able to create a skybox wall item like in your addons to show thins like ex. Wheatley BTS or Test Shaft.

**Comment by Luke18033** [comment]
3D skyboxes are gone, but this process seems like it could still apply well to chamber exteriors.

**Comment by Luke18033** [comment]
See BEEmod/BEE2-items#3891
