### ISSUE TITLE
Feature Request: Sound/Animation triggerable effects

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2.4#921]
Being able to connect things like various sounds, or the "screen shake" that usually accompanies explosions (as seen in Wheatley maps, notably the one with the laser field), would go a long way towards designing an "atmosphere" for a chamber.

For example, making a collapsing floor (which thus necessitates finding an alternate puzzle solution) also be accompanied by such effects would make it feel more convincing. Or maybe the "giant powerup" sound used by gel pumps in the Old Aperture campaign could be used to indicate a test element's activation (or the "powerdown" sound seen in "Hey, who turned off the lights" before the first escape used to indicate *de*activation).

I am obviously not familiar with how this sort of thing works, but I would be surprised if simple sound or animation events were more complex than functional blocks already implemented.

**Comment by TeamSpen210** [comment]
I would recommend you go into using Hammer. It is far far more powerful than the ingame editor, and you can do just about anything. The scope of the is really moreso making puzzles, not maps with storylines. This isn't intended to be a replacement for the ingame editor, if I was to do that it'd pretty much end up as complicated as that.

**Comment by ReikaKalseki** [comment]
Hammer is nightmarishly difficult and vastly overkill for something this simple. If I wanted to recreate PS:Mel, yes, Hammer would be the tool of choice. But using it for something like a sound trigger is akin to building a custom OS from scratch to customize the notification system.

**Comment by HugoBDesigner** [comment]
Wrong. Puzzlemaker is for making puzzles. Hammer is for custom visuals/audios. Beemod is not a replacement for Hammer.

**Comment by peefTube** [comment]
> Hammer is nightmarishly difficult

_Sigh..._
There's a thing called mapping tutorials.
Read 'em. [https://developer.valvesoftware.com/wiki/Level_Design_Introduction_(Portal_2)/Getting_Started](url)
