### ISSUE TITLE
Just updated to pr29, and cannot compile due to "VALVE STANDARD CUBE IS MISSING"

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2.4#923]
I followed the instructions posted by @LautaroL20 in #814, #603, #839, and several others - three times, in fact - to no avail.

The map compiled with the last BEEMod version I was using (whatever was newest around Apr-May of last year), but now it fails.

The full error can be seen here:
https://pastebin.com/0TMtpwia

My BeeMod installation *seems* fine, though I do have Portal 2 and BeeMod on separate drives (P: and E: respectively, P: being an internal secondary SSD and E: a USB platter drive).

Here is my current settings and palette (note that the level contains reflection gel and cutout tiles, which were since removed from the palette to make space for the turret dropper):
![https://i.imgur.com/qdcLXkp.png](https://i.imgur.com/qdcLXkp.png)

**Comment by TeamSpen210** [comment]
Have you updated the packages? That error usually comes when you have an earlier version, I changed some stuff in the app which requires matching changes in the packages.

**Comment by ReikaKalseki** [comment]
Yes, I am using the pr29 packages.

**Comment by ReikaKalseki** [comment]
I just reinstalled the packages, and many items have changed icons, and it now works. This is no different from what I had done earlier when updating the main program (install the program, then overwrite packages with the one from the packages distr), but whatever.

**Comment by ReikaKalseki** [comment]
Also, this chamber has developed a secondary issue related to light projection from the room at right; it causes a square-shaped staticy flickering, which appears the moment the room illuminates and persists across Portal 2 relaunches.

![https://i.imgur.com/JuiwFP2.jpg](https://i.imgur.com/JuiwFP2.jpg)

It only affects that one area.

https://i.imgur.com/i7Kq6PS.mp4

**Comment by ZombiePwner1** [comment]
@ReikaKalseki The static bug is actually a game bug which alot of people have reported but valve being too lazy to fix it. Only way to fix it so far is by switching graphics cards since it seems to be a nivida issue.

**Comment by ReikaKalseki** [comment]
This is the first time I have ever encountered it; is it a known trigger? Does it persist for published maps (ie will people who try the map also see it)?

**Comment by TeamSpen210** [comment]
It's a bug in the shaders. Basically, projected textures (the real-time shadow lights emitted by the large obs room) plus a specific blend effect on the material plus a Nivida card = this.

**Comment by ReikaKalseki** [comment]
That description makes it sound like it should always happen, yet I have never seen it before, including with this level (at least prior to regaining compile ability today).

**Comment by TeamSpen210** [comment]
Actually, maybe it's because you're using more than one double-wide observation room. The engine only supports one projected texture at a time, so by having more than one it'll end up leaving one active and turning the others off (probably depending on very strange things like the order in the map file or other very random elements). That would explain it appearing elsewhere.

**Comment by ReikaKalseki** [comment]
It worked until I updated to pr29. Indeed, having 2-4 size-2 rooms *still* works in other chambers.

It is not a *serious* problem, but it *is* annoying.
