### ISSUE TITLE
Feature Request: "Open concept" level

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2.4#924]
That is, a level without a "room" enclosing it, like seen in this level from the base game.

https://youtu.be/qgxKNcPLHJE?t=167

**Comment by HugoBDesigner** [comment]
Not possible due to puzzlemaker's limitations.

**Comment by ReikaKalseki** [comment]
OK, can you elaborate as to why?

**Comment by HugoBDesigner** [comment]
Puzzlemaker maps require walls around them to work. These maps also can be made larger than the sphere. There's no way to "remove the external walls" to make it open, nor check the map size to make it fit in the sphere. For such maps, [Hammer mapping](https://developer.valvesoftware.com/wiki/Level_Design_Introduction_(Portal_2)/Getting_Started) is your best option.
