### ISSUE TITLE
Suggestion: Add ability for custom images in elevators.

### ISSUE THREAD

**Issue by RealDeadlyOne** [BEEmod/BEE2.4#932]
Imagine if you could add custom images to elevators. Here is an image on the concept.
![lwmface](https://user-images.githubusercontent.com/40037006/41201536-c05a4f24-6cb1-11e8-9440-1a159e76ec01.jpg)

**Comment by Luke18033** [comment]
Apparently videos can't be packed into maps, which would make this impossible.
