### ISSUE TITLE
BTS Corridor World-Portal Glitch

### ISSUE THREAD

**Issue by FailureSnowy** [BEEmod/BEE2.4#941]
So, I decided to try to fix the issue with the FACTORY entrance in the BTS theme, where you can see through the final wall into the test chamber, and where underneath the glass it shows that void oddity. I attempted, and I don't know if it worked, because I switched entrances. 
THEN I decided to edit a bit in the entrance I DO have selected, and now it shows a blank blue-ish wall, and then when I walk through it, it shows the next segment. (Selected Entrance: DANGER. Edited: Office and Entrance_corridor_three)

Can you please help me fix it or update the Mod soon to fix it, please? Much thanks in the future.
Cheers!
~Snowy

**Comment by ZombiePwner1** [comment]
@FailureSnowy No clue for this and it's advisable not to edit the corridors at your own risk unless you know what your doing since messing up the corridors can cause issues.

**Comment by FailureSnowy** [comment]
I have been aware of this when I first began to do so. But I'm still confused on how just opening these corridors and adding maybe one or two prop_statics can affect the world-portals. I do hope sometime that an update will come out to support the creation of items/entrance and exit corridors.

**Comment by LautaroL20** [comment]
BTS Corridors are very leaky. However, you are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.
