### ISSUE TITLE
Nodraw Issue

### ISSUE THREAD

**Issue by Determinated888** [BEEmod/BEE2.4#945]
![error](https://user-images.githubusercontent.com/40443625/42243198-bded060e-7ecd-11e8-8ea0-d9e7197f6a9a.PNG)
When I was using BeeMod yesterday, I was having issues with nodraw with goo pits. I was using the Bee Clean style and the Clean skybox. There was also an error with the entrance door to the chamber disappearing for a short time and then reappearing. I verified my game files for Portal 2, and I also uninstalled Bee and then reinstalled it. When I tried to start Bee after that I got the error shown in the picture. What is going on? I would love any help I could get. Thank you in advance!

**Comment by HugoBDesigner** [comment]
One of the files is being used by another process. Make sure you don't have Portal 2, Beemod, vbps or vrad running in the background. Terminate those processes if they're still lingering and try again.

**Comment by Determinated888** [comment]
Will that fix the nodraw issue?

**Comment by HugoBDesigner** [comment]
No, the nodraw issue is that you've got a leak. There are a number of possible causes (that's deserving a Wiki page of its own, might get to it later), but that should go in the Items repo.

**Comment by Determinated888** [comment]
Ok I will move it there. Thanks.
