### ISSUE TITLE
Being able to use the cube colouriser on cube/sphere buttons

### ISSUE THREAD

**Issue by HumanPerson2** [BEEmod/BEE2.4#947]
If you put a cube colouriser under a button designed for cubes/spheres and let's say you set the colour in the colouriser to number 15, then the button will accept ONLY the cube/sphere with the same colour, this could create rather interesting puzzles in my opinion.

**Comment by TeamSpen210** [comment]
I'm specifically not going to do this. Colourisers will NOT affect gameplay. It's entirely possible you could create two colours which are almost identical, but don't work with each other. And really if you actually have a use for this, chances are your puzzle is far to overcomplicated to be enjoyable.
