### ISSUE TITLE
No music in BTS chambers

### ISSUE THREAD

**Issue by HumanPerson2** [BEEmod/BEE2.4#948]
Even if you do export the BTS style with set music, the music doesn't play in the preview nor in the finished chamber on the workshop.

**Comment by ZombiePwner1** [comment]
@HumanPerson2 I wouldn't suggest using BTS style atm since it's currently bugged.

**Comment by HumanPerson2** [comment]
@ZombiePwner1 Well, that's bad... Will it ever be fixed though?

**Comment by ZombiePwner1** [comment]
@HumanPerson2 Obviously it will be fixed in a future release.

**Comment by Konclan** [comment]
This is still an error

**Comment by Konclan** [comment]
https://github.com/BEEmod/BEE2.4/blob/master/FAQ.md#why-is-bts-being-removed
