### ISSUE TITLE
"Floor Goo" overgrown exit option spawns blue gel but remains portalable

### ISSUE THREAD

**Issue by ReikaKalseki** [BEEmod/BEE2.4#951]
As per the title; it spawns blue gel if the map contains it, allowing for a left-right bounce across - which I very much like.

But it also remains the portalable variant (which is required without the blue goo), but this makes the goo completely unnecessary to use to reach the exit.

**Comment by TeamSpen210** [comment]
To make it non-portalable, I'd really need to make a second seperate copy of the entire room. I don't think it matters too much, it's not supposed to be an incredibly challenging puzzle, just a problem you have to work around. Multiple methods are fine and reasonable.
