### ISSUE TITLE
Allow setting volume for music tracks (and lower volume of "Machiavellian Bach")

### ISSUE THREAD

**Issue by HumanPerson2** [BEEmod/BEE2.4#953]
Like, it might seem kinda insignificant, but it still is kind of annoying in some cases where you specifically WANT to hear them.

**Comment by HumanPerson2** [comment]
It cr

**Comment by Konclan** [comment]
There definitely should be a way to manage music volume

**Comment by unfunny1** [comment]
i hate machiavellian bach

**Comment by vrad-exe** [comment]
Is setting the volume for music tracks not supported? That definitely needs to be a thing you can set in the music config.
