### ISSUE TITLE
Portal 2 editor giving errors after exporting BEE2.4 items!

### ISSUE THREAD

**Issue by iTom33ro** [BEEmod/BEE2.4#955]
Hello, i have a 2 problems with BEE2.4;

1. After export items to Portal 2, I'm getting errors after rebuilding map.
2. If I export one more again, the exporting as cancelled and BEE2.exe are be remove.

PLEASE HELP ME!!!

**Comment by LautaroL20** [comment]
If you have multiple bug reports or feature requests which are not related to each other, **please create separate issues instead of combining them.** This allows us to individually label the issues, and close them once they are fixed/implemented. Combined issues will immediately be closed, no matter how elaborate the post may be.

**Comment by iTom33ro** [comment]
Yes, but how to fixed problem 1 ?

**Comment by TeamSpen210** [comment]
Open up the developer console, there'll be error messages in there. Copy them here.

**Comment by iTom33ro** [comment]
NET_GetBindAddresses found 192.168.0.5: 'Realtek 8821AE Wireless LAN 802.11ac PCI-E NIC'
Opened Steam Socket NS_SERVER ( socket 2408 )
Opened Steam Socket NS_CLIENT ( socket 2412 )
Network: IP 192.168.0.5, mode MP, dedicated No, ports 27015 SV / 27005 CL
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: F:\STEAM\steamapps\common\Portal 2\portal2.exe\platform\config
ILocalize::AddFile() failed to load file "Resource/platform_romanian.txt".
ILocalize::AddFile() failed to load file "Resource/vgui_romanian.txt".
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Failed to init 'maps/soundcache/_master_romanian.cache'
Unknown command "cl_thirdperson"
Didn't find Active Steam Controller to Load Menu Controls
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.5, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 2408 )
Opened Steam Socket NS_CLIENT ( socket 2416 )
Network: IP 192.168.0.5, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
   VAC secure mode is activated.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee2_fizz_error.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_catcher_timed.3ds
[PORTAL2 PUZZLEMAKER]     *!* 3ds file doesn't exist models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  Failed to load selection mesh: models/puzzlemaker/selection_bee_pellet_launcher_inf.3ds
[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[Sound] S_StartSound(): Failed to load sound 'weapons\physcannon\energy_sing_flyby1.wav'. File is missing from disk/repository.
[Sound] S_StartSound(): Failed to load sound 'weapons\physcannon\energy_bounce2.wav'. File is missing from disk/repository.
[Sound] S_StartSound(): Failed to load sound 'weapons\physcannon\energy_bounce1.wav'. File is missing from disk/repository.
[Sound] S_StartSound(): Failed to load sound 'weapons\physcannon\energy_sing_explosion2.wav'. File is missing from disk/repository.
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF F:/STEAM/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (11,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 285 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 23545 (ms)

VVIS failed.

Valve Software - vvis.exe (Mar  1 2018)
4 threads
reading f:\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp
Error opening f:\steam\steamapps\common\portal 2\sdk_content\maps\preview.bsp


iTom33.ro unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: F:/STEAM/steamapps/common/Portal 2/portal2/puzzles\76561198840330760\autosave.p2c

**Comment by iTom33ro** [comment]
What is the developer 2 and how to turn on?

**Comment by Hakaan777** [comment]
i have exactly the same problem, and its not "2 separates problems" butin fact ONE problem with two symptom

**Comment by portalmechanic** [comment]
but what is developer 2? can it help us solve the problem we are facing?

**Comment by HugoBDesigner** [comment]
https://github.com/BEEmod/BEE2-items/wiki/How-to-report-compiler-errors

**Comment by iTom33ro** [comment]
I have the good news, the BEE2 now work normally!
