### ISSUE TITLE
BEE 2.4 hammer wont run map

### ISSUE THREAD

**Issue by Timmy4242** [BEEmod/BEE2.4#957]
So i have gotten BEE 2.4 and while making a simple test map, i could not run that peti map, however thats not my biggest problem. The problem im facing is when i go into hammer, and any hammer map including ones that have only one room and player start, i click run and it just wont work. No error messages or anything is showing up its just says its running the map and does not do any of the loading process then says finished. Hammer does not seem to compile the map and portal 2 does not open. This never happend before i got the mod. If anyone knows what to do please respond asap! Here is a screenshot of what it looks like, i get the same message for all the maps 
![fbfb1d3a-2d66-45ee-952b-bfbd864ca318](https://user-images.githubusercontent.com/30575039/42714545-97bf70d8-86c1-11e8-89b8-2cf3e2992f6e.png)

**Comment by HugoBDesigner** [comment]
Beemod was not made to be compatible with Hammer. There are a lot of weird tricks the custom compiler does to get things working, and it was designed specifically for puzzlemaker, so exporting to Hammer is not only undesirable, but also unsupported.

**Comment by Timmy4242** [comment]
I tried that and it still isnt working, none of this happend until i got bee 2.4 but quite a long time ago i think i got either bee 2 or the first bee and it worked fine but now hammer isnt working, im willing to get rid of the bee 2.4 if i need to, if i do how can i do that?

**Comment by Timmy4242** [comment]
I have uninstalled and reinstalled the game and hammer keeping good files, most things are working fine now but the only thing is hammer is still failing to compile. If anyone is able to figure this out i would love to know how to fix it. Thank you for your help

**Comment by Timmy4242** [comment]
Alright so i tried doing that, and nothing seems to have changed, im thinking maybe bee1 and 2.4 aren’t compatible and i must still have some bee 2.4 left somewhere. if it is possible figure out where they might be that would be great. If i have to delete all my files then is there a way to get the bee1 back or is there only new versions?

**Comment by Timmy4242** [comment]
Alright sorry to bother all of you guys, i solved it. Apparently something in my origional portal 2 bin folder broke hammer so i just took the bin from my reinstalled portal 2 files and replaced it and hammer is working fine now, it is compiling like normal, and all the textures from bee 1 are working and everythings back to normal. Too bad i cant get bee 2.4 for now. I should back up my portal files before downloading stuff is the lesson i learned lol.. thanks for your help and I apologize for wasting your time. Although i have no idea how to close this or mark it as solved or something
