### ISSUE TITLE
After crash i cant reextract Bee.exe "access denied"

### ISSUE THREAD

**Issue by Hakaan777** [BEEmod/BEE2.4#961]
Hello, when i use some items of bee package, the P2 in game creating tool crash on "reconstruction" step, so i have to repair P2 by redowloading files, 
and when i launch BEE again, it crash and BEE.exe disappear from /bin, 
so i have to re-extract that from the .zip, but when i try, i have a popup windows that says "imppossible to create BEE.exe, access denied"

but i'm administrator account no matter with that, its really boring i spend lot of time to repair the game and BEE mod each time

**Comment by TeamSpen210** [comment]
Check your antivirus, it might be doing something.

**Comment by iTom33ro** [comment]
Do i need to have antivirus disabled?

**Comment by TeamSpen210** [comment]
No! It's just that it might erroneously detect BEE2 stuff - mainly with heuristics that fire on programs that not many people have installed.

**Comment by Hakaan777** [comment]
just put BEE and portal directory in exceptions
