### ISSUE TITLE
Add the Portal 1 voicelines, and in order to make them match with other languages for people who do not speak english, implement in a bee´s Packages their respective dubbing voices from the Valve´s translations.

### ISSUE THREAD

**Issue by epicduck64** [BEEmod/BEE2.4#962]
Add the Portal 1 voicelines, and in order to make them match with other languages for people who do not speak english, implement in a bee´s Packages their respective dubbing voices from the official Valve´s translations.

**Comment by King0191** [comment]
In the past, Currently, and for an unspecified amount of time in the future. P1 GLaDOS voice lines are not added. They cant add voicelines so they have to mix match voicelines that line up to P1. This is going to be difficult and they have other things they are working on right now. Don't expect P1 GLaDOS voicelines next update

**Comment by epicduck64** [comment]
Thanks for the update. I am just hoping that they can put in lines from the actual P1 game instead of all that complicated stuff. I remember with the older bee mod for the level editor had the original P1 Voices enabled, so I could select voices. But now its gone so. But if they added normal P1 voices, then I'd be happy.

**Comment by LautaroL20** [comment]
Nice idea!

**Comment by epicduck64** [comment]
Lol, you changed the name like 5 times

**Comment by King0191** [comment]
Isn't one of the biggest issues the Subtitles?

**Comment by epicduck64** [comment]
I don't know if I wanted implementing the different languages, I only asked that voicelines from the original P1 game we're added.

**Comment by LautaroL20** [comment]
Issue´s title will be changed as many times as needed to make it very precise to what we want to suggest. Also, so you want to hear the voices in "english" because its your maternal language but you don´t allow others which speak Spanish, Russian, German etc...

Forcing the rest of people hearing a language who don´t like/understand while we have avaliable official voices translations that Valve did for P1, that seems pretty fair...

**Comment by King0191** [comment]
My issue is that TeamSpen I think mentioned that they cant be added due to Subtitle reasons (maybe im wrong idk) But thats really my only concern. Personally i'd love the voice lines. Its just the subtitles issue

**Comment by LautaroL20** [comment]
Subtitles can be perfectly disable thru the game, and a warning on the P1 Style's description could be added saying "It is recomended to disable subtitles to enjoy voicelines".

As long as we have available all voice´s translations that valve did for P1, we don´t need useless subtitles.

**Comment by Luke18033** [comment]
The way translated voice lines/subtitles work is by downloading an alternate version of the files based on the user's chosen language. That can't be done for packed content, which is why this isn't possible.

**Comment by epicduck64** [comment]
Okay, Thanks for the help, I don't mind the language thing being added, as long as I get the voicelines I'd like. Thanks! 👍
