### ISSUE TITLE
P2 Crashes after loading when building puzzle

### ISSUE THREAD

**Issue by devinkid1** [BEEmod/BEE2.4#970]
this just started happening, **portal 2 crashes** right after loading the puzzle, its really annoying so if there is any way to fix this, that would be great.

i'm on 2.4.0pr24, i don't know if its outdated or not.

**Comment by devinkid1** [comment]
Nevermind, it was just the cameras that were crashing the game. but still if you could fix the camera issue that would be great.

**Comment by LautaroL20** [comment]
Take care that the PRL24 is outdated as hell. We are for the version 29 of beemod and soon we will release the prl 30. Make sure to update your version, otherwise bugs will occur.
