### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by TheSpacedOutEgg** [BEEmod/BEE2.4#971]
I recently uninstalled "Thinking With Time Machine", because BEE2.4 was refusing to allow me to pick up items. The next day when I opened BEE2.4 so I could use it on Portal 2, It gave me an error. I can't exactly remember the error, but it kept me from opening the application. I decided to delete the file "BEE2.4_pr29_win", but kept the "packages" folder. When I reinstalled it and used it again, I got an error saying in PeTI "Error building puzzle". 

On some occasions, when in the 1960's styles, it prompts:  

Error Vertex File for 'props_map_editor/under_door_entry.mdl '  checksum 54625248 should be -1296225686

Most other times, it says: 

VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr29 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'music_location_sp': '-2824 2040 -768', 'voice_pack': 'BEE2_CAVE_60s'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'common': 'instances/bee2/50s/items/rex/pellet_dest/common.vmf', 'head': 'instances/bee2/50s/items/rex/pellet_dest/head.vmf', 'piston_bottom_0': 'instances/bee2/50s/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/50s/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/50s/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/50s/items/rex/pellet_dest/pist_3.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf', 'piston_static_0': 'instances/bee2/50s/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/50s/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/50s/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/50s/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/50s/items/rex/pellet_dest/static_4.vmf'})
[INFO] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[WARNING] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[INFO] fizzler.read_configs(): Loaded 14 fizzlers.
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting Coop Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: COOP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (696 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "BEFORE ENTRY": 1/1 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_Coop"
 | 	{
 | 	"ID" "CAVE_OWN"
 | 	"Quote_Name" "@cave_pre_enter"
 | 	"Bullseye" "cave_a3_03_lift_shaft"
 | 	"setstylevar" "retro_voice_pre_line"
 | 	"EndCommand"
 | 		{
 | 		"Input" "FireUser1"
 | 		"Target" "@cave_enter"
 | 		"Delay" "0.1"
 | 		"Only_Once" "1"
 | 		}
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_intro03.vcd"
 | 		"2" "npc/cavejohnson/fifties_intro04.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "ENTRY": 3/4 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_COOP"
 | 	{
 | 	"ID" "ASBESTOS_SPHERE_COOP"
 | 	"Bullseye" "cave_bomb_flings_entrance"
 | 	"Bullseye" "cave_portal_intro_office"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/misc_tests08.vcd"
 | 		"2" "npc/cavejohnson/eighties_intro04.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "EXIT": 4/7 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "HAPPY_FACE"
 | 	"Bullseye" "cave_bomb_flings_entrance"
 | 	"Choreo" "npc/cavejohnson/misc_tests10.vcd"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/1 quotes..
[INFO] voiceLine.add_voice(): Using microphones...
[INFO] voiceLine.add_voice(): 1 Mid quotes
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 |_

[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['goo', 'laserfield', 'laser', 'deadly', 'glass', 'grating', 'gel', 'geldropper', 'bouncegel', 'bluegel', 'water', 'watergel', 'cleargel', 'pedestalbutton', 'faith', 'catapult', 'faithplate', 'crusher', 'fire', 'flamethrower', 'pellet', 'pelletlauncher', 'laseremitter', 'bridge', 'hardlight', 'observationgrate', 'obsworldportal', 'pistonplatform', 'piston', 'panel', 'funnel', 'excursionfunnel', 'turret', 'spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=101374, misses=353, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'retro_voice_pre_line': True}
[INFO] cond.core.check_all(): Global instances: set()
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding global ents...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_brush(): Goo heights: 736.0 <- Counter({736.0: 27, 96.0: 4})
[INFO] vbsp.clump_walls(): Clumping: 740 clumps (+ 2 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[WARNING] vbsp.make_packlist(): Packlist "PACK_RETRO_PIST_PLAT" does not exist!
[INFO] vbsp.make_packlist(): "#scripts/bee2_snd/pellet_sounds.txt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/arrow_blue.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/arrow_blue.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/cross.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/cross.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/dot.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/dot.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/moon.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/moon.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/slash.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/slash.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/square.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/50s/signage_shape/square.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/blob_surface_bounce.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/testchamber_mark.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/under_metal_wall.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/under_plywood.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/factory_metal_floor001a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/light_bridge_coils.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/light_bridge_coils.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/light_bridge_coils_n.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/light_bridge_lamp.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/light_bridge_lamp.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_underground/metalwall_bts_005a.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/squarebeams_rusty_01.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/underground_metal_corrugated001.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/underground_plywood_01a_bottom.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/underground_woodwall003c.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/world/underground_hotsurface.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/comball/comball.vtf"
[INFO] vbsp.make_packlist(): "materials/effects/eball_finite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/effects/eball_infinite_life.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow1.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_glow2.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_sphere.vtf"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vmt"
[INFO] vbsp.make_packlist(): "materials/models/effects/comball_tape.vtf"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/retro_track_128.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_underground/light_bridge.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_underground/ramp.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_underground/track_plat_horiz.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_underground/turret_skeleton.mdl"
[INFO] vbsp.make_packlist(): "models/effects/combineball.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/piston/common.nut"
[INFO] vbsp.make_packlist(): "sound/BEE2/p1/alyx_stunner2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_bounce2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate4.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_disintegrate5.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_explosion2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby1.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_flyby2.wav"
[INFO] vbsp.make_packlist(): "sound/weapons/physcannon/energy_sing_loop4.wav"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): 
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

If you could respond this to tell me what is supposedly happening, or if you know how to fix it, that would be very much appreciated!

**Comment by LautaroL20** [comment]
Try out the latest pre-release.
