### ISSUE TITLE
New BTS style

### ISSUE THREAD

**Issue by Symba1321** [BEEmod/BEE2.4#973]
I think it would be nice to have a BTS style but with the real textures !

![portal2bts](https://user-images.githubusercontent.com/42472438/44272601-9caba700-a23d-11e8-954f-ef1e0b5e5d5d.png)

**Comment by King0191** [comment]
The textures in the seen picture appear in the bottomless pits

**Comment by Symba1321** [comment]
I know but it's for the assets on all the walls

**Comment by King0191** [comment]
That texture would become bland very quickly. No one wants to stare at a wall of the exact same texture, even in P1 Style, the Unportalable surfaces are different from unit to unit.

**Comment by Symba1321** [comment]
This is the goal of the BTS style; they are not tests...

**Comment by King0191** [comment]
I know they aren't tests. However that has nothing to do with the fact that Aperture doesn't use the same exact type of wall multiple times in a row. (At least not since GLaDOS fixed up the facility.)

**Comment by Symba1321** [comment]
I know but the current textures do not really look like a BTS style (except the white parts), they look like textures used outside enrichment spheres

**Comment by geekkid1** [comment]
To some extent. It's supposed to be the style of BTS you see when you're disabling all of GLaDOS's (and later Wheatley's) defense systems. Like all concrete and stuff. None of the trussed walls you see in your first screenshot. All of the non-white wall elements are so seldom-used. They fit in when they're used as they are in the story gameplay.

That isn't to say I don't see where you're coming from. Maybe a new theme could be added, named "Between the walls" or something to indicate the differences between that and the traditional BTS tileset.

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
