### ISSUE TITLE
Portal 1 Style Exit Door doesn't load in?

### ISSUE THREAD

**Issue by epicduck64** [BEEmod/BEE2.4#976]
Whenever I made one of my levels with the Portal 1 Style, I noticed that the exit door didn't load in, and everyone who finished the level had to noclip to the exit. So either the trigger thats supposted to be there and load in the exit, doesn't work, or its just a problem with the game.

**Comment by Luke18033** [comment]
What do you mean it doesn't "load in"? Post a screenshot.

**Comment by epicduck64** [comment]
I can't post a screenshot as of right now, but its basically when you enter the exit door, around the corner is just the outside of the level.

**Comment by epicduck64** [comment]
If you want to check it out for yourself, maybe its the exit style, my user is epicduck64 on steam, and the level is called Portal Reborn Part 2.

**Comment by LautaroL20** [comment]
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.

**Comment by epicduck64** [comment]
Wow, okay.

**Comment by epicduck64** [comment]
Thanks then.
