### ISSUE TITLE
Shaders are a bit grainy and flashy...

### ISSUE THREAD

**Issue by epicduck64** [BEEmod/BEE2.4#977]
My friend was playing one of my levels, and he noticed a grainy, flashing light on the walls. It was literally black pixels, with flashing white around it. The shaders weren't really liking his game. I'm not sure if this was his game, not liking something about the lighting, or just the bee mod not handling the lighting correctly. I just wanted to report that it could of possibly been Bee 2.4 causing grainy shaders.

**Comment by Konclan** [comment]
This is a problem with Nvidia drivers and Projected Textures which are only emitted from large observation rooms. There is no fix for this and this is a valve bug.

**Comment by epicduck64** [comment]
Alright. I'll tell my friend about this.
