### ISSUE TITLE
Can you please add a setup wizard like with Bee 1? The instructions aren't clear, so can you add an option to have the setup automated?

### ISSUE THREAD

**Issue by SirAxolot** [BEEmod/BEE2.4#978]
Can you please add a setup wizard like with Bee 1?
I'm 12 years old, and the instructions aren't clear, so can you add an option to have the setup automated?

**Comment by LautaroL20** [comment]
Yes, it would be good.

**Comment by Luke18033** [comment]
Duplicate of #77.
