### ISSUE TITLE
When I try to download the packages for PR 29, I just get a "Failed - Forbidden" error. Help please :/

### ISSUE THREAD

**Issue by TheLoneController** [BEEmod/BEE2.4#980]

**Comment by LautaroL20** [comment]
That must be caused by your internet connection, or a momentary failure of the github servers. Keep trying downloading it.

**Comment by TheLoneController** [comment]
It still isn't working! The download is acting strange. It's only downloading 0.1MB when Speedtest says that it can download way more! And when it does make progress, it happens very rarely! The servers are fine, and the internet is fine! This is the only time it's happened!

**Comment by LautaroL20** [comment]
You could ask someone that downloaded the packages version 29, to upload it to another host file like Mediafire or something. Join the Bee´s Discord and ask someone to do it for you: https://discord.me/beemod

**Comment by TheLoneController** [comment]
Thanks I'll do that now.
