### ISSUE TITLE
Item Suggestion

### ISSUE THREAD

**Issue by EterSky** [BEEmod/BEE2.4#981]
Hi ! Yesterday i got an idea for an item: it's a portalable wall that pushes non-portalable walls with an imput, causing them to fall (like in Portal: FACTUM SOLUS or other portal mods). Also enabling Start Reversed causes a non-portalable wall that pushes portalable walls. It may be complex to understand but when you see it it's easier to understand :smile: .

**Comment by HugoBDesigner** [comment]
Is this like the introduction to Faith Plates in Portal 2? If not, can you provide a visual example (screenshot, gif or video)?

**Comment by SW50000** [comment]
![image](https://user-images.githubusercontent.com/20195894/44948381-2cc32200-ade2-11e8-8648-805183323753.png)
Not the best representation, but the panels fall off leaving portalable surfaces.

**Comment by HugoBDesigner** [comment]
So essentially the same as that in Portal 2. A "fancier" flip panel that leaves debris behind (can be problematic in a lot of puzzles).

**Comment by SW50000** [comment]
Yeah, I don't really see how this is helpful, it would be a real mess having to leave those behind. This mod does use it quite a bit but it's mostly just used for detailing. If the debris broke upon ground impact then it would just be ugly.

**Comment by King0191** [comment]
Not to mention that they're posting in the wrong place... I'm just sayin'

**Comment by HugoBDesigner** [comment]
I haven't even noticed that, thanks for pointing out
