### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by goodDOS** [BEEmod/BEE2.4#982]
BUG Report:
When the 'info.txt' in the parkages use UTF-8,it crashs,but some of them do not cause the crash(such as 'catwalk.zip')

![20180902115349](https://user-images.githubusercontent.com/16776856/44952019-e71c5d00-aea6-11e8-86e9-60e7ca24ae76.png)

**Comment by goodDOS** [comment]
![20180902115349](https://user-images.githubusercontent.com/16776856/44952019-e71c5d00-aea6-11e8-86e9-60e7ca24ae76.png)

**Comment by TeamSpen210** [comment]
This seems to me to be a syntax error in the file you changed - you'd get something different from an encoding issue. I process just about everything as UTF-8 anyway, excluding one Valve file which is actually encoded as UTF-16.
