### ISSUE TITLE
ERROR LOADING PREVIEW.BSP

### ISSUE THREAD

**Issue by benjaminpants** [BEEmod/BEE2.4#986]
I went with the default settings, I reinstalled portal 2 meaning all my old local test chambers are gone. Before it loaded one of those, now it loadings nothing at all.
(I reinstalled beemod AFTER portal 2)
Error Log
https://pastebin.com/UDe9kPM9

**Comment by benjaminpants** [comment]
Please, I STILL NEED HALP

**Comment by benjaminpants** [comment]
bump

**Comment by TeamSpen210** [comment]
You have a leak in your map somewhere, or your compilers are messed up. Try verifying your game cache and exporting again?

**Comment by benjaminpants** [comment]
And... Now Beemod.exe killed itself `<a href="http://s1079.photobucket.com/user/benjaminpantz/media/ENDD%20MEE_zpsjp4azkpz.png.html" target="_blank"><img src="http://i1079.photobucket.com/albums/w509/benjaminpantz/ENDD%20MEE_zpsjp4azkpz.png" border="0" alt=" photo ENDD MEE_zpsjp4azkpz.png"/></a>`

**Comment by benjaminpants** [comment]
> 
> 
> You have a leak in your map somewhere, or your compilers are messed up. Try verifying your game cache and exporting again?

Fixed the crashing issue but now it just loads a completely random test chamber and not the one I am working on.

**Comment by benjaminpants** [comment]
bump.

**Comment by benjaminpants** [comment]
No seriously, someone help. I am getting tired of using the non-modded editor. This guy is having the same issue (also why has this not been flagged as a bug yet?) https://github.com/BEEmod/BEE2.4/issues/988

**Comment by TeamSpen210** [comment]
I can't do much, there's nothing of use in the log. Your screenshot just shows a bug that happens when you open up two copies of the app.

**Comment by LautaroL20** [comment]
Try out the latest pre-release where this issue is most likely fixed:

User Interface: https://github.com/BEEmod/BEE2.4/releases/tag/2.4.34.1 
Items Packages: https://github.com/BEEmod/BEE2-items/releases/tag/v4.34.0
