### ISSUE TITLE
Overgrown observation room floor causes failure to compile

### ISSUE THREAD

**Issue by PorTalZ101** [BEEmod/BEE2.4#988]
8 threads
 | materialPath: D:\SteamLibrary\steamapps\common\Portal 2\portal2\materials
 | Loading D:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/over/items/observation_room_128_floor.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

Help would be apreciated.... thanks in advance
don't know if this helps but using Overgrown with Glados, botomless pit and PS: Mel Music

**Comment by PorTalZ101** [comment]
map ran previously...

**Comment by benjaminpants** [comment]
SAME

**Comment by LautaroL20** [comment]
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.

Issue was transfered to the items page: https://github.com/BEEmod/BEE2-items/issues/2925
