### ISSUE TITLE
OSX panes jump around when moving main window.

### ISSUE THREAD

**Issue by TeamSpen210** [BEEmod/BEE2.4#99]

**Comment by LautaroL20** [comment]
Mac support is no longer in the works, if you want to keep using Bee2.4 you will have to migrate to Windows 7-10

**Comment by TeamSpen210** [comment]
Not true, I just need to get back to it.

**Comment by LautaroL20** [comment]
Well, that was actually what you, or one of your collaborators said on Discord...

**Comment by Luke18033** [comment]
Is this still an issue? I don't remember this happening last time I used the Mac version.

**Comment by LautaroL20** [comment]
Since Beemod no longer gives support to Mac systems anymore, leaving this issue open is useless.
