### ISSUE TITLE
PRL30 BUG - Beemod is not displaying the correct preview images for the entrances & exits of the P1 style in the interface...

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2.4#993]
Beemod is not displaying the correct preview images for the entrances & exits of the P1 style in the interface... 

![image](https://user-images.githubusercontent.com/37309250/46478787-b1c3a180-c7bb-11e8-93c0-f93a84627a2c.png)

**Comment by HugoBDesigner** [comment]
I should have probably put my issue here rather than the Items repository...
