### ISSUE TITLE
Old Aperture Physics Repulsion Field Appearance PR:30 

### ISSUE THREAD

**Issue by King0191** [BEEmod/BEE2.4#995]
![20181004161534_1](https://user-images.githubusercontent.com/37309250/46501009-3d582500-c7f2-11e8-8e75-77a4d86afb33.jpg)
It appears that this was not updated for PR.30

**Comment by LautaroL20** [comment]
Could you please specify what is the problem on the field?

**Comment by King0191** [comment]
The texture is not updated to the new one to make it grid-like

**Comment by King0191** [comment]
Oh crap I just realized this was the wrong repository

**Comment by LautaroL20** [comment]
> King0191 said: "The texture is not updated to the new one to make it grid-like."

Aren´t you getting confused with the Force Deflection Field that act similarly to gratings, but that can be turned off? Because the Physics Repulsion Field which you are reporting, players can walk thru it.

**Comment by LautaroL20** [comment]
This post was moved to the item´s section: https://github.com/BEEmod/BEE2-items/issues/2826

**Comment by ZombiePwner1** [comment]
@LautaroL20 Hey wheels let's duel on TF2.
