### ISSUE TITLE
"vbsp_styles: No screenshot was found. Test your chamber before you publish."

### ISSUE THREAD

**Issue by FailureSnowy** [BEEmod/BEE2.4#996]
CDynamicFunction: Loading library 'Kernel32.dll' (763C0000)
CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77C57930

(Dashes here)
Running command: cd "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin"
(Dashes here)

(Dashes here)
Running command: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp.exe" -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\fizztestone"
(Dashes here)

vbsp_styles: Starting style Changer VBSP hook.
vbsp_styles: Elevators (hold ctrl): False
vbsp_styles: commandline: " -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2""
vbsp_styles: filename: "c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\fizztestone"
vbsp_styles: game: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2"
vbsp_styles: limit: -1
vbsp_styles: -game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\fizztestone"
vbsp_styles: Launching and waiting for "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" with commandline "-game "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2" "c:\program files (x86)\steam\steamapps\common\portal 2\sdk_content\maps\fizztestone""
BEE2: Fatal error - saved as _original file.
vbsp_styles: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" finished.
vbsp_styles: Packing because RunBspZip is set to 1 in editoritems.txt
vbsp_styles: Making C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\puzzles\76561198169437299\untitled.jpg writable
vbsp_styles: No screenshot was found. Test your chamber before you publish.

EDIT: Replaced the other one with the BeeMOD 2.4 vbsp.exe (same with a renamed vbsp_original.exe), and have gotten the deadly "VBSP Failed!" Help, again?

Version: BEEMod 2.2.5 Alpha
Compile Type: Full, Both (Tested with normal run as well)
Issue: Every time I run the map in Hammer, I get this log. I'd change it to vbsp_original.exe or vbsp_styles.exe, but the first is broken and the second gives me the same compile log.
Windows Version: 10
Computer: DELL Inspiron 15 7000 Gaming Laptop

Another issue with the same BeeMOD version, when I try to test a Puzzle Maker test, it gives me an unnamed error. Upon consulting the console, I'm given, in red test, "No Exit Room!" Any suggestions?

=Unrelated=
-I was also wondering about a new style for BeeMOD 2.4? One that I made, and would test, have it worked...

**Comment by TeamSpen210** [comment]
Don't mix and match compilers, BEE versions, map versions and Hammer edited maps. It's going to break all sorts of stuff.
