### ISSUE TITLE
Paint Fizzler cause build-error

### ISSUE THREAD

**Issue by Flo2912** [BEEmod/BEE2.4#997]
So, I've updatet to 2.4pre30 and now the Paint-Fizzler doesn't work any more, it gives out a build-error after the first of the three loading-rows is almost completed. Even downgrading back to Pre29 by deleting pre30 and reinstalling pre29 including the item packages wasn't able to solve the problme and I'm currently building a Map wich makes haviely use of it :c
[Edit] Turns out I didn#t reinstall pre29 properly. The issue still exists on Pre30 througth.

**Comment by ZombiePwner1** [comment]
@Flo2912 Open up the console and give us the log so we can see what the error is.

**Comment by Flo2912** [comment]
The strange is: I reinstalled pre30 to do now, but now it works fine. So either i did something wrong on my first try to install pre30 or i did something wrong this time (I'm not sure if i've the updated grid-Like fizzler textures since I see now difference) but I'm not able to pull of the error again o.o

**Comment by ZombiePwner1** [comment]
In this case this is closed.
